google/blockly

core/field.js

As a partial resolution for #17, I'm proposing that iOS touch events not be ignored for versions of iOS known to not exhibit the bug where a bogus event is generated after alert()/prompt() calls.  Unfortunately, I can only test down to iOS 7.1.2, but until I get an iOS 6 device this will at least fix #17 on some devices (without breaking it on others).

Don't ignore touch events on iOS 7.1.2 or later.

---

blocks/logic.js

if you place a number in an input the other input changes it's type to number as well.
When you remove all inputs it reverts back to allowing any input type.
I really don't like the way this is done because there will be a listener added for each block of this type and it has to check all input connections. It would be preferable if the framework provided a call back when a connection was made or unmade to an input and provided the changed input as a parameter, as this would simplify the code quite considerably.
I also realize I could do this with a single listener that iterates all blocks and calls a method on the block, but that is basically the same code as here.

Update logic block so it is reactive to the input attached to it.

---

blocks/logic.js

Previously it was always bumping the first block added
even if you are putting the new block over the first block, so it
bumped the new block as well.

Fix the logic block to bump the correct block.

---

core/blockly.js

When adding input elements that have a type other than 'text', Blockly takes over the keyboard control, preventing the backspace key from being used.

Fixed issue with calculating input focus on different input types

---

blocks/procedures.js

Mutated procedure call blocks are not presented correctly when dragged into the workspace. Steps to reproduce;
1. Create a procedure definition
2. Add arguments
3. Drag in the procedure call block into the main workspace
4. The block appears to have no arguments

Fixed issue with mutated procedure call blocks

---

core/blockly.js

IE11 with the developer tools open will still throw an exception on this line of code, so remove it as it is also executed and caught in the setTimeout.
If for some reason this line should be executed twice, then the first one should also be wrapped in a try/catch statement.

IE deselect exception fix.

---

i18n/create_messages.py

Instead of a hard to handle UnicodeEncodeError exception, check the keys and
print a human readable error. Turn more format strings into utf-8 to avoid the
exception.
Fixes #116 
Example output:
These keys in de.json contain non ascii characters: VARIABLES_ĐEFAULT_NAME
These extra keys appeared in de.json: VARIABLES_ĐEFAULT_NAME
Created ./js/de.js.

Handle non ascii characters in keys with an error.

---

core/workspace_svg.js

In the current situation, when a block is pasted it does not take in consideration if it is close enough to connect with another block. 
This can be confusing in cases where it might erroneously look as if the blocks are "physically connected". For example, if a block already connected is cut and pasted, it will be placed in exactly the same position, visually appearing to be connected.
This pull request offsets the block until it is not within connection range to any neighbouring blocks.

Offset pasted block if in range of a snap connection.

---

core/block.js
core/connection.js
core/field.js
core/field_dropdown.js
core/input.js

Pull request to address: #124
I've added a number of type docs to publicly accessible fields. The types are nice to grok faster (whether public or private). Also I'm looking at creating a typescript d.ts file for Blockly. This information will help in that process as well.

adding missing type documentation to public fields

---

demos/blockfactory/factory.js

Another minuscule update. In this case I noticed that on the block factory when the "manual edit" option is selected any drop down menu, focused input, etch keeps their state and stay on top of the dark overlay.

Block factory: close workspace drop downs and unfocus selections on manual edit.

---

core/block_svg.js
core/warning.js

I've encountered a situation where a block could receive warnings from different portions of my application, so extending `warning` seemed like a cleaner solution than locally adding and removing to the warning string. It seems like a feature that other people might find useful too.
A single warning icon is kept, and all the warnings are combined in the same bubble. The extra id parameter for `setWarningText() ` is optional, and therefore the current implementation will still work with the new:
```javascript
block.setWarningText('warning text');
block.setWarningText('warning about something', 'something');  // Adds to the original warning
block.setWarningText(null, 'something'); // removes only previous text
block.setWarningText(null);              // removes all warning texts
```
As it …

setWarningText can now take optional ID to maintain multiple warnings.

---

core/css.js
core/field_dropdown.js
core/widgetdiv.js

The current field dropdown is anchored to a maximum top position within the browser viewport. However the total height is dependent on the number of items and can get clipped, or forces an expansion of the page height.
You can see an example here: https://blockly-demo.appspot.com/static/demos/code/index.html#dnojq9
If the window viewport height is less than 600px it clips the content (in this case it becomes inaccessible), and if done in a blockly implementation with an expandable body it will trigger the page scrollbars.
This update sets the maximum height of the dropdown menu to be the viewport height and triggers the scrollbar in the menu if there is content overflow
Because the widgetdiv is changed to achieve this (it is given a height, while still having a width of 0) I checked the …

Contain the height of the field dropdown to the window viewport height.

---

demos/plane/README.txt

A rather insignificant change, feel free to reject it.
On Windows, copying and pasting the readme file command causes the generated files to end up in a folder named `'generated` and adds the other `'` to all the js files. I did a quick sanity check in Linux and the double quotes work as expected.

Change plane demo readme cli quotation marks for better compatibility.

---

.gitignore
.jshintignore
msg/messages.js
package.json

To use this linter, make sure npm is installed and execute the following
commands inside the main folder.
1.) Only once to update the package "npm install"
2.) To run the linter "npm run lint"
This would make it easier to clean up some of the code.

Add basic lint options for npm

---

core/field_image.js

I'm not quite sure why it was originally added, but with the new zooming feature the overall width of the image area has been increased:
I had a quick check on Firefox, Chrome, and IE11, including using different image sizes in the BlocklyFactory, and it seems to be working as expected with this removal.

Remove additional height to the FieldImage size.

---

core/field.js
core/field_textinput.js

In IE11, getBBox returns a read-only SVGRect, and throws the NO_MODIFICATION_ALLOWED_ERR exception when trying to edit its attributes.
As this read-only option is left to the browser by design, it seems better to always create a new object instead of doing it only on a catch statement.
https://developer.mozilla.org/en/docs/Web/API/SVGRect

Update getScaledBBox_ to return new object to fix issue in IE.

---

core/zoom_controls.js

IE seems to be ignoring the clippath of the zoom controls. This causes the zoom out button to lay on top of the other two, and therefore blocking their access. Reverting their injection order into the DOM at least allows the use of all the controls.
This is more of a temporal fix until somebody can start looking into the root of the problem, as I probably won't be able to for a little while, so feel free to close the pull request if you'd prefer to wait for a real solution.

Revert DOM injection order of the zoom control images.

---

core/blockly.js

This fixes issue #161, pinch gestures cause errors in console.
There is some difference of opinion on whether this error should be avoided since there is currently work going on for zooming. I propose we include this 3 line change now to keep the code in good shape at all times. When folks work on the pinch gesture, they will see it and can take it out.

fix: https://github.com/google/blockly/issues/161

---

core/inject.js

In the current implementation, if the toolbox XML is already converted to a DOM structure (say, by running the XML string through `Blockly.Xml.textToDom()`) before it is inputted into the Blockly injection, it will __silently__ fail in IE and work in Chrome/Firefox.
The main reason should be clear enough in the patch, the silently part is due to `outerHTML` being undefined, which in turn sets `hasCategories` to `false` in `Blockly.parseOptions_()`.
The `else if` statement was added only to safeguard against non-DOM objects, but could be removed so that any invalid object would trigger an error later on, which would clearly identify the issue.

Allow XML DOM nodes to be injected as toolbox in IE

---

core/block_svg.js
core/flyout.js
core/toolbox.js
core/trashcan.js
core/workspace_svg.js

to avoid getting it for every mouse move event. The delete areas
won't change while the user is dragging blocks around.
Also switch calculations for delete area inclusion to be done in
client coordinates so we don't have to convert to svg coordinates on
every mouse move event.
This should speed up dragging blocks a bunch.

Cache delete area rectangle bounds in the on mouse down event

---

core/workspace_svg.js

On a touch device with multitouch support, multiple `touchStart` events can be fired together. This causes multiple calls to `Blockly.WorkspaceSvg.prototype.onMouseDown_` event handler.
```
if ('mouseup' in Blockly.bindEvent_.TOUCH_MAP) {
Blockly.onTouchUpWrapper_ =
Blockly.bindEvent_(document, 'mouseup', null, Blockly.onMouseUp_);
}
Blockly.onMouseMoveWrapper_ =
Blockly.bindEvent_(document, 'mousemove', null, Blockly.onMouseMove_);
```
This code binds multiple events to the document element but only the last call actually registers the event handler wrapper, which will consequently be called in the global `Blockly.onMouseUp_` handler.
This can cause event handlers for `mouseMove` and `mouseDown` linger in the `document` node, causing other elements on the DOM tree to disfunction.
The fix …

Fix for issue https://github.com/google/blockly/issues/210

---

build.py

Very simple change to add an extra check for the node.js indentification.
The reason this is needed is because with things like Electron, I have `module` exposed to the pages rendered in the chrome engine, so even if I am using closure in the front end, the current implementation assumes it is being executed in the node.js server side.
This stack overflow question suggests this additional check is relatively reliable:
http://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js
Could somebody running closure from within Node confirm this does not break their implementation?

Update build.py with more robust nodejs identification

---

core/block_svg.js
core/blockly.js
core/workspace_svg.js

with a manual calculation. getBBox() can cause the browser to
re-layout the whole page and we have much of the information
(e.g. individual block height and width) we need already cached.
Note that getBoundingRectangle's calculation is slightly different
than the one returned by getBBox.  It is off by 3 in the y direction
due to how one of the curves is drawn. This new calculation is
technically more accurate.

Replace the call to getBBox() in getMainWorkspaceMetrics

---

generators/lua.js
generators/lua/lists.js

This meant that variables could be called _, conflicting with use in Lua
as a dummy variable, and in particular with scrubNakedValue.
I've also made some style fixes to Blockly.Lua.lists.

Add missing comma to Lua reserved words

---

core/block_svg.js
core/blockly.js
core/css.js
core/flyout.js
core/scrollbar.js
core/toolbox.js
core/utils.js
core/workspace_svg.js
demos/blockfactory/factory.js

css to mark text as unselectable instead.  I can't prove this is
significantly faster with numbers since the call to setup the time out
costs ~.1ms and the call when the timer fires is ~.05.  This happens on almost
every mouse event though.  Plus, it seems to remove a flicker of highlighting when
frames are skipped and keeps scrolling via the scrollbar from highlighting.

Remove Blockly.removeAllRanges and replace it with calls to add/remove

---

core/workspace.js

Previously if a workspace.clear() was executed whilst a field was being edited then the following errors would appear in the console and the blockly workspace would become unresponsive.
Uncaught TypeError: Cannot read property 'removeChangeListener' of null(anonymous function) @       blockly_compressed.js:19071Blockly.WidgetDiv.hide @ blockly_compressed.js:20609Blockly.WidgetDiv.hideIfOwner @     blockly_compressed.js:20620Blockly.FieldTextInput.dispose @ blockly_compressed.js:18961Blockly.Input.dispose @     blockly_compressed.js:15786Blockly.Block.dispose @ blockly_compressed.js:17275Blockly.BlockSvg.dispose @     blockly_compressed.js:18327Blockly.Block.dispose @ blockly_compressed.js:17272Blockly.BlockSvg.dispose @     blockly_compressed.js:18327Blockly.Block.dispose @ …

Clearing the workspace now works even if a field is being edited

---

core/toolbox.js

This adds an ```id``` option to toolbox categories, which allows the id of the category to be specified. This in turn allows a known element id which can be styled.
Without this, the tree uses an incrementing number, which is potentially usable, but in a single page app the number doesn't get reset, so the number isn't fixed each time blockly is displayed - making it useless.
EG:
```xml
<category name="Logic" id="toolbox-blue">
```

Add option to set id on toolbox

---

core/block_render_svg.js
core/block_svg.js
core/blockly.js
core/flyout.js
core/inject.js
core/toolbox.js
core/workspace_svg.js
core/xml.js
demos/code/code.js
demos/graph/index.html

This splits the workspace resizing into two pieces:
1. When the blockly div actually changes sizes (e.g. a window resize)
2. When the contents of the workspace change and we need to adjust scrollbars (e.g. new blocks are added)
@NeilFraser I removed asyncSvgResize, but mostly because I didn't see the value as much with this split, though I don't think I knew the motivations for adding it.  Let me know if you want it back.  I'm guessing most developers haven't started using it at this point since it is so recent. If it stays gone, there is some replacement needed in scratchblocks, but it doesn't look that difficult.
@rachel-fenichel Your eyes would be appreciated on this one too.

Change the blockly workspace resizing strategy.

---

core/connection.js

REASON_MUST_DISCONNECT was removed by a refactor in 2a1ffa1.

Remove reference to undefined variable

---

tests/playground.html

Probably broken in 266e2ffa9a017d21d7ca2f151730d6ecfcecf173.
Let me know if you'd prefer for the airstrike to be from the full set of blocks all the time instead of the selected toolbox.  Either way, "toolbox" doesn't exist as id anymore.

Fix airstrike by grabbing the correct toolbox element.

---

generators/javascript.js

Adding setting to allow for switching between zero and one based indexing for Blockly Blocks such that the generated code will use this flag to determine whether one based or zero based indexing should be used. One based indexing is enabled by default.

Add indexing setting for JavaScript Generation

---

core/block_svg.js

This fixes #420 but and it also fixes some other similar problems
with copy/paste and other users of moveBy.

Trigger a contents resize in block's moveBy.

---

core/block_svg.js

from the context menu (or anywhere really) causes the workspace to
recalculate its size.
Fixes #432

Call svgResizeContents from block_svg's dipose so that deleting blocks

---

core/events.js

Prevents 'blockId': undefined in events.
Consider the UI category event.

Feature event null blockid

---

core/flyout.js
core/scrollbar.js

Notably, the margins in the flyout should not change size with zoom, and horizontal RTL coordinates were quite broken.
Horizontal RTL will still start with blocks left-aligned if they do not fill the screen width, but no longer pushes blocks off-screen entirely.

Fix problems with flyout coordinates

---

core/field.js
core/flyout.js
core/icon.js
core/workspace_svg.js

This includes both block drags and workspace scrolls and fixes #404. I
used isDragging rather than checking the origin of click so that it can
easily be extended to the case where the flyout is scrolled by dragging
a block, a la LLK/scratch-blocks#206.

Ignore mouseup at end of drag with isDragging

---

blocks/procedures.js
core/block.js
core/block_svg.js
core/contextmenu.js
core/flyout.js
core/workspace_svg.js
core/xml.js

This prevents a recoverable exception permanently disabling events. This could be caused by calling domToWorkspace() to load a program containing an invalid block type (eg because it was saved by an old version of Blockly).
To fix that case, it only needs to be added to xml.js:domToBlock. I added it everywhere else out of caution - however, in some places, it's not necessarily sensible, as there's other cleanup without which Blockly wouldn't work properly. @NeilFraser, do you think it's sensible to add it everywhere, or only where we predict an exception happening?

Re-enable events even when an exception is thrown

---

core/block_svg.js
core/flyout.js

- allows scrolling by dragging a block up and down
- dragging a block towards the workspace creates it
- dragging a block any direction in a non-scrollable flyout creates it
- dragging a shadow block works properly
- clicks on fields in non-closeable flyouts always open editors
- clicks in closeable flyouts create the block but don't open editors
Fixes #385 and fixes #405.

Revise handling of mouse events on flyout blocks

---

core/workspace_svg.js

This comment made sense [before multiple workspace support](https://github.com/google/blockly/blob/67140282a08b10d0beb8d842a2dc35beadc5d5e0/core/blockly.js#L297), where it was near a (Blockly.readOnly || isTargetSvg) check. Now, this logic is implemented in BlockSvg.onMouseDown_() instead.

Remove out-of-date comment

---

core/blockly.js
core/constants.js
core/flyout.js
core/workspace_svg.js

This fixes #473 by differentiating between a touch on an unmovable block and using it to drag the workspace.
@NeilFraser, would you prefer to remove the `isScrolling` field? I don't know how important it is to keep backwards compatibility on public fields.

Record whether the workspace has been dragged

---

blocks/loops.js
blocks/procedures.js
blocks/variables.js
core/events.js
core/field_textinput.js
core/mutator.js
core/procedures.js
core/toolbox.js
core/tooltip.js
core/variables.js
core/widgetdiv.js
core/xml.js

Unless they could be converted to use goog.dom.TagName, in which case do
that. createDom is going to require goog.dom.TagName member as the
tagName parameter. This change prepares for that.
This PR is currently **just for review** - the online Closure Compiler doesn't currently support createUntypedDom. I'll check with @vrana to find out when this is expected.
Additionally, this will break Blockly in "dev mode" if the checkout of closure-library has not been updated since the 1st of July (when createUntypedDom was added) with an error about that in the console. Is there anything we can/should do to avoid confusing people with this? Maybe add a check somewhere as below, then remove it in a month or so?
if (!goog.dom.createUntypedDom) {
window.alert("Please update your checkout of …

Convert createDom calls to createUntypedDom

---

core/flyout.js
core/workspace_svg.js

We also have to record startFlyout_ on background scrolls - before
dragMode_ wasn't being reset by terminateDrag() for background scrolls,
which would suppress clicks from that point on.
Fixes #476.

Check flyout in isDragging()

---

core/flyout.js

I've chosen to keep these as static members of Flyout, similar to BlockSvg.onMouse*Wrapper_, which are also used by terminateDrag to reset state.
@rachel-fenichel, is this what you were thinking of? Let me know if the docs could be clearer.

Add JSDoc for flyout drag state variables

---

blocks/loops.js
blocks/procedures.js
blocks/variables.js
core/events.js
core/field_textinput.js
core/mutator.js
core/procedures.js
core/toolbox.js
core/tooltip.js
core/variables.js
core/widgetdiv.js
core/xml.js

Reverts google/blockly#481
I believe the compiler might not handle these yet - the demos that use blockly_compressed.js are mostly broken even when I try rebuilding them.

Revert "Convert createDom calls to createUntypedDom"

---

demos/blockfactory/index.html

In the dropdown in which you select block definition language format in the Exporter & Block Factory, generate JSON block definition by default.
"The JSON format is cross-platform so that the same code may be used to define blocks on web, Android, and iOS. Additionally, the JSON format is designed to simplify the internationalization process when developing for languages with different word orderings. The JSON format is the preferred method of defining blocks" ([Blockly Dev Reference](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#json_format_versus_javascript_api)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/517)

Block Factory: set JSON to default language format for block definitions

---

core/toolbox.js

A follow-up on #460.
`event.keyCode` is re-mapped in `Blockly.Toolbox.TreeNode.prototype.onKeyDown` so that arrow keys work properly in horizontal layout. The original `onKeyDown` handler is then called with this modified event.

Scroll toolbox with LEFT/RIGHT in horizontalLayout

---

tests/jsunit/xml_test.js

This would have caught a recent [Scratch Blocks regression](https://github.com/LLK/scratch-blocks/pull/557) where domToWorkspace failed unless given a WorkspaceSvg instance.

Add a test for domToWorkspace

---

core/flyout.js
core/toolbox.js

Fixes #463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/531)

Parse separators in xml in always-open flyouts

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_exporter_tools.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html

- refactored the way tabs are implemented to be flexible for adding tabs.
Workspace Factory:
- added tab for workspace factory
- added workspace factory content div (integration of workspace factory content will be done in next CL)
Exporter: 
- added button for add all blocks used in toolbox/pre-loaded workspace.  (button handler to be implemented)
- expanded export settings menu
- expanded export function within BlockExporterTools to lay groundwork for workspace factory integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/quachtina96/blockly/26)

Blockly Factory: Foundation for Integrating Workspace Factory

---

demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory.js

Deleting from and clearing Block Library now visibly affect the Block Factory workspace by showing the starter block as seen below. This makes the Block Factory/Block Library experience less confusing since the Block Factory better reflects the state of the Block Library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/548)

Blockly Factory: Show Starter Block on Delete from and Clearing of Block Library

---

demos/blocklyfactory/workspacefactory/index.html
demos/blocklyfactory/workspacefactory/style.css
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_model.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Adds tabs to the top of the toolbox workspace to switch between toolbox and workspace editing to allow the user to also edit blocks pre-loaded on to the workspace. Supports importing and exporting. Already reviewed by picklesrus and vicng (https://reviewable.io/reviews/evd2014/blockly/36 and https://reviewable.io/reviews/evd2014/blockly/37).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/546)

Blockly Factory: Add Pre-loaded blocks tab with import/export to workspace factory

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/index.html

Previously, there were download buttons in the Block Factory Tab next to the block's Language Code and Generator Stub. Now that there is the Exporter, we would like to keep block definition and generator stub export there. This also simplifies the UI.
In addition, there is no longer an alert every time Blockly Factory is loaded with an empty block library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/547)

Blockly Factory: Removing Old Download Buttons and Alert

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_exporter_tools.js
demos/blocklyfactory/block_exporter_view.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory.js
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_generator.js

I've pulled functions out of factory.js (BlockFactory) and into factory_utils.js (FactoryUtils), to share useful generator code between the different apps within Blockly Factory. 
- removed console.log calls
- removed the functions in factory.js related to downloading the single blocks block def and generator stub.
- pulled code generating functionality used both in and outside of block factory out of factory.js and into new factory_utils.js file
- factory_utils.js houses code generation functions used for the block factory, workspace factory, and exporter.
-  require FactoryUtils and call functions from it.
-  require FactoryUtils and call functions from it.
-  moved getDefinedBlock out to FactoryUtils so that WFactoryGenerator may use it for generating a category from imported block …

Blockly Factory: Factory Utils

---

core/block.js
core/block_svg.js
core/mutator.js
core/workspace_svg.js

Add a isMutator member similar to isFlyout to workspace_svg so it knows whether
it is mutator or not. Allow blocks to access that property so that they can recalculate
coordinates appropriately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/540)

Fix for #521.

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html

UI changes: 
- Changed the style of the navigation bar for the 3 tabs
- Moved the help button to the top of the page so that it will be visible for any tab selected
- Unified buttons for the Block Selector in the Exporter into a dropdown. 
- Changed the layout of the Exporter to clearly be 3 columns (Block selector, Export settings, and Preview workspace)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/549)

Blockly Factory: UI for Navigation Bar, Help Button, Exporter

---

demos/blocklyfactory/factory.js

When a user is creating a block, they have the freedom to specify a type for the block. Having overlapping block types leads to unexpected behavior since one definition will overwrite the other. Block Factory now warns the user in the case that standard blocks may be overwritten.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/550)

Blockly Factory: Warn if Using Standard Block Name

---

demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_model.js

Added method getAllUsedBlockTypes to Workspace Factory model. CL has LGTM from @vicng and @quachtina96 (https://reviewable.io/reviews/evd2014/blockly/42).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/554)

Blockly Factory: getAllUsedBlockTypes in Workspace Factory Model

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/factory.js
demos/blocklyfactory/workspacefactory/index.html
demos/blocklyfactory/workspacefactory/standard_categories.js
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_model.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Rename FactoryController to WorkspaceFactoryController, FactoryModel to WorkspaceFactoryModel, and FactoryView to WorkspaceFactoryView to distinguish between Block Factory and Workspace Factory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/553)

Blockly Factory: Rename WorkspaceFactory Classes

---

demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_exporter_tools.js
demos/blocklyfactory/block_exporter_view.js
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js

In order to allow users to add custom blocks to their toolbox and workspace configurations within Workspace Factory, we generate the xml for those categories.
- can generate category xml from Block Library (BlockExporterTools)
- can generate category xml from imported block definitions (Workspace Factory Generator)
- added helper functions for category xml generation to FactoryUtils
- can get Block Library category xml through BlockExporterController
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/552)

Blockly Factory: Generate Category Xml

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/style.css
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Updated the Workspace Factory UI and initialization in Blockly Factory to reflect changes made to Workspace Factory. This makes the workspace factory tab in blockly factory behave the same as the page in workspacefactory/index.html. Changes mostly in index.html and wfactory_init.js, but also minor changes in app_controller.js and wfactory_controller.js. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/562)

Blockly Factory: Update Workspace Factory Tab

---

demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js

Increased shadow block validation in workspace factory: 
- When converting a block to a shadow block, all of its children are also converted to shadow blocks (to help users avoid invalid state)
- Provide warning message when a block with a variable field is made a shadow block.
- Provide warning message when a normal block is nested inside a shadow block. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/563)

Blockly Factory: Shadow Block Validation in Workspace Factory

---

demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_init.js

Allows the user to import blocks into workspace factory from a file containing block definitions in JSON or Javascript. Automatically generates a category for the imported blocks and adds it to the toolbox workspace so that the user can use these blocks in their toolbox or pre-loaded blocks. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/566)

Blockly Factory: Import Blocks to Workspace Factory

---

demos/blocklyfactory/factory.js

Block Factory adds warning text when a user's custom block shares the same type as a standard block. This pull requests removes the warning text after the user addresses the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/567)

Blockly Factory: Warn ONLY if Using Standard Block Name

---

core/field_textinput.js
core/toolbox.js
core/tooltip.js
core/widgetdiv.js

in createDom calls only. This improves the type information of the
created objects.
The Closure team have changed plans so createUntypedDom is no longer necessary. This change (using TagName) is recommended but not necessary.

Convert string tag name to goog.dom.TagName

---

.npmrc

So that `npm install` etc. use npmjs registry.

Setting up npm registry for this repo.

---

demos/blocklyfactory/index.html
demos/blocklyfactory/standard_categories.js
demos/blocklyfactory/workspacefactory/wfactory_controller.js

Made StandardCategories a separate namespace outside of WorkspaceFactoryController and moved it into the general BlocklyFactory folder so that it can be used outside of Workspace Factory. Also added a coreBlockTypes array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/572)

Blockly Factory: Standard Categories

---

demos/blocklyfactory/block_exporter_view.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/570)

Block Factory: Nit UI Changes

---

demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js

Split import options into 2 buttons: "Import Custom Blocks" to import block definitions from a file and load them into a toolbox category in the editing workspace, and "Load to Edit" to load toolbox or pre-loaded block XML into the editing workspace. Also changed the file inputs to only accept certain types of files, and updated the block exporter to be consistent with the import types used in workspace factory. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/578)

Blockly Factory: Workspace Factory Import Buttons

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_exporter_tools.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/factory.js
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/index.html

The preview accordingly shows that these options are selected.
- added divs and styling for the exporter preview
- added change listeners for the export settings to the app controller
- added functions for updating the preview in exporter controller
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/573)

Blockly Factory: Exporter Preview Code

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Made small UI changes to workspace factory including: 
- Changing help text for the "toolbox" and "workspace" tabs and style of tabs so that they appear separate from the workspace toolbox.
- Changing the "Clear Toolbox" button to "Clear" and having it clear all state (for both tabs instead of just the toolbox).
- Making options scrollable with a minimum height, and change text of "Standard Options" button to "Reset Options".
- Adding a border around the preview workspace to make it appear separate from the editing area. Changing help text for preview workspace in an attempt to clarify it's relationship to the custom workspace being created.
- Removed "Print Toolbox" button mainly used for debugging. 
- Fixed bug with event listeners for arrow keys so that categories can only be moved up …

Blockly Factory: Workspace Factory UI

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_exporter_tools.js
demos/blocklyfactory/block_exporter_view.js
demos/blocklyfactory/block_option.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html

- created BlockOption class 
- added function to generate the selector from the block library in ExporterTools
- changed BlockExporterController & BlockExporterView to accommodate use of BlockOption
- added styles for BlockOption and selector
- moved resize out of AppController init function and recenter block options in exporter upon window resize.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/579)

Blockly Factory: New Selector UI

---

demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_model.js

Bug fix for clearing, changes to clearing in the model and update preview. Update toolbox every time update preview, update the selected XML, and clear the list of shadow blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/582)

Blockly Factory: Bug Fix for Clear

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js

Before save:
After save:
Fixed bug where a block type that is capitalized in the exported xml gets imported as a block of a different type: 'color_Sea' is different from 'color_sea'. To match the generated code, block types are always saved as lowercase in the library. With this CL, the same is done for each block upon importing a block library.

Blockly Factory: Clean Up Workspace on Save Block, Import Lowercase Types

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_exporter_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory.js
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/workspacefactory/wfactory_controller.js

- reference StandardCategories.coreBlockTypes in factory.js and blockexporter controller
- remove all abbreviations from function names

Blockly Factory: Use StandardCategories, No Abbreviations

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_model.js

Adds a warning to blocks that are not standard blocks, defined in the block library, or imported. These blocks can end up being added to the workspace factory editing area when XML is imported or when a block library block is used and then deleted. This helps the user know when their block definitions and workspace editing is out of sync, and helps the user understand why the block might not be properly rendered. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/581)

Blockly Factory: Warning for Undefined Blocks

---

core/flyout.js

This makes it easy for users to customise the spacing in the flyout,
without having to repeat the same value of "sep" for every block.
@rachel-fenichel, I wasn't sure how to handle the spacing after the button, so I made it the same as the other spacing. Let me know if you'd prefer something else. Here's what it looks like now:

Add GAP_X/Y to the flyout

---

demos/blockfactory/blocks.js
demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/block_library_view.js
demos/blocklyfactory/factory.js
demos/blocklyfactory/index.html

- disable blocks if they aren't connected to the factory_base block
- clear undo in the main workspace on load of each block
- changed 'Language Code' to 'Block Definition'
- changed 'math_foo' to 'block_type
- changed confirm messages to not reference 'OK'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/595)

Blockly Factory: Disable Disconnected Blocks, Nit UI, Bug fix

---

core/workspace_svg.js

Without this, dragMode_ is undefined until explicitly set through a use action.

Require constants in workspaceSvg, which uses them during initialization

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html

Makes the height of the workspaces in workspace factory resizable. Also improves the scrolling for the workspace factory options (before, it was possible for some options to sometimes get stuck underneath). Also hides Block Factory so that it can't be seen when the screen jumps down when selecting a color for a category. Also enables scrolling for workspace factory and the exporter if necessary (only needed if screen is very small).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/593)

Blockly Factory: Resize Workspaces in Workspace Factory

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory.js
demos/blocklyfactory/factory_utils.js

Alerts users when 
- they want to create a block and they've made changes to the block they are currently on.
- they want to switch from the block factory tab to a different tab, but they have unsaved changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/594)

Blockly Factory: Alert if Unsaved Changes in Block Factory

---

demos/blocklyfactory/factory.css
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Prompt the user to add a variables or functions category if they add a variables or functions block to their toolbox without having a variables or functions category in their toolbox already. Also allowed user to save their work from a single flyout in a new category not just when an empty category is created, but also when a standard category is loaded or when a separator is added. Also moved checks for variables field and procedure blocks to Factory Utils. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/589)

Blockly Factory: Prompt User to Add Variables/Functions Category

---

demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js

Changed UI for making a block a shadow block or not a shadow block. Instead of having an "Edit Block" dropdown that is disabled whenever the selected block cannot be made a shadow block or a block isn't selected, instead a "Add Shadow" or "Remove Shadow" button appears whenever a block is selected ("Add Shadow" if the block is not a shadow block, "Remove Shadow" if it is). The button is disabled if the block is not a shadow block and cannot legally become one. Only one button will ever be displayed at a time. 
Adding this button instead of a dropdown that is usually disabled makes it clearer what the button actually does, and by changing the text of the button instead of the content of the dropdown, it reduces the number of clicks for the user to figure out what the options are. Also, …

Blockly Factory: Shadow Block UI

---

demos/blocklyfactory/factory.css
demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_model.js
demos/blocklyfactory/workspacefactory/wfactory_view.js

Made suggested changes to inject options in Workspace Factory, including: 
- Putting read only at the top, and hiding the trashcan if read only is selected
- Having certain zoom attributes preselected so that zoom works when first selected
- Bug fix for zoom option not working in preview
- Indent suboptions (grid, zoom, maxBlocks)
- Create a checkbox for infinite blocks, and if it's not checked, show a number input field for max number of blocks (solves problem of Infinity not being a valid in a number input).
- Manually generated string for options object to solve problem of JSON stringify putting quotations around attributes. Also indents and uses line breaks correctly. 
- Open options help tab in new window (instead of taking the user to the link in the same window and making them lose …

Blockly Factory: Workspace Factory Options

---

demos/blocklyfactory/index.html
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js
demos/blocklyfactory/workspacefactory/wfactory_init.js
demos/blocklyfactory/workspacefactory/wfactory_model.js

Several changes to make sure that the user doesn't accidentally lose work while reducing the number of alerts they run into in a normal workflow. Also expanded exporting options to be exporting basic starter code that unifies the files you can export.
Changes made:
- Option to load the standard toolbox (all standard categories in order) in the '+' dropdown.
- Check with the user before clearing all work.
- Check with the user when importing a toolbox to make sure it's OK to delete their work.
- Check to make sure the user is not importing blocks that are already defined.
- Changed asking the user if they want to make a category for the blocks in their flyout (on creating their first category) to just adding a category with the  name "Category 1" and then adding their next list element …

Blockly Factory: Confirm Changes with User, Reduce Alerts, Generate Starter Code

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/block_library_view.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/factory.js
demos/blocklyfactory/factory_utils.js
demos/blocklyfactory/index.html

- The Block Library is now a dropdown with the Blockly Factory styling.
- The 'Create New Block' button is now housed in the Block Library dropdown.
- Based on the state of the user in Block Factory, the Save/Delete buttons for the Block Library update content and color to guide the user's actions.
- green buttons indicate user can save or update a saved block
- the red save button indicates that user cannot save the block  (but encourages user to click button to learn why)
The button turns green to indicate that they should save.
consistent button name on default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/603)

Blockly Factory: Enhanced Block Library UI

---

demos/blocklyfactory/workspacefactory/wfactory_controller.js

Close the toolbox workspace toolbox when updating the block library category in the toolbox so that the block library category is never out of sync with the blocks in the block library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/610)

Blockly Factory: Close Toolbox when Updating Block Library

---

demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory.css
demos/blocklyfactory/factory_utils.js

- fix bug where repeated alerts for unsaved changes popped up upon selecting different block from library dropdown (due to assignment of multiple of the same click handler). 
- made the block lib scrollable when it reaches a max height in CSS

Blockly Factory: Block Library bug fix & scroll

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/index.html

Blockly Factory currently doesn't support automatic saving of work. In order to prevent users from unwittingly losing their work by leaving the page, I've added some alerts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/607)

Blockly Factory: Warn user when leaving/refreshing page

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/block_library_controller.js
demos/blocklyfactory/factory_utils.js

The Factory Utils function warnIfUnsavedChanges contained code copied from AppController that referenced self.blockLibraryController. The code worked properly despite self not being defined in the function because of an accidental global self defined. 
Changes made:
- made the global self local to the App Controller init function
- make the block library controller a parameter in the Factory Utils function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/616)

Blockly Factory: Global Self Bug Fix  

---

demos/blocklyfactory/app_controller.js
demos/blocklyfactory/workspacefactory/wfactory_controller.js
demos/blocklyfactory/workspacefactory/wfactory_init.js

Extend check for unsaved changes in Blockly Factory to check for unsaved changes in Workspace Factory (this is especially useful because Workspace Factory doesn't use local or session storage). Also removed blocks from the category name for imported blocks (shortens the name so that it fits more easily on the screen), and fixed bug when adding a variables or functions category from a prompt when in workspace mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/617)

Blockly Factory: Check for Unsaved Changes in Workspace Factory

---

demos/blockfactory/blocks.js

spawn shadow blocks for output types when the dropdown to
add/change/remove output types is changed.  This way, we won't overwrite
existing blocks when loading from xml.

Fix #636 by changing the factory_base block definition to only

---

core/xml.js
demos/blocklyfactory/workspacefactory/wfactory_generator.js

add option to skip exporting block ids in XML, and use it in the workspace factory

---

core/toolbox.js

Fix bugs pointed by @NeilFraser in #441:
>  A divider eats the focus. Right and left are reversed in RTL.

Fix toolbox scrolling in horizontal layout

---

core/workspace.js

I was seeing duplicated names in my variables list. Here's a minimal workflow to reproduce the issue:
1. Create a variable named `x`.
2. Create a variable named `y`.
3. Drag two setters to the canvas, one for `x` and one for `y`.
4. Rename `x` to `y`.
5. Find two `y`s listed in the variables flyout and the dropdown menus.
The cause of the trouble seems to be the rename case where both identifiers already exist. The old identifier is properly deleted, but then there's this reassignment:
// The case might have changed.
this.variableList[newVariableIndex] = newName;
`newVariableIndex` is stale after the `splice`. This line will likely clobber another variable or append a duplicate name. Best I can tell the two statements can just be swapped around.

Stops duplicating on rename of old ID to old ID.

---

blocks/logic.js
generators/dart/logic.js
generators/javascript/logic.js
generators/lua/logic.js
generators/php/logic.js
generators/python/logic.js
msg/messages.js
tests/playground.html

Adding `controls_ifelse`, an if/else block that is loaded from JSON and does not use mutators.
This solves a pending problem on current Android & iOS implementations.
Added this block to the playground simple toolbox and all generators.
Tested across all languages using the playground and [this workspace XML](https://gist.github.com/AnmAtAnm/af905f5838110873e6a607593d9ef85d).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/722)

Adding controls_ifelse block

---

msg/messages.js

Clarify the translation comment for CONTROLS_IFELSE_TITLE, including parameter usage descriptions and more specific example link.

Translation comment for CONTROLS_IFELSE_TITLE

---

core/field.js
core/field_textinput.js

Existing text-editable fields don’t care (dropdown care, but are not
text-editable).  But a note picker needs to set its value to 60 if text
is set to ‘C4’.

When user edits text in a field, set text, not value.

---

demos/blockfactory/blocks.js
demos/blockfactory/factory.js
demos/blockfactory/factory_utils.js
demos/code/index.html

The colour input now automatically has a block attached to it.  HelpUrl and tooltip can now be set on the factory block and saved.

Update block factory to make setting colour, helpurl, and tooltip easier

---

core/workspace_svg.js

Before, touchpads would give "smoother" scrolling by delivering lots of
mousewheel events with small distance changes. Because the code only
looked at the sign of deltaY, ten 5px scrolls would zoom 10x more than
one 50px scroll.
This change makes zooming with a touchpad more like zooming with a
mousewheel. On my laptop, a full-scale zoom (fully out to fully in) was
about a 5mm finger movement before, and is now about 3cm.
Fixes #758.

Make zoom speed independent of event granularity

---

core/css.js
core/flyout.js
core/inject.js
core/mutator.js
core/scrollbar.js
core/toolbox.js
core/utils.js
core/workspace_svg.js

are siblings of the workpsace SVG.  This paves the way to make performance
improvements to workspace dragging.
Note that this is very close to what's in the develop-drag-surface-ws-drag branch.  Main difference is:
- Changed to using translate() instead of translate3d to position the flyout and scrollbars since it is more compatible cross browser and there isn't much of perf gain there anyway.  That means I had to alter the regex code a bit in getRelativeXY

Split the scrollbar and flyout out into their own SVG elements. They

---

core/generator.js

In creating a custom Blockly.Generator, these functions are defined in each individual language generator. Adding to prototype for discoverability and JSDocs.

Add Generator functions to prototype + JSDoc

---

core/flyout.js

Disable workspace resizing while loading the flyout from XML

---

generators/python.js

Change the Python codegen for string quoting to match the behaviour of what `repr` does for string objects in CPython.
```
$ python3
Python 3.5.0 (default, Sep 23 2015, 04:42:00)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(repr('hello'))
'hello'
>>> print(repr('hello "world"'))
'hello "world"'
>>> print(repr("hello 'world'"))
"hello 'world'"
>>> print(repr("\"hello\" 'world'"))
'"hello" \'world\''
>>> print(['hello', 'hello "world"', "hello 'world'", "\"hello\" 'world'"])
['hello', 'hello "world"', "hello 'world'", '"hello" \'world\'']
>>>
```
Using the same quoting approach has the advantage for students who are also learning Python that they see the same escaping behaviour in the code …

Change string quoting in Python codegen to match what `repr` does.

---

core/block_svg.js
core/constants.js
core/workspace_svg.js

-- Don't highlight as though you would connect to a block under the flyout.
-- Don't open the trash can if you're going to connect to a block instead.

Don't connect to blocks under the flyout.

---

blocks/logic.js
core/field_dropdown.js
core/utils.js
tests/jsunit/utils_test.js

Adds `Blockly.utils.replaceMessageReferences()` method to handle string replacement without interpolation tokens.  Effectively uses the same old code, now moved into `tokenizeInterpolation_()`, which takes a parseInterpolationTokens option.
Replaces the direct JavaScript references (not pure JSON, and thus not portable).
Demonstrating this behavior in the `logic_boolean` dropdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/818)

Adding support for string table lookups in dropdown field labels

---

core/block.js
core/workspace.js

Add an `allInputsFilled` method to `Block` and `Workspace` to test whether all trees in the block forest have all of their inputs filled. An optional argument controls whether or not shadow blocks are counted as being filled. Recommitting changes off `develop` instead of `master` as per discussion in PR #791.

Adds `allInputsFilled` methods to Block and Workspace.

---

blocks/colour.js
blocks/math.js
core/extensions.js
tests/jsunit/extensions_test.js

Replaces old colour block definitions with a Blockly.defineBlocksWithJsonArray(..) call. Generator unit tests continue to load and pass, signifying compatibility with prior block definitions.
Replaces extension 'math_number_tooltip' with the reusable 'parent_tooltip_when_inline' extension, also used by colour_picker. Includes tests.

JSON definitions for colour blocks

---

appengine/app.yaml

This eliminates 1274 unneeded files from being uploaded (40% of Closure) and should result in faster updates.

Reduce number of Closure files in App Engine upload.

---

core/inject.js

This is equivalent to https://github.com/LLK/scratch-blocks/pull/734

Use bindEvent_ instead of bindEventWithChecks_ for longStop

---

core/field_textinput.js

This will need to be cherry-picked to master and master will need to be rebuilt.
Fixes #839

Use setValue in fieldTextInput so that procedure renaming works

---

generators/python.js

Update the set of reserved words in Python to reflect the current state of the Python language (2.7 and 3.6). These are the union of 2.7 and 3.6.
The set of changes are purely additive, with 86 additions and zero updated or deletions:
```bash
$ diff -u \
<(git show upstream/develop:generators/python.js                    | awk '/^Blockly.Python.addReservedWords\(/{flag=1;next} /^\);$/{flag=0} flag' | tr -d ' ' | sed "/^\/\//d; s/^'//; s/'+\?$//" | tr ',' '\n' | sed '/^$/d' | sort) \
<(git show origin/update-python-reserved-words:generators/python.js | awk '/^Blockly.Python.addReservedWords\(/{flag=1;next} /^\);$/{flag=0} flag' | tr -d ' ' | sed "/^\/\//d; s/^'//; s/'+\?$//" | tr ',' '\n' | sed '/^$/d' | sort) \
| tail -n +3 | grep -o '^[+-]' | sort | uniq -c | sort -rn
86 +
$
```

Update the set of reserved words in Python

---

core/extensions.js

Remove use of Array.prototype.includes which is not implemented in IE or Edge < 14. Fixes google/blockly#876.

Remove IE/Edge-breaking use of Array.prototype.includes

---

core/block_drag_surface.js
core/flyout.js
core/scrollbar.js
core/utils.js
core/workspace_drag_surface_svg.js

Sets both the unprefixed version and the `-webkit-` prefixed version of the CSS `transform` property so that Blockly correctly renders in order browsers, such as Safari < 9 and iOS Safari < 9.2. 
For discussion of this issue, see https://groups.google.com/forum/#!topic/blockly/o3pERaRQhSg

Change CSS transforms to work with older browsers

---

accessible/tree.service.js

Combo boxes need to be special cased like text input. Also, Escape is
a reserved button in NVDA, so I added Enter as a way to "submit and
move up a level" in addition to escape, so these boxes can be edited
while NVDA is on.

Fixing combo boxes getting out-of-sync with NVDA.

---

core/block_render_svg.js
core/field.js
core/xml.js

Attempt to work around the IE/Edge bug where `getComputedTextLength()` throws an exception when the SVG node is not visible. This workaround forces a re-render, which in turn, forces a re-calculation of the node width once a block is inserted into the workspace SVG. This workaround is only executed on IE and Edge. See https://groups.google.com/forum/#!topic/blockly/T8IR4t4xAIY for the initial discussion of this issue.

Work around the IE/Edge `getComputedTextLength()` block sizing bug

---

core/workspace_drag_surface_svg.js

I incorrectly converted one CSS transform setter to use the cross-browser setter function in 40a063763c74b3f712c3057565966c25d5cfdb10. This PR fixes this incorrect conversion.
Fixes #892.

Bugfix for #892

---

blocks/lists.js

1. Visit https://blockly-demo.appspot.com/static/demos/toolbox/index.html
2. Open Lists toolbox
3. Hover on "in list [] find [first] occurrence of item []"
4. Wait for tooltip to attempt to appear
Tooltip should be displayed
Error is thrown:
```
Uncaught TypeError: Cannot read property 'workspace' of undefined
at blocks_compressed.js:22
at Blockly.Tooltip.show_ (blockly_compressed.js:987)
```

Fix "Uncaught TypeError: Cannot read property 'workspace' of undefined"

---

core/block.js

In commit d362c73a041cf0859d0cb33a346426c291174174, we added functionality for replacing empty field descriptions with "BLANK". This commit extends this functionality for dropdowns whose value is empty.
/cc @rachel-fenichel @CoryDCode since this is an update to core Blockly.

Use the empty field placeholder for dropdowns that do not have a value selected.

---

core/block_svg.js

When clearing warnings on blocks with IDs, the changedState variable should be true if the text changed. This will trigger the block being reshaped and remove the space for the notification icon (this.bumpNeighbours_).

Re-shape blocks when clearing warnings with IDs.

---

blocks/math.js
core/block.js
core/extensions.js
tests/jsunit/extensions_test.js

This adds support for a common use pattern in extensions, and adds error checking to avoid future incompatibilities.
Includes tests.

Adds Block.prototype.mixin() and Blockly.Extensions.registerMixin().

---

blocks/logic.js
blocks/loops.js
blocks/math.js
core/extensions.js
tests/generators/loops1.xml

Also...
* Added helper function Blockly.Extensions.buildTooltipWithFieldValue()
* Replaces uses of @mixes with @augments (I think this is more correct; we'll see when we build docs)
* Added a test for controls_repeat

Porting Loop blocks to JSON

---

core/block.js
core/block_svg.js
core/dragged_connection_manager.js
core/flyout.js
tests/playground.html

This PR adds a DraggingConnectionManager that tracks connections during a drag.
There are two goals here: to move large chunks of connection dragging logic out of block_svg, and to stop relying on Blockly.highlightedConnection_ and similar singletons.
In this pass I'm using a global Blockly.draggedConnectionManager_ to store this information.  When using this in new dragging code I will be able to have one of these per touch ID.
This should be a no-op on behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/925)

Extract connection dragging code

---

blocks/logic.js
core/block.js
core/connection.js
tests/blocks/index.html
tests/blocks/logic_ternary_test.js

* revert `logic_null` back to `output: null` (from `output: "null"`)
* Adds a new batch of tests specific for the playground blocks (only testing `logic_ternary` for now).
* Adds `Blockly.Connection.neighbors_()` to prevent headless breakage.

Fixing null/ternary interaction on generator tests.

---

blocks/logic.js

Previous extension naming was mixed with respect to "_mutator" suffix. This matches extensions in math.js and iOS implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/931)

Extension controls_if => controls_if_mutator.

---

core/css.js
core/field_angle.js

This is not a math problem. The onMouseMove method was not called when the mouse was over the "line" (representing the angle). Line being 2px thick, for movements smaller than 2px or any movement over the line, the onMouseMove method was not called. Setting pointer-events of that line to none leads to expected behaviour of the angle picker.  
Only thing is I am not sure this is best way of setting the pointer-event  to none.

Potential bug fix for issue #661

---

blocks/variables.js

The context menu of variable blocks "set" and "get" allows to create the other block, respectively. Unfortunately, it even allows so if the current block limit `maxBlocks` is already exhausted.
This fix deactivates the menu entries if `remainingCapacity()` returns zero or less.
As we want to use Blockly for a competition, we would appreciate this fix to be applied to the master branch as soon as possible.

Fix: Make variable add set/get block in context menu obey block limits

---

build.py

Verified constants are still integrated into generated language files.

Fix #946. Don't check for presence of constants.js

---

core/blockly.js

This may not be the desired behavior, but I didn't want to change the behavior.

Adding warning on duplicate JSON block definition.

---

core/block_svg.js
core/workspace_dragger.js
core/workspace_svg.js

This is a compatriot of BlockDragger.  It knows how to move a workspace around based on how far the pointer has moved, but doesn't have any logic for deciding when a workspace drag should happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/940)

Add workspace dragger

---

build.py
msg/messages.js

* Update help URL on procedure blocks. Fixes #937.
* Replace URL usages of `%28` and `%29` with normal parenthesis characters. They aren't replaced by JavaScript's `encodeURIComponent()` function, and seem to work just fine without them.
* Added missing semicolon in `build.py`. (Noted in #955)

Update help URL per #937.

---

core/block_drag_surface.js
core/block_dragger.js
core/block_svg.js
core/blockly.js
core/constants.js
core/contextmenu.js
core/flyout.js
core/flyout_button.js
core/gesture.js
core/gesture_db.js
core/icon.js
core/inject.js
core/rendered_connection.js
core/scrollbar.js
core/toolbox.js
core/touch.js
core/workspace_dragger.js
core/workspace_svg.js

Note: I'll want to squash these commits when I merge them.
-- Drag bubbles while dragging blocks
-- Use bindEventWithChecks to work in touch on Android.  Not tested anywhere else yet.
-- Handle dragging blocks while zoomed
-- Handle dragging blocks in mutators
-- Handle right-clicks (I hope)
-- Removed lots of unused code

More dragging work

---

blocks/text.js

Making text_count use a text block hue (like text_length, which also returns a number).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1027)

Making text_count use text block hue

---

core/inject.js
core/workspace_drag_surface_svg.js
core/workspace_svg.js

Renames Blockly.workspaceDragSurface to Blockly.WorkspaceDragSurface.

---

i18n/js_to_json.py

The current regex only works with the `\n` line endings as it expects a single character at the end of the line
after the `;` and `\r\n` in windows counts as two.
This causes the en.json and qqq.json files to be recreated with 0 string entries after the metadata, so the entire file would just end up being:
```json
{
"@metadata": {
"author": "Ellen Spertus ",
"lastupdated": "2016-02-05 15:45:48.323000",
"locale": "en",
"messagedocumentation" : "qqq"
},
}
```
Which then causes an issue in the `createmessages.js` script as it expects at least a single key after the metadata and end up causing issues like:
```
Error reading .\msg\json\en.json
Traceback (most recent call last):
File "i18n\create_messages.py", line 149, in <module>
main()
File "i18n\create_messages.py", line 65, in main …
```

Update RegEx in js-to-json to match windows EOL

---

core/input.js

Block connections on such inputs do not save/restore correctly, so it is better to fail early.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1054)

Enforcing non-empty names on value inputs and statement inputs.

---

core/field_variable.js
core/variables.js
core/workspace.js
core/xml.js
generators/dart.js
generators/javascript.js
generators/php/procedures.js
generators/python.js
generators/python/procedures.js
msg/messages.js
tests/jsunit/workspace_test.js

This CL does the following:
- Replaces VariableList with VariableMap.
- Edits all workspace.js functions that used VariableList to use VariableMap.
- Adds the functions outlined by the Design Doc: createVariable(name, opt_type, opt_id), getVariable(name), getVariableById(id), deleteVariable(name), deleteVariableById(id), renameVariable(oldName, newName), renameVariableById(id, newName), getVariablesOfType(type), getVariableTypes()
- Tests that the functionality of every edited function works the same as it did prior to editing.
- Tests that the additional functions work at outlined by the Design Doc.
- Adjusts any calls made by files outside of workspace that directly or indirectly accessed variableList.  The calls are adjusted so that original behavior is preserved.
---
This change …

VariableMap and functions added.

---

core/block.js

goog.asserts to not run from blockly_compressed.js. User data validation should always run.

Improve errors when validating JSON block definitions.

---

core/contextmenu.js

This PR adds a few private helper functions to Blockly.ContextMenu to make ContextMenu.show less gargantuan.

Tidy up context menu code.

---

.travis.yml
scripts/get_chromedriver.sh
scripts/get_geckdriver.sh
scripts/get_selenium.sh
scripts/setup_linux_env.sh
scripts/setup_osx_env.sh

1. update setup scripts for check if needed files are there already.  if so skip it.
2. add ios chrome test run. 
here's my test run, https://travis-ci.org/shirletan/blockly/builds/228155284
In general, travis osx job takes a longer than linux run. job queue is longer on osx. It now takes about 3 mins for both linux and osx run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1074)

add osx travis test run job

---

core/field_variable.js
core/variables.js

After this commit, the name is found inside of the VariableModel and displayed instead of the VariableModel being displayed as the name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1085)

Names are correctly fetched from VariableModels.

---

core/constants.js
core/field_variable.js
core/variable_model.js
core/workspace_svg.js

- Added static ID's for "Rename variable" and "Delete variable".
- Set the internal representation of a variable to its UUID
- Adjusted "FieldVariable.prototype.onItemSelected()" to use the UUID to extract the variable name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1096)

Assign variable UUID to field_variable dropdown.

---

generators/dart.js
generators/javascript.js
generators/php/procedures.js
generators/python.js

With this commit, generators read the variable model name instead of the whole variable model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1107)

Edit generators to read in Variable Models.

---

core/workspace.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1108)

Fix require

---

core/xml.js
tests/jsunit/xml_test.js

Add type and id info to generated xml.
Changed flyout's variable map to point to target workspace's variable map.
Wrote tests for FieldToDom() change in xml_tests.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1112)

Add type and id info to xml

---

demos/blockfactory/factory_utils.js

Fixes #1045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1111)

Fix apostrophe in tooltips and helpurls

---

core/flyout.js

Necessary for the future CL where `fieldVariable`'s `SetValue()` takes in an id.
Because creating a variable takes this path:
`Blockly.flyout.show()` -> `Blockly.Xml.domToBlock()` -> `Blockly.Xml.domToBlockHeadless_()` -> `field.setValue(xmlChild.textContent)` and `setValue` will check that the variable is in `variableMap` before creating the block.  This CL ensures that the main workspace's `variableMap` is checked instead of the flyout's.

Make flyout get variables from target workspace's variableMap.

---

core/block_render_svg.js
core/block_svg.js

Fixes #1102 
Height and width calculation is rendering specific.  This also resolves a repeated merge problem with scratch-blocks.

Move blockSvg.getHeightWidth to block_render_svg.js

---

.travis.yml

It looks like the default configuration for Travis might have changed. Adding a manual step to install webdriverio.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1141)

Fix for travis-ci testing failure

---

tests/jsunit/index.html
tests/jsunit/test_utilities.js
tests/jsunit/variable_map_test.js
tests/jsunit/workspace_test.js
tests/jsunit/xml_test.js

1. I found I was reusing 'isEqualArrays()' and 'setUpMockMethod()' a lot in different files so I just put it in a test utilities file.
2. 'setUpMockMethod()' is more robust now. It can record multiple calls now rather than just one.
3. Replaced a couple lines that should have been called 'setUpMockMethod().'
4. Removed $verify and $verifyAll(), because it is already run in the teardown.

Clean up and create test utilities file.

---

core/events.js
core/variable_map.js
core/variable_model.js
core/workspace.js
tests/jsunit/event_test.js
tests/jsunit/variable_map_test.js
tests/jsunit/variable_model_test.js

1. Added workspace attribute to Blockly.VariableMap and Blockly.VariableModel so that Blockly.Events could use it for redo-ing and undo-ing like it does with blocks. Adjusted tests and core code to reflect this change.
2. Created 3 var events and corresponding tests for constructor, toJson(), fromJson(), and run()
a.) VAR_CREATE
b.) VAR_DELETE
c.) VAR_RENAME
Next will call VAR events in pieces of code that create/manipulate variableModels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1150)

Add VAR events.

---

core/field_variable.js
tests/jsunit/event_test.js
tests/jsunit/field_variable_test.js
tests/jsunit/workspace_test.js
tests/jsunit/workspace_undo_redo_test.js
tests/jsunit/xml_test.js

With this we are able to remove the hack for test files that involves setting Blockly.Msg.DELETE_VARIABLE.
Since we can remove this hack that means for some files that some of the extra setUps can be removed.

In DropdownCreate check for Msg.DELETE_VARIABLE.

---

accessible/tree.service.js
accessible/variable-add-modal.component.js
accessible/variable-modal.service.js
accessible/variable-remove-modal.component.js
accessible/variable-rename-modal.component.js

Fixing the tree service so it doesn't treat unknown block deletion as an error, and turning off keypresses on the workspace when the variable modals are open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1182)

Fixing block deletion and keypresses "falling through" modals.

---

core/field_variable.js
core/variable_map.js
tests/jsunit/field_variable_test.js

This fixes the bug where if a variable is selected in the dropdown that doesn't exist, but it's type does, it is created twice in the workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1194)

Dropdown Create does not create a missing variable twice.

---

core/field_variable.js
tests/jsunit/field_variable_test.js

Prior, change events for field_variables were sending variables names. We have switched to using id's so this commit sends the new value's variable id instead.
Plus tests.
First part of fix for https://github.com/LLK/scratch-vm/issues/628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1196)

Fire field variable change event with variable value, not name.

---

core/procedures.js

Misspelled variable name, should be Blockly.PROCEDURE_CATEGORY_NAME.

Typo in a deprecated variable's value

---

core/extensions.js

We were using strings to check for the existence of properties on
a mutator, which breaks if those properties were renamed by the
closure compiler. This updates all of the uses to direct function
references so that anyone building with advanced optimizations turned
on will get the correct method references in their mutators.
fixes #1251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1253)

Update extensions.js to be compatible with ADVANCED_OPTIMIZATIONS

---

blocks/procedures.js

Fixes https://github.com/google/blockly/issues/1115
Procedure block now checks if the variable in its mutator input already exists in the workspace. If it does exist and there is a case change, the variable is renamed. If not, it is created.

Procedure block renames variable in mutator if there is a case change.

---

core/variables.js

Escape variable names correctly when serializing to XML

---

core/dragged_connection_manager.js

Blockly version of https://github.com/LLK/scratch-blocks/pull/1050

Bring the most recently edited stack to the front at the end of a drag.

---

core/events.js
tests/jsunit/event_test.js

For large App Inventor projects (order 1k+ blocks, 100+ top-level
blocks), the O(n^2) behavior of Blockly.Event.filter was causing
performance issues when rearranging blocks or pasting from the
backpack. This commit provides a linear merge implementation using a
key that uniquely identifies a block so that multiple events targeting
the same block are merged. This change benefits from O(1) amortized
lookup using an object as a key-value store.

Implement Blockly.Events.filter in linear time

---

core/block.js
core/field_variable.js
core/xml.js
tests/jsunit/field_variable_test.js
tests/jsunit/workspace_test.js
tests/jsunit/workspace_undo_redo_test.js
tests/jsunit/xml_test.js

- setValue is only called with the id as the parameter now
- setValue's ability to handle names is removed
- FieldVariable.SetSourceBlock() sets the value of the fieldVariable using text_ attribute since setting the source block is when the field variable finally has access to the workspace variables.
- Tests updated to create mock blocks by id instead of name (it was calling setValue() with names)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1254)

Remove all all instances calling setValue on variable fields with the name instead of the id

---

core/block.js
core/field_variable.js
core/xml.js
tests/jsunit/field_variable_test.js
tests/jsunit/workspace_test.js
tests/jsunit/workspace_undo_redo_test.js
tests/jsunit/xml_test.js

Reverts google/blockly#1254 since it causes an infinite loop. See https://github.com/google/blockly/issues/1294 for details.

Revert "Remove all all instances calling setValue on variable fields with the name instead of the id"

---

core/flyout_base.js

Fixes #1195
When creating Blocks, Flyout_Base creates a rect around each block and records a reference to it in backgroundButtons_
It uses the index of the block to set it in the array, so in the instance there is a FlyoutButton, that takes up an index, but doesn't create a rect and hence it's position in the array is undefined.
ie: Block, Block, FlyoutButton/Label, Block, Block creates this array:
backgroundButtons_ = [rect, rect, undefined, rect, rect].
The issue is the clearOldBlocks_ method in FlyoutBase iterates through the backgroundButtons_ array clearing each rect as it goes, until it reaches an undefined block. This means the last couple of rects are not cleared and remain in the workspace Canvas, causing scrolling issues listed above.
So fix for this is to update the …

Fix for Flyout labels causing Flyout scroll issues

---

core/blockly.js
core/toolbox.js

https://github.com/google/blockly/issues/1174
Adds an `opt_noPreventDefault` flag to `Blockly.bindEventWithChecks_` so that the default action can happen if the developer wants it.
Use the new flag in toolbox.js to allow touch scrolling of the toolbox.
This is based on a change that pxtBlockly has: https://github.com/Microsoft/pxt-blockly/pull/34/files
Developers have been asking for this feature.
Tested by pxtBlockly (with a touchscreen?) on:

Allow the toolbox to scroll

---

core/field.js
core/field_dropdown.js

https://github.com/google/blockly/issues/1047
and its dupes: https://github.com/google/blockly/issues/1232 and https://github.com/google/blockly/issues/1287
Force a rerender of the parent block if the value of a dropdown changed, instead of only when the text changed.  The text of an image item in a dropdown is the alt-text.  If the developer didn't specify alt-text, the image wouldn't update.
The previous behaviour was incorrect in a user-facing way.
Tested on:

Make dropdowns update correctly when you switch between images.

---

core/flyout_vertical.js

When scrolling up in a vertical flyout scroll momentum of the trackpad causes the flyout to then scroll back down, as described here https://github.com/google/blockly/issues/1220.
To fix this you must subtract metrics.contentTop from metrics.viewTop so that the flyout does not begin to scroll down once delta - metrics.viewTop > 0.
Once you are scrolled to the top, the value of metrics.viewTop is not necessarily 0. It should always be equal to the value of metrics.contentTop. So, in my case metrics.viewTop was equal to 5 when I was scrolled all the way up. As delta decayed from a large negative value to 0, once it reached -4 it meant that metrics.viewTop + delta would give me a value greater than 0. Once pos ends up greater than 0 you begin to start scrolling back down the page.
Before you …

Fix scrolling momentum in vertical flyouts

---

core/flyout_button.js

Buttons and text labels that appear in the flyout are both handled by flyout_button. Previously, a margin was being added to the width of both buttons and labels. This PR only applies the margin to buttons, and not to labels.
Labels that appear in a horizontal flyout were too wide when they had the margin added.

Add margin only for buttons, not labels

---

core/flyout_horizontal.js

Only scale the scroll events in Firefox for the mouse wheel, not for trackpad scroll events.
Previously, Blockly was applying a scale factor to all scroll events in Firefox. This scaling is correct for mouse wheels, but not for trackpad events.

Scale Firefox scrolling for mouse only, not trackpad

---

core/contextmenu.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js

https://github.com/google/blockly/issues/1329
Code cleanup in places where widgets are created, as a precursor to changing the API for positioning the widget div.
In each file I've extracted the code that creates and adds the widget into a new function, `createWidget_`. 
I also fixed #1329 by enabling autofocus on the context menu _after_ the first render, instead of before.
This should be a no-op on behaviour, but it makes other widget changes easier to isolate.
Tested manually on:
N/A

Code cleanup: widget creation

---

blockly_uncompressed.js
core/contextmenu.js
core/field.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js
core/ui_menu_utils.js
core/utils.js
core/widgetdiv.js

Fixes https://github.com/google/blockly/issues/1242
Add an API for positioning the widget div based on a basic set of coordinates: the bounding box of the viewport, the bounding box of the anchor, and the size of the widget inside the div.
In the past each place where `widgetDiv.position` was called needed to do a bunch of additional math to figure out positioning.  This math was almost the same, but not fully shared, so there was a lot of almost-duplication.
This change includes correct calculation of menu size for the dropdown menu and context menu, which fixes issues with the scrollbar appearing (#1242).
Tested in the playground (RTL and LTR) with the dropdown field, color field, and context menu.
Tested in the fixed blockly demo (RTL and LTR) with the dropdown field and context menu, …

Unify code for positioning the widget div

---

blockly_uncompressed.js
core/contextmenu.js
core/field.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js
core/ui_menu_utils.js
core/utils.js
core/widgetdiv.js
tests/jsunit/index.html
tests/jsunit/widget_div_test.js

N/A
Adds tests for WidgetDiv.calculateX_ and WidgetDiv.calculateY_.
The new widget div math is easy to test without constructing arbitrary blockly objects, so we should be testing it.
I added jsunit tests (tests/jsunit/widget_div_tests.js)
This includes all of the changes in cleanup/widgetdiv_utils.

Tests for widget div math.

---

demos/code/code.js

Part of #1265.
Add Kabyle as an option in the dropdown in the code demo.
In #1265 I said I'd add Kabyle to the hosted code demo on the next push to master.
I opened the code demo and selected Kabyle in the language dropdown.
Tested on:
This isn't live until the push to master.

Add Kabyle locale to code demo

---

core/field_textinput.js

This is also cherry-picked into this month's release candidate.
https://github.com/google/blockly/issues/1348
Put `showPromptEditor_` on the prototype.
The previous code was a mistake from a cleanup PR.
Tested on:
- Device: iPad 2
- OS: iOS
- Browser: Safari, Chrome
- Version: 10.3.3

Fix FieldTextInput showPromptEditor_

---

core/css.js

https://github.com/google/blockly/issues/1345
Use CSS to get rid of iOS's default tap higlight color on elements.
Surfacing default browser mousedown events exposed this issue.
Tested on iOS
Doesn't do anything on other platforms.
Tested on:
- Device: iPad 2
- OS: iOS
- Browser: Safari and Chrome
- Version: 10.3.3
This change was also cherry-picked into rc/sep_2017

Fix iOS toolbox flashing on tap

---

msg/json/pt.json

Corrects bad Portuguese translation with two `%3` references. This is identical to the Brazilian Portuguese message, verified by two native Portuguese.

Correct bad Portuguese translation.

---

generators/python/procedures.js

Do not assume an indentation of 2 spaces when writing the global variables at the top of a function declaration.
When a function block is used and global variables are needed, an indentation of 2 spaces was assumed
_What Github issue does this resolve (please include link)?_
I do not know if there's an issue with this. I found it with my blockly project
Simply use Blockly.Python.INDENT instead of 2 spaces
Without this change an indentation error appears in Python
This is at the generator level so is not dependent on browser
Tested on:
My first …

Do not assume an indentation of 2 spaces in function block (PYTHON generator)

---

core/flyout_button.js
core/tooltip.js

_What Github issue does this resolve (please include link)?_
Some minor performance improvements from https://github.com/LLK/scratch-blocks/pull/1141
_Describe what this Pull Request does.  Include screenshots if applicable._
2 minor things:
- Check for the timeout pid before clearing it.
- Use the caching `getCachedWidth` from `Blockly.Field` instead of directly reading it from the DOM.

Block rendering performance

---

generators/dart/procedures.js
generators/javascript/procedures.js
generators/lua/procedures.js
generators/php/procedures.js
generators/python/procedures.js

fix indentation for the return statement in function blocks that return a value.
I've also double check this file to see if there were any other such indentations and did not find others.
- [X ] I branched from develop
If the default indentation is changed to anything other than 2 spaces, the function blocks with a return value fail.
I am not aware of any issue already filed.
_What Github issue does this resolve (please include link)?_
Use Blockly.Python.INDENT instead of 2 spaces
Without this PR, the generated python code is invalid and cannot run
This is pretty straightforward.  Check that the code can be executed. Not platform dependent.
Tested on: …

Fix indentation for function blocks with return statements

---

core/extensions.js
core/utils.js

No github issue, just fixing lint errors.
Fix lint errors.
Lint was added in https://github.com/google/blockly/pull/1367/files
eslint can't handle a certain indentation style for function definitions.
Not platform specific.
I ran eslint.

Revert some whitespace changes to appease eslint

---

core/block_svg.js

https://github.com/google/blockly/issues/1365
Don't share the warning text PID map between blocks.
See explanation in https://github.com/google/blockly/issues/1365
Tested on chrome in the playground.
I used this code (taken from #1365) to add warnings:
```
var blocks = []
Blockly.getMainWorkspace().addChangeListener((event) => {
if(event.type === 'create') {
var block = Blockly.getMainWorkspace().getBlockById(event.blockId)
if(block.type == "controls_whileUntil") {
blocks.push(block)
checkForDuplicates()
}
}
})
var checkForDuplicates = () => {
if(blocks.length > 1) {
blocks.forEach(block => block.setWarningText('You are a duplicate', 'duplicate_block'))
}
}
```
The result looked like this:

Don't share the warning text PID map between blocks

---

blocks/loops.js

Fixes #1366
There was a typo in the name of the loop check mixin. Fixes the immediate issue though we should post a warning if trying to register a mixin that doesn't exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1375)

Fix typo in mixin name

---

core/xml.js

Fixes #1368 
Checks whether the type of a variable is null, but not whether `typeof(type == undefined)`.
`typeof` can never return undefined.  See #1368.
Covered by variable tests and xml tests, which still pass after this change.
N/A

Don't check typeof == undefined in variable deserialization

---

core/block_svg.js
core/contextmenu.js

No issue, just cleanup.  Similar to https://github.com/LLK/scratch-blocks/pull/1139/files
Creates helper functions for context menu options, and puts them in contextmenu.js.
Readability.  `showContextMenu` is a monster of a function.
I checked that I can open up the context menu, that the options are still there, and that they do the same things as they did before.
I'll be doing more of this in followup PRs.

Move some context menu options into contextmenu.js

---

blocks/loops.js
blocks/math.js
core/utils.js
tests/jsunit/utils_test.js

This fixes race condition in #1369 by using message references instead of explicit string lookups. This required fixing a bug the token interpolation parser that was breaking on the inner '"%1"' for these tooltips.
#1369
* Uses message reference strings in the tooltip, replacing immediate lookups into the string table that might not be loaded yet.
* Fixes `tokenizeInterpolation_(..)` recursion. Added additional tests.
* Generalizes the reported errors from `checkMessageReferences(msg)`.
Solves race condition.
Tested on:
_Remove this hint: these checkboxes can be checked like this: [x]_

Fix #1369 replaceMessageReferences(..)

---

core/events.js
tests/jsunit/event_test.js

_What Github issue does this resolve (please include link)?_
Fixes #1373 
_Describe what this Pull Request does.  Include screenshots if applicable._
This PR addresses #1373 by adding an else case in the event filter/merge mechanism to add events that collide with an existing hash but don't have paths for merging with existing events still get added to the event queue.
There is also a minor fix for an issue found with mutators where multiple move events are created and merged such that the resulting events are null, but still end up in the event queue and therefore the undo/redo stack. This causes UX problems because one may have to undo/redo twice. …

Fix logic bugs related to `e1e9427`

---

build.py

The online Closure Compiler drops http as of today.

Switch build to HTTPS. -- MASTER

---

core/block.js
core/workspace_audio.js

If external code can ‘play’, it should be able to ‘load’.  Resolves
compile error in Blockly Games.  Feel free to push back if this API
shouldn’t be public.

Allow external code to load new audio.

---

blocks/text.js

#1397 
The text_charAt mutator was replacing more of the title string than
necessary, which would lead to losing some of the relevant text in
the label. Updated the mutator to only add/remove a new input on the
end instead of replacing the default dummy input.
Ran existing unit tests and added X and Y to the TEXT_CHARAT_TITLE string as demonstrated in the bug to verify manually.
Tested on:
_Remove this hint: these checkboxes can be checked like this: [x]_
_Anything else we should know?_
---
This change is [<img …

Fix #1397 by being more careful with mutator

---

core/field_angle.js

Fixes the following lint errors:
```
/home/travis/build/google/blockly/core/field_angle.js
118:6   error  Expected indentation of 4 space characters but found 5  indent
119:4   error  Expected indentation of 2 space characters but found 3  indent
120:6   error  Expected indentation of 4 space characters but found 5  indent
121:4   error  Expected indentation of 2 space characters but found 3  indent
178:7   error  Expected indentation of 4 space characters but found 6  indent
179:7   error  Expected indentation of 4 space characters but found 6  indent
180:7   error  Expected indentation of 4 space characters but found 6  indent
180:34  error  Unexpected trailing comma                               comma-dangle
181:6   error  Expected indentation of 2 space characters but found 5  indent …
```

fix lint in field_angle.js

---

core/block_svg.js

Fixes https://github.com/google/blockly/issues/1417
Check `workspace.isDragging()` instead of `Blockly.dragMode_`.
`bumpNeighbours_` was referring to a property that no longer exists:
https://github.com/google/blockly/blob/master/core/block_svg.js#L1495
Tested by disabling snapping on the playground and dragging an equals block to a repeat block, then verifying that the equals block was bumped.
I missed this because snapping looked like bumping, as Neil mentioned in the bug report.

Check workspace.isDragging() instead of Blockly.dragMode_

---

core/dragged_connection_manager.js

https://github.com/google/blockly/issues/1416
Remove highlighting if releasing the drag would delete instead of connecting.
New behaviour, with all drags happening from the top-left corner of the repeat block.
https://github.com/google/blockly/issues/1416
Tested in the playground (see gif)
N/A

Get rid of highlighting when releasing the drag would delete instead of connecting

---

core/variables.js
core/xml.js
tests/jsunit/xml_test.js

https://github.com/LLK/scratch-blocks/issues/1191
Switch from `variableType` to `variabletype`.  
We were losing case-sensitivity in serialization and didn't notice it.
This is because `goog.dom.createDom` uses the global `document` as the context, which means it creates HTML nodes.  Those are not case-sensitive.  Variables would be serialized with an all-lowercase type, and their type would never be successfully deserialized.
We didn't catch this before because all of the tests that would have covered it use Blockly.Xml.textToDom, which creates XML nodes and preserves case.
Added a test to xml_test.js to make sure that variables names, ids etc. have their case preserved.
Manually checked that I can serialized and deserialized a typed variable correctly.
Tested on:
- Device: [e.g. …

Serialize variable type as all-lowercase

---

core/field_textinput.js

https://github.com/google/blockly/issues/1421
Use attributes that actually exist on getScaledBBox_.
I missed a spot in my widget div cleanup--there was a reference to something that no longer exists.
Tested on:

Fix text input widget position in RTL

---

blocks/text.js

Fixes #1397 for blockly_compiled.js. Had forgotten to update the String refs to use %{} since they're in JSON now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1426)

Use msg references in block JSON for text_charat

---

tests/generators/index.html

https://github.com/google/blockly/issues/1441
Alerts the user to any loading errors.
Improves the alert message.
Error #1442  in prior mutator correction was missed during testing. Prevent similar oversights.
Tested by running the test harness on the current error #1442.
Tested on:

Better error reporting when the test XML fails to load.

---

core/block_svg.js
core/flyout_button.js
core/workspace_svg.js

Uncompiled a goog.math.Coordinate toStrings as a nice “(1, 2)”, but
complied it toStrings as a useless “[object Object]”.  Fixes #1448.

Stop blocks from exploding.

---

core/flyout_vertical.js

https://github.com/google/blockly/issues/1208 was recently fixed by https://github.com/google/blockly/commit/00ada80afe40ca90401d649f612f492c8d713690
This is one more fix taking into account the workspace scale.
Take into account the workspace scale when figuring out where to position a flyout button in RTL mode.
If in RTL mode, and you zoom in/out the workspace, the positioning of a Flyout button is off: 
Tested on:
N/A

Fix positioning of right aligned Flyout buttons when workspace is scaled

---

core/block_svg.js
core/field_dropdown.js

None
Call `forceRerender` instead of `setText` to make a field rerender.
Mixing up rendering and model changes caused problems when trying to make dropdowns and variables distinguish between `setText` and `setValue`.
I can render all blocks in the playground correctly.  JSUnit tests still pass.
Tested on:

Call forceRerender instead of setText

---

core/workspace.js
core/workspace_comment/workspace_comment.js
core/workspace_comment/workspace_comment_svg.js
core/workspace_svg.js
core/xml.js
tests/jsunit/index.html
tests/jsunit/workspace_comment_test.js

Add a `commentDB_` property to the workspace to track comments by ID.  Use it.
Implement comment disposal.
Add basic tests for comments on the workspace.

Comment disposal; tests; tracking in a database

---

core/workspace_svg.js

In IE11 parentElement is undefined for SVG elements whereas element.parentNode is defined.

Switch to parentNode for IE

---

core/gesture.js
core/workspace_comment/workspace_comment_render_svg.js
core/workspace_comment/workspace_comment_svg.js

Adds a bunch of code in gesture.js for dragging comments.
Most of it is a direct duplication of the code for dragging blocks.  If it remains similar I'll come up with a name for a "draggable thing" and combine the code.
@microsoftsam

Gesture code for dragging comments

---

core/flyout_base.js

Resolves #1395 
Fixes the bug where VarCreate does not get fired when dragging a block with a variable out into the workspace:
- check for any new variables when creating a new block from the flyout
- issue VarCreate event for any new variables (not previously in the workspace)
Dragging out a block with a variable into the workspace was not issuing a VarCreate event even though a variable was getting added to the workspace.
Tried steps to reproduce issue #1395 and saw that the VarCreate event is getting fired once for each new variable being added to the workspace. VarCreate event does not retrigger when dragging blocks referring to existing variables out into the workspace.
Tested on:

VarCreate bugfix

---

core/css.js
core/gesture.js
core/workspace_comment/workspace_comment.js
core/workspace_comment/workspace_comment_render_svg.js
core/workspace_comment/workspace_comment_svg.js
core/workspace_svg.js

Added workspace highlighting of comments.
- Comments can now be selected, added to Blockly.selected
- Only edit comment on click. Otherwise, it can be dragged by click and drag anywhere on the comment
- Added comment resizing, resizing mouse handling logic currently in workspace_comment_svg_render
- Added a stroke for when the comment is highlighted.
- Comment is visually different also when it's focused (ie: on click), separate focused state for that
- Handling readonly and comments options
- Moved "Add comment" option to after Undo/Redo on the workspace context menu
Tested: 
- Chrome Mac, Edge, Firefox Mac, and Safari
- Readonly and comment options
@rachel-fenichel

Workspace comment highlighting

---

blocks/procedures.js
core/block.js
core/variable_map.js
core/variables.js
core/workspace.js
core/xml.js
tests/jsunit/variable_map_test.js
tests/jsunit/workspace_test.js
tests/jsunit/workspace_undo_redo_test.js
tests/jsunit/xml_test.js

Enables https://github.com/LLK/scratch-blocks/issues/1245
Allow two variables of different types to share the same name.
Variables can now be uniquely identified either by id or by name + type.  The name is no longer sufficient to look up a variable.
`renameVariable`, `deleteVariable`, and `getVariable` now take an optional `opt_type` argument.  If not specified, the type defaults to the empty string.
Scratch needs to support this.  I want scratch-blocks and blockly to have the same logic for variables.
Unit tested (thanks @marisaleung!) but I had to change lots of tests to use the empty type to make them pass.  I added TODOs referencing #1199 to fix those when I finish my variable work.
Tests caught some problems with rename that I hadn't noticed in the first pass.

Allow variables of different types to share the same name.

---

core/xml.js

None
Extracts field serialization and deserialization code into separate functions in Blockly.Xml.
Blockly.Xml has 100+ line functions for serialization and deserialization.  This structure makes it clear what information is needed for each tag.
Unit tests pass.
Loading random blocks in the playground, exporting to XML, and then importing from XML works.

Blockly.Xml code cleanup : fields

---

core/css.js
core/field_dropdown.js

Fix #1454 : Dropdown fields with a large number of options become unscrollable and get cut offscreen
Added scrollable functionality to dropdown menu of logic_compare.
On small screens the dropdown with more options (eg. 15 options) the portion of the list becomes inaccessible and get cut offscreen.
1. Added more options in blocks/logic.js for type = logic_compare.
2. started build.py
3. Ran demos/fixed/index.html
Tested on:
Thanks @vicng for such a descriptive issue and hack which helped me to make my first PR at blockly.

Added scrollable functionality to dropdown menu

---

tests/playground.html

Resolves #1082 
Removed the button, the "fakeDrag" and "fakeManyDrags" and "fakeDragWrapper", and the "fakeDragStack" list.
> Remove or update "fake dragging" code in the playground.
> After landing new dragging code.
None, sorry - shouldn't be too bad though.
/cc @rachel-fenichel

Remove "fake some drags!"

---

core/block.js
core/field_variable.js
core/xml.js
tests/jsunit/event_test.js
tests/jsunit/workspace_test.js
tests/jsunit/xml_test.js

Handles this case:
```
var block = workspace.newBlock('variables_get');
block.initSvg();
block.render();
```
I added a new test to check that the events come out in the same order when loading from XML and directly (end of event_test.js).
I had to update a bunch of tests that mock out calls to `genUid`.  There are more calls now, becuase we always start a group when trying to serialize a block during creation.  There may be a variable create at that time, which goes in the same group.
I also added try/finally to a bunch of the tests that needed tweaks, because without the finally they were cascading failures.
This still doesn't fully solve headless: it'll behave correctly if events are enabled, but not if events are disabled.

Create variables when blocks are created directly (not from XML)

---

core/block.js
core/xml.js

Create and call `block.initModel` function.  This new function parallels `initSvg`, though for now it's only needed for `fieldvariable`.
This fixes the case when events are disabled and the workspace is non-rendered, which previously meant that the variable field's model was never initialized.

Fix headless

---

core/names.js
core/variables.js
generators/dart.js
generators/javascript.js
generators/lua.js
generators/php.js
generators/python.js
tests/generators/unittest.js
tests/generators/unittest_dart.js
tests/generators/unittest_javascript.js
tests/generators/unittest_lua.js
tests/generators/unittest_php.js
tests/generators/unittest_python.js

- Add the concept of a "developer variable", which is in the generated code but never shown to the user.  We were implicitly doing this in generators before, but now it's explicit.  
- Update Blockly.Names to look up variables by ID instead of name.
- Update generators to set up their Blockly.Names objects correctly.
- Update block definitions used in the generator tests to define `getDeveloperVariables` instead of `getVars`.
- Update block generators used in the generator tests to refer to developer variables with a different constant than user variables.
- Add a utility function in Blockly.Variables to get all developer variables.
All generator tests now pass with variables referenced by ID, except for PHP lists.  That was broken before as well.
Calling getName with the result of …

Fix generator tests

---

blocks/procedures.js
core/field_variable.js
core/workspace.js
core/xml.js
generators/dart.js
generators/javascript.js
generators/php.js
generators/python.js

Every procedure argument is a valid variable, of type ''.
New in this PR:
- Store the variable models on the procedure blocks, as well as variable names.
- Implement `renameVarById` and `updateVarName`
- Serialize variable fields based on their `variable` property instead of doing a lookup in the variable map.  This fixes variable serialization after a variable has been deleted (e.g. when clearing the toolbox).
Tested: 
- Generator tests pass
- JSUnit tests pass
- I can create multiple procedures (with and without return) and multiple procedure calls; add variables; rename variables; then undo everything.  No errors and the correct number of variables exist at the end.

Use variable IDs for procedure arguments

---

core/field_date.js

goog.date.fromIsoString has been deprecated in favor of goog.date.DateTime.fromIsoString.
This change still needs to be tested with field_date enabled in the build before submitting.
goog.date.fromIsoString has been deprecated in favor of goog.date.DateTime.fromIsoString.
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1528)

Change goog.date to goog.date.DateTime

---

blocks/procedures.js
core/block.js
core/field_variable.js
core/workspace.js
tests/playground.html

Cleanup on variables_by_id before merging to develop.
I went through the TODOs that I left for myself and confirmed that some of them marked code that can be safely deleted.
Code cleanup before merge.
JSUnit and generator tests pass.

Remove some TODOs; add a variable-referencing block to the simple playground flyout

---

core/blockly.js
core/gesture.js
core/touch.js
core/touch_gesture.js
core/workspace_svg.js

https://github.com/google/blockly/issues/1295
Two major proposed changes: 
- Support for pointer events (Supported on latest Chrome and Edge)
- Support for multi-touch, zooming on pinch.
Pinch to zoom is more natural on touch devices!
Tested manually on various touch devices, including:
- Pinch to zoom using two fingers
- Drag a block and then place another finger (should continue to drag)
- Drag the workspace and then place another finger (should continue to drag)
Tested on:
* Windows Edge
* Surface Book (touch)
* IE, Chrome, Firefox and Edge
* IOS 11
* Safari and Chrome
* iPhone & iPad
* Android 8
* One Plus 5. 
* Chrome and Firefox
The PR doesn't enable touch gestures by default.
Other things not in this …

Support pinch to zoom gesture for both touch and pointer events

---

core/events.js

Resolves #1548
Remove `Events.disable()` / `.enable()` in `.disableOrphan`.
Events not sent that probably should be.
Tested with BlockFactory and Blockly Games (both use `disableOrphan`) and ran the jsunit tests.
Tested on:

Remove Events.disable() / .enable() in .disableOrphan. Fix #1548

---

demos/blockfactory/block_exporter_controller.js

In Generator section of Block Exporter, '.js' extension is not provided while exporting unless it is explicitly specified.
'.js' extension is appended to the end of file name.
It would lead to confusion since a file extension is not that of JavaScript.
It was not complicated update; hence, no complex test was applied.
Tested on:
Desktop Chrome
* PC(please complete the following information):
* Device: Asus
* OS: W10
* Browser: Chrome
* Version: 63

Fix #1553 - .js extension is provided when exporting Generator files

---

core/block.js
core/field_variable.js
tests/jsunit/field_variable_test.js

#1499
Add a `defaultTypes` option to the JSON for a FieldVariable definition.  Parse it correctly, and make sure that the default type and the allowable types are compatible.
There are cases when variable fields have to create new variables to be valid.  The type of the variable needs to match the intended type of the field.
JSUnit tests added to field_variable_test.js.
@kchadha FYI

Fix #1499 and add some validation

---

core/variables.js
core/variables_dynamic.js

Clarifying the role of Blockly.Variables.createVariableButtonHandler(..).
Updating documentation a making sure it (and its deprecated previous name)
are properly exported.
Confusion about `Blockly.Variables.createVariable(..)` (versus `Blockly.Variables.createVariable_(..)` and `Blockly.Variables.getOrCreateVariablePackage(..)`).
Rename to `Blockly.Variables.createVariableButtonHandler(..)` and add better docs.
It wasn't clear what the function did or what its role was, at a glance.
Tested in the playground on both Variable categories.
Tested on:

Blockly.Variables.createVariable(..) → .createVariableButtonHandler(..)

---

generators/javascript/math.js
generators/php/math.js

It was returning ``ORDER_ATOMIC`` for the block for any number; changed it so that it now returns ``ORDER_UNARY_NEGATION`` for negative numbers.

Fixed JS/PHP generators for math_number

---

generators/dart/variables_dynamic.js
generators/javascript/variables_dynamic.js
generators/lua/variables_dynamic.js
generators/php/variables_dynamic.js
generators/python/variables_dynamic.js
tests/playground.html

Fixes #1574 
Fixes #1574 
Add generators for dynamic variable blocks.
They're just mappings to the normal variable generators, because all of our languages are dynamic.  That means this pull request is almost entirely licenses on new files.
The blocks aren't that useful without the generators.
I checked that I can generate code for each language with the dynamic getters and setters (in the playground), and that it's the same as for the normal getters and setters.

Add generators for dynamic variable blocks.

---

.eslintrc

We turn quotes checking off in eslint because the JSON blobs in Blockly's files must use double quotes. Everywhere else we prefer single quotes. This updates the comment to make that clearer.
Fixes #1588 
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1589)

Update the comment on eslint quotes checks

---

demos/code/code.js

Give the user a warning if a generator is not defined for the given blocks and requested language.
Reimplementation of #1557 by @Rgtemze
Help developers with better messaging it a widely used demo.
I created a new block with no generator functions. I tested with only the new block, with a mix of blocks, and with only older existing blocks.
Tested on:

In Code demo, give warning if a generator function is missing.

---

core/workspace_svg.js

Fixes #1554 
Makes a private function package instead.
Scratch-blocks has a good use case for `refreshToolboxSelection` to be called from outside the WorkspaceSvg class.  It's new enough and private enough that we can just rename it.
Tested on:

Make WorkspaceSvg.refreshToolboxSelection_ package instead of private

---

core/block.js
core/generator.js

Console warnings on block prototypeNames that conflict with Blockly.Generator.prototype
First pass at #1558
Warning on conflicting Block names. Implementing a warning first, since fully banning type names is a breaking change.
Warn on conflict with Blockly.Generator.prototype members.
By convention, we use the Generator instance objects as generator function maps. This will conflict with prototype lookup for name collisions between block names and said members, and needs to be disallowed.  However, this is a breaking changes, so emit a warning in this release.
Locally edited Playground test blocks to have conflicting block instances. Saw the expected the error.
Also ran the build script with no bad effect on existing demos.

Warn conflicts with Blockly.Generator.prototype

---

core/blockly.js
core/workspace_svg.js

Fixes https://github.com/LLK/scratch-blocks/issues/1373
On keyboard paste, paste to the target workspace.
On keyboard cut, backspace, and delete, block the action if the selected block was in the flyout.
See https://github.com/LLK/scratch-blocks/issues/1373
You could delete and paste blocks in the flyout, which was lovely.
Tested on:
@kchadha fyi

Don't allow block deletion in the flyout.  Make copy-paste always copy to the main workspace

---

core/field_dropdown.js

(Cherry-pick #1610 into release candidate.)
#1609 Uncaught TypeError: Cannot read property 'firstChild' of undefined
Do not render block during field init().
The forced block render was causing other fields to render before they initialized, and fail.
Manually tested all dropdown blocks and reported block in both LTR and RTL:
* https://anmatanm.github.io/blockly/20180213-edge/index.html
* https://anmatanm.github.io/blockly/20180213-edge/index.html?dir=rtl
Also verified proper resize on variable rename (since variable fields are also dropdowns).
Tested on:
* Desktop Chrome (Mac, Linux, Windows)
* Desktop Safari (Mac, iOS 9.3)
* Windows Edge

Remove forceRerender() from FieldDropDown.

---

core/field_dropdown.js

#1609 Uncaught TypeError: Cannot read property 'firstChild' of undefined
Do not render block during field init().
The forced block render was causing other fields to render before they initialized, and fail.
Manually tested all dropdown blocks and reported block in both LTR and RTL:
* https://anmatanm.github.io/blockly/20180213-edge/index.html
* https://anmatanm.github.io/blockly/20180213-edge/index.html?dir=rtl
Also verified proper resize on variable rename (since variable fields are also dropdowns).
Tested on:
* Desktop Chrome (Mac, Linux, Windows)
* Desktop Safari (Mac, iOS 9.3)
* Windows Edge

Remove forceRerender() from FieldDropDown.init()

---

blocks/text.js

We had {% instead of %{
Fixes #1613
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1616)

Fix typo in BKY message key

---

package.json

Updating closure dependency.
goog.date.fromIsoString was removed upstream and we need to stay up to date to be compatible with other closure apps/libraries. See #1591.
Build.py uses online compiler, thus latest Closure. That works, so I suspect this will too.

Updating Closure version

---

blocks/procedures.js
core/mutator.js

Fixes #1544 
Update the procedures_mutatorarg block.  At the beginning of an edit to an argument name, start tracking variables that have been created as the user types.  At the end of the edit, delete all of the intermediate variables, saving only the one using the final variable name.  Don't delete variables that were already in use.
See #1544.  We were creating one variable per key typed.
Tested on:

Delete extra variables at the end of a procedure argument edit

---

tests/playgrounds/iframe.html

Adds a iframe host to the Blockly playground.
New `tests/playgrounds/iframe.html` with the `<iframe>` pointing to the standard `playground.html`.
Page to test events, etc in an iframe context.
Tested on:

Adding an <iframe> wrapper page for testing

---

core/touch.js

Pointer events are causing strange behaviour in iframes and in Chrome 64.  Disable them to get the current release out the door.

Disable pointer events for the february release

---

blocks/loops.js
blocks/math.js
blocks/text.js
core/extensions.js

Fix #1619 
The "value" of FieldVariables was the variable id.
However, we want the field text for the human visible tooltip. Refactoring and renaming `buildTooltipWithFieldValue` to use the field text.
* Refactor `buildTooltipWithFieldValue()` to use field text, instead of value. Rename accordingly.
* Make sure all use (the blocks in question) use the renamed function.
* Remove custom functions that were not using this helper.
#1619 
Tested on:

Fix #1619. buildTooltipWithFieldValue() => buildTooltipWithFieldText()

---

tests/playground.html

New toolbox blocks to test #1642 and related "drag block from toolbox" cases.
Adds a new "text blocks" toolbox category "Drag" with entries composed of standard blocks.
#1642 was only identified late in the release cycle, because it only exhibited in the demos, not the playground, JsUnit tests, or generator tests.
Tested on:

Adding new playground test category "Drag"

---

blocks/procedures.js

Fixes #1642 
Serialize and deserialize variable IDs for arguments in procedure definitions.
Dragging this block from the toolbox into the workspace failed.  
The initial XML had no variable IDs, so the code to load the blocks in the flyout created a potential variable for "list" (and another potential variable for "x").
Dragging from the flyout to the workspace uses `blockToDom`, then `domToBlock`.  
The serialization of the procedure definition block and its mutation did *not* include a variable ID, so a new variable was created (with a new ID).
The serialization of the "list" reference in the inner blocks *did* include a variable ID, which was the ID of the potential variable in the flyout.
This ID did not match the new ID of the parameter, so there was a crashing error.
Tested on:
* …

Serialize variable IDs in procedure definitions

---

core/block.js

#1633: If block definition has invalid color, creating/loading fails/throws
Catch the throw error, and print a warning with the block type name.
Without a color assignment, the block defaults to black (same as not having a color property in the JSON).
While it is still illegal to have a bad color value specified in the JSON, the consequences of the thrown error outweighed the functional error. Instead catch the error, allow the block to render. This also allows the the remainder of the toolbox/workspace to load.
This is covered in the new playground test blocks, and the "Styles" category fully loads with this change, with the following warning output in the console:
```
block.js:1072 Block "block_colour_hex4": Illegal color value:  #992aff99
block.js:1072 Block "block_colour_hex5": …
```

Print a warning if block JSON color value is invalid

---

blocks/text.js

On updating the block 'text_getSubstring', the ordinal string 'ORDINAL1' is moved when the corresponding corresponding input field is moved so that the ordinal string does not end up at the end of the block.
None
Reordering the ordinal sign in the block to the right place, even after selecting different entries in the block input fields. Here in German:
In languages with ordinal sign, the ordinal sign ends up on the wrong place in this block, if you first select "get substring from first letter" and then select "get substring from letter #". Here in German:
Tested on:
Desktop Chrome

Move ordinal in block 'text_getSubstring'

---

core/field_variable.js

So that it can actually be called.

Field.Variable's dispose should be on the prototype

---

core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_number.js
core/field_textinput.js
core/field_variable.js

Fixes #1671
Adds the @nocompress annotation to subclass implementations of `fromJson`.
See bullet two in "[Implications of object property flattening](https://developers.google.com/closure/compiler/docs/limitations#implications-of-object-property-flattening)" in the closure compiler documentation: 
Tested by running `tests/compile/compile.sh` and confirming that I can open and interact with `tests/compile/index.html`.
Is this also a problem with event `fromJson`?  I will investigate before merging #1672.

Use @nocompress annotation to fix advanced compilation.

---

core/blockly.js
core/touch.js

See https://github.com/Microsoft/pxt-blockly/pull/96
@microsoftsam

Don't register mouse events if pointer events are supported

---

core/events/abstract.js

Make getEventWorkspace_ protected.

---

core/blockly.js

Mark bindEvent_ and bindEventWithChecks_ package instead of private

---

core/block_svg.js

Expose block ID in SVG.

---

core/blockly.js
core/bubble.js
core/comment.js
core/css.js
core/gesture.js
core/touch.js
core/touch_gesture.js
core/workspace_svg.js

Fix pointer event (edge case) issues described in https://github.com/google/blockly/issues/1655
https://github.com/google/blockly/issues/1655
**Pointer events**:
A couple of major changes with the way we're handling pointer events: 
Always use pointer events, and no other mouse event. We were using a mixture of those, since we only had 'mousedown', 'mousemove' and 'mouseup' defined in the map. I added the rest of the mouse events, there were used in a couple of places where we attached events to mouseover, and so I just added mapping for the suite of mouse events. I also added a couple of mappings for touchend and touchcancel (this is really a workaround) since there are a couple of events that we register only for touch (eg: longstop) that we want to register for pointer events. 
Another …

Pointer Event fixes

---

core/block_dragger.js
core/block_render_svg.js
core/icon.js
core/utils.js
core/workspace_svg.js

In the first commit:
- In `block_render_svg` we pass around arrays that we use to build up the pieces of the SVG paths.  Once we have every piece, we concatenate everything in the arrays to build a string.  The items in the array can be numbers or strings, not just strings.
- In `Blockly.utils`, `hasClass` should be package instead of private.
Gets rid of 35 compiler warnings.
In the second commit:
- The block dragger can only drag BlockSvgs, not Blocks.
- Add a getter for toolboxes on the workspace, and use it.
- Mark some stuff protected in `icon.js` so that subclasses can access them.
Gets rid of about 30 more warnings.

Fix more compiler warnings

---

demos/custom-dialogs/custom-dialog.js

#1704
Bumped the backdrop `z-index` to 100. Was previously unset / `auto`. (The CSS is defined dynamically within `CustomDialog` functions.)
The backdrop was not occluding the toolbox or scrollbars.
Opened variable name dialog in this demo, seeing the toolbox and scrollbars are now behind the backdrop / mask.
Tested on:

Custom Dialogs demo: Bumping backdrop Z.

---

core/workspace.js
core/workspace_comment/workspace_comment.js
core/workspace_comment/workspace_comment_svg.js
core/workspace_svg.js
core/xml.js
tests/jsunit/workspace_comment_test.js

Progress on #1476 
Fixes loading comments on headless workspaces.
Move comment serialization and deserialization into the comment files, and rename to `fromXml` and `toXml`.  
Store height and width on non-rendered comments.  No need to destroy that information.
Part of a larger push to move serialization into the objects being serialized.  Might as well do it before the comments code hits develop.
Headless:
- built a workspace with a comment on the playground
- exported to XML
- ran `build.py core`
- opened the headless demo
- copied XML from the playground
- confirmed that the comment exists and has the correct properties after the `domToWorkspace` call.
Rendered:
- added comments in the playground
- serialized and deserialized
- edited
- resized
- serialized and deserialized more
- …

Move comment XML functions into the comment files.

---

core/workspace_svg.js

Fixes #391 
Needs documentation, but so does everything about context menus.
Adds a property to the workspace for a custom context menu function.
Like the one on blocks, it's null by default.  If it's defined it is called with an array of context menu options.  The function can edit the array, including removing items and adding items.
Each item in the array is an object containing:
`enabled`: boolean
`text`: string
`callback`: function
#391 requested it, and so have other people.
Tested in the playground by defining this function:
```
function customContextMenuFn(options) {
var option = {
enabled: true,
text: "Custom option",
callback: function() {
console.log('Custom context menu option called');
}
};
options.push(option);
}
```
then setting `workspace.configureContextMenu = …

Add hook for custom context menus on the workspace

---

build.py
core/block_svg.js
core/bubble.js
core/comment.js
core/mutator.js
core/warning.js
core/workspace_svg.js

Allows one to associate comments/mutators/warnings with their blocks while inspecting the DOM.
Also adds ‘block’ prefix to prevent possible ID collision between toolbox and workspace.

Add IDs to bubbles.

---

.eslintrc
blocks/variables.js
core/block.js
core/flyout_base.js
core/touch_gesture.js
core/xml.js

None
- Add `keyword-spacing` rule to our `.eslintrc`, and fix issues.
- Update `max-len` rule to limit to 100 and ignore strings and regexp.
Updates that @macherel pointed out in #1579.  (Sorry for the delay in adding them.)
Tested with `eslint .`
According to the google style guide we should limit line lengths to 80 characters.  There are too many errors for me to do that right now, but I enforce it for new code where reasonable.

Lint rule updates

---

core/workspace_comment/workspace_comment_render_svg.js
core/workspace_comment/workspace_comment_svg.js

Support drag of the comment during "editing" mode using the top handle.
Branched from comments_v2
Resolves: https://github.com/google/blockly/issues/1668

Workspace comments: support drag during edit

---

core/blockly.js

Fixes #1726 
Make bind/unbindEvent_ and bindEventWithChecks_ public
From the issue:
>While there probably is no reason to allow developers to call this for binding and unbinding events for elements in their applications (Blockly Games was doing so for menus and the like), there is definitely a desire to allow custom fields to call this.
>Here's a concrete example:
https://github.com/google/blockly-games/blob/master/appengine/music/js/field_pitch.js#L97
As such, the current use of @Package breaks the build for Blockly Games.

Make bind/unbindEvent_ public

---

core/bubble.js
core/bubble_dragger.js
core/css.js
core/workspace_comment/workspace_comment_render_svg.js
core/workspace_comment/workspace_comment_svg.js

Show an (X) icon on the comment when selected. Delete icon deletes the comment. Comment can be deleted if dragged onto the toolbox or the trash icon. A normal bubble cannot be deleted that way.
Branched of comments_v2
Resolves https://github.com/google/blockly/issues/1662
Notes: 
- Only showing the x icon when the comment is selected. (otherwise there was too much clutter)

Workspace comments: delete targets and icon

---

blocks/loops.js
blocks/procedures.js

Fixes https://github.com/google/blockly/issues/1741
Don't show the 'create get VAR' and 'create Function' context menu options on blocks when in the flyout.
Fixes https://github.com/google/blockly/issues/1741
Tested by right clicking on the for, count with, and function blocks in the flyout. Also tested that the option works when not in the flyout.
Tested on:
* Desktop Chrome.

Don't show create VAR and create Function context menu options when in the flyout

---

core/workspace_comment_svg.js

Promote the workspace comment to the top of the stack when selected.

workspace comments: promote comment when selected

---

core/block_dragger.js
core/gesture.js

Remove a single block from a stack of any of the meta keys are pressed. 
Fixes #1485 
When the gesture starts set a flag (healStack) whether any of the meta key was pressed during the start of the click. 
When we disconnect the block (unplug), we pass healStack to the unplug function to heal the stack. (All the healstack code was already there).
Feature used to exist and is very handy for rearranging blocks. 
Tested on:
- Chrome Mac
- Firefox Mac
- Safari Mac

Snap a single block from a stack (if meta key is pressed)

---

appengine/storage.js
core/xml.js

When loading, place blocks with no coordinates at 10,10 instead of 0,0.

Strip coordinates from storage of single block stacks in demos.

---

blocks/procedures.js
core/workspace_svg.js

This allows us to go to a block with a warning, or go to the definition of a user-defined function!

Add a function to scroll the workspace to center on a given block

---

.eslintrc
core/block.js
core/comment.js
core/events/abstract.js
core/field.js
core/field_textinput.js
core/generator.js
core/toolbox.js
core/tooltip.js
core/warning.js
core/workspace.js

None
Configure eslint to ignore unused arguments that start with an underscore.
Lets us get rid of some per-argument flags that we were using to ignore unused variables.  These are mostly in handlers and callback functions that might be overridden, where we still want to document that it will be called with an argument.
eslint passes
This is a nifty flag that I just learned about, but it's been in eslint for a while.

Add argsIgnorePattern to the eslintrc

---

blocks/colour.js
blocks/lists.js
blocks/logic.js
blocks/loops.js
blocks/math.js
blocks/procedures.js
blocks/text.js
blocks/variables.js
blocks/variables_dynamic.js
core/block.js
core/blockly.js
core/inject.js

#1648 
Making all blocks use the MSG colour values.
* Deprecating Blockly.Constants.Lists.HUE and similar constants.
* Removing deprecated Blockly.Blocks.lists.HUE constants.
* Allowing message references in the Block.setColour() parameter.
Since the conversion from JavaScript to JSON block definitions was never completed, several blocks used the old colour constants, while JSON use MSG constants. This made it difficult to change the colors on Blockly's predefined blocks.
I added the following lines to `playground.html` and then loaded all blocks in all categories, including the dynamic variables category.
```js
Blockly.Msg.LOGIC_HUE = '#193863';  // dark blue
Blockly.Msg.LOOPS_HUE = '#193863';
Blockly.Msg.MATH_HUE = '#193863';
Blockly.Msg.TEXTS_HUE = '#193863';
Blockly.Msg.LISTS_HUE = …
```

Making all blocks use the MSG colour values.

---

tests/jsunit/index.html
tests/jsunit/metrics_test.js

None
Add some simple tests to demonstrate the relationship between workspace size and content dimensions (in pixels).
Working toward a full understanding of metrics.
Added jsunit tests.
Next step: `getContentDimensionsBounded_`.  Then `getTopLevelWorkspaceMetrics`.

Simple tests for getContentDimensions

---

core/block_render_svg.js
core/block_svg.js
core/blockly.js
core/contextmenu.js
core/field_image.js
core/flyout_base.js
core/workspace_audio.js
core/workspace_svg.js

Removes requires in files that don't actually use it, and add requires in files that do use it.

Require goog.userAgent in the correct files.

---

core/flyout_vertical.js

Fixes #1425 
Change the calculation of the delete area for flyouts in mutators in RTL in firefox.  Explicitly add an offset from the left side of the mutator.
See #1425, but TLDR: Firefox is reporting the wrong value, and that bug has been around for years.  We surfaced it with a combination of changes to our DOM structure and changes to delete logic.
Tested in the playground in Firefox in RTL mode, with the if/else mutator.
Tested at a variety of scales.
Also tested in LTR mode to make sure there are no regressions.
Tested in Chrome to confirm no regressions.
Tested on:
As soon as we merge this they're going to fix Firefox and this will all break again :(
This should unblock the Blockly Games release.

Work around a problem with RTL mutators

---

demos/accessible/index.html
demos/code/index.html
demos/custom-dialogs/index.html
demos/fixed/index.html
demos/generator/index.html
demos/graph/index.html
demos/interpreter/async-execution.html
demos/interpreter/step-execution.html
demos/maxBlocks/index.html
demos/minimap/index.html
demos/mirror/index.html
demos/resizable/overlay.html
demos/rtl/index.html
demos/storage/index.html
demos/toolbox/index.html
tests/multi_playground.html
tests/playground.html

#1659
Setting the value of `math_numnber` toolbox blocks to 123.
Using 123 as a better indicator to the user this block can represent any number, and the user should replace this value with the desired number.
Admittedly, the basis of this assumption is not grounded in experimental evidence. App developers are encouraged to choose the right decision for their own apps.
Opened the Math toolbox category of every demo and playground.
Tested on:

Setting the value of math_numnber toolbox blocks to 123.

---

blocks/loops.js
blocks/procedures.js
blocks/variables.js
blocks/variables_dynamic.js
core/variables.js
core/variables_dynamic.js
tests/jsunit/xml_test.js

Fixes #1658 
Update the text of the custom context menu options to refer to the variable by name, not ID.
Update the generated XML to create a block that refers to the correct variable.
The previous implementation worked when variable field values gave the name of the variable rather than ID.  I missed this when testing variable by ID changes.
Unit tests pass.
I loaded all blocks that have this type of context menu option (XML is in a comment on #1658) and checked that the right-click menu said the right thing and generated the right block when clicked.

Fix context menus on blocks with variables

---

blocks/logic.js
tests/playground.html

#1408
* Create prevBlock_ upon first call to onchange.
* Revert state upon an incompatible combination, bumping the new incompatible
block, instead of the old block. Thus, the shadow is never the bumped block.
Bug:
* The undo stack get caught in a loop, and will never undo back to a state
equivalent to the previous action.
Prevent the creation of orphan shadow blocks on the workspace.
Added a pair of `logic_compare` test blocks to the Playground "Test Blocks" toolbox.
Tested on:

Rewrote LOGIC_COMPARE_ONCHANGE_MIXIN to fix #1408.

---

core/block.js
core/connection.js
core/flyout_base.js

#1681 , #1684 , #1679 
Mark some properties protected instead of private so they can be used by their subclasses.
Clean up warning messages during build to have a clearer picture of what the compiler may be telling us.
Tested on:
* Desktop Safari 
It seems like Safari also has the security restrictions mentioned on https://developers.google.com/blockly/guides/modify/web/unit-testing .

Mark some properties @protected instead of @private so they can be used by subclasses

---

core/block.js
core/block_dragger.js
core/block_svg.js
core/contextmenu.js
core/events/events.js
core/flyout_base.js
core/flyout_horizontal.js
core/flyout_vertical.js
core/generator.js
core/mutator.js
core/rendered_connection.js
core/toolbox.js
core/workspace.js
core/workspace_svg.js
core/xml.js

workspace.getTopBlocks has an ordered option, extend this option to workspace.getAllBlocks, block.getChildren, and block.getDescendants.

Add 'ordered' option to descendant getting functions.

---

demos/graph/index.html

#1790
Use color constant from the Msg table, not the deprecated and removed value.
The old constant was removed, rendering the block black.
Ran the graph demo. Looked at both custom variable blocks.
Tested on:

Correct block color reference in demos/graph

---

blocks/colour.js
blocks/lists.js

Both namespaces are only used by the deprecated `HUE` constant.
No issue. The constants were marked deprecated in a recent PR, which means the namespaces might be removed in the (far) future. The deprecation notice gives developers early warning on such removal.
Adding comments to mark namespaces as deprecated.
Backdating the deprecation to the date the `HUE` constants were deprecated.
None. Only added comments.

Deprecate Blockly.Constants.Colour and .Lists

---

core/blockly.js

* #1792: False hue warnings in console if a block library was not loaded.
* False warnings if `Msg` constant is changed
* Replacing last argument of `checkBlockColourConstant_()` (was `removed`) with `expectedValue`, which can be undefined.
* Do not warn if `value` is not assigned.
* Ran the unit tests.
* Added `Blockly.Msg.LOGIC_HUE = '#193863'; ` to playground.html, ensuring the color changed and no warnings were emitted.
* Added `Blockly.Blocks.logic.HUE = "#193863";` to the playground, ensuring the warning mentioned the constant was removed.
* Added `Blockly.Constants.Logic.HUE = "#193863";` to the playground, ensuring the warning mentioned the constant was deprecated and unused.
* Ran playground with `Blockly.Constants.Logic.HUE` commented out (as if `blocks/logic.js` was not …

Refactor of checkBlockColourConstant_()

---

core/block.js

Part of #1790.
In `jsonInit()`, if the JSON object has a `colour` attribute, but not a value, emit a warning.
For simplicity, this will occur on every block initialization of the given block type.
Warn developers that their blocks may be referencing a removed colour constant, or similar error.
Ran the graph demo that was using the old constants.  Saw the new warning.
After rebasing, tested against a `logic_boolean` with an explicit `colour: undefined`.
Tested on:

Warn if jsonInit() receives a colour attribute without a value.

---

blocks/colour.js
blocks/lists.js
blocks/logic.js
blocks/loops.js
blocks/math.js
blocks/procedures.js
blocks/text.js
blocks/variables.js

No reported issue.
Removing the empty namespace objects that use to contain the original block colour constants.
These namespaces use to contain the original block hue constants, but were deprecated (via comment, except for procedures) over a year ago. With the removal of those constants, the declarations were creating empty, unused objects.
References to old block constants were failing silently because the empty object existed.
Rebuilt compressed files and ran graph demo, which referred to the old constants (#1790).
With this change, the demo now throws:
```
index.html:225 Uncaught TypeError: Cannot read property 'HUE' of undefined
at Blockly.BlockSvg.init (index.html:225)
at Blockly.BlockSvg.Blockly.Block (blockly_compressed.js:1324)
at new Blockly.BlockSvg (blockly_compressed.js:1377) …
```

Removing namespace declarations for deprecated and unused namespaces.

---

blocks/colour.js
blocks/lists.js
blocks/logic.js
blocks/loops.js
blocks/math.js
blocks/procedures.js
blocks/text.js
blocks/variables.js

This reverts commit 75459abfddda176a0c779ec555154d9563a2d67e, PR #1796.
https://github.com/google/blockly-games/issues/79
Restores deprecated `goog.provides(..)` statements in block files.
These were used to load the block files in projects that use Closure for full-project compilation.
None. Restoring old code. No additional changes.

Revert #1796, restoring block file provide statements.

---

appengine/index_redirect.py
appengine/storage.py

Back-ports from Blockly Games:
* db is old and busted, ndb is the new hotness (there’s no known
difference, just pointless API churn).
* Use SHA1 which is consistent, rather than Python’s hash() which has
started changing between executions.  This stops duplicate programs
from being stored.
* Restructure so that storage.py can be used as a library, with
xmlToKey and keyToXml being callable by external programs.
* Use print function compatible with Python 3.

Update storage.py to use ndb instead of db.

---

core/block.js
core/field.js
core/field_variable.js
core/xml.js

Merge issues with scratch-blocks.
Add a `referencesVariables` function to field, and use it insteand of `field instanceof Blockly.FieldVariable`.
Scratch blocks has more types of fields that references variables, and we have merge conflicts every place where we do one instanceof check and they do two.  
Played around with the playground, and all tests pass.
Tested on:

Add a referencesVariables function to field

---

demos/custom-dialogs/index.html
demos/generator/index.html
demos/graph/index.html
demos/interpreter/async-execution.html
demos/interpreter/step-execution.html
demos/maxBlocks/index.html
demos/rtl/index.html
demos/storage/index.html
demos/toolbox/index.html
tests/multi_playground.html
tests/playground.html

Use `Msg` constants as the source of truth for toolbox categories.
In toolbox categories, replacing hard coded numbers with `%{BKY_..}` reference notation, adding the `colour` attribute when missing.
I also added `<sep></sep>` when missing above the variable and procedure categories.
Ensure toolbox category colors match the block colors.
I opened all changed demos, ensuring the category colors did not load as black.
Tested on:

Using %{BKY_} notation for toolbox category colours.

---

core/blockly.js
core/touch.js

Should resolve #1812 under Node.
Replace all `if (window && window...)` checks with `if (goog.global.window && goog.global.window...)`
The raw `window` reference throws in Node, where the object is not defined.
Ran the playground in Chrome, testing two-finger pinch gestures (that should trigger the related `PointerEvent` code).
Still need to test in Node.js somehow.
Tested on:

Replace raw window references with goog.global.window

---

core/flyout_vertical.js

Fix pulled over from Scratch-blocks that uses the correct multiplier for a trackpad scroll event.
Scrolling was weird on ff.

Fix a problem with scrolling on firefox

---

core/flyout_base.js

Fixes https://github.com/google/blockly/issues/1806
CSS transforms on SVG (inner) elements are not supported in IE and Edge.
I've scanned the codebase and https://github.com/google/blockly/blob/master/core/flyout_base.js#L375 (when the tagname is a `<g>`) is the only instance where Blockly.utils.setCssTransform is used on an SVG (inner) element. All other instances apply this on the SVG `<svg>` element and that's okay.
RTL mutators were broken on IE and Edge. The transform wasn't getting applied and so both the flyout and the workspace were left aligned (on top of each other)
Tested on: 
- Desktop Mac Chrome
- IE 11
- Edge 16
Not sure how to avoid something like this in the future @rachel-fenichel any thoughts?

Fix RTL mutators in Edge and IE

---

.eslintignore
.gitignore
core/node_lib_suffix.js
gulpfile.js
package.json

Importing Blockly into a Node.js project, which is important for headless testing.
The gulp file is derived from work in PR #887, with numerous
refinements and clarifying comments.
Also updating the version number in package.json, including the
'develop' prerelease tag for the develop branch.
This is a long requested feature, and one important for testing our headless infrastructure.
I built using `npm install`, and then successfully ran `var Blockly = require('./blockly');` inside Node, check for the presence of expected Blockly API and block definitions.
Tested on:
* Node!!! (v8.11.1)

Adding gulpfile to build Node.js compatible library.

---

package.json

Incorrect dependencies in package.json
* Moving some dependencies to `devDependencies`. Removing unused dependencies.
* Updating Closure version.
Clean-up
Ran `npm` install on clean copy of this branch of the repo (`git archive | tar -x ...`).
Awaiting a pass on Travis.

Clean-up dependencies in package.json

---

tests/generators/index.html

Makes it easier and faster to run all of the generator tests for a single language at once.
Add a button that loads all of the test suites into the workspace in order, using appendDomToWorkspace.
A lot of the time required for generator testing is in the repeated clicks to load and generate for each file.  This reduces that time in the case that everything works.
I loaded everything, then ran the tests in various languages.  PHP still fails with the known bug in the list generators; everything else works.
Tested on
We still need to find a way to fully automate generating and running code, so that we can add it to travis.

Button to load all XML files for testing

---

core/blockly.js
core/touch.js

#1812 regression
Replacing `goog.global.window` with `goog.global['window']`, which seems to get past the compiler and loads into Node again.
Sometime in the last three weeks (since #1818), closure compiler started unwrapping `goog.global.window` references, breaking Node usage again.
Rebuilt via gulp after change, and tested `var Blockly = require('.');` in node, in effect loading a rebuilt the `blockly_node_javascript_en.js`. This command was failing prior to this change.
Tested on:
* Node.js

Revised references to window to solve Node issues.

---

gulpfile.js
package.json

Don't run `build.py` upon `npm install`.
Moving `google-closure-library` dependency to `devDependencies` (which was supposed to be in the previous commit).
Build depends upon ../closure-library, which is outside the usual
npm process. And since the library ships pre-built, just concatenate
the built files to make the node-ready version.
Created a clean copy (`git archive | tar -x`) in a directory without a sibling `../closure-library` and ran `npm install`. Verified build did not run but `blockly_node_javascript_en.js` was created (triggering errors related to #1812).
Tested on:
* Node.js

Don't build upon npm install.

---

core/blockly.js
core/touch.js

Advanced compilation error introduced in #1856. Now bypassing `window` altogether.
Test `goog.global.PointerEvent` directly.
Duplicate var `window` in the previous version.
* Opened playground and tested pinch zoom.
* Rebuilt with gulp and tested `require('.')`.
* Executed `tests/compile/compile.sh` with errors (lots of warnings).
Tested on:
* Node.js

Another attempt at testing for PointerEvent.

---

.travis.yml
package.json
tests/compile/compile.sh
tests/compile/main.js

#1824 
* Replace `cd tests/compile; compile.sh; cd ..` with a direct call `tests/compile/compile.sh` in `.travis.yml`.
* Rewrote `compile.sh` to assume it is run from the project root.
* Test the exit code of the compiler, not just the presence of the output file.
**TODO[#1872]:** Test compilation with the other blocks (variables, procedures, colours, and lists).
**TODO[#1873]:** Adaptively find the correct path.
Travis was not running advanced compilation, like we thought.
* Ran `tests/compile/compile.sh` locally and opened the matching `index.html` file.
* Ensured Travis passed, checking logs to verify there were no compilation errors (and compilation warnings were logged).
Tested on:

Fix advanced compilation on Travis

---

core/block.js
core/block_svg.js
core/dragged_connection_manager.js
core/field.js
core/workspace.js
core/xml.js

None
Various changes from scratch blocks, including
- Use .textContent setter instead of deleting and recreating nodes: https://github.com/LLK/scratch-blocks/pull/1438
- Add an XML utility to clear the workspace and then load a new one without refreshing:  https://github.com/LLK/scratch-blocks/pull/1178
- Optimize block.setParent while clearing the workspace: https://github.com/LLK/scratch-blocks/pull/1441
Performance improvements, especially for repeatedly opening large workspaces.

Fixes from scratch blocks

---

core/contextmenu.js

Related to #230 
Makes the "Add Comment" option in the workspace context menu gray out in Internet Explorer.
IE doesn't support foreign objects, so comments aren't editable.  We decided we're okay with that as long as we don't make it possible to create a comment that can't be edited.

Disable ws comments in IE

---

core/block_render_svg.js

General cleanup.
Decomposes `Blockly.BlockSvg.prototype.renderDrawRight_` into separate functions for the major cases.
Create and pass around objects containing essential information, instead of passing large numbers of parameters to each function.
I tried to solve a problem with rendering and really struggled to understand the code.
I loaded a lot of blocks into the playground, in both rtl and ltr.  I made sure that they nest correctly, switch from inline inputs to external and back, and collapse and expand correctly.
Future work:
- use the `stepObject` more places, and ideally annotate it in a more useful way for the closure compiler
- decide whether the cursor and connection position objects should be coordinates

Decompose some render functions so they'll be easier to work with

---

core/block_dragger.js
core/block_svg.js

Fixes #1780 
Fire the move event at the end of a drag before firing the connect event.  This means that the events combine correctly.
Get rid of a check for `Blockly.selected` in `block.setParent`.
For the change in block_dragger.js, see the [explanation](https://github.com/google/blockly/issues/1780#issuecomment-385087792) by @jlaurens in #1780.
The change in block_svg.js gets rid of a check against `Blockly.selected` that was causing problems if the block was actually selected.  I added that check as part of https://github.com/google/blockly/commit/df7f534ad6ed287ecc8d13c4e159138b71ed1e88.  It came in from scratch-blocks; I had noted that it was an odd check there, but didn't investigate further yet.  It appears to cause real problems here.
I imported two blocks (a math_number block and …

Fix undoing a drag to connect

---

core/block_dragger.js
core/dragged_connection_manager.js
core/events.js
tests/jsunit/event_test.js

The rest of https://github.com/google/blockly/issues/1780
Make the filter function only merge consecutive move events on the same blocks.
The fix in #1889 exposed a new problem, which was that events were getting merged in the wrong way.  The example is:
Dragging the "123" block to the addition block leads to four events:
- move "123" to an x,y position near the addition block
- move the shadow block from the parent block to the main workspace
- delete the shadow block
- move "123" to connect to the addition block
The middle two events are a result of calling `unplug` on the shadow block.
The previous merge algorithm then merged the first and 4th event, giving:
- move "123" to connect to the addition block
- move the shadow block from the parent block to the main workspace
- delete the …

Make event filtering stricter for move events

---

core/toolbox.js

Fixes regression in #1893. Patch on change in #1831.
Verify typeof colour variable before passing through Number().
Missing attributes return `null`, and `Number(null) === 0`, resulting in a red hues category color.
Opened the Playground test blocks, observing the (lack of) colour next to the category label.
Opened the console noting the lack of warning messages.
Locally added the following toolbox categories to the playground test blocks:
<category name="No colour attr"></category>
<category name="Empty colour attr" colour=""></category>
<category name='"0" colour attr' colour="0"></category>
<category name='"undefined" colour attr' colour="undefined"></category>
<category name='"null" colour attr' colour="null"></category>
<category name='"true" colour attr' colour="true"></category> …

Fix #1893, null colour attribute for toolbox category

---

core/css.js
core/field_dropdown.js

#1364
Limit height of the dropdown popup to 45% of the height of the viewport.
Removed hardcoded height limit. (Why was `max-height` previously `!important`?)
Prevent the popup from exceeding the boundaries of the viewport.
Using `example_dropdown_long` in `test_blocks.js`, open the drop down when the block is visible near the top, near the bottom, slightly above the middle, slightly below the middle, and at various workspace zoom scales and page zoom scales. Make sure the contents can scroll in all cases.
Tested on:
* Windows Edge (Surface)
* Android phone (O)
* iOS iPad

Adaptive popup size for FieldDropdowns

---

core/flyout_button.js

#1880 
Correct name in button field reference.
Used the wrong name, creating a callback that was never disposed of.
Tested that the Variables toolbox still works (has a button in the flyout).
Did not test callback disposal (ideas?), but the PR reasoning is sound.
I verified the incorrect name does not exist anywhere else in the codebase using grep.
Tested on:

Fixed typo in flyout_button

---

core/field_dropdown.js

Fixes #1804
Get rid of custom touch handling code for dropdown fields.
The touch handler was selecting on touch up, which meant that you couldn't scroll a long dropdown--releasing the scroll would select an item.
Tested with the long dropdown field in the test blocks on the playground, in chrome in mobile mode.
Tested on:
I tried to get confirmation that the closure dropdown now works correctly in touch, but I have not heard any response.  From experimentation it seems to do the right thing; I'm a bit concerned about Edge/pointer events.

Remove custom touch handling code for dropdown fields

---

core/block_dragger.js
core/block_svg.js
core/bubble_dragger.js
core/mutator.js

Correcting `goog.require('goog.Timer')` calls only exist in files that actually use `goog.Timer`.
Also confirmed successful compilation using `tests/compile/compile.sh`.
Rebuilt (with workspace comments enabled) and tested various trashcan animations (the only use of `Timer`) in `demos/code/index.html` (compiled/compressed blockly).
Tested on:

Correct require goog.Timer statements.

---

tests/jsunit/workspace_comment_test.js

General testing.
Tests for XY, content, and HW getters and setters for headless workspace comments.
Continuing work on comments in scratch-blocks means that we may have compatibility problems as constructors and events change.  These tests can help us verify that we're not breaking anything in headless mode.  Scratch-blocks doesn't really run headless, but scratch blocks and blockly should behave the same with respect to these comments.
New JSunit tests.
This also need to land in scratch blocks.  https://github.com/LLK/scratch-blocks/issues/1563

Add some workspace comment tests

---

tests/jsunit/event_test.js
tests/jsunit/test_utilities.js

None
Move the temporary event firing function into test_utilities.
It's used in files other than event_test (where it was previously defined).
Jsunit

Move a test function into utils

---

demos/blockfactory/analytics.js
demos/blockfactory/app_controller.js
demos/blockfactory/block_definition_extractor.js
demos/blockfactory/block_exporter_controller.js
demos/blockfactory/block_exporter_tools.js
demos/blockfactory/block_exporter_view.js
demos/blockfactory/block_library_controller.js
demos/blockfactory/block_library_storage.js
demos/blockfactory/block_library_view.js
demos/blockfactory/block_option.js
demos/blockfactory/factory.js
demos/blockfactory/factory_utils.js
demos/blockfactory/standard_categories.js
demos/blockfactory/workspacefactory/wfactory_controller.js
demos/blockfactory/workspacefactory/wfactory_generator.js
demos/blockfactory/workspacefactory/wfactory_init.js
demos/blockfactory/workspacefactory/wfactory_view.js

#668 (partially)
Replacing all Closure `goog.` library calls from BlockFactory, with the exception of the ColorPicker and the test for the warning about running without Closure. This includes (almost) all `goog.provide` and `goog.require` statements.
Final status:
```
$ grep -rF "goog." .
./index.html:      Add it only if you need it.  See also goog.require in blockly.js.
./app_controller.js:goog.require('goog.dom.xml');  // Used to detect Closure
./app_controller.js:  if (!window.goog.dom.xml) {
./workspacefactory/wfactory_init.js:goog.require('goog.ui.PopupColorPicker');
./workspacefactory/wfactory_init.js:goog.require('goog.ui.ColorPicker');
./workspacefactory/wfactory_init.js:  var colourPicker = new goog.ui.ColorPicker();
./workspacefactory/wfactory_init.js:  var popupPicker = new …
```

Removing (most) Closure from BlockFactory

---

core/flyout_button.js
core/variables.js

#1927 
Expand `%{..}` references in toolbox `<button>` and `<label>`
Support i18n.
Changed the add variable category button to emit the message reference, and tested in Code demo.
Tested on:

Support %{..} in flyout_button (#1927)

---

core/block.js

I'm experimenting with generation of Typescript defs using clutz, which uses the closure-compiler, but it complains that a var is redeclared.
Rename redeclared var.
To allow clutz to process core blockly js.
Tested on:

Fix case of redeclared var (i) in Blockly.Block.prototype.jsonInit

---

.eslintrc
blocks/text.js
core/block_drag_surface.js
core/blockly.js
core/ui_events.js

Make curly stricter.
Require spaces around infix ops.

Add curly and space-infix-ops rules

---

demos/blockfactory/factory.js
demos/blockfactory/factory_utils.js

XML code the block definition `<pre>`, and missing preview:
Correct the overcorrection, restoring use of `innerHTML`.
Excessive removal of `innerHTML` reference broke code.
Opened BlockFactory to see it was correct and working.
Tested on:

Revert breaking changes to BlockFactory

---

i18n/js_to_json.py

#1934
`messages.js` does not use array notation. Match on original dot notation.
Message building broke, but only noticed when the message files were out of date.
Future: Need to update Travis to test compilation with `msg/js` files removed (and maybe other files).
Removed `msg/js/en.js` and rebuilt

Revert changes to i18n/js_to_json.py from 4cb4b42

---

tests/playground.html

Adding test values to the fields in the number field testing "Test Blocks".
Faster testing if a value is already assigned.
I opened the playground to the Test Blocks Fields category.
Tested on: * Desktop Chrome

Adding appropriate test values to number field test blocks.

---

tests/generators/colour.xml

No issue filed, but the random colour tests in the generator suite were failing when generated with zero-based-indexing because the tests were not correctly adjusting the index and return value.
- Correctly use the "adjusted" block to take indexing into account.
- Add better messages to the asserts.
Generator tests were failing.
I ran the generator tests in both indexing modes.
Old "test colour random" function:
New "test colour random" function:

Fix colour generator tests

---

tests/generators/colour.xml

Unbreak "load all" functionality on the generator test page.
Remove variable IDs from the XML for the colour tests.
I just updated the colour test XML, so it had IDs for variables for the first time.  Load all uses `appendDomToWorkspace` and it can't handle conflicting variable IDs (#1931).
Loaded all and ran generator tests.

Remove variable IDs from colour test XML

---

core/xml.js

Suppress empty \<variables\> tag in XML.
Alternatively, this code could check that allUsedVarModels is non-empty.  While that would be slightly more efficient, this approach is more robust in case variablesToDom gets smarter in the future.

Supress empty <variables> tag in XML.

---

core/workspace_comment.js

Adjusting annotations of the return object properties of Blockly.WorkspaceComment.parseAttributes
Previous form treated JSDoc `@return` object properties as globals.
Rebuilt JSDoc with this change.

Fixing JSDoc for the return type of Blockly.WorkspaceComment.parseAttributes

---

core/block_svg.js

The icons in rendered Blockly currently own the comment text. When
a block was deleted the icons were being disposed of before the block
info was recorded in the event, which meant the comment was lost. This
adds some additional logic to block_svg to make sure the event is
captured before the icons are removed.
#1960 
For now, have block_svg handle firing the event so it can capture all the info correctly. 
#1969 documents future work to not have the rendered icon own the comment.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1970)

Fix #1960 by collecting block info before icons are destroyed

---

core/block_svg.js

Reverts google/blockly#1970
Causes a crash when replacing a shadow block. Should just do the full fix to decouple icons from the comment instead of patching around it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1973)

Revert "Fix #1960 by collecting block info before icons are destroyed"

---

blocks/loops.js
blocks/procedures.js
blocks/variables.js
blocks/variables_dynamic.js

#1971
Replace all uses of `goog.*` library calls, other than `goog.provide(..)` and `goog.require(..)`. Specifically, `goog.dom.createDom(..)` and one use of `goog.array.equals(..)`.
`blocks/` files may not be compiled with the Closure compiler and should never use `goog.*` library calls.
This happened to work in the past because these functions happened to be called by `core/` files. However, as we are distancing ourselves from Closure library, the calls in `core/` were removed and now causes the crash identified in #1971
Performed actions in the playground that triggered each of the modified methods:
* Performed numerous various procedure mutator interactions/modiciations.
* Used variable block shortcuts in context menus.
Tested on:

Removing goog.* uses from blocks/*.js files

---

tests/workspace_svg/workspace_svg_test.js

Partial fix for #1976. This fixes the broken test by initializing the
svg for blocks when they're created.
Partially fixes #1976 . It fixes the broken test, but doesn't make Travis run these additional tests.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1977)

Fix failing svg canvas test

---

generators/python.js

Remove escaping code for `%` in python strings.
`%` is not a special character in a python string.
Rebase of #1890, commit 793055… from Ellipsis753:patch-1

Do not escape % in python strings.

---

tests/jsunit/event_test.js
tests/workspace_svg/event_svg_test.js
tests/workspace_svg/index.html

Disabled for now as it fails due to #1960.
I also added a comment to the block being used in the delete event test so if they start getting lost in headless too we'll notice.
Tested on:
Desktop Chrome
SVG tests aren't being run by travis, but I disabled so it won't start failing when they do get run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1984)

Add test for deleting a rendered block with a comment

---

core/inject.js
core/toolbox.js
core/utils.js
core/workspace_comment_svg.js
core/workspace_svg.js

Another small step for deleting Closure.

Some goog.dom removal

---

tests/jsunit/block_test.js
tests/jsunit/index.html

None
Add tests for the behaviour of `block.unplug` for blocks connected vertically (stacks) and horizontally (rows).
I want to change `unplug` to heal the stack in the horizontal case as well as the vertical case.  This adds tests that I can use to guard against regressions when I do that work.
4 new jsunit tests in a new file.  I checked that the file is being loaded and that the number of tests run went up by four.  The new tests pass.

Tests for block.unplug

---

core/block.js
tests/jsunit/block_test.js

None.
Extend the `opt_healStack` behaviour in `block.unplug` to work for rows as well as stacks.
Removing an insertion marker should heal the stack around it.
Added new JSUnit tests to cover various stack and row cases, including bad connection checks and bad numbers of connections.

Heal rows when unplugging, and add tests

---

core/ws_comment_events.js

- [ x] I branched from develop
- [ x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
https://github.com/google/blockly/issues/1871
This PR will create a common Helper function within lockly.Events.CommentCreateDeleteHelper. It will be called by Blockly.Events.CommentCreate.prototype and Blockly.Events.CommentDelete.prototype
Cleanup of code base. Reduce redundant code
I havent added new test cases. I would expect existing ones to pass successfully 
Tested on:

#1871 Create a common helper function for Comment[Create|Delete]

---

demos/resizable/overlay.html

Resolves #2000
Call `svgResize()` at the end of the window resize handler.
Without the extra call, window maximize does not appear to trigger resizing behavior for Chrome, Firefox, and Safari.
Opened `demos/resizable/overlay.html` in a window, and then maximized and minimized the window, ensuring the workspace filled the screen.
Tested on:

Call svgResize in the resize handler.

---

tests/workspace_svg/workspace_svg_test.js

PR #1970 created a bug that only occurred when replacing a rendered
shadow block. Add a test for this case to prevent breaking it again.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1981)

Add test for replacing a rendered shadow block

---

blocks/procedures.js

Missing annotations on procedure functions.
Adding `@override` and `@this`

Correcting annotations of procedure block mixin functions

---

core/css.js
core/workspace_svg.js
core/zoom_controls.js

This is just a new version of #1754.  From that description:
> Animate the workspace move when scrolling. Support for developers to begin and end the transition property on the block and bubble canvas.
>Add support for transitioning the workspace block and bubble canvas.
>
> Enable for scrollCenter.
> 
> It turns out only Chrome supports CSS transitions on SVG elements, so feel free not to pull in this change. Cool demo though!
> Animations are great!
Only works on chrome.
I tested what happens if you pick up a block during this transition, and it can be significantly offset from the mouse (tested by setting the transition to 5 seconds).  However, with a .5s transition it's hard to make that happen, and the offset is only during that one drag--the blocks don't end up in an overall bad …

Add support for transitioning the workspace block and bubble canvases on scrollCenter

---

core/variables.js

The documentation for allDeveloperVariables in https://developers.google.com/blockly/reference/js/Blockly.Variables does not match the variable in code.
(Rebase of #1979, which was apparently abandoned.)
Accept either old `getDeveloperVars()` or `getDeveloperVariables()` (as document).
Also emit on-shot warning when the old function name is detected, noting which block definition triggered the error.
Umm......

Rename getDeveloperVars() as getDeveloperVariables()

---

core/field_textinput.js

Fixes the following lint errors:
```
/.../Blockly/web/previous-attempt-at-1958/field_textinput.js
119:12  error  Expected space(s) after "if"  keyword-spacing
121:7   error  'setText' is not defined      no-undef
396:1   error  Missing JSDoc return type     valid-jsdoc
✖ 3 problems (3 errors, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
FAILED: eslint
```
Ran `npm test playground.html` successfully.

Fix lint errors in field_textinput

---

core/block.js

#1558.
Make previously added warning an official breaking error.
Occluding Generator members is *bad*.

Converting bad block warning into an error.

---

core/block_animations.js
core/block_svg.js
core/bubble.js
core/field.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/flyout_base.js
core/flyout_button.js
core/icon.js
core/rendered_connection.js
core/scrollbar.js
core/toolbox.js
core/trashcan.js
core/utils.js
core/workspace_comment_svg.js
core/workspace_svg.js
core/xml.js
core/zoom_controls.js

#2040
Duplicate older removeNode behavior by copying `goog.dom.removeNode(..)` into the Blockly codebase. Replaced all original locations of `goog.dom.removeNode(..)`, not just the case for the existing error.
The null check appears necessary, though the whole error case is not fully understood.
I opened the BlockFactory locally, which crashed before making these changes.
Tested on:

Adding Blockly.utils.removeNode(..)

---

blocks/variables_dynamic.js

when create get/set dynamic variable block from set/get ,
lost the type.
Tested on:
Desktop Chrome

fix bug.when create get/set dynamic variable block from set/get , lost the type.

---

core/field.js
core/field_dropdown.js
core/field_textinput.js
core/gesture.js
core/workspace_svg.js
core/ws_comment_events.js
core/xml.js

These are all properties that are being used by other field types that extend the base type.  Removes ~80 build warnings.

Mark some field properties protected

---

core/block.js
core/block_svg.js

Progress on insertion markers
Add some of the functions that insertion markers will need, without changing any of the actual rendering logic.
The added functions are 
- `isInsertionMarker`
- `setInsertionMarker`
- `getPreviousBlock`
- `getFirstStatementConnection`
- `getMatchingConnection`
I also added the `isInsertionMarker_` property to block.js
I'll need these for insertion markers.
These are the pieces of https://github.com/google/blockly/pull/1987/files that can come out into a separate PR while I debug the rest of it.
No changes to the code that's actually running until I land the insertionMarkerManager.

Add some functions for insertion markers

---

blocks/procedures.js
core/blockly.js
core/procedures.js
core/variable_map.js
core/variables.js
core/workspace_svg.js
demos/blockfactory/blocks.js
demos/blockfactory/workspacefactory/wfactory_controller.js
demos/blockfactory/workspacefactory/wfactory_generator.js
demos/blockfactory_old/blocks.js
demos/code/code.js
demos/plane/plane.js

None.  Gets rid of some compiler warnings.
All calls to `workspace.getAllBlocks` now pass `false` for `ordered`.  
Cleanup related to https://github.com/google/blockly/commit/662d79443f4e9a59334e19e2802399e6f427812c
There's nw an option to get blocks in order (slow) or out of order (faster).  These calls were missed in the original PR.
No change in executed code (undefined is falsy).

Calls to getAllBlocks should pass a value for _ordered_

---

core/connection.js

Part of adding insertion markers.
Restructure isConnectionAllowed to match scratch blocks.
Much of the detail work for insertion markers happens in isConnectionAllowed.  I've been struggling to see what needs to be changed because it's written differently in the two repos.  I'm matching the structure that the functional code has to make my diffs a bit easier to parse.
Tested with airstrike + dragging in the playground.

Restructure isConnectionAllowed to match scratch blocks

---

tests/blocks/test_blocks.js
tests/playground.html

Adds two new blocks to the playground's test blocks:
Fixes dropdown which previously could not be set to 'Test Blocks' due to missing condition.
Simplifies detection of file:// url.

Playground upgrades

---

generators/javascript/lists.js
generators/javascript/text.js
generators/lua/lists.js
generators/python/text.js

String literals in JS and Python don’t need to be coerced to strings.
Makes generated JS and Python code cleaner.
Previously, generated code for string concatenation looked like this:
JS: String('hello') + String('world');
Py: str('hello') + str('world');
Now string literals are detected and the unneeded string functions are dropped:
JS: 'hello' + 'world'
Py: 'hello' + 'world'
By the same token, string append looked like this:
JS: x = String(x) + String('foo');
Py: x = str(x) + str('foo');
Now append looks like this:
JS: x += 'foo';
Py: x = str(x) + 'foo';
(Python can't use += because x might not be a string and unlike JS, Python won't quietly cast x.)
In all cases, if an element isn't a string literal, the String() or str() functions are retained.
Procrastinating from real work.
Ran …

Remove unneeded String() and str() calls.

---

demos/mobile/android/app/src/main/java/com/google/blockly/android/webview/BlocklyWebViewFragment.java
demos/mobile/android/app/src/main/java/com/google/blockly/android/webview/JsDialogHelper.java
demos/mobile/android/app/src/main/java/com/google/blockly/android/webview/WebChromeClient.java
demos/mobile/android/app/src/main/res/layout/js_prompt.xml
demos/mobile/android/app/src/main/res/values/js_dialog_helper.xml
demos/mobile/html/index.html

Partial resolution to the Android half of #2076.
Allows editing of the field, but does not open the keyboard automatically. To get the keyboard requires tapping additionally in the EditText of the dialog. Additionally, the IME done button does not confirm the input and close the dialog (but partial code exists for this).
Adding hooks for Android dialogs upon `console.prompt()` and similar.
Adapting code from Android's `JsDialogHelper`, a private class in the Android source code.
It does not distinguish text fields from number fields, and does open up the appropriate IME.
When Blockly detects it is running on a mobile device, Blockly prefers `console.prompt(..)` dialogs for field text/number input.  Similar dialogs are also used in lots of other interactions (variables names, delete …

Adding hooks for Android dialogs upon console.prompt() and similar

---

core/workspace.js

If workspace.MAX_UNDO is reduced, we now throw away the extra records in the stack, as opposed to just not growing it anymore.

Honour reductions to MAX_UNDO

---

core/field_image.js
core/field_label.js

#2030
Saves the tooltip value and sets it when initializing the field's svg.
Previous code failed if the function was called too early.
Tested in Chrome by running these two snippets and hovering over the resulting blocks
```
Blockly.Blocks['test_1'] = {
init: function() {
this.appendDummyInput('in1');
var in1 = this.getInput('in1');
var field = new Blockly.FieldLabel('Test');
field.setTooltip('Test tooltip');
in1.appendField(field);
}
};
bl = Blockly.getMainWorkspace().newBlock('test_1')
bl.initSvg()
bl.render();
```
And
```
Blockly.Blocks['test_1'] = {
init: function() {
this.appendDummyInput('in1');
var in1 = this.getInput('in1');
var field = new Blockly.FieldImage('https://www.gstatic.com/codesite/ph/images/star_on.gif', 15, 15);
field.setTooltip('Test tooltip'); …
```

Fix setting tooltips in field init for fields

---

tests/generators/colour.xml
tests/generators/functions.xml
tests/generators/index.html
tests/generators/lists.xml
tests/generators/logic.xml
tests/generators/loops1.xml
tests/generators/loops2.xml
tests/generators/loops3.xml
tests/generators/math.xml
tests/generators/text.xml
tests/generators/unittest.js
tests/generators/unittest_dart.js
tests/generators/unittest_javascript.js
tests/generators/unittest_lua.js
tests/generators/unittest_php.js
tests/generators/unittest_python.js
tests/generators/variables.xml

Pick which generator tests to run with checkboxes instead of a dropdown.
Add a suite name field to the unittest_main block, update all tests to have the correct value in that field, and update generators to print that value.
I don't enjoy running generator tests.
This makes it possible to run a subset of the tests to find which ones are failing, without needing to go immediately to running only one suite at a time.
Having the suite name makes it possible to see what test suite failed and isolate it more quickly.

Generator test improvements

---

core/xml.js

Fixes #2096
We were creating a text node to wrap any block connected to
next when we should have just been attaching the generated dom.
Resolves #2096 
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2098)

Fix bad xml element when generating next node

---

core/workspace_svg.js

To recreate the issue reported by James Ma, go to the playground, and import this XML:
```
<xml xmlns="http://www.w3.org/1999/xhtml">
<block type="controls_whileUntil" x="13" y="13"></block>
<block movable="false" type="logic_negate" x="188" y="88"></block>
</xml>
```
Then right-click on workspace and cleanup blocks.  The 'not' block is immovable yet moves to a new location.
With this PR, the 'not' block does not move.

Immovable blocks should not move when workspace is cleaned

---

tests/generators/index.html

Part of generator testing being painful.
Select test suites to load from a checkbox instead of a dropdown.
Sometimes during debugging it's useful to load a subset of the tests to check for interactions.
Tests still work.

Select generator test suites by checkbox

---

build.py
tests/2018_playground.html
tests/scratch_playground.html

Updated build script to support 'core' and 'scratch' rendering. 
Blocks are shared, 'core' will exclude the scratch rendering file and 'scratch' will exclude the core renderer (block_render_svg). 
'core' generates blockly_compressed.js
'scratch' generates blockly_scratch_compressed.js
Thoughts on what we want to call this? Can probably re-visit that later. 
I also added a scratch_playground which is a dupe of playground.html but references the blockly_scratch_compressed.js
Note: calling this script currently will fail as block_render_svg_scratch.js doesn't exist yet. 
I've left accessible as is.

[rendering] update build script

---

demos/mobile/ios/Blockly WebView.xcodeproj/xcuserdata/marshalla.xcuserdatad/xcschemes/xcschememanagement.plist
demos/mobile/ios/Blockly WebView/ViewController.swift

#2076
In iOS ViewController, handle `alert(..)`, `confirm(..)`, and `prompt(..)` with native dialogs. These come up when confirming whether blocks can be deleted and alerting when blocks cannot be deleted. They are also supposed to come up when editing text and number fields on a phone... but don't, thanks to https://github.com/google/closure-library/issues/941.
I also added missing doc comments and corrected the Swift code style.
Add UI where UI was previous missing.
Tested all three functions in a simulator window, both by calling them at the console and (with the exception of `prompt`) via interacting through Blockly.

Add support for handling window.prompt(..) etc in iOS mobile demo

---

build.py
i18n/common.py
i18n/create_messages.py

Following changes are made with minimal touches in the rest;
- version dependent module imports
- codecs.open instead of open (for encoding errors)
- string_is_ascii modified for better compatibility
- In create_messages.py, synonym_defs are sorted as well to increase
testability, as Python 3 does not guarantee key order.
Note that this will cause previously generated files to have different
orders from the files generated without this patch.
- small changes; parenthesis around "print"s, has_key -> in,
"except x, y" -> "except x as y", sorted -> sort
https://github.com/google/blockly/issues/2112
Enabling the upgrade to Python3.x
Tested on:
Tested on Windows by comparing generated files using:
- original code with Python 2.7
- patched code with Python 2.7
- patched code with Python 3.6 …

Make build.py compatible with Python 2 and 3

---

build.py
i18n/create_messages.py
i18n/dedup_json.py
i18n/json_to_js.py
i18n/tests.py
i18n/xliff_to_json.py

Most changes are for except usages and paranthesis around print. 
decode had to be added for Python 3.4 compatibility, in build.py#341, because of changes in return type of response.read() and supported argument types for json.loads between 2.7, 3.4 and 3.6
Further updates following up https://github.com/google/blockly/issues/2112
Making remaining python files compatible with Python 2 and 3 versions. 
This patch also covers Python 3.4 compatibility for build.py
All files are inspected by PyCharm
build.py and dedup_json.py is tested on Ubuntu 16.04 by comparing generated files using:
- original code with Python 2.7
- patched code with Python 2.7
- patched code with Python 3.4
- patched code with Python 3.6
json_to_js and create_messages are indirectly used by build. 
xliff_to_json.py is …

Fix issues related to Python 3 compatibility

---

blockly_uncompressed.js
core/block_dragger.js
core/block_render_svg.js
core/block_svg.js
core/connection.js
core/constants.js
core/css.js
core/dragged_connection_manager.js
core/icon.js
core/insertion_marker_manager.js
tests/jsunit/connection_db_test.js
tests/jsunit/connection_test.js

Add the insertion marker manager class
Mark the dragged connection manager class deprecated, and remove the only use of it
(I propose leaving it in until we have a clear upgrade strategy for developers)
Add utility functions that are called by the insertion marker manager
Blockly should have insertion markers!  They look snazzy on Scratch Blocks, and the plan was always to backport them to Blockly. 
Unit tests pass.
Tested on:
You can play with this on [my demo site](https://rachel-fenichel.github.io/blockly/tests/playground.html) for now.  I reserve the right to update that site without warning.

Insertion markers in Blockly!

---

tests/scripts/get_chromedriver.sh

Longer term we should set it up to use the most recent version.  This is just a quick change to pull it up to date.
This [gist](https://gist.github.com/chitoku-k/67068aa62aa3f077f5307ca9a822ce74) may be relevant to configuring it to use the most recent version.

Update chromedriver version

---

core/connection.js
core/insertion_marker_manager.js

Fixes #2131 
Allow statement inputs to connect around block stacks during drags.
Remove distinction between first statement connection and other statement connections.
See #2131
Tested with the example in #2131, and with an if-else block to test the case with more than one statement input.
This makes it possible to connect on a statement input, but it's still not a great experience--the insertion marker is a little too stubborn about sticking around, so you have to drag away from the target and then back to switch which of the statement inputs you're connecting to.

Allow statement connections to connect around block stacks during drags

---

core/constants.js
core/rendered_connection.js

Add randomness to bump distances[ #2011](https://github.com/google/blockly/issues/2011)
Adds 0 to 10 workspace units to the dx & dy when bumping a block.
Improves Readability.
Tested using method seen above.
Tested on:
N/A

Added randomness to bumping per Issue #2011

---

core/constants.js

Insertion markers were too sticky when dragging a block with a statement input down through a stack of blocks.
Decrease the radius to search for good connections.  This makes sense--the old radius was from scratch blocks, and their blocks are taller.
Also increase the preference for the current connection.
It was not possible to drag an if block down one block through a stack of statement blocks.
Tested on the playground
We can continue to tweak this, but these numbers feel okay to me.

Tweak insertion marker snap radii

---

core/workspace_comment_render_svg.js

https://github.com/google/blockly/issues/1848
I added disposed state for svg component, so we could check it before blur or focus
These changes helped to solving #1848 issue
Tested on:

#1848 Fixed throw console warning when deleting workspace comments

---

core/flyout_base.js

#2154 
Correctly disables blocks in the flyout if there is not capacity available for them.
Users should not be able to create blocks that put the workspace over its capacity limits.
1. Added below code at ~ln 1084 in playground.
`<block type="limit_instances">
<value name="STATEMENT">
<block type="limit_instances">
</block>
</value>
</block>`
2. Set maxBlocks to 4.
2. Opened the test block's toolbox in the playground, and then the basic category.
3. Dragged the last block out into the workspace, and reopened the basic category. Last block is disabled (pass)
4. Dragged the second to last block out into the workspace, and reopened the basic category. Two last blocks are disabled (pass)
5. Dragged the third to last block out inot the workspace, and reopened the basic category. All blocks …

Fixed Filter Capacity not Considering Child Blocks.

---

core/css.js
core/zoom_controls.js

https://github.com/google/blockly/issues/172
Fixed IE, Edge bug on rendering svg image, clipPath element and added svg element as holder of image element.
These changes helped to solving #172 issue
Tested on:
* Windows Internet Explorer 10
* Windows Edge

#172, Fixed [Edge, IE] Zoom control mouseover is not clipped

---

core/inject.js

Fixes #1653
Makes the bounds checker created in inject correctly set the event group
before moving blocks in bounds.
#1653 
Propagate the event group in the bounds checker callback.
When a workspace can't scroll the inject method sets up an event listener
to bump blocks back into the visible bounds when dropped off the edge. The
event group wasn't being used, though, causing the move to be a separate
undo step. When undone, this would get you stuck in a loop where the
workspace would keep pulling it back into the visible range.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2163)

Propagate the event group when enforcing bounds on blocks

---

blocks/logic.js

#2037 
Reconnects the children of an if/else block after an undo is made.
Before Undo
After Undo 
When a user tries to undo adding an else block it rebuilds the if/else block by removing all inputs and reconstructing with the appropriate number of elseif and else  inputs. When removing the inputs it disconnects any statements attached to the inputs.
Tested on:
Desktop Chrome 
Desktop Opera

Reconnects child blocks when an undo is done on an else block

---

core/field_textinput.js

#1508
Adds setGroup(true) above where the BlockChange events get fired for renaming the procedure and renaming its callers.  
When trying to undo renaming a procedure with multiple callers it would create an extra undo for every block that was renamed.
Tested on:
Desktop Chrome

Groups events fired during field input change

---

core/blockly.js
core/inject.js
core/trashcan.js
core/workspace_svg.js
core/zoom_controls.js

#2136
Adds a flyout that appears ontop of the trashcan (and zoom controls) when the trashcan is clicked. You can then drag deleted blocks out of the trashcan.
Requirements:
1.There should be indication that the trashcan has blocks: When the trashcan has contents the lid is tilted & animates on hover.
2.Deleted blocks should render in an intuitive order: Newest at the top.
3.Deleted blocks should be easy to get: 1 click and 1 drag to retrieve, and the flyout always renders ontop of the trashcan.
4.The flyout should not be cluttered: Only 1 instances of every block (or group of blocks) is added to the flyout. A MAX_CONTENTS property limits the number of blocks (or groups of blocks).
Using keyboard controls (ctrl z) could be unintuitive for young users. This creates a way that they can get …

Added flyout to trashcan to "get back" deleted blocks.`

---

core/css.js
core/widgetdiv.js

Duplicate of this PR from scratch: https://github.com/LLK/scratch-blocks/pull/1821
Lets long context menus scroll.

Scroll very long context menus

---

core/block_svg.js
msg/messages.js

#2175 
1. Warnings stay attached to a block even if it is collapsed & expanded.
2. Warnings now "bubble up" from child blocks when the parent is collapsed.
3. Only the "bubbled up" warnings get removed from the parent block when it is expanded.
Warnings should inform the user of when there is an issue with there code. Collapsing a block should make the workspace less cluttered, without sacrificing important information (especially warnings!). 
These changes make it so collapsing a block doesn't hide important information from its child blocks, and makes it so that any warnings on a block stick around until they are properly dealt with.
1. Added the below code at ~ ln 124  in the playground:
`var workspaceBlocks = document.getElementById("workspaceBlocks"); …

Changed Warnings to Interact Properly with Collapsing/Expanding.

---

core/options.js
core/trashcan.js

#2165 
Allows you to set the maximum number of blocks allowed in the trashcan flyout through the workspace options struct.
* The flyout is not created if the maxTrashcanContents is <= 0.
* maxTrashcanContents is Infinity by default if the workspace has a trashcan.
* maxTrashcanContents is 0 by default if the workspace does not have a trashcan.
Allows developers to modify this option without changing the core.
Flyout Created/Not Created
1. Set the maxTrashcanContents option to Infinity.
2. Inspected the playground and observed how a trashcan flyout was created. (pass)
3. Set the maxTrashcanContents option to 0.
4. Inspected the playground and observed how a trashcan flyout was not created. (pass)
Default Values
1. Added below code at ln 143 in options: …

Added maxTrashcanContents Property to Workspace Options

---

core/field_image.js

Fixes #1632 
This PR adds `alt` attribute to the imageElement of fieldImage.
This changes will add alt value to the image in the block.
**Steps to test changes**:
- Created one block factor with the image field.
- Added it to the workspace and inspect the image element.
- Found `alt` attribute:
- Found tootip with text tag in svg:
Tested on:
- Desktop Chrome
- Desktop Firefox

Fix #1632: Added alt attribute to the field image.

---

blocks/procedures.js

Fixes #1958
This will drop the input when it's in the empty string state. This
causes the block to remove the input and re-add it when the text
is reverted, but prevents the breakage. A followup fix should leave
the input alone instead of removing it, but this works for now.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2182)

Avoid crashing when a procedure input has an empty string

---

core/flyout_horizontal.js

#1093 
Sets the scroll delta variable to the vertical delta if there is no horizontal delta.
This allows vertical-only scrolling mice to scroll horizontal flyouts.
1. Set playground to bottom or top.
2. Opened a scrollable category.
3. Scrolled vertically with the mouse.
4. Observed that the flyout scrolled.
Tested on:
* Windows Edge

Fixed Scrolling Horizontal Flyout with Mousewheel

---

core/flyout_button.js

#1146
Changes the callback to be looked up dynamically whenever the button is clicked instead of being associated with the flyout button on instantiation.
This allows button callbacks to be added to category-less toolboxes.
1. Added below code at ~ln 124 in playground.
```
workspace.registerButtonCallback('CALLBACKLABEL', function(button) {
console.log("Label Callback!");
});
workspace.registerButtonCallback('CALLBACKBUTTON', function(button) {
console.log("Button Callback!");
});
```
2. Added below code at ~ln 367 in playground.
```
<label text="label without callback"></label>
<label text="label with callback" callbackKey="CALLBACKLABEL"></label>
<button text="button without callback"></button>
<button text="button with callback" callbackKey="CALLBACKBUTTON"></button>
```
3. Set the …

Fixed Being Unable to Register Button Callbacks in Category-less Toolbox

---

core/bubble.js

#1521 
The bubble now has 4 possible positions it could be in:
* Top shifted
* Start shifted
* End shifted
* Bottom shifted
Shifted meaning that it has been moved along it's "subaxis" (x-axis for top and bottom, y-axis for start and end) so that the maximum amount of the bubble will be shown for the given position. E.g. if the bubble is being positioned at the top, but it is being overlapped by the workspace on the left, it will be shifted to the right so that the maximum amount of the bubble will be shown.
For each of these positions the "overlap percentage" (meaning the percentage of the bubble's total area that is visible when in a given position) is calculated. The bubble is then placed at the position with the highest "overlap percentage" with tiebreaks going in the below order …

Changed how Bubbles Position Themselves

---

tests/mocha/.eslintrc
tests/mocha/block_test.js
tests/mocha/event_test.js
tests/mocha/field_variable_test.js
tests/mocha/test_helpers.js
tests/mocha/utils_test.js

Add a `.eslintrc` file to the tests/mocha directory, and move inline eslint comments into the eslintrc.
Consistent linting/the other way was just a hack to get going.

Add eslintrc to mocha directory

---

core/block_svg.js

#1960
Quote from #1970 
> For now, have block_svg handle firing the event so it can capture all the info correctly.
#1969 documents future work to not have the rendered icon own the comment.
This PR also calls this.unplug(healstack) before creating the delete event, so we don't see the error reported in #1972.
Quote from #1970 
> The icons in rendered Blockly currently own the comment text. When a block was deleted the icons were being disposed of before the block info was recorded in the event, which meant the comment was lost. This adds some additional logic to block_svg to make sure the event is captured before the icons are removed.
1. Opened playground, turned on event logging, opened console.
2. Created a block.
3. Added a comment to the block.
4. Observed how a Change event was …

Fixed Comments Not Being Recorded in Delete Event

---

core/trashcan.js

#2166 
Displays the trashcan flyout horizontally when the layout is horizontally.
The flyout always appears "ontop" of the trashcan.
Tested on:

Added Displaying Trashcan Flyout Horizontally When Layout is Horizontal

---

core/scrollbar.js
core/workspace_svg.js

For keyboard accessibility, the PR supports the ability to programmatically pan the workspace by x and y in CSS units.
To test, drag a block to the workspace and call: 
``Blockly.mainWorkspace.panByOffset(50,50)``
I've split up the scroll function as it can be used by https://github.com/google/blockly/issues/2205#issuecomment-454534679 to scroll using the scrollbar as well.

Pan the workspace by x,y CSS units

---

core/css.js
core/cursor.js
core/gesture.js
core/inject.js
core/workspace_svg.js

Creates the Cursor class that is in charge of showing, positioning and rendering the cursor SVG into the workspace. 
Show the cursor using a mouse click when the shift key is down on the workspace at the position of the click.
The cursor currently animates using SVG SMIL but that's not supported on IE and Edge, I didn't want to spend too much time on rendering just yet, but we can animate with JS instead.

Initial cursor rendering, supports coordinate positioning only

---

core/navigation.js

Currently no way to navigate blocks by keyboard.
Given a certain connection adds basic functionality for finding next and previous connection.
Trying to add keyboard functionality. 
Tested on:

Added basic up and down block navigation

---

core/blockly.js
core/cursor.js
core/gesture.js
core/inject.js
core/navigation.js
core/workspace_svg.js

Support showing a cursor that's associated with a PREV/NEXT connection. Input/Output still to come.
Renders the cursor on the workspace, and moves it to the prev/next connection coordinates taking into account the offset.
Helper methods for enabling / disabling keyboard accessibility mode. 
For testing: Use space to set the cursor at the previous connection of a selected block.

Show the cursor with attached to a statement connection

---

core/blockly.js
core/css.js
core/cursor.js
core/gesture.js
core/navigation.js

Add support for rendering a vertical cursor and show vertical / horizontal cursor based on the connection type.

Add support for rendering a vertical input based cursor

---

core/block.js

Resolves #2215
Use ['primaryColour'] instead of .primaryColour because strings do not get changed during compilation unlike .primaryColour.
.primaryColour was getting changed to a different variable name and the value name on the style was not. 
Tested on:
Desktop Chrome

Access colours using bracket notation

---

.gitignore
local_build/local_build.sh

https://github.com/google/blockly/issues/2099
This change modifies local_build.sh to generate local_blocks_compressed.js
local build only supports generating local_blockly_compressed.js.
Tested on my local system
Tested on:
Desktop Chrome

local_build: Add build for local_blocks_compressed.js

---

blockly_uncompressed.js
core/events.js
core/workspace_events.js
core/xml.js

#2142 
Quote from Issue:
> Developers sometimes want to run some actions after a workspace finishes loading. There is no event to indicate this right now.
1 . Turned on "Log events" in the playground.
2 . Hit the "Spaghetti" button.
3 . Observed how a FinishedLoading event was correctly fired. (pass)
1 . Changed the following code ~ln 251 in playground:
```
console.time('Spaghetti domToWorkspace');
Blockly.Xml.domToWorkspace(dom, workspace);
console.timeEnd('Spaghetti domToWorkspace');
```
To:
```
console.time('Spaghetti domToWorkspace');
Blockly.Events.setGroup(true);
console.log(Blockly.Events.group_);
Blockly.Xml.domToWorkspace(dom, workspace);
Blockly.Events.setGroup(false);
console.timeEnd('Spaghetti domToWorkspace');
```
2 . Hit the "Spaghetti" button.
3 . Observed how a …

Added FinishedLoading Event

---

core/flyout_horizontal.js
core/flyout_vertical.js
core/trashcan.js
core/zoom_controls.js

#2237 also similar to #2035 
The trashcan and zoom controls are now positioned in the corner opposite the toolbox. (This just changes LTR, Vertical, End & RTL, Vertical, End)
Also replaces a call to workspace.resize() with a call to flyout.position() which corrects the trashcan hotspot bug.
1) Removes the "chasing" of zoom controls that would occure when resizing the LTR, Vertical, End & RTL, Vertical, End workspaces when they had simple toolboxes.
2) Allows us to replace the workspace.resize() call with a call to flyout.position(), because the reason resize was called was specifically to move the trashcan (bad behavior stop it!). Replacing this call fixes the hotspot problem.
Plus the multiplayground looks very nice now =D
1. Opened the multiplayground, and set the toolbox mode to …

Fixed Trashcan Hotspot & Changed Positioning

---

core/trashcan.js

See Additional Information on #2240 
Changes the trashcan lid animation so that it always opens towards the workspace (i.e. the direction blocks will be comming from).
Feels better. ¯\\\_(ツ)_/¯ 
1. Opened the multiplayground.
2. Dragged a block towards the trashcan. Observed how it opened in the "correct" direction. (pass)
3. Repeated step 2 for every workspace.
Tested on:
N/A

Changed Trashcan Lid Opening Direction

---

core/block_dragger.js
core/gesture.js
core/insertion_marker_manager.js
core/workspace.js
core/workspace_svg.js

Fixes #2236
Stop counting insertion markers in the results of getAllBlocks.  Add an accessor for getting the current live insertion markers from a gesture.
It also would have worked to have an optional parameter to getAllBlocks, but I decided to leave its signature alone and do something a little more complicated but only in internal code.  This way we don't add yet another thing to the external API.
See #2236 
Tested in the max blocks demo with uncompressed blockly.
This might also apply to `workspace.getBlocksByType`, `getTopBlocks`, etc.  It's kind of unfortunate: there are good reasons for the blocks to be in the top blocks list, mostly related to behaving like perfectly normal blocks for connection and disconnection purposes, but in all other cases they're unwanted.

Ignore insertion markers in getAllBlocks; add accessors for insertion markers

---

core/field.js

#2238 
So the problem is that the first time FieldDropdown.renderSelectedImage_ is called the dropdown arrow is not yet rendered, which causes the FieldDropdown to calculate its size incorrectly. By happy accident, if the block is enabled the field is forced to rerender because of updateColor(), but when the block is disabled this does not happen, so it is stuck with the incorrect size.
The incorrect first size calculation is triggered as follows: (function names link to the function, arrows link to the call)
[xml.domToBlock](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/xml.js#L535) [>](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/xml.js#L555)
[block.initSvg](https://github.com/google/blockly/blob/3342a375ff0ce …

Fixed Image Dropdowns on Disabled Blocks not Rendering Correctly.

---

tests/blocks/test_blocks.js
tests/playground.html

N/A
Adds a test block to the playground for testing dynamic dropdowns. The dynamic dropdown is populated through two toolbox-button-prompts similar to the "create variable..." button.
I was helping someone with their dynamic dropdown and wrote a little thing to help me test. I thought it might be useful to you, if not that's cool too =)
N/A This *is* a test!
N/A

Added a Test Block for a Dynamic Dropdown

---

core/block.js
tests/playground.html

#2227
Check against healing child shadow blocks.
Also applies to shadow next blocks.
Added a playground test block group with a shadow statement.
See examples in issue #2227.
Tested on:
Manually tested scenario in #2227. Also added a block group with a shadow next block to test the statement case.

Check against healing child shadow blocks

---

core/flyout_base.js

#2237 
Makes it so that if the top block in the toolbox is disabled (because of capacity) then the next blocks are disabled as well.
Just a visual nicety.
1. Changed the simple toolbox to the below xml.
```
<xml id="toolbox-simple" style="display: none">
<block type="controls_if">
<next>
<block type="controls_if"></block>
</next>
</block>
<block type="controls_if">
<next>
<block type="controls_if">
<value name="IF0">
<block type="logic_compare"></block>
</value>
</block>
</next>
</block>
<block type="controls_if">
<next>
<shadow type="controls_if"></shadow>
</next>
</block>
<block type="controls_if">
<next>
<block type="controls_if">
<value name="IF0">
<shadow type="logic_compare"></shadow>
</value>
</block>
</next>
</block>
<block type="math_single">
<value name="NUM">
<shadow …
```

Fixed next blocks not being disabled in flyout.

---

core/flyout_base.js

#1445
Adds an extra call to setPosition.
Resize would fail because the metrics were the same. This means setPosition would never get called so the scrollbar would stay in the same position.
Tested on:
N/A

Fixed Flyout Scrollbars Not Being Repositioned on Window Resize

---

core/flyout_horizontal.js

#2275
Returns 0 for contentTop and contentLeft instead of optionBox.x and optionBox.y.
The positive contentTop and contentLeft values were causing [this](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/scrollbar.js#L524) equation to be calculated incorrectly.
Tested on:
N/A

Fixed Horizontal Scrolling on Window Resize for Simple Toolboxes

---

core/variables.js
core/variables_dynamic.js

#2050 
Makes it so the most recently created variable is the one selected in the setter/change blocks.
When you create a new variable, often you want to set that variable immediately. This makes it more convenient. Previously the selected variable would be the first one alphabetically.
1. Created a 'z' variable. Observed how it was selected in the set/change blocks. (pass)
2. Created an 'a' variable. Observed how it was selected in the set/change blocks. (pass)
3. Created a 'b' variable. Observed how it was selected in the set/change blocks. (pass)
Before on step 3, the 'a' variable would have still been selected.
1. Switched the workspace toolbox to dynamic variables.
2. Created an 'a' string variable. Observed how it was selected in the set block. (pass)
3. Created a 'b' number …

Changed New Variable to Default Setter to That Variable

---

core/connection.js

Fixes #2255 
isConnectionAllowed was returning false if the target was already connected to any block, including an insertion marker.  Now it returns false if the target is connected to a non-insertion marker block.
Flickering
Tested in the playground (though this one can definitely also take an actual test).
I'm also going to cherry-pick this into the february release.

Fix insertion marker flickering on value inputs

---

core/trashcan.js

#2291 
Moves contents_ and hasBlocks_ to be declared on the instances rather than the prototype.
contents_ had to be moved because it was only being *modified* by the instances rather than *set*. This means that each instances was modifying the prototype array, rather than its own personal array.
hasBlocks_ was moved because I thought it made more sense that way.
1. Opened multi playground.
2. Deleted a 'controls_if' block from one workspace.
3. Deleted a 'controls_if' block from another workspace. Observed how the trashcan's lid opened slightly (pass)
4. Opened the first workspace's trashcan.
5. Removed the 'controls_if' block. Observed how there was no error. (pass)
Tested on:
I fixed the big problem (declaring contents on the instance rather than the prototype), but I …

Fixed multiple trashcans on the same page leaking state.

---

blocks/procedures.js
core/events.js
core/inject.js
core/options.js
core/utils.js
core/workspace_dragger.js
core/workspace_svg.js
core/zoom_controls.js
tests/playground.html

#2205 
Adds a new "move" object configuration option with the following properties:
* scrollbars: Determines if the workspace has scrollbars. Defaults to true if the workspace has categories.
* drag: Determines if the workspace can be dragged with the mouse. Always false if scrollbars is false (at least in options parsing). Defaults to true if scrollbars is true.
* wheel: Determines if the workspace can be scrolled with the mouse wheel. Always false if scrollbars is false (at least in options parsing). Defaults to false.
Parsing does not currently allow these options to be independent, but you can make them independent by overriding the drag & wheel options after the workspace has been injected. This behavior is supported.
Changes the zoom function so that the zoom is "anchored" to the …

Movement Updates

---

core/mutator.js

Disables any block in a mutator that isn't connected to the root block.
Two-line change.  Not sure why this wasn't done years ago.

Disable orphaned mutator blocks.

---

core/theme.js

Issue with generated JSDoc because of improper format.
Adding space before `{` in JSDoc tags.
`@param{...}` and `@return{...}` were not recognized.
None.

Correcting jsdoc tag spacing

---

core/block_render_svg.js

https://github.com/google/blockly/issues/2302
Fix this.hat check logic
Applied a hot fix to master at https://github.com/jollytoad/blockly, and tested in my app with that repo instead of google/blockly. Hat behaviour restored.
Tested on:

Fix hat logic

---

core/field_dropdown.js

I have following dropdown options
```
[
["no matter", ""]
["Update", "true"]
["Command", "false"]
]
```
In case my value is "" the text is not filled with "no matter" by the initial draw and the empty selector is shown. I expect the text "no matter"
This PR fixes that
Just check if the text_ was initialized and if not => do it.
Invalid drawing if value is ""
the change is so tiny.

Fix error by init of dropdown in case the value is ""

---

core/constants.js
core/flyout_horizontal.js
core/flyout_vertical.js
core/utils.js
core/workspace_svg.js

#2301 
Makes it so that scrolling with line or page delta modes isn't incredibly slow.
Slow is bad.
1 . Set mouse mode to line (windows settings).
2 . Scrolled vertically with mouse on all browsers. Observed how the scrolling looked the same on all browsers. (pass)
3 . Pressed shift and scrolled vertically with mouse on all browsers (shift causes horizontal scrolling). Observed how the scrolling looked the same on all browsers (pass)
4 . Scrolled vertically with touchpad on all browsers. Observed how the scrolling looked the same on all browsers. (pass)
5 . Scrolled horizontally with touchpad on all browsers. Observed how the scrolling looked the same on all browsers except IE 11 (apparently IE 11 doesn't let you scroll horizontally with touchpads). (pass)
1 . Set the mouse mode to page …

Added Scroll deltaMode Multiplier Constants

---

core/inject.js
core/toolbox.js

#2066 and half of #2267 (I wasn't able to reproduce the sticking-on-scroll behavior)
Calls hideChaff when the document is clicked. Also removes the hideChaff call from the toolbox, since that is now handled by the document listener.
Bug fixes are good.
1 . Created a block with a text/number input field.
2 . Selected said field.
3 . Clicked the surface of the document. Observed how the field lost focus. (pass)
4 . Selected the field once again.
5 . Clicked on a category. Observed how the field lost focus. (pass)
6 . Selected the field once again.
7 . Click on a non-category part of the toolbox. Observed how the field lost focus (pass)
8 . Selected the field once again..
9 . Clicked the workspace. Observed how the field lost focus. (pass)
1 . Switched the toolbox view to simple.
2 . Created …

Fixes Block Input Sticking to the Screen When Navigated Away

---

core/field.js

Progress on rendering updates.
Adds a click target property that lets a field specify its click target instead of always using the field group.  
This is useful for single-field blocks in the new renderer, which spread their click target to cover the entire block.
Tested in the playground, both for rendering fields and for clicking on them.

Add click target property to fields, with accessor

---

core/mutator.js

N/A
Adds a little bit of optimization to the workspaceChanged function by having it return on events that don't actually change anything.
Eliminating extra operations is good.
workspaceChanged is called for two purposes A) Rerendering the source block (the one being mutated) and B) Resizing the bubble.
[UI events](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsui) do not affect the composition of the workspace. They also do not affect the size of the workspace. This means the A & B are not neccessary.
[Disable events](https://developers.google.com/blockly/guides/configure/web/events#blocklyeventsblock_change) do affect the composition of the workspace, but by default disabling is not available for workspaces (because they have simple toolboxes, and now an …

Added Event Filtering to workspaceChanged in Mutator

---

core/inject.js

Bug found by Neil.
Check if the object exists before getting its bounding rectangle.
The bump object function runs on events, but it's possible to get a move event and then a delete event, so the block (or comment) that is being inspected has been deleted by the time the bump object function runs.
Neil says this only happens in RTL.  I find that concerning.

Don't try to bump if the object has already been deleted.

---

core/bubble.js
core/flyout_horizontal.js
core/flyout_vertical.js
core/inject.js
core/mutator.js
core/workspace_svg.js

#2280 
You can now only scroll the visible portion of the workspace:
Blocks are always created in the correct position:
Otherwise everything looks the same, but the math is different. Now simple toolboxes and category toolboxes work the same way math-wise and UI-wise, except in the case of zooming where they act different (UI-wise and math-wise).
Should (hopefully) make the coordinate system easier to use in the future. Now you won't have to write special code for flyouts (unless you're writing zooming code).
* Category Flyout Rendering
* Simple Toolbox Flyout Rendering
* Mutator Workspaces
* Bubble Positioning
* scrollCenter
* zoomCenter
* zoomToFit
* Zoom on Wheel
* Zoom then Scroll
* Scroll on Wheel
* Block/Comment Bumping (unmovable workspace bounds)
Tested on:
Note …

Changed Absolute Metrics to Avoid Simple Toolboxes

---

core/workspace_svg.js

#2330 
Makes it so open flyouts are properly positioned & populated when updateToolbox is called on the workspace.
Before the flyouts would not be modified at all, causing visual bugs.
1. Added the expanded="true" attribute to the Logic toolbox category in the "toolbox-categories" toolbox at ~ln 430 in playground.
2. Added the expanded="true" attribute to the Basic toolbox category in the "toolbox-test-blocks" toolbox at ~ln 1113 in playground. 
3. Added the below code at ~ ln 146 in playground:
```
function test() {
var categoriesTB = document.getElementById('toolbox-categories');
var testTB = document.getElementById('toolbox-test-blocks');
Blockly.getMainWorkspace().updateToolbox(testTB);
}
```
4. Refreshed the playground in chrome:
and ran the test() command in console. Observed how it …

Fixed updateToolbox Not Properly Updating Flyouts

---

core/blockly.js

#2331 
Check for a workspace before trying to refresh the theme on all the blocks and categories in the workspace.
Blockly.setTheme was throwing an error when the workspace had not yet been created.
Tested on:
Desktop Chrome

Set theme fix

---

tests/rendering/svg_paths.html

Makes debugging block paths less painful.
Creates a page with a grid that makes it easy to draw paths defined in Blockly core.  It looks like this:
You can add a path:
```
addPathAt(Blockly.BlockSvg.TAB_PATH_DOWN, 0, 0);
addPathAt(Blockly.BlockSvg.START_HAT_PATH, 0, 40);
addPathAt(Blockly.BlockSvg.NOTCH_PATH_LEFT, 0, 60);
addPathAt(Blockly.BlockSvg.NOTCH_PATH_RIGHT, 0, 70);
addPathAt(Blockly.BlockSvg.INNER_TOP_LEFT_CORNER, 0, 90);
```
The path renders with a red dot at the beginning and a blue dot at the end (helpful for working with paths that run LTR or RTL).
We consistently hear people asking if they can tweak the block connections.  It is much easier to do this when you can see what the different parts of the path evaluate to.
Also, I'm working on rendering again and I needed this.

Add a playgound for debugging SVG paths

---

generators/dart/math.js

Resolves #2329
Commit in develop branch
Resolves [issue #2329](https://github.com/google/blockly/issues/2329) by replacing Python references with Dart references in the Dart math generator. 
Resolves [issue #2329](https://github.com/google/blockly/issues/2329).
Resolves [issue #2329](https://github.com/google/blockly/issues/2329).
Tested on:
Desktop Firefox (Firefox 65.0.1 on Windows 10 1803)
Tested with Blockly's tests for generators for math, interpreting dart.
Testing was done on Firefox according to Blockly's Unit Tests for generators, [here](https://developers.google.com/blockly/guides/modify/web/unit-testing). Only tested for Dart math, as that was the only generator changed. Running code on DartPen has end output of "OK".

Remove Python references in Dart math generator

---

core/flyout_horizontal.js
core/flyout_vertical.js

#2345 <- Best issue number evaaar.
Makes it so the trashcan flyout is positioned correctly (aligned with the edge of the blocklyDiv)
It looks ugly otherwise.
Categories, Small Flyout
Categories, Big Flyout
Simple, Small Flyout
Simple, Big FLyout
Tested on:
N/A

Fixed Trashcan Flyout Positioning

---

.eslintrc.json

The builds was failing because a url was over the max length line limit.
Add ignoreUrl to eslintrc files.
So we can now add urls to comments without having to break into multiple lines.
Tested on:

Ignores urls for eslint

---

core/css.js

Increases the margins on selected menu items by 1 to match a recent change to the unselected sizes.
Fixes #2351 
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2353)

Update selected menu sizing to fix #2351

---

core/block.js
tests/jsunit/block_test.js

#2336 
Currently, we are looking at all value inputs on a block. If there is more than one value input then we return null which means that we don't have a connection to reattach to the parent block. The proposed fix is to only look for value inputs that have something connected. In the case that something is connected we want to return that connection so that we can reattach this block to the parent. 
When there was a block with more than one value input the block that was connected to the insertion marker would not get reattached to the parent. Therefore when we hid the insertion marker the block would disappear with it. 
Tested on:

Adds check for a targetConnection

---

core/workspace_svg.js

https://github.com/google/blockly/issues/1101
Renames instances of ".getFlyout_" to ".getFlyout"
Due to issue #1101

Rename WorkspaceSvg.getFlyout_ to WorkspaceSvg.getFlyout

---

core/inject.js

#2066 & #2312
Previously this was fixed in #2286, however it was breaking context menus. Clicks on context menus were not being processed because the document mousedown function was calling Blockly.hideChaff() before the context menu mouse up event could process the user’s click. The closure context menus use 'mouseup' to process the user's click. We therefore need to use mouseup so that the click on the context menu can be processed before we call Blockly.hideChaff() in the document mouseup event handler. 
We can’t use the Blockly.bindEvent functions because it changes mouseup to be pointerup which we can't use because the closure menus use mouseup. If we used pointerup then the context menu click would not be guaranteed to execute first and we would have the same problem with context …

Hides chaff on document mouseup

---

core/rendered_connection.js

#2290 
Previously we were just taking the negative value of dx when in RTL. As far as I can tell this only works the first time that we bump a block. The next times that we bump a block the x value of the output connection is farther to the left(because of the previous bump) while the place that we want to get to (staticConnection.x_ + snap_radius + random number) is moving farther to the right. So when we take the different between the two it is getting larger and larger creating the unnecessarily large bump.
The proposed fix is to change subtract the snap_radius and random number instead of adding them. This way our target is in the same direction as the block is moving. Which will create a smaller bump.
Some blocks in RTL were getting bumped too far.
Tested on:
Desktop Chrome

Fixes bumping too much when in RTL

---

core/css.js

Fixes #2337 by adding in correct positioning for RTL selected states
and fixing an incorrect margin value.
#2337 
Update some of the css for RTL dropdown menu items.
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2356)

Fix margins/checkbox in RTL dropdown menus

---

core/field.js

#2368
Fixes a small grammar issue in documentation in field.js
The typo bugs me.
N/A?
<Tested on:>
N/A

typo fix in line 134 of field.js for documentation

---

core/flyout_horizontal.js
core/flyout_vertical.js
core/mutator.js

#2377 
Makes it so the mutator is positioned correctly in RTL once again.
Before it overlapped the workspace blocks and other bad things.
Tested on:
PR #2349 (which fixed the trashcan flyout positioning) added a check to see if the flyout's toolbox positioned match its target workspace's toolbox position (that is, if it was the toobox flyout). The problem was the mutators weren't returning what their toolbox position was, so the flyout was assuming it wasn't the toolbox flyout, causing it to position itself incorrectly.

Fixed Mutator Flyout Being Positioned Incorrectly RTL

---

core/field_number.js
tests/blocks/test_blocks.js
tests/playground.html

#516 also #1945 which is a dupe.
Makes it so numbers are rounded to a fixed decimal place before being returned to eliminate visible floating point errors.
I also moved the clamp to be above the precision check, for reasons discussed in #516.
Floating point errors are confusing and ugly.
The numbers section of the fields test blocks category now has some additional blocks. The integer block has also had its label changed to 'precision 1'.
Old Validator:
New Validator:
**Note the extra .0 on the 'precision 1.5' block.** This may or may not be desirable, and I'm happy to change it.
Tested on:
N/A

Fixed Visible Floating Point Errors in Number Fields.

---

core/field.js
core/field_angle.js
core/field_colour.js
core/field_label.js
tests/blocks/test_blocks.js
tests/playground.html

Work on #1623
Adds an isDirty_ property to a field to tell if the field needs to be rerendered.
Also does some cleanup on angle, colour, and label, which weren't conforming to standward.
Checks the circumstance of: not dirty, visible, but width = 0, because this probably means someone is using the old rerender method. It then logs a warning, and does the render anyway.
Before if you wanted to rerender a field you had to set its size_.width property to 0. This was inconvenient, and confusing because size_.width would also be zero when the field was not visible (unrelated to rerendering). 
I wasn't exactly sure how to test this since it isn't really a functional change just a structural one, so I just decided to create test blocks for all the fields that didn't have one yet. They are all …

Added isDirty_ Property to Fields

---

core/block_svg.js
demos/blockfactory/app_controller.js

[Issue #2388](https://github.com/google/blockly/issues/2388) - Comments should be allowed on non-movable/deletable blocks
Regardless of deletable state:
* Add the "Add Comment"/"Remove Comment" menu items whenever the block is editable and not collapsed.
* Add the "Expand Block"/"Collapse Block" menu items whenever the block is movable.
* Add the "Inline Inputs"/"External Inputs" menu items whenever the block is movable and not collapsed.
* Add the "Disable Block"/"Enable Block" menu items whenever the block is editable.
Block Factory:
* Turned off comments and block disabling in the Blockly.inject() call.
Previously, most of the context menu entries required that the block must be movable and deletable in addition to being editable. However, there's no compelling reason for these strict …

Reorganize conditionals for block context menu

---

core/ast_node.js
tests/mocha/astnode_test.js
tests/mocha/index.html

- [] I branched from develop
- [] My pull request is against develop
Adds an AST Node for keyboard navigation. An AST Node will be able to find the next, prev, in, or out node from its current location. 
To create a better keyboard navigation api.
Tests are written in mocha.
Tested on:

Keyboard nav ast node

---

demos/rtl/index.html

#2387 
Makes it so the blocks are now positioned correctly in RTL.
Blocks being positioned behind the toolbox looks bad.
Tested on:

Moved RTL Demo Blocks so They Aren't Behind the Toolbox

---

core/flyout_base.js
core/toolbox.js

#2396
Makes it so that button and label flyout elements obey sep elements.
I also changed flyout XML parsing so that it uses a switch statement so that it matches the toolbox XML parsing.
If you have a lot of buttons stacked on top of eachother it can make your flyout look pretty cluttered. It would be nice to be able to set the gap between them to be smaller.
XML for this testing: (default gap is 24)
```
<category name="Separation">
<block type="logic_compare"></block>
<sep gap="32"></sep>
<block type="logic_compare"></block>
<sep gap="8"></sep>
<block type="logic_compare"></block>
<button text="button" callbackKey="logCallback"></button>
<sep gap="32"></sep>
<button text="button" callbackKey="logCallback"></button>
<sep gap="8"></sep>
<button text="button" …
```

Changed Buttons and Labels to Respect <sep> Elements in Toolbox

---

core/generator.js

#2339
Update documentation so that we are more clear statementToCode is used in generators.
Multiple forum posts showing that people were confused about the usage.
Tested on:

Documentation update

---

core/navigation.js
tests/mocha/astnode_test.js
tests/mocha/index.html
tests/mocha/navigation_test.js

Desired functionality for keyboard navigation.
Move cursor to workspace when E pressed in toolbox or flyout.
Add `shouldHide` param to `Blockly.Navigation.resetFlyout`.
If there was a selected block on the workspace the cursor goes to that block.  Otherwise it goes to a fixed location on the workspace.
Add a test file for navigation, and a basic test.
Stub `getMainWorkspace` for AST Node tests, and restore it at the end of the tests.
We needed a way to exit the flyout/toolbox without inserting a block.
Added mocha test.

Kb exit toolbox

---

blocks/loops.js
blocks/procedures.js
core/block.js
core/block_events.js
core/block_svg.js
core/events.js
core/flyout_base.js
core/xml.js
tests/workspace_svg/procedure_svg_test.js

[Issue #1593](https://github.com/google/blockly/issues/1593)
From [Issue #1593](https://github.com/google/blockly/issues/1593), provides the negated version of `setDisabled` with `setEnabled`. 
`setDisabled` is deprecated in Block.prototype, and BlockSvg.prototype.
Calls to `setDisabled` have been updated to use `setEnabled`.
From [Issue #1593](https://github.com/google/blockly/issues/1593), removes double-negation in this instance.
**Blockly Tests**
PASSED JSUnit test
PASSED Workspace_SVG test
**Playground Testing**
Playground Test:
Disabled Blocks still enable/disable fine.
Loading disabled/enabled blocks though XML is fine.
Tested on:
Browsers:
- Desktop Chrome v73
- Desktop Firefox v66
Device: Windows Laptop
OS: Windows 10 v1803
`setDisabled` has only been deprecated. The original …

Add Block.setEnabled

---

blocks/procedures.js
core/field.js
core/field_angle.js
core/field_dropdown.js
core/input.js

#2381 
Removes setVisible from the public API. This change applies to inputs and fields but not from icons (comments, mutators, warnings, etc), scrollbars, flyouts, or workspaces.
In doing so this removes a [setVisible call from the procedures_defnoreturn](https://github.com/google/blockly/blob/9c4f9d6c1693c3c25160f008d3eaa2539127c9e8/blocks/procedures.js#L175) block.
Also cleans up setVisible within fields. Some of the setVisible logic was leaking into the render() function because of the old way of re-rendering fields (setting their width to zero) it has now been moved back to the setVisible function.
Set visible should not be used to hide fields or inputs, it should only be used when collapsing a block.
Tested collapsing blocks:
Tested the procedure block mutator:
On Develop:
On This …

Removed setVisible (fields, inputs) from the Public API

---

core/field.js
core/field_variable.js
core/xml.js

#1627 
Adds fromXml and toXml methods to fields that Blockly.Xml.domToField_ and fieldToDom_ can call.
Also changes the playground over to the new value-attribute rather than textContent based xml because... I thought it would be nice I guess ¯\\\_(ツ)_/¯
Some fields (e.g. variable fields) need more information to be serialized to xml than just the field name and value. This adds functions that custom fields can override so people can impliment more advanced fields without having to change the core.
Added backwards compatibility mocha tests:
Also here's a gif of some things serializing and deserializing:
That generated this XML:
```
<xml xmlns="http://www.w3.org/1999/xhtml">
<variables>
<variable type="" id="4=m(NP7VfKepgVGbq99y">am i item?</variable>
</variables>
<block …
```

Added fromXml and toXml to Fields

---

core/flyout_base.js

N/A
Makes it so buttons that come after labels in a flyout are correctly rendered as buttons and not labels.
Before (meaning after I changed flyout parsing to a switch statement, but before this change) the flyout would be rendered like this:
Tested on:

Fixed Buttons Being Rendered as Labels if They Come After a Label

---

core/block_render_svg.js
core/block_svg.js
core/insertion_marker_manager.js
core/navigation.js
tests/mocha/astnode_test.js

Previously the block stack would move to 100, 100 on the workspace if the new block was being inserted at the start.
Use the same code that we use to solve this problem for insertion markers.
I moved the helper function and changed its signature because it had an unnecessary param before.  That's the first commit.  The second commit uses it.
Remove extra `connect` calls in `insertBlock`--`connect` moves the `orphanBlock` around internally.
Blocks need to stay in the same place as new blocks are connected.
I had to add a call to `render` so that the new block's connection positions are correct internally.  That I expected.  I also had to explicitly set the connections to not be hidden, which I didn't expect.  The connections are hidden in `domToBlock` and unhidden …

 Position correctly when inserting before another block (from the flyout)

---

core/block_svg.js
core/cursor.js
core/cursor_svg.js
core/inject.js
core/navigation.js
core/workspace_svg.js

Progress on keyboard navigation.
Add a `marker` to the workspace as well as the `cursor`.  A `marker` is a type of `cursorSvg` that cannot be moved with prev/next/in/out.  It can only be moved directly to known locations with `setLocation`.
When the user hits enter to mark a location on the workspace or a connection on a block, the marker renders.  It disappears again when the user inserts a block at that marker.
It's important to know where your insertion location is when you're inserting blocks.
Tested in Chrome

Add a marker that shows where the user has marked on the workspace

---

core/block.js
core/block_svg.js
core/field.js
core/field_dropdown.js
tests/blocks/test_blocks.js
tests/playground.html

Work on #1623 and sorta #1456
Adds a function so fields can be coloured based on the colour of their block.
Also creates dedicated functions for getting a blocks shadow and border colours. This way if more things in the future need access to this logic it's all in one place.
More efficient than rerendering every field when the colour updates & separates responsibilities.
I added buttons to the default fields category so styles, enabling/disabling, and shadowing/unshadowing could be tested.
Classic:
Classic, style randomized:
Classic, shadow true:
Classic, shadow false (everything renables correctly):
Modern:
Modern, style randomized:
Modern, shadow true:
Modern, shadow false (everything renables correctly):
Tested on:
Currently fields do not react to their block being …

Added updateColour to Field

---

core/ast_node.js
tests/mocha/astnode_test.js

Out cleanup
Fixes out functionality for blocks, previous connection, next connection(all same problem) and output connections.
Out functionality on ast was not working properly.
Added tests in mocha.
Tested on:

Out cleanup

---

core/ast_node.js
tests/mocha/astnode_test.js

Fixes: 
1. Going from empty workspace to stack 
2. Dealing with blocks that don't have editable field or input with connections
3. Simplifies finding the top ast node for a block 
Adds tests in mocha
Tested on:

Cleanup for in functionality

---

.travis.yml
package.json
tests/generators/run_generators_in_browser.js
tests/jsunit/run_jsunit_tests_in_browser.js
tests/scripts/get_geckdriver.sh

Fixes #2283 
Fixes #2117
Fixes #2118
- update webdriverio to v5
- switch to async/await syntax in our testing files--v5 doesn't support chaining
- update geckodriver--the older version didn't work with newer webdriverio
Webdriverio v5 had some pretty significant changes: https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html
I want to get to v5 for two reasons: first, so that we don't get completely stale and second, because it looks like running mocha tests on travis will be easier with v5.  Now that both Abby and Beka are writing those tests regularly, I want them to run on all PRs.  This is a step in that direction.
Generator tests and jsunit tests pass.  I also checked to make sure I could make them fail.

Update to webdriverio v5; fix resulting test breakages

---

core/variables.js
tests/mocha/xml_test.js

N/A
Removes explicitly setting the variable type to two single quotes.
Before the toXml/fromXml pr went in there was a check in domToFieldVariable_ to change an string containing two single quotes to an empty string, with a comment that maybe this wasn't necessary. I believe the only purpose of that chunk of code was to undo the thing that I am removing now (where the string containing two double quotes is created).
This all seems a bit weird though so I'm not sure if there was a secret purpose behind it. I did check the git blame and found the [original PR](https://github.com/google/blockly/pull/1495/files), but I didn't see any information about why it was set up this way.
I discovered this because field_variable's fromXml was throwing an errow when it was trying to deserialize the …

Removed Explicitly Setting Variable Type to Two Single Quotes

---

build.py
core/block_render_svg.js
core/blockly.js
core/flyout_base.js
core/generator.js
core/xml.js

Realtime collaborators are liable to independently generate blocks with the same IDs due to the IDs being encoded in XML.  This PR fixes IDs in toolboxes and IDs in cut/copy/paste.
Also included are a couple of other minor cleanup commits that result in no functional changes.

Reduce ID collisions.

---

core/ast_node.js
tests/mocha/astnode_test.js

Fixes next functionality for fields and inputs. 
Makes navigateBetweenStacks return null if it gets to the last stack in the workspace instead of wrapping.
Cleans up next, previous, and block functionality.
Tests written in mocha.
Tested on:

Next cleanup

---

.eslintignore
tests/mocha/block_test.js
tests/mocha/index.html
tests/mocha/run_mocha_tests_in_browser.js
tests/run_all_tests.sh

Run mocha tests with webdriverio (the same way we run jsunit and generator tests) and check the results.
Not all of our tests actually need to be run in a browser, but some do, so right now we're running all of them in the browser.  Both mocha and jsunit tests can be run locally by opening their respective `index.html` files.
Another step in moving from jsunit to mocha.
Added mocha tests, and ran with tests broken and all tests passing.
The first push of this should have a broken test, to make sure it works.  Then I'll fix that test and push to make sure it works when tests pass as well.

Add mocha tests to npm test

---

core/blockly.js
core/navigation.js
tests/mocha/navigation_test.js

Fixes getting into a bad state when exiting the toolbox or flyout with escape.
If we're in accessibility mode, give the navigation key handler a chance to handle the escape key (in addition to Blockly's normal call to hideChaff).
Exiting the toolbox with E worked differently from exiting with ESC before.
Mocha tests added.

Handle escape in the toolbox/flyout.

---

core/ast_node.js
tests/mocha/astnode_test.js
tests/mocha/index.html

1. Fixes previous for field and input
2. Output can't have a previous connection 
3. Adds checks for non null connections on block and previous.
Tests written in mocha. 
Tested on:

Cleanup for previous

---

core/ast_node.js
core/navigation.js
tests/mocha/astnode_test.js

Store whether an ast node points to a connection on the node, and add a getter.
This is a pretty common check and easy to know from the type.
Helper function
Added checks to the ast node constructor tests.

Helper to check whether an ast node points to a connection

---

core/field.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_variable.js
tests/playground.html

#1010
Moves init logic into an initView function. The init function now calls initView and initModel.
I also had to change the emoji testblocks category label because apparently IE just couldn't handle the beauty of it.
Firstly makes the lifecycle more clear. Secondly the abstract init() function now creates the field group, so fields that want to do custom dom structures (e.g. not include the border rect or text element) don't need to remember to create a field group named 'fieldGroup_'.
Looked through test blocks and assured that everything was rendering correctly. RTL and LTR
Also ran mocha tests locally.
Tested on:
* Windows Edge
[Here](https://i.imgur.com/izzAxcV.jpg)'s a picture of how the flow works now.
If the field …

Refactored field.init into field.initView and field.initModel

---

core/cursor_svg.js
core/navigation.js
core/rendered_connection.js

Changes include: 
1. Fixes block being positioned incorrectly when an output connection is selected 
2. Deselects the selected block when in accessibility mode
3. Removes CURSOR_REFERENCE 
4. Adds getOffsetInBlock so we don't have to use private variables
Tested on:

Small bug fixes and cleanup

---

core/navigation.js

Inserting a block when no location was marked was previously a no-op
If no location is marked when opening the toolbox/flyout, mark the current cursor location.
Also unify some code for inserting on ws vs at a connection.
This seems like a reasonable guess at the user's intent.

Mark the cursor location when opening the toolbox; cleanup

---

core/navigation.js

Wrap all calls to console.log and console.warn so developers can optionally handle them instead.
We don't know what showing errors and warnings will look like, but it probably won't involve the console.  This gives us a unified API for developers to work with for error and warning handling.
Tested in the playground to make sure that the default is to log to the console, and that the callback happens if defined.

Add wrapper functions so developers can override warning and error handling

---

core/navigation.js

There is currently no way to get to the flyout when we do not have a toolbox.
Adds the ability to go to the flyout directly if no toolbox is available. The user would get there by hitting T. 
Tested on:

Fixes case where we do not have a toolbox

---

core/cursor_svg.js

Having the cursor for a stack and a block be the same can be pretty confusing when trying to navigate through the blocks. 
Make the cursor for a stack cover the entire stack of blocks as well as make it slightly cover a slightly larger area than the block. 
Tested on:

Changes the cursor look for a stack

---

core/navigation.js
tests/blocks/test_blocks.js
tests/mocha/.eslintrc.json
tests/mocha/index.html
tests/mocha/navigation_modify_test.js
tests/mocha/test_helpers.js
tests/playground.html

I'm working on unifying all of the `insertBlockToWs`, `insertBlockFromWs`, etc. code into a single function, `Blockly.Navigation.modify`.  That function acts based on the state of the cursor and the marker.  I'm currently assuming that it will return a boolean specifying whether it actually made a change (or whether it made the expected change?) but that's still flexible.
This is a start on tests for this, so that we can lay out the desired behaviour.  I'm still adding more, but want to get this out for comment.
The first commit has tests for the marker being on a previous or next connection, and the cursor being on a workspace, block, previous connection, next connection, or output connection.

TDD: tests for navigation insert/modify, currently skipped

---

core/cursor.js
core/navigation.js
tests/mocha/cursor_test.js
tests/mocha/navigation_test.js

We had too many different areas that were all doing in, out, next, prev functionality of some sort. 
Moves the user facing logic for moving around the workspace to the cursor instead of in the navigation file. 
Changes the key handling WASD keys. 
Fixes a insertFromWs test case.
Tested on:

Moves navigation logic to cursor

---

core/field_checkbox.js
core/field_colour.js
core/field_date.js
core/field_image.js
core/field_label.js
core/field_label_serializable.js
core/field_textinput.js
tests/mocha/field_angle_test.js
tests/mocha/field_checkbox_test.js
tests/mocha/field_colour_test.js
tests/mocha/field_date_test.js
tests/mocha/field_dropdown_test.js
tests/mocha/field_image_test.js
tests/mocha/field_label_serializable_test.js
tests/mocha/field_label_test.js
tests/mocha/field_number_test.js
tests/mocha/field_textinput_test.js
tests/mocha/field_variable_test.js
tests/mocha/index.html
tests/mocha/test_helpers.js

Work on #2169 specifically [this](https://github.com/google/blockly/issues/2169#issuecomment-488471207).
Adds tests to document how fields should react to different values.
Also clarifies which fields have default values and which do not.
Tests needed to be added before #2441 possibly breaks the world.
So... a lot of these tests are actually failing! But that's not because the tests are broken, it's because the fields are broken.
Examples:
* Most validator tests fail because atm most fields don't validate unless they are attached to a block. ([link](https://github.com/google/blockly/issues/2169#issuecomment-491080867))
* All checkbox field tests are failing because checkboxes don't handle their text_ properly.
* Lots of fields have less severe checks on setValue than …

Added Field Value Tests

---

.gitignore
tests/screenshot/diff-reporter.js
tests/screenshot/diff_screenshots.js
tests/screenshot/diff_viewer.html
tests/screenshot/gen_screenshots.js
tests/screenshot/mocha.opts
tests/screenshot/run_differ.sh
tests/screenshot/test_cases/math_subtraction
tests/screenshot/test_cases/test_cases.json

^ None of these, but the style guide doesn't currently apply in this directory.
- Use a `test_cases.json` file to specify which tests to run.
- Use a custom reporter for mocha to output test results in a way that's easy to use.
- Use those results in `diff_viewer.html`.
- Make sure folders exist
- Automatically open `diff_viewer.html` after running tests

Load a list of tests to run from a file; connect test output to dif-viewer

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_draw_debug.js

Debug rectangles were handy if you were rendering a block once, but failed if you were testing how a block resizes in response to changes, because they just kept piling up on top of each other.
Turn the debug namespace into a class and save an instance of it on the block.  Use that instance for repeated debugging, and clear old nodes and references to them before drawing new ones.
I didn't try to match new nodes to old nodes and just update the old values, mostly because this is easier and less likely to act strangely around mutators.
I also added documentation to all of the functions in `block_rendering_debug.js`.
Make debug visualizations useful in more cases.

Clear debug rectangles before rerendering

---

core/block_rendering_rewrite/block_render_draw_debug.js
tests/playground.html

Like the logEvents checkbox, it persists its state across reloads.
It controls both rectangles and connection dots.

Add a checkbox to toggle rendering debug visualizations in the playground

---

tests/screenshot/gen_screenshots.js
tests/screenshot/mocha.opts
tests/screenshot/run_differ.sh

Use the first argument to `run_differ.sh` to filter tests.
So that we don't have to get as many screenshots to see specific test cases, or scroll through piles of screenshots when we're only interested in a few.
Part of screenshot testing.
Sample usage:
`tests/screenshot/run_differ.sh controls`

Filter tests based on command line argument

---

core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js

- top left corner highlight was too thick on a square corner
- empty rows between statement inputs were too short
- fields were centered vertically in rows.  It's good to be able to do it, but this change makes it match the current rendering and leaves a clear place to change field vertical alignment.
- topRow no longer has a `squareCorner` property, so check the element instead
- One extra condition in `getSpacerRowHeight_`
- pull centerline calculation out into its own function

Rendering tweaks

---

tests/screenshot/diff-reporter.js

The test reporter was dereferencing something it couldn't find (but only when tests passed) and failing with no helpful warnings.  We only found this when we got a test to pass for the first time.
Also, the color used by the reporter for passing tests is exactly the same as my terminal background so I couldn't see it.  Which is funny, but not useful, so I changed it from dark grey to green.  It should be fine on a white background as well.
Directly add the code for coloring outputs and displaying checkmarks, instead of trying to reference it and failing.
Tests broke when I asserted that 0 equaled 0.  This made me unhappy.

Make the test reporter function when tests pass

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js
core/block_rendering_rewrite/measurables.js
tests/screenshot/test_cases/test_cases.json

Turns the bottom row into a row so that it can hold elements such as corner and next connection.
Tested on:

Refactors bottom row to be a row instead of measurable

---

core/utils.js

Chrome returns `transform: translate(107px, 0px);` whereas Firefox now returns `transform: translate(107px);` if the y value is 0.  This is consistent with existing behaviour in the translate SVG attribute.
The comment in our code specifically states:
`// Accounts for same exceptions as XY_REGEX_`
Yet that was not true at all.
This PR makes the y argument optional (as falsely described in the comment).  It also merges the 2D and 3D regeps together to simplify the code.
Resolves issue #2482.  Needs to be cherrypicked to Master and everything rebuilt and pushed.

Fix style matching in Firefox 67

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js
core/block_rendering_rewrite/measurables.js

Problem where the bottom row after statement input with inputs in line is always length of the block.
Add a max length to the bottom row so that it doesn't exceed that length. This way if someone adds a lot of inputs the bottom row will not be as wide as the entire block.
It is how we have it in current rendering.
Tested on:

Restricts bottom row length after a statement input

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_info.js
core/field.js
core/field_colour.js

Image and colour fields were rendering wrong.
Add a `getCorrectedSize` function for images and add them to the list of jackass fields--they're placed to the left of their ostensible top-left corner.
Add padding between pairs of non-editable fields.

Fix colour and image fields

---

core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_rendering_constants.js

Fixes highlight on the bottom row and an extra highlight on bottom rows following statement inputs in RTL. 
Subtract offset from the height of the bottom row when drawing a rounded corner or when in rtl. 
Tested on:

Fixes highlight for bottom row

---

core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/measurables.js

Dummy inputs were not getting aligned properly.
Add the input to the field measurable so that we can get the alignment information for dummy inputs. Depending on whether the row has an external input or not add missing space to the last spacer or the spacer before the external input.
Dummy inputs were not getting aligned properly.
Tested on:

Adds alignment padding to dummy inputs

---

.travis.yml

Tests are currently failing on master
Explicitly use node 8 and node 10.  Travis now uses node 12 by default, and that breaks with gulp.
We previously ran into this problem on develop.  I think we hadn't seen it on master because the tests only run when we push to master, and we haven't done that in a while.
See #2403
Tests should pass on travis.

Set node version explicitly for travis on master

---

core/field_colour.js
tests/mocha/field_colour_test.js

N/A
Makes it so the class validator accepts any string that can be parsed by [goog.color](https://google.github.io/closure-library/api/goog.color.html).parse. If it can be parsed it converts it to #rrggbb format.
I noticed that the [documentation ](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#colour_picker_field)stated any css colour string was valid, so I wanted to make sure the colour field still worked if people had defined their colours that way.
I did not change the documentation of the field constructor, because I think it's best if people input strings in #rrggbb format, because that's the format validators will need to parse.
Added tests for strings: '#AA0', '#aa0', 'rgb(170, 170, 0)', and 'red'.
N/A

Changed Colour Field Class Validator to Accept all Documented Values

---

core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/measurables.js

The highlight on the bottom of a statement input was not being displayed.
Have the spacer draw a highlight if it follows a statement input.
Tested on:

Draws highlight on the bottom of a statement input

---

tests/screenshot/gen_screenshots.js
tests/screenshot/run_differ.sh
tests/screenshot/test_cases/colour
tests/screenshot/test_cases/lists
tests/screenshot/test_cases/logic
tests/screenshot/test_cases/loops
tests/screenshot/test_cases/math
tests/screenshot/test_cases/procedures
tests/screenshot/test_cases/test_cases.json
tests/screenshot/test_cases/text
tests/screenshot/test_cases/texts
tests/screenshot/test_cases/variables

- Use less verbose logging for webdriverio
- Use `xdg-open` vs `open` based on OS ( I hope--need someone to test it on a mac)
- Delete empty tests

Remove empty tests; clean up logs; open based on OS

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_info.js

New rendering couldn't handle insertion markers before.
Hide fields and icons on insertion markers.
Insertion marker color seems to be handled by css.

Render insertion markers

---

core/field.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_textinput.js

Changing the field value didn't update the appearance of the field, even though the value was changed internally.
Call `getSize` from `getCorrectedSize`
`getSize` rerenders the field if necessary.  I don't want to duplicate its internal logic, especially since that's an active area of code, so I'm just calling it here.
Another option would be to call `getSize` and then `getCorrectedSize` in sequence in `measurables.js`.  That would put it in only one place, which would be nice, but it's also a weird place for it.

Call getSize in getCorrectedSize

---

core/block_rendering_rewrite/block_render_draw.js
core/field_checkbox.js

It looked like this before:
- Add checkboxes to the list of jackass fields.
- Override `getComputedSize` to include the size of the border rect.
Checkboxes were allocated too little space, and offset when rendered.
test_fields_checkbox screenshot diff now passes.

Fix checkbox rendering

---

core/field_number.js

N/A
Readds reevaluating values when number field constraints are set.
This was removed because of #2392, but it can now function properly, and people may be relying on it, so I have readded it.
This change is already covered by the Number Fields > setValue > Constraints tests.
N/A

Readded Reevaluating Values when Constraints are Set

---

core/field_date.js
tests/blocks/test_blocks.js

N/A
1) Moves the date picker from the widget div to the dropdown div.
2) Removes the automatic closing of the picker upon selection (this comes with some tradeoffs).
3) Makes the picker look butiful (maybe?)
Note: The darker colour denotes "Today" and the lighter colour denotes the selected day. It is based on how G-cal's mini-calendar looks:
1) The date field was sad because it wasn't in the dropdown div club.
2) Makes it so the dropdown div works consistently.
3) Sticking with the old UI meant one of two options had to be picked:
Both of which look ugly (imo).
The closure date picker is missing some functionality that we need, which is the ability to undo a date selection. Because there's no perfect way to do this, the date field has some quirky behavior when dealing with null …

Moved the Date Field to the Dropdown Div, and Restyled It

---

core/field_angle.js
core/field_textinput.js

N/A
1. Fixes the angle offset property.
2. Angle field now displays wrapped values correctly.
3. Fixed the gauge not displaying correctly at high angle values (like the millions or something, only applies to text input)
4. Angle field now displays zero if given empty text input.
1. It was broken. (The below is a clockwise angle field)
2. It was always displaying between 0 and 360. It's pretty confusing if it changes when you close th editor.
3. This just bugged me.
4. Angle fields should always display a number value (this is different from pure text inputs, which can be empty).
I tested lots of combinations of CLOCKWISE, OFFSET, and WRAP. Here are some highlights:
* Clockwise, Offset 90
* Widdershins, Offset 90
* Widdershins, Wrap 180
* Widdershins, Wrap 180, Offset 90
And here's it now …

Angle Field Fixes

---

core/field.js
core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js

#2428 and some collapse/expand problems
1. Makes it so visibility (return a size of 0) is handled inside getSize instead of inside setVisible.
2. Changes (public) updateWidth to (protected) updateSize_.
1. There were problems with collapsing when it was done the previous way. Now all blocks are expanded and collapsed correctly.
2. Makes it less confusing for outside developers who want to create a field with a dynamic height.
Note that the dropdown field's updateWidth function wasn't getting called from anywhere, so it could be safely removed.
I also tested collapsing and collapsing all of the default categories, and it all looks good.
Tested on:
Was not able to test on internet explorer or edge because of #2499
N/A

Fixed How Fields Handle Size

---

core/field.js
core/field_variable.js
core/xml.js

N/A
Has xml.js handle serializing the field's name.
Expecting every field that overrides toXml to remember to save the name is error prone.
Covered by mocha serialization tests.
N/A

Moved Serializing the Field's Name up to xml.js

---

core/field.js
core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_textinput.js
core/gesture.js
core/tooltip.js
tests/jsunit/gesture_test.js

#2484 plus some other changes.
1. Adds separate functions for creating border rects and text elements.
2. Adds fieldBindEvents_ and doEventBinding_ functions to the field.
4. Adds tooltip support to all fields.
3. Moves updateEditable, setTooltip, and event binding calls out of initView and into init.
5. Removes the field is editable check from isFieldClick inside gesture.
Field Specific Stuff:
1. Fixes the angle field, with regard to #2484
1. Changes the checkbox to use the textElement_.
2. Removes the textElement_ from the colour field.
3. Reorganizes dropdown initialization so that dom creation happens inside initView and rendering just modifies it.
4. Removes tooltip handling from image.
5. Image onClick handlers use the showEditor_ function instead of having their own event binding. …

Reorganized Field View Initialization

---

core/field_dropdown.js

#2527 
Readds dropdown arrow padding.
Never supposed to be removed.
Tested on:
I don't know if this is /the best/ way to handle padding, but it's how it worked before.

Fixed Dropdown Arrow Missing Padding

---

tests/screenshot/test_cases/multi_block_1
tests/screenshot/test_cases/multi_block_logic
tests/screenshot/test_cases/not_true
tests/screenshot/test_cases/test_cases.json

New tests cases with a few block combinations.  
Note that these are bigger than the 500x500 window size I picked for screenshot tests, so I may revise that upward at some point.

Add new test cases

---

core/field_angle.js
core/field_colour.js
core/field_date.js

N/A
Removes extra calls to `hideWithoutAnimation()` and `clearContent()`
Duplicate work is bad.
Every gesture starts with a call to hideChaff, which calls `hideWithoutAnimation`, which calls `clearContent`. So there's no reason for fields to call hide as well.
Here's a gif of before (observe the duplicate calls):
And a pic of the logs:
Here's a gif of it still working (observe no duplicate calls):
Tested on:
N/A

Removed Extra DropDownDiv Calls

---

core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js

Tests passing: 65/109 -> 77/109 in LTR
- Increase padding between an icon and end of row (changes min width)
- Set padding between a notch (prev or next) and the end of a row (changes min width)
- Adjust padding between a notch (prev or next) and the beginning of the row (addresses misalignment)

Block min width; notch offsets

---

core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js

In current rendering, text on inline inputs and statement inputs is placed a set distance below the top of the row.  I had two different constants for this, but that was masking a different error.
If/when we switch to vertically centering the fields in a row, this goes away entirely.

Fix text y location on statement inputs

---

core/block_rendering_rewrite/block_render_draw.js
core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js
core/block_rendering_rewrite/measurables.js

Changes:
- Add the shadow/dark path size to the reported size of all blocks (in block_render_draw)
- Vertically align inline inputs to match classic rendering (in block_render_info)
- Account for the shadow/dark path in the size of an inline input (in measurables.js)
- Use a constant for the size of the dark path, to make it easier to later remove it
One additional test passes.
Diffs looked like this:
Now they look like this:
Note that the remaining error here is an instance of #2535:

Account for shadow in block size.

---

core/block_svg.js
tests/screenshot/test_cases/multi_colour_with_external
tests/screenshot/test_cases/multi_colour_with_internal
tests/screenshot/test_cases/test_cases.json

Changes:
- Add two new test cases (see below)
- Set shadow colour of block correctly (makes 3 tests pass, total 85/111 passing)
@alschmiedt if this looks like a good fix for the shadow block colour, I can make a similar PR against develop.
New test cases:

Add tests with external and inline inputs; set shadow colour

---

core/trashcan.js

#2538 
Makes it so the trashcan ignores top-level shadow blocks.
Fixes buggy behavior
1. Dragged math "+" block onto workspace.
2. Dragged math "123" block into "+" block.
3. Observed how there was no change in the trashcan, and it was not interactable.
Tested on:
N/A

Fixed how the Trashcan Handles Shadow Blocks

---

core/block_rendering_rewrite/block_render_draw.js

Part of making multi-block tests pass is getting the connections to be placed right.
This mostly preserves the previous code, but pulled out so that we can easily compare (e.g.) previous and next placement.

Extract connection placement into separate functions

---

demos/keyboard-nav/index.html
tests/mocha/navigation_test.js

Tree traversal was not working for multiple stacks when a stack was not valid. 
If the sibling or parent node is not valid traverse the sub tree to look for a valid node. We don't want to traverse the tree if we are at the top workspace node. 
Before if the node was not valid then we skipped the sub tree underneath it and just went to the next out node. 
Tested on:

Fix tree traversal to work for multiple stacks

---

core/block_rendering_rewrite/block_render_draw_highlight.js
core/block_rendering_rewrite/block_rendering_constants.js

This addresses problems with these blocks and similar ones in RTL:
Previously the inline inputs didn't have a highlight for the top right side (above the tab).  There were also a bunch of magic numbers to put things in the right places.
Changes:
- Added top right side highlighting.
- Removed extra magic numbers from the rtl tab highlight.
- The above broke external value inputs, so I also fixed those.
- Removed vertical line below the tab from the tab highlight path.

Clean up inline and external value input highlighting

---

core/block_rendering_rewrite/block_render_info.js
core/block_rendering_rewrite/block_rendering_constants.js
core/block_rendering_rewrite/measurables.js
core/field_colour.js
core/field_image.js
core/icon.js
core/input.js

Makes the logic similar for square and round corners.
Removes extra constant.
I don't know where the 0.5 comes from.
Tests passing:
87/112 in LTR
77/112 in RTL

Change alignment on previous and next connections

---

tests/screenshot/img_viewer.html

Adds a page for direct comparison of the outputs of the screenshot diff tests.
You type in the name of the test file and hit open.  Clicking on the image toggles between the old and new image, and "show diff" shows the diff output.  This makes it easy to see height differences in blocks.

Add simple page for comparing rendered blocks directly

---

core/css.js
core/field_colour.js
core/field_date.js
core/procedures.js
core/toolbox.js
core/utils.js
core/variables.js

1) Simplifications/elimination of regular expressions.
2) Enable toolbox category colours to be specified using the full range of CSS formats (not just hue or #rrggbb).
3) Fix bug where `Blockly.utils.checkMessageReferences('%{BKY_today}  %{BKY_xxx}')` returns true.
4) Reduce memory footprint of CSS.
5) Remove potential for fetching gstatic.com resource.

Fix regular expressions.

---

core/dropdowndiv.js
core/field.js
core/field_angle.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_textinput.js
core/field_variable.js
core/tooltip.js
core/workspace_svg.js
tests/mocha/field_angle_test.js
tests/mocha/field_number_test.js
tests/mocha/field_textinput_test.js

Related to [this](https://github.com/LLK/scratch-blocks/issues/1947).
Makes it so that fields properly dispose of themselves and their editors.
Reorganizes some editor creation code to make it more readable (lookin at you dropdowns).
Cleaning up after yourself is polite.
Got rid of some now-redundant code from #802. Could not reproduce #779 or #651. (pass)
Changed some stuff that could have affected #1329 (the dropdown equivalent) could not reproduce with dropdowns. (pass)
Here's all of the editors working:
Tested on:
There are a few TODO's with little questions, but my big question is what all do we need to dispose of? Is it just references to DOM elements and events? Or is it all field properties?

Fixed Field Disposal, and Reorganized Editor Creation

---

core/connection.js
core/connection_db.js
core/workspace.js
core/workspace_svg.js

It seems wrong that Blockly.ConnectionDB.init reaches in to create a property on workspace.
It seems wrong that this database isn’t disposed of when the workspace is.
It seems unnecessary that disposed connections need to drop their reference *to* the workspace’s database since the connection object is going away anyway, and the databases aren’t.

Refactor workspace.connectionDBList

---

tests/mocha/index.html
tests/mocha/trashcan_test.js

N/A
Adds tests to documenta trashcan behavior.
To keep Beka from breaking things.
The tests document the current behavior of the trashcan, but I don't think all of that behavior is good. I left TODO's in places where I think behavior should be changed.
Also this might not cover everything that needs to be tested. If you have suggestions I'd love to add more tests.

Added Trashcan Tests

---

core/field.js
tests/mocha/field_test.js

N/A
Makes it so you can call setTooltip on a field before calling appendField().
setTooltip should not throw errors.
Added setTooltip tests for:
* setTooltip before appendField().
* setTooltip after appendField().
* setTooltip after block creation.
* setTooltip with static text.
* setTooltip with a dynamic function.
* etc...
N/A

Fixed setTooltip Not Working Before appendField()

---

core/block_svg.js

- [ x ] I branched from develop
- [ x ] My pull request is against develop
- [ x ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
Split showContextMenu_ into generateContextMenu_ and showContextMenu_.
No issue created, but I can create one if that would make for easier tracking.
Split showContextMenu_ into generateContextMenu_ and showContextMenu_.
This allows for custom Blockly forks to easily extend the context menu options available on all blocks by just doing something like
```
var oldGenerateContextMenu_ = Blockly.BlockSvg.prototype.generateContextMenu_;
Blockly.BlockSvg.prototype.generateContextMenu_ = function() {
var menuOptions = oldGenerateContextMenu_() || [];
// Push other options into menuOptions
return menuOptions;
} …
```

Pull Request: Split showContextMenu_

---

gulpfile.js
package.json

As of NodeJS v12.4.0, gulp v3 fails to run at all. This small change
should allow for future compatibility with NodeJS.
Resolves: https://github.com/google/blockly/issues/2582
This pull request will update gulp to v4 and also update the gulpfile to use
the new v4 syntax.
Without this change, any attempt to use blockly in a NodeJS  (or NodeJS-built) v12.4.0 project fails.
Tested on:

upgrade gulp to v4

---

core/field_textinput.js

N/A
Removes useless fromJson check.
Text input fields don't accept classes.
N/A
N/A

Removed Class Option Check from Text Input fromJson

---

core/block_events.js
core/options.js
core/trashcan.js
core/variables.js
core/variables_dynamic.js
core/xml.js
tests/mocha/trashcan_test.js

#2029 
textToDom is now less picky. It accepts whatever you give it and throws a generic parsing error if it doesn't parse.
It's annoying to have to wrap and unwrap text in `<xml>` tags to get it to parse.
1. Added the below code to the playground:
```
Blockly.Xml.domToBlock(Blockly.Xml.textToDom(
'<block type="controls_if"/>'
), workspace);
Blockly.Xml.appendDomToWorkspace(Blockly.Xml.textToDom(
'<xml><block type="controls_if"/></xml>'
), workspace);
```
2. Observed how both blocks were created correctly.
There are also some unit tests that cover the xml.
Tested on:
N/A

Removed textToDom Needing <xml> Documents

---

core/field.js
core/field_date.js
core/field_textinput.js

N/A
doValueInvalid_() now recieves the invalid value.
Makes it easier for fields to display invalid values if they wish.
This was not added previously because the only core field that uses doValueInvalid is the text input field, and its display value is stored on the htmlInput. But when I was working on the custom fields demo I found that this was useful.
N/A
N/A

Added Sending the Bad Value to doValueInvalid

---

core/block_svg.js

This is a rework of PR #2580.  That PR has issues in its handling of the block's highlight.
Tested on:
* Windows Edge
I hate IE.

Fix IE not unhighlighting

---

core/utils/svg_paths.js

No issue
Create a set of helper functions for making SVG path commands.
SVG paths are defined as strings.  There are a variety of commands, each represented by a single character and a sequence of numbers.  These commands are really hard to read in the current code:
```
Blockly.BlockSvg.TAB_PATH_DOWN_HIGHLIGHT_RTL = 'v 6.5 m -' +
(Blockly.BlockSvg.TAB_WIDTH * 0.97) + ',3 q -' +
(Blockly.BlockSvg.TAB_WIDTH * 0.05) + ',10 ' +
(Blockly.BlockSvg.TAB_WIDTH * 0.3) + ',9.5 m ' +
(Blockly.BlockSvg.TAB_WIDTH * 0.67) + ',-1.9 v 1.4';
```
These functions make the SVG path code more readable, and also remove some of the confusion around number addition vs string concatenation.  It also makes it easier to see when we're using negative numbers.
This is a proposed API.  I would like to keep the names …

Create svg_utils file

---

core/renderers/block_rendering_rewrite/block_rendering_constants.js
tests/screenshot/test_cases/multi_stack

Tested by running the screenshot diff tests in rtl and ltr after every change and confirming that the number of passes stayed the same.
This change replaces some path constants with strings built using the new `Blockly.utils.Paths` functions.  I may move them around later, but this makes them more readable and means later changes can simply move code.
I also added a missing `>` on a test.  See #2600 for information on why that was necessary.

Use Blockly.utils.Paths functions for some constants; fix a test

---

core/css.js
core/field_number.js

#1595
Adds number type to the FieldNumber editor.
To help mobile devices on screen keyboards.
Tested on:

Adds type to FieldNumber editor

---

core/procedures.js

#2590
Use getValue instead of this.text_ to get the name of the procedure. 
When a procedure name is changed we look through all the blocks for a caller with the same name and then update the caller with the new name. We do not allow procedures to be named with trailing white spaces. Whenever a user types in a trailing or leading white space we ignore it and do not update the caller. 
The problem was that we were storing the trailing white spaces as part of the procedure name, but were not updating the caller to have the same name. When we looked through the list of blocks for the procedure name with the trailing white space it did not exist and would not get updated. (ex. Looking for callers named “do something   “ instead of “do something”). 
Tested on:
Desktop Chrome

Fixes spacing problem in procedure name

---

core/block_svg.js

#2535
Add fill colour to the block's svgPathDark and remove display: none.
There was a gap between the right and bottom side of shadow blocks and their parent block. 
Tested on:
Desktop Chrome

Adds fill to svg dark path

---

blocks/procedures.js

#2620 
Fixes procedure decomposition throwing erros when the procedure has >1 arguments.
Erros be bad.
Repeated reproduction steps given in the issue. The error did not occure.
Tested on:
N/A

Fixed Procedure Decomposition Not Working with >1 Arguments

---

blocks/variables_dynamic.js
core/variable_map.js
core/workspace.js

#2557
1. Use getVariable() instead of getVariableById(). getVariable looks through both the potential variable map as well as the variable map. This fixes the original error.
2. Look through the potential variable map and the regular variable map when getting variable types. This fixes the error we were getting when we have a block like the one below that accepts any type.
Tested on:

Fixes bug with using dynamic variable in toolbox

---

blocks/procedures.js

#2624 
Refactors procedure decompose to build the xml node-by-node (as suggested by neil). Also fixes arguments not being properly escaped.
Bugs be bad.
Tried the reproduction steps given, the bug did not reproduce.
Tested on:
Gonna work on more procedure unit tests today.

Fixed Procedure Argument Escaping

---

core/insertion_marker_manager.js

[#2363](https://github.com/google/blockly/issues/2363)
Sets collapsed state of insertion markers on creation.
Setting the collapsed state of the insertion marker ensure that there isn't an error with the insertion marker block missing a field when the source block is collapsed. This fixes the bug where dragging collapsed blocks with fields throw errors.
Tried the reproduction steps given, the bug did not reproduce.
Tested on:

Added setCollapsed to insertion marker block creation.

---

local_build/local_build.sh

STRICT is a deprecated alias for PRUNE.
N/A
Migrate off of deprecated Closure Compiler --dependency_mode=STRICT flag.
See above.
Tested by running local_build.sh locally.
N/A

Replace --dependency_mode=STRICT with PRUNE.

---

demos/mobile/android/app/src/main/java/com/google/blockly/android/webview/JsDialogHelper.java

This handler should be unnecessary on most versions of Android, and it's currently just swallowing events that would be handled by default. Removing it to let the system take the default action.
Fixes #2340
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2634)

Remove edit handler that is just eating events

---

core/blocks.js
core/field_variable.js
core/variable_map.js
core/variables.js
core/variables_dynamic.js
core/workspace.js
core/xml.js
gulpfile.js
tests/jsunit/xml_test.js
tests/mocha/xml_test.js
tests/xml/blockly.xsd

A bunch of XML related issues.

---

core/block.js
core/field.js
tests/blocks/test_blocks.js
tests/playground.html

N/A
Allows the developer to set a field's tooltip through the block's JSON definition, to match block tooltips.
Consistency and usability!
Added a test block that covers field tooltips and block tooltips.
Tested on:
As with the last two PRs, would you like this added to the block factory? If you do I would love some guidance on how to go about it (b/c I haven't got a clue).

Added Field Tooltip Support to the JSON

---

core/field_colour.js
tests/blocks/test_blocks.js
tests/playground.html

#286 
Adds the ability to set a colour field's options, their titles, and the number of columns through JSON:
* colourOptions
* colourTitles (maybe titleOptions would be better?)
* columns
Gotta give the JSON some love.
Added  a test block to the playground, it works as expected.
Tested on:

Added Setting a Colour Field's Options Through JSON

---

core/utils/svg_paths.js

Rename Blockly.utils.Paths -> Blockly.utils.svgPath
Match existing conventions on capitalization for classes vs namespaces. 
I will also cherrypick this into the release candidate so that we don't have to later do a rename when it's already on master.
These functions aren't yet used anywhere.

Rename Blockly.utils.Paths -> Blockly.utils.svgPath

---

core/rendered_connection.js

We weren't always setting the display style on blocks when the hidden
state changed on a connection. This meant that sometimes unhiding a
connection would cause the attached block to be invisible.
This moves the display style code into the setHidden so it is never
skipped.
https://github.com/google/blockly/issues/2660
https://github.com/google/blockly/issues/2632
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2666)

Properly set the display style on blocks when connections are unhidden

---

.eslintignore
.gitignore
tests/screenshot/diff-reporter.js
tests/screenshot/diff_screenshots.js
tests/screenshot/diff_viewer.html
tests/screenshot/gen_screenshots.js
tests/screenshot/img_viewer.html
tests/screenshot/playground_new.html
tests/screenshot/playground_old.html
tests/screenshot/run_differ.py

Adds files for screenshot tests:
- diff-reporter.js is a custom reporter for mocha that outputs the diffs in the format that I want
- diff_screenshots.js opens the pairs of generated images, diffs them, and saves the diffs to the diff folder
- diff_viewer.html is a web page that parses the results output by diff_screenshots and the diff-reporter, and shows a table with old, new, and diff images
- gen_screenshots.js uses webdriverio to open up old and new playgrounds, load blocks from XML, and take screenshots
- img_viewer.html lets you inspect a single set of old/new/diff images in a way that I found helpful for debugging
- playground_new.html loads the new rendering files and is used by gen_screenshots.js
- playground_old.html loads the hosted version of blockly and is used by …

Add screenshot test scripts and web pages

---

core/field.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_textinput.js
core/icon.js

Note: This is a chunk of code from `render/collab` which I'm pulling in piecewise, because the rebase is terrible.
Part of new rendering.
Adds `getCorrectedSize` functions to fields and icons.
`getSize` is not guaranteed to return a bounding box on the field, and I don't want to touch it now because that will break old rendering.
New rendering uses `getCorrectedSize`, which calls `getSize` if `getSize` already does the correct thing.
As we get rid of the old rendering I will change `getSize` functions to be correct, and eventually remove `getCorrectedSize` entirely.
@BeksOmega because this touches fields.

Add getCorrectedSize functions to fields

---

blocks/procedures.js
core/names.js
core/procedures.js
msg/messages.js
tests/mocha/procedures_test.js

#2591 
#2592 
If a procedure is renamed to empty it instead gets renamed to 'unnamed' (or a translated version of the same).
Procedure parameters can now be renamed without throwing errors.
Bug fixes.
Re-enabled all applicable tests. They pass!
N/A

Fixed Procedure Empty Names & Procedure Parameters

---

core/field_textinput.js

https://github.com/google/blockly/pull/2441#discussion_r282982055
Removes an accreted workspace change listener.
Efficiency and readability.
So I said I would investigate this and I did!
This change listener was originally added as the only way the editor would get resized: (ctrl f "resizeEditor" on [this page](https://github.com/google/blockly/blob/a8acffd81c520b83027eebedc45543f14c5a8059/core/field_textinput.js#L128))
Then in [this commit](https://github.com/google/blockly/commit/c429949a4e449fc84e46f79e8eba55f5df9c06cb) Neil added an additional call to it inside the onHtmlKeyDown_ function making the listener obsolete.
The listener is not used for workspace resizing/zooming/scrolling etc. Firstly because the workspace does not yet fire those events. And secondly because the workspace …

Removed Useless Text Input Workspace Change Listener.

---

core/renderers/block_rendering_rewrite/block_rendering_constants.js

Rename uses of Blockly.utils.Path to Blockly.utils.svgPaths
I did this rename on develop before the release.  This just applies it to the rendering files, which didn't exist at the time.

Paths->svgPaths

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/block_rendering.js
core/renderers/block_rendering_rewrite/measurables.js

- Rename `Blockly.BlockRendering` to `Blockly.blockRendering` because it's a namespace (first commit)
- Create a block_rendering.js file that defines `render`, instead of having that in block_render_draw.js (second commit)
- Naming scheme we agreed on
- Having the definition of render in draw was confusing
Next steps:
- Rename `BRC` to `Blockly.blockRendering.constants` and fix up resulting lint (after #2686) lands
- Remove `/* global BRC */` comments
- Uncomment `'use strict';`

Block rendering namespace

---

core/field.js
core/field_textinput.js

Missing definition of this property.
Define it, and use it in two places.
Remove magic numbers.  Also, I was already using this in the new rendering code, but didn't have the definition in.

Define BORDER_RECT_DEFAULT_HEIGHT constant

---

tests/compile/index.html
tests/playground.html

Add necessary css, checkbox, and callback to playground.html so that debug rendering rectangles can be toggled on and off.
Also add some of that css to the compilation test.
Pulling stuff in from render/collab.
Tested that the new checkbox shows up in the playground.

Add debug rendering to playground

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js
core/renderers/block_rendering_rewrite/measurables.js

As promised before my merge, renames BRC to something that makes sense
The old name was a shorthand while iterating on my design.
Checked that things still work in the playground, though it took some tweaks to block_render_svg (to be resolved tomorrow)

BRC -> Blockly.blockRendering.constants

---

local_build/local_build.sh
tests/compile/compile.sh

The google closure compiler has moved the java compiler into it's own package under google-closure-compiler-java.  Updating paths to reflect that.
Local build script depending on the npm google closure compiler and library is broken from a change of paths in the package.
Updating paths in local build scripts.
Tested on a mac. Ran the local_build.sh script and the tests/compile/compile.sh script.

Fix the local npm compiler build script

---

package.json
tests/screenshot/playground_new.html

Fixes screenshot tests
- Adds new stuff to dev dependencies for the tests
- Removes explicit script tags containing the rendering files
- Removes explicit require
Getting the tests to work on develop.  Now the tests diff the local blockly_uncompressed against the hosted blockly_compressed.  Both use the local block definitions, but those should not be changing much.
Ran the screenshot tests.  The results match, as we would expect.

Make screenshot tests run

---

demos/custom-fields/blocks.js
demos/custom-fields/custom-fields.css
demos/custom-fields/field_turtle.js
demos/custom-fields/media/warning.svg

https://github.com/google/blockly/pull/2594#discussion_r302133456
The turtle field now shows a warning icon next to the invalid property.
This better demonstrates validating multipart values. This pattern is also used in the class validator, but as Erik pointed out that could be solved by just using default values. This is a more applicable use case.
Tested that the warnings hide & show correct:
Tested that the warning is "saved" when you hide & show the editor:
Tested that it goes through XML correctly (it should save the last valid value, i.e. the stovepipe hat):
Tested that the other turtle blocks still function correctly:
Tested on:
The turtle demo should be republished whenever it is convenient (sorry I didn't get this to you peoples sooner).
N/A

Added a Better Example of Validating Multi-Part Values to the Custom Fields Demo

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js
core/renderers/block_rendering_rewrite/measurables.js

Progress on rendering.
Create and use objects that encapsulate dimensions and paths of the start hat and puzzle tabs.
Swapping the connection shapes is a very common request.  The hat change is simple.
Also, this makes it easier to see the relationship between the paths when going up and down, which otherwise were stored and changed separately.
Ran the screenshot tests in ltr and rtl.  98/112 and 88/112 tests pass respectively.
Not yet.
Next steps:
- Create a Measurable representing the puzzle tab
- Put the information about the offset distance from the top in the measurable, not strewn across draw and draw_highlight.

Move puzzle tab and start hat information into objects

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/measurables.js

Updates debug rendering for top and bottom row to treat them like rows with elements rather than spacer rows.
Displays more information useful for debugging rendering.
old debug rendering:
new debug rendering:
Tested on:

Updating debug rendering for top and bottom block rows.

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_info.js

Uses computed centerline for debug rendering and updates how next connection centerline is computed.
Results in a more accurate debug rendering view.
Tested on:

Using centerline for debug rendering.

---

core/workspace_audio.js

Fixes the issue that was introduced by https://github.com/google/blockly/pull/2162 in browsers such as Edge, in which `sound.play()` does not return a promise. Adds in the same changes that were added in scratch-blocks in https://github.com/LLK/scratch-blocks/pull/1959.

Properly handle cases when sound.play() does not return a promise

---

core/flyout_button.js

Fixes https://github.com/google/blockly/issues/2672
IE doesn't like cases in the xml so it converts them all to lower case. This check the lowercase version of the callbackKey attribute as well to make sure we wire up the button callback.
Flyout buttons broken in IE.
Tested on:

Fix IE flyout button callback

---

core/flyout_dragger.js

#2728
Makes it so dragging flyouts scrolls the scrollbars.
Bugs are bad.
Currently there is no way to unit tests gestures.
Tested scrolling each flyout position on the multiplayground, simple toolbox & categories.
Tested on:
No docs needed.
Not my prefered solution, but it works and I didn't want to tear into scrollbars right now.

Fixed flyout scrollbars not being updated when the flyout was dragged.

---

core/field_image.js

Fixes setOnClickHandler jsdoc parameter.
function -> Function
Uppercase ``Function`` is the type of a generic function. 
Lowercase ``function`` is a specific type. eg: ``function(...): ...`` Generally the more specific type is preferred, but we'd have to define the function signature we are expecting. If unknown, use the uppercase ``Function``.
More on the closure type system: https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System
@BeksOmega FYI

Fix setOnClickHandler jsdoc

---

core/block_svg.js

The new moveTo function was duplicating a lot of the functionality in moveBy.
Compute the difference in moveTo and pass the dx and dy to moveBy.
Tested on:

Used moveBy in moveTo

---

core/keyboard_nav/navigation.js
core/workspace_svg.js

Copy paste was broken for keyboard navigation.
If we are in accessibility mode and a connection has been marked then try to insert the copied block at the marked location. If the marker is not at a valid connection point, then warn the user. 
Tested on:

Fixes copy paste to work with the marker

---

core/block_render_svg.js
core/block_svg.js
core/rendered_connection.js
core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_rendering.js

- rename `renderMoveConnections` to `updateConnectionLocations_`, move it from `block_render_svg.js` to `block_svg.js`, and call it in the same place for both renderers.
- Use the new constants in `rendered_connection.js` for connection highlighting
- Fix some connection locations in new code 
- Change connection placement in old code to make the new highlights work in the old code
- code dedup
- fixing connection highlights in new rendering
- fixing block positioning in new code, maybe
- the old code doesn't mind a few more constants sprinkled in, and this makes it so that I don't have to check which renderer I'm using when highlighting connections.
Tested in the playground in both LTR and RTL, in classic and compatibility rendering modes.
Future work: connection location for previous …

Work on connection locations

---

core/renderers/block_rendering_rewrite/block_render_info.js

Get rid of a console.log that was filling the console.
No longer needed for debugging, and easy to turn on when needed.

Remove logs from rendering

---

core/renderers/block_rendering_rewrite/block_render_info.js

Moves conditional update of bottom row height within finalize_ to before row element centerlines are computed.
Fixes edge case where centerline for bottom row elements is computed incorectly.
Before:
After:
Tested on:

Fix bottom row element centerlines

---

core/block_svg.js

When using the tab button and pressing tab from a visible field, the code does not skip over hidden fields.
Added a check if the field is visible
Behavior not logical
None
Tested on:
* Windows Edge
None

Make the TabList exclude hidden fields

---

core/css.js
core/field_textinput.js

Make field text centered and use input instead of keyup/press.
Old behaviour: 
Notice how the text jumps left when editing.
New behaviour:
The keypress / keydown event combo was used to support IE9- browsers. Since we've dropped compatibility, we can use the input event which is available on all browsers we support: https://caniuse.com/input-event.
N/A
Center the text in the input widget and use the input change event to detect changes instead of the keypress / keyup event.
It looks better when the text doesn't jump out of place when you're editing.
Tested typing characters, clearing input, select all and delete, escape, enter, and pressing and holding (all with expected behaviour)
Tested on:
- Desktop Chrome
- Desktop Safari
- Edge 18
- IE 11
The input even is available on all the …

Center text field input when editing

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js

Changes how debug rectangles are drawn to take into consideration whether a block is RTL for determining x position.
More accurate debug rendering for RTL blocks.
Tested on:

Updating debug rendering for RTL blocks.

---

build.py
core/blockly.js

Inject the Blockly version from package.json into compressed Blockly builds.
This makes it easier for developers to let us know which version of Blockly they are running.
The way the variable is defined (Jsdoc), it lets us also use the --define flag when compiling locally. see --define flag for more info: https://github.com/google/closure-compiler/wiki/Flags-and-Options

Inject Blockly version into binaries

---

core/workspace_svg.js

Flyouts and mutator workspaces don't have enough info to handle
zooming correctly, so they were throwing errors if you pinched them.
This adds a check to quit a zoom early if in either of those. We
might want to revisit later if we should support zooming on them.
Fixes #2752
Tested on:
Desktop Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2772)

Don't try to zoom flyouts and mutators

---

core/field.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_textinput.js
core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/measurables.js

#2562
Update field sizing to always describe all visible parts of the field, including the border rect if it exists.
Make field sizing more consistent.
Note that this breaks the old renderer.
71/112 tests pass in LTR; 86/112 in RTL.  All field types pass, and the remaining test failures are due to other known bugs.
After I finish this + the followup work, will need to update the documentation on fields to include a description of what the size represents.
Also related to #2530
Followup work: 
- Fix all fields that actually position themselves at -5 px, which may be all fields with a border rect, and remove `dealWithOffsetFields`
- Remove `getCorrectedSize` for icons
- Update documentation

Remove getCorrectedSize for fields

---

core/keyboard_nav/ast_node.js
msg/messages.js
typings/blockly.d.ts

Add jsdoc annotations to messages so that the typescript generator tool picks it up.
Disclaimer, I don't know a huge amount about how our translation service looks at this file. I assume the comments are formatted in a specific way for a reason, eg: {{Notranslate}}. 
In order to avoid breaking any automated tool, I added the jsdoc at the top of the comment block for each message. 
Ran ``npm run typings`` to generate typings.
Also ran advanced compilation and it doesn't introduce any more warnings (partly because I think this file isn't included, and is only used for generating other message files).

Add jsdoc to messages

---

core/block.js
core/connection.js
core/field.js
tests/mocha/block_test.js
tests/mocha/connection_test.js

Work on #2152
* Connections now have a default behavior for dealing with connected blocks on dispose.
* This matches the previous behavior which was stored in block.js.
* This does not affect how blocks dispose of their children (which is different than the default behavior depending on the healstack property), because all disposal of children is handled before the disposal of connections.
* Connections now have a disposed property.
* Blocks also have a disposed property, because it was needed for unit tests.
Code simplification.
* Unplugging with connected shadow blocks.
* Dispose tests that correspond to all of the unplug tests (including the new shadow ones).
* Remove input tests for:
* No connected block.
* Connected shadow block.
* Connected corporeal block.
1. Defined the below …

Updated How Connections Dispose of Themselves

---

core/field_textinput.js

As user's type in the text input, it resizes the input field based on the field's borderRect. Currently it doesn't get a chance to reflow when resizing, and that causes an issue for RTL blocks as the left hand size is constantly changing as a user types. 
Fixes https://github.com/google/blockly/issues/2777
Reflow for RTL.
Tested on:
* Desktop Chrome (Mac)
* Desktop Firefox (Mac)
* Edge18
* IE

Fix RTL text field positioning bug by ensuring a reflow

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/measurables.js

Stores flag for flipRtl on BlockInfo and flips image in block_render_draw if in RTL and flipRtl is set.
Enabling flipRtl behaviour makes new renderer more consistent with old renderer features.
Tested manually in playground and compared using screenshot tests.
Tested on:

Adding logic to flip FieldImages in RTL with flipRtl flag set.

---

core/utils/style.js

It turns out when positioning the dropdown div, we attempt to get its size while it's not yet visible.
I initially thought we only computed sizes of visible components so I stripped out a lot more of this logic, but now we need it.
Dropdown field positioning bug after https://github.com/google/blockly/pull/2781
Support getSize when an element is not visible.

Support getting sizes of elements that are not visible

---

core/workspace.js

There was a typo at some point that introduced this. 
Note for all,`` Math.sign`` is not available on IE, and needs a polyfill if we want to use it.
In this case, it was just a typo, and ``sin`` was the intended method.

Math.sign -> Math.sin

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js
tests/playground.html
tests/screenshot/playground_new.html

Adds a dashed line bounding box around each block in debug rendering.
Improve debug tools for rendering changes.

Add debug rendering that shows the bounding box of the block

---

core/renderers/block_rendering_rewrite/measurables.js

N/A
Add a few properties to the prototypes for measurables and rows, pointing at the connection shape objects.
Use these instead of directly referring to the constants.
Makes it easier to swap out shape objects.
Tested in the playground
Filed #2803 to track figuring out what the objects actually contain.

Centralize references to puzzle tab and notch in measurables.js

---

core/flyout_base.js
core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js
core/renderers/block_rendering_rewrite/highlight_constants.js
core/renderers/block_rendering_rewrite/measurables.js
tests/playground.html

This is an updated version of https://github.com/google/blockly/pull/2790
I split some changes out into https://github.com/google/blockly/pull/2804 and https://github.com/google/blockly/pull/2805, so you should review those first.
- Makes all constants and highlight constants use relative svg commands instead of absolute ones.
- Adds startX and startY values to the RenderInfo object and uses them in drawing and highlighting.
- Uses startX and startY to make all parts of a block (including tabs and hats) draw down and to the right from the block's position on the workspace.
- Adds some debug rendering (see #2805)
- Fixes calculation of block width when blocks have tabs.
- Adds an `xPos` property to rows.  I decided this is worth it to make sure that a row has all of the information needed …

Hats and tabs

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js

- Build block paths as strings instead of arrays of strings.
- Fix a misplaced height in the start hat constant
- Add a triangle constant, since I keep using it for testing.
- The array was mostly to get spaces in the right places, but it's slower than string concatenation.  Also, the svg path is really just a string, so let's treat it that way.
- Start hats were drawing wrong by the height.
- I use it to test that changes are flexible.
This also uses the new svg util functions to create all of the path fragments.  Those functions are adding appropriate spacing.
Looked at test blocks in the playground.

Replace path array with path string

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/measurables.js

Next connection was not correctly part of the height of the last row.
- Give the bottom row the concept of overhang, and adjust drawing of the bottom of the block accordingly.
- Remove more explicit references to connection shape objects, and use the connection measurable's connectionShape property instead.  Tested by replacing the puzzle tab with a different shape in measurables.js:
```
Blockly.blockRendering.Measurable.prototype.connectionShape =
Blockly.blockRendering.constants.TRIANGLE;
```
- Block height and width should include all parts of the block.
- All input and output connections should be drawn the same way right now.
Tested on chrome in the playground.
Followup: look into getHeightWidth in block_render_svg, and move it block_svg.

Include next connection in block's bounding box

---

core/utils/keycodes.js

Add keycode utils to reference keycodes via an enum.
@alschmiedt this should be equivelenat to goog.events.KeyCodes, so we'll have to go through and replace all those references with this one (once we're closure free). 
Copied from https://github.com/google/closure-library/blob/master/closure/goog/events/keycodes.js#L37

Add Blockly Keycode utils

---

package.json

Remove private attribute from package.json as the package is now published on ``npm``.

package.json no longer private

---

core/renderers/block_rendering_rewrite/block_render_info.js

Aligning padding on statement input rows.
Previously, padding before statement input edge was not updated. This change makes the xPos for statement inputs accurate and enables using the xPos on that element for draw.
Tested manually on playground/
Tested on:

Adding missing padding to statement input rows.

---

core/utils/style.js

Add extra style methods used by closure components.
``scrollIntoContainerView`` is useful for scrolling a list box to the visible element (as a user navigates a long dropdown list with a keyboard, we want to scroll to show the current visible element)
``isRightToLeft`` is used to detect if we're currently in RTL or LTR.

Add extra style methods used by closure components

---

core/utils/idgenerator.js

This is very similar to closure's id generator. 
It's a great way to get a unique id for any components, just call
``Blockly.utils.IdGenerator.getInstance().getNextUniqueId()``
Similar to closure's https://github.com/google/closure-library/blob/master/closure/goog/ui/idgenerator.js
(We just use the single prefix for blockly)

Add a singleton id generator util

---

core/components/component.js
core/components/tree/basenode.js
core/components/tree/treecontrol.js
core/components/tree/treenode.js

A subset of closure tree components for building a no-closure toolbox.
Note, the build will fail until the following PRs are checked in: 
IdGenerator: https://github.com/google/blockly/pull/2815
Aria: https://github.com/google/blockly/pull/2813
KeyCode: https://github.com/google/blockly/pull/2814
Style: https://github.com/google/blockly/pull/2816
These are the files needed to create a no-closure toolbox. This doesn't integrate with toolbox.js yet, that will be a different PR. 
This is a subset of the closure components (goog.ui.component, goog.ui.tree.BaseNode, goog.ui.tree.TreeNode, and goog.ui.tree.TreeControl) stripped down to only support functionality that's used in Blockly. 
Another key difference with how closure renders the toolbox and us. In order to not have to add functionality …

Foundation for no-closure toolbox

---

core/utils/aria.js

Adding Blockly utils file for accessibility roles and state.
Similar to https://github.com/google/closure-library/blob/master/closure/goog/a11y/aria/aria.js
FYI @alschmiedt 
The two public methods to be used here are: 
``Blockly.utils.aria.setRole`` and ``Blockly.utils.aria.setState``.

Add Blockly aria utils

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js
core/renderers/block_rendering_rewrite/measurables.js

Changing width set for StatementInput measurable and simplified computation in computeBounds to use the width of the element.
Updated width is the actual width of the rendered element.
Tested manually on playground.
Tested on:

Update statementInput width to reflect what is actually being rendered.

---

core/block.js

The JavaScript closure compiler barfs at this. No such thing as JSDOC @throw.

Fix @throw jsdoc issue

---

core/block_events.js
core/ws_comment_events.js

N/A
Makes it so that the BlockBase and CommentBase events properly call the base toJson and fromJson functions.
Code simplification.
These are the base functions:
```
Blockly.Events.Abstract.prototype.toJson = function() {
var json = {
'type': this.type
};
if (this.group) {
json['group'] = this.group;
}
return json;
};
Blockly.Events.Abstract.prototype.fromJson = function(json) {
this.group = json['group'];
};
```
Also [link](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/events_abstract.js#L63).
As you can see this means we achieve the same functionality as before.
If there are other tests you'd like me to do I'd be glad to =)
Tested on:
Nope!
@rachel-fenichel  since I'm touching workspace comments.

Cleaned up BlockBase and CommentBase toJson and fromJson Calls

---

core/renderers/block_rendering_rewrite/block_render_draw_highlight.js

Check row height before drawing vertical highlight for right side row in RTL.
Prevents incorrect highlight from being drawn.
Before:
After:
Tested manually on playground in LTR and RTL.
Tested on:

Prevent incorrectly drawing vertical line for zero height spacer rows in RTL.

---

demos/blockfactory/workspacefactory/wfactory_controller.js

Workspace Factory generates self-closing XML tags that are incompatible with being embedded in an HTML document.

Remove self-closing XML tags in workspace factory

---

core/renderers/block_rendering_rewrite/block_render_info.js

https://github.com/google/blockly/issues/1346
https://github.com/google/blockly/issues/333
Center fields and inputs vertically within a row.
Alignment
Checked in the playground.
New:
Old:

Center some fields and inputs vertically

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/measurables.js

Part of #2821 
In render_draw_debug:
- Adds rendering rectangles for the width of a row with connected blocks and the width of a block with connected blocks
- Adds a config object so it's easy to turn on and off parts of the debug rendering--there's too much going on otherwise.
- Uses random colours for some parts, to distinguish between blocks at boundaries
In the other three files:
- Improves calculation of widthWithConnectedBlocks on rows
- Defines widthWithConnectedBlocks on rows
- When adding alignment padding to a row, records the size change in widthWithConnectedBlocks (only for external value inputs)
Block width was wrong before, and the missing amount was the amount that had been added in alignment padding on the given row (so it was showing up for external value inputs but not …

Correctly calculate widths of blocks with children on external inputs.

---

core/field_textinput.js

Text input border size is 4px regardless of workspace scale.
Set the border size on a text input to take into account scaling.
🎨
Tested on:
* IE 11
* Edge 18
Not selected: 
Before: 
After:

Textfield input border size with scale

---

core/field_textinput.js

Simple change to update the aria-invalid attribute when we change the UI of the text field to reflect invalid input.
Add aria invalid for when a text input field is invalid
Accessibility
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-invalid_attribute

Text input invalid accessibility

---

build.py
tests/compile/compile.sh

#2838
Removes filtering out rendering subdirectories.
We decided against choosing which renderer to use at compile time.
Tested on:

Remove check for renderer name from build and compile scripts

---

core/renderers/block_rendering_rewrite/block_render_draw.js

Various changes that solve javascript warnings.
Less warnings is nice.
Ran playground, no observed change.
Tested on:

Cleaning up some warnings in block_render_draw.js.

---

core/dropdowndiv.js

Adding support for eventually adding a visual indicator of focus on the dropdowndiv. 
Listen to focusin/out events when the dropdowndiv is created. Since the dropdowndiv is never disposed, we don't need to dispose of these events.
As any element is focused inside the dropdowndiv, we can use the .focused class to show a visual indicator of focus on the div.
Here's an example:

Focus in/out on dropdowndiv

---

demos/keyboard_nav/index.html

The keyboard navigation demo didn't get updated when I switched Blockly.Navigation -> Blockly.navigation. 
Change Blockly.Navigation -> Blockly.navigation. Also update the css for blockRenderDebug to be display none so the rectangles don't show up on the demo.
Tested on:

Fix keyboard nav demo

---

tests/mocha/run_mocha_tests_in_browser.js

Mocha tests were failing intermittently because of a timeout. I *think* this should fix it.
Add more time for mocha tests to do their thing.
Tested on:
Added this issue #2846 so that we can look into a better way to fix this.

Add timeout for mocha tests

---

core/block_render_svg.js
core/keyboard_nav/cursor_svg.js
tests/rendering/svg_paths.html

The input and output puzzle piece was being drawn in the incorrect places.
Use the new rendering constants to draw it in the correct place.
Tested on:

Fix cursor svg to work with new rendering

---

core/renderers/block_rendering_rewrite/block_render_draw_debug.js

Updates annotation for svgRoot to allow for null.
Minor refactor of for loop to declare variable inside the loop block.
Cleans up warnings, code health.
Checked things still work in playground.
Tested on:

Fixing basic warnings in block_render_draw_debug.

---

core/css.js

Shows visual indicator when a dropdowndiv or dropdown menu is focused. It's a slight box shadow by default but can be changed by developers to make it stand out further.
Also removing left padding for context menu as it's not necessary (since there's no checkbox)
CSS styling for focused indicator.
Accessibility
Tested on:
* Desktop Safari 
Tested with RTL.

Focus indicator styling

---

demos/custom-fields/field_turtle.js

Old:
New:
Mostly, I made it so that the size the field reports is the same as the size we give its bounding box.

Fix turtle rendering

---

core/renderers/block_rendering_rewrite/block_render_draw.js

Fix ``Uncaught ReferenceError: e is not defined`` introduced by:
https://github.com/google/blockly/pull/2865

Fix reference error in block_render_draw

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js

… and more approriate constants.
block_render_draw:
* Updated drawValueInput and drawStatementInput to use the element xPos
* Updated constants used in drawStatementInput to more accurately reflect what is happening.
block_render_draw_highlight:
* Using xPos for drawing highlight for value input and statement input
* Using svgPaths function and appending to this.steps_ rather than creating a local variable to follow patterns used in other functions in file.
The change in constants more accurately represent what is happening in computation.
Using xPos and the highlight minor refactor more closely matches pattern used in other functions and does not change output.
Tested on playground in RTL and LTR.
Tested on:

Minor refactor in drawing statement and value inputs

---

core/block_events.js

N/A
Removes a deprecated call to callValidator.
Validator handling logic is handled inside setValue. This call was redundant.
Tested undoing and redoing:
Tested on:
Nope!
N/A

Removed Deprecated callValidator Call

---

core/field_colour.js
tests/mocha/field_colour_test.js

Work on #2722
* Added an opt_config property to the JS Constructor which accepts the same properties as the JSON Definition (colourOptions, colourTitles, and columns)
Standardization of Configuration
Added tests for:
* Configuring via constants.
* Configuring via the JS Constructor.
* Configuring via the JSON Definition.
* Configuring via setColours() and setColumns()
* Also some documentary tests about how the title and colour arrays interact.
Tested on:
Yes, the [colour configuration](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/colour#customization) section should be updated with new information.
N/A

Changed Colour field to New Configuration Paradigm

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_draw_debug.js
core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/measurables/rows.js

Updating instances of for loops in renderers/ to use assignment in for loop condition with parenthesis where appropriate.
The case for using assignment inside of a condition is because, as long as array elements are not expected to evaluate to false, it simplifies code and in some cases produces more efficient code (like in node arrays where .length call is O(n) operation).
However, some debuggers and IDEs flag assignment inside a condition as a warning, asking if you meant a test for equality (==) and mistyled it as assignment (=). Adding a set of parenthesis around the assignment should prevent this case from being flagged as a warning.
Tested locally in playground.
Tested on:

Updating for loops in renderers to use constent pattern.

---

tests/mocha/gesture_test.js
tests/mocha/index.html

https://github.com/google/blockly/issues/2870
Convert gesture jsunit test to mocha.
Explained in linked issue.
Will remove from jsunit in a separate cleanup PR.

Convert gesture junit tests to mocha

---

core/field.js
core/field_registry.js
tests/mocha/field_test.js

Work on #2722 
Adds an opt_config property to the abstract field that adds a tooltip to the field.
<sub> sounds like a rap they'd make you do in school </sub>
Added tests for:
* JS Constructor
* JSON Definition
* w/ and w/out message references
Also moved setTooltip function tests into the new configuration suite.
Tested on:
Tooltip documentation already has a tracking issue: #2706
but it needs to be updated to include info about the opt_config property when constructing the field in JavaScript. (updates incomming)
N/A

Changed Abstract Field to New Configuration Paradigm

---

core/renderers/block_rendering_rewrite/block_render_draw.js
core/renderers/block_rendering_rewrite/block_render_info.js
core/renderers/block_rendering_rewrite/block_rendering_constants.js
core/renderers/block_rendering_rewrite/measurables.js
core/renderers/measurables/base.js
core/renderers/measurables/rows.js

Storing notch_left_offset on measurable or row instead of using constant directly
This allows for easier future customization.
Tested locally in playground.
Tested on:

Storing notch_left_offset on measurable or row.

---

demos/blockfactory/factory_utils.js

#636 
Makes it so that all unimportant attributes (x, y, id, xmlns) are removed from the xml before comparing.
The reason diffing was failing before is that an output shadow block was being created with a different ID before the one in XML could be loaded.
This is because validators are now called whenever a value is loaded from XML, which makes [this](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/demos/blockfactory/blocks.js#L48) trigger the creation of a new shadow.
The changes proposed negate this problem by ignoring the ID when diffing.
Could not replicated #636
Tested on:
N/A
The [trashcan ](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/trashcan.js#L503)and the blockfactory are now both doing …

Fixed Block Factory XML not Getting Properly Cleaned

---

core/block.js
core/block_svg.js
core/keyboard_nav/cursor_svg.js
core/keyboard_nav/navigation.js
core/mutator.js
tests/mocha/navigation_test.js

When the cursor is on a block that is deleted the cursor will also be deleted.
Move the cursor to the appropriate location before the block is deleted. 
The appropriate location are one of the below:
* The connection point of the deleted block and the parent 
* In the case of no parent or the parent has also been deleted to the workspace
Tested on:

Moves the cursor to correct location when block is deleted

---

tests/blocks/index.html
tests/jsunit/block_test.js
tests/jsunit/event_test.js
tests/jsunit/index.html
tests/jsunit/mocha_jsunit_test_runner.js
tests/jsunit/run_jsunit_tests_in_browser.js
tests/jsunit/test_utilities.js
tests/jsunit/theme_test.js
tests/jsunit/variable_map_test.js
tests/jsunit/variables_test.js
tests/jsunit/widget_div_test.js
tests/jsunit/workspace_comment_test.js
tests/jsunit/workspace_test.js
tests/jsunit/workspace_undo_redo_test.js
tests/jsunit/xml_test.js
tests/mocha/test_helpers.js
tests/workspace_svg/event_svg_test.js
tests/workspace_svg/index.html
tests/workspace_svg/procedure_svg_test.js

https://github.com/google/blockly/issues/2734
Short term plan for https://github.com/google/blockly/issues/2870
Ideally long term we should convert all these into mocha tests and remove jsunit, but for now I've wrapped jsunit tests into mocha tests.
Remove goog.testing dependency and wrap jsunit tests into mocha tests using mocha as the test runner instead of goog.testing.jsunit.
Instead of goog.testing.mockControl, using sinon for stubs / mocks (which was already being used in the mocha tests)
Removing closure dependency from tests

Remove closure dependency from tests

---

core/field_checkbox.js
tests/mocha/field_checkbox_test.js

Work on #2722 
* Adds an opt_config property to the constructor that accepts checkCharacter
* JSON Definition now also accepts checkCharacter
* Added a setCheckCharacter function to the checkmark field.
Added tests for:
* Setting the character via the constant.
* Setting the character via the JS Constructor.
* Setting the character via the JSON Definition.
* Setting the character via setCheckCharacter.
Tested on:
Yes, the [checkmark customization](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/checkbox#checkmark_character) section should be updated with new information.
N/A

Changed Checkbox Field to New Configuration Paradigm

---

core/keyboard_nav/cursor_svg.js
core/keyboard_nav/navigation.js

Shift clicking on a block only worked if it had a previous or output connection.
If there is no previous or output connection then creates a node at the block level. 
Tested on:

Fixes shift clicking on block

---

core/keyboard_nav/navigation.js
tests/mocha/navigation_test.js

Trying to connect the above scenario was throwing an error in block.setParent because we can not set the parent's svgRoot a one of its children.
Disconnect the child block before connecting.
Tested on:

Disconnect child block before trying to connect

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/measurables/rows.js
core/renderers/thrasos/info.js

Removes a special case I didn't want.
The bottoms of statement inputs should go to the right edge of the block, whether or not the block has inline inputs.
Old behaviour fell out of old rendering, but we don't need to retain it.
Checked all three renderers in the playground.
Old:
New:

Remove special case for spacer after statement

---

core/keyboard_nav/cursor_svg.js
core/keyboard_nav/navigation.js

The cursor should always be shown on top of the marker so that it does not disappear when a user marks a connection.
Update the position of the marker and the cursor in the dom so that the cursor is always after the marker.
Tested on:

Fix cursor rendering

---

core/renderers/common/block_rendering.js
core/renderers/common/debugger.js
core/renderers/common/drawer.js
tests/playground.html

#2904
Add a single property that turns debug rendering on and off
Move all the css directly into the debugger file, just to silo it
Put the config object into a getting so it's easy to change
The debugger would be more useful if it were less painful to use.

Debug configurability

---

core/components/menu/menu.js
core/components/menu/menuitem.js
core/components/tree/treecontrol.js
core/field_colour.js

Toolbox doesn't click on IOS.
Long dropdown's can't be scrolled. 
I can't find a reason for using mousedown on these elements since all we're after is detecting a click. A click works universally, so going with that instead. 
@rachel-fenichel can you think of a reason to do mouseover > click?
Fix mobile
Tested on:
* IOS

Fixes toolbox and menu dropdown on mobile.

---

core/renderers/common/debugger.js

More work on debug rendering
Add an option to turn off the connected block bounds.
Most of the time this overlaps with other boxes (when it doesn't, something's broken).
Yes, actually!  Here's a quick write-up of the debug renderer:
[Block render debug key (1).pdf](https://github.com/google/blockly/files/3557751/Block.render.debug.key.1.pdf)

Add `connectedBlockBounds` option; set quieter defaults

---

core/keyboard_nav/navigation.js

Refactor insert to use the new moveAndConnect_ function.
moveAndConnect_ checks to make sure that the types of the connections match, which was something we wanted to add before but didn't get a chance. Also it centralizes some of the moving logic. 
Tested on:

Update insert to use new moveAndConnect method

---

core/renderers/common/info.js

https://github.com/google/blockly/issues/2941
Have the base renderer deal with a next connection's overhangY property.

Fix base renderer not respecting the connection's overhangY property

---

core/renderers/common/drawer.js
core/renderers/common/info.js
core/renderers/measurables/rows.js

Fixes #2821
Statement inputs now extend to the right side of the block:
Note that the width of a statement input does not go past the width of a block:
But the bounding boxes of the rows-with-children and blocks-with-children are correct:
Now the statement input can be responsible for drawing its bottom out to the right side, and that means Sam can add rounded corners on the statement input.
Looked at it in all three renderers, and in geras in RTL, and it looked reasonable.
Checked that block bounds with connected blocks are still right.

Make statement inputs store their actual width.

---

core/renderers/geras/info.js
core/renderers/thrasos/info.js

Padding was never added on rows with only dummy inputs.
New:
Old:
If a row has only a dummy input it will always align left, even if the dummy input actually said to align right.  This seems subpar, although it probably matches the old behaviour.
I didn't actually create a Measurable for a dummy input, since it's never drawn, but that means we don't have a way to find the Blockly.Input that owns this row's fields, and that means we can't tell which way to align stuff.
That's similar to this problem: https://github.com/google/blockly/issues/338
That makes me wonder if I need an Input measurable for dummy inputs.

Fix width on dummy row.

---

core/renderers/common/drawer.js
core/renderers/geras/highlight_constants.js
core/renderers/geras/highlighter.js

https://github.com/google/blockly/issues/2952
Add additional X coordinate space when positioning the statement input. Enough for the dark path and the light path (so it matches the original renderer). 
Use the DARK_PATH_OFFSET constants instead of 0.5 when positioning the statement input on the Y axis.
Match original renderer.

Fix slight offset in statement input connection X location.

---

core/blockly.js
core/keyboard_nav/ast_node.js
core/keyboard_nav/navigation.js
tests/mocha/navigation_test.js

Keyboard navigation did not work in readonly mode. 
If we are in read only mode and keyboard accessibility mode is turned on then we will allow a certain subset of actions that do not modify the workspace, but allow the user to move around the workspace.
Tested on:

Action list

---

.gitignore
package.json

Conviniently run: 
```
npm run build:debug
```
and look at ``build-debug.log`` for the closure compiler output with warnings.
``build-debug.log`` ignored from git.
Useful for both internal and external developers to easily check their changes against the closure compiler.

Add a build debug npm script for convenience

---

demos/custom-fields/pitch/blocks.js
demos/custom-fields/pitch/field_pitch.js

Rename the pitch field to fall under the CustomFields namespace instead of the Blockly namespace.

Rename the pitch field

---

core/renderers/common/drawer.js
core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Add a spacer before and after a statement input and place use it to render a right corner before and after the statement input.
Looks like this: 
The spacer height and statement input width adjust to the corner radius. You can see that here, with a corner radius 3x: 
Right round corners for statement inputs to match zelos spec.
Tested geras and zelos, ltr and rtl.

[zelos] Right inner round corners for statement inputs

---

core/rendered_connection.js
core/renderers/common/block_rendering.js
core/renderers/thrasos/info.js
core/renderers/zelos/info.js

Part of #2956 
Remove most references to dark path offset outside of geras.
It's still being used for inline inputs in thrasos, and in the root drawer.  thrasos may need to set it to zero, or (preferred) the root drawer needs to not refer to it at all (all references can be in info instead).
Cleanup

Remove references to dark path offset; fix highlights while dragging

---

blocks/colour.js
blocks/lists.js

Reverts google/blockly#1797
We should keep a non-deprecated provide in both of these files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2972)

Revert "Deprecate Blockly.Constants.Colour and .Lists"

---

core/renderers/common/drawer.js
core/renderers/geras/drawer.js
core/renderers/geras/highlighter.js
core/renderers/geras/info.js

Toward #2956
Add the dark path offset to the block height, width, and width with children in geras info, instead of in the drawer.
Height should be accurate at the end of the measure pass.
Adding the baseline property on the bottom row made this possible.

Add dark path offset in geras info.

---

core/renderers/common/drawer.js
core/renderers/measurables/connections.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js
tests/playground.html

https://github.com/google/blockly/issues/2977
This is just an initial PR, there's more work to be done here, but this gets us the following:
We still need to figure out how this should render for external inputs. https://github.com/google/blockly/issues/2978 tracking that.
I have removed the drawing of empty inline inputs in this change but hope to tackle that in a separate change: https://github.com/google/blockly/issues/2979
Rendering feature.

Dynamic output shapes

---

package/README.md

Update npm readme to use correct path for the Javascript generator.

Fix npm js generator path in npm readme.

---

core/blockly.js
core/gesture.js
core/keyboard_nav/key_map.js
core/keyboard_nav/navigation.js
tests/mocha/navigation_test.js
tests/playground.html

The only way to get into keyboard accessibility mode used to be by shift clicking on the workspace.
1. Add a checkbox on the playground for inserting into keyboard navigation mode.
2. Add an action for toggling keyboard navigation. Currently mapped to hitting control k
3. Clicking on the workspace no longer takes us out of keyboard navigation. Instead keyboard navigation is turned off by hitting control k once keyboard navigation is on.
Shift clicking wasn't a very accessible way to turn on keyboard navigation.
Tested on:

Enter accessibility

---

core/keyboard_nav/key_map.js
core/utils/object.js

Fixes https://github.com/google/blockly/issues/2999
Add an Object.values helper method in the object utils to have a fallback option for IE.
No Object.values in IE.
Tested on:
* IE 11

Add Object values helper method to fix IE

---

core/block_svg.js
core/flyout_base.js
core/rendered_connection.js
core/renderers/common/block_rendering.js
core/renderers/common/drawer.js
core/renderers/common/info.js
core/renderers/common/renderer.js
core/renderers/geras/highlight_constants.js
core/renderers/geras/highlighter.js
core/renderers/geras/info.js
core/renderers/geras/renderer.js
core/renderers/measurables/base.js
core/renderers/measurables/connections.js
core/renderers/measurables/inputs.js
core/renderers/measurables/row_elements.js
core/renderers/measurables/rows.js
core/renderers/thrasos/info.js
core/renderers/thrasos/renderer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js
core/renderers/zelos/renderer.js
core/toolbox.js
core/workspace_svg.js
gulpfile.js

#2702
Move the rendering object onto the workspace. Different workspaces can have different renderings (eg: flyout vs main workspace), it's also a logical place for the renderer to live. 
Playground and ran tests.
Tested on:

Move the rendering object to live on the workspace_svg

---

core/field_number.js
core/field_textinput.js
tests/mocha/field_number_test.js

Work on #2722 
Adds an opt_config parameter to the number field construct. Accepts min, max, precision, and tooltip.
Also added a getConstraints function.
So people can change individual constraints at runtime without having to store the constraints separately.
Added tests for setting:
* Min
* Max
* And precision
Updates [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/number#creation).
Dependent on #2915 Will rebase once merged.

Number Field Configuration 

---

core/field_textinput.js
tests/mocha/field_textinput_test.js

Work on #2722 
Adds an opt_config parameter to the text input field constructor. Accepts spellcheck.
Added tests for setting the spellcheck. JS, Json, programmatic, etc.
Updates [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/text-input#creation). And info about .spellcheck_ parameter should probably be removed [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/text-input#customization).
Dependent on #2915 Will rebase once merged.

Text Field Config

---

core/field_image.js
demos/blockfactory/factory_utils.js
tests/mocha/field_image_test.js

Work on #2722 
Adds an opt_config option that can be passed to the image field constructor. Supports flipRtl, alt, and tooltip.
Also fixed block factory.
Working is good!
Added tests for:
* onClick handler
* Alt
* FlipRtl
Updates [here ](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/image#creation)and [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/image#click_handler).
Dependent on #2915 Will rebase once merged.

Image Field Config

---

core/field_label.js
core/field_label_serializable.js
tests/mocha/field_label_serializable_test.js
tests/mocha/field_label_test.js

Work on #2722 
Adds an opt_config parameter to the label field and serializable label field constructors. It accepts class and tooltip.
Added tests for setting the class via js constructor, json, programmatic, etc. Tests run on label field and serializable label field.
Updates [here ](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/label#creation)and [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/label-serializable#creation).
Label fields also need a customization section, since setClass is now a thing.
Dependent on #2915 Will rebase once merged.

Label Field Config

---

core/renderers/common/debugger.js
tests/playground.html

Fixes #2904 
Adds checkboxes to playground for toggling debug rendering options that are dynamically generated (based on defined config object on debugger) and hidden when debug rendering is disabled. The debug rendering options persist in session storage and changing any debug render option triggers re-render.
In this change, the debug config object is changed to be shared across all debuggers, rather than each instance of the debug renderer for each block storing its own object. This simplified logic, but no longer allows for different instances of the debug renderer to have different options (which is expected to be a rare case).
Improves debugging experience.
Tested on playground and checked without session storage for options and with options saved.
Tested on:

Adding checkboxes for debug rendering options to playground.

---

build.py

* Remove unused imports and reorder.
* Compute default values during argument parsing, not at every end-point.
* Always rebuild JSON messages, since it just takes a split second.  Removes a complicated file-timestamp check.
* Remove support for “old argument style” (whatever that was).
* Restore Python 3 compatibility (injecting Blockly version number only works on strings, not bytes).

Simplify build script

---

.eslintignore
core/utils/global.js
gulpfile.js

Fixes https://github.com/google/blockly/issues/3032
An any bugs that arise from Blockly.utils.global not pointing to the global object.
The previous logic in Blockly.utils.global was referencing ``this`` and falling back onto ``self`` if this didn't exist. When Blockly is wrapped in a UMD module, ``this`` references the function scope of the module. 
``self`` points to window in browsers and web-workers. Not generally implemented outside of browsers.
``window`` points to the window object. Not generally implemented outside of in-page browsers.
``global`` points to the global object in Node. Not implemented outside of Node.
I left out ``globalThis`` as it's not widely implemented outside of V8.
Tested Blockly samples, webpack, react and node.
Tested on: …

Fix Blockly.utils.global when wrapped in a module.

---

core/field_dropdown.js
tests/blocks/test_blocks.js
tests/playground.html

https://github.com/google/blockly/issues/2493
https://github.com/google/blockly/issues/2926
Only generate options during inialization (as we need the first tuple) and when a use clicks on the field to open it. (ie: when the editor is shown / widget is created). 
Be more efficient about calling a dynamic dropdown function and not break in places where we expect certain options to be available. 
Tested the playground, and added a new test dropdown block that returns a random number of items every time the generate method is called. 
Tested on:

Cache dynamic dropdown options

---

tests/compile/main.js

The block files now handle the requires for these fields.

Remove now unneeded requires from compile test.

---

core/block_svg.js
core/requires.js
core/workspace_svg.js

Saves 6 KB when compiled if there is no trashcan nor zoomcontrols.

Make trashcan and zoomcontrols optional modules.

---

core/field_multilineinput.js
core/field_textinput.js
tests/blocks/test_blocks.js
tests/playground.html

Work on #2722 
Gives the multinline input field an opt_config parameter.
Also I fixed a little text input doc bug.
Currently the field doesn't have any of its own config options, but now it can support tooltips and spellcheck correctly.
I didn't add any configuration tests because this field doesn't have any options of its own, but I did add a test block, and everything seems to be working.
Tested on:
When the multiline input field gets written up, its creation section should include info about its config properties.
N/A

Changed multiline field to use new configuration

---

core/keyboard_nav/navigation.js

Don't insert disabled blocks from the flyout.
Match mouse behaviour.

Don't insert disabled blocks from the flyout.

---

core/blockly.js

Closes #3008 
Makes it so you can scroll the trashcan flyout with mouse/touch input.
Mobile users need to be able to scroll with mouse/touch.
Tested scrolling the trashcan flyout using mouse input on the flyout background, and on the scrollbars, for every workspace on the multiplayground.
Also tested that clicking on the workspace surface/blocks still closes the flyout, which it does.
Tested on:
N/A
How's this fix look to you @samelhusseini ?
I looked through all the hideChaff calls, and I think this is the correct behavior.

Fixed scrolling the trashcan flyout with mouse

---

core/keyboard_nav/cursor_svg.js
core/renderers/common/renderer.js
core/workspace.js
core/workspace_svg.js

Moves initialization of drawer for cursor to the renderer, rather than in the WorkspaceSvg constructor.
Additionally, in order to have access to the renderer when setCursor and setMarker are called, the initialization of the renderer was moved to getRenderer(), so the renderer is now initialized at the first time getRenderer is called, rather than in the WorkspaceSvg constructor. At this time, this means that the renderer is initialized at the overridden setCursor call for WorkspaceSvg (inside of the super constructor call).
We expect some people to customize their cursor, so moving the initialization to the renderer gives more flexibility for changing what implementation of the cursor drawer to call.
Tested on:

Creating cursordrawer in renderer.

---

core/components/tree/basenode.js
core/components/tree/treecontrol.js
core/components/tree/treenode.js
core/field_colour.js
core/keyboard_nav/navigation.js
core/theme.js
core/toolbox.js
tests/mocha/navigation_test.js
tests/mocha/xml_procedures_test.js

Merge both types of toolbox navigation (when in accessibility mode) and when we're not. 
The arrow keys can be used when we're not in accessibility mode and focused on the toolbox.
The logic was duplicated into Blockly.navigation. This moves it all into the one places and makes use of the same methods in base_node.js
I've also moved the handling of a blockly action on a toolbox into toolbox.js.
The two navigation methods were tracking the selected category differently causing conflicts when using both interchangeably.
Tested on:

Merge toolbox navigation 

---

core/keyboard_nav/navigation.js

When inserting a block from the flyout into the middle of a stack the block was not being added correctly.
In insert block use the connect_ method instead of moveAndConnect_. The connect_ method does more logic for checking which connection to check, while the moveAndConnect_ method just connects whatever connections it is given.
Tested on:

Fix inserting into middle of stack from flyout
