google/blockly

core/blockly.js
core/components/component.js
core/components/menu/menu.js
core/components/tree/basenode.js
core/components/tree/treecontrol.js
core/css.js
core/field_colour.js
core/requires.js
core/toolbox.js
core/utils/idgenerator.js
core/workspace_svg.js

This drops the compiled size by 25 kb if there are no categories.  Which also indicates that the toolbox itself suffers from really bad bloat.  The toolbox should not represent 1/6th of our codebase.

Make toolbox an optional module.

---

core/block.js
core/block_svg.js
core/bubble.js
core/comment.js
core/icon.js
core/mutator.js
core/warning.js
core/xml.js
generators/dart.js
generators/javascript.js
generators/lua.js
generators/php.js
generators/python.js
tests/mocha/block_test.js
tests/mocha/comment_test.js
tests/mocha/index.html
tests/mocha/xml_test.js

Closes #1969 
* Moved comment icons to use a model-based system. The block holds the model of the comment, and the comment icon holds a reference to it.
* Reorganized the setVisible function.
* Changed how xml.js serializes and deserializes comments.
Some other little things:
* Removed blockSvg's getCommentText function.
* Changed bubble.getSize to return a Blockly.utils.Size object.
* Removed a rendered_ check from the bubble.
* Changed icons to properly call the parent updateEditable function.
* Fixed block disposal/delete events.
* The previous organization caused erroneous events to be fired.
* Fixed round-tripping through a headless workspace.
* This can now be handled by the headless block.
* Type specificity is good.
* This was unnecessary and causes icons to have to set the size …

Fixed comment ownership.

---

core/renderers/common/info.js
core/renderers/measurables/rows.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Fixes #2945 
Refactors populate method from Row Measurable to RenderInfo.
Other rows are populated in RenderInfo, so moving the logic for top and bottom row seems consistent.
Tested manually on playground.
Tested on:

Move populate for topRow and bottomRow to info

---

core/field_dropdown.js

#2722
Adds an opt_config property to the dropdown field that accepts 'tooltip'.
I didn't add unit tests since this field doesn't have any of its own config options, but I did manually test that the tooltips passed through JSON are applied.
Tested on:
Not necessary. #2706 docs should cover this.
N/A

Changed dropdown field to use new configuration

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/measurables/rows.js
core/renderers/thrasos/info.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Fixes #2964 
Adds functions to row to check whether spacer element should be added to start or end of row and removing adjustments in other places of code that assume that the last spacer is not the correct one.
In certain cases, like with statement input, external input, and end of top/bottom row (zelos), the last spacer in the row is not actually a spacer that we want to modify and instead get the second to last spacer of that row. Not adding a spacer to the ends in some cases simplifies logic.
Tested on playground by checking that flyout blocks in different categories render correctly (especially for cases for statement input and external input) with all 3 renderer types.
Tested on:

Adding checks for whether to add elem spacer on row ends

---

core/components/menu/menu.js
core/field_dropdown.js

Handle blockly actions on the dropdown fields. Move up and down with actions mapped to PREVIOUS and NEXT in Blockly navigation.
Field dropdown support for Blockly actions.
Playground.
Tested on:

Handle blockly actions on the dropdown fields.

---

core/insertion_marker_manager.js

Fixes #2556
Sets field values for insertion markers directly with setValue instead of using setFieldValue.
Using setFieldValue causes an issue when multiple fields on a block share the same name. In that case, the value would always be set to the first field with the shared name, potentially causing inaccuracy in the rendered size of the insertion marker.
Tested using custom blocks in playground with shared field values (that would render incorrectly before change).
Tested on:

Copying values to insertion marker fields directly.

---

core/field_dropdown.js
core/field_variable.js
tests/mocha/field_variable_test.js

Closes #2722
Adds an opt_config option to the variable field.
I added the option to configure types using the opt_config, but I did it on a separate commit so it can be easily reverted.
The initial commit just adds an opt_config property so variables can support tooltips.
Added tests for configuring types using different methods.
And for the initial commit I manually tested setting tooltips via json.
Tested on:
If you want to keep configuring types via the opt_config the variable field's [creation ](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/variable#creation)section may need updates.
Configuring types via opt_config is on a separate commit, so it'll be easy to revert if you don't want it. …

Changed variable field to use configuration

---

core/block_svg.js
core/field.js
core/input.js
core/workspace_svg.js

Fixes https://github.com/google/blockly/issues/2811
When a workspace re-gains visibility. It's possible some fields may have been imported while the workspace was not visible. We'll need to re-compute the field size. This PR goes through all blocks on the workspace and marks their fields as dirty. The next time render is called, the field's sizes are re-computed.
A previous attempt at this https://github.com/google/blockly/pull/3041 breaks collapsed mode.
Tested playground, tested adding blocks onto the workspace when the workspace is not visible. 
Also tested that this works with collapsed blocks.
Tested on:
@BeksOmega FYI

Mark fields as dirty when the workspace becomes visible.

---

core/components/component.js
core/components/menu/menuitem.js
core/components/tree/basenode.js
core/css.js
core/field_colour.js
core/flyout_base.js
core/inject.js
core/toolbox.js
core/workspace_svg.js

Also removes three private accesses from workspaceSvg into toolbox tree.
The strategy for workspace.updateToolbox is no longer to clear and repopulate the toolbox, but rather to throw away the old toolbox and rebuild a new one.  This is simpler and more reliable.
This commit trims off another KB from the compiled code.

Strip out more bloat from toolbox

---

core/renderers/common/info.js

Addresses one of the concerns in #2933 
Adds check so that last row is pushed if it has a dummy input, even if there are no elements.
Rows with dummy inputs are not considered empty so the row should have been pushed.
Tested on playground.
Tested on:

Adding check for pushing last row with only empty dummy input.

---

core/block_events.js
core/bubble_dragger.js
core/components/menu/menu.js
core/components/menu/menuitem.js
core/components/tree/basenode.js
core/contextmenu.js
core/css.js
core/dropdowndiv.js
core/field_multilineinput.js
core/toolbox.js
core/variables_dynamic.js
core/widgetdiv.js
core/workspace_comment_render_svg.js
core/workspace_comment_svg.js
core/workspace_svg.js
core/ws_comment_events.js
core/xml.js
demos/custom-fields/turtle/field_turtle.js

Random improvements to require statements.
Removal of some obviously dead CSS.
.blocklyDropDownDiv no longer suppresses text selection (see comment in PR).
This PR drops the compiled size by 4 KB, which is larger than I was expecting.

Code cleanup, drop some CSS.

---

core/block.js
core/connection.js
core/rendered_connection.js
tests/jsunit/block_test.js
tests/mocha/block_test.js

Fixed #2991 
Always disconnects child block with healStack true in unplugFromRow_. Bumps child block away if it cannot be connected.
Desired behavior.
Blockly playground
Tested on:

Disconnect child block always for block.dispose(/* healStack */ true)

---

.eslintrc.json
core/block.js
core/block_events.js
core/bubble.js
core/insertion_marker_manager.js
core/keyboard_nav/ast_node.js
core/keyboard_nav/cursor_svg.js
core/toolbox.js
core/touch_gesture.js
core/workspace_comment_render_svg.js
core/workspace_svg.js
tests/mocha/connection_test.js
tests/mocha/field_test.js
tests/mocha/xml_procedures_test.js

Fix up all remaining violations and turn the rule on.
Turns on another rule so we don't have to manually check it.
Only comment changes.  Here's the rule: https://eslint.org/docs/rules/spaced-comment
This was already a warn; now it's an error.

Enable eslint rule spaced-comment

---

.eslintignore
core/block.js
core/css.js
core/field_angle.js
core/field_colour.js
core/field_date.js
core/field_multilineinput.js
core/flyout_button.js
core/keyboard_nav/ast_node.js
core/toolbox.js
core/zoom_controls.js

Drops the compile test by 3 KB.
Remove obsolete .blocklyDraggable class stub (it used to be dynamically changed).
Remove unused menuseparator CSS.

Break CSS into modules.

---

core/block_svg.js
core/bubble.js

The JS Compiler would rename ‘id’ and ‘blockId’ to something random.  Normally that would be fine, but if it ended up with a ‘$’ in the name, then that becomes an illegal HTML property name and Blockly crashes.
A bug that’s been lurking in Blockly for years and randomly surfaced on a recent compile.

Prevent dataset IDs from being renamed

---

core/extensions.js
core/field_registry.js
core/renderers/common/block_rendering.js
tests/mocha/field_registry_test.js

Fixes #2788
Adds unregister methods for extensions, fields, and renderers.
Changes field register to throw error if another is registered with same name.
Makes the behavior of register functions more consistent with extensions, fields, and renderer all throwing an error when something is registered with same name as existing and adding an unregister functionality for all of them.
Ran tests.

Updating behavior of register functions and adding unregister.

---

tests/playground.html
tests/screenshot/playground_new.html

Removes deprecated renderMode reference in playground and removing TODO since #2702 has been resolved.
Renderer is no longer set using renderMode.

Removing deprecated renderMode reference in playground.

---

core/xml.js

…if Blockly.Comment was not compiled in.
Untested, but should work.

Block comments from XML not fatal

---

core/components/tree/basenode.js

Fix crash in IE.
el.style is readonly in strict mode IE.  Fixing crash in IE.
Fix crash in IE.
Tested on:
* IE11

Fix crash in IE

---

core/renderers/common/debugger.js
core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/thrasos/info.js
core/renderers/zelos/info.js

Use row height for spacer height, instead of spacers being the default height all the time.
This fixes an issue with debug rendering showing spacers in the row place.
Pull the corresponding code up into the base renderer for code reuse.

Use row height for spacer height.

---

core/dropdowndiv.js

If using a framework (such as React), we will want a way to unmount components from the dropdown div element before disposing of it.
Re-ordering the dispose order so that ``onHide`` is called before clearing the dropdown div contents.
Tested on:

Call onHide before disposing of the dropdown div element.

---

core/workspace.js
core/xml.js

Related to https://github.com/google/blockly/pull/3115
Actually make WS comments optional, by removing the last remaining reference to it in ``core/xml.js``.
``- 10KB`` compressed.
Tested on:

Actually make WS comments optional

---

core/renderers/geras/info.js

Fixes #3098, which is the case when the field next to an inline input us taller than the inline input itself.

Bound element position based on height of the row

---

core/renderers/common/info.js
core/renderers/zelos/info.js

Resolves https://github.com/google/blockly/issues/3132
Add spacing before next / previous connection notches in the base renderer to account for the notch offset. 
Take into account square corners when there is a next connection.
Move baseline alignment of rows into the base renderer to take into account top and bottom row baseline. 
Couple of issues with the base renderer.
Tested all renderers in the playground.
Tested on:

Base renderer next / prev notch alignment issues

---

core/blockly.js

Variables and Xml are circular dependencies.  Both need to be declared in blockly.js
Maybe they can be sorted out later, but for now things are broken since nobody in core currently requires variables anywhere.
Also alphabetize (not asciibetize) the requires in blockly.js.

Restore require variables to blockly.js

---

core/flyout_button.js
core/workspace_svg.js
core/zoom_controls.js

Fix some annotations and remove setting things to null in dispose for flyout buttons.
I played around with the memory tab in chrome dev tools to make sure this wasn't retaining anything extra as a result.
There are some event listeners attached to the dom nodes but they don't keep anything else alive, and no one else references them, so they disappear with the nodes.

Misc cleanup

---

tests/playground.html
tests/playgrounds/screenshot.js

Add an option on the playground to download a screenshot of the blocks on the workspace.
Only supporting Chrome at this point, and only blocks on the workspace, this is meant for testing and not a feature ready for production.
Tested on:

Download screenshot in playground

---

core/block.js

Fixes block toString when collapsed.
When collapsed, toString was referencing text_. Using getText instead.
Found this through compiler warnings.
Tested on:

Fix collapsed toString.

---

blocks/lists.js
blocks/logic.js
blocks/procedures.js
core/block.js
core/block_svg.js
core/components/tree/treecontrol.js
core/extensions.js
core/field.js
core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_date.js
core/field_dropdown.js
core/field_image.js
core/field_label.js
core/field_label_serializable.js
core/field_number.js
core/field_registry.js
core/field_textinput.js
core/field_variable.js
core/input.js
core/mutator.js
core/names.js
core/rendered_connection.js
core/renderers/common/block_rendering.js
core/variables.js
tests/mocha/input_test.js

Fixes 34 warnings related to fields.
``bumpNeighbours`` is @package.
Fix unregister calls to delete from map rather than set to undefined.
Make ``SERIALIZABLE`` and ``EDITABLE`` not constants.
Fix ``doValueUpdate_`` parameter to be consistent with super class. 
Compiler warnings.
Tested on:

Fix compiler warnings related to fields.

---

core/block.js
core/block_svg.js

https://github.com/google/blockly/issues/3152
Turns out @package is more restrictively. Making ``bumpNeighbours`` public since it's used in blocks.
This is a bit lame, because what we really want is @package. A way to say this is okay to be used within our codebase but not outside, but blocks falls in a different directory, so we can't use @package. 
Tested on:

Make bumpNeighbours public.

---

demos/custom-fields/turtle/blocks.js
demos/custom-fields/turtle/field_turtle.js

#3153 
Removes the Object.assign call from the turtle demo.
No longer assign to properties of the bbox (not that we were trying to change them anyway).
Doesn't work in IE.
Throws errors in IE.
Tested the relevant example block manually.
Tested on:
* Desktop Firefox 
* Windows Edge
N/A
I figured this was just for a demo, so I went with the simple options.

Removed Object.assign() from turtle demo

---

core/keyboard_nav/key_map.js

Fixes #3153
Remove last instance of Object.assign which is not available in IE / ES5.
Tested on:

Remove last instance of Object.assign

---

core/block_dragger.js
core/bubble_dragger.js
core/trashcan.js
core/workspace_svg.js

Grinding through compiler warnings.  Removes 6.
- Make trashcan's `setOpen_` package and rename to `setOpen`
- Update a few annotations in workspaceSvg to be more accurate.
Note: trashcan has `close()` but it just calls `setOpen(false)`, and there's no `open()` function.  Maybe we should just get rid of `close()` and use `setOpen` everywhere?
Compiler warnings
I used the trashcan in the playground.
This can go in after we cut the release.

Make trashcan setOpen package and update a few annotations.

---

tests/playground.html

The change image flyout button throws an error.
We no longer need this call to setText, and setText is very much deprecated. 
Removing.
Tested on:

Remove call to setText in playground

---

core/block_svg.js
core/connection.js
core/connection_db.js
core/input.js
core/keyboard_nav/navigation.js
core/rendered_connection.js
core/xml.js
tests/mocha/connection_db_test.js

N/A
Changes all reference to `hidden_` or `inDb_` to `tracked_`.
There were also quite a few picky doc changes that went with this.
These meant /slightly/ different things before, but they were similar enough that it seemed weird to have two properties. It also seemed confusing to have a property named 'hidden_' that didn't always reflect the visibility of the connection (since it had to do with database tracking, not visibility).
Already has tests coverage.
Reenabed two disable tests.
Tested on:
N/A
Related to #2994

Connection Tracking Pt 3: Changed connections to use 'tracked_' property

---

core/field_number.js

Fixes #3180 
The number field now accepts any case-variation of "Infinity".
Firstly because #3180 requested it and I also think that it would be convenient to use "infinity" lower-case or prevent the user from accidentially capitalizing one letter.
Tested on:
* Desktop Chrome - Version 77.0.3865.90 (Official Build) (64-bit)
* Windows Internet Explorer 11 - Version 11.388.18362.0
* Windows Edge - Version 44.18362.387.0

Make "Infinity" case-insensitive in number field

---

core/keyboard_nav/ast_node.js
tests/mocha/astnode_test.js

Remove findPreviousEditableField_ from ast node. 
It wasn't being used anywhere.
Tested on:

Remove dead code from ast node

---

core/dropdowndiv.js
core/field_colour.js

Fixes https://github.com/google/blockly/issues/3190
Add support for setting the direction in RTL.
Fields that want to always render in LTR can explicitly set that in their own divs.
RTL support.
Tested on playground in: 
Tested on:

Dropdowndiv RTL support

---

gulpfile.js
typings/blockly.d.ts
typings/parts/blockly-interfaces.d.ts
typings/parts/goog-closure.d.ts

setLocale not in typescript definitions as it's defined under ``package/``.
https://groups.google.com/forum/#!topic/blockly/UXjQnNHTixA
Adding to the override typings.
Remove goog typings.
Affects angular sample / anyone using the npm release and wants to update the locale.
Tested with angular sample.
Tested on:

Add setLocale to the Blockly typescript definition file.

---

core/rendered_connection.js

See #3199 
This is a separate commit instead of a cherry-pick because the code around it has changed names on develop.

Version of #3199 for release

---

core/dropdowndiv.js

Revert calling dropdown hide.
Reverted the order in which we call onHide when we're animating. This way each field is able to dispose of their dropdown by unbinding event listeners even before the animation is complete.
Avoid dropdown double click issues when animating. 
Tested on:
Fix warning while I'm at it.

Revert calling dropdown hide order

---

core/block_svg.js

The ``appendChild`` is causing a reflow takes much longer with larger workspaces.
Something as simple as a field click causes calls to bringToFront.
Minor optimization to skip moving a block if it's already in the right position.
Perf.
Tested on:

bringToFront optimization for large workspaces

---

core/block_svg.js

Previously we'd assume the tab height would always be 4:
https://github.com/google/blockly/blob/4efa0dad1f2c882234759d3ba7ecd0ebd95a4c77/core/block_render_svg.js#L304
Use the constant instead, so it'll work with renderers that have different tab heights. Fixed with lots of help from @samelhusseini!

Look up notch height from the current renderer

---

generators/javascript.js
generators/python.js
tests/generators/golden/generated.js
tests/generators/golden/generated.py

Fixes #3230 by removing multi-line comments for procedures.
Should be cherry-picked
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3231)

Remove multi-line comments to avoid escaping

---

generators/javascript.js
generators/python.js
tests/generators/golden/generated.js
tests/generators/golden/generated.py

Cherry-pick of #3231 
Fixes #3230 by removing multi-line comments for procedures.
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3232)

Remove multi-line comments to avoid escaping (#3231)

---

demos/blockfactory/factory_utils.js

Fixing JSON.parse misspelling.  It causing the Blockly Block factory to break.  Minor fix.  I pull from master branch because I thought you might want to release this soon.

Fix Capitalization Error

---

core/keyboard_nav/cursor_svg.js

Resolves #3225 in which movement of the accessibility cursor appears delayed for movement which occurs while the cursor is not visible.
Adds a check for an animate (in a way that assumes animate is the only type of child the cursor ever has) element in the current cursor and calls `beginElement()` on it if found to restart the animation.
Before patch
With patch applied
No automated tests changed or added.
Manually tested on:
No doc updates
I discussed this in person with Abby at the Blockly Summit Hackathon on Oct 11.

restart cursor animation on cursor move

---

core/trashcan.js
tests/mocha/trashcan_test.js

Closes #3243
Closes #2574 
* Disabled tags are removed from blocks when they are added to the trashcan.
* h, w, and pinned tags are removed from block-comments when they are added to the trashcan.
* See reasoning [here](https://github.com/google/blockly/issues/2239#issuecomment-458290090). I was going to go with the alternative suggestion [here](https://github.com/google/blockly/issues/3243#issuecomment-541941991), but I believe that would allow users to get around the maxBlocks/maxInstances if disable/enable was available.
* This allowed "duplicate" blocks that looked the same to exist in the trashcan.
Modified unit tests to reflect changes.
1. Added disableOrphans listener to playground.
2. Dragged blocks onto the workspace.
3. Dragged them into the trashcan.
4. Observed how they were …

Fixed disabled blocks in trashcan. Also fixed block comments.

---

tests/blocks/index.html

Blocks tests are broken because no goog. in blockly_compressed.
``/tests/blocks/index.html``
Use uncompressed instead.
Fix test
Tested on:

Fix blocks tests

---

core/blockly.js
core/components/component.js
core/field.js
core/field_angle.js
core/field_colour.js
core/field_dropdown.js
core/field_image.js
core/field_multilineinput.js
core/field_textinput.js
core/field_variable.js

Memory leaks with fields when closing fields, but also when disposing of fields.
Dispose of references to all elements created as part of the render pass in field ``dispose``. Dispose of all references to elements created in widget/dropdown create methods in widget/dropdown dispose.
Plugging leaks
Tested using chrome perf tools.
Creating and disposing fields + opening / closing fields.
Tested on:
@BeksOmega FYI

More field dispose

---

core/components/menu/menu.js
core/components/menu/menuitem.js
core/components/tree/basenode.js
core/field_colour.js
core/field_dropdown.js
core/field_multilineinput.js
core/field_number.js
core/field_textinput.js
core/utils/aria.js

Use enums instead of arbitrary strings.
Comment out unused enum values.
Add missing requires.
Delete unused code.

Cleanup aria usage.

---

core/css.js
core/dropdowndiv.js
tests/mocha/dropdowndiv_test.js

Fixes https://github.com/google/blockly/issues/3178.
Also repro'ing https://github.com/google/blockly/issues/3178 on Mac Safari by opening a dropdown div after the browser has been zoomed.
Make the dropdown div absolutely positioned similar to the widget div. Calculating positioning based on the scaled bounding box of a field / block.
Fix up a bunch of visibility on the dropdown methods. No need for them to be public.
Tested zooming the playground and opening the dropdown div.
Tested on:
* IOS

Dropdowndiv positioning

---

core/dropdowndiv.js
core/keyboard_nav/cursor_svg.js
core/renderers/common/debugger.js
core/utils/colour.js

Over the past month a couple of instances of "color" appeared in our codebase.  I don't actually care about how people spell this word, but consistency and predictability is important.  It isn't good if 90% of our API uses one spelling, and 10% uses a different spelling.
I assume this choice was unintentional.

Normalize to one spelling of color/colour.

---

core/workspace_svg.js

#3248 
Reverts a change made by #2247 (it was just meant for efficiency).
It broke things, because `onScroll_` was no longer getting called.
1. Attempted to drag a block outside of the workspace bounds.
2. Observed how scrollbars resized to show the block.
1. Moved blocks to high x-coordinates.
2. Cleaned up blocks.
3. Observed how blocks were still in view.
Tested on:
N/A
We could also add a call to `this.centerOnBlock(topBlocks[0]);` at the end of `workspace.cleanUp` if you want @NeilFraser .

Fixed block cleanup

---

core/field_textinput.js
core/renderers/measurables/rows.js
core/renderers/zelos/measurables/rows.js
demos/custom-fields/pitch/field_pitch.js

Clean up.
Fix jsdoc. @return instead of @returns
Tested on:

Fix jsdoc. @return instead of @returns

---

core/renderers/common/info.js
core/renderers/measurables/rows.js

Fixes https://github.com/google/blockly/issues/3279
Only add a hat if there's no output connection
Rendering fix.
Tested on the playground by changing the ``Blockly.BlockSvg.START_HAT = true``
Tested on:

Only add a hat if there's no output connection

---

core/block_dragger.js

Addresses #3216, creating UI events for the start and end of a drag.
Creates UI events "dragStart" and "dragEnd" which are fired at the start and end of a drag respectively.
"dragStart"
Provide support for updating the UI in response to a block being dragged.
Tested on:
Desktop Chrome
The Events document needs to be updated to include "dragStart" and "dragEnd" to the list of valid element values.

Add dragStart and dragEnd UI events

---

core/events.js
core/workspace_events.js
demos/mirror/index.html

Currently the playground throws when a block is deleted and the delete is undone.

Make finished-loading events be UI events

---

tests/compile/compile.sh

We now require the use of a separate script tag for the message file.

Messages are no longer compiled in.

---

closure/goog/base.js
core/block_svg.js
core/renderers/common/debugger.js
core/renderers/common/info.js
core/renderers/common/path_object.js
core/renderers/common/renderer.js
core/renderers/geras/measurables/inputs.js
core/renderers/measurables/connections.js
core/renderers/measurables/types.js

Fix 6 compiler warnings.
Suppress module not found with Blockly.blockRendering.Debug as it's only included in the playground.
Add requireType. Allows us to require type information from another file without including that file in the dependency tree.
Interfaces and Enum cannot be @package.
Tested on:

Fix 6 warnings related to rendering.

---

core/generator.js

6 compiler warnings.
Blockly.Procedures.NAME_TYPE is deprecated. Using Blockly.PROCEDURE_CATEGORY_NAME instead.
Add type information for properties defined in each of the generators.
Tested on:

Fix 6 warnings related to generators.

---

core/generator.js
generators/dart/procedures.js
generators/javascript/procedures.js
generators/lua/procedures.js
generators/php/procedures.js
generators/python/procedures.js

Blockly.Procedures.NAME_TYPE is marked as deprecated so just removing it from use in our code.
Tested on:

Remove deprectaed use of Blockly.Procedures.NAME_TYPE

---

core/contextmenu.js
core/workspace_svg.js
core/xml.js

Suppress compiler errors related to workspace comments as it's complaining about not finding the module. (Since it's not bundled in). 
Added a TODO issue to remove these suppress tags when we bundle workspace comments back in.
https://github.com/google/blockly/issues/3302
Tested on:

Suppress workspace comment compiler errors.

---

core/flyout_horizontal.js
core/flyout_vertical.js
core/inject.js
core/options.js
core/toolbox.js
core/trashcan.js
core/workspace_svg.js

Partial fix for https://github.com/google/blockly/issues/2937
Make Blockly options an interface that can be extended in the Typescript typings. This makes the closure compiler happy with the type given to ``Blockly.Options`` but also allows us to extend the type to include the full list of options. 
I would prefer to just define the options interface in closure (using @typedef) but unfortunately closure doesn't support optional properties and all the properties are optional.
This solution makes it so that you can do something like ``Blockly.inject(div, {
... options
});`` and not have to cast options to Blockly.BlocklyOptions.
Ran ``npm run typings`` and tested with the Angular sample (TypeScript).
Tested on:

Make Blockly options an interface

---

core/block_svg.js
core/insertion_marker_manager.js
core/rendered_connection.js

Fix 17 warnings related to insertion markers.
Added ``BlockSvg.lastConnectionInStack`` and ``getMatchingConnection`` that both return ``RenderedConnection`` instead of ``Connection``.
Added ``RenderedConnection.getSourceBlock`` and ``targetBlock`` that return ``BlockSvg``'s instead of ``Block``.
Use connection.``getSourceBlock`` instead of ``sourceBlock_``.
Tested on:

Fix warnings related to insertion markers.

---

core/block_dragger.js
core/block_svg.js
core/bubble.js
core/gesture.js
core/icon.js
core/touch_gesture.js
core/workspace_comment_svg.js
core/workspace_svg.js

Fixes 17 compiler warnings.
Visibility: 
Renamed block.``moveOffDragSurface_`` to ``moveOffDragSurface`` and made it package.
Renamed block/comment/workspace .``showContextMenu_`` to ``showContextMenu`` and made it package.
Cast gesture. startWorkspace_, startBubble_, targetBlock_ to each of their none null types where they're called after a start drag that sets them.
Tested on:

Fix warnings related to gestures and drag.

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/measurables/inputs.js

Fixes #3228 
Only use the dark path offset in bottom row height in Geras
Height of the connected block includes the dark path, but height while laying out this block doesn't.
Checked Geras, Thrasos, and Minimalist.  Test cases included a concatenation of not blocks and of ternary blocks.
None

Fix #3228 by only using the dark path offset in Geras.

---

core/names.js
core/procedures.js

Fixes 10 compiler warnings.
Fix compiler warnings in procedures. Since we have no type information from Blockly core of what a procedure block looks like, and since there's extra methods it requires. I've added a ProcedureBlock type definition that's used by core/procedures.js.
Also fixes deprecated call to Blockly.Variables.NAME_TYPE.
No functional change.
Tested on:

Fix compiler warnings in procedures

---

build.py

Fix cloud compile build.
calcdeps.py doesn't understand reqiureType. Stripping it out before sending files up to the closure cloud compiler.
Tested on:

Fix cloud compile build

---

core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js

Draw a notch to match zelos style. 
Also resolves https://github.com/google/blockly/issues/2963
Draw a notch after a statement input.
Add a minimum height for the bottom row following a statement input.
Remove any space between the last statement and the statement input.
Tested zelos and geras in playground.
Tested on:

[zelos] Draw a notch after a statement input

---

core/block.js
core/block_svg.js
core/bubble_dragger.js
core/flyout_base.js
core/grid.js
core/input.js
core/trashcan.js
core/workspace_dragger.js
core/workspace_svg.js

Resolve remaining type issues that are triggered by setting non-nullable objects to null in dispose.
I'm suppressing ``checkTypes`` in all disposes to avoid having to deal with non-nullable types all over our code. My reasoning to special case ``dispose`` in these objects is because it's only setting it's (non-null) properties to null to clear their reference, and the object is then immediately thrown away, so it's more convenient for us to assume these properties are non-nullable if they are truly non-nullable throughout the object's lifecycle and only null when disposed.
Note: in some cases setting properties to null isn't necessary but I'm not tackling that here.
Tested on:

Resolve all type issues with disposal

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/measurables/inputs.js

Fixes https://github.com/google/blockly/issues/3330
Wrap dummy inputs in a measurable so that it can be aligned appropriately by ``addAlignmentPadding_``.
Fix rendering.
Tested with the following block in the block factory: 
```
{
"type": "test",
"message0": "s %1 some %2 s %3 ss %4",
"args0": [
{
"type": "input_dummy",
"align": "RIGHT"
},
{
"type": "input_statement",
"name": "NAME",
"align": "RIGHT"
},
{
"type": "input_statement",
"name": "NAME",
"align": "RIGHT"
},
{
"type": "input_value",
"name": "NAME",
"align": "RIGHT"
}
],
"colour": 230,
"tooltip": "",
"helpUrl": ""
}
```
@rachel-fenichel FYI.

Fix dummy input alignment. Fix for #3330

---

core/block.js
core/block_svg.js
core/blockly.js
core/gesture.js
core/inject.js
core/keyboard_nav/navigation.js
core/mutator.js
core/toolbox.js
core/workspace.js
core/workspace_svg.js
msg/json/en.json
msg/json/qqq.json
msg/messages.js
tests/mocha/gesture_test.js
tests/mocha/navigation_test.js

Adds support for navigating to multiple workspaces using the keyboard.
1. Add keyboardAccessibilityMode onto the workspace
2. Add a tabindex and label onto the injectionDiv
3. onFocus set the mainworkspace
4. onBlur set the mainWorkspace to null
Want to be able to test with screen readers so we need to add a tabindex, and also multi workspaces should work with keyboard navigation.
Tested on:

Add keyboard navigation support for multiple workspaces

---

core/block.js
core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/measurables/rows.js

We weren't accepting lowercase alignment values in block config.
Accept lowercase version of LEFT, RIGHT, and CENTRE.
Accept alternate spelling of CENTER.
The first input decides the alignment.
Add input type information on the row.
More flexibility in what we author.
This block now looks like it was authored (with a right aligned value input)
Tested on:

Accept lowercase alignment

---

core/block_svg.js
core/keyboard_nav/navigation.js
core/rendered_connection.js
core/xml.js
tests/mocha/block_test.js

Closes #3305 
Adds a third state to the tracked_ property. It means "This connection is not currently tracked but it will add itself to the db on the next moveTo call it recieves". It is currently symbolized by a `null` value.
Other changes just got that working.
To work elegantly in the current architecture connections need to be able to add themselves to the connection db automatically on the first moveTo call.
I added connection tracking tests for both adding and removing connections programmatically.
I was also not able to reproduce #3305.
Tested on:
N/A
I think this is a pretty good way of solving this problem, but I'm open to other options, including reverting #3133

Fixed programmatically added connections not being added to the connection db

---

core/flyout_button.js

Fixes https://github.com/google/blockly/issues/1928
The SVG is LTR, add an RLM after flyout button texts for RTL languages to switch the text direction.
Fix bug.
Tested in the playground with the ar.js lang.
Tested on:
Fixed

Add an RLM after Flyout button text for RTL languages

---

core/css.js
core/utils/dom.js

Fixes https://github.com/google/blockly/issues/3368
Use zero height / width for compute canvas and position:absolute.
So it doesn't affect layout.
Tested on:
* Edge 18
* IE 11
@BeksOmega

Use zero height / width for compute canvas

---

core/flyout_vertical.js

Originally introduced in: https://github.com/google/blockly/commit/29571e91e25248dfb854203d5cb4c50ef82c2f0a
The workaround was unintentionally broken by https://github.com/google/blockly/pull/2311
The root Firefox bug ([1066435](https://bugzilla.mozilla.org/show_bug.cgi?id=1066435)) has been fixed, so removing.
Remove firefox flyout positioning workaround code.
Workaround broken, cleaning up.
Tested on:
* Desktop Firefox 69.

Remove Firefox flyout positioning workaround

---

core/bubble.js

Fixes https://github.com/google/blockly/issues/1896.
Take into account RTL workspaces and the width of the bubble when returning the relative positioning of the bubble to the bubble dragger.
Fixes bug.
Tested in playground in both LTR and RTL.
Tested on:

Fix RTL bubble drag

---

core/options.js
core/theme.js
core/workspace.js
typings/parts/blockly-interfaces.d.ts

Support passing in a theme in workspace options as JSON, rather than having to pass in a Theme Object.
Updated typings.
Most of our other configuration is in JSON. It's serializable and easier for developers to work with.
Tested on:

Support workspace theme option as JSON

---

core/theme.js

Fixes https://github.com/google/blockly/issues/3382
Access the theme object properties with bracket notation so advanced compilation doesn't rename them.
@rachel-fenichel FYI
Fixes colours in advanced compilation.
Tested on:

Fix block colours in advanced compilation

---

core/workspace.js
core/workspace_svg.js
tests/jsunit/block_test.js
tests/mocha/procedures_test.js
tests/mocha/xml_procedures_test.js

Fixes https://github.com/google/blockly/issues/3380
Moves the theme manager out of Workspace and into WorkspaceSvg, which also means there's no concept of a theme in headless mode.
This is originally how we would've done it but before https://github.com/google/blockly/pull/3357 we needed block styles in [Blockly.Block](https://github.com/google/blockly/pull/3357/files#diff-5148dfb78f1d110be97f1d3539fa647cR926)
Cleaner code.
Ran tests.
Tested on:

Move the theme manager into WorkspaceSvg

---

core/keyboard_nav/ast_node.js

Fixes #3339.
And adds support for #3344
Use isClickable() instead of EDITABLE when navigating around the AST. 
Add a flag on ASTNode to support going through all fields or only going through clickable fields.
Tested on:

Add flag to navigate to all fields

---

core/block_svg.js
core/renderers/common/i_path_object.js
core/renderers/common/path_object.js
core/renderers/geras/path_object.js

Moves more responsibility to the path object.
Move some functions that apply styles to the block's svg root into the path object.
Note that unlike #3390 this doesn't address moving styling into the renderer code.  This just moves the existing addition/removal of CSS styles.
Pre-work for different renderers implementing each of these differently.
Remove the pattern of having lots of different functions that really just decide whether to add or remove a class on the svg root.

Move lots of update style functions from block_svg to path_object

---

core/block_svg.js
core/xml.js

Part of #3142 
Remove two constants: TAB_WIDTH and SEP_SPACE_Y.
These were leftovers from block_render_svg, but we don't need them anymore.
Vertical separation of blocks during loading does not depend on the renderer and its constants.
Tab width no longer needs to be considered separately in `getHeightWidth` because it's handled in the rendering code.

Delete two leftover constants in block_svg.

---

blocks/logic.js
core/block.js

Closes #3392 
* Adds an isDisposed() function to block.js
* Checks if the prev blocks are disposed before trying to reconnect them.
* The disposed property is package. Adding a wrapper function keeps it protected, and it keeps the API looking consistent (isShadow, isMovable, isEnabled, etc).
* Avoids connect errors.
Could not reproduce #3392
Tested on:
N/A
See note [here ](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/connection.js#L298)about why this showed up as a "different workspaces" error.

Fixed logic_compare type checks for disposed blocks

---

core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Zelos constants.
More zelos constants.
Removing ``getInRowSpacing_`` from zelos as I don't see a need for anything more than the standard medium spacing between everything.
Also adding ``STATEMENT_INPUT_PADDING_LEFT`` to be considered by the common.
Remove top and bottom row spacers from Zelos.
Tested on:

More zelos constants

---

core/inject.js

Spurious warning.
Only warn about a bad move if we actually moved the object.
As it is the warning is actionable but wrong, which is not a good state.
Tested in the fixed playground.

Only log about a missing event group if we actually did something

---

tests/playgrounds/screenshot.js
tests/rendering/zelos/index.html
tests/rendering/zelos/pxtblockly.html
tests/rendering/zelos/zelos.html

Updates to the zelos rendering playground. 
Make it so each iframe returns an image of the block that can then be used to compare the two as animation on top of each other.
Tested on:

Zelos rendering playground updates

---

core/inject.js

#2929 
Wraps the object.getRootBlock call in a null check.
It seems like there's a race condition. Deleting a block via drag fires a move condition. And then the block gets disposed. It seems like sometimes listeners receive the move event after the block has already been disposed, so they can't access it.
No test coverage! I wasn't able to reproduce the error, so someone else should take a look as well.
Tested on:
N/A
I can close this since I wasn't able to reproduce if you want to take a look @samelhusseini 
I do think this should fix it though.

Fixed getRootBlock error in bumpObjects

---

core/field.js
core/field_dropdown.js
core/field_multilineinput.js
core/field_textinput.js
core/renderers/common/constants.js
tests/mocha/field_textinput_test.js

Establish a way for fields to access renderer constants.
Move the text size constants into the renderer.
Tested on:

Field constants

---

core/block_svg.js
core/renderers/common/i_path_object.js
core/renderers/common/path_object.js

None
Move highlightForReplacement into the path object so that it can use setClass.
Renderers should be able to make decisions about what it looks like to highlight a block for replacement.
Checked in the playground.

Move highlightForReplacement into the path object as well.

---

core/components/menu/menu.js
core/field_colour.js
core/field_dropdown.js
core/field_textinput.js
core/gesture.js
core/inject.js
core/workspace_svg.js

Fixes #3364.
1. Use focusin and don't set the mainWorkspace on focusout
2. Add prevent scroll to focus 
3. hideChaff before marking workspace 
Tested on:

Fix setting focus for workspace

---

core/components/menu/menu.js
core/components/tree/treecontrol.js
core/contextmenu.js
core/field_angle.js
core/field_colour.js
core/field_textinput.js
core/flyout_button.js
core/gesture.js
core/touch_gesture.js
core/workspace_comment_svg.js
demos/custom-fields/pitch/field_pitch.js

N/A
Every time there was an `unbindEvent_` call that wasn't part of disposing of the entire object I set the event data object to null. This pattern was already used some places, like scrollbars, and the workspace comment renderer.
This makes sure that if the function which contains the unbinding is called, we don't have unnecessary calls to `unbindEvent_`.
If we are disposing of the entire object, setting the event data object to null is unnecessary because we'll be getting rid of that reference anyway.
These changes shouldn't affect behavior.
N/A
N/A

Cleaned up unbindEvent_ calls

---

core/bubble.js

Work on #2512
Removes null settings from Bubble dispose.
Adds a `disposed` property to the bubble.
Unnecessary code is sad.
It's nice to be able to know when something is disposed.
This shouldn't change any functionality.
I tested this doing the following stress test while running a profile.
```
function memoryStrike(n) {
var toggleCount = 0;
var block = /** @type Blockly.BlockSvg */Blockly.Xml.domToBlock(Blockly.Xml.textToDom(
'<block type="controls_if">' +
'  <comment pinned="false" h="80" w="160">test</comment>' +
'</block>'), workspace);
for (var i = 0; i < 1000; i++) {
block.commentIcon_.setVisible(true);
block.commentIcon_.setVisible(false);
toggleCount++;
}
console.log(toggleCount);
}
```
Profiles are the same (within a margin of error): …

Fixed bubble dispose

---

core/renderers/common/info.js

Set statement input height to be the max of the default statement input height and the row height.
Tested on:

Statement input height

---

core/renderers/zelos/path_object.js

Zelos rendering in RTL.
Flip in RTL the input outlines.
Tested on:

Fix zelos input outline rendering in RTL

---

core/renderers/common/path_object.js

Unused code.
Remove the light path from the base path object, since it is no longer used outside of geras.
Cleanup!

Delete unused property on pathObject

---

core/block_svg.js
core/renderers/common/i_path_object.js
core/renderers/common/path_object.js

Move cursor svg and marker svg into the path object.
Moving markers and cursors into rendering generally.
Tested in playground with zelos and thrasos.

Move cursorSvg and markerSvg to pathObject

---

core/field.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_label.js
core/field_multilineinput.js
core/field_textinput.js
core/renderers/common/constants.js
core/renderers/geras/constants.js
core/renderers/zelos/constants.js
demos/custom-fields/turtle/field_turtle.js
tests/mocha/field_checkbox_test.js
tests/mocha/field_label_serializable_test.js
tests/mocha/field_label_test.js

I split up the change into multiple commits for easier review.
Border rect height, x and y padding, and text height / position moved to constants.
Upgraded all fields to use these values instead.
Added support for ``FIELD_TEXT_BASELINE_CENTER`` which uses dominant-baseline to have the browser align text vertically. (On by default)
Zelos center aligned rendering.
Tested geras and zelos renderers in playground.
Tested on:

Moves field layout constants into the renderer

---

core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/info.js
tests/rendering/zelos/zelos.html

Zelos spacing.
Add constants for top row and bottom row min spacing. Override in zelos.
Bring back in row spacing override for output connections, and pretty much always use medium spacing for everything else.
Fix zelos playground.
Zelos rendering. 
Tested zelos and geras in playground.
Tested on:

Fix up more zelos spacing

---

core/dropdowndiv.js
core/widgetdiv.js

Last remaining focus work. 
Return focus to the workspace after hiding a widget or dropdown div.
Keeping focus in Blockly.
Tested playground and multiplayground with keyboard nav. 
Fields, context menu, and dropdown div.
Tested on:

Return focus to the workspace

---

core/block_svg.js
core/insertion_marker_manager.js
core/renderers/common/path_object.js
core/renderers/common/renderer.js
core/renderers/zelos/path_object.js
core/renderers/zelos/renderer.js

Highlight input shape in zelos.
Highlight input shape on drag in Zelos.
Add a method on the block and the renderer that determines whether or not to insert a dragged block into a stack. We could consider moving these into an object that defines how the insertion marker does its work if we get more of these.
Tested on:

Highlight input shape in Zelos

---

core/flyout_base.js
core/renderers/zelos/path_object.js

Fixes flickering in zelos selection highlight. 
The zelos highlight uses two elements, the path object and the selected path object, mouse moves in between them trigger a mousemove event. Instead use ``mouseenter`` / ``mouseleave`` which is agnostic of moves inside of the root element. 
[This](https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseenter_mouseover) is a good demonstration of the difference between the two events.
Fix zelos flyout selection highlight.
Tested on:

Fix flickering in zelos selection highlight.

---

core/css.js
core/dropdowndiv.js
core/renderers/common/renderer.js
core/renderers/zelos/renderer.js
core/widgetdiv.js
tests/mocha/field_textinput_test.js

Add theme and renderer classnames onto the widget and dropdown div when the container is shown and remove when it is hidden.
Fixed some types.
Customize widgetdiv / dropdown based on theme / renderer.
Tested on:

Add theme and renderer classnames onto the widget and dropdown div.

---

core/css.js
core/renderers/common/renderer.js
core/renderers/minimalist/renderer.js
core/renderers/zelos/constants.js
core/renderers/zelos/renderer.js

Move blocklyReplaceable CSS into the common renderer.
Bring back hover stroke for zelos renderer.
Rendering.
Tested geras and zelos renderer in playground.
Tested on:

Move more CSS into renderers.

---

core/block_svg.js
core/field_colour.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

Full colour fields.
Add support in field_colour for full colour fields. Add constants option set in the renderer to determine whether to add a border Rect or whether to use the source block's svgPath to set the current colour value.
Tested on:

[zelos] Full field colour

---

core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Statement inputs have minimum widths in zelos.
Add min width constants to statement input before / after spacers.
Add row spacing before computing bounds.
Tested on:

[zelos] Statement inputs minimum widths.

---

core/css.js
core/dropdowndiv.js
core/theme/dark.js
core/theme_manager.js
tests/mocha/theme_test.js

Support setting the dropdown theme default colours through CSS.
Update dark theme to adjust dropdown and widget div colours. 
Multiple themes in playground.
Tested on:

Support adjusting dropdowndiv default colours through CSS

---

core/css.js
core/field_dropdown.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js
core/renderers/zelos/renderer.js

Set dropdown div colour to match block colour
Add a constant for whether or not to colour a dropdown div to match the block's colour. Call ``setColour`` in dropdown field if so. Update CSS to an inverted colour in zelos.
Tested on:

[zelos] Set dropdown div colour to match block colour

---

core/block_svg.js
core/field.js
core/field_colour.js
core/field_textinput.js

https://github.com/google/blockly/commit/2a8e7d9ac8ba31ef9111ec2f576d678df485ddd9 introduced a couple of bugs: 
- Clicking on a zelos colour field throws an exception
- Opening a mutator dialog doesn't colour the blocks inside the mutator.
Always apply colour. Check if field is rendered before applying colour in a field. Move getScaledBbox calculation into field.js
Fix rendering bugs.
Tested on:

Fix bugs with apply colour

---

core/css.js
core/warning.js

#3386 
This PR adds a mouse down event handler for the warning text elements.
This fixes the bug in #3386 
Tested on:
Desktop Chrome
Desktop Safari
No new documentation is required
This logic is very similar to handling mouse down events for dragging in the Bubble Class.
Functionality after the code changes:

Bug Fix - Issue #3386 - Warning Bubble Dragging

---

core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Minor adjustments to the zelos spacing constants: 
- min width
- statement input min width
Add a small padding after top row and before bottom row in some situations to make it so the top and bottom rows are identical in height and the block content is centered vertically.
Before: 
After:
Tested in zelos rendering playground.
Tested on:

Adjust zelos spacing constants

---

core/field_textinput.js

Check border Rect first.
Tested zelos in playground.
Tested on:

Fix the text input field colouring in full block fields.

---

core/renderers/common/constants.js
core/renderers/common/debugger.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/path_object.js

Reduce the amount of implicit spacing added by the connection shape by adding negative spacing to the first and last spacer in an output block.
Tested zelos rendering playground blocks.
Tested on:

Zelos horizontal tight nesting.

---

core/workspace_comment.js
core/workspace_comment_render_svg.js
core/workspace_comment_svg.js

This PR adds the option to set the workspace comment readonly.
requested in #1476 
Tested on:
Desktop Chrome
Desktop Opera
Windows Edge
* Smartphone:
* Device: iPhone 7 Plus
* OS: iOS 13.1.3
* Browser: Safari
* Version 13
Documentation has to be updated in the following since this is a new feature:
https://developers.google.com/blockly/reference/js/Blockly.WorkspaceComment
https://developers.google.com/blockly/reference/js/Blockly.WorkspaceCommentSvg

added readOnly property to workspaceComment

---

core/renderers/common/debugger.js

Render negative elem spacing in debugger.
Tested on:

Render negative elem spacing in debugger.

---

core/field_textinput.js

Fixes blocks that have a text input field and only label fields.
Count all fields when deciding whether or not a full text field should be used.
@rachel-fenichel any idea why we weren't including label fields?
Before: 
After: 
Tested test blocks playground.
Tested on:

Fix full text input fields with label fields

---

core/renderers/common/debugger.js
core/renderers/zelos/info.js

Fixes https://github.com/google/blockly/issues/3495
Reduce the vertical spacing for spacers before and after an input row if it contains non-shadow connected blocks.
Added debugger support for displaying negatively spaced row spacers.
Zelos rendering
Tested in zelos playground.
Tested on:

[zelos] Vertical tight nesting

---

core/field_checkbox.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

Override zelos field constants for the checkbox field. Make the checkbox field width a constants.
Tested on:

[zelos rendering] Checkbox field constants

---

core/renderers/common/constants.js
core/renderers/common/renderer.js
core/renderers/zelos/constants.js
core/renderers/zelos/path_object.js
core/workspace_svg.js
tests/scripts/selenium-config.js

Fixes issue with setting the outline path when the parent block is disabled. 
Cleanup and a more reasonable place to inject CSS.
Inject constants CSS in workspace createDom instead. Use a random identifier to pre-emptively set css that disabled the outline path based on the disabled pattern id. 
Cleanup / bug fix.
Tested on:

Inject constants CSS in createDom

---

core/renderers/zelos/info.js
core/renderers/zelos/path_object.js

Limit vertical tight nesting to blocks with a certain height: 
Tight nesting:
No tight nesting:
Also, re-add code to apply colour on input outlines, as the theme changes.
Tested zelos in playground.
Tested on:

[zelos] Limit vertical tightnesting

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/thrasos/info.js
core/renderers/zelos/info.js
tests/blocks/test_blocks.js

Fixes https://github.com/google/blockly/issues/3361
Rather than it just being in geras and thrasos. Make alignment common to all renderers.
Tested geras and zelos in playground (with test blocks).
Tested on:

Make alignment common renderer behaviour

---

demos/code/code.js
demos/code/index.html
demos/code/style.css

- (Mostly)
https://github.com/google/blockly/issues/1479
When the width of the page goes below a certain threshold, the multiple language tabs collapse into a single tab with a dropdown menu. This allows the page to shrink more in width without the rightmost buttons going off-screen.
Screenshots taken on iPhone 8:
Fig 1: the second tab is selected, with Dart as the chosen language.
Fig 2: the Blocks tab is selected.
To switch to another language, either select another language in the drop-down, or click on the other part of the second tab.
To make the demo fit better on screens that are not as wide.
Only manual testing.
Tested on:
* Smartphone:
* Device: iPhone 8
* OS: iOS 13.1.3
* Browser: stock browser (Safari)
No updates needed. This PR just changes …

Allow code demo to shrink more

---

core/utils/colour.js

Pulls https://github.com/microsoft/pxt-blockly/pull/255. (Sorry for resubmitting, I messed something up in the other one!)
Allows Blockly.utils.colour.parse to handle "0xffffff" hex formatting. Calls "parse" in the hexToRgb to handle cases of "#fff", "0xfff" etc.
Additional flexibility in defining colors.
Modified the classic theme with color values of "0x######" format, ran it in 
Tested on:
Desktop Chrome
Windows Internet Explorer 11
Windows Edge
I updated the function description to include the supported format.

Handle 0x hex values in color parsing

---

core/field_variable.js
core/mutator.js

Closes #3458 
1) Changes the mutator to no longer "disable" rendering.
2) Changes the variable field to call doValueUpdate_ directly instead of calling setValue.
So the problem wasn't exactly what I thought it was. The problem was that mutators set the block's `rendered` [property to false](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/mutator.js#L351), which meant the [fields were not getting initialized](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/input.js#L116) when they were appended. Then mutator would then [call initSvg](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/mutator.js#L357), which would eventually call the variable field's initMethod, which would force a …

Fixed adding a variable field programmatically when it has a following field.

---

core/renderers/common/constants.js
core/renderers/measurables/inputs.js
core/renderers/zelos/constants.js

Add additional offset to the statement input in zelos to account for the right corner width.
Tested in developer tools.
Tested on:

[zelos] Add extra offset for statement input to account for right corner width

---

core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Cleanup.
Spacer rows already have a followStatement property. Add a precedesStatement property and use that to draw the right corner before / after a statement input instead.
Remove before / after statement spacer row measurables and cleanup measurement of height / width.
Zelos rendering / cleanup
Tested in zelos rendering playground.
Tested on:

Remove BEFORE/AFTER statement input spacer measurable

---

core/keyboard_nav/basic_cursor.js
core/keyboard_nav/key_map.js
core/keyboard_nav/navigation.js

Add ability to move around the workspace in keyboard navigation mode.
shift + wasd keys will move a user around the workspace.
If a user hits shift + wasd when on a block or field nothing will happen. 
Not being able to move around the workspace is no fun.
Tested on:

Ws cursor move

---

core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/zelos/constants.js

Use GRID_UNIT for all constants.
Zelos has different minimum height for dummy inputs whether they're in a shadow block or not. 
Update zelos constants to use GRID UNIT.
Zelos has different minimum height for dummy inputs whether they're in a shadow block or not. Add new constant for shadow dummy min height.
Tested on:

[zelos] Update constants to use grid unit, add dummy shadow min height

---

core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Statement input left side text shouldn't move up/down as the statement stack changes.
Make statement inputs in zelos use the top row centreline.
Tested in zelos playground.
Tested on:

[zelos] Statement input centreline

---

gulpfile.js

https://github.com/google/blockly/issues/3518
Fix gulp compile build of blocks, by ensuring all added provides are included in the remove regex.
Fix gulp build.
Tested demos and playground with both uncompressed and compressed builds.
Tested on:

Fix gulp blocks compile build

---

core/renderers/common/constants.js
core/renderers/zelos/constants.js

Jagged teeth not using the constants provided.
Zelos doesn't use jagged teeth.
Update jagged teeth code to use height / width constants.
Remove use in zelos.
Tested on:

[zelos] Jagged teeth

---

core/renderers/common/drawer.js
core/renderers/measurables/connections.js
core/renderers/measurables/inputs.js
core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Zelos connection is currently positioned in the top left corner. Because the connection shape is circular / triangular, this is positioned off the block.  
Position the connection point to the left and center of the block: 
Added methods on the shape for the shape developer to decide where to position it. 
@rachel-fenichel just a thought, but maybe we should make all shapes dynamic and simplify the code, in the cases where the height / width are static they would just return the static height / width not taking into account the block height that's passed in.
Tested RTL.
Tested on:

[zelos] Output connection position

---

core/field_dropdown.js

Fix dropdown field alignment in zelos when baseline is not centered and the border rect height is greater than the text height. (in IE / Edge). 
Fix is to only take into account text height when calculating dy.
Fixes in IE / Edge:
Tested in playground in Edge / IE and on Chrome with no baseline center in zelos.
Tested on:

Fix dropdown field alignment in zelos in IE / Edge

---

core/block.js
core/mutator.js
core/workspace.js
core/workspace_svg.js
tests/mocha/gesture_test.js

Fixes #3507.
1. We recently removed the cursor and marker from a workspace so removed references to keyboardAccessibilityMode.
2. Use Blockly.getMainWorkspace().keyboardAccessibilityMode instead of the mutators workspace since the mutators workspace doesn't get updated when keyboardAccessibilityMode is toggled on and off for the main workspace.
3. Move the check for moving the cursor to after we re-render the block. Re rendering the block creates new inputs which causes the cursors reference to the input to no longer exists and we get an error.
Tested on:

Fix moving cursor when block mutates

---

core/dropdowndiv.js
core/field.js

Fixes https://github.com/google/blockly/issues/3532
Take into account page scroll with field scaled bbox calculation.
Fix scrolled text input widgetdiv positioning.
Tested playground and multi playground.
Tested on:

Fix scrolled text input widgetdiv positioning.

---

core/gesture.js
tests/mocha/gesture_test.js

Fixes #3412
Shift click no longer puts a user into keyboard accessibility mode. A user can still shift click to move around the workspace once they are in keyboard accessibility mode.
Tested on:

Removes ability to enter accessibility mode using shift click

---

core/renderers/zelos/info.js

Instead of only applying the bump X logic (for bumping inputs past the notch horizontally), apply this logic for every row that has a notch before it and after it (with the exception of the first row where we always apply the bump).
When bumping horizontally, unless we're bumping the first row, use the prev statement row's left width to determine the full extent to which to bump the next row, ie: making sure we always bump past the notch on every row.
We use this same logic to determine whether we should tightly nest vertically.
Add small padding after a notch so the notch doesn't clash with inputs / fields.
Tested in zelos rendering playground.
Tested on:

[zelos] Bump / tight nest for all rows that are preceded and followed by a notch

---

core/renderers/zelos/info.js

Deal with the case where we have two dummy inputs on the same row, one with left alignment and the other with right.
Zelos rendering specific fix. We keep track of the right aligned dummy input and add the missing space when adding alignment padding.
Tested with pxt-blockly's controls_if block.
Tested on:

[zelos] Left/right aligned dummy inputs

---

tests/compile/compile.sh

Apparently 'PRUNE' is the new option, but it's undocumented.  More info:
https://github.com/google/blockly-games/issues/176

STRICT is no longer supported by Closure Compiler

---

core/renderers/zelos/info.js

We were adding an additional padding between the top row and the input row of the breakout loop block.
Only apply small padding after notch if we have a statement input.
Zelos rendering fixes.
Tested the breakout loop block in the playground. 
Tested on:

[zelos] Fix breakout loop block

---

core/renderers/zelos/info.js

Reduce an empty row surrounded by statement inputs to match size of bottom row.
Tested in playground with controls_if block.
Tested on:

[zelos] adjust height of sand-witched empty row

---

core/css.js
core/dropdowndiv.js

Fixes https://github.com/google/blockly/issues/3083
Rename arrowTop and arrowBottom css classes to blocklyArrowTop and bllocklyArrowBottom.
Tested playground
Tested on:

Fix non-prefixed CSS

---

core/block_svg.js
core/bubble.js
core/workspace_svg.js

Part of #3142
Replaces usages of MIN_BLOCK_Y from BlockSvg with MIN_BLOCK_HEIGHT from constants.
Rendering constants is source of truth for minimum block height.

Removing leftover constant MIN_BLOCK_Y in BlockSvg.

---

core/flyout_horizontal.js

Fixes https://github.com/google/blockly/issues/3550
Use positive BIG_NUM for bottom range of the deletion rectangle, so block's are included in delete areas of simple toolboxes that are bottom positioned.
Fix bug.
Tested in playground and multi_playground.
Tested on:

Fix bottom horizontal flyout delete areas

---

core/renderers/zelos/drawer.js
core/renderers/zelos/info.js

Single field vertical tight nesting adjustment for text/image single fields: 
Tested in rendering playground with the pxt-blockly control_if block and if_else block.
Tested on:

[zelos] single field text/image tight nesting

---

blocks/procedures.js
core/mutator.js
core/procedures.js
core/variable_map.js
core/variables.js
core/workspace.js
core/workspace_svg.js
tests/mocha/procedures_test.js

N/A
Changes the prevent-duplicate-args behavior so that instead of updating the arg when the block is placed, the flyout is updated instead.
I also changed it so that it starts at whatever character you want, instead of always at 'i'.
New behavior:
Old behavior:
... Mostly I was just bored hehe. But I do think there are a couple of nice things about the new behavior.
* The arg value changes in the flyout. This makes the behavior more clear.
* The args go in alphabetical order, instead of jumping to i. I think that's more pleasant.
* In the second behavior gif, I drag out the second arg and its value turns to "j" instead of "i". The new behavior fixes that, which I think is nice.
I don't think this really needs unit tests. It's basically just two event listeners and a unique string …

feat: Improved procedure arg interaction.

---

core/block.js
core/renderers/zelos/constants.js

Fixes https://github.com/google/blockly/issues/3414
Add ouput shape property on a block and parse from json.
Add implementation for a square shape in zelos. 
Use a block's output shape if one exists when deciding on what shape to use.
Zelos rendering. 
Tested with pxt-blockly blocks in zelos rendering playground.
Tested on:

Add output shape on a block. Add squared shape.

---

core/widgetdiv.js

Fixes https://github.com/google/blockly/issues/1327
Remove workaround for Firefox as: 
- Fix was over 4 years ago
- No longer repro original issue on dropdowns
- Aside from the context menu, dropdown fields have moved to the dropdown div.
Code cleanup / performance.
Tested on Chrome and Firefox on Mac.
Both RTL and LTR modes.
Tested on:

Remove Firefox workaround for widgetdiv positioning

---

core/renderers/common/info.js
core/renderers/geras/info.js
core/renderers/thrasos/info.js

Fixes https://github.com/google/blockly/issues/3176
Include the connected block width when computing the width with connected blocks of a value to stack block.
Bug fix.
Tested with a value to stack block: 
Tested in geras, minimalist and thrasos renderers. Zelos doesn't support value to stack blocks.
Tested on:

Fix value to stack width measurement

---

core/block_svg.js
core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/measurables/rows.js

Part of #3142
Moves START_HAT constant into rendering ConstantProvider and renames it to ADD_START_HATS to resolve conflict of pre-existing constant START_HAT (that defines start hat path).
START_HAT constant was leftover UI constant from block_render_svg.

Move of render contant START_HAT into ConstantProvider.

---

core/renderers/zelos/drawer.js
core/renderers/zelos/info.js

Fix bug in zelos tight nesting code causing this:
Tested all if statement blocks, both blockly's and pxt-blockly's.
Tested on:

[zelos] Fix bug in tight nesting

---

core/components/menu/menu.js
core/field.js
core/field_angle.js
core/field_dropdown.js
core/field_textinput.js
core/gesture.js

Fixes https://github.com/google/blockly/issues/3567
Prevent a dropdown field's menu from propagating a click event immediately to a menuitem when it first opens (if the menu is positioned above the field).
We do this by keeping around a cache of the opening event coordinates. If the click event is handled that is within 1 pixel distance to the opening event then we ignore it and reset the cached coordinates.
Bug fix.
Tested playground on Chrome with mobile tools.
Tested on:

Fix bug with dropdown menu propagating the opening click event to a menu item

---

core/renderers/common/debugger.js
core/renderers/common/drawer.js
core/renderers/geras/drawer.js
core/renderers/measurables/inputs.js

Fixes https://github.com/google/blockly/issues/3186
Rename references to an input measurable's connection property to connectionModel and remove that property.
Cleanup.
Tested on:

Rename input connection to connectionModel

---

core/rendered_connection.js
core/renderers/common/marker_svg.js

Part of #3522
Replaces references directly to `PUZZLE_TAB` and `NOTCH` for paths to use the shape returned from call of `ConstantProvider.shapeFor`.
Using the return of shapeFor ensures that the correct path is used and is particularly important for extensions of the renderer.

Using shapeFor for notch and tab paths.

---

core/renderers/common/marker_svg.js

Part of #3522
Cast connections in `MarkerSvg` to `Blockly.RenderedConnection` and use `shapeFor` to determine the correct path for input.
Renderers may change the path of the input based on the connection so using `PUZZLE_TAB` directly instead of `shapeFor` does not guarantee the correct path.

Using shapeFor to determine connections shape for marker_svg.

---

core/renderers/common/debugger.js
core/renderers/common/info.js
core/renderers/geras/info.js

Detect undefined elements in the debugger.
Don't add multiple spacers when there are no elements in a row (only one for alignment)
Rendering.
Tested with an empty dummy input.
Tested on:

Detect undefined elements in the debugger

---

core/renderers/geras/info.js

Treat the space before a statement input as the end of a statement input row reducing the spacing of an editable field to match spec: 
Geras rendering.
Tested with the blocks factory.
Tested on:

Treat a statement input as the end of the statement row.

---

core/block_svg.js

Fixes #3510
Added call to re-render block in `setMutator`.
Blocks were not re-rendering as expected after `setMutator` call.
Tested on:
Tested change by:
1) Loading the following XML to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml">
<block type="logic_compare" id="2n20(|Q%A^}6]Z-V`}5w" x="63" y="38">
<field name="OP">EQ</field>
</block>
<block type="math_number" id="iTHDI?u7Ojrv{`iCKf][" x="188" y="38">
<field name="NUM">123</field>
</block>
</xml>
```
2. Running the following code in the console:
```
blocks = workspace.getBlocksByType('logic_compare');
for (var i = 0, block; block = blocks[i]; i++) {
block.setMutator(new Blockly.Mutator(['logic_negate']))
}
```
3. Observing how the logic_compare block is correctly re-rendered and the …

Re-rendering block in setMutator.

---

core/renderers/zelos/info.js

Zelos statement input centerline alignment currently centers spacers but they shouldn't. This fixes that.
Tested on:

[zelos] Bug fix in centerline alignment of statement inputs

---

core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/geras/constants.js
core/renderers/geras/drawer.js
core/renderers/geras/highlighter.js
core/renderers/geras/info.js
core/renderers/measurables/types.js
core/renderers/zelos/info.js

Fixes #3367
Add hook for getting desired width of a row.
Move MAX_BOTTOM_ROW constants to geras as it only applies there.
Don't take row alignment into account if inline.
Override alignRowElements_ in geras to align all rows (top, bottom, spacer) to the width of the max of the prev / next input.
Geras rendering fix.
Tested a bunch of blocks in the blocks factory matching spec of the old renderer.
Tested on:

Geras inline alignment of rows + max bottom row width

---

tests/playgrounds/screenshot.js
tests/rendering/zelos/pxtblockly/index.html
tests/rendering/zelos/pxtblockly/pxtblockly.html
tests/rendering/zelos/pxtblockly/zelos.html
tests/rendering/zelos/scratchblocks/index.html
tests/rendering/zelos/scratchblocks/scratchblocks.html
tests/rendering/zelos/scratchblocks/zelos.html

Zelos rendering playgrounds for testing.
Add two new zelos rendering playgrounds for the blocks defined in pxt-blockly and scratch-blocks.
Update constants were relevant for each specific fork.
Zelos rendering testing.
More test coverage of zelos rendering by adding playgrounds for the blocks defined in pxt-blockly and scratch-blocks.
Tested on:

Zelos rendering playgrounds

---

core/renderers/common/constants.js
core/renderers/zelos/constants.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Override start hat constants in zelos to rendering of: 
Tested in rendering playground.
Tested on:

Start hat support in zelos.

---

core/renderers/zelos/info.js

Simplify zelos tight nesting logic. Only check for non-shadow connected blocks if we have both a prev and next notch.
Make the single field check take precedence.
Zelos rendering playground.
Tested on:

Simplify zelos tight nesting logic

---

core/renderers/zelos/info.js

Fix zelos top spacer height when the top row precedes a statement row.
Give preference to the followsStatement check before checking if the prev row is a top row and applying the top row check.
Tested in playground with new connection test blocks.
Tested on:

Fix zelos top row spacer height when it precedes a statement row.

---

tests/blocks/test_blocks.js
tests/playground.html

Cleanup. 
Remove connection tests blocks handlers introduced in https://github.com/google/blockly/pull/3525 out of the playground and into the test_blocks.js file. 
Add jsdoc for handlers, and align properly.
Cleanup, keep playground lean.
Tested on:

Cleanup connection test blocks in playground

---

core/insertion_marker_manager.js

Fixes #3589
Move set collapse to after we have added any block mutations.
When we had setCollapsed after domToMutation, domToMutation was overriding some of the inputs that were created in setCollapsed. 
Tested on:

Moves setCollapsed to after mutation

---

tests/blocks/test_blocks.js

IE 11 doesn't allow the same property to be set on an object twice in strict mode.
Fix testing in IE11
Tested in IE11
Tested on:

Fix testblocks in IE11

---

core/variable_map.js

Fixes https://github.com/google/blockly/issues/3593
getVariableTypes wasn't returning a set but instead was concatenating the types returned from the variable model's map and the potential variable model map.
Instead, return a set of the two objects merged together.
Bug fix.
Tested with the mirror demo.
Tested on:

Fix duplicate variable model type

---

core/field_dropdown.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

Add constants for field dropdown arrow padding for more control over where the arrow shows up, and so that the padding between the text and the arrow isn't necessarily the same as the padding on the edges (which is the case for scratch-blocks).
Tested in rendering playground: 
8 px padding around edges, 8px padding between text and arrow (pxtblockly):
11 px padding around edges, 8px padding between text and arrow (scratch-blocks):
Tested on:

Add constant for field dropdown arrow padding

---

core/xml.js

Fixes https://github.com/google/blockly/issues/3174
Use setAttribute instead of block.id for setting the block's id as IE11 doesn't serialize the id otherwise. 
The bug linked is one of the side effects of this bug, but another side effect is if you export a workspace to XML, no id's are present in IE11.
Bug fix.
Tested in Chrome and IE11.
Tested on:

Fix IE11 serializing block ids

---

core/field_dropdown.js

Fixes https://github.com/google/blockly/issues/3553
Reference selected option instead of selected index in field dropdown so re-names in the underlying model are reflected in the field.
Bug fix.
Tested with sample block in bug. 
Tested on:
@mattbishop thoughts?

Use selectedOption instead of selectedIndex in field dropdown

---

core/xml.js

Fixes https://github.com/google/blockly/issues/3408
Fix positioning of blocks when appending blocks to the workspace with ``Blockly.Xml.appendDomToWorkspace`` in RTL mode.
Bug fix.
Tested with test blocks in the playground in both LTR and RTL mode.
Tested on:

Fix RTL appendDomToWorkspace positioning.

---

core/renderers/common/drawer.js
core/renderers/geras/drawer.js

#3288
Use baseline for positioning rendered next connection.
Previous connection is hard set to always be the top of the block, so for consistency, the next connection is at baseline (this does not change the positioning in any of the current renderers).
Tested in playground with all renderers.
Tested on:

Use baseline for positioning rendered connection.

---

core/inject.js
core/mutator.js
core/options.js
core/toolbox.js
core/trashcan.js
core/workspace.js
core/workspace_svg.js
tests/mocha/procedures_test.js
tests/mocha/xml_test.js

#3459
Uses default `Blockly.Options` if it is not provided to the Workspace constructor.
Before this change, the options set for workspaces through the constructor vs inject when no options were provided were different. This especially caused confusion for the option for oneBasedIndexing which can result in different code being generated.
Compared code generation between headless and non-headless workspaces without parameters provided.
Tested on:

Setting default options in workspace constructor.

---

core/mutator.js
core/options.js
core/toolbox.js
core/trashcan.js
core/workspace_svg.js

Fixes https://github.com/google/blockly/issues/3614
Workspace options were moved to all pass through the Blockly.Options parser. This means that we have to update the options sent to reflect the differences in the property names.
There's a number of side effects to this issue, RTL, mutators, etc.
This also fixes issues with Advanced compilation where the options object properties are renamed if not fully qualified.
Bug fix.
Tested on:

Fix parsing and passing of workspace options around Blockly

---

demos/custom-fields/pitch/field_pitch.js
demos/custom-fields/turtle/field_turtle.js

Turtle and pitch custom fields demo were both broken because they still had references to getColourBorder.
Problem was reported here: #3621
Remove getColourBorder in favor of style.getColourTertiary.
Tested on:

Fix broken field demos

---

core/block_svg.js

getColourBorder is used in a lot of fields. In an attempt to not break people we don't need to we are adding back the method and deprecating it. Also adding back helper methods for getting the different colours.
Original issue reported here: #3621
Added back the methods and removed some unnecessary checks if the colours don't exist since they should all be going through validatedBlockStyle_ which makes sure primary, secondary, and tertiary all have colours. 
Tested on:
Not sure if we also wanted to deprecate the getColourSecondary, getColourTertiary and getColourShadow ?

Add colour methods back to blockSvg

---

typings/parts/blockly-interfaces.d.ts

Add renderer to the blockly options in our typings.
Typings update.
Tested on:

Add renderer into typings options

---

core/renderers/zelos/constants.js
core/renderers/zelos/path_object.js

Rename highlight filter to selected filter as it more accurately describes what it is.
Cleanup. 
Tested on:

Zelos rename highlightfilter

---

core/field_dropdown.js

Fixes https://github.com/google/blockly/issues/3628
Fix logic for positioning an arrow in RTL when there is no border rect.
Rendering bug fix.
Tested in playground with the variable getter block.
Tested on:

[zelos] Fix rtl placement of arrow in non-borderbox dropdown fields

---

core/field_textinput.js

Revert on blur for text input fields as it interferes with combo boxes. Any field that uses both a widgetdiv and a dropdown div would have trouble with this blur event as moving focus from the widget to the dropdown causes a blur and closes the editor. 
Tested on:

Revert on blur for text input fields

---

core/css.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

#3617
Moves css for cursor out of renderer.
Block text on draggable blocks should have the cursor style from the css rule `.blocklySvg text, .blocklyBlockDragSurface text` applied (and the css selector for blockText needs to be made less specific for that to happen).
Moving the css out is the closest to the previous behavior for css rules.

Updating css rules for blocklyText cursor

---

demos/custom-fields/turtle/field_turtle.js
demos/custom-fields/turtle/turtle.css

#3636
Rename `updateColour` to `applyColour`. Add check due to handle case for when `initSvg` is not called before `updateColour`. Update css for turtle demo.
It used to be the case that (the now named) `applyColour` would only be called if the block was renderered (and so `initSvg` would have been called), but that is no longer the case so a check needed to be added.
Additionally, the css selectors have changed after refactor of css into renderer to be more specific, so the css modifying the text color for the turtle demo needed to be made more specific so that they would override the renderer css.
Tested on:

Fixing custom fields turtle demo.

---

core/renderers/geras/info.js
core/renderers/measurables/row_elements.js
core/renderers/thrasos/info.js

#3632
Subsituting checks for isEditable for field EDITABLE property for determining element spacing.
Fields that can be editable like `TextInput` have property `isEditable = false` in `readonly`  and element spacing calculation uses the `isEditable` property, which causes a difference in padding depending on `readonly` state.
Opened all blocks in playground in geras and thasos.

Editable field spacing

---

core/field_image.js
tests/blocks/test_blocks.js
tests/playground.html

Add test block for field image with a click handler.
Testing.
Tested on:

Add test block for field image with a click handler

---

gulpfile.js

Remove scripts part of package.json when preparing drop for publishing to npm. Otherwise, the prepare part of the script will continue running even as we try and publish the package.
Tested on:

Update gulp task for package-json to remove scripts.

---

core/block.js
core/block_svg.js
core/insertion_marker_manager.js
core/renderers/common/i_path_object.js
core/renderers/common/path_object.js
core/renderers/common/renderer.js
core/renderers/zelos/path_object.js
core/renderers/zelos/renderer.js

Closes #2948 
* Changes insertion marker manager to explicitly ask which way a valid connection should be handled. Options include:
* Placing an insertion marker.
* Highlighting an Input.
* Giving a block a "faded" appearance.
* Renamed show preview and hide preview functions so that they're more clear.
* Fixed and simplfied decision logic so that markers are properly inserted into statement stacks.
* Reduces duplicate logic, and makes code more readable.
* Readability!
* No need to have extra logic. Bugs are bad.
It's really hard to know how to test these things, because it's hard to know what you touched, but I tried my best. I tested using the test blocks from #3525 
Blocks no longer disconnect:
Blocks can still be inserted:
Also works for C-statement blocks:
Row blocks work as …

fix: Fixed insertion preview logic. And fixed markers not handling typed statements.

---

core/components/menu/menu.js

Unhighlight current menu item when hovering over disabled menu items in a menu.
Match expected behaviour of a context menu.
Tested in playground's context menu which has disabled menu items.
Tested on:

Unhighlight current when hovering over disabled menu item

---

blocks/lists.js
blocks/text.js

Fixes https://github.com/google/blockly/issues/3662
In order to be consistent visually with geras, updating value inputs to align right for zelos.
Setting the alignment value inputs in geras has no effect.
Tested in playground with create text and create list block.
Tested on:

Update list and text create block to right align its value inputs

---

core/theme.js

Adds back setBlockStyle and setCategoryStyle and makes blockStyles and categoryStyles @package again. 
Makes blockStyles and categoryStyles @package again.
Tested on:

Add back setters for theme

---

core/renderers/common/info.js
core/renderers/zelos/constants.js
core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

Fixes https://github.com/google/blockly/issues/3684 and https://github.com/google/blockly/issues/3676
Set a maximum for the width of a dynamic connection shape, thus getting to a shape like this: 
and
For dealing with the statement input + output connection. We keep track if we have any statement inputs in our input rows, and only render the left side of the connection if that is the case, like so: 
Size of multi-line blocks with an output connection grows without a limit creating obnoxiously sized blocks.
Tested on:
As a side effect of this change, when blocks with output connections are deeply nested, at some point (after hitting the max width), the blocks don't visually align exactly. I think that's a fair side effect. 
Thoughts @rachel-fenichel?

[zelos] Set a maximum width for dynamic connection shapes.

---

core/renderers/zelos/constants.js
core/renderers/zelos/info.js

Make it clearer what the padding after the top row and before the bottom row is based on. Make it based on the top row's height (min height, corner height and notch). Making it so that there's always equal padding in the top / bottom. 
Allow adjusting the corner radius and notch height, and have everything adjust accordingly.
Tested in playground and rendering playground.
Tested on:

Zelos adjust top / bottom row padding based on

---

core/trashcan.js

Closes #3666 
First commit adds constants to the trashcan's animation. I've been wanting to do this for a while so I just tacked it onto this PR. If you guys don't like it I'm totally cool with removing it.
Second commit adds an emptyContents function and a contentsIsOpen function.
* emptyContents: Clears the trashcan's contents. Sets the lid's minOpenness to 0. And hides the flyout.
* contentsIsOpen: returns if the trashcan flyout is currently open.
I figured people might want to check if the flyout is open before emptying it.
1) I like constants.
2) Might be useful when you're creating an application that uses levels? And it adds a harmless bit of flexibility for developers.
1) Imported the following xml to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml"> …
```

Added empty trashcan function.

---

build.py

As both the python filename array and the Input_X indexing is 0 based, the `-1` operation is not needed.
fromFileArray in closure-compiler uses 0 based indexing. see:
https://github.com/google/closure-compiler/blob/09cca3b536923dfb86d4e2ea34c8ee97d3ab471c/src/com/google/javascript/jscomp/gwt/client/JsRunnerMain.java#L816
https://github.com/google/blockly/issues/3613

#3613 fixing off-by-one error on compiler errors

---

blocks/loops.js
core/block_svg.js

#2321 
Fixes the event filtering and grouping in the break block so that it doesn't break undo.
Also makes it so that update disabled is called only if the block is not inherently disabled.
Bugs are the worst.
This matches the current behavior, it's just called in a more centralized place now.
Tested on:
N/A
I like this much better than #3696 This may not fix the wider problem, but I think it's safer.

fix: Break breaking undo.

---

core/renderers/common/block_rendering.js

We are currently unable to do ``Blockly.blockRendering.register('test', Renderer);`` where Renderer is an ES6 class.
Remove wrapper class during initialization (which was only really there to make the compiler happy).
Make the renderer compatible with ES6 classes.
Tested on:

Support ES6 classes in renderer initialization

---

core/block.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js

https://github.com/google/blockly/pull/3685 introduced a bug where blocks with only output connections had right corners added to their elements resulting in an offset when centering the text of text fields: 
Only add a right corner if we don't have an output connection or if we do but we have a statement input to account for:
Rendering bug fix.
Tested on:

[zelos] Fix centered textinputs

---

core/renderers/geras/highlight_constants.js
core/renderers/geras/highlighter.js

#3700 
* Add height and width to geras jaggedTeeth constants object.
* Remove horizontal-line-to step.
* These being undefined causes NaN errors if/when they are accessed.
* This step was causing errors for blocks with output notches, and seems to be unneccessary.
Tested on:
N/A
N/A

Fix geras collapsed rendering incorrect in RTL

---

core/field_checkbox.js
tests/mocha/field_checkbox_test.js

N/A
Discovered this issue while testing #3698 and I decided to go ahead and fix it b/c it was small.
Makes it so that checkboxes properly re-render when their character is set by calling forceRerender()
Blocks should automatically re-render when ever they are modified.
Repeated steps and could not reproduce bug:
Tested on:
N/A
N/A

Fix checkbox field rerendering on setCheckChar

---

core/utils/dom.js

Fixes https://github.com/google/blockly/issues/3710
Use ``display:flex`` and align-items when computing the height and baseline of text (based on a specific font) rather than inline-block with vertical-align. 
Fix bug when user is using flex.
Tested on all major browsers with both display:block and display:flex
Tested on:
* Windows IE 11
@BeksOmega FYI

Use flex to compute measure font metrics

---

core/renderers/zelos/constants.js
core/theme/highcontrast.js

Configure selected and replacement glow size and colour in zelos from the theme.
Show how to pipe theme properties to renderer properties.
Tested in playground with high contrast theme.
Tested on:

Configure zelos selected glow properties in theme

---

core/workspace_comment_svg.js
core/workspace_svg.js
tests/playground.html

N/A
Adds a context menu option to the playground so that you can test workspace comments.
I was doing some testing with workspace comments earlier and I think it is handy to be able to create one through right-clicking instead of having to load xml.
This is for testing silly!
N/A
N/A

Add workspace comment context menu option to playground

---

core/widgetdiv.js

Checks if WidgetDiv is visible before hide logic.
This follows the pattern of `Blockly.DropDownDiv.hideWithoutAnimation` and prevents unnecessary side effect of marking focus on workspace in the case where the WidgetDiv didn't need to be hidden.

Check if WidgetDiv is visible before hide logic.

---

core/insertion_marker_manager.js

Fixes https://github.com/google/blockly/issues/3718
Set the inputs inline property of an insertion marker to the same as the source block.
Bug fix.
Tested on:

Insertion markers to adopt the inputsinline state of the source block

---

core/css.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

##The basics
Fixes https://github.com/google/blockly/issues/3657
More specific CSS in renderer.
Bug fix.
Tested on:

Fix warning text color.

---

core/options.js
core/theme.js
core/theme/dark.js
core/toolbox.js
core/utils/object.js
tests/themes/test_themes.js

Related to https://github.com/google/blockly/issues/3113
```
Blockly.Theme.defineTheme(name, {
'base': Blockly.Themes.Classic,
'blockStyles': ...,
'categoryStyles': ...,
'fontStyles': ...
});
```
Developers can call the factory themselves when defining a theme, before passing in the theme object to the workspace options. In addition, if a developer is authoring a theme in workspace options in JSON, we would pass those options to this factory instead of doing this.
The defineTheme method would read the base property if it exists, and complete a deep merge of the base theme object's properties with the properties passed into the method and return a new Blockly.Theme.
Removed Dark theme CSS, and got around the need to specify a hover color by using an rgba value instead of a specific colour. …

Support extending themes with a base theme property.

---

core/block_svg.js
core/field.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_multilineinput.js
core/field_textinput.js
core/field_variable.js
core/mutator.js
core/options.js
core/renderers/common/block_rendering.js
core/renderers/common/constants.js
core/renderers/common/path_object.js
core/renderers/common/renderer.js
core/renderers/geras/path_object.js
core/renderers/geras/renderer.js
core/renderers/zelos/constants.js
core/renderers/zelos/path_object.js
core/theme_manager.js
core/toolbox.js
core/trashcan.js
core/workspace_svg.js

Request on the forums and in https://github.com/google/blockly/issues/3653
The ability to pass in workspace options ``rendererOverrides``. 
The properties passed in are applied when a new renderer constants is created. Before initialization, the property bag is mixed in to override whichever properties the developers wants.
As part of this change also: 
- Renderers create a new constants provider instance when refreshing a theme
- Fields no longer keep a reference to the rendering constants, instead call into the workspace for that.
Allow developers to override rendering constants without the need to create a new renderer.
Tested on:

Support passing renderer overrides in options

---

core/block_svg.js
core/field.js
core/marker_manager.js
core/renderers/common/constants.js
core/renderers/common/marker_svg.js
core/renderers/common/path_object.js
core/renderers/zelos/marker_svg.js
core/theme.js
core/theme/dark.js
core/workspace_svg.js
tests/mocha/field_checkbox_test.js

https://github.com/google/blockly/issues/3113
Add an accessibilityStyle property bag in the theme that adjusts the respective properties in renderer constants when the theme is set.
Redraw the attached marker / cursor when a field / block / workspace is re-rendered.
Support theme configuration for accessibility marker / cursor colours. That's quite important if we're allowing developers to change the workspace background.
We weren't currently updating the a field when its size changed. Similarly we weren't updating a block's marker if it is re-rendered. 
Tested on:

Adjust marker and cursor colours from the theme

---

core/dropdowndiv.js
core/inject.js
core/renderers/common/constants.js
core/renderers/common/renderer.js
core/renderers/geras/renderer.js
core/renderers/zelos/constants.js
core/theme.js
core/theme_manager.js
core/widgetdiv.js
core/workspace_svg.js
tests/mocha/field_textinput_test.js

If we have multiple renderers with different themes, they begin to interfere with each other as all renderers of the same type share the CSS.
Making it so that each renderer/theme combo share CSS on the page, and no renderer disposes of the CSS when it is disposed (only clears reference to it). This is because we don't know if another workspace is making use of it.
Noticed in design meetings that multi workspaces with differing renderers / themes was broken.
Tested in multi playground.
Tested on:

Support multiple renderer / theme combos on the same page.

---

core/renderers/zelos/marker_svg.js

Position the zeros circle marker in the middle on top of the connection point.
Tested on:

Position zelos marker svg on top of connection point

---

core/block_svg.js

Move the workspace cursor if we're in keyboard nav mode and hit tab on a tabbable field.
It makes sense if we're moving focus to also move the main cursor.
Tested on:

Move cursor on tab if we're in keyboard nav mode.

---

core/renderers/common/info.js
core/renderers/zelos/info.js

Connected block bounds are incorrect for Zelos and minimalist renderers.
This causes all sorts of issues with keyboard nav markers and types of blocks that factor in a statement block's width (eg: value to statement blocks).
Fix right connection measurable width addition logic in Zelos. Revert finalize_ measurement of widthWithConnection to be consistent with other renderers. 
I also began setting the widthWithConnectedBlocks of the top and bottom row to be the same as the row's width so that the entire block width is taken into consideration when measuring widthWithConnectedBlocks.
Fix rendering.
Tested in playground with repeat and value to statement blocks.
Tested on:
Fixed:

Fix block connected bounds for Zelos and minimalist renderers.

---

tests/rendering/zelos/pxtblockly/zelos.html
tests/rendering/zelos/scratchblocks/zelos.html
tests/rendering/zelos/zelos.html

Keep our rendering playground up to date and have it use the new renderer overrides. 
Keep our tests up to date.
Tested on:

Update rendering playground to use rendererOverrides

---

core/renderers/zelos/drawer.js
core/renderers/zelos/info.js
core/renderers/zelos/measurables/rows.js
core/renderers/zelos/path_object.js

This is what it looks like today:
Similar to value to statement blocks, add checks to skip right side rendering of the block if we have an output connection + next statement.
Tested in playground with the value to stack block.
Tested on:

[Zelos] Value to stack block support

---

core/css.js
core/renderers/common/marker_svg.js

Fixes #3744
Add pointer-events none
Tested on:

Fix marker css

---

core/block_dragger.js
core/block_svg.js
core/connection.js
core/field.js
core/flyout_base.js
core/tooltip.js

2 memory leaks
Connection.js: 
Generally connections are disconnected in block_svg's dispose method before they are disposed (eg: dragging a block into the trash can). Only setting the shadowDom_ to null if its connected does not suffice, and leaves around detached elements.
Block_svg.js
A path object maintains a reference to a block's svgRoot. Not disposing of the path object leaves around detached nodes.
Performance.
Tested with the chrome memory tools.
Tested on:

Fix two memory leaks

---

core/workspace_svg.js

Running into the problem when calling registerToolboxCategoryCallback and registerButtonCallback where it was registering them for all workspaces. 
Move flyoutButtonCallbacks_ and toolboxCategoryCallbacks_ to the constructor instead of having them on the prototype.
Tested on:

Move registering objects to constructor

---

core/block_svg.js
core/constants.js
core/insertion_marker_manager.js
core/renderers/common/constants.js
core/renderers/geras/constants.js
core/renderers/zelos/constants.js
core/theme.js
core/theme/dark.js

https://github.com/google/blockly/issues/3113
Moving insertion marker colour and opacity from global constants, into a theme property.
Colours should live in theme.
Tested in playground and with dark theme.
Tested on:

Insertion marker properties in theme

---

core/dropdowndiv.js
core/tooltip.js
core/widgetdiv.js

Problem with calling Blockly.WidgetDiv.hide in ie11. 
It was setting the innerHtml of the child of the Blockly.WidgetDiv to null as well as the innerHtml for Blockly.WidgetDiv.
Changing to textContent = '';
Tested on:

Fix inner html

---

core/field_multilineinput.js
core/field_textinput.js
core/workspace_svg.js
tests/mocha/field_textinput_test.js

Fixes https://github.com/google/blockly/issues/3166
Fix the scale used by fields inside of the mutator dialog. Mutators should borrow their scale from their parent.
Bug fix.
Tested on:

Fix mutator field scale

---

generators/lua/lists.js
tests/generators/golden/generated.dart
tests/generators/golden/generated.js
tests/generators/golden/generated.lua
tests/generators/golden/generated.php
tests/generators/golden/generated.py
tests/generators/lists.xml

#3566
Fixes error in operator in 
Incorrect precedence resulted in cases where Blockly generated code with syntax errors.
Ran generator tests.

Fixing operator precedence in Lua and and adding test.

---

demos/plane/blocks.js
demos/plane/plane.js

#3639
Reduce unnecessary calls to update block field value by only updating when slider value changes and setting field label at init (rather than at Block.CREATE).
Row blocks were misaligned when dragged directly from the toolbox. Reducing calls and setting field value on init prevents this issue.
Filed bug #3773 to investigate further why there are issues with updating field value on trigger of Block.CREATE

Fix plane demo bug.

---

core/blockly.js
core/dropdowndiv.js
core/inject.js
core/tooltip.js
core/widgetdiv.js

Resolves https://github.com/google/blockly/issues/3758
Support a custom container element for the dropdowndiv, widgetdiv and tooltip.
Allow developers to change where these divs get placed.
Tested on:
@bartbutenaers
For full screen, you can support your scenario by: 
```
var blocklyArea = document.getElementById('blocklyArea');
Blockly.WidgetDiv.CONTAINER_ELEMENT = blocklyArea;
Blockly.DropDownDiv.CONTAINER_ELEMENT = blocklyArea;
Blockly.Tooltip.CONTAINER_ELEMENT = blocklyArea;
```
And just make sure you inject your workspace into ``blocklyArea``.
This makes sure everything ends up there, and then you can call ``fullscreen`` on the blockly area element.

Support a custom container element for the dropdowndiv, widgetdiv and tooltip.

---

core/flyout_button.js
core/renderers/common/constants.js
core/renderers/zelos/constants.js

Fixes https://github.com/google/blockly/issues/3778
Move flyout label css into the renderer and set the theme font options in CSS. 
This still allows users (in CSS) font properties they want to override, like so: 
https://github.com/google/blockly/blob/develop/tests/playground.html#L607
but it defaults to using the same properties as set on ``blocklyText``
Bug fix, expect theme font changes to be reflected in flyout labels (similar to flyout buttons). 
Tested on:

Move flyout label css into the renderer

---

core/field_colour.js

Fixes https://github.com/google/blockly/issues/3794
Check if headless.
Bug fix.
Tested on:

Fix field colour in headless

---

core/field.js
tests/blocks/test_blocks.js
tests/playground.html

N/A
Makes it so that setValue returns if the local validator disposes of the block.
1) Firing an event with a disposed block throws errors.
2) We might as well skip the rest of the rerendering and stuff because the block is dead.
I added a test validator block that disposes of the block when the text input is edited. With the changes events are now correctly not being fired.
Tested on:
Noup
Discovered while working on #3750

Fix setValue not handling block disposal

---

core/mutator.js

N/A
Anything that changes the shape of a block should be calling bumpNeighbors directly. For example:
* Append Input
* Add Comment
* Insert Field
* Etc
So this call is unnecessary. If this call /is/ making something bump that normally wouldn't, that should be treated as a bug, and the root should be made to call bumpNieghbours.
Tested on:
N/A

Remove mutator bump timeout

---

core/components/component.js
core/utils/dom.js
core/xml.js

Rename Node enum to NodeType to avoid conflict with type Node.
Make ``createSvgElement`` last parameter actually optional matching description.
Tested on:

Rename dom Node enum

---

core/block.js
core/block_svg.js
core/input.js
core/insertion_marker_manager.js
core/rendered_connection.js
tests/mocha/block_test.js
tests/mocha/run_mocha_tests_in_browser.js

#3784 
#1967 
Adds an extra rendering step to the rendering pipeline in the case that the block is collapsed. This step makes sure that the block is in a proper collapsed state before re-rendering the block.
I didn't add the crazy toString changes that I added to AppInventor. I figured toString can't be slower than code generation, and people are encouraged to generate code pretty much constantly, so readability is probably better than efficiency in this case. If you want me to move it over I definitely can though.
Currently if you edit a collapsed block it doesn't update.
None yet, but there will be.
Tested on:
Noppers
This hasn't been thoroughly tested yet, but I wanted to put up something so you guys could see how this looks in the latest version (instead of the …

Fix collapsed blocks not updating when modified

---

core/block_svg.js
core/blockly.js
core/interfaces/i_copyable.js
core/interfaces/i_deletable.js
core/interfaces/i_movable.js
core/interfaces/i_selectable.js
core/workspace_comment_svg.js
scripts/gulpfiles/typings.js

Add an interface for what a "Selectable" object is.
Right now Selectable and Copyable are the same thing, we could split them up but we don't really have much use for a selectable object that is not copyable.
Build passes.
Tested on:

Add Selectable interface

---

core/dropdowndiv.js
tests/blocks/test_blocks.js

Fixes https://github.com/google/blockly/issues/3834
Dropdown divs were using the tiny mutator workspace as their bounds. Use the root workspace as the bound instead.
Bug fix.
Added test dropdown in mutator block and tested in playground.
Tested on:

Fix bug with dropdown divs in mutator dialogs.

---

core/block.js
core/block_svg.js

Closes #3803 
Makes block.removeInput return a boolean (false if opt_quiet is set, instead of throwing an error or  doing nothing)
Currently if removeInput fails while opt_quiet is set, nothing happens so there is no way to tell if it succeeded.
I have it always return true if it succeeds because it's simpler, but I can change it to only return true if opt_quiet is set if you'd prefer.

Make block.removeInput return a boolean.

---

core/procedures.js

Closes #2579
Procedures.allProcedures only needs to check top-level blocks (instead of all blocks as it currently does) because procedures can only be top-level blocks. This should speed up allProcedures generation similar to Procedures.getDefinition

Procedures.allProcedures only searches top-level blocks

---

core/utils/object.js

Fixes dark theme having startHats = true
typeof null === "object", go figure..
Escape null when deep merging.
Bug fix.
Tested on:

Fix defineTheme startHats

---

tests/mocha/xml_test.js

Fixes #3819
Adds timeout to test case to call built in mocha done callback.
Cleans up console warning during test run.

Add wait for xml test case.

---

core/options.js

Use the theme name if it exists when defining a theme based on JSON.
Tested on:

Blockly options - Use the theme name if it exists

---

core/blockly.js

Unlike the other existing shortcuts, this should not also cover Command-y since the latter is used on Macs for opening the history tab.  Ctrl-y is exclusively a Windows/DOS shortcut.

Add Ctrl-y (redo) support.

---

core/generator.js
tests/mocha/index.html
tests/mocha/insertion_marker_test.js

#2322
#2646
Makes it so that code generation and serialization skip over insertion markers.
Supports real time code generation and real time serialization.
Tested generation & serialization for the following cases:
* Marker Surrounds
* Marker Enclosed
* Marker Enclosed and Surrounds
* Marker Prev
* Marker Next
* Marker Middle of Stack
* Marker On Output
* Marker On Input
* Marker Middle of Row
* Marker Detatched
I also check that this matches the pre-insertion marker generation.
Pre-Insertion Markers:
This Branch:
Tested on:
Nope, I checked and the docs still show the "old" method, so we should be good!
I went ahead and fixed both things but if you want me to remove the serialization fix that's cool!

Add ignoring insertion markers in code/xml gen

---

core/flyout_horizontal.js
core/flyout_vertical.js

Also hide the Dropdown div when the flyout is scrolled.
We do it for the widget div, looks weird to have a hanging dropdown div when the flyout is scrolled.
Tested on simple flyout, variable dropdown.
Tested on:

Hide DropdownDiv on flyout scroll

---

core/block_dragger.js
core/components/component.js
core/components/menu/menu.js
core/components/menu/menuitem.js
core/components/tree/basenode.js
core/components/tree/treecontrol.js
core/components/tree/treenode.js
core/contextmenu.js
core/css.js
core/dropdowndiv.js
core/field_dropdown.js
core/flyout_button.js
core/keyboard_nav/basic_cursor.js
core/keyboard_nav/marker.js
core/renderers/common/constants.js
core/renderers/common/info.js
core/renderers/geras/constants.js
core/renderers/geras/path_object.js
core/renderers/zelos/constants.js
core/theme.js
core/toolbox.js
core/workspace_audio.js
core/workspace_comment_svg.js

Bunch of changes relating to menus.  Highlights:
* Deleted a bunch of unused CSS rules and classes.
* Put the menu code on a diet, so it only supports features that we actually use.
* Improved menu UX with support for more keyboard navigation.
* Remove Component as a dependency of Menu/MenuItem.

Simplify Closure-sourced code for menus

---

scripts/gulpfiles/build_tasks.js

Fixes build issue of gulp build script on Windows, reported: 
https://groups.google.com/forum/#!topic/blockly/vkwHBjmIpFU
Escape the path separator for the regex. It's `\` on Windows, and that needs to be escaped to `\\`.
Fix build
Tested build on Windows.
Tested on:

Fix gulp build on Windows

---

tests/playground.html
tests/playgrounds/advanced_playground.html

Part of https://github.com/google/blockly/issues/3882
Create advanced playground:
- Use the @blockly/dev-tools package to import the debug renderer, simple toolbox, category toolbox, and gui controls.
- Remove lots of checkboxes and dropdowns in favor of gui controls.
- Modify airstrike to randomly select from all blocks instead of all blocks in the toolbox.
- Open to discussion
Update the standard playground:
- Remove various controls + logic:
- Debug renderer
- Renderer picker
- Theme picker
- Accessibility checkbox
Use published dev tools where possible.
Simplify standard playground while continuing to have a functional playground that works w/no internet access, installation, etc.
Opened both playgrounds and clicked around.
None
There's more that can be done. I'm tracking some ideas …

Create advanced playground; simplify basic playground

---

core/xml.js
tests/mocha/insertion_marker_test.js

Closes #2322 
Skips over insertion markers, returning the xml of the insertion marker's child instead. If the insertion marker has no children we return a DocumentFragment instead (as suggested by @NeilFraser ).
If the developer happens to serialize the workspace while the user is dragging we don't want insertion markers to be included in the xml.
Unit tests for all of the following:
* Marker Surrounds
* Marker Enclosed
* Marker Enclosed and Surrounds
* Marker Prev
* Marker Next
* Marker Middle of Stack
* Marker On Output
* Marker On Input
* Marker Middle of Row
* Marker Detatched
Noup
Hopefully the compiler likes this! :crossed_fingers:

Add ignoring insertion markers in xml gen

---

core/block.js
tests/mocha/block_test.js
tests/mocha/index.html
tests/mocha/workspace_test.js

Fixes https://github.com/google/blockly/issues/57
The block ``toString`` method which is what's shown to users when a block is collapsed doesn't allow users to tell the difference between the block configuration: 
Instead, now that we have a Blockly AST, we can go through and build up a block's textual representation by traversing the tree. In addition, we can add parentheses around `Number` and `Boolean` connections to make it clearer to user the order of precedence. 
The previous example turns into (when collapsed):
Finally, I run through the text array and remove any simple parentheses around single input blocks. eg: ``((10) * (50)) + (10)`` turns into ``(10 * 50) + 10``.
Fix ambiguity around order of precedence of collapsed blocks. 
Tested on:
turns into
turns …

Use the Blockly AST for block toString

---

tests/playgrounds/advanced_playground.html

Advanced playground options weren't being piped correctly. 
Fix advanced playground options passing.
Tested on:

Fix advanced playground options passing

---

core/block_svg.js
core/connection.js
core/flyout_base.js
core/interfaces/i_bounding_box.js
core/utils/toolbox.js
core/variable_map.js
core/variables.js
core/workspace.js
core/workspace_comment_svg.js
core/workspace_svg.js
scripts/gulpfiles/package_tasks.js
tests/blocks/test_blocks.js
tests/scripts/selenium-config.js

Add an interface describing a bounding box registered on the workspace.
Workspace comment (like) plugins need a way to register on a workspace that an object is present and the space (bounding rect) that it takes up.
Tested on:

Bounding Box interface

---

core/connection.js
core/input.js
core/xml.js
tests/mocha/connection_test.js

N/A
This PR allows developers to assign shadow blocks to connections/inputs programmatically.
This functionality is necessary if you want to assign shadow blocks based on the mutation of a block. For example: if you have a mutable addition block and you want to add a shadow to each input.
I also flipped through the toolbox, and everything seems fine!
Tested on:
None as far as I know.
This was actually really easy to add, which kind of scares me.
If anyone can think of other areas that need testing I'm happy to test.

Add programmatically setting shadows

---

core/block.js
core/field_dropdown.js
core/input.js

Strict types in input.js.
Added prefixField and suffixField properties to FieldDropdown 
Add rendered property to Blockly.Block and set to null such that:
- Blockly.Block, rendered = null
- Blockly.BlockSvg, rendered = false
- Blockly.BlockSvg (after render is called), rendered = true
Tested on:

Strict types in input

---

core/block_svg.js

- [ x ] I branched from develop
- [ x ] My pull request is against develop
- [ x ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
It resolves my problem, that I am facing now. If I call this code: https://github.com/ioBroker/ioBroker.javascript/blob/master/src/public/google-blockly/own/blocks_trigger.js#L418
in collapsed state, I could see a warning, but it is wrong.
This PR just fixes an error.
If some block tries to remove warning with `block.setWarningText(null, block.id)` in collapsed state, the warning will be shown anyway.
Tested on:
The change is so small and not depend on browser features relevant.
Not relevant

Do not add COLLAPSED_WARNINGS_WARNING by deleting of warning

---

core/block_svg.js
core/contextmenu.js
core/dropdowndiv.js
core/field.js
core/utils.js
core/widgetdiv.js

Cleanup 
Stricter typechecks in dropdown and widget div.
- Use Blockly.utils.Rect and Blockly.utils.Size instead of Object.
- Add Blockly.DropdownDiv.BlocksInfo and Blockly.DropDownDiv.PositionMetrics typedefs
Cleanup.
Ran build script.
Tested on:

Type fixes for Dropdown / Widget divs

---

core/block_svg.js
core/comment.js
core/connection.js
core/field_angle.js
core/field_colour.js
core/field_dropdown.js
core/field_textinput.js
core/field_variable.js
core/flyout_base.js
core/flyout_dragger.js
core/flyout_horizontal.js
core/flyout_vertical.js
core/icon.js
core/menuitem.js
core/mutator.js
core/toolbox.js
core/warning.js
core/workspace.js
core/workspace_drag_surface_svg.js
demos/custom-fields/pitch/field_pitch.js
scripts/gulpfiles/build_tasks.js
tests/mocha/workspace_test.js

Enables unusedPrivateMembers check
Remove unused private members
Fix up the use of private on members the override a property.
Make Blockly.Icon abstract
Tested on:

Enable unusedPrivateMembers check

---

core/flyout_base.js
core/utils/toolbox.js
tests/playgrounds/test_blocks_toolbox.js

Before if a user wanted to define a simple block in JSON they would need to specify the blockxml, which can be a bit of a pain. This will allow users to just give the type. 
Add ability to have a block with the following definition.
{
'kind':'block',
'type': 'type_name',
'disabled': 'true'
}
Makes it easier to add a simple block. 
Tested on:

Add ability to add blocks by type

---

core/toolbox.js

Reverts part of #3848 due to the bug #3936.
Will re open bug #3387
Going to save #3387 for when we rewrite the toolbox.
Tested on:

Revert not closing the flyout for a tree separator

---

core/workspace.js
tests/mocha/workspace_test.js

Fixes #3837
Distinguish between `maxInstance[type] = 0` and `maxInstance[type] = undefined` in `remainingCapacityOfType`.
This allows for setting maxInstance[type] to 0. Before this change, it would be treated as unset (and limit would be default be Infinity).
Also unskippped and removed TODOs in corresponding mocha tests.

Support maxInstance[type]=0 in remainingCapacityOfType

---

core/block_dragger.js
core/insertion_marker_manager.js

Fixes #3898
Update the available connections for the dragged block after it has been unplugged.
Tested on:
We can also go the route to only initialize insertion manager in startBlockDrag however the change is farther reaching since getInsertionMarker uses the draggedConnectionManager.

Update availble connections when we have unplugged a block

---

core/mutator.js
tests/blocks/test_blocks.js
tests/playgrounds/test_blocks_toolbox.js

Fixes https://github.com/google/blockly/issues/3955
Support showing the mutator UI for a single root block (with no flyout workspace).
Bug fix.
Tested mutator blocks (controls_if), and added a new block to test no-flyout mutators, the block sets the colour of the parent block using the mutator UI.
Tested on:
@mattbishop FYI

No flyout mutator

---

generators/dart/procedures.js
generators/javascript/procedures.js
generators/lua/procedures.js
generators/php/procedures.js
generators/python/procedures.js

Changes usages of private property `arguments_` in `procedures_defreturn` and `procedures_defnoreturn` generators to public `getVars` call.
Fixes https://github.com/google/blockly-samples/issues/301
Allows for more flexibility in custom implementation of procedure block by removing reference to internal variable.
Mocha tests and playground.
Tested on:

Use getter for variables in procedure generators.

---

blocks/procedures.js

Fixes test failure introduced by #3971
Adds getter to procedure call blocks (`getVars` just as procedure definitions have).
Adding this getter enables code outside of `blocks/procedures.js`, such as in generator code, to use a public method rather than accessing the private `arguments_` property directly.
Ran generator tests.

Adding getter to procedure call block for arguments_ property

---

core/flyout_base.js

Fixes https://github.com/google/blockly/issues/3977
Flyout setVisible calls needs to happen before blocks are created in `createFlyoutInfo_`.
Bug fix.
Tested in playground with multi-line test block
Tested on:

Fix multiline field not rendered in flyout

---

core/block.js
core/flyout_base.js
core/options.js
core/registry.js
core/toolbox.js
core/workspace_svg.js
tests/compile/compile.sh

Fixes for Advanced compilation.
- gridPattern can't be set to undefined if the type is !SVGElement
- Block.getVars used by procedures.js (can't be package, must be public)
- registryItem['fromJson'] is not found when the compiler aliases field methods.
Fix advanced compilation.
Tested with the advanced compilation script.
Tested on:

Advanced compilation fixes

---

package/node/core.js

Mocha tests in blockly-samples run multiple tests with the same global scope. 
On subsequent tries, Blockly's document object is not reset as the global.DOMParser object had already been set on the previous iteration.
This makes it the document is set every time.
Tested on:

Fix for mocha tests

---

core/toolbox.js

Fixes #3991
Adjust check for colour value from `=== null` to. `== null` to also catch on `undefined`.
Without this change, there are a lot of warnings when someone does not set the optional colour value for a category.
Tested on playground by checking Test Blocks (no colours on categories) and Categories (typed variables) (with colours for categories).
Tested on:

Handle undefined colour

---

generators/python/loops.js
tests/generators/golden/generated.py
tests/generators/variables.xml

Fixes #4000 
Fixes error in controls_for code generation when start, end, or increment is not a simple number.
This change produces valid python, where before the code generated had syntax error.
Updated golden file for generator and ran against python interpreter to see that all tests pass.
Manually tested on advanced playground with:
```
<xml xmlns="https://developers.google.com/blockly/xml">
<variables>
<variable>j</variable>
<variable>i</variable>
<variable>k</variable>
</variables>
<block type="variables_set">
<field name="VAR">j</field>
<value name="VALUE">
<block type="math_number">
<field name="NUM">0</field>
</block>
</value>
<next>
<block type="controls_for">
<field name="VAR">i</field>
<value name="FROM">
<shadow type="math_number">
<field name="NUM">1</field>
</shadow> …
```

Fix python loop

---

tests/scripts/check_metadata.sh

Update metadata of Blockly compressed and gzip'd sizes after the 3.20200625.1 release.
Tested on:

Update Blockly size metdata for the 3.20200625.1 release

---

core/menuitem.js

Fixes https://github.com/google/blockly/issues/4015
Handle cases where the content of the menu item is a HTML element.
Fix regression.
Tested with the test field dropdown image block.
Tested on:

Fix field dropdown with images

---

core/css.js
core/variables.js
core/workspace.js
core/workspace_svg.js

Code cleanup.
Delete the following functions:
- Blockly.Css.setCursor. Deprecated April 2017
- Blockly.Variables.allUsedVariables. Deprecated January 2018
- Blockly.Workspace.prototype.variableIndexOf. Deprecated April 2017
- Blockly.WorkspaceSvg.prototype.traceOn. Deprecated October 2016
All of these were deprecated a long time ago and had messages to that effect for multiple years. It's time to fully delete them.
I don't know of any documentation that references these.

Remove some old deprecated functions

---

core/zoom_controls.js

Emits a ui event when zoom control is clicked including old and new workspace scale.
Since clicking on zoom controls does not emit a workspace click event, it makes sense to emit some kind of event instead to describe what happened.
Playground
Tested on:
We may also want to update https://developers.google.com/blockly/guides/configure/web/events to include the new possible value for element (i.e. 'zoom').
This PR also does some refactoring cleanup of the mouseDown event handlers for clicking on zoom controls.

Emit UI event on zoom control clicks.

---

core/gesture.js
core/trashcan.js

#3975 
- Changes ui events emitted on workspace and on block click to both be 'click' and adding string in newValue to differentiate between what has been clicked.
- Stops event propagation on mouse down when trashcan is clicked (and has contents) to prevent workspace click from being emitted.
- Emits ui event when trashcan is opened (mouseUp) 
- Consistency in naming of events
- Clicking on trashcan is not expected to trigger a workspace click event
Playground
Tested on:
We may also want to update https://developers.google.com/blockly/guides/configure/web/events to include the new possible value for element (i.e. 'trashcan').
Any support for emitting an event on trashcan flyout closing will be addressed in future PR.

Update click event handling for workspace and trashcan.

---

core/zoom_controls.js

Adds missing cleanup in dispose for unbinding events.
Tested on:
Follow up from #4025

Unbind event handlers in dispose of zoom controls.

---

core/field_multilineinput.js
core/xml.js

A complex regular expression in `Blockly.Xml.domToText` was running on every save, causing performance problems on large projects. The regexp progressively replaces all `\n` with `&#10;` in content fields, and was added along with `FieldMultilineInput`, in #2663.
Override `toXml` and `fromXml` on `FieldMultilineInput` and do the conversion there. This simplifies the regexp, and it only runs when there is multiline content in the program, improving performance - especially on large programs.
Testing with this MakeCode Arcade game: https://arcade.makecode.com/74548-67333-76127-33508
Time spent in `Blockly.Xml.domToText`:
| Before | After |
| -- | -- |
| 10s | 250ms |
Resolves #4030
I tested this change in playground.html. Steps I followed:
1. Add a few paragraph blocks and populate them …

Perf: Move multiline xml text encoding out of domToText

---

blockly_uncompressed.js
core/block.js
core/block_svg.js
core/utils/deprecation.js

#4049 
Adds a deprecation warning helper to standardize our deprecation messages.
Standardization.
Checked in the advanced playground.
It would be nice to automatically know what function was being called, instead of typing it as a string.

Add deprecation helper + 2 uses

---

blockly_uncompressed.js
blocks/logic.js
core/block.js
core/connection.js
core/connection_checker.js
core/connection_checks.js
core/connection_db.js
core/interfaces/i_connection_checker.js
core/keyboard_nav/navigation.js
core/rendered_connection.js
core/renderers/common/renderer.js
core/workspace.js
core/workspace_svg.js
tests/mocha/connection_checker_test.js
tests/mocha/connection_db_test.js
tests/mocha/connection_test.js
tests/mocha/index.html

Part of #1357
- Create a new `IConnectionChecker` interface and `ConnectionChecker` class
- Store the connections checker on the workspace and in the connection db.
- Use the new checker object everywhere
- Update tests
Extract logic so that alternate type systems can be implemented as extensions.
The tests in connection_tests.js and connection_db_tests.js were actually just checking this logic in a lot of cases. I updated them to point to the correct objects.
Eventually we will want to have a codelab or example for implementing your own connection checks.
Next steps:
- Add deprecation warnings for old functions
- Add tests for old functions 
- Register the checker through the registry, instead of always creating an instance of `Blockly.ConnectionChecker`. (separate PR)
The first two I'm …

Connection checker object

---

core/gesture.js
tests/mocha/gesture_test.js
tests/playground.html

#3976
- Changes workspace linked to event to `startWorkspace_` for firing workspace click events.
- Adds option to listen to flyout workspace events
- This changes makes it so the workspace id for a click event made on a flyout references the flyout workspace.
- Adding an option to listen to flyout workspace events is useful for debugging. Being able to only listen to main workspace events is valuable because it reduces the amount of events.
Tested on playground.
Tested on:
The log events checkbox:
was changed to log main workspace events and log flyout events:

Add listener for flyout events to playground.

---

core/flyout_base.js

#4034
Hide flyout after events are re-enabled when creating a block from the flyout.
Allows for the category event for a flyout category closing to be triggered, making events for category open/close more consistent. 
Tested manually in playground by observing events logged.
Tested on:
The logic for hiding the flyout while Events are disabled was introduced in #1078.
This doesn't appear to cause any unintended side effects.

Hide flyout after Events are re-enabled when creating a block

---

core/blockly.js
core/trashcan.js

#4033
Adds logic for emitting event when trashcan is closed and adds helper for opening/closing trashcan flyout.
Adding helpers makes the connection between showing/hiding flyout and emitting event for open/close clearer.
Event for closing trashcan flyout is consistent with behavior of other similarly named Ui events.
Tested on playground by observing event logging.
Tested on:
The change in #4034 in combination with this change will cause event to be emitted when block is dragged out of trashcan flyout.

Emitting event on trashcan close.

---

package-lock.json
package.json
tests/mocha/.eslintrc.json
tests/mocha/test_helpers.js
tests/mocha/toolbox_helper.js

Turns off es6 method lint checking for files under tests/mocha.
Adds 'babel-eslint' parser to support arrow functions.
More flexibility and ease in writing tests.
Ran eslint.
Added eslint rules primarily based on  "plugin:es5/no-es2015" that base eslintrc file extends.
Also turned off "no-unused-vars" as the parser has issues with false positives (with helper functions defined in tests that used comment exported before to be ignored).

Allow es6 in mocha tests lint check

---

tests/playgrounds/advanced_playground.html

Fixes https://github.com/google/blockly/issues/4074
This PR is against master.
Snap the dev-tools version to a specific version so upcoming changes don't affect master.
Fix playground in master.
Tested on:

Snap dev-tools in master to v1.1.0

---

core/toolbox/toolbox.js

Adds logic in for selecting a toolbox item.
Tested on:

Adds select logic

---

appengine/storage.py

Part of data retention.
- Add a `last_accessed` field to the `Xml` model
- Use `auto_now` to [make it update on every put](https://googleapis.dev/python/python-ndb/latest/model.html#google.cloud.ndb.model.DateTimeProperty)
- Update when accessed
Data retention
Not yet tested. I think my best way to test would be to:
- deploy this on staging
- save some blocks
- inspect entities to find the correct one and confirm that the datetime is correct
- open the saved blocks from the link
- inspect entities to confirm that the last_accessed time has been updated
I can also set the property to be required, but I'm not sure what value I would end up with. The documentation says "And unlike the legacy google.appengine.ext.db, auto_now does not supply a default value."
I will need to add a …

Add last accessed time to Xml model, and update it when getting from the db

---

core/toolbox/separator.js

Adds a toolbox separator class.
Tested on:

Add separator for toolbox

---

core/toolbox/category.js

Adds create dom methods for a category.
Tested on:

Adds create dom for the category

---

core/options.js

Add typedefs for MoveOptions, GridOptions and ZoomOptions.
Strict types
Tested with build.
Tested on:

Add option sub types

---

tests/mocha/.eslintrc.json
tests/mocha/block_test.js
tests/mocha/comment_test.js
tests/mocha/event_test.js
tests/mocha/index.html
tests/mocha/procedures_test.js
tests/mocha/test_helpers.js
tests/mocha/trashcan_test.js
tests/mocha/workspace_comment_test.js
tests/mocha/workspace_svg_test.js
tests/mocha/workspace_test.js

Part of #4070
Part of #4064
Partially addresses #4080
- Adds shared setup/cleanup to handle resolving all setTimeout calls triggered in tests in teardown, disposes of workspace, and resets global properties on Blockly.Events (`sharedTestSetup` `sharedTestTeardown`)
- Adds warnings in cleanup to help with detecting leakages from other tests
- Adds try/catch/finally in cleanup that logs an errors on Blockly code so that it does not prevent other tests in the suite from running and also still performs some of the cleanup needed.
- Moves logic for stubbing `Blockly.Events.fire` into shared setup
- Adds usages of `sharedTestSetup` `sharedTestTeardown` in tests that were stubbing/spying `Events.fire`
- Shared code makes for easier cleanup
- Cleaning up async calls reduces possibilities of test …

Shared events cleanup

---

core/toolbox/toolbox.js

Handles keyboard events and clicking on the toolbox and toolbox items.
Tested on:

Adds keyboard and onClick logic

---

core/flyout_button.js

#4027
Flyout buttons store all attributes/properties of their xml/json definition. This information can be useful for button callbacks. See [this comment](https://github.com/google/blockly/issues/4027#issuecomment-656325534)

flyout button stores all the deserialized properties

---

core/block_dragger.js
core/bubble_dragger.js
core/trashcan.js

Fixes #4061
Renames methods for opening/closing trashcan lid to mention "lid".
This rename makes it clearer that these methods are referring to closing the lid, rather than the trashcan flyout (which can also be opened/closed).
Tested on:
I searched devsite source and didn't find any places that should be updated, aside from the pages auto-generated from jsdoc.

Rename trashcan api calls for open/close lid.

---

tests/mocha/event_test.js
tests/mocha/json_test.js
tests/mocha/navigation_modify_test.js

None
Fixes asserts in tests to follow the form: (actual, expected) so that error messages are correct.
This fixes test assert messages so the values aren't swapped, making for a better debugging experience.
Ran tests.
Tested on:
Files updated using the regex:
Find:
`chai.assert.equal\((\d+), ([^\s\)]+)\);`
Replace:
`chai.assert.equal\($2, $1\);`

Cleanup of chai asserts

---

tests/mocha/index.html
tests/mocha/navigation_modify_test.js

Part of #4070
Part of #4064
- Adds call to shared setup and teardown and updates test logic for testing event firing.
- skips failing tests in `navigation_modfiy_test.js`
- Cleans up async calls after tests.
- The failures in the tests are a pre-existing race condition that was not apparent until the introduction of the stubbed clock. A separate bug (#4113) was filed to either fix the tests or determine whether it is a bug in keyboard nav.
Tested on:

Nav modify test shared cleanup

---

tests/mocha/test_helpers.js
tests/mocha/theme_test.js

Part of #4070
Part of #4064
- Adds call to shared setup and teardown and updates test logic for testing event firing.
- Updates logic for getting full test name in shared test helpers so that the correct reference is found when it is called from test (rather than setup/teardown).
- Adds proper cleanup to `'Set theme'` tests
- Cleans up async calls after tests.
- `'Set theme'` test cleanup (workspace dispose and undefining test blocks) was not correct as it would not cleanup if any asserts failed (thus the need for a try/finally).
Tested on:

Adding cleanup to theme tests

---

tests/mocha/insertion_marker_test.js

Part of #4070
Part of #4064
- Adds call to shared setup and teardown and updates test logic for testing event firing.
- skips failing tests in `insertion_marker_test.js`
- Cleans up async calls after tests.
- The failures in the tests are a pre-existing race condition that was not apparent until the introduction of the stubbed clock. A separate bug (#4116) was filed to either fix the tests or determine whether it is a bug in keyboard nav.
Tested on:

Insertion Marker tests async cleanup

---

demos/blockfactory/factory.css
demos/blockfactory/index.html
demos/code/index.html
demos/code/style.css
demos/storage/index.html

Fixes #4063
Adds a link to the google privacy policy on the demos that use storage.
- code
- storage
- block factory
See #4063 
Opened the demos locally

Add privacy policy to demos that use storage

---

core/field_number.js
tests/mocha/field_number_test.js

Fixes issue #4105 
Use toLocaleString when counting decimal places for consistent results around small values. Numbers like 1e-7 automatically get converted to exponential notation with .toString()
Test coverage added in separate PR #4115 
Tested on:
* Desktop Firefox 
* Desktop Safari 
There is potentially issues with IE 10 support here since the "locale" and "options" arguments for .toLocaleString are not supported for IE 10. I don't have an easy way to test IE 10 at the moment.

Use toLocaleString to count decimal places consistently

---

.eslintrc.json
.travis.yml
core/renderers/measurables/types.js
core/xml.js
package-lock.json
package.json
tests/mocha/extensions_test.js

Replaces #4131
- Bump eslint from v5 to v7
- Fix eslintrc.json formatting: use // comments
- Fix errors with no-prototype-builtins, which was added to eslint:recommended in v6
- Remove node 8 from travis.yml (end of lifed, and no longer supported for eslint)
- Add node 14 to travis.yml
Version upgrades, prompted by dependabot.

Upgrade eslint

---

package-lock.json
package.json

Remove unused dev dependencies.
Remove dev dependencies on pngjs and pixelmatch.
These were only used in the pixel-perfect screenshot tests that I recently deleted.
Brought up by dependabot trying to update pngjs: https://github.com/google/blockly/pull/4148
I will close that issue after this lands.

Remove img deps

---

demos/blockfactory/app_controller.js
demos/code/msg/en.js
demos/storage/index.html

Update the alerts in the three demos that have blocks storage on Google side. This is inline with the verbiage agreed with legal/privacy teams.

Update link alert description in demos

---

.jshintignore
package-lock.json
package.json

None
Remove jshint from devDependencies; remove jshint config from package.json; delete jshintignore.
We are fully committed to eslint now, and our jshint config was clutter but not useful.
Dependabot proposed a jshint update that made me realize we probably just don't need it.

Remove jshint

---

core/zoom_controls.js
tests/mocha/index.html
tests/mocha/zoom_controls_test.js

Part of #4065
- Used event dispatching to test click behavior in zoom controls
- Changed the svg element that the zoom control behavior is bound to
- More tests
- Changing the svg element made it easier to test and seemed like an appropriate element to use
Tested on:

Zoom controls test click

---

core/flyout_horizontal.js
core/flyout_vertical.js
core/mutator.js
core/toolbox.js

Closes #4138 
Fixes most of #4086 
Makes it so that the size of the toolbox gets properly updated so that block bumping happens correctly.
The problem was actually that the absolute left/top value was not getting updated because the workspace wasn't getting translated.
Also makes it so that mutator blocks get properly bumped away from the top edge and flyout edge:
#4086 is partially fixed. Blocks get moved when the flyout resizes, but only in LTR. And the bubble doesn't get resized.
To fix this you should just need to fire a resize event on the workspace whenever the toolbox size changes. That will make should make the bump and bubble resize trigger. But adding workspace resize events seemed a bit outside the scope of this PR, so I decided to punt on it.
Bash the bugs.
I know you've been …

Fix toolbox sizes not being updated properly

---

core/inject.js
core/utils.js

n/a
Changing `console.log` calls that start with "WARNING:" with `console.war` and removing "WARNING".
Using `console.warn` seems to better fit intention.

Replace console "WARNING" log calls with warn call

---

package-lock.json
package.json
tests/mocha/.mocharc.js
tests/mocha/mocha.opts
tests/node/.mocharc.js
tests/node/mocha.opts
tests/run_all_tests.sh

Replaces #4141
- Bump mocha from v6.2.3 to v8.1.1
- Replaces deprecated moch.opts with equivalent.mocharc.js
- Updated command in `run_all_tests.sh` for node mocha tests to pass new config file
Version upgrades, prompted by dependabot.

Upgrade mocha.

---

core/input.js

Fixes https://github.com/google/blockly/issues/4178
Call applyColour when inserting a field to a block that has already been rendered.
Bug fix.
Tested with the get_list block.
Tested on:

Call apply colour when inserting field into rendered block

---

tests/mocha/astnode_test.js

Part of #4080
- Removes unecessary delete calls
- Remove unecessary stub call
- Adds missing workspace dispose cleanup (`workspaceTeardown`) 
Cleanup of tests.
Tested on:

Add missing workspace cleanup in astnode tests

---

core/insertion_marker_manager.js

Closes #4048
Dispose of lastMarker_ before reassigning it.
The lastMarker_ was not being properly disposed when it was being reassigned by initAvailableConnections. This meant a block was getting left behind in the workspace's topBlocks_ array. So when you deleted all of the blocks, it would try to fire a delete event for the insertion marker. The insertion marker doesn't seem to serialize properly? so it would cause the trashcan to throw errors when it received the event.
Manually tested and could not reproduce #4048
Tested on:
N/A
N/A

Fix trashcan errors on delete event

---

core/registry.js

Changes registry types to use camel case.
1. Consistency - some types already used camelCase and we shouldn't mix conventions
2. Eliminates the need to quote property names. In the following example:
```
const defaultOptions = {
toolbox: toolboxCategories,
plugins: {
'toolbox': ContinuousToolbox,
'flyouts-vertical-toolbox': ContinuousFlyout
},
};
```
the quotation marks are required around `flyouts-vertical-toolbox` or else a JavaScript syntax error occurs. By using camel case, we avoid this problem.
These two registry types are not yet in master, so this isn't a breaking change.

Use camel case for registry types

---

tests/mocha/field_test.js

Part of #4194
- Refactors field setValue tests to be clearer and use sinon stubs
- Stubs deprecation warning logs at start of test and references related bug
- Refactor was done to make it easier to follow why some tests were and weren't triggering deprecation warning log and also make the tests easier to follow.
- Suppressing logs cleans up console
Tested on:
Rebased on #4195

Field test deprecated logs

---

tests/mocha/json_test.js

Part of #4194 
Removes unnecessary block `dispose` calls.
This call was causing issues with test leakage because it is called after the `sharedTestCleanup`. Since the `dispose` is not needed, I removed the `dispose` calls rather than swapping the order.
Tested on:

Remove unnecessary block dispose that was causing test leakage.

---

tests/mocha/field_dropdown_test.js
tests/mocha/field_test.js
tests/mocha/field_variable_test.js
tests/mocha/input_test.js
tests/mocha/navigation_test.js

n/a
Updates test asserts on stubs to use sinon asserts
- Better assert messages
- In some cases, clearer intention
Tested on:
Used the following regex to perform cleanup:
| Search | Replace |
| --- | --- |
| chai\\.assert\\((.+)\\.called(Once\|Twice\|Thrice)\\); | sinon\\.assert\\.called$2\\($1\\); |
| chai\\.assert\\.isTrue\\((.+)\\.called(Once\|Twice\|Thrice)\\); | sinon\\.assert\\.called$2\\($1\\); |
| chai\\.assert\\((.+)\\.notCalled\\); | sinon\\.assert\\.notCalled\\($1\\); |
| chai\\.assert\\.isTrue\\((.+)\\.notCalled\\); | sinon\\.assert\\.notCalled\\($1\\); **[no occurrences]** |
| chai\\.assert\\.isFalse\\((.+)\\.notCalled\\); | sinon\\.assert\\.isCalled\\($1\\); **[no occurrences]** |
| chai\\.assert\\.isFalse\\((.+)\\.calledOnce\\); | …

Update test asserts on stubs to use sinon asserts

---

tests/mocha/index.html

Part of #4194 
Gives blocklyDiv used in mocha tests a height using css.
Tests were triggering warning:
```
inject.js:314 Moved object in bounds but there was no event group. This may break undo.
```
This fixes all instances aside for a couple in `navigation_modify_test.js`.
Ran mocha tests and confirmed that css changes did not affect the test result styling.
Tested on:

Give Blockly div in tests a height.

---

core/flyout_base.js

Use `convertToolboxContentsToJSON` instead of `convertToolboxToJson` when parsing a dynamic category that's part of an array of toolbox contents.
`convertToolboxToJSON` puts the parsed category contents into an object under a property called contents. Instead of merging the array of contents into parsedContent, it gets added as a sub-array which is never properly iterated through. This causes contentInfo (line 537) to contain that parent object instead of the first of the actual contents. That object does not contain a `kind` property, causing an error on the next line. Using `convertToolboxContentsToJSON` correctly puts the parsed contents directly into an array which is merged into parsedContent.
I was getting errors in the continuous flyout after pulling down the latest of toolbox, and …

Fix dynamic category generation when part of an array

---

appengine/add_timestamps.py

Part of #3899
A script to get all Xml entries in the datastore for Blockly demos
and reinsert any that do not have a last_accessed time.
This script should only need to be run once, but may take a long time
to complete.
NDB does not provide a way to query for all entities that are missing a
given property, so we have to get all of them and discard any that
already have a last_accessed time.
Need to be able to run this somewhere where it won't time out.
Technically I don't need to check it in since in theory I'll only run it once, but I'd rather get a full review and check it in in case we have problems down the line.
Tested against my test project and confirmed in pantheon.

Script to add timestamps, with instructions

---

core/registry.js
core/toolbox/category.js
core/toolbox/separator.js
core/toolbox/toolbox.js
tests/mocha/toolbox_test.js
tests/scripts/selenium-config.js

Adds support for having both categories and blocks as children of a category. Ex: 
<category name="something">
<category name="somethingElse"></category>
<block></block>
</category>
Tested on:
I had originally decided to not have this in core, however I was re reading documentation and realized that we offer this feature in the old toolbox. So adding this as to not break anyone.

Adds support for both categories and blocks

---

appengine/expiration.py
appengine/main.py

Part of #3899 
Add an expiration handler that gets keys for expired items (last accessed more than a year ago) and deletes them.
I'm going to set up a cron job to hit this endpoint. But we don't need to start running that yet, since nothing expires for at least a year from now.
Data retention.
Tested locally:
- dev_appserver
- local datastore
- set retention window to a few hours instead of a year
None
Remaining work:
- handler to add dates to all existing entries
- cron.yaml

Add expiration handler

---

core/flyout_button.js

Adds public methods for getting the value of several private fields on flyout_button I'm using in the continuous toolbox plugin.

Add getters for private properties in flyout button

---

core/registry.js

Toolbox Item registry throwing an error when we override the default value.
Tested on:

Fix category registry bug

---

core/toolbox/category.js
tests/mocha/.eslintrc.json
tests/mocha/toolbox_helper.js
tests/mocha/toolbox_test.js

Categories that are nested twice currently do not work. 
Steps to reproduce: 
1. Add a double nested category to your toolbox
<category name="LogicNestedOne">
<category name="LogicNestedTwo">
<category name="LogicNestedThree"></category>
</category>
</category>
2. Expand all the nested categories 
3. Close the top category.
4. Use the arrow keys to go to the next item 
Notice how the next item is only selected after hitting the down button two times.
Checks all ancestor categories to make sure they are all expanded, in order for a category to be visible. The keyboard navigation uses visibility to tell if a category can be navigated to
Added tests for this case. also while I was here, I cleaned up some typos in types for test_helpers that were causing red squiggles.
I'm pretty sure we can …

Fix deeply nested categories visibility

---

tests/mocha/navigation_test.js

Part of #4194 
Stubs modify in workspace keys insert test.
Cleans up console when running tests. The modify call in this tests was logging a warning. Since there are other tests that cover the behavior of modify, it seemed appropriate to stub modify here rather than to mark a node before calling insert.
Tested on:

Stub modify in navigation_modify workspace keys test

---

tests/mocha/event_test.js

Part of #4194 
Modifying setup in event tests to not disable/enable events when creating a block with variable.
Disabling/enabling events was causing the error:
```
Events Constructors With variable getter blocks Block change
Error: Tried to call dropdownCreate on a variable field with no variable selected.
at Blockly.FieldVariable.dropdownCreate [as menuGenerator_] (field_variable.js:390)
at Blockly.FieldVariable.Blockly.FieldDropdown.getOptions (field_dropdown.js:478)
at Blockly.FieldVariable.Blockly.FieldDropdown.doValueUpdate_ (field_dropdown.js:521)
at Blockly.FieldVariable.doValueUpdate_ (field_variable.js:285)
at Blockly.FieldVariable.initModel (field_variable.js:133)
at Blockly.FieldVariable.toXml (field_variable.js:180)
at Object.Blockly.Xml.fieldToDom_ (xml.js:113)
at …
```

Fixing issues with workspace dispose in event tests.

---

demos/code/style.css

#4245
Adds a white-space: nowrap property to the tabon class.
Certain unicode characters layout vertically by default. This was pushing the size of the content area down when it should not have been.
Adding an explicit white-space: nowrap property to the div makes it so that they always layout horizontally, so we don't get size issues:
Tried switching between Japanese, Traditional Chinese, and English. Observed no layout issues.
Tested on:
N/A

Fix code demo size being incorrect for some langs

---

core/block_events.js
core/connection.js
core/input.js
core/rendered_connection.js
core/xml.js
tests/mocha/connection_test.js
tests/mocha/event_test.js
tests/mocha/index.html
tests/mocha/workspace_test.js

Closes #3964 
Addresses #3929
See #3902 for more details.
To address #3929:
I looked into the `Blockly.Events.recordUndo` issue mentioned [here](https://github.com/google/blockly/issues/3929#issuecomment-641419970). I tracked it back to [this commit](https://github.com/google/blockly/commit/2a1ffa11c4c167e013cb1505afcd6e4cde9291f5#diff-1a1453e5905aa4f669088c9cfc5e6951R510).
After some testing it seems like the reason this was added is because it was allowing create, move, and delete events to handle deleting/respawning shadows in the context of undoing/redoing events (recordUndo is always false when undoing/redoing events). I've changed it so that if those events are recording info about a shadow block, they no longer get applied to the undo stack. This means that shadow spawning/deleting …

Add programmatically setting shadows Take 2

---

package-lock.json
package.json
tests/run_all_tests.sh

Fix issue with uncompressed build.
Revert google-closure-deps update to avoid regression.  https://github.com/google/blockly/pull/4259
Add build test to build all of Blockly and catch cases like this in the future.
Fix build.
Tested on:

Revert closure deps package update

---

core/mutator.js

Error reported on the forums. https://groups.google.com/g/blockly/c/AQBVus73VXM/m/gnD3JUmbAgAJ
Checks that the flyout exists before accessing any flyout properties.
Some mutators don't contain flyouts.
* Tested that a mutator with no quark blocks (ie no flyout) does not break.
* Retested mutator bumping for rtl and ltr.
Tested on:
Nope
Should not change any functionality, this basically just rearranges some code.

Fix flyoutless mutators throwing errors.

---

core/block.js
core/flyout_base.js
tests/mocha/block_test.js
tests/mocha/event_test.js

Resolves #3584 and resolves #2627 
1) In flyout, moves the block Create event after the var create events.
2) In block creation, disable recordUndo during block initialization and set the group id to match.
There are two existing bugs, details in the issues linked above. Both are manifested by undo issues. After this change, the undo issues do not appear.
For 1) just drag a for loop out of the flyout, then undo. There will be a warning in the console.
For 2) do
```
var a = Blockly.getMainWorkspace().newBlock("controls_for");
a.initSvg();
a.render();
```
then undo. you notice the block is deleted, but you can press undo again, then get a console warning.
In this case, there is a block Change event that is fired before the Block create event. That is true after this change too but at least …

Fix bugs related to events firing during block create

---

core/block_svg.js
core/blockly.js
core/connection.js
core/flyout_base.js
core/interfaces/i_copyable.js
core/trashcan.js
core/workspace_svg.js
core/xml.js

#4048
The fix for the bug is this line: `event.type == Blockly.Events.BLOCK_DELETE && event.oldXml.tagName &&`
However, I updated the types on `blockToDom` and `blockToDomXy` to return an Element or a DocumentFragment as suggested so that we can hopefully avoid a similar problem in the future.
Document Fragments is not a subtype of Element and therefore does not contain the same methods and attributes as an Element such as tagName, setAttribute, getAttribute etc. 
Tested on:
I am assuming in one of my casts that there is no reason for a block to be both a shadow block and an insertion marker, but if you can think of a reason lmk.

Update types to include document fragments

---

core/mutator.js
core/options.js
core/toolbox/toolbox.js
core/trashcan.js
core/utils/toolbox.js

Resolves #4246 
Converts toolbox position from a number to an enum. Backwards compatible.
Tested on various demos including RTL.

Convert toolbox position to enum

---

core/css.js

Fixes #4012
Add position: relative to the blocklyDropDownContent div. 
When a dropdowns content was too long it was adding scrollbars on the parent page as well as the dropdown div. This causes the problem in #4012 but also causes the page to jump when the dropdown is clicked in safari. 
Tested to make sure it does not cause #3178 to reappear.
Tested on:

Fixes problem with dropdown scroll

---

core/mutator.js

Reverts part of #3468 in order to fix #4175.
Remaining issue is documented in #4288.
Set rendered = false before mutating a block.
Tested on:

Fixes blocks flying when mutator is open

---

generators/lua.js

Fixes #3978 and part of #3979 
Make the Lua multiline quote function generate multiple concatenated strings instead of a single multiline string.
Previous code was wrong anyway.
Multiline literals get additional indentation in loops, and the easiest way to fix it is to switch to concatenation.
Tested with these blocks:
```
<xml xmlns="https://developers.google.com/blockly/xml">
<block type="controls_repeat_ext">
<value name="TIMES">
<shadow type="math_number">
<field name="NUM">10</field>
</shadow>
</value>
<statement name="DO">
<block type="text_print">
<value name="TEXT">
<shadow type="text">
<field name="TEXT">abc</field>
</shadow>
<block type="text_multiline">
<field name="TEXT">this is&amp;#10;a &amp;#10;multiline &amp;#10;string</field>
</block>
</value>
</block>
</statement> …
```

Fix lua multiline quote

---

generators/python.js

Part of #3978 
Change Python multiline string generation to use concatenation.
Excessive indentation if using a multiline string in a loop.
Tested in the advanced playground with these blocks:
The old generated code looked like this:
```
for count in range(10):
print('''this is
a
multiline
string''')
```
The new code looks like this:
```
for count in range(10):
print('this is' + '\n' +
'a ' + '\n' +
'multiline ' + '\n' +
'string')
```
I tested the generated code on repl.it with Python 3.

Fix python multiline string

---

generators/php.js

Part of #3978 
Changes PHP multiline string generation to use concatenation.
Excessive indentation if using a multiline string in a loop.
Also, the previous code produced invalid PHP.
Tested in the advanced playground with these blocks:
The old generated code looked like this:
```
for ($count = 0; $count < 10; $count++) {
print(<<<EOT
this is
a
multiline
string
EOT);
}
```
The new code looks like this:
```
for ($count = 0; $count < 10; $count++) {
print('this is' . "\n" .
'a ' . "\n" .
'multiline ' . "\n" .
'string');
}
```
I tested the generated code on repl.it.
The print statement in PHP does not automatically add a newline at the end of the line. I did not add it here because I didn't want to change the existing generator, but the fact that we haven't been getting complaints says to me …

Fix PHP multiline string

---

generators/dart.js

Part of #3978 
Change Dart multiline string generation to use concatenation.
Excessive indentation if using a multiline string in a loop.
Tested in the advanced playground with these blocks:
The old generated code looked like this:
```
for (int count = 0; count < 10; count++) {
print('''this is
a
multiline
string''');
}
```
The new code looks like this:
```
for (int count = 0; count < 10; count++) {
print('this is' + '\n' +
'a ' + '\n' +
'multiline ' + '\n' +
'string');
}
```
I tested the generated code on [dartpad.dev](dartpad.dev).

Fix dart multiline strings

---

core/xml.js

#3542
Calls `initSvg` for block with mutator after fields' `fromXml` are called.
Fixes issue with variable fields with a mutator creating extra variable models.
- Tested repro steps in #3542 and saw issue was fixed.
- Ran mocha tests.
Tested on:

Call initSvg for blocks with mutator after loading field xml

---

core/block_svg.js
core/input.js
core/rendered_connection.js

Reverts google/blockly#4264
Caused issues with deleting collapsed blocks.

Revert "Don't render children of collapsed blocks"

---

core/block_svg.js

Checks whether a child block is rendered before calling updateDisabled.
Cut off a deep recursive stack that was happening on every mouse move.
Tested in the playground by:
- creating a large spaghetti stack
- collapsing top blocks
- starting a performance log
- dragging a block over the collapsed stacks
- stopping the performance log
- inspecting the flame chart and making sure that there aren't 100+ ms of recursive updateDisabled calls
Updating disabled is expensive because it applies a change to the dom every time, instead of checking if a change has actually occurred and only then doing the update.

Don't update disabled on unrendered children

---

core/block_svg.js

Part of #4229 
Don't recursively call `updateDisabled` on children of collapsed blocks.
Children of collapsed blocks are hidden and don't need to be updated. Unnecessarily calling `updateDisabled` (and `appyColour` on these blocks is a big drain on performance.
Tested in playground by:
- Creating a large spaghetti stack
- Collapsing all blocks
- Disconnecting one of the collapsed blocks
- Starting a performance log
- Dragging the disconnected block across the collapsed stacks
- Stopping the performance log
- Observing significant reduction of `updateDisabled` calls
Tested on:
This change improves performance for collapsed block, but there still appears to be drag lag issue.

Don't update disabled on children of collapsed blocks.

---

tests/run_all_tests.sh

Tests keep failing with ECONNREFUSED, and it looks like it's because the selenium server isn't up by the time mocha tests start.
Move some longer tests that don't need the selenium server to run earlier.

Change order of tests to avoid timing issues

---

core/options.js
core/toolbox/toolbox_item.js
demos/blockfactory/workspacefactory/wfactory_controller.js
tests/mocha/index.html

Block factory was broken due to: 
1. Using Blockly.Options.parseToolbox instead of Blockly.utils.toolbox.parseToolbox
2. Toolbox Items use the given id on the `<category>` element when creating the html for the toolbox. This causes problems since the `<category>` xml has the same id.
1. Use Blockly.utils.toolbox.parseToolbox.
2. .  Use a different name for the id so that there are not two elements on the page with the same id.
Tested on:
I could potentially keep it as `id` for JSON and change it for xml but I thought this would be more confusing. So changing the name for both.

Block factory fix

---

tests/mocha/procedures_test.js

Closes #4080
- Refactors tests to generate separate tests for `procedures_callreturn` and `procedures_callnoreturn` rather than use `this.callForAllTypes`.
- Adds `try`/`finally` blocks with `workspaceTeardown` where appropriate
- Removes unnecessary `block.dispose` calls (handled in `Workspace.dispose`)
- Removes unnecessary `deleteVariable` calls (each test has its own `Workspace`)
- Without separating logic into separate test calls, if test assert failed for `procedures_callnoreturn` (was run first) then test was not run for `procedures_callreturn. This makes it easier to debug if there is a bug specific to `procedures_callreturn` or `procedures_callnoreturn`
- Workspaces are now always disposed even if assert fails
- Removing unnecessary logic helps simplify tests …

Procedures test workspace cleanup

---

core/block.js
core/block_svg.js

Deletes some deprecated functions.
Deletes block.setDisabled and blockSvg.setDisabled.
Both were past their marked removal dates.
None
Breaking change (for release purposes)--removes functions.

Delete some deprecated functions

---

demos/blockfactory/blocks.js

https://groups.google.com/g/blockly/c/Jm4_bSpjNes/m/m6HXBZNEBwAJ
Adds a `rendered` check before calling `render` on block added in `connectOutputShadow_`.
The change in #4296 caused issues with the block factory connection dropdown field. The `render` call in `connectOutputShadow_` is triggered when the validator is called in `domToHeadless_` and throws an error. 
Tested on:
Previously an error was not thrown because `initSvg` was called before the dropdown field was processed. Reverting the PR would cause issues with variable models, but adding a `rendered` check before calling `render` seems reasonable.

Fix render issue with block factory connection dropdown

---

core/toolbox/toolbox.js

Fixes #4338
Instead of setting the newX or newY to 0 when we don't want their position to change, we can set to workspace.scrollX, or workspace.scrollY
When the toolbox was not at the top the newY was getting set to 0. This was making the blocks jump. It is now getting set to the workspace.scrollY so that the blocks will stay at their current location. 
Tested on:

Fix toolbox resize problem

---

generators/dart.js
generators/dart/text.js
generators/javascript.js
generators/javascript/text.js
generators/lua.js
generators/lua/text.js
generators/php.js
generators/php/text.js
generators/python.js
generators/python/text.js
tests/generators/golden/generated.dart
tests/generators/golden/generated.js
tests/generators/golden/generated.php
tests/generators/golden/generated.py
tests/generators/unittest_javascript.js
tests/generators/unittest_lua.js
tests/generators/unittest_php.js

n/a
- Fixes text block generators logic to use the correct order
- Fixes unit test blocks logic to use the correct order (didn't seem to have caused any issues before, but were incorrect)
- Moves multiline string helper into `text.js` files
- Fixes errors in code generation for text blocks
- multiline string helper is only used in `text.js` files and moving it makes it easier to understand the logic in code for block `text_multiline`
Generated and ran unit tests for text in interpreters for all languages.
First noticed error in order after creating tests for `text_multiline` in  #4317 and saw that generated code was invalid for python for the new tests added.
In creation of this PR, also learned that `ORDER_COMMA` was being misused. In most of our use cases, `ORDER_COMMA` should have been …

Fix order errors in text generators

---

tests/generators/golden/generated.dart
tests/generators/golden/generated.js
tests/generators/golden/generated.lua
tests/generators/golden/generated.php
tests/generators/golden/generated.py
tests/generators/index.html
tests/generators/text.xml
tests/mocha/field_multilineinput_test.js
tests/mocha/index.html

n/a
-  Adds tests for multiline block, including blockToCode tests
- Adds generator tests for multiline block
- blockToCode tests were necessary to sufficiently test code generation for multiline text (cannot write tests using blocks for multiline block expected output without using multiline block) , but basic tests were added to generator tests to test order (parentheses and operator precedence).
- Better test coverage.
Tested on:
Rebased on #4329
Created with issues #3978 and #3979 in mind.

Adding tests for multiline block

---

package-lock.json
package.json
tests/playground.html
tests/playgrounds/advanced_playground.html

Add test-blocks back into the basic playground.
Switch from unpkg to using local node_modules for advanced playground dev-tools.
Add alert if npm install is not yet run.
Get test blocks from @blockly/block-test package in basic playground.
X-browser testing with test blocks in basic playground.
Tested basic playground with test blocks on IE11, Edge 18, Edge 80, and Chrome.
Relies on a publish of the @blockly/block-test package in https://github.com/google/blockly-samples/pull/384
After publish, re-run npm install, to update package-lock.json here.

Add test-blocks into the basic playground

---

core/contextmenu_items.js

Changes the default weight of context menu items. Previously they were all 0.
Developers registering custom context menu items can now more easily insert their items at the beginning (0) or in between the default items (1.5 weight etc)
Tested on:

Change weights of default context menu items to support easier sorting

---

core/field.js
tests/mocha/field_test.js

https://github.com/google/blockly/issues/4345
The issue was, in the field, if the user has entered invalid once the flag `isTextValid_;` was being set to false at `doValueInvalid_` which is fine. If however the user enters correct value, then the flag is never se to true.
I made it so that at field.js `processValidation_` we do `doValueUpdate_` so that we update the flag.
To solve the bug that was opened.
Tested on:
Desktop Chrome

do value update if the value is valid again

---

generators/javascript/colour.js
generators/javascript/lists.js
generators/javascript/math.js
generators/javascript/procedures.js
generators/php/colour.js
generators/php/lists.js
generators/php/math.js
generators/php/procedures.js

Part of #4353 
Changes incorrect instances of `ORDER_COMMA` to `ORDER_NONE`.
The `ORDER_COMMA` operator enum is meant for instances of the comma operator. 
Commas inside of parentheses of function calls are not instances of the comma operator.
Does not change generated code output from generator tests.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

Replace incorrect usage of ORDER_COMMA with ORDER_NONE

---

generators/php.js

https://github.com/google/blockly/pull/4354#issuecomment-704512863
Removes comma operator order from PHP generator.
PHP does not have a comma operator.
Enum was unused in code base.

Remove ORDER_COMMA from PHP generator.

---

core/flyout_base.js

In the ContinuousFlyout plugin we need these methods on the flyout to be protected.
Tested on:

Make private methods protected

---

core/utils/toolbox.js

An issue was discovered while trying to update the maze game from https://github.com/google/blockly-games. The game worked fine without debugging enabled. However when debugging was enabled the toolbox on the left side was not visible anymore.
I never worked with blockly before so it took a while to figure out what was going on. I am not 100% sure the fix is correct.
In debugging mode (session storage, debug=1) the core/options.js does not initialise the toolboxPosition correctly because the Blockly.utils.toolbox.Position.xxx are undefined. This is caused by an unspecified dependency on Blockly.constants in utils/toolbox.js which was introduced in https://github.com/google/blockly/commit/f6688d033923a2b53da401d6998e906b7d938ff2
None
Include necessary dependency in utils/toolbox.js
Before …

Add Blockly.constants dependency to utils/toolbox.js

---

core/field_textinput.js

n/a
Changes access level of `widgetDispose_` and `unbindInputEvents_` in `FieldTextInput from `@private` to `@protected` so that subclasses have access to these methods.
Since `widgetCreate_` and `bindInputEvents_` are `@protected`, it makes sense for the paired methods `widgetDispose_` and `unbindInputEvents_` to also be `@protected` so that subclasses can override them for cleanup needed to unbind events or dispose of elements created.

Update access level of methods in FieldTextInput

---

core/events.js
core/events_abstract.js
core/mutator.js
core/procedures.js
core/ui_events.js
demos/blockfactory/workspacefactory/wfactory_init.js
demos/minimap/minimap.js

Part of #4203
- Adds constants for new UI types
- Adds property `IS_UI_EVENT` to `Blockly.Events.Abstract`
- Updates checks for UI events in core to use new `IS_UI_EVENT` property instead of checking `type`
- Preparation for later refactoring of UI events
- Property added as constant on prototype as it does not change per-instance
Not yet

Ui events base

---

core/ui_events.js
core/workspace_svg.js
tests/mocha/theme_test.js

Part of #4203
Creates dedicated class (`Blockly.Events.ThemeChange`) for theme update event.
See issue, but generally motivated by:
- better typing
- clearer events
Tested by logging events on playground and using the following code:
```
var ws = Blockly.getMainWorkspace();
ws.setTheme(ws.getTheme());
```
and observing logged event had expected properties. Also ran mocha tests.
Tested on:
Previously theme events did not include theme name.

Refactor theme event

---

core/css.js

Fixes https://github.com/google/blockly/issues/4403
Add a couple of CSS properties to reset properties introduces by goog-menu on pages that goog-menu is injected by gapi.
Compatibility with gapi.
Tested on:

Fix graph demo

---

core/blockly.js
core/shortcut_items.js

Adds shortcut items. 
Refactor `Blockly.onKeyDown` to use the shortcuts registry. 
Registers the default shortcut options that used to be in `onKeyDown`.
Tested on:
This is a partial PR. For the full change see #4397.

Adds shortcut items

---

core/block_svg.js

Set `data-id` on blocks' svg groups using `setAttribute()`, not `dataset` for IE. 
https://github.com/google/blockly/issues/4419
Sets the `data-id` using `setAttribute` for IE
We use the data-id from the SVG group to interact with blocks in UI tests, so this is needed to be able to test in IE
Tested in the playground
Tested on:
* Windows IE 11

Set data-id on block svgs for IE11

---

tests/mocha/field_multilineinput_test.js

n/a
Add shared setup and cleanup to multiline field test
There was test leakage from field_multiline_test in event queue that was detected in field_number_test. This kind of leakage can cause unexpected test failure due to unexpected interactions of something that happened in previous test.
Found issue while looking at console and seeing warning:
`Number Fields Constructor Empty" needed cleanup of Blockly.Events.FIRE_QUEUE_. This may indicate leakage from an earlier test`.

Add missing cleanup to multiline field test

---

core/css.js

Fix conflict of background in dropdown div.
Make it inherit the background so that the .goog-menu selector setting the background doesn't conflict with the zelos renderer.
In addition, make it so we're not explicitly setting the background so we don't conflict with other field dropdown subclasses.
Bug fix.
Tested on:

Fix conflict in background CSS for dropdown div

---

core/field_variable.js
tests/mocha/field_variable_test.js
tests/mocha/test_helpers.js

Part of #4260
- Refactors `FieldVariable` tests to use dev-tools helpers
- Modifies handling of invalid values passed to `FieldVariable` constructor (for truthy non-string values like number or true)
- Expands coverage
- Better handling of invalid values (to use default value rather than causing error later down the line.
Ran mocha tests (using local version of dev-tools).
Depends on change https://github.com/google/blockly-samples/pull/428
Old tests:
New tests:

Refactor field_variable_tests to use dev-tools

---

core/field_textinput.js

Closes #4430 
Related to https://github.com/google/blockly-games/issues/212
Calls getValueFromEditorText_ before passing the value to setValue from the text input prompt editor (which is used on mobile).
I also got rid of the closure and used .bind() instead, as recommended by the styleguide.
Fixing bugs :D
Could not reproduce https://github.com/google/blockly-games/issues/212 using the following steps:
1) Change the text input field's show editor function to look like:
```
Blockly.FieldTextInput.prototype.showEditor_ = function(_opt_e,
opt_quietInput) {
this.showPromptEditor_();
};
```
2) Locally load the pitch field demo.
3) Enter the text "G4" into the prompt.
4) Hit "Ok".
5) Observe how the field has been properly updated.
Tested on:
Nope!
N/A

Fixes pitch field not working with prompt

---

typings/blockly.d.ts
typings/templates/blockly-header.template

It is now possible to use tsc to typecheck a .js file such as:
// @ts-check
Blockly.inject('blocklyDiv', {});
if tsconfig.json is configured with:
{
"compilerOptions": {
"allowJs": true,
}
}
(No issue was created)
It is now possible to use tsc to typecheck a .js file such as:
// @ts-check
Blockly.inject('blocklyDiv', {});
if tsconfig.json is configured with:
{
"compilerOptions": {
"allowJs": true,
}
}
Previously it was impossible to typecheck .js files with tsc which assume that Blockly is imported to the global scope via a script tag. With this PR it is now possible to typecheck such .js files.
Manually tested by running `tsc` in a directory with the following files:
```
// index.js
// @ts-check
Blockly.inject('blocklyDiv', {});
// tsconfig.json
{
"include": [
"./index.js", …
```

Allow .js script files to refer to Blockly global from blockly.d.ts

---

core/field_multilineinput.js

n/a
Fixed logic in `getDisplayText_` for `FieldMultilineText` to use `getText` rather than `this.value_` directly.
Due to the logic in `getDisplayText_`, rendering of editor text for `FieldMultilineText` was acting up in cases where the validator returned a string of different size. This is because there is extra logic in `getText` that returns the editor text if the field is currently being edited.
Before change:
After change:
Tested block with `FieldMultilineInput` and custom validator before and after change:
```
Blockly.Blocks['text_multiline_validator'] = {
init: function() {
this.appendDummyInput()
.appendField('multiline text input:')
.appendField(
new Blockly.FieldMultilineInput('default', this.validate), 'INPUT');
this.setColour('#5ba58c');
},
validate: function(newValue) { …
```

Add fix for display text on multiline text block

---

core/mutator.js

Rest of #4448
Reverts #3783. 
At the time, that PR was fine, but in combination with setting `rendered` to false to address #4175 it now causes mutations to not bump blocks, as documented by #4448
Tested on:
Nope
N/A

Add mutator bump back in

---

blocks/lists.js
blocks/logic.js
blocks/procedures.js
blocks/text.js

Part of #4448 
Adds checks for insertion markers to all compose functions.
Insertion markers should not be considered when doing composition, as they aren't actual blocks.
Note that the issue with all of the procedure args being 'x' is just because the UI events are still in flux (I think).
Tested on:
[Edit: Actually, might want to mention this under [compose and decompose](https://developers.google.com/blockly/guides/create-custom-blocks/extensions#compose_and_decompose)]
N/A

Fixes mutators considering insertion markers during compose

---

core/field_dropdown.js

Part of https://github.com/google/blockly-samples/issues/373
Changed visibility of `FieldDropdown.menu_` from `private` to `protected`.
Allows subclasses to access `menu_` property, which is useful to access the html element containing the menu. 
Change needed for plugin feature: https://github.com/google/blockly-samples/pull/440.

Make FieldDropdown menu_ field protected

---

core/flyout_horizontal.js
core/flyout_vertical.js
core/interfaces/i_flyout.js
tests/mocha/flyout_test.js

#4396
Creates `getX()` and `getY()` functions for flyouts, which are called from `position()`.
See issue for more context, but in brief, this allows subclasses to change the positioning logic, without having to override the entire position function, which does a lot of things.
I added unit tests as there were none for `position` and there is a lot of logic in there.
I also manually tested all variations of simple, category, mutator, and trashcan flyouts in top, bottom, left, and right positions and in ltr mode in the advanced playground.
None needed.
I didn't change any of the logic, just extracted the code into functions. I did add additional comments or reword the existing comments in some places because I found it confusing which cases would follow which path through the if maze, and …

factor out getX and getY methods for flyouts

---

scripts/gulpfiles/build_tasks.js

Fixes https://github.com/google/blockly/issues/4433
Replaces windows path separator with the browser path separator.
Tested on:

Fix windows path separator in uncompressed build

---

core/field.js
core/field_textinput.js
tests/mocha/field_image_test.js

Part of #4481
Removes all deprecated functions in fields.
Tested on:
`Blockly.FieldTextInput.nonnegativeIntegerValidator` doesn't look like it ever got a `Blockly.utils.deprecation.warn`. So we can either: 
- Add the deprecation warning now, and add back `Blockly.FieldTextInput.numberValidator` since `nonnegativeIntegerValidator`  relies on it.
- Just remove it now without the deprecation warning. 
- Add a deprecate warn to `nonnegativeIntegerValidator` now, and remove all the functions together when they have been deleted.
I prefer option 2 or 3, so that people only have to go through and update their fields once.

Remove deprecated field functions

---

core/generator.js

https://github.com/google/blockly/issues/2153
Adds " The generator should be initialized before calling this function." to the JsDoc fo `blockToCode`.
Unlike `workspaceToCode`, `blockToCode` must have the generator initialized before calling it, otherwise there may be a nondescript error (depending on the generator). Adding this to the documentation can help developers to have an easier time with catching this mistake.

Add info to JsDoc for blockToCode

---

tests/mocha/insertion_marker_test.js

Fixes https://github.com/google/blockly/issues/4116
Removes skip from test suite.
Tests are no longer failing (previously failed due to difference in expected block coordinates in xml).
Tested on:
After running git bisect, found that these tests were fixed at https://github.com/google/blockly/pull/4207, where the test div for mocha tests was modified.

Unskip tests that are now passing

---

core/workspace_svg.js

Part of #1476
Manually tested in playground that this change caused workspace comment create event to be emitted when a comment is duplicated.
Tested on:
Found issue by searching in repo for TODO without bug number.

Emit workspace comment create event on paste

---

core/bubble.js
core/comment.js
core/warning.js

Fixes: #4186 and #2943.
There are two methods in warning that comments need in order to create a non editable bubble. Since these methods primary goal is to create a bubble this moves those methods on to the Bubble class. 
#2943 says that the comments should have their own UI which I agree with. However, since we can not use `<foreignobject>` to create a non editable bubble (see [here](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/comment.js#L254)) then whatever UI we create will most likely rely on these methods in some capacity.
1. We want to be able to remove `getText` on the comment. We can't do that if the warning UI is using getText. (#4186)
2. General cleanup. (#2943)
Tested on:

Move where a non editable bubble is created

---

core/trashcan.js

Fixes #3975
Binds mousedown event on trashcan to prevent event propagation if opening flyout using `bindEvent_`.
This change prevents a workspace click event from emitting if trashcan click opens the flyout and otherwise emits workspace click if trashcan click does nothing (happens when trashcan contents are empty).
Tested event logging on web and mobile (using browserstack) using playground.
Tested on:
Previously a similar solution was attempted using `bindEventWithChecks_` which caused bug on mobile (#4303).

Preventing workspace click when trashcan is clicked

---

core/generator.js
generators/dart.js
generators/javascript.js
generators/lua.js
generators/php.js
generators/python.js

Fixes https://github.com/google/blockly/issues/2153
Adds property to `Generator` to allow for checking whether it has been initialized and logging a warning in `blockToCode` if `init` was not called.
Provides developers with a helpful warning when `blockToCode` is called before `init`.
Tested manually on playground with repro steps described in bug.
Tested on:
`isInitialized` is set to `null` so that it does not affect custom generators (and incorrectly log a warning when `blockToCode` is called).

Add warning to blockToCode

---

core/workspace_svg.js

#4440 
Checks that `blur` function exists before calling it.
In IE, svg elements cannot be blurred or focused, so IE users see a console error on this line as blur function does not exist.  Of course, this begs the question of how such an element became focused in the first place... I couldn't figure that out. I did some playing around in win-ie11 and couldn't ever reproduce the linked bug. The activeElement was always the svg's parent element, exactly what the code in line 1830 is doing. Perhaps there is some client code that is causing this as opposed to something in Blockly, I'm not sure, but either way since having the svg be focused in IE is unexpected behavior, and there's no way to blur it, I can't think of anything else we need to do here.
Tested on:
Desktop Chrome
Windows …

Make sure el can be blurred before doing so

---

core/shortcut_registry.js

Adds a function to remove key maps without needing to know the key code for the shortcut.
Tested on:

Add a remove key map function

---

core/toolbox/toolbox.js
tests/mocha/toolbox_test.js

Fixes #4510
Changes 'mousedown' --> 'click'.
**There were two problems for this bug:** 
1. [e.srcElement](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/toolbox/toolbox.js#L260) is undefined for a touchstart event. The [onClick_  method in toolbox](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/toolbox/toolbox.js#L255) relies on this and would therefore throw an error.
2. After this was fixed, the new bug became that the toolbox would close shortly after opening. 
**Why this bug was happening:**
1. We add a listener for a touchstart event when binding a mousedown event. 
2. Because we call [clearTouchIdentifier](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/toolbox/toolbox.js# …

Fix ios12 bug

---

blocks/loops.js

#4500 
break block onchange handler acts even if the moved block is not the break block. 
See #4500 
This was added in #3697 to fix #2321 so I double checked against the scenario in the original bug. Undo still works (thanks to the group id being set) and now the break block updates state correctly even if you are e.g. dragging a parent or a stack it's a part of. checked many variations of this to make sure.

update break block even if it's not the dragged block

---

typings/blockly.d.ts
typings/templates/blockly-header.template

Reverts google/blockly#4434
This was causing the following issue:
```
node_modules/blockly/msg/msg.d.ts:13:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ADD_COMMENT, CANNOT_DELETE_VARIABLE_PROCEDURE
```
It looks like messages are getting defined twice, which is causing problems. 
This can be seen by running this version of blockly with our angular example.
Opening #4544 to look into this more next release.

Revert "Allow .js script files to refer to Blockly global from blockly.d.ts"

---

appengine/redirect.html

Currently there's a double-redirect (Blockly sends the user to appspot, Blockly Games then sends the user to its own domain).

Update Blockly Games URL.

---

tests/playgrounds/iframe.html

- [ x] I branched from develop
- [ x] My pull request is against develop
- [ x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
Fixed misplaced percent sign in css, close iframe html tag
It fixes possible bugs.
Missplaced "%" sign may cause css bugs.
Iframe tag must be closed.

Fix misplaced percent sign in css, close iframe html tag

---

core/field_multilineinput.js

[#3969](https://github.com/google/blockly/issues/3969#issue-638060504)
Added a maxLines config option to multiline text input
[#3969](https://github.com/google/blockly/issues/3969#issue-638060504) proposed to add a scrolling functionality, to make working with large amounts of text more comfortable. 
So one of the reasons is to close the issue, another - to make working with large amounts of text more comfortable :)
Tested on:
Additionally, I have added a clamsy block to playground [here](https://github.com/gagiopapinni/blockly/tree/multilineinput-scroll) to test it, so you can also play with it

Added maxLines config option to MultilineInput 

---

core/utils.js
core/utils/useragent.js

This doesn't fix a specific problem per se, but it makes things consistent. This is ensuring we always access properties / methods on `Blockly.utils.global` using fully qualified strings (rather than dot syntax), that way the closure compiler will never rename these fields.
The reason these instances haven't caused an issue is:
- navigator: Elsewhere in the code we use the fully qualified name, so the closure compiler must pick up that that field shouldn't be renamed. 
- getComputedStyle: Unsure why that is. I would have expected it to but it didn't, maybe closure is doing something special for an object with the name `global`?
Use fully qualified names.
Consistency 
Tested on:

Be consistent in how we access global properties on Blockly.utils.global

---

core/block.js
core/block_animations.js
core/block_dragger.js
core/block_svg.js
core/blockly.js
core/bubble.js

Resolves some compiler errors that show up when I enable the `'stricterMissingRequire'` flag.
I ran `npm run build:strict:log` with that flag set, and looked for `Please add a goog.requireType`.
The new warning surfaced https://github.com/google/blockly/issues/4575

Add some missing requires and requireTypes

---

scripts/gulpfiles/build_tasks.js

In preparation for https://github.com/google/blockly/pull/4580
Temporarily disable strict require compiler errors, as the new closure compiler uses `missingRequire` to flip them on.
Temporarily disable strict require compiler errors until we have resolved the missing require checks in https://github.com/google/blockly/issues/4457
Preparation for the new closure compiler update.
Tested on:

Temporarily disable strict require compiler errors

---

core/events/ws_comment_events.js
tests/mocha/event_test.js

Fixes #4527
- Updates logic in serialization of methods of workspace comment events to be consistent.
- Adds tests for workspace comment events and finished loading event
- Workspace comment events were not serializing/deserializing properly.
- Tests are good.
Filed #4577 to track adding more complex tests for testing coordinate properties of move events (for block move and comment move).

Fix serialization of workspace comment events and add tests

---

core/field_dropdown.js
core/xml.js

Fixes #2135
- Connects block to it's parent in domToBlockHeadless_ rather than in the parent block's instantiation (allows for parent to be connected before field tag is processed)
- Before: Block was connected it it's parent after it was fully loaded (which caused issues with fields validators that depended on the connected state of the block)
- After: Block is connected to parent as it is being loaded, before it's field values are loaded
- Solves issues with loading blocks with field validators that depend on the parent being connected (and accessing parent fields) from xml
- Solves issues with loading dynamic dropdowns that depend on a connected parent from xml
Ran tests and tested in advanced playground with the following block:
```
<xml …
```

Connecting block to parent in domToBlockHeadless_

---

core/block.js
package-lock.json
tests/mocha/block_json_test.js
tests/mocha/index.html
tests/mocha/utils_test.js

Work on #4575
Refactors the interpolate_ function to be more testable and consistent. Removes the call to new Blockly.FieldLabel() in the process.
This PR breaks the interpolate_ function into 5 new functions, so that each piece can be tested individually:
* validateTokens_(): Ensures that all of the args are referenced, that all references are in the correct range, and that there are no duplicate references.
* interpolateArgs_(): Replaces all arg references and strings with field/input json definitions. This means that `interpolate_` can invariantly expect all elements of the `elements` array to be objects, which simplifies the logic in `interpolate_` greatly.
* inputFromJson_(): Appends an input to the block and returns it, given a json representation of an input. 
* fieldFromJson_(): …

Refactor interpolate_ into multiple functions & remove direct new Field call

---

typings/templates/blockly-interfaces.template

#4587
Changes type to Blockly.utils.toolbox.ToolboxDefinition. This encompasses the following types:
Node
Blockly.utils.toolbox.ToolboxInfo (Json Toolbox)
string
This was never updated after we added support for the json toolbox.
Tested on:

Fix toolbox typings

---

scripts/gulpfiles/appengine_tasks.js

Fixes https://github.com/google/blockly/issues/4567
Include playground deps from node_modules in the set of files deployed to appengine.
Fix deployed playgrounds.
Tested on:

Update appengine_tasks to include playground dependencies

---

core/block.js
core/input.js
tests/mocha/block_json_test.js
tests/mocha/input_test.js

Closes #4575 
1) Changes input.insertFieldAt to use the field registry.
2) Fixes last dummy inputs only being added for fields where the key is prefixed with 'field_'
Changes are kept in separate commits to make reviewing easier =)
1) Using the registry allows people to override the default field for strings, as referenced in #4575 
2) Not all fields are prefixed with 'field_' but we should add the last dummy input regardless.
Most of the tests were already written :D But for insertFieldAt I made a test to make sure if field_label gets overwritten in the registry, the new field gets used. And for interpolation I added a test that fields prefixed with input_ also force dummy inputs to be created.
Again, I went through and checked all of the core blocks and test blocks to make sure they get …

Remove last FieldLabel call and fix adding dummy inputs to json

---

README.md

* Copied the introductory statement from the dev site. The devsite introduction makes it more clear that Blockly is a library, not a standalone application. but I can change this back if we are attached to the original statement.
* Kept the image at the top, despite it not showing in the diff preview
* Added an explicit Getting Started section with links to the main resources and where to get help
* Added info on blockly-samples
* Fleshed out the Contributing section
* Added info on beta channel
* Updated date of next release, definition of major and patch update, and some other minor release info (it said we were on major version 2)
* Switched the order of "branches" and "new APIs" so they reference each other in a logical order
I filled in all the links afterward, please help me double …

Reorganize README.md and add more links

---

core/workspace_svg.js

Fixes #4636
Removes insertion marker from content size computation (cause of erratic scroll bug)
Erratic scroll behavior in `contentResize` logic, as described in #4636, where no scroll was expected.
No erratic jump in scenario described by #4636.
Fixes incorrect behavior (insertion marker was causing issues in the math for scrolling)
Extensive manual testing in playground.
Broken off from #4643
This was a tricky change.

Erratic scroll fix

---

core/block.js
core/blockly.js
core/constants.js
core/input.js
core/renderers/common/info.js
core/renderers/zelos/info.js
tests/mocha/block_json_test.js

Fixes 16 warnings.
Move the align constants into an enum on the Blockly.constants namespace, and then add aliases in blockly.js.
Resolves compiler warnings related to setting properties on `Blockly` from `constants.js`.
Allows files to require `constants` rather than `blockly` to get the correct values, to reduce circular dependencies.
- Will need to make sure the jsdoc is correct.
- Constants are referenced in the [define blocks page](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks)
There are still uses of the old names in demos and in samples.
We will likely never get rid of the old constants for external use, because they are part of block definitions. But all internal uses should now use the constants file.

Align constants -> Blockly.constants.ALIGN enum

---

core/flyout_base.js
core/flyout_horizontal.js
core/flyout_vertical.js

Addresses #4038 but it doesn't change anything about the block dragging / adjust block position relative to cursor.
Adds an overrideable function to get the flyout scale. By default, it has the exact same behavior as before, as in it just returns the target workspace scale. But now the behavior is customizable, for example you can override the function to return a constant value if you never want the flyout to zoom. You could also do something more complex such as implement independent zoom controls for the flyout.
The flyout zoom level always matches the target workspace zoom level.
The behavior is customizable. For example, I added the following code:
```
/**
* @override
*/
Blockly.VerticalFlyout.prototype.getFlyoutScale = function() {
return 1;
};
```
and you get the result shown in …

Add overrideable function to get flyout scale

---

core/registry.js
core/toolbox/toolbox.js
core/workspace.js
core/workspace_svg.js

Fixes 6 strict missing requires errors.
Use the registry for creating the vertical / horizontal flyout on a no-category workspace.
@rachel-fenichel  FYI

Use registry for creating the no-category flyout

---

core/blockly.js
core/constants.js
core/flyout_horizontal.js
core/flyout_vertical.js
core/metrics_manager.js
core/toolbox/toolbox.js
core/trashcan.js
core/utils/toolbox.js
core/workspace_svg.js
core/zoom_controls.js
tests/mocha/flyout_test.js
tests/mocha/toolbox_test.js

Resolves ~40 missing require warnings.
Replace uses of `Blockly.TOOLBOX_AT_TOP` and friends with uses of `Blockly.utils.toolbox.Position.TOP` and friends.
Leave the old names around as aliases in `blockly.js`.
No change in behaviour--just in types.

Use Blockly.utils.toolbox.Position enum everywhere

---

core/flyout_base.js

Fixes #4692
Adds `setPosition` call inside of Flyout code to fix issues cause by scrollbar not repositioning correctly in certain edge cases.
Scrollbar was not repositioning correctly, as described in #4692
Scrollbar positions correctly.
Bugfix
Manual testing in playground.
This `setPosition` call was removed in #4607 because it was incorrectly assumed to be unnecessary. A comment has been added to reference why it's needed and the bug for additional repro of what it fixes.

Fix flyout scrollbar reposition edge case

---

core/input.js
scripts/gulpfiles/build_tasks.js
tests/compile/main.js
tests/compile/test_blocks.js

Advanced compilation test was failing due to 
- Us moving the "test_style_hex1" block out of core
- Because of a type cast to `Blockly.FieldDropdown`.
This bug was a bit weird and I am not entirely sure I understand what is happening but I will try to document at least what I know:
- We were getting an error because somehow [field.suffixField](https://github.com/google/blockly/blob/d7e9eaff0fd533e8bfda905c8eb02a16722af89d/core/input.js#L122) was getting set to true when it shouldn't be(only in advanced compilation).
- We do not get the error when we remove the [type cast](https://github.com/google/blockly/blob/d7e9eaff0fd533e8bfda905c8eb02a16722af89d/core/input.js#L114) OR when we remove [these three lines](https://github.com/google/blockly/blob/82a2dd90a7f965205882875bf7325dd4428fd0e9/cor …

Fix advanced comp

---

core/events/ws_comment_events.js
tests/mocha/event_test.js

Fixes #4527
Includes `oldContents` and `oldCoodinate` in serialization/deserialization of workspace comment events
Workspace comment change events did not serialize the `oldContents` property and workspace comment move events did not serialize the `oldCoordinate` property.
Workspace comment change events serializes `oldContents` property and workspace comment move events serializes the `oldCoordinate` property.
Adding comment move event tests tracked as part of #4577.

Include oldCoordinate and oldContents in ws comment event serialization

---

core/metrics_manager.js

n/a
Updates flyout metrics computation.
1. Switching between text and logic category flyouts in the playground and scrolling in them caused a weird "bump" behavior.
2. The horizontal scrollbar did not have enough padding to the left of the first block in the flyout, if that block was not a value block, when compared to master.
Expected:
Actual:
3. (on master) The left edge padding for a horizontal flyout is not adjusted if the first block is not a value block. 
4. (on master) The bottom edge padding for a vertical flyout and the left edge padding for a horizontal flyout is not scaled with zoom as it should.
1. Flyout scrolling now behaves as expected, without "bump" behavior.
2. Padding to the left of the first block in a horizontal flyout on develop is adjusted so that blocks with and …

Fix flyout scroll metrics

---

core/zoom_controls.js
tests/playground.html

n/a
Updates zoom reset logic to scroll to center after resetting zoom level.
Workspace doesn't scroll to center when zoom reset control is clicked.
Workspace scrolla to center when zoom reset control is clicked.
This behavior is consistent with how the zoom controls worked in previous releases.

Always scroll center on zoom reset

---

demos/blockfactory/workspacefactory/wfactory_init.js

See image. In the workspace factory in developer tools, when you select a block, the "make shadow" button should be enabled. it is not, because the event listener gives up because "Blockly.Event.Selected" does not exist.
See image. "make shadow" button does not work
"make shadow" button enables correctly
This behavior is also present on master, so this isn't a recent regression. The rest of developer tools still works fine.

update event type in blockly developer tools

---

core/block_svg.js
core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_image.js
core/field_multilineinput.js
core/field_number.js
core/mutator.js
core/rendered_connection.js
core/renderers/geras/drawer.js

This resolves an issue tracked internally in Google, since it relies on https://github.com/angular/clutz which is no longer kept up-to-date on GitHub.
Replace @private on overrides of @protected methods with @protected.
An upcoming change to emit private properties in Google's internal version of https://github.com/angular/clutz will otherwise break any TypeScript depending on these types. This is because TypeScript errors on overriding protected with private while Closure Compiler does not.
I believe this change is also generally reasonable to make since it doesn't make sense to narrow the visibility of a method when overridding.
none; this does not affect behavior.
no doc updates needed.
n/a

Stop overriding @protected methods with @private

---

scripts/gulpfiles/typings.js

Fixes #4546
Changes logic in typing script to check all directories in core and msg and use exclude paths instead of a list of include paths that need to be manually updated.
If a new folder was added to core, then this file would need to be updated manually.
If a new folder is added to core, the typing script does not need to be updated.
Reduces overhead for committing changes that edit the directory structure of source code in the repo.
Ran typings and checked the console output.

Add exclude paths as config for typings

---

package.json
scripts/package/node/core.js

This reverts #4573 due to issue google/blockly-samples#665.
Relies on jsdom version 16.
Relies on jsdom version 15.
It causes problems when running tests in blockly samples.
There is a follow up PR to ignore jsdom updates on dependabot.

Reverts #4573

---

scripts/gulpfiles/build_tasks.js

Sets the input language for the closure compiler to STABLE rather than pinning it to ES5.
Uncompiled code had to be written in ES5. 
The uncompressed library could be used in IE10 and IE11.
Uncompiled code can be written in ES6. 
The uncompressed library may not be loadable in IE10 and IE11.
Library modernization/catching up with the world.
Ran `npm test` and `npm test:compile:advanced`
Related doc changes that should follow on:
Clang-format made this a bit hard to read.
Lines I actually changed:
- In `compile`, `options.language_in = 'STABLE'`, instead of `ECMASCRIPT5_STRICT`.
- In `buildCompressed`. removed `language_in` from `options`
- In `buildAdvancedCompilationTest`, removed `language_in` from `options`.
This may also be the right time to remove the `build.py` script entirely. …

Change compilation language_in to STABLE

---

.eslintrc.json
core/utils/object.js
package.json

Gets rid of (erroneous) lint warnings about es6 methods.
- Stop using [eslint-plugin-es5](https://www.npmjs.com/package/eslint-plugin-es5)
- Remove from eslintrc
- Remove from package.json
- Warnings for use of es6 language constructs
- Erroneous warnings for use of Blockly's internal `startsWith` method.
No warnings for use of es6.
Prompted by #4764
The input language is now es6, compiled down to es5 in the build/compress pass.
Ran `npm run lint` locally.
Possibly need to change the style guide.
Another option is to turn off *some* of the rules that this plugin gives us (e.g. no-es6-methods) but leave others on. Here's the [list of rules](https://www.npmjs.com/package/eslint-plugin-es5#list-of-supported-rules).
We currently have the compiler set to not add polyfills for es6 features …

Remove rules forbidding es6

---

core/insertion_marker_manager.js

#4485
Adds better errors to the insertion marker managers so that people can figure out why their blocks are breaking.
Blockly should, in general, throw informative errors so that developers can have a smooth experience debugging their code.
1) Modified the controls_if block by removing the updateShape_ call from rebuildBlock_ and replacing it with the code from updateShape_
2) Modified the duplicated code to not create inputs/fields properly.
3) Observed how before uninformative errors were thrown, and now informative errors are thrown.
Tested on:

Add better error messages to insertion marker

---

core/events/events.js
tests/mocha/event_test.js

n/a
Updates event filter code to merge consecutive viewport change events.
ViewportChange events are not filtered.
VIewportChange events that happen quickly after each other are merged together.  
This filtering helps improve performance when workspace change listeners are listening for viewport change events.
Tested locally by linking to content-highlight plugin demo.
PR created to improve performance of content-highlight plugin created in https://github.com/google/blockly-samples/pull/675.

Merge consecutive viewport change events

---

core/block_dragger.js
core/gesture.js
core/interfaces/i_block_dragger.js

- Changes private --> protected
- Changes package --> public
- Formats the document using clang
- Breaks up larger functions to make overriding easier
- Renames block dragger methods to make them more generic in anticipation of a common i_dragger interface.

Update block dragger

---

core/connection.js
core/renderers/common/renderer.js
tests/mocha/connection_test.js

Closes #3656
Renames `lastConnectionInRow` and `singleConnection_` to better reflect what they're doing. But the main point of this was to add tests for `lastConnectionInRow`/`getPlaceForOrphanedOutput`.
No behavioral changes.
Before I can tackle #4826 I need to write tests for everything, this is part of that.
Manually tested all of the behavior documented by #3658 to ensure nothing changed.
Tested on:

Change lastConnectionInRow to getPlaceForOrphanedOutput

---

core/connection.js
core/renderers/common/renderer.js
tests/mocha/connection_test.js

Redux of #4831 that is actually against the correct branch.

Change lastConnectionInRow to getPlaceForOrphanedOutput - Take 2

---

core/field_number.js
demos/code/msg/en.js

toLocaleString results in a 4.6% performance penalty when loading the Spaghetti test in Playground.
This relates to issue #4105

Use String() over toLocaleString when possible

---

tests/mocha/connection_test.js
tests/mocha/event_test.js

n/a
- Removes extra teardown call in test
- Adds require to event test
- Console fills with logged errors from second teardown call when connection test is run
- event test throws error if `workspace_comment_test.js` is commented out in index.html
- no errors from connection test
- no errors from event test
Cleans up console log for mocha tests.
Ran tests.
Extra teardown call was introduced in https://github.com/google/blockly/pull/4853 but the automated tests check doesn't fail when there are `console.error` calls in teardown.

Fix error caused by extra teardown call

---

core/block.js
tests/mocha/block_test.js

Extra spaces should only be stripped from the inside of paren tokens.  Parens in strings (and other static content) should not be edited.

Fix removal of spaces near parens inside strings

---

core/flyout_horizontal.js
core/flyout_vertical.js

n/a
Fixes bug in Flyout `getClientRect` which causes simple Flyout to no longer function as a delete area.
Simple Flyout does not delete.
Simple Flyout can delete.
Fixes bug introduced by recent changes.
Manually testing in playground with simple flyout.

Fix bug in Flyout getClientRect

---

core/block_dragger.js
core/bubble_dragger.js

Revert accidental change in bubble dragger logic and reverts name change in block dragger helper.
From: https://github.com/google/blockly/pull/4886

Revert bubble dragger logic change and helper name change

---

.github/workflows/build.yml
tests/scripts/setup_osx_env.sh

~~This should fix the CI issue with PR #4812~~, and also does some preparatory work for #2114.
Update our CI configuration:
- Bump node.js versions: ~~remove v10 and~~ add v16, per https://nodejs.org/en/about/releases/
- Update the configuration for macOS, but leave it disabled for now.
Will be improved.

CI updates: bump node, prepare to reenable macOS

---

core/interfaces/i_positionable.js
core/trashcan.js
core/workspace_svg.js
core/zoom_controls.js

n/a
Makes the jsdoc type for `getBoundingRect` more accurate.
Adds support for other use cases:
- support of positionables that can be hidden (such as the `Flyout`, which is not yet a positionable).
- support for positionables that are meant to overlay the workspace and not affect the positioning of other positionables, such as `@blockly/workspace-search`.
Tested manually by making the `Trashcan` return `null` in `getBoundingRectangle` and observing how the zoom controls ignore the trashcan placment.

Update positionable jsdoc

---

.github/workflows/build.yml
package-lock.json
package.json
tests/generators/run_generators_in_browser.js
tests/mocha/run_mocha_tests_in_browser.js
tests/scripts/setup_osx_env.sh

This change also migrates the generator tests to run in Chrome instead of Firefox.
This PR uses the selenium-standalone-service module to automatically start and stop Selenium when running test cases, instead of the old commands in package.json to coordinate doing so. It also uses Chrome to run the generator tests (consistent with the Mocha tests) instead of Firefox.
`npm run test` would run the test suite, but hang and never terminate since it was blocking on a child Selenium process.
`npm run test` runs the test suite and terminates when it is done.
The test suite had to be manually stopped with ^C.
Change is to the test suite itself; ran the test suite and confirmed that all tests pass.

Use selenium-standalone-service to automatically start and stop Selenium when running the test suite.

---

core/utils/useragent.js

https://github.com/google/blockly/issues/4818
Updates user agent parsing to detect iPads posing as desktop Safari. Since iOS 13, non-mini iPads use the same user agent as desktop Safari. This change checks for multitouch (which doesn't exist on Macs) to distinguish iPads. I looked into using the desktop behavior (inline fields instead of a modal text field), but that appears to be bordering on infeasible due to mobile Safari playing games with calls to focus().
Editing values in text fields in blocks on an iPad running iOS 13 or greater with an external keyboard was not possible due to focus being lost as soon as the text field was tapped.
The standard modal text input dialog appears.
I have manually verified the fix on an iPad running iOS 14.6 with an external keyboard attached. I also …

Updated user agent parsing to detect iPads posing as desktop Safari.

---

core/block.js
tests/mocha/block_test.js

#4830 
Calling [`block.setFieldValue`](https://github.com/google/blockly/blob/master/core/block.js#L1121) without supplying the field name for the required second parameter results in the block's first unnamed field being set to the value of the first argument.  For example, calling it on a built-in `text_print` block replaces `print` with whatever the new value that's passed is.  Connected to this, calling [`block.getField`](https://github.com/google/blockly/blob/master/core/block.js#L1023) or [`block.getFieldValue`](https://github.com/google/blockly/blob/master/core/block.js#L1113) without supplying a name of the field (whose value) to get returns the block's first unnamed field (value). 
Calling [`block.getField`](https://github.com/google/blockly/blob/master/core/block.js#L1023) or …

Fix #4830 for getting/setting unnamed fields

---

core/shortcut_items.js

https://github.com/google/blockly/issues/4537
Prevents the default copy behavior when a block is copied; the default behavior caused Safari to beep due to the lack of a text selection.
Safari would beep when copying a block with Command C.
Safari copies the block silently.
Confirmed that entire test suite passes and that blocks can be copied/pasted using command/control C and V in Safari, Chrome and Firefox.

Prevent an error beep when copying blocks in Safari.

---

core/insertion_marker_manager.js

Fixes #2338.
I also looked at having workspace.clear delete any insertion marker, but there doesn’t appear to be a public API for this.  Shouldn’t matter, this should be sufficient.

Don’t hide insertion marker if it’s already gone

---

core/flyout_horizontal.js
core/flyout_vertical.js

https://github.com/google/blockly/issues/4912
Updates the delete areas when the flyout width changes.
Delete area bounds were not updated, so the width of the delete area did not align with the width of the flyout.
Delete area and flyout bounds are kept in sync.
Manually tested and confirmed all test suites pass.

Fixed bug that prevented delete areas from updating when flyout width changed.

---

core/toolbox/toolbox.js

Fixes https://github.com/google/blockly/issues/4811
- Adds property to toolbox to track visibility status.
- Checks if toolbox is visible in `getClientRect`
- Update drag targets when visibility changes
Toolbox area is still a delete area when invisible.
Toolbox area is not a delete area when invisible.
It is unexpected that the toolbox area is still a delete area when it is invisible.
Testing manually in playground by setting the toolbox visibility to false.
This is a bug that already existed in master. So it's a great sign that we can now easily fix this.

Update toolbox drag target when visibility changes

---

tests/mocha/.eslintrc.json
tests/mocha/registry_test.js
tests/mocha/test_helpers.js
tests/mocha/workspace_test.js

https://github.com/google/blockly/issues/4761
Refactors Mocha tests to use captureWarnings method from dev-tools instead of the old implementation in mocha/test_helpers.js
Mocha tests used their own version of the method.
Mocha tests use a common, shared version of the method.
Verified that all tests continue to pass.

Use captureWarning helper from dev-tools instead of mocha/test_helpers.js implementation

---

core/flyout_base.js
core/interfaces/i_component.js
core/toolbox/toolbox.js
core/trashcan.js
core/zoom_controls.js

n/a
Updates the registered component id for `zoom_controls`, `trashcan` and `toolbox`.
Since there is only ever one of each of these kinds of components, these ids do not need to be generated. 
These ids are easier to use to get the component by an external developer.
This change would mean that if someone wanted to have multiple of these kind of components, then they would need to change the ids of the two instances so that they would be unique (ids must be unique).
It might make sense to also add a constant for a default id for developers to use to get these components from the `ComponentManager`.

Update the registered component ids

---

core/field_angle.js
core/field_colour.js
core/field_dropdown.js
tests/mocha/field_colour_test.js

These functions have side effects and set all kinds of private fields.  It is misleading for them to do all that, then return the top-level element, for the caller to assign to a private field.

Remove return value from Field dropdownCreate_

---

core/contextmenu_items.js

Currently the ‘collapse’ option is always present, even if flagged off in the inject options.  This must have broken about a year ago.  Found while testing Blockly Games.

Honour option for collapse in context menu

---

core/block.js
core/block_svg.js
core/connection.js
core/insertion_marker_manager.js
core/rendered_connection.js
core/renderers/common/renderer.js
package-lock.json
package.json
tests/mocha/connection_test.js
tests/mocha/event_test.js

Closes #4826 
Changes the order of logic in connect_ so that the new child block is connected to its new parent before any orphans are dealt with. This ensures that we don't end up with erroneous connections if you have a custom connection checker that changes the type of the new child based on the type of the orphan.
Also refactors some related logic to make it (hopefully) more readable.
See #4826 for details related to the nominal connection checker plugin.
Tests were added separately in #4853 
Also did some smoke testing on the advanced playground, everything looked good.
Somehow while rebasing I managed to wrap Monica's changes #4877 into this commit.

Refactor connect logic

---

core/field_textinput.js

Currently the escape key fails to revert the value.  This is the inherited root of all type-in fields, including number and angle.
Fixes #4910

Fix escape key on all fields.

---

core/block_drag_surface.js
core/field_textinput.js
core/toolbox/category.js
core/utils/dom.js
core/workspace_drag_surface_svg.js

Fixes #4189.
Also use 0 instead of 0px, in accordance with the rest of Blockly and Google’s CSS style guide.

Group field edits together for undo/redo

---

core/workspace_svg.js

Problems with JsDoc generation. Trailing comma breaks everything.
Tested with `jsdoc core/workspace_svg.js` and no errors.
This needs to go in this release so that JsDocs can be generated correctly.

Fix Jsdoc by removing trailing comma

---

core/flyout_base.js
core/workspace_svg.js

https://github.com/google/blockly/issues/4931
Updates flyouts to listen for zoom events and re-render themselves so that their blocks reflect the new zoom level.
Zoom level changes are not reflected in an open flyout until a click occurs inside the flyout itself.
Zoom level changes are immediately reflected in an open flyout.
Manually verified and ensured all test suites pass.

Reflow flyouts when zoom level changes to keep block zoom level in sync.

---

core/workspace_svg.js

https://github.com/google/blockly/issues/4957
Adds a no-op event listener that works around a WebKit bug preventing listening to wheel events on an SVG <g> element.
The workspace could not be zoomed or scrolled in Safari.
Workspace zooming and scrolling works as expected in Safari.
Manually verified the fix in Safari and confirmed that behavior was unaffected in Firefox and Chrome.

Work around WebKit bug that prevents scrolling/zooming the workspace.

---

.github/workflows/appengine_deploy.yml
gulpfile.js
package.json
scripts/gulpfiles/appengine_tasks.js

https://github.com/google/blockly/issues/4988
- Adds a gulp action that prepares the demos but doesn't deploy or delete the directory
- Adds a github workflow with steps to prepare and deploy demos
Deploying had to be done manually.
Deploying will be done by clicking a button in github.
Automate tasks
Not yet tested
Internal documentation on how to release will need to be updated.
- I'm following [these steps](https://github.com/google-github-actions/deploy-appengine#setup) to use the deploy-appengine action. I need to set up a service account and some secrets before I can actually run this.
- I still need to set the version number based on package.json
- @cpcallen after your build changes are merged, I'll need to use them and make sure that I'm copying over the correct built files
- I'm …

Initial commit for appengine deploy action

---

.github/workflows/appengine_deploy.yml
gulpfile.js
package.json
scripts/gulpfiles/appengine_tasks.js

This is a version of https://github.com/google/blockly/pull/4998 against master so that the action is available to be triggered manually.

Appengine deploy workflow on master for testing

---

.github/workflows/appengine_deploy.yml

Previous path was `_deploy/`. New path is `../_deploy`.
The alternative is to change where the prepareDemos action places the files.

Get deploy files from the correct directory

---

.gitignore
scripts/gulpfiles/config.js
scripts/gulpfiles/package_tasks.js
scripts/gulpfiles/typings.js
typings/msg/bs.d.ts

- Fixes issue with msgTypings script when the `build/msg` folder is not present.
- Move the typings temporary directory so that it's in the new`build` directory.
- Group all typings files in the build directory under their own directory: `build/typings`.

Move typings output into their own directory under `build`

---

core/utils/object.js

In ES5 static methods on child classes don't inherit static methods on parent classes.  In ES6 they do.
For example, a new field in core (written in ES5) which doesn't define `.fromJson` will not have this method.  Whereas a new field in a plugin (written in ES6) which doesn't define `.fromJson` will inherit from `Blockly.FieldTextInput.fromJson` or `Blockly.FieldNumber.fromJson`
This change modifies our ES5 inheritance to be consistent with the ES6 pattern.

Enable static method inheritance.

---

core/flyout_horizontal.js

Fixes #4914.
Uses the height of flyout buttons in the calculation to find the height of the flyout.

Fix vertical button padding in horizontal flyout

---

core/block_drag_surface.js
core/field_textinput.js
core/toolbox/category.js
core/utils/dom.js
core/workspace_drag_surface_svg.js

Group field edits together for undo/redo (attempt #2)

---

msg/json/sv.json

Resolves #5017
Usually direct edits to the msg json files work just fine.  Occasionally such edits will get inadvertently reverted by translate wiki on their next push.  If this happens, then we make the edit again.  If it reverts a second time, then we ping them and ask them to pull it.
We have to reedit once every two years, and ping them about once every four years, so it's an acceptable solution in my opinion.  Not worth automating and creating more moving parts.

Remove undesirable \n from sv.json

---

.github/workflows/appengine_deploy.yml

Reverts google/blockly#5010
Relative locations are not allowed, so I'll need to change where the prepareDemos script puts files.

Revert "Get deploy files from the correct directory"

---

.eslintignore
scripts/gulpfiles/appengine_tasks.js
scripts/gulpfiles/build_tasks.js
scripts/gulpfiles/package_tasks.js

* Fixes possible Windows incompatibility (see #5000)
* Fixes issue with eslint tests failing due to (incorrectly) linting build output.
* Build depends on existence of `mkdir -p` command.
* `npm test` will fail if `npm run clean` (or `npm run clean:build`) isn't run first.
* Tests succeed even if build directory not cleaned first.

Build system changes cleanup

---

package-lock.json

Update `package-lock.json` from `lockfileVersion: 1` to `lockfileVersion: 2`.
Version 7 of `npm` does this automatically; as a consequence, most of the team are using `npm` v6 to avoid this update.  But I believe the update is harmless:
* `lockfileVersion: 2` is backward-compatible with `lockfileVersion: 1`, so `npm` v6 can work fine with new file (although it does print a warning, because it can't know that this file-format-from-the-futrure is fine).
* `npm` v7 is backwards compatible as far as `node.js` v10, so this update does not prevent anyone from using `npm` v7 with any of the older versions of `node.js` we wish to continue supporting.
Awaiting CI tests on GitHub.
You can update `npm` to the latest (v7.x) by running `npm install -g npm`.

Update package-lock.json to lockfileVersion 2

---

tests/mocha/gesture_test.js
tests/mocha/keydown_test.js
tests/mocha/test_helpers.js
tests/mocha/theme_test.js

n/a
Removes unused param `sharedCleanupObj` from test helpers. This parameter used to be necessary before `Blockly.defineBlocksWithJsonArray` was stubbed in tests.
Reduce confusion in test helpers and correct incorrect call in `keydown_test.js`.
One of the calls was also passing the incorrect object (in `keydown_test.js` undefined was being passed due to an incorrect assumption of scope). However, removing this param bypasses the need to fix that call.

Remove unused parameters from test helpers

---

core/block.js
tests/mocha/block_test.js

Throws error when attempting to set a block's parent to a non-null block `b` if `b` is `not` properly connected to it without changing state (i.e., if its previous/output connection is *not* connected to one of `b`'s input/next connections or when it doesn't have such connections).  Also throws error when attempting to set a block's parent to `null` if it has a connection to a superior block.
Setting a parent of a block already connected to some other superior block would remove the block from that old parent's child list before throwing, leading to potential rendering issues.  Setting the parent of a disconnected block could cause rendering issues and errors when attempting to delete that parent.
Errors are thrown in these cases without changing state so none of these problems ensue.
To …

Enforce connection preconditions for setParent

---

.eslintrc.json
scripts/gulpfiles/build_tasks.js

Configure eslint and Closure Compiler to accept ES6 input.
We are beginning the migration to ES6.

Configure eslint and Closure Compiler to accept ES6

---

core/utils/keycodes.js
tests/deps.js

Converts `core/utils/keycodes.js` to `goog.module` syntax. 
No instances of var to update.
No changes to the file after running clang-format.

Migrate core/utils/keycodes.js to goog.module

---

core/utils/deprecation.js
tests/deps.js

Converts `core/utils/deprecation.js` to `goog.module` syntax. 

Migrate core/utils/deprecation.js to goog.module syntax

---

core/utils/object.js
tests/deps.js

Converts `object.js` to `goog.module` syntax. 

Migrate object.js to goog.module syntax

---

.github/workflows/update_metadata.yml
tests/scripts/update_metadata.sh

https://github.com/google/blockly/issues/4977
Adds a script that calculates the size of the various Blockly JS files and updates check_metadata.sh with the new values.
As part of the release process, a developer would need to manually determine the build artifact sizes and update the check_metadata.sh script.
Running the workflow will automatically calculate the new build artifact sizes, update the script, and create a PR with the updated script.
Makes this step in the release process more reliable and reduces the effort on the part of the dev team.

Added script and workflow to automatically update build artifact sizes in check_metadata.sh

---

core/utils/idgenerator.js
tests/deps.js

Migrate core/utils/idgenerator.js to goog.module syntax

---

core/utils/math.js
tests/deps.js

Converts `core/utils/math.js` to `goog.module` syntax. 

Migrate core/utils/math.js to goog.module syntax

---

core/utils/svg_paths.js
tests/deps.js

Migrate core/utils/svg_paths.js to goog.module syntax

---

core/utils/rect.js
tests/deps.js

Part of #5026
Converts `FILENAME` to `goog.module` syntax. 

Migrate core/utils/rect.js to goog.module syntax

---

.github/PULL_REQUEST_TEMPLATE/goog_module.md

Provide a standard pull request template more suited to PRs doing
goog.module conversions.
Facilitate standardised PRs.
Migration guide in #5026 will be updated with instructions.
There's no way to pick a non-default template when creating a PR manually, but this one can be used by adding `&?template=goog_module.md` to the `https://github.com/cpcallen/bugs/compare/` URL.

Pull Request template for goog.module PRs

---

core/utils/colour.js
tests/deps.js

Converts `core/utils/colour.js` to `goog.module` syntax. 

Migrate core/utils/colour.js to goog.module syntax

---

core/utils/metrics.js
tests/deps.js

Part of #5026
Converts `core/utils/metrics.js` to `goog.module` syntax. 
No changes after running clang-format

Migrate core/utils/metrics.js to goog.module syntax

---

demos/code/code.js

Fixes #1949
Only bind one event listener depending on platform.
Code executes twice, one after the other because of the two event listeners bound to the "run" button.
Code executes only once.
Tested on chromium devtools mobile viewport mode, where the bug was also present.

Fix code in code demo executing twice on mobile

---

core/css.js
tests/deps.js

Part of #5026
Converts `core/css.js` to `goog.module` syntax.

Migrate core/css.js to goog.module syntax

---

core/connection_types.js
tests/deps.js

Part of #5026
Converts `core/connection_types.js` to `goog.module` syntax.

Migrate core/connection_types.js to goog.module syntax

---

core/utils/coordinate.js
tests/deps.js

Converts `core/utils/coordinate.js` to `goog.module` syntax. 
No changes after running clang-format on this file.

Migrate core/utils/coordinate.js to goog.module syntax

---

core/interfaces/i_block_dragger.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_block_dragger.js` to `goog.module` syntax.

Migrate core/interfaces/i_block_dragger.js to goog.module syntax

---

core/interfaces/i_bounded_element.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_bounded_element.js` to `goog.module` syntax.

Migrate core/interfaces/i_bounded_element.js to goog.module syntax

---

core/interfaces/i_component.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_component.js` to `goog.module` syntax.

Migrate core/interfaces/i_component.js to goog.module syntax

---

core/interfaces/i_deletable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_deletable.js` to `goog.module` syntax.

Migrate core/interfaces/i_deletable.js to goog.module

---

.github/workflows/tag_module_cleanup.yml

**Branched from goog_module because this is a workflow and that's where I want it to run.
Automates tagging and adding milestones. 
I looked into adding to the cleanup project but that API is less well specified.
I believe that this workflow should run against this PR when I create it.

Auto-tag and add milestones for cleanup PRs

---

tests/mocha/index.html
tests/mocha/serializer_test.js

Work on Project Cereal
Adds a suite for testing serializers, as outlined [here](https://docs.google.com/document/d/1Dbpezxsd4H1S0p31ncrZ1hLaMfFYBeanv8pqjkpxoHI/edit?resourcekey=0-hYVVlo828cnLmnlj30Lysg#heading=h.g8wz2wuda80j). Once we're sure that this suite covers enough cases, this will be moved into the [dev-tools test helpers](https://github.com/google/blockly-samples/tree/master/plugins/dev-tools/src) (probably around the end of my internship).
Currently this just tests that the XML round-trips correctly, but the idea is that you can plug in other serializers (including the JSON serializer).
Gives us confidence that the new JSON serializer will properly round-trip state. Also once this is a test helper it will make it easy for devs to test their custom serializers.
When this moves …

Adds a serializer test suite - project cereal

---

.github/workflows/tag_module_cleanup.yml

Uses the `pull_request_target` trigger instead of `pull_request`, in order to acquire the write permission to add labels.
References:
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- https://github.com/actions/labeler/issues/12

Use pull request target trigger for tagging cleanup

---

core/interfaces/i_delete_area.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_delete_area.js` to `goog.module` syntax.

Migrate core/interfaces/i_delete_area.js to goog.module syntax

---

core/interfaces/i_draggable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_draggable.js` to `goog.module` syntax.

Migrate core/interfaces/i_draggable.js to goog.module syntax

---

core/interfaces/i_copyable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_copyable.js` to `goog.module` syntax.

Migrate core/interfaces/i_copyable.js to goog.module syntax

---

core/interfaces/i_movable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_movable.js` to `goog.module` syntax.

Migrate core/interfaces/i_movable.js to goog.module

---

core/interfaces/i_styleable.js
tests/deps.js

Part of #5026
Converts `FILEPATH` to `goog.module` syntax.

Migrate core/interfaces/i_styleable.js to goog.module

---

core/connection_checker.js
tests/deps.js

Migrate core/connection_checker.js to goog.module

---

core/interfaces/i_positionable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_positionable.js` to `goog.module` syntax.

Migrate core/interfaces/i_positionable.js to goog.module syntax

---

core/interfaces/i_drag_target.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_drag_target.js` to `goog.module` syntax.

Migrate core/interfaces/i_drag_target.js to goog.module syntax

---

package.json

Problem observed when existence of a `public/` subdirectory in the repository root causes `http-server` to serve `./public` instead of `./`, resulting in `npm start` opening a browser window that immediately displays a 404 error.
Explicitly specify directory to be served by `http-server` in response to `npm start`.

Always have npm start serve the repository root

---

core/utils/style.js
tests/deps.js

Migrate core/utils/style.js to goog.module syntax

---

core/interfaces/i_bubble.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_bubble.js` to `goog.module` syntax.

Migrate core/interfaces/i_bubble.js to goog.module syntax

---

core/interfaces/i_selectable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_selectable.js` to `goog.module` syntax.

Migrate core/interfaces/i_selectable.js to goog.module syntax

---

core/interfaces/i_contextmenu.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_contextmenu.js` to `goog.module` syntax.

Migrate core/interfaces/i_contextmenu.js to goog.module syntax

---

core/interfaces/i_flyout.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_flyout.js` to `goog.module` syntax.

Migrate core/interfaces/i_flyout.js to goog.module syntax

---

core/interfaces/i_toolbox.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_toolbox.js` to `goog.module` syntax.

Migrate core/interfaces/i_toolbox.js to goog.module syntax

---

core/interfaces/i_autohideable.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_autohideable.js` to `goog.module` syntax.

Migrate core/interfaces/i_autohideable.js to goog.module syntax

---

.github/workflows/build.yml
core/block.js
tests/run_all_tests.sh

Currently all lint errors show up 4x, one per each version of Node we test with. This causes spam.
eslint will only be run if the CI environment variable is NOT set. When you run `npm run test` locally, linting will happen. When GitHub runs it in the build workflow, it will not be run. Instead, a separate action will run `npm run lint` and report lint errors only once.
4x lint error messages per error on PRs. 
1 lint error message per error on PRs.
Reduces lint spam.
Tested by adding and then reverting a lint error in this PR. Example run https://github.com/google/blockly/pull/5128/checks?sha=62affa59527dece39b22c6f657acaf1c96c7346c

Only lint once in CI

---

core/keyboard_nav/basic_cursor.js
tests/deps.js

Part of #5026
Converts `core/keyboard_nav/basic_cursor.js` to `goog.module` syntax.

Migrate core/keyboard_nav/basic_cursor.js to goog.module syntax

---

core/interfaces/i_connection_checker.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_connection_checker.js` to `goog.module` syntax.

Migrate core/interfaces/i_connection_checker.js to goog.module syntax

---

core/keyboard_nav/cursor.js
tests/deps.js

Part of #5026
Converts `core/keyboard_nav/cursor.js` to `goog.module` syntax.

Migrate core/keyboard_nav/cursor.js to goog.module syntax

---

core/block.js
core/extensions.js
core/field.js
tests/mocha/extensions_test.js

Link for Diff: https://github.com/BeksOmega/blockly/compare/tests/serialier...BeksOmega:cereal/basic-hooks
Work on project cereal.
Dependent on #5034 
Adds `saveState` and `loadState` to fields. These functions wrap the old `toXml` and `fromXml` functions for backwards compatibility (as suggested by Sam).
Adds `saveExtraState` and `loadExtraState` to blocks. These functions do *not* wrap `mutationToDom` and `domToMutation` because mixins don't allow that.
1) If we add default definitions to the block, the mixin function will throw errors when devs try to overwrite it.
2) If we mixin default definitions via the extensions logic then we don't have wrappers for mutators defined via JavaScript.
As such handling backwards compatibility will need to be done in the JSO serializer itself.
We want …

Add JSO hooks for blocks and fields.

---

core/utils/toolbox.js
tests/deps.js
tests/mocha/workspace_svg_test.js

Part of #5026
Converts `core/utils/toolbox.js` to `goog.module` syntax. 
This is failing [this](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/tests/mocha/workspace_svg_test.js#L115) test case. It is because `Blockly.utils.toolbox.parseToolboxTree` !== `parseToolbox`. I'm not entirely sure what to do about this. I tried updating the test, but couldn't find a way to require the module with the current set up.

Migrate core/utils/toolbox.js to goog.module syntax

---

scripts/goog_module/convert-file.sh

Tested on OSX and gLinux on `core/bubble.js`
```bash
$ ./scripts/goog_module/convert-file.sh -h
Conversion steps:
1. Use IDE to convert var to let/const
2. Rewrite the goog.provide statement as goog.module and explicitly enumerate exports
3. Rewrite goog.requires statements and add missing requires (often skipped for simple files)
4. Run clang-format on the whole file
Usage: ./scripts/goog_module/convert-file.sh [-h|-c <number>|-s <number>|-f] <filepath>
-h                      Display help
-c <step> <filepath>    Create a commit for the specified step [2-4]
-s <step> <filepath>    Run the specified step [1-4]
$ ./scripts/goog_module/convert-file.sh -s 2 core/bubble.js 
[INFO]: Verifying single goog.provide declarations...
[INFO]: Updating goog.provide declaration...
[INFO]: Extracting …
```

Add script for partially automating goog.module conversion steps

---

core/interfaces/i_collapsible_toolbox_item.js
core/interfaces/i_selectable_toolbox_item.js
core/interfaces/i_toolbox_item.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_toolbox_item.js` to `goog.module` syntax. 
This PR splits up `core/interfaces/i_toolbox_item.js` into multiple files for each interface that it provided.

Migrate core/interfaces/i_toolbox_item.js to goog.module syntax

---

scripts/goog_module/convert-file.sh

Fixes bugs for the following edge cases:
* No missing requires -  corrects logic for detecting missing requires by checking for non-empty string instead of counting lines for the regex match return
* Checks for overlapping requires, such as if `Blockly.utils` and `Blockly.utils.dom` are both required
* Checks for overlap with module name and require, such as if `Blockly` is a require

Fix edge cases for convert-script

---

core/keyboard_nav/tab_navigate_cursor.js
tests/deps.js

Part of #5026
Converts `core/keyboard_nav/tab_navigate_cursor.js` to `goog.module` syntax.

Migrate core/keyboard_nav/tab_navigate_cursor.js to goog.module syntax

---

core/interfaces/i_registrable_field.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_registrable_field.js` to `goog.module` syntax. 
https://github.com/google/blockly/issues/5124

Migrate core/interfaces/i_registrable_field.js to goog.module syntax

---

core/drag_target.js
tests/deps.js

Part of #5026
Converts `core/drag_target.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/drag_target.js to goog.module syntax

---

core/keyboard_nav/ast_node.js

Replacing check `instance of Blockly.Block` in order to fix circular dependency between `Blockly.Block` and `Blockly.ASTNode`.

Remove need for require instead of requireType for Block in ASTNode

---

demos/code/code.js

PR #5037 fixed double execution of the run button on mobile.  But the link button and other events still suffer from double execution.  This PR moves the fix from the run button to the central bind function so that it applies universally.

Fix double execution in Code demo

---

scripts/goog_module/convert-file.sh

This PR includes the following changes:
Functional changes:
* Adds support for passing filepath as second argument
* Removes unnecessary checks for arguments (arguments were already verified in parent call)
* Fixes typo for log at end of step 2 "step 3" > "step 2"
* Addresses possible bug with regex (L115)
* Simplifies regex on (L151)
* Updates formatting of list of missing requires to remove duplicates for a more readable error message (L202-L204)
Formatting/style changes:
* Adds main function
* Adds newlines and removes some extra spaces
* Adds extra square brackets to  single square bracket if statements to keep style consistent
* Adds `""` around variables like `${filepath}` to keep style consistent
* changes `! -z` to `-n` equivalent
* Removes unnecessary `$()` on L186

Convert files script cleanup

---

scripts/goog_module/convert-file.sh

This PR makes the following changes:
* Adds missing parentheses `()` for functions
* Adds missing indentation
* Fixes bug on L282 where incorrect variable was passed, causing issue with processing arguments passed in

Fix bug in convert-file script with processing arguments

---

package-lock.json

All of the dependabot changes have been stuck for a few days with cryptic errors. The internet suggests deleting and regenerating the package lock, which actually upgrades the dependency versions. I've done that here to see if it can kick dependabot back into working.
I kept eslint the same version so we'd have a test case for a dependabot version. But the mocha and generator tests also failed to run for me locally so I also kept webdriverio the same version.
So the versions changed are all the other ones in this list that are NOT major bumps: https://github.com/google/blockly/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies
@blockly/dev-tools, trim-newlines, etc
Tested with
npm run build
npm run start
npm run test
Tests intermittently fail with php generator errors, this seems unrelated. …

Update package-lock to try to unstick dependabot

---

core/interfaces/i_metrics_manager.js
tests/deps.js

Part of #5026
Converts `core/interfaces/i_metrics_manager.js` to `goog.module` syntax.

Migrate core/interfaces/i_metrics_manager.js to goog.module syntax

---

core/menu.js
tests/deps.js

Part of #5026
Converts `core/menu.js` to `goog.module` syntax.

Migrate core/menu.js to goog.module syntax

---

scripts/goog_module/convert-file.sh

Remove logic for deconstructing require and update logic so that it correctly handles instances like:
`Blockly.utils` and `Blockly.utils.dom` both being required (previously this only worked correctly if both were deconstructed)

Remove deconstructing properties and update logic

---

core/contextmenu_items.js
scripts/goog_module/convert-file.sh

* Add fixes to regex for convert-file script.
* Adds check for Blockly require before and warns instead of error for missing requires if Blockly was required

Apply fixes for convert-file script

---

core/marker_manager.js
tests/deps.js

Part of #5026
Converts `core/marker_manager.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/marker_manager.js to goog.module syntax

---

core/utils/size.js
tests/deps.js

Part of #5026
Converts `core/utils/size.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/utils/size.js to goog.module syntax

---

core/theme_manager.js
tests/deps.js

Part of #5026
Converts `core/theme_manager.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/theme_manager.js to goog.module syntax

---

scripts/goog_module/convert-file.sh

* Adds comment to top of file as reference for syntax used.
* Converts some `perl -nle` commands to a simplified `perl -ne` for commands that are used to extract only a single match
* Adds space to perl commands (`perl -nle'command'` => `perl -nle 'command'`)
* Removed an unnecessary `tr ' ' '\n'` that was noticed on L207 (old L172)

Add comment to top of convert-file script for reference to syntax used

---

core/warning.js
tests/deps.js

Part of #5026
Converts `core/warning.js` to `goog.module` syntax.

Migrate core/warning.js to goog.module syntax

---

core/keyboard_nav/ast_node.js
tests/deps.js

Part of #5026
Converts `core/keyboard_nav/ast_node.js` to `goog.module` syntax.

Migrate core/keyboard_nav/ast_node.js to goog.module syntax

---

core/keyboard_nav/marker.js
tests/deps.js

Part of #5026
Converts `core/keyboard_nav/marker.js` to `goog.module` syntax. 
This PR also adds missing nullability modifier to JsDoc, according to the [style guide](https://google.github.io/styleguide/jsguide.html#jsdoc-nullability).

Migrate core/keyboard_nav/marker.js to goog.module syntax

---

core/trashcan.js

Issue reported in https://groups.google.com/g/blockly/c/Wv38l8bwX5Q
This PR recalculates the drag targets of the main workspace when the trashcan flyout is closed.
With the continuous toolbox plugin, the region occupied by the trashcan flyout would remain an active delete region even once the flyout had closed.
The region previously occupied by the trashcan flyout is not a delete region once the flyout is closed.
The old behavior could cause the inadvertent deletion of blocks.
Verified that all tests continue to pass.

Fix issue where the trashcan flyout would remain an active delete region even when closed with the continuous toolbox plugin

---

scripts/goog_module/convert-file.sh

* Refactors logic in `step3` into 2 helper functions `getRequires` and `getPropertiesAccessed` (logic unchanged)
* Removes unecessary `if` statement 
* Adds additional comments for clarity on what is happening
* Changes logic in `step2` to loop through a specific list of properties instead of using a general regex so that non-leaf nodes, such as `Blockly.utils` is properly handled (script was tested on `core/utils.js`).
This does not add support for handling non-leaf nodes that are classes (does not seem to be any existing files that require this handling).
**Additional Context for reviewer:**
* `inf` and `err` are helper functions defined at the top of the file for logging
* The top of the file (L3-L37) contains an extra reference to perl and regex syntax used throughout this script

Add handling for converting modules that are not leaf nodes

---

scripts/goog_module/convert-file.sh

Updates logic in the method in covert-script used for getting the list of properties accessed on a module reference.
Additional Context:
- `(?<!)` is a negative lookbehind and `(?!\w)` is a negative lookahead used to ensure that there isn't a word character (`\w`) before or after the matched string to replace.

Add regex lookarounds to check for require overlaps

---

core/variable_model.js
tests/deps.js

Part of #5026
Converts `core/variable_model.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/variable_model.js to goog.module syntax

---

core/serialization/blocks.js
tests/mocha/jso_serialization_test.js

Link for Diff: https://github.com/BeksOmega/blockly/compare/cereal/block-serialization...BeksOmega:cereal/mutator-serialization
Work on project cereal.
Dependent on #5053 
Adds serialization of mutators on blocks. ~~Handles backwards compatibility with the XML hooks by converting them to a string before appending them to the JSO.~~ That was removed in favor of investigating upgrading developers' files directly using a script.
Does not handle deserialization.
Serializing state is good.
Added tests for the different categories of objects the save function could return. Also added a test for wrapping the `mutationToDom` hook.

Add serialization of mutators

---

core/utils/dom.js
tests/deps.js

Part of #5026
Updates unecessary `require` to `requireType` and adds eslint disable for line.

Fix eslint warning in core/utils/dom.js

---

core/variables_dynamic.js
tests/deps.js

Part of #5026
Converts `core/variables_dynamic.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/variables_dynamic.js to goog.module syntax

---

core/contextmenu_items.js
tests/deps.js

Part of #5026
Converts `core/contextmenu_items.js` to `goog.module` syntax.

Migrate core/contextmenu_items.js to goog.module syntax

---

core/renderers/common/i_path_object.js

Part of #5026
Adds missing eslint disable.
<!-- 
* ### Additional Information
* Un-comment and update this section if relevant.
* →

Add missing eslint disable to core/renderers/common/i_path_object.js

---

core/gesture.js

Part of #5026
Removes extra eslint disable.
<!-- 
* ### Additional Information
* Un-comment and update this section if relevant.
* →

Remove extra eslint disable from core/gesture.js

---

core/mutator.js

Fixes #5183
Updates the mutator workspace immediately when it is visible instead of waiting for the Blockly.Events.CREATE event to fire, since there is sometimes a delay between when the mutator workspace is set to visible and when the event is fired, which causes a visible shift in block position when such a delay occurs.
Also updated the workspaceChanged_ function so it does not continue execution of if the parameter event type is a Blockly.Events.CREATE event to avoid multiple calls when the mutator is set to visible. 
(May cause some issues though if the workspaceChanged_ listener is being used to initialise the mutator workspace elsewhere; doesn't seem like it but not sure)
Blocks will sometimes remain in their default position for a moment before moving to their correct positions. …

Fix Mutator editor block positions sometimes being out of place for an instant

---

core/events/events_marker_move.js
tests/deps.js

Part of #5026
Converts `core/events/events_marker_move.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/events/events_marker_move.js to goog.module syntax

---

core/menuitem.js
tests/deps.js

Part of #5026
Converts `core/menuitem.js` to `goog.module` syntax.

Migrate core/menuitem.js to goog.module syntax

---

blocks/logic.js
blocks/loops.js
core/block.js

The no-mutator version of the if/else block (playground - simple blocks) fails to set suppressPrefixSuffix, which means there are two prefix calls and two suffix calls.  All languages.  By contrast, the if/else block with the mutator only has one prefix and suffix call.
This PR adds a new JSON option to set this boolean.  Alternatively, this could be done by using an extension, rather than JSON.  I have no preference.
Issue #5268.

Add supressPrefixSuffix to if/else block

---

.github/workflows/tag_module_cleanup.yml

Fixes #5298
Instead of just using the update endpoint to set the labels to a single-item list, get the information about the issue and add the new label to the end of the existing list when updating the issue.
Note that I'm using update because I also want to set the milestone. An alternate approach would be two writes: one to set the milestone and one to add the label, using the addLabel endpoint.
Conflicts with the cla-bot because the cla: yes label is being removed.
Existing labels are left in place and the new label is added.
Watching bots fighting is kind of sad.

fix: update tag module workflow to add labels instead of setting one label

---

core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_label_serializable.js
core/field_multilineinput.js
core/field_number.js
core/field_textinput.js
core/field_variable.js
tests/mocha/field_angle_test.js
tests/mocha/field_checkbox_test.js
tests/mocha/field_colour_test.js
tests/mocha/field_dropdown_test.js
tests/mocha/field_label_serializable_test.js
tests/mocha/field_multilineinput_test.js
tests/mocha/field_number_test.js
tests/mocha/field_textinput_test.js
tests/mocha/field_variable_test.js
tests/mocha/serializer_test.js

Link for Diff: https://github.com/BeksOmega/blockly/compare/cereal/field-serialiation...BeksOmega:cereal/field-upgrades
Dependent on #5072 
Adds implementations of the new JSO serialization hooks to all of the built-in fields. Fields in blockly-samples will be handled later.
Added basic tests to ensure that fields serialize correctly. More edge cases are handled by the round-trip serializer tests.

feat: upgrade fields to use new JSO hooks

---

core/serialization/blocks.js
tests/mocha/serializer_test.js

Dependent on #5132 
Adds deserialization of blocks. This handles everything except icons (ie comments), because I'm going to investigate their serialization and deserialization separately. Namely, type, id, coords, attributes, extra state, fields, and children.
Does not handle initialization of the deserialized blocks.
Saving state is good.
Enabled all of the serializer tests for the JSO system except for icons, which aren't handled yet, and mutators, which aren't upgraded yet.

feat: add deserialization of JSO block state

---

core/events/events_abstract.js
tests/deps.js

Part of #5026
Converts `core/events/events_abstract.js` to `goog.module` syntax. 
Adds call to `goog.module.get` and uses `requireType` for dependency `Blockly.Workspace` in order to work around circular requires.

Migrate core/events/events_abstract.js to goog.module syntax

---

core/workspace.js

Part of #5026
Adds missing eslint disable line for interface required for `Blockly.Workspace`.

Add missing eslint disable line for required interface

---

core/serialization/blocks.js
tests/mocha/index.html
tests/mocha/jso_deserialization_test.js
tests/mocha/jso_serialization_test.js
tests/playground.html

Dependent on #5137 
Adds (hopefully) properly initializing blocks for rendered workspaces, and firing block create events. Note that variable events are already [fired by the variable model](https://github.com/google/blockly/blob/64188ae27297b1ca23a3244cc987dfbfc6e98f34/core/variable_model.js#L69).
This also modifies the playground (not the advanced playground) to use JSO serialization for testing.
Properly rendering blocks is important. Also being consistent with our events system.
Added tests for properly firing events. If you have recommendations for testing the other parts of initialization I'd love to do that as well!
NOTE FOR REVIEWERS: Please look over the logic in [domToBlock](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/cor …

feat: add initialization of blocks and event firing

---

tests/generators/run_generators_in_browser.js
tests/mocha/run_mocha_tests_in_browser.js

This PR adds the --disable-gpu flag to the run mocha/generator test scripts, which works around an issue where Chrome would hang when running the tests on Linux with older versions of the NVIDIA driver.
This fixes https://github.com/google/blockly/issues/5345.

Fix issue that prevented Mocha and generator tests from running on certain configurations

---

core/variables.js
tests/deps.js
tests/mocha/field_variable_test.js

Part of #5026
Converts `core/variables.js` to `goog.module` with ES6 `const`/`let`.
This uses the approach outlined in https://github.com/google/blockly/issues/5199 to export a function in order to make it mockable by the unit tests.

Migrate core/variables.js to goog.module syntax

---

scripts/gulpfiles/typings.js

Removes most of the output from `npm run typings` unless you call `npm run typings -- --verbose`
Lots of useless output during `npm run test` (2 lines for every single file)
No useless output unless you actually want to see it, and pass the `--verbose` flag
I got tired of scrolling through a lot of output I didn't care about after running `npm run test`.
I didn't really know where to document this flag. I did pick the same flag that is used in eg `npm run build -- --verbose`. It doesn't look like our gulp commands really come with help descriptions and I don't know that much about gulp but if you have any ideas about where to document this, I can add it.
I don't know of a scenario where we wouldn't want to suppress this output. I added a bunch of obvious type errors:
* @type …

Quiet the typings script unless you tell it to be verbose.

---

core/utils/string.js
tests/deps.js

Migrate core/utils/string.js to goog.module syntax

---

core/renderers/zelos/info.js

Fixes #5170
Use the zelos.StatementInput function to handle statements in addInput_ instead of the blockRendering.StatementInput function used by the superclass' addInput_.
Blockly.zelos.StatementInput was unused and is required to correctly render using Zelos.
Chromium and Firefox on Ubuntu 21.04

Fix blocks with no next connections overlapping statement input in Zelos

---

core/serialization/blocks.js
tests/mocha/jso_serialization_test.js
tests/mocha/serializer_test.js

Dependent on #5200
Adds round-tripping comments.
Saving state is good.
Added tests to ensure that comments are serializing to the form we expect. Also enabled serializer (round-trip) tests.

feat: add serialization and deserialization of comments

---

core/theme/zelos.js
tests/deps.js

Part of #5026
Converts `core/theme/zelos.js` to `goog.module` syntax.

Migrate core/theme/zelos.js to goog.module syntax

---

core/theme/classic.js
tests/deps.js

Part of #5026
Converts `core/theme/classic.js` to `goog.module` syntax.

Migrate core/theme/classic.js to goog.module syntax

---

core/connection.js
core/rendered_connection.js
core/serialization/blocks.js
tests/mocha/connection_test.js
tests/mocha/jso_deserialization_test.js
tests/mocha/jso_serialization_test.js

Link for Diff: https://github.com/BeksOmega/blockly/compare/cereal/comments...BeksOmega:cereal/shadows
Dependent on #5216
Makes it so that shadow blocks are encoded as JSOs rather than stringified XML when using the JSO serialization system.
Stringified XML takes up more space than the normal JSO representation.
Added tests to make sure that the new setShadowState hook works correctly, and that the state serializes to XML and JSO properly, regardless of whether you use the setShadowDom or setShadowState hooks.
Also adds two simple tests for recycling vs not recycling blocks.

Add serializing shadows as JSOs for the JSO system

---

core/utils/svg.js
tests/deps.js

Part of #5026
Converts `core/utils/svg.js` to `goog.module` syntax. 
Considered exporting properties directory instead of as static properties on the `Blockly.utils.Svg` class (and not export the class), but found that the class `Blockly.utils.Svg` is used outside of this module, as a type, and must be exported.

Migrate core/utils/svg.js to goog.module syntax

---

core/utils/global.js
tests/deps.js

Part of #5026
Converts `core/utils/global.js` to `goog.module` syntax.

Migrate core/utils/global.js to goog.module syntax

---

core/events/block_events.js
core/field.js
core/insertion_marker_manager.js
core/mutator.js
tests/mocha/.eslintrc.json
tests/mocha/block_change_event_test.js
tests/mocha/index.html
tests/mocha/mutator_test.js
tests/mocha/test_helpers.js

Updates the logic for insertion markers and change events to properly handle JSO serialization hooks.
Bugs are bad.
* Added tests for mutators properly firing (or not firing) events. 
* Added tests for undoing and redoing mutator change events, for both XML and JSO hooks
* Manually tested that insertion markers are properly constructed for blocks with XML hooks, JSO hooks, or both.

fix: insertion markers and change events to work with JSO hooks

---

core/connection.js
tests/mocha/connection_test.js

Work on #4847 
Dependent on #5313 
Adds errors which are thrown when a connection attempts to connect to a shadow which it cannot connect to. This can occur programmatically, or because of loading serialized state.
Inform devs when something goes wrong, and signal that the workspace is in an invalid state.
Tests for all of the different error situations.

feat: add throwing errors for bad shadows

---

core/connection.js
core/serialization/blocks.js
tests/mocha/block_change_event_test.js
tests/mocha/block_create_event_test.js
tests/mocha/index.html

I discovered a problem with the project-cereal branch, where if you followed the below steps, you would end up with an extra block on the workspace:
1) Load the following JSON into the workspace:
```json
{
"blocks": {
"languageVersion": 0,
"blocks": [
{
"type": "text_print",
"inputs": {
"TEXT": {
"shadow": {
"type": "text",
"fields": {
"TEXT": "abc"
}
},
"block": {
"type": "text",
"fields": {
"TEXT": ""
}
}
}
}
}
]
}
}
```
2) Disconnect the text block from the print block.
3) Undo the disconnection (using keyboard shortcuts).
4) Redo the disconnection (using keyboard shortcuts).
5) Observe how you end up with two text blocks instead of just one.
This was occurring because the event for creating the shadow had `recordUndo` enabled when it should not have, because of …

fix: redo disconnect from shadow bug

---

core/workspace_svg.js

Fixes #4993.
Also check if the command key has been pressed on mac devices when deciding if the user is able to zoom. 
The workspace can't be zoomed when the command key is pressed and the mouse wheel is scrolled (when move with wheel is enabled).
The command key can be used to zoom.
Tested on:
- OS: macOS 11.4, Ubuntu 21.04 (to check that zoom doesn't work with the super key)
Browsers:
- Google Chrome on macOS
- Safari on macOS
- Chromium on Ubuntu

Allow command key zoom on mac devices

---

scripts/migration/renamings.js

Part of #5026.
Create a file `scripts/migration/renamings.js` to collect information about renamed API entries.  Start by filling it with the renamings already done to blockly.js.
This will be consumed by a script to be written in the blockly-samples repo that will assist users in automatically updating references to parts of the Blockly API that we have renamed.
The exact file format is not fully finalised (nor documented), but the entries added so far should be reasonably self-explanatory.  Details not fully decided yet include:
* Is having the old version number as the main key the best way to organise the file?
* How should this file indicat that the default export has been given a name (in that module or another)?
* …

Create `scripts/migration/renamings.js` to collect information about renamed API entries

---

core/serialization/blocks.js
tests/mocha/jso_serialization_test.js

Fixes serializing shadows that have been edited and not overwritten.
Added tests for serializing shadows that have been edited.

fix: serializing edited shadows

---

core/field.js
core/field_angle.js
core/field_checkbox.js
core/field_colour.js
core/field_dropdown.js
core/field_label_serializable.js
core/field_multilineinput.js
core/field_number.js
core/field_textinput.js
core/field_variable.js
core/serialization/blocks.js
tests/mocha/field_test.js
tests/mocha/jso_deserialization_test.js
tests/mocha/jso_serialization_test.js

Changes the JSO system to automatically convert values returned from XML hooks to strings, so that the data can be encoded in the JSO state.
This allows us to serialize and deserialize blocks/fields that were built for the XML system using the JSO system. This will in turn allow us to move copy paste, the flyout, shadows, etc to the JSO system without breaking people.
No breaking people!
Added tests for all of the following cases, for both serialization and deserialization, for both systems:
* A field with no overrides.
* A field with XML hooks.
* A field with XML hooks that calls super.
* A field with JSO hooks.
* A field with JSO hooks that calls super.
* A field with both sets of hooks.
To clarify for Christopher: Yesterday when we discussed this plan, we were …

fix: cereal backwards compatibility

---

core/block_svg.js
core/blockly.js
core/interfaces/i_copyable.js
core/workspace_comment_svg.js
core/workspace_svg.js

Fixes copying and pasting blocks with different sets of serialization hooks.
* Tested copying and pasting blocks with different sets of hooks using the blocks from https://github.com/google/blockly-samples/pull/875
* Tested that workspace comments can be duplicated.
* Tested that the instance limit for blocks is still respected.

fix: copy paste with json system

---

core/flyout_base.js
core/serialization/blocks.js
tests/playground.html

1) Fixes a blocks not being positioned correctly in the flyout
2) Dragging blocks/fields out of the flyout that only have XML hooks
Tested dragging blocks/fields that only have XML hooks out of the flyout using https://github.com/google/blockly-samples/pull/875

fix: dragging blocks from the flyout that only have XML hooks

---

core/utils/useragent.js
tests/deps.js

Part of #5026
Converts `core/utils/useragent.js` to `goog.module` with ES6 `const`/`let`.

Migrate core/utils/useragent.js to goog.module syntax

---

core/workspace_svg.js

Clarifies the JSDoc for centerOnBlock to document the behavior noted in #5432.

Note behavior of centerOnBlock when block is part of a stack in the JSDoc

---

core/serialization/blocks.js

* Fixes block positions for RTL
* Tested saving in RTL and then loading into RTL. Position is now the same.
* Tested saving in LTR and then loading into RTL. Position is now the same relative to the toolbox.

fix: loading blocks in RTL

---

core/workspace.js

Issue Fix #5374 
This PR fixes the issue #5374, Filtering out the insertion marker in the function [getsBlockByType](https://github.com/google/blockly/blob/f94b1db85018b5a7261fa01f7d04cd5c8367fe2c/core/workspace.js#L257) will fix the issue.
As @kvanthienen stated-
When the maxInstances option is set for a block (for example to 5), the corresponding block in the toolbox gets the 'blocklyDisabled' class after all the instances have been used in the workspace as expected.
The strange thing, however, is that this block already temporarily gets the 'blocklyDisabled' status while dragging around the second-last block on the workspace (for example block number 4). When the block is released, the status is flipped again.
This is a short term fix where blocks which are not real ` Insertion marker …

maxInstance fix

---

core/events/block_events.js
core/trashcan.js
tests/mocha/event_test.js
tests/mocha/jso_deserialization_test.js
tests/mocha/test_helpers.js
tests/mocha/trashcan_test.js

* Fixes undoing and redoing copy and paste events for blocks with JSON hooks.
* Fixes adding blocks with JSON hooks to the trashcan.
Using the blocks from https://github.com/google/blockly-samples/pull/875
* Tested undoing and redoing create events
* Tested undoing and redoing delete events
* Tested adding blocks to the trashcan

fix: create and delete events, and the trashcan

---

core/block.js
core/field.js
core/field_variable.js
core/flyout_base.js
core/serialization/blocks.js
tests/mocha/field_variable_test.js
tests/mocha/jso_serialization_test.js

Fixes dragging blocks containing variables from the flyout. Before variables would not be created properly because the serialized state of the block only stores the ID. So any variable fields would have the default name of `i`.
This manually creates an variables before the block is dragged from the flyout to ensure this doesn't happen.
An alternative fix would be to serialize all of the attributes of the variable referenced by the variable field, but that is such an incredible duplication of data I couldn't bring myself to do that.
* Tested dragging the variable field test block from the flyout.
* Tested dragging some list blocks from the flyout (which reference variables).

fix: dragging variables from flyout

---

core/msg.js
tests/deps.js

Part of #5026
Converts `core/msg.js` to `goog.module` with ES6 `const`/`let`.
There is some doubt about whether this PR will cause issues with localisation because:
* The `exports` object of a `goog.module` gets frozen upon being loaded.
* This will prevent any additional properties from being added to it.
* `msg.js` doesn't actually add any message properties to it at all.
* How is the playground successfully loading messages after the fact?
* Will this continue to work with advanced compilation?

Migrate core/msg.js to goog.module syntax

---

core/browser_events.js
core/msg.js
core/touch.js
core/utils.js
core/utils/global.js
core/utils/useragent.js
core/workspace_audio.js
generators/javascript.js
scripts/migration/renamings.js
scripts/package/node/core.js
tests/deps.js

Part of #5153
Converts `core/global.js` to named exports.
This is part of #5153 but is being prioritised because we want remove
the `declareLegacyNamespace` calls from the `core/utils/*.js` modules and
doing so results in the `exports` object of this module being passed to
`Object.freeze` - which fails on the global object, which can't be made
non-extensible!
The new name chosen for the former default export is `globalThis`, since
it is intended to have the same value as the global variable of that
name; see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Migrate `core/global.js` to named exports

---

core/utils/xml.js
tests/deps.js

Part of #5026
Converts `core/utils/xml.js` to `goog.module` with ES6 `const`/`let`.
The `.documents` export is monkey-patched in `scripts/package/node/core.js`; removing this monkey-patching will be addressed in a separate PR.

Migrate core/utils/xml.js to goog.module syntax

---

core/utils/xml.js
scripts/migration/renamings.js
scripts/package/node/core.js
tests/deps.js

Part of #5026
* Rename the `Blockly.utils.xml.document` export to `getDocument` (this function already had that as its internal name), and have it return a new module-global variable `xmlDocument`.
* Introduce a `.setDocument` export that sets `xmlDocument`.
* Call `.setDocument` instead of monkey-patching `.getDocument` in `scripts/package/node/core.js` (which becomes part of the `blockly` package).
* Also clean up the code around this location a little.
Monkey-patching (i.e., modifying exported properties from another module) is contrary to the style guide and is generally to be avoided wherever possible.
Ran `npm test`.
An entry has been added to `scripts/migration/renamings.js` for `document` -> `getDocument`.

Don't monkey-patch `Blocky.utils.xml.document` in node module 

---

core/blockly.js
core/toolbox/category.js
core/utils/colour.js
demos/blockfactory/workspacefactory/wfactory_controller.js
demos/blockfactory/workspacefactory/wfactory_init.js
tests/deps.js

Part of #5208
This PR migrates Blockly.hueToHex to Blockly.utils.colour.hueToHex and updates core and demos to use the new function.

Migrate Blockly.hueToHex to Blockly.utils.colour.hueToHex

---

.github/workflows/build.yml
package-lock.json

We were having problems 
Applies a [work around](https://github.com/actions/setup-node/issues/214#issuecomment-810829250) maribeth found.
Npm install on CI was breaking.
Npm install now works.
We don't' know why it just started failing. But we got the following failure when trying to install:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/fivetran/doctrine.git
```

fix: adds a fix for npm install failing

---

scripts/migration/renamings.js

Part of #5208
Adds records of renaming Blockly.alert, Blockly.confirm, Blockly.prompt and Blockly.hueToHex to renamings.js. Also adds a comment about hideChaff, but since that's not strictly a rename (minor change in semantics and moving onto the WorkspaceSvg class) I did not include an actual rename record.

Note Blockly.alert/confirm/prompt/hueToHex/hideChaff migrations in renamings.js

---

scripts/gulpfiles/build_tasks.js

#5039
Updating this flag caused the following changes in the compressed files:
**Old**
blockly_compressed: **795798**
blockly_compressed.js.gz: **151736**
**New**
blockly_compressed: **800683**
blockly_compressed.js.gz: **153167**
**Deltas** 
blockly_compressed: **4885** (~5kb)
blockly_compressed.js.gz: **1431**(~1.5kb)
**Note**: this is for about 6 polyfills(as far as I could tell). As we increase the number of methods that need polyfills, the size will increase. 
**How I tested?** 
- Changed the flag in the `build_tasks.js` file
- `npm run build`
- `./tests/scripts/check_metadata.sh` to get the new size.

chore: sets polyfill flag to true

---

blockly_uncompressed.js

Fixes #5103
Since the only part of the Closure Library we have is `closure/goog/base.js`, set the global `CLOSURE_NO_DEPS` flag to prevent it from trying to load `deps.js` from the same directory.
We already load our own dependency graph from `tests/deps.js`.

fix: Prevent request of (non-existent) closure/goog/deps.js

---

core/events/events.js
core/extensions.js
core/registry.js
tests/mocha/block_test.js
tests/mocha/extensions_test.js
tests/mocha/field_registry_test.js
tests/mocha/logic_ternary_test.js
tests/mocha/test_helpers.js
tests/mocha/theme_test.js

#5135
This PR addresses exported private fields and methods in Blockly. They have been resolved as follows:
* `Blockly.Events.disabled_` -> Removed, and tests rewritten to use public API to accomplish the same thing
* `Blockly.Events.FIRE_QUEUE_`, `Blockly.Events.fireNow()` -> Moved into TEST_ONLY export and tests updated accordingly
* `Blockly.Extensions.ALL_` -> Moved into TEST_ONLY export (as allExtensions) and tests updated accordingly
* `Blockly.registry.typeMap_` -> Moved into TEST_ONLY export and tests updated accordingly
Because all these private exports were used exclusively in tests, I did not include deprecation wrappers; if we have reason to …

Make several exported private fields/methods TEST_ONLY

---

package-lock.json
package.json

Updates the dev tools dependency to 2.6.1. We were previously using the beta version as a stand in until the 2.6.1 version was updated.

chore: update dev tools dev dependency

---

core/blockly.js
core/css.js
core/events/events.js
core/extensions.js
core/procedures.js
core/serialization/priorities.js
core/tooltip.js
core/utils.js
core/utils/aria.js
core/utils/colour.js
core/utils/deprecation.js
core/utils/dom.js
core/utils/idgenerator.js
core/utils/keycodes.js
core/utils/math.js
core/utils/object.js
core/utils/string.js
core/utils/style.js
core/utils/svg_paths.js
core/utils/toolbox.js
core/utils/useragent.js
core/utils/xml.js
core/variables.js
core/widgetdiv.js

Adds @alias JSDoc annotations to fix generation of JSDoc for modules that do not include a class declaration.

fix: JSDoc generation for modules without classes

---

core/inject.js
tests/mocha/block_test.js
tests/mocha/comment_test.js
tests/mocha/field_registry_test.js
tests/mocha/field_test.js
tests/mocha/generator_test.js
tests/mocha/registry_test.js
tests/mocha/trashcan_test.js
tests/mocha/workspace_helpers.js
tests/mocha/xml_test.js

Fixes https://github.com/google/blockly/issues/5029
Part of https://github.com/google/blockly/issues/4194
- Updates `inject.js` to use non-deprecated method
- Various updates to tests to prevent warnings from being logged
- Removes unnecessary stubs due to https://github.com/google/blockly/issues/4186 and https://github.com/google/blockly/issues/4197 being fixed

fix: Cleanup warnings logged by mocha tests

---

core/serialization/blocks.js

Fixes typo paramters -> parameters

Fix typo in Blockly.serialization.blocks

---

core/blockly.js

Issue with accessor properties (e.g. `Blockly.selected`) not being copied from the `exports` object of the`Blockly` module to the `Blockly` namespace object in the global scope.
Copy them explicitly.
See implementation of `goog.exportPath_` in `closure/goog/base.js` for why this is necessary (and note that `globalThis.Blockly` will have been pre-created by any dependency of `blockly.js` with a `declareLegacyNamespace` call, or failing that, by the hack in `core/msg.js`.
Once the `declareLegacyNamespace call has been removed from `core/blockly.js`—which entails all users of the `Blockly` module require it via something equivalent to `const Blockly = goog.require('Blockly');`—then `goog.exportPath_` will never be invoked …

fix: Add hack to copy accessors to global Blockly namespace object

---

core/flyout_base.js

Fixes #5545 
Uses `moveTo` instead of `moveBy` when positioning blocks dragged from the flyout.
In the XML system `domToBlock` positions blocks at (0, 0) regardless of whether the workspace is RTL or LTR, while `workspaceToDom` positions blocks correctly, by mirroring the X coordinate in RTL mode.
The JSON system always places blocks correctly (from `blocks.append` and `workspaces.load`), which causes an issue when flyouts assume that blocks will be initially positioned at (0, 0).
Changing the code to use `moveTo` instead of `moveBy` removes this assumption, making the flyout code work properly once again.
Tested on:

fix: blocks dragged from RTL flyout being incorrectly positioned

---

core/blockly.js
core/contextmenu.js
core/events/events.js
core/events/utils.js
core/generator.js
core/renderers/common/block_rendering.js
core/renderers/common/debug.js
core/tooltip.js
core/widgetdiv.js

* Revert removal of documentation for get/set accessors in #5549 (but still work around the compiler bug that caused #5538!)
* Use @name to attach JSDocs to get/set accessors.
* Restore documentation for deprecated properties that was lost when they were converted to accessors.
* Remove duplicate @Package declarations
* Improve generated JSDocs.
* Provide model for how to document accessor properties in future.
* Passes `npm test`.
* Cursory manual checking of locally-generated `jsdoc` output.

JSDoc improvments for accessors, etc.

---

core/workspace_svg.js

#5553 
Fixes copy-paste and duplicate not positioning the block correctly in RTL mode.
The copy paste code is really wacky and needs to be cleaned. But since it's public changing the behavior would require breaking changes, so I've just put a fix in for now.
In the past the block would convert itself to XML inside [toCopyData](https://github.com/google/blockly/blob/0ac360f163ae4ea35af8f997edd92310b6c602cb/core/block_svg.js#L958), but instead of using domToBlockWithXY it would use domToBlock and add the XY itself. Confusingly, it would make it's [X coordinate negative in RTL](https://github.com/google/blockly/blob/0ac360f163ae4ea35af8f997edd92310b6c602cb/core/block_svg.js#L967) (even though that's not the proper way to handle RTL0 only for it to be [converted back to …

fix: RTL copy-paste and duplicate

---

demos/blockfactory/factory.js

Fixes #5556
Rewrite code that previews user-created blocks to modify the contents of, rather than entirely replace the `Blockly.Blocks` object—which no longer works.
The following error appeared in the console:
```
TypeError: Unknown block type: block_type
at BlockSvg.Block (block.js:213)
at new BlockSvg (block_svg.js:149)
at module$exports$Blockly$WorkspaceSvg.newBlock (workspace_svg.js:1045)
at Object.BlockFactory.updatePreview (factory.js:223)
at BlockFactory.updateLanguage (factory.js:143)
at module$exports$Blockly$WorkspaceSvg.module$exports$Blockly$Workspace.fireChangeListener (workspace.js:694)
at module$contents$Blockly$Events$utils_fireNow (utils.js:337)
```
and the preview workspace remained blank.
Error shown above does not appear; block preview does.
Fix bug caused by #5026 …

fix: Fix Block Factory preview workspace

---

tests/scripts/update_metadata.sh

#5463
Works around incompatibility between macOS and Linux `sed` (https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed/131940#131940) and macOS's `date` command's lack of support for the %Q year-quarter date format specifier.
`update_metadata.sh` fails on macOS
`update_metadata.sh` works on macOS

fix: Make update_metadata.sh work on macOS

---

core/field_dropdown.js

Fixes #4933.
Clear the content of the dropdown div before rendering new elements to prevent the elements from being added "on top" of the pre-existing elements (in this very specific use case).
https://user-images.githubusercontent.com/57055412/132082732-d1222893-7935-4bcf-9c84-826d8d688354.mp4
https://user-images.githubusercontent.com/57055412/132082733-f6426d52-efd8-44f0-919d-e0b48310464f.mp4
- Chromium on Ubuntu 21.04
- Firefox on Ubuntu 21.04

Fix options list being repeated when showEditor is programmatically called repeatedly

---

.github/dependabot.yml

Related to conventional commit work.
Updates our dependabot config to add the prefix "chore(deps)" to dependabot PRs, and to add the label "chore" in addition to the label "dependencies".
Allows dependabot-generated changes to pass conventional commit linting.
Part of getting our labels sorted out so we can autogenerate informational release notes.
See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#commit-message
I *think* this will actually add the prefix with a colon, but I'm not 100% certain and can't find it either way in the docs.

chore: update dependabot messages and labels

---

generators/python/colour.js
generators/python/lists.js
generators/python/logic.js
generators/python/loops.js
generators/python/math.js
generators/python/procedures.js
generators/python/text.js
generators/python/variables.js
tests/deps.mocha.js

Updates python block generators to `const` and `let` in preparation for modularization. (Part of https://github.com/google/blockly/issues/5598)
Replace `var` with `const` and `let`. Where needed, restructure code that was relying on hoisting and multiple declarations of a variable.
No change.
Tested by generator tests.

chore: replace var with const and let in python block generators

---

generators/javascript.js
generators/lua.js
generators/php.js
generators/python.js

Updates javascript, lua, php, and python generators to `const` and `let` in preparation for modularization. (Part of https://github.com/google/blockly/issues/5598)
Replace `var` with `const` and `let`. Where needed, restructure code that was relying on hoisting and multiple declarations of a variable.
No change.
Tested by generator tests.

chore: update language generators to const and let

---

core/block.js
core/extensions.js
core/field_dropdown.js
core/input.js
core/utils.js
generators/dart/logic.js
generators/javascript/logic.js
generators/lua/logic.js
generators/php/logic.js
generators/python/logic.js

There are only 10 instances of ++x in our codebase (not counting places where the return value is used), compared with over 500 instances of x++.  The style guide has no opinion on which to use, nor do I.  But the lack of consistency is making regex searches for bugs more difficult.

chore: Normalize ++x to x++.

---

.github/dependabot.yml

[Error comments from dependabot](https://github.com/google/blockly/pull/5658#issuecomment-956413784): "The following labels could not be found: `chore`, `dependencies`."
Label all dependabot PRs as "PR: dependencies", following
@rachel-fenichel's recent rationalisation of issue/PR labels.
Kind of hard to test in advance, really…  Please proofread my change carefully.

chore: Update dependabot labelling config

---

.github/workflows/check_clang_format.yml

Part of #5659.
Do not attempt to post comments from this workflow.
A PR with clang-format issues would fail the check, but the failure would manifest itself as an `Resource not accessible by integration` error caused by insufficient permissions to post a comment on the PR.
A PR with a clang-format issue should fail this check but no other errors should occur (and no comment should be posted).
The check-clang-format workflow needs to be split into two parts: one that checks out the submitted code, and a separate one which has permission to post a comment.  See #5659 for more information.
I created draft PR #5667 to test this, but that PR appears to be 404, most probably due to @cpcallen-test being flagged.  
Then @alschmiedt created PR 5668 which verified that this change worked as …

fix: Don't crash when unable to post comment to PR

---

.github/workflows/report_clang_format.yml

Part of #5659.
The initial version of this workflow just uses `console.log` to report the context of the `context` object.  It is hoped that there will be enough information in this context to identify the PR to comment on, without the `check_clang_format` workflow having to upload a 'build artefact' of some kind - see example of what I hope to avoid [starting at `ReceivePR.yml` here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
A follow-up PR will (if possible) add the code to create comments when `check_clang_format` fails.
The check-clang-format workflow needs to be split into two parts: one that checks out the submitted code, and a separate one which has permission to post a comment. See #5659 for more information.
This is a test.
This workflow …

chore: Create separate report_clang_format workflow in master branch

---

.github/workflows/report_clang_format.yml

Removes an unwanted `on` clause that was overlooked in #5670 by author and reviewer.

chore: Remove spurious extra `on` clause in report_clang_format.yml

---

.github/workflows/report_clang_format.yml

In aid of #5669.
`console.log` the `github.event` object, in search of information about PR that triggered original `check_clang_format` run that triggered this workflow.

chore: More spelunking in GitHub Action data

---

core/toolbox/toolbox.js
tests/mocha/insertion_marker_test.js
tests/mocha/toolbox_test.js

No issue filed.
- Fix redeclares in helper functions in tests.
- Fix a bug in flyout visibility logic that was masked by a bad test
Calling `Toolbox.prototype.updateFlyout_` with `null` for both `oldItem` and `newItem` tried to access `isCollapsible()` on `null` and failed.
If `newItem` is null the flyout is hidden.
I fixed a suspicious redeclaration of a variable in a test, which unearthed this bug.
Tested by 'No new item -> Should close flyout' in `toolbox_test.js`.
Added a test for 'Old item but no new item -> Should close flyout' in `toolbox_tests.js`.

fix: bad order of checks for setting flyout visibility

---

blocks/colour.js
blocks/lists.js
blocks/logic.js
blocks/loops.js
blocks/math.js
blocks/text.js
blocks/variables.js
blocks/variables_dynamic.js

Progress toward https://github.com/google/blockly/issues/5597
Remove all references to JSON extraction in blocks files.
No change.
No change.
The reason we made the JSON block definition format in the first place was so that you could define blocks in one place and have them work across Android, iOS, and web. At the time we were building Android and iOS versions of Blockly.
There was a script that scraped the block definitions in google/blockly and copied JSON block definitions into the Android and iOS repositories.
JSON is still helpful for simple blocks, but we're no longer developing Android or iOS and these comments are outdated and confusing.

chore: remove references to JSON extraction

---

core/field_textinput.js

Mobile users get a window.prompt as an input, if they press the cancel button the return value is null.  Don't attempt to set the value of the field to null.
Caused errors in the custom note field which inherits from FieldTextInput.  Detected in Blockly Games Music.

fix: Don't try to set text fields to null on cancel

---

package.json

Improves workflow for local testing
Adds the command `npm run tests:mocha:interactive`, which launches a server and opens the mocha index page.
Reduce friction in testing--when I see test failures in my mocha tests on the command line, my next move is usually to open the mocha test page so I can start debugging.
Ran command locally

chore: add command to launch mocha tests

---

blocks/variables.js
blocks/variables_dynamic.js

This is the context menu of a variable-get block in the flyout.
Detected via error logging in Blockly Games.

fix: Quote Msg prop name to survive compile

---

.github/dependabot.yml

I changed the labels after the last dependabot update, so it keeps adding comments that it can't find the labels "chore" and "dependencies". This fixes it.
Note that it's against master.

chore: fix dependabot labels

---

scripts/migration/renamings.js

https://github.com/google/blockly/pull/5623#pullrequestreview-783719318
Adds entries to renamings.js for modules that were migrated to named exports.

chore: Record renamings for named exports

---

core/common.js

Fixes #5674 
Makes `Blockly.common.setSelected` package visibility, and updates the documentation string.
This function was added last quarter when adding get/set pairs for the properties in blockly.js. It is used to track which block is currently selected. I did not rename the function as suggested because we already have `BlockSvg.prototype.select` which updates the UI and is generally the function external developers should call in order to programmatically select a block.

chore: make Blockly.common.setSelected package and update docs

---

core/touch_gesture.js

The e.pageX (and .pageY) checks aren't strict enough.  0 is a perfectly valid coordinate.
Checking for the existence of changedTouches is an easier way to distinguishing a PointerEvent from a TouchEvent.
Resolves #5688.  Found from client-side error logging on Blockly Games.

fix: Stop throwing error when PointerEvent.pageX is 0.

---

.eslintrc.json
scripts/gulpfiles/build_tasks.js
tests/node/.eslintrc.json

Also:
- Ensure that the `comma-dangle` rule will not be applied to function parameter lists (even when multi-line).
- Update `tests/node/.eslintrc.json` to make the environment node-specific and not pinned to es6.
Proximately this is to allow use of spread syntax in object literals (`const foo = {...bar, baz: 'quux'}`).

chore(build): Update compiler & linter input language to ES2020

---

generators/javascript/text.js
generators/javascript/variables.js
generators/javascript/variables_dynamic.js
tests/deps.js

Part of #5598
Changes three files to goog.module and adds missing requires:
- `generators/javascript/text.js`
- `generators/javascript/variables.js`
- `generators/javascript/variables_dynamic.js`

refactor: convert some js block generators to goog.module

---

blocks/procedures.js

Fixes a bug where caller blocks would not update properly when an input was removed. 
This was found because of @BeksOmega tests in the block-plus-minus plugin. 🎊 
We should probably add a similar test in core. [[Filed issue](https://github.com/google/blockly/issues/5466)]
Use `this.arguments_.length` instead of `itemCount_`. `itemCount_` is used in text & list blocks but not procedures. I think this was introduced when we were doing a [larger refactor](#5626) that included all the blocks.
Remove an input on a procedure breaks the caller block.
Procedures work!

fix: procedure callers now remove inputs properly

---

generators/lua/colour.js
generators/lua/lists.js
generators/lua/logic.js
generators/lua/loops.js
generators/lua/math.js
generators/lua/procedures.js
generators/lua/text.js
generators/lua/variables.js
generators/lua/variables_dynamic.js
tests/deps.js

Part of #5598
Converts to goog.module with named requires, and fixes missing requires, for 
- `generators/lua/colour.js`
- `generators/lua/lists.js`
- `generators/lua/logic.js`
- `generators/lua/loops.js`
- `generators/lua/math.js`
- `generators/lua/procedures.js`
- `generators/lua/text.js`
- `generators/lua/variables.js`
- `generators/lua/variables_dynamic.js`

refactor: convert some block generators to goog.module

---

core/blockly.js
tests/compile/main.js
tests/compile/test_blocks.js
tests/run_all_tests.sh

Fixes #5602.
* Fix advanced compilation test:
- Fix loading of blocks in `tests/compile/main.js` caused by recent `goog.module`-ification work.
- Fix problem caused by ADVANCED_OPTIMISATIONS renaming the `Msg` property on the fake `Blockly` object created by the translation-loading hack in `blockly.js`.
* Reenable advanced compilation test 
Test was disabled and if run manually produced un-loadable code.
Test enabled, runs as part of `npm test`, and produces code that loads and works correctly.
We like tests.
Tested on:
* `npm test`

fix(tests): Fix & reenable the advanced compilation test

---

tests/playgrounds/compressed.html

Resolves issues with testing on playground when loading over a network. Uncompressed mode should only be used for local development and testing; compressed mode should be used for most tests.
Adds another playground that duplicates the standard playground but uses compressed files for blockly, blocks, and generators.
Test page took >1 minute to load; the browser often thought it was completely broken.
Test page takes less time to load.
Make test pages load in a reasonable time.
I'll need to push this up to gh-pages once merged and then tell Divya to use the new URL for tests, at least this quarter. If longer term, that change will need to be included in the test plan.
This is a duplicate of the standard playground. I don't like playground proliferation, so we may want to delete it after …

chore(test): Add playground that uses compressed files

---

tests/playgrounds/multi_compressed.html

Similar to https://github.com/google/blockly/pull/5782 but for the multi-playground. 
Also related to https://github.com/google/blockly/issues/5783, because this should be removed at the same time as the compressed playground.

chore(test): add version of multi_playground with compressed files

---

tests/multi_playground.html

Broken multi-playground.
Uses `goog.require` instead of bare script tags to load blocks in a playground that runs in uncompressed mode.
multi-playground was broken with an error in the console: 
> Uncaught Error: Module Blockly.blocks.logic has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.
Error is gone and playgrounds work.
Modules can't be loaded in bare script tags.

fix: multi-playground should use goog.require to get blocks

---

core/toolbox/category.js

Toolbox definition with undefined colour attribute would give warning: "Toolbox category "If" has unrecognized colour attribute: undefined"
Allows undefined as value
This was introduced in #5599 . `== null` is allowed when testing for undefined and null values so changed it back.
Tested in block factory which was previously showing this warning, no longer.

fix: allow undefined color in toolbox definition

---

core/utils/aria.js

Don't use fully qualified Blockly namespace. this was missed during module conversion
Using the fully qualified namespace is against the style guide and breaks TypeScript
I think we should merge this in before release since it's related to the module conversion

fix: don't use fully qualified namespace in aria

---

package-lock.json
package.json
tests/mocha/.eslintrc.json

Test failures for PR #5791.
* Remove dev dependency on `babel-eslint` parser.
* Revert most other changes made to `tests/mocha/.eslintrc.json` in PR #4062 as they appear to no longer be needed thanks to updates to our top-level `.eslintrc.json`.
When linting `tests/mocha/`, `eslint` would use the `babel-eslint` parser.
When linting `tests/mocha/`,  `estlint` will use its usual built-in parser.
When dependabot submitted PR #5791, it became apparent that `eslint` version >= 8 is incompatible with `babel-eslint` v10.1.0 despite the latter not having a version restriction against it.  This is probably because v10.1.0 is the last version of the package before it was deprecated and renamed `@babel/eslint-parser`.
We could switch to using the new package, but a little more investigation …

chore(deps): Remove dependency on `babel-eslint`; simplify eslintrc for mocha tests

---

core/shortcut_registry.js

KeyCodes does not use a generic type, this is just incorrect syntax and it was broken in generated TS defs
This is not urgent to go in before release, I've already fixed it manually in TS types and Closure hasn't complained about it

fix: fix keycodes type

---

core/utils.js
core/utils/svg_math.js

The namespace for certain utils function was incorrectly listed as `Blockly.svgMath` rather than `Blockly.utils.svgMath`. This affects:
- The deprecation notices for functions moved out of Blockly.utils direct namespace
- The JsDoc for these functions on devsite
We can regenerate the JsDoc script to have these corrected on devsite (unless Aaron already fixed it manually, haven't checked)
This should be cherry-picked into a patch release for v7, because currently the deprecation warnings tell people to use a function that does not exist.

fix: Use correct namespace for svgMath functions

---

core/blockly.js
core/internal_constants.js
core/utils/colour.js
core/utils/parsing.js

However, this will need to be cherry-picked into a patch release.
Fixes the issue [reported](https://groups.google.com/g/blockly/c/Zme8UGnh0Bg) on the forum where devs can no longer set default saturation and value.
These properties were settable before goog.module-ification, and we [suggest setting them](https://developers.google.com/blockly/guides/create-custom-blocks/block-colour) in our documentation.
- Move the two values from InternalConstants into utils/colour.js and add get and set functions.
- Update internal uses (only in utils/colour.js and utils/parsing.js)
- Add getter and setter pairs in blockly.js
Note that I marked the internal get and set functions package, because we may yet want to rearrange these.
Could not set default value or saturation.
Can now set default value or …

fix: re-expose HSV_VALUE and HSV_SATURATION as settable properties on Blockly

---

core/insertion_marker_manager.js

Resolves #5720
It allows changes the insertion marker manager to handle a block which changes its connections while it is being dragged (e.g. by a drag/move event handler).
The insertion marker manager would throw an error due to mismatched connections when dragging a block which has changed its connectors during a drag.
The insertion marker manager no longer throws an error due to mismatched connections when dragging a block which has changed its connectors during a drag.  More specifically, it updates its set of available connections and its marker block more dynamically.
I would like to be able to create a "chameleon" block which would have previous, next and output connections when
created, so that it could be used as either a value or a statement. Once it is actually connected it …

fix: change getCandidate_ and showInsertionMarker_ to be more dynamic

---

demos/blockfactory/index.html

In demo/blockfactory, I see that the input tag is not closed in demo/blockfactory/index.html, and I fixed this

fit: Fixed the label closure on demo/blockfactory

---

core/renderers/common/constants.js

Fixes #5830.
This was introduced in #5599. We could go back to using `!=` however I'm not sure if someone would try to 'fix' this again in the future so I think the proposed fix is safer. 
The original functionality would break if a developer set it as an ''. This fix covers that case as well as when a user passes `null` or `undefined`.

fix: setting null for font styles on a theme

---

core/mutator.js

Closes #5439 
Adds proper handling of groups to the mutator so that it doesn't clobber things and break undo. Basically we now make sure to check for existing groups, and reset to them after starting new groups if necessary.
Event groups are global, even though events are specific to a given workspace. So what we want is for all of the events related to editing a parameter to be a part of the group started by editing that field in the mutator workspace.
These changes make sure that is the case, by making sure the mutator does not clobber existing event groups.
* Parameter edits are undone with a single undo.
* Mutator edits still undo and redo properly (tested with controls_if and lists_create_with)
* Neighbor bumps triggered by mutator edits are still grouped properly (tested with …

fix: procedure param edits breaking undo

---

core/clipboard.js
core/workspace_svg.js
tests/deps.js

Closes #5689 
Always wraps the create event from a paste in an event group.
Before, when a paste was triggered via clipboard.duplicate the create event wasn't being wrapped in a group, which meant that the bump event couldn't be grouped with the create event. This was breaking undo, which is not happy.
Replicated the steps from #5689  using both the context menu duplicate option, and copy paste keyboard shortcuts. Could no longer replicate the result.
Tested on:
Nope!
The check for the existing group isn't necessary for Blockly on its own, because `workspace.paste` is only called from the context menu and keyboard shortcuts. However `workspace.paste` is public (for some reason) so we need to check for existing groups to make sure we don't break the event groups of people …

fix: bumping a block after duplicate breaking undo

---

core/block_drag_surface.js

Observed this error in Blockly Games Bird 6 (Chrome OS):
`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`
~It has only shown up once, and I can't reproduce,~ but it looks like the drag surface was being cleared while empty.  Maybe some weird multi-touch race-condition on a Chromebook?
Open question: Leave the code as is so that the error is thrown and visible, or suppress it?

fix: Don't throw if drag surface is empty.

---

typings/index.d.ts

This is a copy of https://github.com/google/blockly/pull/5846 against master, which will fix https://github.com/google/blockly/issues/5841 in the next patch release.
When we released v7 we committed to making patch releases for typescript definition errors, since our pipeline for typings was convoluted this quarter.

fix: msg imports in type definitions

---

package-lock.json
package.json

Clearing node_modules and removing the package-lock causes build errors because the block-test version is not updated correctly.
Cherry pick #5836 from develop.

chore(deps): bump @blockly/block-test from 1.1.5 to 2.0.1 (#5836)

---

core/block_drag_surface.js
core/block_dragger.js
core/bubble.js
core/bubble_dragger.js
core/utils/coordinate.js
core/utils/rect.js
core/utils/size.js

Part of #5860
I suggest reviewing this PR one commit at a time, because the final clang-format run touches most lines.
- Convert the following files to es6 classes:
- `utils/coordinate.js`
- `utils/rect.js`
- `utils/size.js`
- `block_dragger.js`
- `block_drag_surface.js`
- `bubble_dragger.js`
- `bubble.js`
- Run clang-format
I also moved several property declarations into the constructor on bubble in response to compiler errors during conversion. Those properties were:
- `bubbleGroup_`
- `bubbleArrow_`
- `bubbleBack_`
- `resizeGroup_`
The compiler error was that the properties were being used without having been declared in the constructor. We didn't have this error before because we didn't tag the class with `@struct`, and it's a common pattern in our codebase that I expect I'll have to …

refactor: convert some files to es6 classes

---

core/block.js
core/block_svg.js
core/comment.js
core/icon.js
core/mutator.js
core/warning.js

Part of https://github.com/google/blockly/issues/2892
Declare properties in the constructor and annotate appropriately, instead of declaring at first use.
I found these by adding `struct` to annotations for various classes and fixing new errors that resulted. Struct means that you can't add new properties after the constructor runs.
Not all of our classes will be able to be structs--for instance, we let people store arbitrary properties on their blocks--but it's good practice and makes it easier to later convert classes to es6. I found some of these problems when working on #5861 
No change in behaviour.
Tested by running mocha and generator tests, and by playing around in the playground with a focus on comments and mutators.

chore: declare properties in the constructor instead of at first use

---

package-lock.json

CVE-2022-0155
Update `follow-redirects` to latest version.
Verified that `npm start` still works (since `follow-redirects` is a subdependency of `http-server`).
See https://github.com/google/blockly/security/dependabot/package-lock.json/follow-redirects/open

chore(deps): Update `follow-redirects` to address CVE-2022-0155

---

package-lock.json

CVE-2022-0155
Update `follow-redirects` to latest version.  This is the same as PR #5879, but against the `master` branch.
Verified that `npm start` still works (since `follow-redirects` is a subdependency of `http-server`).
See https://github.com/google/blockly/security/dependabot/package-lock.json/follow-redirects/open

chore(deps) Update `follow-redirects` to 1.14.7 to address CVE-2022-0155 (in `master`)

---

typings/blockly.d.ts

https://github.com/google/blockly/issues/5891 Attempts to use `Blockly.serialization` fail within TypeScript environments as serialization is not exported within the type definition file.
Cleans up the serialization type declarations and bundles them into the main Blockly export so that they are available to TypeScript users, in the same manner as Xml.
Two of the serialization module declarations were distant from the others; moving them to be adjacent improves code maintainability.
The existing convention appears to use bundling and re-exporting, so a `serialization` module was introduced.
The new singular module is imported to blockly and then re-exported.
Note: I did **not** change the capitalization of the existing code, however it appears to be in conflict with precedent. I am unsure …

fix: TypeScript exporting of the serialization functions
