- demos/plane/blocks.js
If this block is removed, the puzzle cannot be completed. This will make a good example users can be pointed to for a use example of setDeletable(boolean).
> Make the "seats =" block not deletable.

- core/field_textinput.js
keyup and keypress don't care IME on or off.  so, I added handling
keydown event to check pressing enter key with IME (keycode is 229) or
without IME (keycode is 13).
> Fixed issue with pressed enter key with IME.

- core/block.js
- core/block_svg.js
When collapse a block containing collapsed blocks duplicates the text.
> fix collapse bug

- demos/code/code.js
The bug status is: RESOLVED FIXED (https://bugzilla.mozilla.org/show_bug.cgi?id=151407)
> Remove resolved firefox bug comment

- demos/interpreter/index.html
Fix a minor typo in demos/interpreter
> Fix typo (wth -> with)

- package.json
This basic package.json file will allow the integration with the nodejs package manager npm.
More infos:
https://docs.npmjs.com/files/package.json
If need we could also publish this to the npm repositories under https://www.npmjs.com/.
> Add basic package.json for npm support.

- core/block.js
- core/field.js
A couple helpful type annotation additions.
> adding type annotations

- core/block.js
- core/block_svg.js
- core/connection.js
- core/xml.js
Improved a couple of type annotations I came across. Additionally, added block.data to prototype so that 1) it's easier to discover 2) it is type annotated and documented.
> improve type annotations

- core/scrollbar.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/google/blockly/236)
> Fix scrollbar visibility when horizontal

- core/workspace_svg.js
Hi, this method could be useful for some requirements of Blockly based applications.
> Add zoomToFit method to Workspaces

- core/scrollbar.js
calls come before all of the setAttribute calls.  This gets rid
of an unnecessary layout pass on mouseMove events.
> Rearrange code in ScrollbarPair set so that all the getAttribute

- core/scrollbar.js
I made the pull request to master since the original one was there too.  Let me know if you'd prefer to have it on develop.
Also, if there's a way to amend this change to the other commit, happy to do it, but I'm new to git and don't know how to upstream that kind of thing.
> Add missing semicolons to methods. Oops.

- core/block.js
- core/block_svg.js
> Move Blockly.Block rendered into Blockly.BlockSvg

- core/block_svg.js
Fixes https://github.com/google/blockly/issues/308
> Disable connecting to last block in stack

- demos/code/code.js
> fixed a translation error

- demos/plane/plane.js
> fixed an translation error

- core/flyout.js
> Decompose functions in flyout.  Does not change behaviour.

- core/block_render_svg.js
- core/flyout.js
Also, position hat blocks correctly in the flyout/toolbox.
This fixes #330.
> Take into account height of the hat for hat blocks.

- core/toolbox.js
> Revert "Add option to set id on toolbox"

- build.py
> Revert "proxy option for build.py"

- core/connection.js
- tests/jsunit/connection_test.js
> Allow terminal blocks to replace other terminal blocks

- core/block_svg.js
- core/flyout.js
- core/toolbox.js
- core/trashcan.js
- core/workspace_svg.js
> Cache delete areas

- core/toolbox.js
> Rewrite anonym function "syncTree" for compiler and debugging reasons.

- blocks/loops.js
- blocks/procedures.js
- blocks/variables.js
- core/events.js
- core/field_textinput.js
- core/mutator.js
- core/procedures.js
- core/toolbox.js
- core/tooltip.js
- core/variables.js
- core/widgetdiv.js
- core/xml.js
This is a cherrypick from the one submitted to develop yesterday.
Once submitted and merged, will update my fork and then run a recompile and submit that.
> Revert "Convert createDom calls to createUntypedDom"

- demos/resizable/overlay.html
knows what size it is going to be.
> Call Blockly.svgResize() once the div it is going to be placed in

- core/workspace_svg.js
Make Blockly.WorkspaceSvg.cleanUp public by removing @private tag and changing name.
> Make Blockly.WorkspaceSvg.cleanUp public

- blocks/procedures.js
- core/field_textinput.js
Per https://github.com/google/blockly/issues/493
> Create variables from the procedure definition mutator

- demos/blocklyfactory/app_controller.js
Avoid repetitive code by adding a new function to add or remove styles from tabs based on whether or not they are selected.
> Blockly Factory: Refactor Tab Handler

- demos/blocklyfactory/app_controller.js
- demos/blocklyfactory/index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/605)
> Blockly Factory: Exporter Buttons and Tab Ordering

- core/workspace.js
> Check result of window.confirm before deleting variables.

- demos/blocklyfactory/workspacefactory/wfactory_generator.js
- demos/blocklyfactory/workspacefactory/wfactory_model.js
Fixed bug for updating flags for custom categories. Also updated the starter code to use document.getElementById for XML elements, and added some more comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/615)
> Blockly Factory: Bug Fix, Adjust Starter Code

- core/field_checkbox.js
> Make field checkbox setValue case insensitive

- core/workspace_svg.js
Get rid of warnings about the meaning of "this"
Fixes #623
> Add @this annotation to get/set metrics.

- core/flyout.js
- core/tooltip.js
Tooltips should tooltip
Blocks in the flyout should highlight when moused over
Pending verification with touch
> Mouseover behaviour fixes

- generators/php/procedures.js
- generators/python/procedures.js
> Don't modify workspace.variableList in generators

- core/toolbox.js
- core/workspace_svg.js
Just adding a few more helpful type definitions that I came across.
> Add a few missing type definitions

- core/block_svg.js
- core/inject.js
- core/workspace_svg.js
- demos/interpreter/index.html
Allows multiple blocks to be highlighted when executing multithreaded programs.  No more collision between selections and executions.
> Highlighting

- core/workspace_svg.js
- demos/custom-dialogs/custom-dialog.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/719)
> Addressing comments from #703

- core/field_dropdown.js
- core/field_variable.js
- core/workspace.js
- demos/mirror/index.html
FieldDropdown now has onItemSelected(..) method to handle the menu item selection action. Variable renames and deletes are now handled here, instead of during validation.
Fixes #723.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/726)
> Refactor variable rename to handle UI actions more directly.

- core/field_variable.js
- core/xml.js
> disallow variables on shadow blocks

- blocks/logic.js
- core/utils.js
- generators/dart/logic.js
- generators/javascript/logic.js
- generators/lua/logic.js
- generators/php/logic.js
- generators/python/logic.js
- tests/jsunit/utils_test.js
- tests/playground.html
Using in the CONTROLS_IFELSE block, referencing the existing string of CONTROLS_IF_MSG_*.
> String reference in JSON string messages

- core/css.js
- core/flyout.js
- core/flyout_button.js
- tests/playground.html
New PR because the old one bit-rotted over a month.
> Add classes to labels with web-style attribute in xml

- core/workspace_svg.js
There was some IE specific code that also applies to Edge so just updated
a conditional to include Edge.
> Fix #794 and make the workspace grid drag along with the workspace.

- core/field_colour.js
- core/field_date.js
- core/field_dropdown.js
- core/field_textinput.js
> Fix two event bugs on fields

- tests/generators/index.html
- tests/generators/logic.xml
Also, adding helpful links into the unit test page.
> Adding unit tests for ifelse block.

- core/field_angle.js
- core/field_number.js
- tests/jsunit/field_angle_test.js
- tests/jsunit/field_number_test.js
> Replace single quotes with double.

- core/field_dropdown.js
- tests/jsunit/json_test.js
> Fixing JSON support for images in dropdowns. Adding tests.

- core/extensions.js
- core/utils.js
Defer tooltip message string check until after load, when all Blockly.Msg should be loaded.
Also, fix annotation error.
> Blockly.Extensions.buildTooltipForDropdown(..): Deferred validation.

- core/blockly.js
- core/field.js
- core/variables.js
> annotation updates

- core/events.js
> Don't try to get block position in a headless workspace

- core/connection.js
- core/rendered_connection.js
> Stop bumping neighbours in headless blockly

- core/touch.js
> Place context menu correctly on touch

- blocks/colour.js
- blocks/logic.js
- blocks/math.js
Also, correcting quotes in logic.js.
Tested via generator tests.
> Moving extension related constants to Blockly.Constants.Math and .Colour

- blocks/lists.js
> JSONify simple list blocks

- core/block.js
- core/field_image.js
- core/utils.js
Allow string table / Blockly.Msg references in the JSON "variable" attribute.
> Variable name i18n

- core/utils.js
Unraveling nested ternaries in Blockly.utils.tokenizeInterpolation_()
> Clarification in Blockly.utils.tokenizeInterpolation_

- accessible/field-segment.component.js
- accessible/tree.service.js
Also, fixing FieldSegment so it updates dropdowns when the underlying dropdown changes.
> Fixing Enter so it properly propogates to dropdown selection.

- core/gesture_handler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/928)
> Add gesture handler

- core/block_dragger.js
- core/dragged_connection_manager.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/939)
> Add block dragger object

- core/block_svg.js
- core/constants.js
See thread in support group before merging.
> Option for moving one block from stack.

- blocks/logic.js
- blocks/math.js
- core/block.js
- core/extensions.js
- tests/jsunit/extensions_test.js
> Use mutator extension for controls_if block

- core/xml.js
- tests/jsunit/xml_test.js
- tests/workspace_svg/workspace_svg_test.js
This is a copy (with additional comments) of PR #822 (and also #961) by @qnoirhomme with unrelated files removed.  See #822 for full review.
> Adding Blockly.Xml.appendDomToWorkspace()

- tests/playground.html
> Set background color to lilac if opening the playground from file:

- accessible/app.component.js
- accessible/field-segment.component.js
- accessible/variable-modal.service.js
- accessible/variable-remove-modal.component.js
- accessible/variable-rename-modal.component.js
- core/field.js
- core/field_variable.js
- core/workspace.js
- demos/accessible/index.html
NOTE - this one has core blockly changes. Please double check those are fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1011)
> Adding the remove variable to Accessible Blockly

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1021)
> Add links to the dev registration form and contributor guidelines

- core/block.js
- core/block_drag_surface.js
- core/block_svg.js
- core/rendered_connection.js
- core/touch.js
Mostly adding descriptions of units for coordinates.
> Miscellaneous comment cleanup

- accessible/app.component.js
- accessible/block-options-modal.component.js
- accessible/commonModal.js
- accessible/keyboard-input.service.js
- accessible/toolbox-modal.component.js
- accessible/variable-add-modal.component.js
- accessible/variable-remove-modal.component.js
- accessible/variable-rename-modal.component.js
- demos/accessible/index.html
Centralizes accessible modal behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1017)
> Adding the common modal class for Accessible Blockly.

- .travis.yml
- README.md
- package.json
- scripts/get_chromedriver.sh
- scripts/get_geckdriver.sh
- scripts/get_selenium.sh
- scripts/selenium_connect.sh
- tests/jsunit/test_runner.js
Cherry-pick of travis ci change into develop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1035)
> Enable google/blockly with continuous build on travis ci (#1023)

- core/block_svg.js
> Ensure useDragSurface is a boolean.

- core/field_angle.js
> field_angle renders degree symbol consistently.

- core/block.js
- core/block_svg.js
Fixed #1009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1049)
> bumpNeighbours_ function moved to block_svg.

- core/input.js
> single quotes. better logic.

- core/variable_model.js
- tests/jsunit/index.html
- tests/jsunit/variable_model_test.js
The logic for checking for uniqueness in VariableMap will be added to workspace.js.
I think this variable model is simple enough it doesn't require tests, but I wrote tests anyways for practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1055)
> Create a variable model with name, id, and type.

- demos/code/code.js
@vicng string.startsWith breaks IE compatibility.
> Use goog.string.startswith instead of string.startswith

- scripts/test_setup.sh
Add more wait time for selenium connection. 
travis job run passed on my branch: https://travis-ci.org/shirletan/blockly/jobs/230441457
> add more wait time for test setup

- scripts/test_setup.sh
- tests/jsunit/test_runner.js
I'm not able to reproduce this issue  happened on google/blockly merge test run. 
Adding a wait on a few more places to see it can be fixed.second attempt. 
Test run passed: https://travis-ci.org/shirletan/blockly/builds/230490681
> Work around timing issue with travis osx issue

- README.md
This lets us redirect to a different form if we change it in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1106)
> Change registration link to a static one

- core/gesture.js
> Click events on shadow blocks have the correct id

- core/field_image.js
Added an onclick option for field_image
> Field_image onclick function

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1119)
> Add missing CLAs info to the contributing file

- demos/code/code.js
Replaced prettify.* with latest on CDN.
> Forgot update code demo

- core/xml.js
- tests/jsunit/xml_test.js
Blockly.Xml reads in serialized variables at top.
Error thrown if the serialized type of a variable does not match the type of a variable field that references it, as in the code below.
Error thrown if <variable> tag has no type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1130)
> Develop deserialization variables at top

- core/xml.js
Create a flag for checking if <variables> is the first tag.
> Deserialization variables at top.

- blocks/text.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1140)
> Convert text_join block to JSON + mutator format

- blocks/text.js
- msg/messages.js
Converts the mutator blocks for text_join and the text_append block
to JSON format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1147)
> Convert more text blocks to json

- core/events.js
- tests/jsunit/event_test.js
- tests/jsunit/index.html
> Add block events.

- accessible/toolbox-modal.service.js
- build.py
- core/variables.js
Also fixing a bug with the core-only uncompressed file not finding its own directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1149)
> Adding automatically-generated variable lists to the accessible toolbox.

- blocks/procedures.js
- core/block.js
- core/block_dragger.js
- core/block_svg.js
- core/comment.js
- core/connection.js
- core/contextmenu.js
- core/field.js
- core/field_checkbox.js
- core/field_colour.js
- core/field_dropdown.js
- core/field_textinput.js
- core/field_variable.js
- core/mutator.js
- core/procedures.js
- core/workspace_svg.js
- core/xml.js
- demos/blockfactory/workspacefactory/wfactory_init.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1151)
> Correctly named block events called.

- core/variable_map.js
- core/variable_model.js
- core/workspace.js
- tests/jsunit/index.html
- tests/jsunit/workspace_undo_redo_test.js
All Var Events are fired in locations indicated by the Design Doc:
https://docs.google.com/document/d/1q49IrmDHu-D1ENA5t_Ruxkuej1O2htW5YeM-4Em88ic/edit?ts=592f2c6e&actionButton=1#heading=h.gknl12ppwima
Includes tests for redo and undos of:
- VAR_CREATE
- VAR_DELETE: Without blocks and with blocks
- VAR_RENAME: Without blocks and with blocks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1162)
> Fire VAR events and test.

- accessible/toolbox-modal.service.js
- demos/accessible/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1171)
> Fixing an error with block messages and ordering.

- core/workspace_svg.js
Fixes  https://github.com/google/blockly/issues/1175
> Followup RefreshToolbox.

- core/gesture.js
Fixes https://github.com/google/blockly/issues/1185
> Bug fix: always open flyout fields are not editable.

- core/flyout_base.js
Fixes https://github.com/LLK/scratch-blocks/issues/956
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1181)
> Fix checkbox delete bug.

- tests/jsunit/gesture_test.js
- tests/jsunit/index.html
- tests/jsunit/variable_map_test.js
Never worry about IsFieldClick() again!!!!!!!
> Revamping mostly gesture tests.

- core/flyout_base.js
Fixes https://github.com/LLK/scratch-blocks/issues/982
> Fix flyout dropdown bug.

- generators/php.js
- generators/php/procedures.js
- generators/python/procedures.js
Fixes https://github.com/google/blockly/issues/1190
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1191)
> Fix python and php procedures.

- core/block_svg.js
- core/dragged_connection_manager.js
> Fix "Connection UI Effect not playing on block connect"

- core/gesture.js
> Only add a block in the flyout if it is not disabled

- blocks/text.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1207)
> Fix issue with compression stripping dropdown options

- demos/blockfactory/analytics.js
- demos/blockfactory/app_controller.js
- demos/blockfactory/block_exporter_controller.js
- demos/blockfactory/block_library_controller.js
- demos/blockfactory/index.html
- demos/blockfactory/workspacefactory/wfactory_controller.js
Adding BlocklyDevTools.Analytics, an interface for integrating an analytics library to track basic usage, including:
* navigation.
* saving, importing, and exporting.
* warnings and errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1217)
> Adding BlocklyDevTools.Analytics

- generators/php/procedures.js
- generators/python/procedures.js
> Fix code generation for procedures (PHP, Python).

- core/block.js
- core/field_variable.js
- core/procedures.js
- core/variables.js
- core/xml.js
- msg/messages.js
- tests/jsunit/field_variable_test.js
- tests/jsunit/xml_test.js
- Set variableTypes in Blockly.fieldVariable
- Add Blockly.fieldVariable.getVariableTypes_()
- Follows design doc [guidelines](https://docs.google.com/document/d/1ZCLus7iBrL7ZMhpmlCdrVDKXEpQtwqWdDjf_Ojm88yE/edit#heading=h.vayo408ql2vv): 
- Add check that two variables are of the same type if renaming one variable to another existing one.
- Add tests for Blockly.fieldVariable.getVariableTypes_()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1230)
> Add VariableType checks.

- core/procedures.js
- core/variables.js
- tests/jsunit/index.html
- tests/jsunit/procedures_test.js
Fixes:
https://github.com/google/blockly/issues/1237
> Fix Blockly.Procedures.isNameUsed return values.

- tests/generators/index.html
Change the Lua interpreter to another one with version 5.3 so that it
would support goto statement which Blockly uses currently
> Change the Lua interpreter

- demos/blockfactory/block_option.js
- demos/custom-dialogs/index.html
- demos/fixed/index.html
- demos/generator/index.html
- demos/headless/index.html
- demos/interpreter/async-execution.html
- demos/interpreter/step-execution.html
- demos/maxBlocks/index.html
- demos/resizable/overlay.html
- demos/rtl/index.html
- demos/storage/index.html
- demos/toolbox/index.html
- tests/generators/index.html
Fixes https://github.com/google/blockly/issues/1224
> Change workspace name to playgroundWorkspace.

- core/extensions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1262)
> Missed one use of string instead of .property in extensions.js

- core/contextmenu.js
- core/flyout_base.js
- core/gesture.js
- core/variable_map.js
- core/workspace_svg.js
Fixes https://github.com/google/blockly/issues/1260
> Fix type tags and todo placement.

- core/block_svg.js
> Code cleanup in BlockSvg.prototype.tab

- core/field_dropdown.js
Fix wrong width of field_dropdown with an image on Edge / IE. 
Fixes #1274
> Fix width of field_dropdown in IE/ Edge

- accessible/toolbox-modal.service.js
than on a timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1255)
> Fixing no-category toolboxes so they populate immediately, rather

- core/field_textinput.js
Create helper functions for binding and unbinding event handlers.
> Clean up code in FieldTextInput

- core/field_textinput.js
This is a followup on #1284 that does more decomposition.
> Decompose the showEditor_ function in FieldTextInput

- core/block.js
Hello! This is my first ever pull request, so please lmk if there's anything I should have done differently :)
I think this should address issue #1247 by storing hue as a private field in Block. I think I've updated the get and set methods correctly.
I know it's only a tiny contribution, but it's my first step in contributing to an open source project, so small steps!
> Store Block hue so it can be extracted reliably

- generators/dart/procedures.js
- generators/javascript/procedures.js
- generators/lua/procedures.js
- generators/php/procedures.js
- generators/python/procedures.js
> Properly escape IDs in procedure generators.

- demos/codelab/app-complete/index.html
- demos/codelab/app/index.html
This adds Google Analytics to the new codelab files.
This PR applies to the `analytics-DO_NOT_DELETE` branch, used to patch demos before pushing to appspot. These updates are not in master or develop, or referenced in the codelab files.
> Adding Google Analytics info to new Codelab files.

- msg/js/br.js
- msg/json/br.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/1353)
> Fixes bad Breton translation that misses positional specifier

- demos/code/code.js
Closure should not be used except within core.
> Fix code demo if Blockly is compiled harder.

- core/events.js
Noted missing documentation in [this thread](https://groups.google.com/forum/#!topic/blockly/peB-XCokkFU).
> Adding JSDoc for blockId, varId, workspaceId, group, and recordUndo

- demos/code/code.js
Slight modifications to avoid matching %{key} notation.
> Adding code removed in #1028 to fix regression #1386.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Cleans up our GitHub templates.
Use HTML comments for instructional text, and replace many uses of checkbox with lines to uncomment. Keeping the checkboxes for "the basics" in the PR template.
Streamline error reporting and PR creation.
Copied into github issues and previewed the results.
> Updates to issue and PR templates

- .eslintignore
- .travis.yml
- package.json
N/A
Enable linting on travis, and switch from jshint to eslint.
Auto-linting will keep our code cleaner.  Eslint is the linter we've decided to use.
Added npm run lint to travis.yml
N/A
> Run eslint on travis

- blocks/colour.js
- blocks/text.js
- core/block.js
- core/blockly.js
- core/comment.js
- core/events.js
- core/field_textinput.js
More lint, so that we can enable eslint.
Annotate lots of unused variables.
Make lint pass.
Local eslint.
> More lint for unused variables

- core/variables.js
- msg/json/be-tarask.json
- msg/json/bg.json
- msg/json/br.json
- msg/json/da.json
- msg/json/de.json
- msg/json/en.json
- msg/json/es.json
- msg/json/fi.json
- msg/json/fr.json
- msg/json/hi.json
- msg/json/it.json
- msg/json/kab.json
- msg/json/ko.json
- msg/json/lb.json
- msg/json/nb.json
- msg/json/nl.json
- msg/json/pl.json
- msg/json/pms.json
- msg/json/pt-br.json
- msg/json/qqq.json
- msg/json/ru.json
- msg/json/sv.json
- msg/json/tcy.json
- msg/json/tr.json
- msg/json/uk.json
- msg/json/vi.json
- msg/json/zh-hans.json
- msg/json/zh-hant.json
- msg/messages.js
Cherry-pick of https://github.com/google/blockly/pull/1405
> Remove unnecessary restriction on variable names.

- .eslintignore
- .travis.yml
- package.json
None
Enables eslint on travis.
Automation is fun!
I added linting as part of tests on Travis.
> Enable eslint on Travis!

- core/workspace.js
- core/workspace_comment/workspace_comment.js
- core/workspace_comment/workspace_comment_svg.js
- core/workspace_svg.js
- core/xml.js
Initial work on XML parsing and encoding of workspace comments.
> XML parsing and encoding of workspace comments.

- core/workspace_comment/workspace_comment.js
- core/workspace_comment/workspace_comment_render_svg.js
- core/workspace_comment/workspace_comment_svg.js
Cleanup:
- Removed some logs
- Line lengths
> Remove svg elements when disposing of a comment; some code cleanup

- core/css.js
- core/workspace_comment/workspace_comment.js
- core/workspace_comment/workspace_comment_render_svg.js
- core/workspace_comment/workspace_comment_svg.js
- core/workspace_svg.js
- core/xml.js
Add a workspace comment on context menu click and position it where the initial context menu was clicked.
> Add a workspace comment on context menu click

- blockly_uncompressed.js
- core/css.js
- core/gesture.js
- core/workspace_comment/comment_dragger.js
- core/workspace_comment/workspace_comment_render_svg.js
- core/workspace_comment/workspace_comment_svg.js
Again, lots of code duplication from block dragging.
> Create comment dragger and wire up basic dragging

- core/variables.js
- core/workspace.js
> Make some functions public

- generators/javascript.js
No issue
Adds an `ORDER_AWAIT` constant to the JavaScript generator
`async` and `await` were added to JS recently, it would be nice to order these properly without having to use `ORDER_DELETE` or similar
Unsure how I should test these, please advise
Tested on:
> Add ORDER_AWAIT constant to JavaScript generator

- build.py
- generators/javascript.js
- package.json
Adds ‘yield’ and ‘**’ to JS order list.
Build generates files (more) parsable by Node.
This PR should have no effect on existing code.
> Improve support >ES5 and Node.

- core/block.js
- core/field_angle.js
- core/field_checkbox.js
- core/field_colour.js
- core/field_date.js
- core/field_dropdown.js
- core/field_image.js
- core/field_label.js
- core/field_number.js
- core/field_textinput.js
- core/field_variable.js
- tests/jsunit/field_angle_test.js
- tests/jsunit/field_number_test.js
https://github.com/google/blockly/issues/1486
* Adds fromJson_ fn to every Blockly.Field.
* Removes Blockly.Block.newField*FromJson_ helpers.
* Blockly.Block.prototype.interpolate_ updated to use fromJson_ for each field rather than directly instantiating the field or using the old helpers.
As described in the issue, and to support custom field types... https://github.com/google/blockly/issues/1584
I've added a couple of simple unit tests where field tests already existed. (field_angle_test & field_number_test)
Tested on:
> Fields should implement fromJson #1486

- package.json
Cherry pick #1620. See details there.
> Updating Closure to 20180204.0.0

- demos/blockfactory/index.html
Applies changes suggested in #1176, based off of latest develop.
HTML typo in BlockFactory.
Tested on:
> BlockFactory: Fixing incorrect <button> html

- core/gesture.js
- core/workspace.js
> Fix some annotations

- core/workspace.js
Moved the TODO from a doc comment to a single line comment.
The TODO triggered a devsite validation error when building the docs.
> Moving TODO from doc comment to single line comment.

- blocks/loops.js
See https://groups.google.com/d/msg/blockly/v6W3BGN9P_o/RH91g94RBAAJ
> Update comment on loop types

- tests/generators/functions.xml
- tests/generators/variables.xml
Informs future developers that there is a reason to test on the older save format, discouraging it from being over written.
> Comments on generator test workspace save files

- core/blockly.js
> Mark unbindEvent_ package instead of private

- core/workspace.js
> Make undoStack_ and redoStack_ protected

- demos/custom-dialogs/custom-dialog.js
- demos/custom-dialogs/index.html
- demos/plane/README.txt
> Add source code link to custom dialog demo.

- core/flyout_horizontal.js
- core/flyout_vertical.js
Recreation of commit c2bf01ab4879e489b2e996eea2459d4bdf74dde6 which got
lost in a refactor.
> Dragging blocks towards the toolbox should create blocks rather than do nothing

- blocks/text.js
> Add @this annotations in blocks/text.js

- core/zoom_controls.js
None
Make some helper functions to create the zoom controls.
More work for easing merges with scratch blocks.  Will need an accompanying change on that side.
Tested on chrome in the playground.
> Decompose some functions for creating zoom controls SVG

- core/blockly.js
Clarifies `this` context for closure in `initJsonFactory_()`.
> Adding JsDoc @this for closure in jsonInitFactory().

- core/field_dropdown.js
Verifies the data structure of dropdown option lists.
Catches errors early, such as:
https://groups.google.com/forum/#!topic/blockly/ae9WrvEcOP0
Adding Blockly.FieldDropdown.validateOptions_()
Added the block from the forum post to the playground, and verified the new error was present.
Tested on:
> Adding Blockly.FieldDropdown.validateOptions_()

- blocks/logic.js
Tested in Playground and RTL demo.
> Simplify RTL handling of '<' and '>'.

- gulpfile.js
> Correcting typo in comment (from #1857)

- tests/compile/main.js
Fixes #1872
Uncommented the requires in `main.js`, correcting the `procedures` require.
Ran `tests/compile/compile.sh` with the following results:
```
0 error(s), 628 warning(s), 96.3% typed
Compiler exit code: 0
Compilation OK.
```
...which is more than the previous 555 warnings, which is as expected with the inclusion of more code.  Verified several of the warnings in the log results were attributable to the newly added files.
> Adding all blocks to the compilation.

- core/block_render_svg.js
Followup from #1886 
- Define a `Blockly.BlockSvg.PathObject` type for use in the rendering code.
- Use the new object everywhere that we were passing around step arrays to all of the render functions.
- Rename uses of `stepObject` to `pathObject`.
- Update render functions to access the new object's arrays correctly
- Update all annotations.
- Create a new `setPaths_` function that just applies the paths that have been computed during render.
- Improved type checking in the rendering code (closure will warn if you push something that's not a string or number into any of the arrays).
- Gives a single place to explicitly state what each of the step arrays represents.
- Hopefully improved readability.
- The @struct annotation should mean that we can't just tack new properties onto the …
> Create and use a Blockly.BlockSvg.PathObject type

- tests/scripts/get_chromedriver.sh
See https://github.com/LLK/scratch-blocks/pull/1568
> Update chromedriver version

- core/block_dragger.js
- core/bubble_dragger.js
- core/trashcan.js
Removes goog.Timer in all places.
> Remove goog.Timer

- demos/generator/index.html
Adding a link back to the "Running JavaScript" page.
#1913
Clarifying the description of the demo.
Adding a link back to the "Running JavaScript" page.
Reduce confusion that lead to #1913.
I opened the updated page and clicked the links to make sure the correct pages opened.
> Clarifying the description on demo/generators/

- core/ws_comment_events.js
Moving TODO line out of the jsdoc comments, into a line comments.
Presubmit failure on documentation update.
> Moving TODOs out of JSDoc comments.

- blocks/lists.js
- blocks/logic.js
- blocks/procedures.js
- generators/dart/lists.js
- generators/dart/loops.js
- generators/dart/math.js
- generators/dart/text.js
- generators/javascript/lists.js
- generators/javascript/loops.js
- generators/javascript/math.js
- generators/javascript/text.js
- generators/lua/lists.js
- generators/lua/loops.js
- generators/lua/math.js
- generators/lua/text.js
- generators/php/lists.js
- generators/php/loops.js
- generators/php/math.js
- generators/php/text.js
- generators/python/lists.js
- generators/python/loops.js
- generators/python/math.js
- generators/python/text.js
> Throw errors instead of strings.

- .eslintrc.json
- package.json
Fixes #2006
- Makes a copy of .eslintrc in .eslintrc.json
- Updates eslint rules to support eslint5.
- Changes travis to use eslint5
issue #2006
Updates to eslint 5.3 and adds .eslintrc.json with proper format for configuration.
Tested on:
Desktop Linux
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2009)
> Add support for eslint5

- core/field.js
#2008
More accurate closure type annotations, and better (clearer and more complete) description of the validator function return values.
Prior documentation was incomplete.
> Improving field validator docs

- package.json
Updating NPM dependencies prior to release.
Ran `npm test playground.html` on Mac.
Tested on:
> Updating NPM dependencies to latest available.

- package.json
Bump `develop` branch `package.json` version for imminent master release.
> Bumping develop version to 1.20180831.0-develop

- package.json
`package.json` version bump to `1.20180904.0-develop`
> Bumping develop branch version to 1.20180904.0-develop

- core/connection.js
> Add connection.getCheck function #2048

- core/field_image.js
#1887
#2034
Tested on:
Desktop Chrome
> fix #1887 #2034

- demos/mobile/README.md
- demos/mobile/android/README.md
Adding `demos/mobile/README.md`.
Also updating `demo/mobile/android/README.md`.
Added readme explains the relationship between the three mobile demos, and how to run each of them.
Just documentation. Viewed Markdown in GitHub preview.
> Adding demos/mobile/README.md

- core/xml.js
.children is not well supported (in node in particular).
> Remove .children access

- core/block.js
> Fix inconsistent return type warning

- demos/mobile/android/build.gradle
Bump gradle version to latest version `3.1.4`.
Automated update from Android Studio
> Update gradle to 3.1.4

- demos/mobile/android/build.gradle
- demos/mobile/android/gradle/wrapper/gradle-wrapper.properties
Bumping gradle to 4.6.0 and Android build tools to 3.2.0.
Automated update from Android Studio.
> Update Android project to gradle 3.2.0

- demos/mobile/android/app/build.gradle
Updates to the latest ConstraintLayout in the Android demo
> Updating Android ContraintLayout

- generators/dart/lists.js
- generators/dart/math.js
- generators/dart/text.js
Update the Dart generators so that the unit tests pass when run on Dart 2.0.
> Upgrade to dart 2.0

- package.json
Update dev dependencies for october/november release.
> Update some dev dependencies

- tests/scripts/get_selenium.sh
- tests/scripts/selenium_connect.sh
> Update selenium version

- core/generator.js
- generators/dart.js
- generators/javascript.js
- generators/lua.js
- generators/php.js
- generators/python.js
- tests/jsunit/generator_test.js
- tests/jsunit/index.html
- [ x] I branched from develop
#2067
Allows a user to generate code for a single block by passing a parameter to the blockToCode method.
Helpful for allowing the users to step through blocks one by one.
Tests can be found in tests/jsunit/generator_test.js. The tests check that the blockToCode method returns only a single block for all the generators. 
Tested on:
> Generate Code For Single Block

- core/flyout_base.js
- core/gesture.js
- core/trashcan.js
#2239 
Adds a isBlockCreatable_ function to the flyout which allows you to check if a block can be "dragged out of" the flyout. By default this returns false if the block is disabled, true otherwise. The trashcan overrides this function on its flyout to make it always return true, so even disabled blocks can be "dragged out of" the flyout.
Disabled blocks should be able to be removed from the trashcan.
1. Added the below code at ~ln 124 in playground.
`workspace.addChangeListener(Blockly.Events.disableOrphans);`
2. Dragged a block from the toolbox to the workspace so it gets disabled.
3. Dragged disabled block to the trashcan.
4. Opened the trashcan and removed the disabled block. (pass)
Tested on:
N/A
> RetrieveDisabled Blocks from the Trashcan

- core/blockly.js
- tests/jsunit/theme_test.js
Changes description for theme event.
Change themeChanged to theme.
Changed is implied.
Tested on:
> Fix event description for theme

- blocks/lists.js
"independent" instead of "independant".
> Typo fix in code comment

- core/block.js
- core/block_svg.js
- core/theme/classic.js
- core/theme/highcontrast.js
- core/theme/modern.js
- tests/jsunit/block_test.js
- tests/jsunit/theme_test.js
- theme_scripts/create_blockStyles.py
#2262
Changes primaryColour -> colourPrimary, secondaryColour -> colourSecondary, tertiaryColour -> colourTertiary
To match Scratch-blocks and pxt-blockly
Tested on:
> Changes colour names

- core/bubble.js
#2277 
Makes it so that bubbles do not appear underneath simple toolboxes (flyouts as toolboxes).
I also found that it didn't always work when the workspace was zoomed, so I fixed that.
If the mutator appears underneath the toolbox it is inaccessible. This is bad behavior
Same strategy as [before](https://www.youtube.com/watch?v=JkVLbHiKtFk&feature=youtu.be), except this time with every position of flyout in LTR and RTL (it would be a *really* long video). 
Tested on:
1. I would like to try to add unit tests for this once the mocha stuff is more settled.
2. I left a TODO note that I think relativeLeft_ should be changed to relativeStart_, if you guys think this is reasonable I can switch the math over, in this PR or a follow up.
> Fixed Bubble Positioning With Simple Toolboxes

- core/inject.js
#2310 
Makes it so that every workspace on the page is updated on scroll instead of just the main one.
Now zoom on wheel will work even if the page has been scrolled.
1 .  Added the below code at ~ln 399 in [updateInverseScrenCTM](https://github.com/google/blockly/blob/d7e47c66b2ceb2aacfbb97bae42a1da093463dad/core/workspace_svg.js#L398) in workspace_svg.js:
`console.log(this.id);`
2 . Opened the multiplayground.
3 . Scroll the document. Observe how only 24 ids were logged, (main + flyout + trash flyout) * (8 instances). (pass)
1 . Added grid to multiplayground so the zooming was visible.
```
grid:
{
spacing: 25,
length: 3,
colour: '#ccc',
snap: false
},
```
2 . Enabled zoom with wheel on the multiplayground.
3 . Scrolled the document.
4 . Zoomed with the mouse wheel. Observed how the grid …
> Fixed Scroll Event Binding to Work with Multiple Workspaces

- blocks/lists.js
#2061 make list from text block throws uncaught Error
When switching the operation, disconnect the input block first, if the input block is a shadow, dispose it and make sure the shadow dom is null, otherwise bump it away.
The reason why I disconnect the input block is that if we change the operation, we change the type, and whatever got connected will have a type mismatch. Thus, to avoid the error, we need to make sure the block is disconnected.
The shadow is useless outside of the block, so I disposed the shadow.
If it is not a shadow, we want to keep it. After disconnecting, the input block stays at the same location, therefore we need to bump it away.
Because of #2312, the context menu is not working in the develop branch, so we cannot repro the bug in the develop branch.
Because of …
> Fix issue 2061 (make list from text block throws uncaught Error)

- core/inject.js
- core/toolbox.js
Reverts #2286 
#2312 by reverting the original change
Reverts the original change.
Code was causing issues with selecting values on dropdowns and context menus. 
Tested on:
> Reverts changes to fix bug with selecting dropdown

- core/events.js
- core/ui_events.js
- msg/messages.js
...and update a couple of help URLs.
> Fix bubble open/close events

- tests/blocks/test_blocks.js
- tests/playground.html
Fixes #2103.
This will break any saved XML involving the playground’s test blocks.  I don’t think any such XML exists on this planet.
> Common prefix for test blocks

- core/mutator.js
#2364
Updates call from getFlyout_() to getFlyout()
Tested on:
> Updates function call

- core/inject.js
#2362 
This reverts back a previous commit #2359 that was meant to fix this bug #2066. But instead broke many more things.
Tested on:
> Reverts hideChaff fix

- core/field_angle.js
> Angle picker's degree symbol left of number in both LTR and RTL.

- README.md
Part of setting up Sauce Labs testing.
> Add sauce labs to readme

- core/field.js
- core/field_number.js
#2169 
Validates the input value in setValue of field.js by using callValidator function
Proposed change in #2169 
Tested on:
Might potentially introduce redundancies in subclasses?
> Validate newValue parameter in setValue

- README.md
Update our Readme to include more explicit expectations and information about our release and prioritization process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2401)
> Add release and milestone information to Readme

- tests/mocha/index.html
- tests/mocha/navigation_test.js
Add tests!
Regression tests for navigation, since we'll be making lots of changes in that file.
Mocha tests added.
> Add tests for keyboard handling in the toolbox

- blockly_compressed.js
- build.py
Matches existing stripping of Google’s licence.  Done with MIT’s permission.  Resolves issue 2412.
"If you have a problem and you solve it with a regex, now you have two problems."
> Strip MIT’s licence out of compiled code.

- .eslintignore
- tests/mocha/block_test.js
- tests/mocha/index.html
- tests/mocha/run_mocha_tests_in_browser.js
- tests/run_all_tests.sh
PR 2 of 2 to pull this stuff over from develop, where we've already reviewed it.
This should fail on travis with a message that two mocha tests are failing.  
There are 3 tests failing on keyboard_nav.  One is the test in block_test, which I've fixed here.  The other two are in keyboard-nav related work and Abby will have to take a look at them.
> Run mocha tests in the browser on travis

- core/navigation.js
Stop using the insertionNode_ and check the marker instead.
Get rid of duplicate information.
> Get rid of insertionNode

- core/variables.js
Fix typo in createVariable documentation
Typos are bad
n/a
Tested on:
n/a
> typo fix in createVariable documentation in variable.js

- core/css.js
- core/cursor_svg.js
Marker not being distinct.
Set the colour of the cursor differently when it's a marker.
Checked in the playground.
> Make the marker blue on both blocks and input/output connections.

- core/navigation.js
Couldn't disconnect blocks before.
Capture the X key and break the connection that the cursor is pointing to.
Tested in the playground, by disconnecting inputs, outputs, and prev connections.
- The marker doesn't blink correctly after disconnecting an input/output connection.  Moving the marker with the keyboard shows that it is in the right place, but not showing up.
- There are lots of cases where this won't do anything.  We need to find a way to surface that, probably.
> Disconnect blocks with X

- tests/mocha/navigation_test.js
Adds very basic tests for insert functions: 
1. insertFromFlyout
2. insertBlockFromWs
3. insertBlockToWs 
Tested on:
> Add basic tests for insert functions

- core/navigation.js
Call `Blockly.Navigation.modify` to insert blocks from the flyout.
Inserting a block from the flyout and moving a block from within the workspace should have very similar code.  This unifies them.
Mocha tests pass (locally, at least) and I can add blocks from the flyout on the workspace and on connections.
If the blocks cannot connect, the new block just gets dropped onto the workspace.
> Use modify when inserting from the flyout

- blocks/logic.js
- blocks/loops.js
- blocks/procedures.js
- blocks/variables.js
- core/blockly.js
- core/extensions.js
- core/generator.js
- core/mutator.js
- core/toolbox.js
- core/touch.js
- core/useragent.js
- demos/code/code.js
- generators/dart/logic.js
- generators/dart/loops.js
- generators/dart/procedures.js
- generators/javascript/logic.js
- generators/javascript/loops.js
- generators/javascript/procedures.js
- generators/lua/logic.js
- generators/lua/loops.js
- generators/lua/procedures.js
- generators/php/logic.js
- generators/php/loops.js
- generators/php/procedures.js
- generators/python/logic.js
- generators/python/loops.js
- generators/python/procedures.js
Adding ability to insert suffix code after every statement.  All prefix code is guaranteed to have a suffix, and vice versa.
> Fraser suffix2

- core/inject.js
Traced one cause of Mocha tests sometimes failing to blocks being
bumped back into bounds. It looks like a block being moved to be
a child of another block ended up out of bounds probably
because the size of the workspace isn't set yet. When the change
handler tried to move it back in it would throw an error since you
can't move child blocks with that method.
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2467)
> Fix bug with in bounds bumping

- tests/screenshot/run_differ.sh
This was failing if I didn't pass a filter arg.
> Handle empty filter argument, in an ugly way

- blocks/lists.js
- blocks/math.js
- blocks/procedures.js
- blocks/text.js
- core/dropdowndiv.js
- core/field.js
- core/procedures.js
- demos/blockfactory/blocks.js
N/A
Adds a getSourceBlock function to the abstract field class.
Changes all references to sourceBlock_ in classes that are not field sub-classes to getSourceBlock() calls.
I believe it is better for validators to be kept ignorant of the inner workings of a field. While referencing sourceBlock_ inside of a validator is /technically/ legal, it doesn't feel safe and I think it's a bad habit for outside developers to get into.
Also the dropdownDiv was referencing sourceBlock_ when I believe it shouldn't, so its nice that there's an accessor now.
N/A
N/A
> Added getSourceBlock Function to Field

- core/block.js
- core/blockly.js
- core/theme.js
- core/theme/classic.js
- core/theme/highcontrast.js
- core/theme/modern.js
- core/toolbox.js
- core/xml.js
> Fix 19 warnings in theme-related code.

- core/field.js
- tests/mocha/field_angle_test.js
- tests/mocha/field_checkbox_test.js
- tests/mocha/field_colour_test.js
- tests/mocha/field_date_test.js
- tests/mocha/field_dropdown_test.js
- tests/mocha/field_number_test.js
- tests/mocha/field_test.js
- tests/mocha/field_textinput_test.js
- tests/mocha/field_variable_test.js
N/A
1. Adds tests to the abstract field to document setValue's structure.
2. Stubs console.warn and console.error for any tests where those functions get called.
3. Changes validator tests to be properly torn down.
4. Adds 'Validator Returns Undefined' tests to all fields.
@rachel-fenichel  I gave you some wrong information. You said you thought undefined means something and it does. If a validator returns undefined, we assume they're using the validator as a change function and ignore the returned value. So essentially it means "this value is good".
5. Makes post-class-validation respond to undefined values the same way post-local-validation does. I.E. if a class validator returns undefined, we ignore it there as well.
1. Makes sure that if anyone tries to refactor the setValue function …
> Added More setValue Test Coverage

- tests/screenshot/test_cases/multi_stack
- tests/screenshot/test_cases/test_cases.json
> Add test case for stacked blocks

- core/field.js
N/A
Makes it so isClickable now checks if the block is editable.
Support for non-editable blocks.
1) Set the `readOnly` workspace option to true. Observed how fields were not editable.
2) Set the `readOnly` workspace option to false. Observed how fields were editable.
Tested on:
N/A
> Fixed Fields Still Being Editable on Non-Editable Blocks

- core/field_colour.js
- core/field_date.js
#2544 
Makes it so the colour and date editors close when a value is selected.
Begone click-happy interface!
Tested on:
I wanted to do this in a seperate PR because I thought I would have to change the date editor CSS/updateEditor_ function to not look bad, but having actually changed it I think it looks fine as is. If you have suggestions I can change it though.
> Added Colour and Date Editor Auto-Close on Selection

- tests/screenshot/gen_screenshots.js
- tests/screenshot/run_differ.py
Add the ability to specify inline and external inputs.
Tested on:
> Adds option for testing external and internal inputs

- blocks/logic.js
- blocks/procedures.js
- core/block_svg.js
- core/blockly.js
- core/bubble.js
- core/field.js
- core/field_date.js
- core/field_textinput.js
- core/flyout_base.js
- core/options.js
- core/utils/coordinate.js
- core/workspace_svg.js
- demos/code/code.js
- demos/code/index.html
Some type annotations, some redeclared variables.  Note the removal of copy-pasted validation code in Field.prototype.setValue.
> Resolve 13 warnings

- core/block_rendering_rewrite/block_render_info.js
- core/block_rendering_rewrite/measurables.js
> Add a row after a dummy input.

- core/field_dropdown.js
N/A
Makes it so dropdowns containing image options and text options are properly rendered.
The old rendering was incorrect and buggy.
Old (develop) behavior:
New behavior:
Tested on:
N/A
> Fixed Rendering of Images & Text Dropdown

- generators/dart/colour.js
- generators/javascript/colour.js
- generators/lua/colour.js
- generators/php/colour.js
- generators/python/colour.js
The new validators already solve this problem, but as a second layer of defence, the generators should also be secured.  Issue #2637
> Fix colour injection vulnerability.

- core/utils/xml.js
- core/variables.js
Advanced compilation was failing.
Remove @package annotation from methods that were being used in different folders.
Tested on:
> Remove @packages annotation from public methods

- core/css.js
- core/field_number.js
> Revert "Adds type to FieldNumber editor"

- build.py
Add ability to pick a renderer at build time.
We are in the process of creating multiple renderers. We therefore need a way for users to choose which renderer they want to use.
Tested on:
This change was originally in the render/collab branch so this is just merging it over to develop.
> Adds ability to pick renderer at build time

- demos/custom-fields/index.html
- demos/index.html
Makes the demo publicly easier to find.
Add a link to the demo.
Demo is done and ready for release.
I will cherry-pick this.
> Link to custom fields demo from demos/index.html

- core/block_render_svg.js
- core/connection.js
- core/rendered_connection.js
- tests/mocha/connection_test.js
Reverts all of the changes related to #2003 because they cause rendering problems. The tests for the bug the original change was solving are left in but set to skip since they are no longer passing.
#2671 
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/2676)
> Revert changes related to #2003

- package.json
> Bump version on develop

- core/renderers/block_rendering_rewrite/block_render_draw.js
- core/renderers/block_rendering_rewrite/block_render_draw_debug.js
- core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
- core/renderers/block_rendering_rewrite/block_render_info.js
- core/renderers/block_rendering_rewrite/block_rendering_constants.js
- core/renderers/block_rendering_rewrite/measurables.js
Adds all of the new rendering files to the develop branch.
Does not use the files yet.
Rendering is happening!
Previously tested by screenshot testing.
Remaining todos are tracked internally.
> Pull all the new rendering files into develop

- .github/ISSUE_TEMPLATE/bug_report.md
Fixes the bug report template. This has already been tested in master.
Tested on:
> Fixes the bug report template

- demos/custom-fields/field_turtle.js
- demos/custom-fields/index.html
#2696 
Also Fixes IE (apprently someone thought classList was not an important property for SVGs)
* Makes it so the workspace renders correctly on Firefox (statically sets the height of the workspace).
* Makes it so the turtle field doesn't throw errors on IE (removes classList reference).
Demos should be usable on all browsers.
* Tested all of the toggle buttons.
* Tested round-tripping through XML.
* Tested that validators are working.
You can see #2691 for examples, I replicated the same procedure.
Tested on:
* Windows Edge
This is an update to the custom fields demo, so the demo should be republished once this and #2691 are both in.
N/A
> Fixes Custom Fields (Turtle) Demo Browser Support

- .github/ISSUE_TEMPLATE/documentation.md
Add a template asking the right questions for documentation issues.
I will also add this to master.
> Add template for documentation issues

- .github/ISSUE_TEMPLATE/documentation.md
See #2692 
Cherrypick to get this onto master so it shows up on github.
> Cherrypick of #2692

- core/block_svg.js
- core/connection.js
- core/css.js
- core/field.js
- core/input.js
- core/rendered_connection.js
- core/utils.js
This adds in the helper functions necessary for keyboard navigation.
Tested on:
> Adds helper functions for keyboard nav

- core/field_dropdown.js
> Typo: enutral -> neutral

- core/block.js
- core/field.js
- core/field_image.js
- core/field_variable.js
- tests/mocha/field_image_test.js
- tests/mocha/field_variable_test.js
N/A
* Deprecates the field's setText function.
* Adds a setAlt function to the image field.
* Adds an updateVariableName function to the variable field.
* Because the only access point should be setValue.
* So that developers can still manipulate the image field's alt.
* So that updating the variable name without updating the variable model still works & is efficient.
* Added unit tests for setting an image field's alt value (w/ backwards compatibility tests.
* Added unit tests for renaming a variable (keeping same id, and getting a new id).
Tested on:
Important: I'm not sure if the new variable field function should be called updateVariableName or updateVarName, there is inconsistency.
> Deprecated Field.setText

- README.md
This PR resolves the incorrect link provided for the blockly doc in the README.md file.
Adds a proper link for the blockly doc.
This change is required to fix redirecting to 404 for blockly doc.
_Not required._
> Add correct link for blockly doc in the README.md file

- tests/blocks/test_blocks.js
- tests/mocha/.eslintrc.json
- tests/mocha/astnode_test.js
- tests/mocha/cursor_test.js
- tests/mocha/index.html
- tests/mocha/navigation_modify_test.js
- tests/mocha/navigation_test.js
- tests/mocha/test_helpers.js
- tests/playground.html
Add tests for keyboard navigation: 
cursor tests
navigation tests
navigation modify method tests 
ast node tests
Tested on:
> Add tests for keyboard navigation

- demos/keyboard_nav/index.html
> Basic linting of Keyboard nav demo

- core/utils.js
Fix typos in screenToWsCoordinates jsdoc.
> Fix screenToWsCoordinates jsdoc

- .gitignore
- gulpfile.js
- package.json
- typings/README.md
- typings/blockly.d.ts
- typings/parts/blockly-header.d.ts
- typings/parts/blockly-interfaces.d.ts
- typings/parts/goog-closure.d.ts
- typings/tsconfig.json
Add TypeScript definition file for Blockly to be included in the ``npm`` package.
Added a README file describing how to include the dts in a project, and how to generate a new version of the dts.
> TypeScript Definition file

- gulpfile.js
- typings/blockly.d.ts
- typings/parts/goog-closure.d.ts
Removed goog.math typings as we've removed references to all goog.math from our repo.
> Update typings after removing references to goog.math

- core/constants.js
- core/dropdowndiv.js
- tests/mocha/dropdowndiv_test.js
- tests/mocha/index.html
#2640 
The dropdowndiv will now try to render outside the bounds of the workspace if it can't render inside the bounds.
It first tries to render below, but if that goes outside the /window/ bounds it renders above.
The old behavior looked kinda buggy.
Rendering Above:
Rendering Below:
Tested on:
N/A
> Fixed DropDownDiv Rendering On Small Workspaces

- core/renderers/block_rendering_rewrite/block_render_draw.js
- core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
- core/renderers/block_rendering_rewrite/block_render_info.js
- core/renderers/block_rendering_rewrite/block_rendering_constants.js
- core/renderers/block_rendering_rewrite/highlight_constants.js
Some work to position previous and next notches.
Check whether the highlighter exists before using it.
I think this is just moving 0.5s around, unfortunately.
> Position notches

- tests/compile/compile.sh
Currently closure complains that everything is in a different package when we put things in different folders. 
Copy over all files into a temp directory before compiling. 
Pass in a command line argument to choose the renderer at compile time.
Having multiple directories in core makes it more organized.
Tested on:
> Fix compile

- core/blockly.js
Undo was broken because of keyboard nav changes.
Fix undo!
Being able to undo is great.
Tested on:
> Fixes undo

- core/keyboard_nav/ast_node.js
- core/renderers/block_rendering_rewrite/block_render_info.js
- demos/blockfactory/block_exporter_controller.js
- demos/blockfactory/factory.css
- demos/blockfactory/factory_utils.js
- demos/blockfactory/index.html
- demos/blockfactory_old/factory.js
- demos/blockfactory_old/index.html
- generators/javascript.js
- generators/php/lists.js
- generators/php/text.js
- tests/generators/golden/generated.php
>  Fix injection vulnerability in Block Factories.

- package.json
Version bump for Node patch fix.
> Version bump for Node patch fix

- .gitignore
- gulpfile.js
- package.json
- package/README.md
- package/browser/core.js
- package/browser/index.js
- package/index.js
- package/node/core.js
- package/node/index.js
- package/templates/node.template
- package/templates/umd.template
- typings/README.md
- typings/blockly.d.ts
- typings/parts/blockly-header.d.ts
- typings/parts/blockly-interfaces.d.ts
- typings/parts/goog-closure.d.ts
- typings/tsconfig.json
This PR prepares tasks that help us release our compressed built files as UMD / CommonJS modules for distribution Blockly on NPM.
Note: this PR is against master. I've had to also pull in the Typescript blockly.d.ts changes defined in https://github.com/google/blockly/pull/2738.
https://github.com/google/blockly/issues/177
Package our built files into UMD modules.
In order to release Blockly on NPM.
I've build samples for different development environments at https://github.com/google/blockly-samples and tested locally via ``npm link ...``
I've added documentation throughout. 
The README.md file in this PR is what users will see that go to https://www.npmjs.com/package/blockly. 
There is a bunch more documentation at https://github.com/google/blockly-samples. 
I've also added comments in …
> NPM distribution

- core/inject.js
<sub>Small unmovable workspaces sound pretty depressing lol<sub>
#2681 
Object bumping now calculates a valid coordinate region for the object's anchor, and then clamps the anchor within that region. This was done to simplify the code for the following changes:
* If the  object is too tall for the workspace it is top-aligned.
* If the object is too wide for the workspace:
* In LTR it is left-aligned.
* In RTL it is right-aligned.
Bugs be bad.
Idk how to write tests for this since it relies on the event system, and the event system seems to break tests, so I did a bunch of manual testing:
Tested on:
Nope!
Comments may be a bit verbose, critiques are appreciated =)
> Fixed Object Jitter on Small Unmovable Workspaces

- tests/run_all_tests.sh
- tests/scripts/compile_typings.sh
Add a test script to compile typings and test on travis.
As per @rachel-fenichel's request.
This should help catch any typings issues early.
> Test script to compile Typings

- core/blockly.js
- core/gesture.js
- core/inject.js
- core/keyboard_nav/key_map.js
- core/keyboard_nav/navigation.js
- core/workspace_svg.js
- tests/mocha/key_map_test.js
- tests/mocha/navigation_modify_test.js
- tests/mocha/navigation_test.js
Blockly.Navigation should be Blockly.navigation.
Namespaces should be lowercase.
Tested on:
> Make the navigation namespace lowercase

- core/block_render_svg.js
- core/icon.js
Remove unused code.
Remove unused code.
> Remove renderIcon function

- core/renderers/block_rendering_rewrite/block_render_draw.js
- core/renderers/block_rendering_rewrite/block_render_draw_debug.js
- core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
- core/renderers/block_rendering_rewrite/measurables.js
814 compiler warnings -> 745 compiler warnings
Add some missing annotations
Compiler warnings
Still works in the playground
None
> Fix some compiler warnings

- core/renderers/block_rendering_rewrite/block_render_info.js
Creates that top and bottom rows immediately, so that they can be annotated non-null.
> Guarantee that the top and bottom rows exist

- core/field_number.js
- core/field_textinput.js
Add valuemin and valuemax aria properties for number fields
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuemin_attribute
Accessibility
> Aria valuemin/max for number fields

- tests/mocha/index.html
- tests/mocha/names_test.js
https://github.com/google/blockly/issues/2870
Convert names_test jsunit test to mocha.
Explained in linked issue.
Will remove from jsunit in a separate cleanup PR.
> Convert names_test from jsunit to mocha.

- tests/mocha/connection_db_test.js
- tests/mocha/index.html
https://github.com/google/blockly/issues/2870
Convert connection_db jsunit test to mocha.
Explained in linked issue.
Will remove from jsunit in a separate cleanup PR.
> Convert connection_db jsunit tests to mocha

- package.json
I just realized they are meant to be in alphabetical order, I had messed up the order recently. 
Reordering..
> Reorder package.json.

- core/field.js
- core/field_colour.js
[Request from Sam
](https://github.com/google/blockly/pull/2876#issuecomment-523595211)
Moves configuration tasks into a private function.
Also adds link jsdoc param to colour field.
That readability yo.
Already covered by tests.
Nope, purely internal change.
N/A
> Changed Field and Colour Constructors to use Better Organization

- demos/custom-fields/index.html
- demos/custom-fields/pitch/field_pitch.js
- demos/custom-fields/pitch/index.html
- demos/custom-fields/turtle/index.html
https://github.com/google/blockly/pull/2930
Field pitch remaining PR fixes that were missed in previous PR due to Github's hidden comments UI..
PR feedback.
> Field pitch remaining fixes that were missed in previous PR.

- core/keyboard_nav/navigation.js
- tests/mocha/.eslintrc.json
- tests/mocha/navigation_modify_test.js
- tests/mocha/navigation_test.js
- tests/mocha/test_helpers.js
Refactors modify and cleans up some TODOs. 
The only change in functionality is if the workspace is marked and the cursor is on a next or an input connection it will move the source block to the workspace. Previously, it did not move the block and warned the user that this action was not allowed. We changed insert to be a bit more aggressive in trying to find a way to connect two blocks given a connection, so trying to do the same thing here.
Tested on:
> Refactors modify and add tests

- core/renderers/common/constants.js
- core/renderers/common/debugger.js
- core/renderers/common/drawer.js
- core/renderers/common/info.js
- core/renderers/common/renderer.js
- core/renderers/geras/highlight_constants.js
- core/renderers/geras/highlighter.js
- core/renderers/geras/info.js
- core/renderers/geras/renderer.js
- core/renderers/measurables/base.js
- core/renderers/measurables/connections.js
- core/renderers/measurables/inputs.js
- core/renderers/measurables/row_elements.js
- core/renderers/measurables/rows.js
- core/renderers/thrasos/info.js
- core/renderers/zelos/constants.js
- core/renderers/zelos/drawer.js
- core/renderers/zelos/info.js
- core/renderers/zelos/renderer.js
- [ x] My pull request is against develop
Lint, more or less.
Alphabetize all of the requires in rendering code.
> Alphabetize requires

- demos/custom-fields/turtle/index.html
#2998 
Adds hideChaff calls when the editability and collapsed...ness change.
Avoid dumb looking behavior.
Tested on:
N/A
Thanks for the catch Neil!
> Added hideChaff calls to the custom fields demo

- blocks/lists.js
- blocks/logic.js
- blocks/loops.js
- blocks/math.js
- blocks/procedures.js
- blocks/text.js
- blocks/variables.js
- blocks/variables_dynamic.js
Fixes 9 compiler warnings.
- Replace `@this Blockly.Block` with `@this {Blockly.Block}` in all block files.
- Fix 9 compiler warnings (JSC_USED_GLOBAL_THIS)
- Most documentation has the curly braces
- Compiler warnings
Only annotation changes.
No
> Block annotations

- core/requires.js
- tests/compile/main.js
> Fix compiled test.

- core/keyboard_nav/ast_node.js
- tests/mocha/astnode_test.js
Moving around the cursor on the workspace was a bit weird. We used the up and down arrows to move the cursor from left to right. 
Remove the ability to move around the workspace until we figure out the best way to do that. 
Tested on:
> Remove moving on the workspace

- core/block.js
- core/block_svg.js
- core/field.js
- core/field_colour.js
- core/field_image.js
- core/field_textinput.js
- core/renderers/measurables/row_elements.js
Check if a type exists before instance of in case a field doesn't exist.
> Check if a type exists before testing instanceof

- blocks/colour.js
- blocks/lists.js
- blocks/logic.js
- blocks/loops.js
- blocks/math.js
- blocks/procedures.js
- blocks/text.js
- blocks/variables.js
- blocks/variables_dynamic.js
- build.py
- gulpfile.js
Allows each set of blocks to pull in the correct fields when they are used in a compiled application.
> Add require statements to all block files.

- blocks/procedures.js
- tests/mocha/index.html
- tests/mocha/procedures_test.js
- tests/mocha/xml_procedures_test.js
N/A
Adds more unit tests for procedures. In particular mutator tests for the things I broke, as well as some deserialization tests.
So Beka doesn't break things (silly Beka).
As always there are todos for changes and clarifications.
> Added More Procedure Unit Tests

- blocks/procedures.js
- build.py
- core/block.js
- core/block_svg.js
- core/requires.js
- gulpfile.js
Measured as a 5 KB *increase* in code size, but that's because some other commit just landed between my tests.  It's like running down an up escalator.
> Make block comments an optional module.

- core/field_angle.js
- tests/blocks/test_blocks.js
- tests/mocha/field_angle_test.js
- tests/playground.html
Work on #2722 
* Adds config options: clockwise, offset, wrap, and round to the angle field.
* Fixes up a little thing with keyboard nav and wrapping.
* Standardization of Configuration.
* Bugs be bad.
Added the following test blocks to the playground:
* Clockwise
* Offset 90
* Wrap 180
* Round 30
* No Round (0)
* Protractor Mode
* Compass Mode
For each of them I tested:
* Mouse Input
* Keyboard Nav Input
* Keyboard... key? Input
I also added unit tests for:
* Clockwise
* Offset
* Wrap
* Round
* Compass
* Protractor
Tested on:
Updates [here ](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/angle#creation) and [here](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/angle#customization).
Also …
> Added angle field config

- README.md
Update README with new npm instructions.
Outdated instructions.
> Update README with new npm instructions.

- core/field_colour.js
- core/field_dropdown.js
- core/keyboard_nav/ast_node.js
- core/keyboard_nav/cursor.js
- core/keyboard_nav/navigation.js
1. When a field wasn't open it was still trying to handle blockly actions.
2. When the cursor was on a field on the workspace and we were trying to navigate the flyout it would give the action to the field to try and handle.
3. If a user had gone to a block in the flyout previously and then switched to a flyout with no blocks it would throw an error when a user tried to move up and down within the flyout.
1. Check if the field is open or not before handling the action.
2. Move this logic for passing the action to a field into the workspace section of onBlocklyAction.
3. The error was because the workspace on the block was null. So check for null before trying to navigate to the next stack.
So that it can be slightly less broken. 
** Need to add tests ** 
Tested on:
> A bunch of small bug fixes

- core/gesture.js
- core/keyboard_nav/navigation.js
- core/toolbox.js
1. If a user tried to use both the keyboard and the mouse for keyboard navigation the states wouldn't be in sync and everything would break. 
2. Hitting out on a flyout without a toolbox was causing an error.
Keep the navigation state updated when the user moves around using the mouse.
Fixed Scenarios: 
1. User clicks on the toolbox and then uses keyboard navigation to move around.
2. User is in the toolbox using keyboard navigation and then clicks on the workspace. 
3. User is in the flyout using keyboard navigation and then drags a block to the workspace. 
4. User is in the toolbox using keyboard navigation and then clicks on the category to close the toolbox.
Tested on:
> Fix interaction between mouse and keyboard

- build.py
- core/requires.js
Simplify the generated JavaScript.  Include needed require statements.
> Build improvements

- core/keyboard_nav/navigation.js
Comments and organization of the navigation file was out of date. 
Group similar methods together and add comments.
Tested on:
> Cleanup navigation file

- .gitignore
- package-lock.json
- tests/run_all_tests.sh
- tests/scripts/check_metadata.sh
Adds a script test for building Blockly's compressed files and
checking their size to prevent unexpected increases.
Fixes #3052 
Adds a script test for building Blockly and comparing the size against a previous value. This test will need to be updated each release. We could also compare against the files currently on the master branch, but we may want to manually update the size when appropriate instead of allowing continuous growth over multiple releases.
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3075)
> Add a test for built file size

- core/block.js
- core/insertion_marker_manager.js
- core/keyboard_nav/ast_node.js
- core/keyboard_nav/cursor.js
- core/keyboard_nav/cursor_svg.js
- tests/mocha/astnode_test.js
Had a few minutes free.
There are also some post-submit comments on https://github.com/google/blockly/pull/3074
> Partial code review of nav

- core/keyboard_nav/navigation.js
Fixes left over review comments from #3074.
Tested on:
> More navigation cleanup

- core/field_angle.js
- core/field_checkbox.js
- core/field_colour.js
- core/field_image.js
- core/field_label.js
- core/field_label_serializable.js
- core/field_number.js
- core/field_textinput.js
Clean up fields by passing the right type in fromJson.
Non functional change, pass the right type to the constructor in fromJson.
Types.
@BeksOmega FYI
> Cleanup fields

- tests/workspace_svg/index.html
Renables test fixed with issue #1960
Tests are good.
Test passes.
> Re-enable block delete test.

- tests/multi_playground.html
Changing the theme wasn't changing the color of the categories for the multi playground.
Tested on:
> Fix changing category color in multi playground

- .eslintignore
- .gitignore
- gulpfile.js
- package.json
- tests/node/run_node_test.js
Cleanup.
Removed old node module bundle and updated tests to use the new ``npm`` packaged one.
Clean up.
Tested node test locally. Waiting for travis.
> Remove old node module, update tests to use the npm one.

- core/block.js
- core/blockly.js
- core/css.js
- core/extensions.js
- core/requires.js
> Make generator an optional module

- core/dropdowndiv.js
Removes TODO referencing closed bug #2744. 
Cleanup.
> Removing obsolete TODO comment.

- core/workspace.js
- tests/jsunit/xml_test.js
- tests/mocha/xml_test.js
Adds test and updates TODO comment for closed bug #1199.
Cleanup and additional test coverage.
Ran tests.
> Adding test and updating TODO.

- core/css.js
- core/trashcan.js
- tests/playground.html
- typings/blockly.d.ts
Also delete unused props in CSS.
> Simplify trashcan code

- core/requires.js
Add the themes to the require.js file.
Tested on:
> Add theme requires

- core/block.js
- core/block_svg.js
- core/connection.js
- core/rendered_connection.js
- tests/mocha/connection_test.js
N/A
Moves all connection database related code out of headless and into rendered.
Work towards possibly moving to a 'tracked_' property in connections.
Also code health.
Enabled connection tests.
N/A
Related to #2994
> Connection Tracking Pt 2: Moved all database related code out of headless

- core/renderers/minimalist/constants.js
- core/renderers/minimalist/drawer.js
- core/renderers/minimalist/info.js
- core/renderers/minimalist/renderer.js
- tests/playground.html
Rename sample renderer to minimalist
> Rename sample renderer to minimalist

- core/components/component.js
- core/components/menu/menu.js
- core/components/tree/treecontrol.js
> Fix 6 warnings in components/

- core/block_animations.js
- core/block_drag_surface.js
- core/block_svg.js
- core/bubble.js
- core/comment.js
- core/field.js
- core/field_angle.js
- core/flyout_base.js
- core/flyout_button.js
- core/mutator.js
- core/trashcan.js
- core/workspace_comment_svg.js
- core/workspace_drag_surface_svg.js
- core/zoom_controls.js
None
No functional changes.
Replaces lots of Element annotations with SVGElement annotations to make them stricter.  I went through and looked at the results of createSVGElement and updated them, mostly.
I'm poking at annotations of elements and nodes and so on.
> Element -> SVGElement

- core/block.js
- core/block_svg.js
Fixes 20 warnings.
Add annotations for possible functions that appear on the block.
Tested on:
> mutation / compose fn annotations

- core/block_events.js
- core/events.js
- core/events_abstract.js
- core/inject.js
- core/ui_events.js
- core/variable_events.js
- core/workspace_events.js
- core/ws_comment_events.js
Fix 23 warnings.
Fix 23 warnings in event related code.
Tested on:
> Fix compiler warnings related to events.

- typings/blockly.d.ts
Rebuild typings in prep for release.
> Rebuild typings

- blocks/procedures.js
- core/blockly.js
- core/bubble.js
- core/bubble_dragger.js
- core/comment.js
- core/inject.js
- core/mutator.js
- core/workspace.js
- core/workspace_svg.js
- demos/code/code.js
- demos/custom-fields/turtle/index.html
- tests/generators/index.html
- tests/jsunit/workspace_test.js
- tests/jsunit/xml_test.js
- tests/mocha/xml_procedures_test.js
- tests/playground.html
- tests/screenshot/gen_screenshots.js
- tests/workspace_svg/workspace_svg_test.js
6 Compiler warnings.
getAllBlocks requires an argument
Use ws.getToolbox() instead of ws.toolbox_
Compiler warnings.
Tested on:
> Misc compiler warnings.

- core/mutator.js
#3170 
* Readds resizeBubble_ call.
* Fixes the jsdoc on resizeBubble_.
* Fix bug.
* Prevent Beka from breaking things.
I was going to put up a proper fix, as referenced in #3170. But it started getting _way_ more complicated than something I was willing to put up as a release fix.
So I went with Sam's suggestion and just added the call back in.
Manually tested opening and closing mutators. No stuttering was visible.
Tested on:
* Windows Edge
N/A
I'll put up a proper fix once I have time to polish, write tests, etc.
> Re-added resizeBubble_ call. Fixed resizeBubble_ JSDoc.

- core/field.js
- core/field_angle.js
- core/field_number.js
- core/field_textinput.js
- tests/mocha/field_angle_test.js
- tests/mocha/field_number_test.js
null was being converted to 0 by Number() when it should cause the
default value to be set instead. This updates FieldNumber to handle
nulls correctly.
Fixes #3177
Should be cherry-picked
Fixes #3177
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3179)
> Set correct defaults for Field min/max/precision

- demos/index.html
Fixes #3181.
Change 'K' to 'k'.
Tested on:
> Fix capitalization

- demos/index.html
Fixes #3181 
Cherry pick #3182 into release candidate
Tested on:
> Fix capitalization (#3182)

- core/renderers/common/constants.js
- core/renderers/common/info.js
- core/renderers/geras/highlighter.js
- core/renderers/measurables/inputs.js
- core/renderers/measurables/rows.js
- core/renderers/zelos/constants.js
Delete some, and make another into a tracked issue.
Fixes #2854
> Clean up todos.

- core/field.js
- core/field_angle.js
- core/field_number.js
- core/field_textinput.js
- tests/mocha/field_angle_test.js
- tests/mocha/field_number_test.js
null was being converted to 0 by Number() when it should cause the
default value to be set instead. This updates FieldNumber and
FieldAngle to handle nulls correctly. Also update jsdoc.
Fixes #3177
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3195)
> Set correct defaults for Fields (#3179)

- core/block.js
- core/connection.js
- core/keyboard_nav/ast_node.js
- core/keyboard_nav/cursor_svg.js
- core/keyboard_nav/key_map.js
- core/keyboard_nav/navigation.js
- core/workspace.js
- core/workspace_svg.js
- tests/mocha/connection_test.js
Fixes a bunch of compiler warnings.
Less trivial changes: 
1. Changed canConnectWithReason and checkConnection from private to package so I could use in navigation.
2. Changed getTopStackBlock in block to package. 
3. Changed getSourceBlock in connection to return !Blockly.Block since it doesn't look like it can be set to null anywhere. 
4. Create methods for ASTNodes handle being given a null value and return null if this is the case.
5. Never let the cursor_ or marker_ on the workspace be null.
Tested on:
> Fix compilier warnings for keyboard nav

- core/gesture.js
Removes 12 warnings.
Initialize drag delta to 0, 0.
Update annotation to non-null.
Improve type checking.
Dragged stuff on the playground.
None
> Initialize drag delta to (0,0) and update annotation.

- core/field.js
Cherry pick https://github.com/google/blockly/pull/3205 into the release branch.
> [cherry-pick] Fix #2811 (#3205)

- core/field_angle.js
- tests/mocha/field_number_test.js
Tested on:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly/3229)
> Cleanup for #3179

- core/components/component.js
- core/components/tree/basenode.js
- core/components/tree/treecontrol.js
Update:
@private {type} to be
@type {type} 
@private 
Jsdocs are complaining
Tested on:
> Fix jsdoc syntax

- core/block_svg.js
- core/gesture.js
- core/icon.js
- core/renderers/common/info.js
- core/renderers/measurables/rows.js
Todos shouldn't be visible in jsdocs
Tested on:
> Update todos so they are no longer in jsdocs

- core/block_svg.js
- core/gesture.js
- core/icon.js
- core/renderers/common/info.js
- core/renderers/measurables/rows.js
> Cherry pick Update todos so they are no longer in jsdocs (#3250)

- core/flyout_horizontal.js
- core/keyboard_nav/cursor_svg.js
- core/keyboard_nav/navigation.js
- core/renderers/zelos/constants.js
Some obvious code inefficiencies spotted while randomly browsing the compressed file.
> Minor cleanup in keyboard nav

- gulpfile.js
Build process improvements
Create gulp tasks for syncing develop and recompiling on a clean branch.
Note: these aren't wired into `scripts` yet.
Playing around with gulp.
@samelhusseini to look at structure before I go much further with this.
> Rebuild task in gulp.

- package.json
@rachel-fenichel 
Print the summary output of the closure compiler in the console after a debug compile.
Tested on:
> Print debug compile output

- blocks/procedures.js
- core/block_svg.js
- core/blockly.js
- core/connection.js
- core/generator.js
- core/insertion_marker_manager.js
- core/variable_map.js
- core/workspace.js
Fix 11 warnings.
Fix warnings by passing the right number of arguments to methods.
Tested on:
> Fix 11 warnings related to number of arguments passed.

- core/options.js
- core/workspace.js
- core/workspace_svg.js
Fix 14 compiler warnings.
Tested on:
> Fix 14 warnings related to workspace svg

- core/block_svg.js
- core/comment.js
- core/field.js
- core/gesture.js
- core/keyboard_nav/navigation.js
- core/workspace_svg.js
Fix 11 warnings related to block_svg
Compiler warning fixes.
Tested on:
> Fix 11 warnings related to block_svg

- core/dropdowndiv.js
- core/field.js
- core/field_multilineinput.js
- core/field_textinput.js
- core/tooltip.js
- core/utils/style.js
Fix compiler warnings.
Fix 4 misc warnings.
Tested on:
> Fix 4 misc warnings

- build.py
- gulpfile.js
Build is breaking due to the JS environment sweep (#3269).
> Add missing utils.global

- gulpfile.js
More release automation.
Task to create a release candidate from develop and push it to github.
Automation.
> Add task to create a release candidate.

- core/block_svg.js
- core/insertion_marker_manager.js
Closes #3299 
Removes positionNewBlock.
Makes positionNearConnection package.
Code health.
There was only [one place](https://github.com/google/blockly/search?q=positionNewBlock&unscoped_q=positionNewBlock) this function got called, and I fixed it.
Tested insertion markers, and they work fine.
Tested on:
N/A
N/A
> Removed positionNewBlock

- core/block.js
- core/variable_map.js
- core/variables.js
- core/variables_dynamic.js
- core/workspace.js
Fix compiler warnings.
Fix 11 warnings related to variables and variable_model.
Tested on:
> Fix 11 warnings related to variables and variable_model.

- core/keyboard_nav/cursor.js
- core/ui_menu_utils.js
- core/utils.js
- core/utils/colour.js
8 compiler warnings.
Mostly checking for null types.
Tested on:
> Fix 8 warnings related to utils.

- core/scrollbar.js
Fix 3 compiler warnings.
Tested on:
> Fix scrollbar warnings.

- core/renderers/common/info.js
Resolves https://github.com/google/blockly/issues/3313
Account for output connection width when aligning statement row.
Tested on:
> Fix for #3313

- core/renderers/common/info.js
Cherry-pick fix for #3313 (#3316)
> Cherry-pick fix for #3313 (#3316)

- blocks/logic.js
- core/block.js
- core/block_dragger.js
- core/block_svg.js
- core/connection.js
- core/connection_db.js
- core/insertion_marker_manager.js
- core/keyboard_nav/navigation.js
- core/rendered_connection.js
- tests/mocha/connection_db_test.js
- tests/mocha/connection_test.js
Fix 47 compiler warnings related to connections.
All visibility changes.
Renamed connection. ``x_`` to ``x`` and made it package.
Renamed connection. ``y_`` to ``y`` and made it package.
Renamed connection.``checkType_`` to ``checkType`` and made it package.
Renamed connection.``tighten_`` to ``tighten`` and made it package.
Renamed connection.``lastConnectionInRow_`` to ``lastConnectionInRow`` and made it package.
Renamed block.``moveConnections_`` to ``moveConnections`` and made it package.
Changed ``connection.makeConnection_`` from private to protected.
Changed ``connection.connect_`` from private to protected.
Tested on:
> Fix warnings related to connections.

- core/block.js
- core/block_dragger.js
- core/block_svg.js
- core/blockly.js
- core/contextmenu.js
- core/gesture.js
- core/touch.js
- core/workspace.js
- core/workspace_comment_svg.js
Resolve remaining compiler warnings with visibility issues
Added wrappers around blockDb_ to set a block and remove it.
Renamed block / comment.``moveToDragSurface_`` to ``moveToDragSurface`` and made it @package.
Renamed block.``showHelp_`` to ``showHelp`` and made it @package.
Renamed Blockly.``duplicate_`` to ``duplicate`` and made it @package.
Renamed Blockly.``longStart_`` to ``longStart`` and made it @package.
Tested on:
> Resolve remaining compiler warnings with visibility issues

- core/keyboard_nav/ast_node.js
- core/keyboard_nav/cursor.js
- core/keyboard_nav/cursor_svg.js
- core/keyboard_nav/navigation.js
#3258
Dispatch a ui event when a cursor changes location or when a marker is placed. 
Also moves getSourceBlock from navigation to astnode because it should have been there all along.
This will be really helpful when we start testing what to say when a user is moving around with the cursor. Also at the summit it seemed pretty common for people to want to do something every time the cursor changes location.
Tested on:
> Fire UI events when cursor moves or a marker is added

- core/block.js
- core/block_drag_surface.js
- core/block_svg.js
- core/blockly.js
- core/contextmenu.js
- core/events.js
- core/extensions.js
- core/grid.js
- core/keyboard_nav/ast_node.js
- core/workspace.js
- core/workspace_audio.js
- core/workspace_svg.js
Resolve remaining type mismatch warnings.
Misc fixes. Marked the functional changes in comments.
Tested on:
> Resolve remaining compiler type warnings

- core/bubble.js
- core/comment.js
- core/icon.js
- core/mutator.js
- core/warning.js
Fixes 10 compiler warnings.
Renamed bubble.``promote_`` to ``promote`` and made it package.
Fixed up iconXY's null type in various places.
Tested on:
> Fix warnings related to icons and bubbles

- core/options.js
- core/touch_gesture.js
- core/workspace_svg.js
#2782
Adds pinch zoom option.
Allows for pinch zoom to be configured.
Tested on:
> Adding pinch zoom config option.

- tests/playground.html
Fix #3185 
Removes the creation of the `a1` variable that could otherwise cause an error to occur.
Tested on:
jsunit tests on Dektop Chrome Version 77.0.3865.120 (Official Build) (64-bit)
> Fix 'add test variable' button not working

- core/touch_gesture.js
Crash when dragging any block.
```
touch_gesture.js:94 Uncaught TypeError: Cannot read property 'options' of null
at new Blockly.TouchGesture (touch_gesture.js:94)
at Blockly.WorkspaceSvg.getGesture (workspace_svg.js:2516)
at Blockly.BlockSvg.onMouseDown_ (block_svg.js:752)
at SVGGElement.wrapFunc (blockly.js:482)
Blockly.TouchGesture @ touch_gesture.js:94
Blockly.WorkspaceSvg.getGesture @ workspace_svg.js:2516
Blockly.BlockSvg.onMouseDown_ @ block_svg.js:752
wrapFunc @ blockly.js:482
touch_gesture.js:94 Uncaught TypeError: Cannot read property 'options' of null
at new Blockly.TouchGesture (touch_gesture.js:94)
at Blockly.WorkspaceSvg.getGesture (workspace_svg.js:2516)
at flyout_base.js:607
at SVGGElement.wrapFunc (blockly.js:484)
```
Introduced by …
> Fix touch gesture

- core/generator.js
- core/names.js
- generators/dart/loops.js
- generators/javascript/lists.js
- generators/javascript/loops.js
- generators/javascript/text.js
- generators/lua/lists.js
- generators/php/loops.js
- generators/python/math.js
Following on from https://github.com/google/blockly/pull/3350 but these are warnings in block generator code.
Mostly re-declared variables and some visibility issues.
Compiler warnings.
Tested on:
> Fix warnings in block generator code

- core/block.js
- core/block_svg.js
- core/connection.js
- core/contextmenu.js
- core/field.js
- core/keyboard_nav/ast_node.js
- core/renderers/measurables/connections.js
- core/renderers/zelos/info.js
- core/utils/dom.js
- core/workspace_svg.js
Compiler warnings.
Fix warnings for code used by blocks.
Tested on:
> Fix warnings for code used by blocks

- core/theme/deuteranopia.js
> Fix colour

- blocks/loops.js
- blocks/procedures.js
- build.py
- core/block_svg.js
- core/renderers/measurables/types.js
- core/requires.js
- gulpfile.js
> Make warnings an optional module.

- core/block_svg.js
- core/flyout_base.js
- core/keyboard_nav/cursor.js
- core/keyboard_nav/flyout_cursor.js
- core/keyboard_nav/navigation.js
Adds feature requested in #3244
Make it easier for users to add new actions. Move onBlocklyAction to the cursor so that users can create a new cursor and override this method if they want to add new actions.
*This pr only adds support for adding new shortcuts to the workspace.
Want to make it easier for users to add new actions.
Tested on:
> Action update

- core/bubble.js
- core/comment.js
Work on #2152
Saves event data for bound events, and properly disposes of it.
Proper memory handling.
I ran the following stress test while doing a performance profile:
```
function memoryStrike(n) {
var toggleCount = 0;
var block = /** @type Blockly.BlockSvg */Blockly.Xml.domToBlock(Blockly.Xml.textToDom(
'<block type="controls_if">' +
'</block>'), workspace);
for (var i = 0; i < 1000; i++) {
block.mutator.setVisible(true);
block.mutator.setVisible(false);
toggleCount++;
}
console.log(toggleCount);
}
```
The following are the profiles from my tests. You can view them by opening the chrome console, going to the performance tab, and clicking "Load profile...".
[Profile-Orig.zip](https://github.com/google/blockly/files/3833694/Profile-Orig.zip)
6190 Listeners …
> Fixed comment event listener disposal.

- .travis.yml
https://github.com/google/blockly/issues/2582 means we should be fine now.
Needs travis to run to check.
> Add Node 12 back to our travis matrix

- core/css.js
- core/field.js
- core/field_textinput.js
- core/renderers/common/constants.js
- tests/mocha/field_angle_test.js
- tests/mocha/field_number_test.js
- tests/mocha/field_textinput_test.js
- tests/mocha/procedures_test.js
Pixel perfect input.
Related to https://github.com/google/blockly/issues/2694. We still need to know the font height.
Fix sizing of text input field in zelos. 
Fix sizing issues in other browsers. 
Rendering.
Tested the playground with both geras, thrasos and zelos.
Tested on:
> Field textinput pixel perfect input

- core/block_svg.js
- core/keyboard_nav/cursor.js
Fixes https://github.com/google/blockly/issues/3452
Don't show editor if the current node has not changed.
Fixed bug.
Tested on:
> Fix bug with tabbing out of Blockly

- core/renderers/common/constants.js
Improved documentation.
Add jsdoc.
All values are package and not const right now.
Document things that become APIs.
Only added comments.
> Add comments to many rendering constants

- tests/rendering/zelos/pxtblockly.html
- tests/rendering/zelos/zelos.html
Update zelos rendering playground so that screenshots reflect the state of the workspace.
Testing.
Tested the thing I'm using to test things.
Tested on:
> Update zelos rendering playground

- blockly_uncompressed.js
- core/flyout_base.js
- core/keyboard_nav/marker.js
- core/keyboard_nav/navigation.js
- core/marker_manager.js
- core/workspace.js
- core/workspace_svg.js
- tests/mocha/cursor_test.js
- tests/mocha/navigation_modify_test.js
- tests/mocha/navigation_test.js
Adding the ability to have multiple markers on the workspace.
Add a marker manager that will manage all the markers and the cursor.
We want to be able to have multiple markers.
Tested on:
> Marker manager

- core/options.js
> Restore support for 0-length grid lines.

- core/keyboard_nav/key_map.js
- demos/keyboard_nav/index.html
- tests/mocha/key_map_test.js
- tests/mocha/navigation_test.js
Fixes #3375
1. Always serialize a key in the order of the valid modifiers, not the order that the modifiers are given.
2. Make key map methods public. 
Tested on:
> Fix key map

- core/flyout_base.js
- core/flyout_button.js
- core/inject.js
- core/scrollbar.js
- core/theme/dark.js
- core/toolbox.js
- core/workspace_svg.js
I added a comment to #3113 about changing the names but never updated in the code.
Update component names 
Tested on:
> Update component names

- core/mutator.js
https://github.com/google/blockly/pull/3527#discussion_r363971153
Changed new getWorkspace function on mutator icon to package.
Keep codebase as package as possible.
Tested on:
No testing necessary.
N/A
N/A
> fix: Changed mutator getWorkspace to package.

- core/renderers/common/constants.js
- tests/compile/compile.sh
- tests/compile/index.html
- tests/compile/main.js
Fixes #3397
Use valid['colourPrimary'] instead of valid.colourPrimary
Working on it.
Tested on:
Still not sure why this was happening for blockly games but I couldn't reproduce in blockly demos where we use compressed.
> Fixes blockly games blocks being black

- tests/blocks/test_blocks.js
- tests/playground.html
N/A
Adds blocks that test the connection system (typed connections, "missing" connections, and non-movable blocks).
I also moved the field blocks to the bottom of the test toolbox.
The "insert" buttons insert the set of blocks shown to the left (for each respective screen shot).
And as the toolbox suggests all of the blocks have tooltips to explain how they work. But simply:
* Greys:
* Have permiscuous (untyped) connections so they can connect to anything.
* Blues:
* Top/Left: None.
* Bottom/Right: Only yellow.
* Yellows:
* Top/Left: Blue, yellow.
* Bottom/Right: Yellow, red.
* Reds:
* Top/Left: Only yellow.
* Bottom/Right: None.
I've been using these for a while, and I think they're useful for testing!
N/A
N/A
> test: Added connection test blocks.

- typings/blockly.d.ts
Ran ``npm run typings``.
Tested on:
> Update Typings in preparation for release

- gulpfile.js
Recompile typings in the release script. 
Tested on:
> Rebuilds typings for release script

- gulpfile.js
- package.json
Revert package.json version change (as we should only change it when it goes into master)
Rename release tasks for clarity, remove gulp 'release' task as its redundant. 
Tested on:
> Release tasks renames

- gulpfile.js
Creates a branch called gh-pages and pushes so we have a place to test the changes after a release.
Tested on:
> Add push to github pages after build

- tests/blocks/test_blocks.js
Fixes `test_align_all` block definition.
> Fix test align block.

- core/mutator.js
- core/toolbox.js
- core/workspace_svg.js
#3644
Sets toolboxPosition after options are parsed.
Tested on:
> Fix flyouts

- package.json
Bumping version for release
Tested on:
> Bump version for January 2020 release

- appengine/app.yaml
Bump appengine version number
Tested on:
> Bump appengine version number

- core/renderers/common/info.js
- core/renderers/measurables/rows.js
- core/renderers/zelos/measurables/rows.js
Start hats don't respect the ADD_START_HATS constants.
Check for empty string of hat, which is what's set [here](https://github.com/google/blockly/blob/master/core/renderers/common/constants.js#L662)
Fix bug.
Tested on:
> Fix start hats

- blocks/procedures.js
- core/field.js
- core/field_angle.js
- core/field_dropdown.js
- core/field_textinput.js
Fix typo "programatically" > "programmatically"
> Fixing typo on "programmatically".

- core/options.js
#3661
Updating path referenced in comment.
Path was incorrect.
> Fixing path typo.

- core/block_svg.js
Fixes #3669
Checks keyboard accessibility mode is on before rendering the cursor.
Tested on:
> Checks keyboardAccessibility flag before rendering

- core/theme.js
- core/theme_manager.js
Just remove the check in theme that checks if it is the same object. This already does all the refresh logic that we need so by removing this check we can call setTheme(Blockly.Themes.Classic) and it will refresh properly.
People want to be able to easily add block styles and category styles to the default themes. We don't really have a good path for them to change this.
Tested on:
> Remove check for same theme when refreshing

- appengine/.gcloudignore
- appengine/app.yaml
- appengine/deploy
- appengine/index_redirect.py
- appengine/main.py
- appengine/requirements.txt
- appengine/storage.py
Python is a non-issue.  But App Engine took the opportunity to change everything.
This merges to master (not develop) since we want to push master to appspot.
> ‘Upgrade’ from Python 2.7 to Python 3.7

- appengine/main.py
> Fix main.py redirect.

- core/block_svg.js
Blockly.navigation.keyboardAccessibilityMode -> this.workspace.keyboardAccessibilityMode
Because Blockly.navigation.keyboardAccessibilityMode is not a thing anymore.
Tested on:
> Update to use new variable

- blocks/procedures.js
- [] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guxide)
Closes #3711 
Makes checking for duplicate vars case-insensative.
Procedure args should not allow duplicate vars. Blockly does not allow vars that are only different based on case. Together this means, the check for duplicates should be case insensative.
Tested on:
N/A
N/A
> Fix procedure args handling case incorrectly

- core/workspace_svg.js
Removes redundant math and updates comments. Removes call to `Blockly.hideChaff(...)` since it is also called in `Blockly.WorkspaceSvg.scroll(...)`.
Should not result in any change in behavior.
> Cleanup logic in centerOnBlock.

- core/block_svg.js
- core/renderers/common/constants.js
- core/renderers/common/debugger.js
- core/workspace_svg.js
- tests/playground.html
Flash a block red for 100ms when the debugger is included and enabled so we can tell when a block is re-rendered.
Help with render performance testing.
Help with testing.
Tested on:
> Flash on render

- core/workspace_svg.js
Change keyboardAccessibilityMode to true
We need this property in workspace search in blockly-samples. If we need it then stands to reason other people would need this to be public.
Tested on:
> Make keyboard accessibility public

- tests/workspace_svg/procedure_svg_test.js
> chore: fix typo

- core/components/component.js
- core/components/menu/menuitem.js
- core/components/tree/basenode.js
- core/components/tree/treecontrol.js
- core/components/tree/treenode.js
- core/toolbox.js
- tests/mocha/navigation_test.js
Begin to address https://github.com/google/blockly/issues/3056
Remove unnecessary public getters. Use protected instead of private.
Cleanup.
Tested on:
> Cleanup Blockly UI components.

- core/flyout_base.js
Follows on from #3742 
Fix annotation to be throw instead of return null.
Tested on:
> Fix flyout createBlock annotation

- gulpfile.js
- scripts/gulpfiles/build_tasks.js
Remove unused requires in gulpfile.js
Don't add the closure library for blocks.
Cleanup
Tested on:
> Cleanup build

- gulpfile.js
- package.json
- scripts/gulpfiles/git_tasks.js
Add task to easily update github pages from develop
Tested on:
> Update gh pages task

- package-lock.json
- package.json
Resolve npm security vulnerabilities
Resolves most security vulnerabilities, and upgrades dependencies to the latest minor version.
Tested on:
> Npm update and audit fix

- demos/keyboard_nav/index.html
Fixes #3779
1. Add explanation of the line cursor
2. Update explanation of the basic cursor
3. Update link for documentation info.
Tested on:
> Update the keyboard navigation demo

- tests/mocha/.eslintrc.json
- tests/mocha/field_angle_test.js
- tests/mocha/field_checkbox_test.js
- tests/mocha/field_colour_test.js
- tests/mocha/field_dropdown_test.js
- tests/mocha/field_image_test.js
- tests/mocha/field_label_serializable_test.js
- tests/mocha/field_label_test.js
- tests/mocha/field_number_test.js
- tests/mocha/field_textinput_test.js
- tests/mocha/test_helpers.js
To catch the likes of bugs like https://github.com/google/blockly/issues/3794
Tested on:
> Add field set source block tests

- core/theme.js
Fixing jsdoc typing in theme.js.
> Fix jsdoc typing in theme.

- tests/scripts/selenium-config.js
Update chrome version in selenium config.
Fixes issue with running tests on newer versions of chrome.
> Updating chrome version in selenium config.

- blocks/procedures.js
https://github.com/google/blockly-samples/pull/172#issuecomment-612534049
Use getters
Getters are betters than errors.
Not a behavioral change.
> Fix procedure callers accessing private vars

- core/gesture.js
- core/keyboard_nav/ast_node.js
- core/keyboard_nav/navigation.js
- core/renderers/common/marker_svg.js
- core/renderers/zelos/marker_svg.js
- tests/mocha/astnode_test.js
While writing keyboard navigation documentation I found some parts of AST Node and Marker_Svg that I wanted to change.
1. Blockly.navigation.getTopNode -> Blockly.ASTNode.createTopNode(block)
-- We already have a bunch of create methods in Blockly.ASTNode so seems like this is a better fit
2. Changed methods in marker_svg to be showWithBlock_, showWithPrevious, showWithOutput_ so that they are easier to override. They were previously all one function, which was an... interesting decision by past me.
3. Passed the curNode to applyColour_. Seems like it would be nice to have the option to change the colour of the cursor depending on the type of curNode. 
4. Random cleanup: Made sure everything was less than 80 characters, changed some wording in comments.
Added tests for createTopNode. …
> Update ast node

- core/utils/useragent.js
Add user agent types so they appear in typings dts.
Tested on:
> Add user agent types so they appear in dts

- core/options.js
- typings/templates/blockly-interfaces.template
Update the options object to reflect its properties.
Update public option interface to include keymap and other little things.
Tested on:
> Update options types

- demos/storage/index.html
- [ X] I branched from develop
- [ X] My pull request is against develop
- [ X] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)
Update the message displayed when the storage demo 'Save Button' is clicked.
Data retention mapping needed within the org.
Tested on:
Laptop Mac Chrome Yes
> Update the alert for demo storage.

- tests/jsunit/workspace_test.js
- tests/mocha/index.html
- tests/mocha/workspace_test.js
Part of #2870
Converts some of the jsunit tests in workspace_test.js to mocha.
Explained in linked issue.
Ran mocha and jsunit tests.
Filed bugs #3836 and #3837 for test skipped.
Additional PR to follow with remaining test conversion.
> Partial conversion of workspace tests to mocha.

- core/variables.js
Fixes #3815
Make nameUsedWithAnyType public.
Tested on:
> Make variable method public

- tests/mocha/toolbox_test.js
I broke toolbox tests before even getting them merged.
Not break things.
.blocks -> .contents
Tested on:
> Fix toolbox tests

- tests/mocha/index.html
Enable workspace comment tests.
Previously tests were only running on compressed and enabling workspace comments was complicated because it is not included in compressed. Currently, tests run on uncompressed so there are no issues with running the tests.
> Enabling workspace comment test

- core/variables.js
Related to #3877 
Changes the JSdoc of the renameVariable function to be more descriptive.
It was kind of out of date before, and not very helpful.
No testing needed :D
This is docs silly!
N/A
> Improve renameVariable jsdoc

- tests/mocha/astnode_test.js
- tests/mocha/block_test.js
- tests/mocha/navigation_test.js
Cleans up block definitions in test teardown
Reduces warnings thrown by tests
> Add missing cleanup for block types.

- tests/playground.html
Remove populateTestThemes();
Tested on:
> Remove populateTheme

- core/components/component.js
- core/components/tree/basenode.js
- core/components/tree/treecontrol.js
- core/components/tree/treenode.js
- core/menu.js
- core/menuitem.js
Clean up types under components/ and menu / menuitem.js
Tested on:
> Cleanup types under components/

- core/field.js
- core/flyout_base.js
- core/interfaces/i_deletearea.js
- core/interfaces/i_registrable.js
- core/interfaces/i_toolbox.js
- core/keyboard_nav/navigation.js
- core/renderers/common/renderer.js
- core/toolbox.js
- core/trashcan.js
- core/workspace_svg.js
- tests/mocha/toolbox_test.js
I left the toolbox interface in mainly one piece other than the items that were optional for the toolbox (delete are & accessibility). 
Planning on separating out other interface pieces from the toolbox in separate PR
1. Adds a toolbox interface
2. Adds a delete area interface
3. Adds a registrable interface (For objects that can be registered)
Working on making a toolbox that can be used instead of this toolbox.
Tested on:
> Toolbox interface

- gulpfile.js
- package.json
- scripts/gulpfiles/build_tasks.js
- scripts/gulpfiles/git_tasks.js
Will bump the version number in package.json and blockly_compressed.js whenever we build core.
For releasing: 
1. npm run recompile 
2. Merge created PR into develop
3. npm run release
4. Merge created PR into master
1. Remove the part that creates a pull request that bumps the version since we are rolling this into the rebuild process.
2. Added the bump whenever we build core
3. Renamed prerelease -> recompile
Tested on:
> Update build scripts

- core/options.js
- core/registry.js
- core/toolbox.js
- core/workspace_svg.js
- tests/mocha/registry_test.js
Add a way to override the toolbox in options. 
** I left out any extra validation for the toolbox. I still think it would be nice to have some kind of check that will warn people if their toolbox doesn't have the required methods, but don't have a great way to do this yet. 
Tested on:
> Add plugin options

- scripts/gulpfiles/git_tasks.js
Adds step for rebuilding before pushing to github pages.
Remove automatically pushing to github pages after a release. 
I am concerned if there is a merge conflict in the update github pages step it will be confusing what part of the script has failed if I put it with the release step. So I would rather keep the tasks separate.
Tested on:
> Update gh pages script

- core/flyout_base.js
- core/options.js
- core/utils/toolbox.js
1. Remove call to  Blockly.utils.xml.domToText. I was converting to Text in `convertToolboxXml` and then having to convert back from textToDom later on. 
2. Removed the two branches because I read that helps performance. Testing it, it seems to improve a it by ~6ms on average.
Tested on:
> Fix performance

- core/block_dragger.js
- core/bubble_dragger.js
- core/interfaces/i_styleable.js
- core/interfaces/i_toolbox.js
- core/toolbox.js
- core/workspace_svg.js
Makes it so that a user does not need addStyle and removeStyle on their toolbox, and changes updateColourFromTheme -> applyTheme
Tested on:
> Update Toolbox Interface

- tests/playground.html
- tests/playgrounds/advanced_playground.html
Update the advanced playground to use the newly published Blockly playground in `@blockly/dev-tools`.
Tested on:
> @blockly/dev-tools playground

- core/gesture.js
Fixes #3947
Add an event that is emitted when someone clicks on the workspace.
Tested on:
> Emit workspace click event

- core/gesture.js
- core/workspace_svg.js
Fixes #3957
Removes an extra workspace fire I previously left in
Move deleting the theme manager after all the blocks are disposed of. 
Tested on:
> Fix disposing of a workspace

- core/connection.js
Fixes #3218
Just remove @package to make canConnectWithReason public.
Tested on:
> Remove @package

- core/block.js
- core/input.js
Fixes #3967 and #3966
Add opt_quiet to removeField. Similar to how we have opt_quiet for removeInput.
Tested on:
> Add opt quiet to remove field

- core/utils/toolbox.js
We were seeing this console log when someone opened a mutator or a flyout.
Added a check if the definition is a toolbox category. It wont' cover a simple toolbox, but it was cleaner than adding a check in the mutator, workspace and options. 
Tested on:
> Update Console Logs for Toolbox

- core/components/tree/basenode.js
- core/keyboard_nav/ast_node.js
- core/registry.js
Fixes JSDoc errors detected by running internal documentation generating script.
Fixes syntax errors.
Errors not good.
> Fixing JSDoc syntax errors.

- tests/playgrounds/test_blocks_toolbox.js
Fixes all the spaces that I accidentally deleted in test blocks.
Tested on:
> Fix spaces

- core/theme.js
- core/theme/dark.js
#3987
propertyValue -> style
This allows users to use a value in the components in multiple places in their component. I added an example in dark.js in order to test it easier. I think we didn't realize it because it is a smaller feature that a lot of people might not use. Might be fine for this release since it is so small.
Tested on:
> Fix theme and add example

- .gitignore
- gulpfile.js
- package.json
- scripts/gulpfiles/build_tasks.js
Add a new gulp task to build in advanced compilation mode.
Benefits for this: 
- Standardized tooling
- source maps in advanced compilation test page to help with debugging
Tested in advanced compilation test page.
Tested on:
> Advanced compilation gulp script to replace the shell script.

- build.py
Add deprecation message to build.py and deprecate it.
Add comment at the top of the file as well.
Tested on:
> Add deprecation message to build.py

- tests/scripts/check_metadata.sh
Fixes https://github.com/google/blockly/issues/4011
Tested on:
> Add blockly size metadata snapshot of previous releases

- tests/compile/compile.sh
Deprecated advanced compilation script and add deprecation warning
Tested on:
> Deprecated advanced compilation shell script

- core/gesture.js
Updates doWorkspaceClick_ jsdoc.
Tested on:
> Fix jsdoc for workspace click

- tests/mocha/input_test.js
- tests/mocha/toolbox_test.js
Removes debug logs from mocha tests.
Cleans up console when running mocha tests in browser.
Ran tests.
> Remove debug logs from mocha tests

- blockly_uncompressed.js
- core/flyout_base.js
- core/flyout_dragger.js
- core/flyout_horizontal.js
- core/flyout_vertical.js
- core/gesture.js
- core/inject.js
- core/interfaces/i_flyout.js
- core/interfaces/i_toolbox.js
- core/registry.js
- core/toolbox.js
- core/trashcan.js
- core/workspace_svg.js
This adds an interface for a flyout and the ability to add a toolbox flyout. 
The registry doesn't really support nesting the name of the plugin. 
I don't love the way I implemented this, but was having issues coming up with better ways to do this.
Tested on:
> Add Flyout as a Plugin

- tests/playgrounds/advanced_playground.html
Similar to https://github.com/google/blockly/pull/4075 but for develop. Snapping to latest 1.1.1
Tested on:
> Snap dev tools to 1.1.1

- core/toolbox/toolbox.js
- [] I branched from develop
This PR mainly adds back in methods from the old toolbox that are necessary.
The exceptions to this are: 
getToolboxItemById
getSelectedItem
Tested on:
> Adds methods migrated from old toolbox

- core/toolbox/category.js
- core/utils/toolbox.js
Adds the constructor and methods needed in the constructor for a toolbox category. Just a reminder that this is not the complete category class. 
Tested on:
> Init category

- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
Adds three classes that have to do with items that can be added to the toolbox. 
Toolbox Item --> This is the base class. Used for purely visual items. (eg a separator)
Selectable Item --> An item that can be selectable. (eg a button)
Collapsable Item --> An item that can be collapsed. (eg a category)
Tested on:
> Adds a toolbox item

- core/toolbox/category.js
Adds methods needed for expanded and selecting a category. Also adds in all getters and setters for the category.
Tested on:
> Category select methods

- core/flyout_base.js
- core/keyboard_nav/navigation.js
- core/options.js
- core/toolbox/category.js
- core/utils/toolbox.js
1. Updates to some toolbox types
2. Rename classConfig_ to cssConfig_ to match separator.js
Tested on:
> Update toolbox types

- core/bubble.js
- core/bubble_dragger.js
- core/gesture.js
- core/interfaces/i_bubble.js
- core/interfaces/i_contextmenu.js
- core/workspace_comment_svg.js
Add an IBubble interface
Add an interface for describing bubbles for use in WorkspaceComments
Code documentation and plugin use of interfaces.
Ignore formatting changes.
Tested on:
> Add IBubble interface

- core/comment.js
- core/field.js
- core/rendered_connection.js
Part of #4049
Uses a util function and adds explicit deletion dates for more deprecated functions.
Make it easier to delete these down the line.
No functional changes
> Deprecation warnings

- tests/playgrounds/advanced_playground.html
> Apply dependabot change to develop

- blockly_uncompressed.js
- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/utils/toolbox.js
- tests/playground.html
Fix problems from merge.
Tested on:
> Small fixes

- core/toolbox/category.js
- core/toolbox/toolbox.js
- core/utils/dom.js
1. Support localization for category names
2. Dispose of toolbox items before rendering new toolbox items
3. Support multiple class names in the cssConfig. For example, this.cssConfig['iconopen'] = 'classOne classTwo'
Tested on:
> Small features

- tests/mocha/field_number_test.js
Adds test for bug #4105.
Adds test to catch bug.
To easier test fix and prevent breaking in future.
Tested on:
> Add high precision constraint test case for FieldNumber

- core/toolbox/category.js
1. Rename iconSpan_ -> iconDom (since when someone overrides they could be returning a div)
2. Rename labelSpan -> labelDom (since when someone overrides they could be returning a div)
3. Rename createSubCategories -> createSubCategoriesDom (More descriptive)
4. Rename addColour_ -> addColourBorder
Tested on:
> Updates category method names

- .github/dependabot.yml
Creating it on develop doesn't do anything.
> Create dependabot.yml on master

- tests/mocha/run_mocha_tests_in_browser.js
Increase mocha timeout
Timouts are blocking most of our PRs right now.
> Increase mocha timeout to 5m30s

- tests/mocha/xml_test.js
Part of #4070
Part of #4064
Part of #4080
- Adds call to shared setup and teardown and updates test logic for testing event firing.
- Modifies some tests to use the clock defined in shared setup.
- Adding missing workspace cleanup.
- Cleans up async calls after tests.
Tested on:
Before adding missing workspace cleanup, `sharedTestTeardown` for a different test logged an error (an error about `null` object), showing some usefulness in the console error log because it helped detect there was missing cleanup.
> Xml test cleanup

- core/toolbox/category.js
- core/toolbox/toolbox.js
Adds ability to hide and disable a category. 
Add isHidden_ and isDisabled properties.
Tested on:
If isHidden is set to true on the currently selected item, this relies on the developer to call toolbox.clearSelection() to close the flyout.
> Hide category

- tests/mocha/test_helpers.js
Clean up as part of #4070
- Update Events fire stub to call original wrapped method rather than custom logic.
- Now that async cleanup was added for all tests with #4070, calling wrapped method is feasible and better tests the `Event.fire` logic since its called directly and is less fragile changes to `Events.fire`
Tested on:
> Update events fire stub.

- core/toolbox/category.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
1. Add a disabled attribute to the category div when an item is disabled. Allows a user to easily add css to deal with this. 
2. Adds a method to update the contents of the category.
3. Adds a method to get all contents of a toolbox.
Tested on:
> Toolbox api updates

- tests/mocha/trashcan_test.js
Part of #4065
- Used event dispatching to test click behavior in trashcan
- Added additional test cases for trashcan clicks
- More tests
Tested on:
> Trashcan test click

- tests/mocha/field_image_test.js
- tests/mocha/insertion_marker_test.js
n/a
Removes unnecessary `delete` calls
The `delete` calls aren't necessary because context is not shared between tests
Tested on:
> Remove unecessary delete calls in test cleanup.

- core/toolbox/category.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- tests/playground.html
1. Adds a previouslySelectedItem 
2. Adds shouldDeselectItem_ and shouldSelectItem_ methods
3. Separates out the childToolboxItems and contents. I like this for a few reasons: 
- It makes the code a bit easier to reason about and seems more clear to me. 
- It makes having a category with both toolbox items and flyout items easier. (This is not the full way there, since there are a few changes that would need to be made in category.onClick and shouldDeselect, and updateFlyout)
- It clears up some weirdness around types
Things I don't like: 
- It's a bit weird that one of them will always be empty.
Updates to the toolbox and category in order to make having a category with both toolbox items and flyout items easier.
Tested on:
> Sub categories and block

- scripts/gulpfiles/build_tasks.js
- tests/compile/compile.sh
- tests/compile/main.js
Part of https://github.com/google/blockly-samples/issues/210
Removes references to `test_blocks.js`
`test_blocks.js` was moved out of core
Ran `npm run test:compile:advanced' as well as `run_all_tests.js` after commenting out advanced compile test script.
Tested on:
> Remove references to removed test_blocks.js

- core/flyout_base.js
- core/flyout_button.js
- core/interfaces/i_flyout.js
- core/interfaces/i_toolbox.js
- core/options.js
- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- core/utils/toolbox.js
- core/workspace_svg.js
- tests/mocha/toolbox_test.js
1. Updates JSON toolbox definitions to be {'contents': []} instead of just an array. This is for both simple and normal toolboxes. 
2. Removes NodeList as a possible way to define the toolbox. I think this is something that I added last quarter, and it adds extra unnecessary complexity. 
3. Updates types names
Tested on:
> Update toolbox def

- tests/mocha/field_checkbox_test.js
Part of #4194 
Adds missing constants to mock of rendering constants.
Fixes console errors relating to setting rect attributes to NaN.
Tested on:
> Add missing constants to field_checkbox_test

- tests/mocha/connection_db_test.js
- tests/mocha/event_test.js
- tests/mocha/navigation_test.js
n/a
- Fixes order of actual/expected arguments in assert call
- Replaces usages of `callsFake` with `returns` where approriate
- More accurate assert message
- Simplifies
Tested on:
> Minor stub and assert cleanup

- tests/mocha/registry_test.js
Part of #4194 
Captures expected warning in registry test.
Cleans up console logs.
Tested on:
> Capture expected warning in registry test.

- core/toolbox/toolbox.js
1. Updates toolbox event TODO with a comment
2. Small improvement for toolbox performance
Tested on:
> Adds small updates to toolbox

- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/utils/toolbox.js
- tests/mocha/toolbox_helper.js
- tests/mocha/toolbox_test.js
1. Allows uppercase and lowercase versions of cssConfig and categoryStyle
2. Fixes hovering for categories.
Change the div that handles a click to be the blocklyTreeRow div instead of blocklyToolboxCategory div. The blocklyToolboxCategory div held all of its children, so when there was a nested category and we hovered over the parent category all the children would appear hovered.
Tested on:
> Bug Fixes for Toolbox

- core/interfaces/i_toolbox.js
- core/toolbox/category.js
- core/toolbox/toolbox.js
Adds #4139 into new toolbox file.
Tested on:
> Handles toolbox item resizing

- tests/scripts/selenium-config.js
Update chrome version
Tested on:
> Update chrome driver version

- core/flyout_base.js
- core/interfaces/i_flyout.js
- core/mutator.js
- core/options.js
- core/toolbox/category.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- core/utils/toolbox.js
- core/workspace_svg.js
- tests/mocha/toolbox_helper.js
- tests/mocha/toolbox_test.js
- tests/mocha/workspace_svg_test.js
- tests/playgrounds/category_test.js
Toolbox parsing was messy. 
Breaks it into two methods: 
1. For parsing the flyout def which can be: NodeList, Array<Node>, Array<json>, string(name of custom category). This returns a list of json for the flyout.
2. For parsing the toolbox def which can be: Node, string(of xml), Json. This returns toolbox json.
Tested on:
> Toolbox parse

- core/flyout_base.js
- core/toolbox/category.js
- core/toolbox/toolbox.js
- core/utils/toolbox.js
1. Adds a DynamicCategoryJson type
2. Fixes bug with horizontal toolbox at the bottom
3. Fixes bug with custom categories by checking for categoryDef['contents'] instead of assuming it is there
4. Removes parsedToolboxDef.slice() since it is no longer needed.
5. Store the blockxml when someone creates a block from a type
Tested on:
> Toolbox cleanup

- core/flyout_base.js
- core/interfaces/i_flyout.js
- core/interfaces/i_toolbox.js
- core/mutator.js
- core/registry.js
- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
1. Fixes requires
2. Fixes Blockly.Flyout -> Blockly.IFlyout
3. Misc category comments
4. Updates registry to have an opt_quiet flag
Tested on:
> Fix requires

- core/toolbox/category.js
- core/toolbox/toolbox.js
- tests/mocha/toolbox_test.js
- [ x] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guidex)
Fixes PR comments pertaining to category.js and toolbox.js.
Tested on:
> Address pr comments

- core/toolbox/category.js
- core/toolbox/toolbox.js
1. Separators were always being added to the toolbox and not to the flyout because I added items to the flyout based on if they did not exist in the registry.
2. Going from a custom category to a category that has contents using updateFlyoutItems was not working. 
3. Refresh selection on a category that has both categories and blocks was not working.
4. There was extra padding on nested categories. 
1. From our old implementation the position of the separator (either in the flyout or in the toolbox) depends on the item directly before the separator. In the case that the separator is the first item in the list it is considered to be in the flyout.
2. Delete the old customs field on the toolboxItemDef and clear out the flyoutItems list.
3. Remove check for isCollapsible and instead look at …
> Toolbox bugs

- core/flyout_base.js
- core/flyout_button.js
- core/interfaces/i_toolbox.js
- core/options.js
- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- core/utils/toolbox.js
Rename types from Json --> Info
Tested on:
> Type renaming

- core/flyout_base.js
- core/interfaces/i_toolbox.js
- core/registry.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- core/utils/toolbox.js
- typings/blockly.d.ts
Addresses pr comments
Tested on:
> Another round of pr comments

- blockly_uncompressed.js
- core/interfaces/i_toolbox.js
- core/interfaces/i_toolbox_item.js
- core/toolbox/category.js
- core/toolbox/collapsible_category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/toolbox/toolbox_item.js
- core/utils/toolbox.js
- tests/mocha/toolbox_test.js
1. Creates interfaces for a toolbox item, a selectable toolbox item and a collapsible toolbox item. 
2. Removes the Collapsible and Selectable toolbox item abstract classes
3. Splits the category into a `CollapsibleToolboxCategory` and a `ToolboxCategory`
4. Adds init methods to separate out creating the dom and updating the dom (expanding/hiding categories) Was also needed to fix a bug for hiding a nested category.
5. Moved getParent and getLevel into the ToolboxItem class. Since any toolbox item can technically be nested this needed to be on the toolbox item class. This also means that if someone extends the toolbox item class they don't have to deal with any of these methods.
Tested on:
The refactor for the types is in the first commit. If you would like to split up when reviewing.
> Category split

- core/block.js
- core/workspace.js
- core/workspace_svg.js
N/A
Just updates some docs, no functional changes.
Noticed that the docs for setFieldValue were weird over the weekend, and I figured I would fix them up.
> Update some inline docs in block.js

- tests/mocha/navigation_modify_test.js
Could not repro #4113 so uncommenting the tests.
Tested on:
> Uncomment skipped tests

- core/utils.js
#4157
Allows developers to add `data-is-text-input` to their custom elements to signal that it is a text input.
There is not currently a way to tell if custom components are a text input or not. 
Tested on:
Some alternatives: 
1. Could add a different attribute such as kind. But we would have to make sure it does not interfere with attributes that are already used such as type.
> Add check for custom components

- tests/playgrounds/advanced_playground.html
Advanced playground was not loading due to `ReferenceError: testBlocksToolbox`
Update testBlocksToolbox to toolboxTestBlocks. `toolboxTestBlocks` is the name of the test blocks in dev tools.
Tested on:
> Fix advanced playground

- tests/playgrounds/advanced_playground.html
Updates dev tools version from 1.1.1 --> 2.0.0 in order to use the new toolbox json definition.
Tested on:
> Updates dev tools script to new version

- core/field_registry.js
- core/icon.js
- core/interfaces/i_registrable.js
- core/interfaces/i_registrable_field.js
- core/options.js
- typings/templates/blockly-interfaces.template
Fixes for https://github.com/google/blockly/issues/2937
Typings fixes for field registry and some misc typings.
Typescript typings.
Tested by running closure build and `npm run typings`.
Tested on:
> Fix field registry typings

- core/trashcan.js
Fixes #4303
Revert part of #4024. 
Re opens: #3975
Tested on:
> Fix bug in trashcan

- demos/blockfactory/app_controller.js
n/a
Fixes escape for `'` in string
Was causing syntax error.
Loaded block factory locally.
> Fix error in escape in string

- core/contextmenu_registry.js
- core/options.js
- core/toolbox/category.js
- core/toolbox/collapsible_category.js
- core/toolbox/separator.js
- core/utils/svg.js
FIxes jsdoc errors and warnings. 
Jsdoc throws an error when there is a trailing comma after in a typdef.
Jsdoc throws a warning if you put @package on the same line as a @type
Tested on:
> Fix jsdoc errors and warnings

- tests/scripts/check_metadata.sh
Updated metadata sizes for new release.
> Update Blockly size metadata for the 3.20200924.0 release 

- core/events.js
- tests/mocha/event_test.js
Resolves #4261 
In Blockly.Events.disableOrphans, when blocks are disabled/enabled, they should not be undoable.
Users should not have to undo twice to undo moving a block when disabledOrphans is used.
Added tests for disableOprhans in general, including a test case to make sure undoStack does not contain the disable event.
> Don't undo the change events from disableOrphans

- tests/mocha/field_checkbox_test.js
- tests/mocha/field_colour_test.js
Part of #4260
- Updates `FieldCheckbox` `setValue` tests to use dev-tools helpers
- Updates `FieldColour` `setValue` tests to use dev-tools helpers
Covers more test cases and makes tests more readable.
Tested on:
> Update FieldCheckbox and FieldColour setValue tests

- core/toolbox/category.js
- core/toolbox/collapsible_category.js
Fixes #4335
Make all css class names lowercase since xml does not support camel case attributes.
Tested on:
> Fix adding an icon in xml definition

- generators/javascript/text.js
- generators/php/text.js
n/a
- Removed extra set of text in `Blockly.JavaScript['text_getSubstring']`
- Minor refactor of set of text in `Blockly.PHP['text_getSubstring']`
Cleans up code.
Ran tests.
Follow up after #4329. Noticed that some logic that should have been deleted wasn't. Should have no effect on code generation.
> Clean up some text generator logic

- tests/mocha/field_dropdown_test.js
Part of #4260 
Refactors FieldDropdown tests to use dev-tools helpers.
Improves readability.
Tested by setting temporary link to local built files of dev-tools (with necessary changes) and running mocha tests.
Tested on:
Depends on PR in Blockly-Samples https://github.com/google/blockly-samples/pull/381, now published so changes can be used.
> Update FieldDropdown to use dev-tools helpers

- tests/mocha/field_image_test.js
Part of #4260 
Refactors FieldImage tests to use dev-tools helpers.
Improves readability and coverage.
Tested by setting temporary link to local built files of dev-tools (with necessary changes) and running mocha tests.
Tested on:
Depends on PR in Blockly-Samples https://github.com/google/blockly-samples/pull/381, now published so changes can be used.
> Refactor FieldImage tests to use dev-tools helpers

- core/toolbox/category.js
- core/toolbox/separator.js
- core/toolbox/toolbox.js
- core/utils/toolbox.js
> Fix toolbox types

- demos/blockfactory/standard_categories.js
- demos/blockfactory/workspacefactory/wfactory_controller.js
https://github.com/google/blockly/issues/2408
I have added a new standard category called "TypedVariables" with custom = 'VARIABLE_DYNAMIC' and hue = 290
I have chosen these according to the issue description except for hue. I did not understand what is meant by "style="variable_category". That needs clarification on my end. 
To resolve the issue
I ran the mocha tests
Tested on:
Desktop Chrome
> add new typed variable

- core/field_textinput.js
https://github.com/google/blockly/issues/4049
Using the deprecation utils to add warning for numberValidator method
To use deprecation warning utils instead of console logging
Not applicable in this case I think.
Tested on:
> add deprecation warning

- core/registry.js
Updating `opt_quiet` flag in registry to make the name more descriptive.
Tested on:
Discussion [here](https://github.com/google/blockly-samples/pull/395#discussion_r502714279)
> Changes flag name in registry to be more descriptive

- tests/mocha/.eslintrc.json
- tests/mocha/index.html
- tests/mocha/keydown_test.js
- tests/mocha/test_helpers.js
Add tests for Blockly.onKeyDown.
So I can refactor things without breaking everything.
Tested on:
> Test Blockly.onKeyDown method

- core/interfaces/i_toolbox_item.js
- core/keyboard_nav/navigation.js
- core/toolbox/category.js
- core/toolbox/collapsible_category.js
- core/toolbox/toolbox.js
- core/utils/toolbox.js
1. Adds this.labelDom_
2. Navigation searches for a selectable toolbox item when it focuses on the toolbox
3. Add a `onKeyDown` method.
4. Add a `getClickTarget` method so that users don't have to add toolboxItem.setAttribute('id', this.id). 
5. Check the childNodes instead of the tagName when deciding to add 'contents' to the toolbox item definition.
1. When I was creating a codelab I realized that even though I don't need the labelDom in the category class it is helpful to have when I extend a category.
2. Navigation will not work if the first item is not selectable.
3.  The keyDown listener is on the parent toolbox element. Passing the event through to the toolbox items allows them to handle keydown events.
4. In order for a toolbox item to be clickable a user would have to add …
> Small fixes to the toolbox

- core/events.js
- tests/mocha/event_test.js
Part of #4203
- Adjust logic in event filtering for UI events.
Fixing behavior that worked before UI event refactoring
Tested by logging events on playground and observing that expected events were logged and running mocha tests.
Tested on:
> Fix event filtering for ui events

- core/events/block_events.js
- core/events/events_click.js
- core/events/events_drag.js
- core/events/events_marker_move.js
- tests/mocha/event_test.js
Part of #4203
- Adds serialization tests for events.
- Adds missing fromJson implementation for `Blockly.Events.Click`.
- Updates some serialization logic in other events
Fixes to serialization for events and expanded test coverage.
Tested on:
Tests added:
> Add missing fromJson implementation for click event

- core/flyout_horizontal.js
- core/flyout_vertical.js
Fixes #4414 
Use the main workspaces scrollX and scrollY when translating the flyout.
Tested on:
> Uses the ws scroll value when updating flyout

- core/field_multilineinput.js
Fixes #4367
Link to newly added multiline text field documentation in JSDoc.
Multiline text field documentation was added.
CL with documentation addition for multiline text field currently under review.
> Link to multiline text field documentation in JSDoc

- tests/mocha/logic_ternary_test.js
n/a
Adds tests to `logic_ternary` block tests using dev-tools helpers.
Specifically adds new serialization tests and does minor refactor of other tests.
Expanding test coverage. 
> Add tests to logic ternary block

- core/shortcut_registry.js
- tests/mocha/shortcut_registry_test.js
Updates getKeyCodeByShortcutName --> getKeyCode**s**ByShortcutName, since it was updated to return a list of keycodes that map to a shortcut name instead of a single keycode. 
Tested on:
> Update shortcut registry method name

- tests/mocha/event_test.js
Removes debug logs from console when running mocha tests.
Removes console log.
Console logs were making it console less useful for mocha tests. Logs were unecessary.
Tested on:
> Remove debugging console log from test

- core/renderers/geras/constants.js
- core/renderers/measurables/rows.js
> Fix rendering bug

- core/comment.js
fix #3596  
Expected comments to have scrollbars
Using `text-overflow` instead of `overflow` for CSS block comment. `text-overflow` can be used to determine what the browser should do when the amount of text exceeds the available space in a container
screenshots
Tested on:
Desktop
Chrome: Version 86.0.4240.193 (64-bit)
Firefox: 81.0.2 (64-bit)
Microsoft Edge: Version 86.0.622.63 (64-bit)
> fix #3596:Textarea of comment missing scrollbars

- scripts/gulpfiles/git_tasks.js
Fixes #4322
Override any local changes on gh-pages with the changes from develop. 
Build.
Commit.
Force push to upstream gh-pages
Tested on:
> Fix update gh pages

- core/generator.js
Updating JSDoc in response to comment https://github.com/google/blockly/pull/4490#issuecomment-737545626
> Updating JsDoc in response to comment

- core/comment.js
Fixes #4481
Remove deprecated functions in comment.
Tested on:
> Remove deprecated functions in comment.js

- core/procedures.js
- demos/blockfactory/workspacefactory/wfactory_init.js
Fixes #4499
Part of #4203
Fixes ui event checks.
Checks were incorrectly updated before (when ui events refactor was merged).
Tested in playground. Confirmed that procedure input names updated such that there would be no duplicate variable names.
Tested on:
> Fix ui event checks

- core/events/events.js
Fixes: #4445
From what I can tell the filter function is not working properly when you have the following event: 
[Move1, Move2, Change, Move3, Move4, Move5, Move6]
I *think* the expected result after the merge would be: [Move, Change, Move] (If debugging this, you will notice one of the Move events is removed because it is null)
The actual result is: [Change, Move, Move, Move, Move, Move]
When we get to the Move3 event the last move event before Move3 has an index of 1. 
At this point i=3 so the check if (...lastEntry.index == i -1) will fail and we will find ourself on line 299.
If we set this to 1 then all subsequent (lastEntry.index==i-1) checks will fail. By setting it to the actual index then the other move events will merge together.
Tested on:
> Fix undo for if blocks

- core/block.js
n/a
Makes `isInsertionMarker` public.
Fixes advance compilation tests.
> Make isInsertionMarker public

- package.json
Snap jsdom to version 15.2.1.
Tested on:
> Snap version number of jsdom

- demos/keyboard_nav/index.html
Removes redirect and instead adds a link to the samples page, which is where the keyboard navigation demo will be once navigation is moved out of core.
Tested on:
> Update keyboard demo text

- core/flyout_base.js
- scripts/gulpfiles/typings.js
- typings/blockly.d.ts
- typings/msg/zgh.d.ts
- typings/templates/blockly-interfaces.template
Similar to https://github.com/google/blockly/pull/4541
Adds toolbox and events directories to the typings script, removing deprecated components directory.
Fix two typing issues in Flyout and Blockly Options.
Fix typings.
Generated typings. 
Ran tsc on typings/
Tested on:
> Update typings script and fix two typing issues:

- tests/scripts/check_metadata.sh
Update metadata of Blockly compressed and gzip'd sizes after the 4.20201217.0 release.
Tested on:
> Update Blockly size metdata for the 4.20201217.0 release

- gulpfile.js
- package.json
- scripts/gulpfiles/appengine_tasks.js
n/a
Adds script for deploying to demos. Additionally, adds logic for including patch number in version, for the instance where we want to update demos with Blockly patch version.
Automates process for deploying demos 
Used script to deploy demos and tested that directory is cleaned up even if deploy to gcloud is canceled.
> Add script for deploying demos

- core/block_svg.js
- tests/mocha/block_test.js
#4536
When we expand a block update the disabled value of the block and all the children. 
#4536
Added tests for: 
- The use case mentioned in the bug.
- That updateDisabled does not get called for every child block when the parent is collapsed. (Makes sure I don't undo #4302, which was put in place for performance reasons)
- That a child block that was already disabled does not get set to enabled when the parent is enabled.
Tested on:
> Fix collapsing bug and add tests

- core/xml.js
- package.json
Part of #2135
- Processes xml tags in an explicit order.
- Adds npm script `npm run test:generators` to allow for running only generator tests (which were used heavily in testing this change)
- This change allows for us to guarantee that tags are processed in a specific order and ensures that a difference in order of xml tags does not affect the loaded block.
- After this change, we have the ability to add logic between processing specific tags.
Ran tests.
Tested on:
> Process xml tags in an explicit order in domToBlockHeadless_

- core/bubble.js
- core/bubble_dragger.js
- core/comment.js
- core/connection.js
- core/connection_checker.js
- core/zoom_controls.js
Missing requires and requireTypes, as found by the closure compiler.
> More missing requires

- core/gesture.js
- core/keyboard_nav/basic_cursor.js
- core/keyboard_nav/cursor.js
- core/registry.js
- core/workspace_svg.js
Allows users to register cursors.
Adds cursors to the registry and runs clang formatter on the files. 
I separated the changes, so all the actual changes should be in the first commit and all the formatting should be in the second commit.
> Register cursors

- .github/workflows/build.yml
- tests/mocha/astnode_test.js
Updates github pages to trigger the build when there is a pull request instead of on push.
Tested on:
> Add pull request

- core/dropdowndiv.js
- core/input.js
- core/insertion_marker_manager.js
- core/widgetdiv.js
- core/workspace_svg.js
- core/xml.js
Fixes some missing calls to require and requireType.
Adds calls as identified by the `stricterMissingRequire` flag for the closure compiler.
Improved correctness-->tools become more effective.
> Fix some missing requires

- core/connection_checker.js
- core/connection_db.js
- core/contextmenu.js
- core/events/block_events.js
- core/events/events.js
- core/events/events_abstract.js
- core/events/events_block_drag.js
- core/events/events_bubble_open.js
- core/events/events_click.js
- core/events/events_marker_move.js
- core/events/ui_events.js
- core/events/variable_events.js
- core/events/workspace_events.js
- core/workspace_dragger.js
Missing calls to `goog.requireType`.
> Update more missing requireTypes

- scripts/gulpfiles/release_tasks.js
Prints out the latest beta version, so it is easier to decide what beta version to update to.
Tested on:
> Update beta release script

- core/field_colour.js
- package-lock.json
- package.json
Replaces #4622
- Upgrades closure compiler version 
- Adds missing typecasts to prevent compile errors
Version upgrades, prompted by dependabot.
> Upgrade closure compiler

- core/flyout_vertical.js
Fixes #4655
Adds padding to top of scrollbar in flyout metrics.
Flyout was missing padding at top of the flyout.
Flyout now has padding
Flyout should have padding.
Manually testing in playground.
> Add missing padding to flyout

- core/scrollbar.js
n/a
Adds `requiresResize` check in `resizeVertical_` and `resizeHorizontal_` to prevent unecessary calls to `resizeViewVertical` and `resizeViewHorizontal`
`resizeViewVertical` and `resizeViewHorizontal` is called every time the scrollbars resize. 
`resizeViewVertical` and `resizeViewHorizontal` is not called, only `resizeContentVertical` and`resizeContentHorizontal`,  if view metrics and absolute metrics didn't change on resize.
Prevents unecessary set attribute calls triggered by `resizeViewVertical` and `resizeViewHorizontal`.
Manual testing in playground.
Broken off from #4643
> Adding requiresResize check

- core/inject.js
- core/options.js
- core/workspace_svg.js
Part of #1292
Adds inject options to specify whether workspace should have single-directions scrollbars.
Single direction scrollbars can be enabled for main workspace by passing options `move: {hasVerticalScrollbars: true}` or `move: {hasHorizontalScrollbars: true}`.
If `hasHorizontalScrollbars` and `hasVerticalScrollbars` are not used in options, the behavior of parsing workspace options remains the same as before this PR.
Adding support for single-direction scroll.
Tested with playground.
Inject options on devsite should be updated to reflect this addition.
Depends on #4652
> Adding single-direction scroll options to inject options

- core/flyout_horizontal.js
- core/flyout_vertical.js
- core/workspace_svg.js
n/a
- Updates metrics computation for flyouts
- Updates logic in scroll to properly handle case where `scrollHeight`<`viewHeight` and `scrollWidth`<`viewWidth`
- Bug where scrolling up/left with trackpad in horizontal and vertical flyout would scroll back down/right
- Bug where flyout would unexpectedly scroll when dragged (scrolls horizontally in vertical-only scrolling flyout)
- Trackpad scrolling in horizontal and vertical flyout fixed
- Flyout no longer unexpectedly scrolls when dragged
Bugfix
Manual testing in playground and multi_playground.
For review, you can test changes here: https://moniika.github.io/blockly/tests/multi_playground.html
> Fix flyout metrics and workspace scroll

- core/interfaces/i_positionable.js
- core/trashcan.js
- core/zoom_controls.js
n/a
Cleans up comment wording.
cleanup
> Cleanup of positionables comments

- core/plugin_manager.js
- core/trashcan.js
- core/workspace_svg.js
- core/zoom_controls.js
n/a
- Fixes bugs in `getPlugins` logic where plugins are not returned in correct order.
- Updates some comments for clarity.
- Assigns different weights to zoom controls and trashcan
`getPlugins` did not order plugins by weight.
`getPlugins` now returns the plugins correctly ordered.
bugfix of new logic
Tested on playground by observing how changing weight of positionable affected how they were positioned.
> Positionables bugfix

- core/trashcan.js
> Use registry to instantiate flyout from trashcan

- tests/scripts/selenium-config.js
> Update chrome version

- demos/keyboard_nav/index.html
Fixes #4420
Keyboard navigation demo does not redirect.
Keyboard navigation demo redirects to a new test page.
> Update keyboard nav redirect link

- core/registry.js
Updates the registry to use IMetricsManager.
> Update to metrics interface

- core/shortcut_registry.js
Keyboard shortcuts were broken in advanced compilation. 
Make the keys to the modifier objects strings, so they are not renamed in advanced compilation.
Keyboard shortcuts was broken for blockly games.
> Fix keyboard shortcut for blockly games

- blocks/lists.js
- core/events/block_events.js
Reverts google/blockly#4758
(change should have been merged on develop, not master)
> Revert "Issue #4475 fix"

- blocks/lists.js
- core/events/block_events.js
> Cherrypick (#4758)

- typings/dart.d.ts
- typings/javascript.d.ts
- typings/lua.d.ts
- typings/php.d.ts
- typings/python.d.ts
`workspaceToCode` method  is not inferred automatic
`workspaceToCode` method  is inferred automatic
Fix wrong ts definition for exported generator.
> fix: Fix typing error of generators

- .github/dependabot.yml
We do not want to keep getting updates from dependabot about jsdom changes. 
Ignore jsdom until the next major version, or until we fix google/blockly-samples#665.
> Updates dependabot to ignore jsdom changes

- core/gesture.js
- Adds a getter for the current dragger that is in use on gesture.
> Adds a getter for the block dragger

- core/block.js
- core/block_svg.js
- core/connection_db.js
- core/field_number.js
- core/inject.js
- core/renderers/common/info.js
> Code simplifications

- core/block_drag_surface.js
- tests/scripts/selenium-config.js
- Returns a copy of the coordinate in block drag surface
- Runs clan format on the block drag surface.
> Fix drag surface

- tests/mocha/connection_test.js
Work on #4826 
Adds tests for connecting blocks.
So that I can fix #4826 without worrying about breaking things (or worrying less anyway).
Do you think this covers all relevant cases? Is there anything else I should test before jumping into #4826?
> Add tests for connecting blocks

- core/inject.js
Fixes optimization bug in bumpHandlers. Fixes part of #4871.
> Fixes a check in bump into bounds

- core/component_manager.js
n/a
- Adds api to ComponentManager add/remove capability of registered component
- Adds api to ComponentManager to check if a registered component has a capability
Makes it easier to add/remove capabilities when extending a class that has already handled adding to `ComponentManager`.
> ComponentManager API extension

- core/block_dragger.js
- core/bubble_dragger.js
n/a
- Prevents unnecessary calls to update cursor style if state hasn't changed.
> Prevent unecessary add/remove class calls on cursor during drag

- core/block_dragger.js
- core/bubble_dragger.js
n/a
Fixes logic on block and bubble dragger to set `this.wouldDelete` before calling method to update cursor style.
Delete style was applied to cursor with block after it left a delete area and removed after it entered.
Delete style is applied to cursor with block when it enters a delete area and removed when it leaves.
bugfix
Tested manually in playground.
Bug introduced in https://github.com/google/blockly/pull/4885
> Fix bug with updating cursor style in draggers

- core/block_dragger.js
Fixes a merge mistake in block dragger.
> Fixes block dragger after merge

- core/interfaces/i_drag_target.js
n/a
Updates the type and description of the `getClientRect` method on the `IDragTarget` interface to match that of the implementations.
Cleaning up jsdoc.
> Update JsDoc for IDragTarget

- core/toolbox/toolbox.js
Fixes #4678.
Call `handleToolboxItemResize` after the toolbox has been rendered. 
We call `handleToolboxItemResize` in `setExpanded`. The width of the toolbox was not accurate here, which was causing the workspace to resize thinking the toolbox width was 0. Adding a call after render updates the workspace with the correct size of toolbox. 
When you called updateToolbox with an expanded toolbox, any blocks on the workspace would move.
The blocks stay put. 
Fix bugs.
> Fixes workspace scroll bug

- core/block_drag_surface.js
- core/field_textinput.js
- core/toolbox/category.js
- core/utils/dom.js
- core/workspace_drag_surface_svg.js
Reverts google/blockly#4952
Too close to release.  Merge later.
> Revert "Group field edits together for undo/redo"

- .github/CODEOWNERS
Makes @google/blockly-eng owners of the repo in preparation for enabling branch protection and requiring/auto-assigning code reviews.
> Added @google/blockly-eng as the owner of the entire repo

- core/utils/toolbox.js
> fix doc typo

- core/block.js
- core/block_svg.js
Closes #4989 
No functional changes, just updates some jsdoc descriptions and visibility tags in Blockly and BlockSvg to be more accurate.
Docs or it didn't happen.
> Updates JSDoc in Block and BlockSvg

- demos/custom-fields/turtle/field_turtle.js
- demos/custom-fields/turtle/index.html
n/a
- Update placement of turtle svg elements when mask hat is selected so that text does not overlap field
- Remove extra 's' character from html
Cleanup
Tested zooming in/out to see that the placement appeared correct.
> Update turtle mask placement on custom field and remove typo

- tests/mocha/block_test.js
- tests/mocha/event_test.js
- tests/mocha/field_angle_test.js
- tests/mocha/field_checkbox_test.js
- tests/mocha/field_colour_test.js
- tests/mocha/field_dropdown_test.js
- tests/mocha/field_image_test.js
- tests/mocha/field_label_serializable_test.js
- tests/mocha/field_label_test.js
- tests/mocha/field_multilineinput_test.js
- tests/mocha/field_number_test.js
- tests/mocha/field_textinput_test.js
- tests/mocha/flyout_test.js
- tests/mocha/names_test.js
- tests/mocha/procedures_test.js
- tests/mocha/toolbox_test.js
- tests/mocha/utils_test.js
- tests/mocha/workspace_comment_test.js
- tests/mocha/workspace_svg_test.js
- tests/mocha/workspace_test.js
- tests/mocha/xml_test.js
n/a
Adds missing whitespace in mocha tests.
Cleanup. Noticed issue while browsing files.
Completed using a regex replace in the tests/mocha directory (excluding comments and string literals.
Find: ",([^\s])"
Replace: ", $1"
> Add missing whitespace to test files

- tests/mocha/run_mocha_tests_in_browser.js
https://github.com/google/blockly/issues/5030
Adds flag to webdriverio options.
Mocha tests fail when any .js files have been converted to `goog.module`.
Mocha tests pass.
Failing tests.
Tested by running `node tests/mocha/run_mocha_tests_in_browser.js` in this branch and on branch of https://github.com/cpcallen/blockly/tree/migrate with the same change.
This change should also be merged into the goog_module branch.
> Add flag to webdriverio options

- .eslintrc.json
- Removes eslint indentation rules because we are going to move to using clang format and clang format and eslint rules collide. 
- Removes `no-use-before-define` since we decided internally that this errors was no longer helpful.
> Removes eslint rules

- core/connection_db.js
- tests/deps.js
> Migrate core/connection_db.js to goog.module syntax

- scripts/goog_module/convert-file.sh
Update convert-file.sh script to prompt before destructuring a require.
(and fix some bugs accidentally introduced in previous PR)
> Prompt before destructuring properties for a require

- core/interfaces/i_collapsible_toolbox_item.js
- core/interfaces/i_registrable_field.js
- core/interfaces/i_selectable_toolbox_item.js
- core/keyboard_nav/tab_navigate_cursor.js
- core/renderers/common/info.js
Part of #5026
Silences unused variable warnings for requires used in JSDoc.
> Silences unused variable warnings for requires used in JSDoc.

- generators/javascript/colour.js
- tests/generators/run_generators_in_browser.js
- tests/mocha/run_mocha_tests_in_browser.js
- tests/scripts/run_generators.sh
This removes extra output from the generator tests that was caused by [this line](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/tests/generators/run_generators_in_browser.js#L26). 
- Change logLevel to 'error'. We still get any console output, we just don't get webdriverio output.
- Remove -silent from the `cmp` command so we can at least see what line the error happened on.
Lots of extra unhelpful output in tests.
Less unhelpful output, but still not a lot of helpful output.
Filed issue #5198 to look into providing better output in the future.
> Remove extra output from generator and mocha tests

- .github/workflows/tag_module_cleanup.yml
Reverts google/blockly#5315
Syntax was wrong and this is blocking.
> Revert "fix: update tag module workflow to add labels instead of setting one label"

- tests/generators/run_generators_in_browser.js
- tests/mocha/run_mocha_tests_in_browser.js
- tests/scripts/run_generators.sh
Cherry picks #5196 into `goog_module` so we have slightly nicer output for our generator tests. Also prints out the line that is failing so we can use it to debug our generator tests when they fail intermittently.
> Remove extra output from generator and mocha tests (#5196)

- .github/workflows/tag_module_cleanup.yml
Update `tag_module_cleanup.yml` logic to add labels instead of setting labels list.
Fixes: https://github.com/google/blockly/issues/5298
> Add labels instead of setting in github action

- appengine/add_timestamps.py
- scripts/gulpfiles/build_tasks.js
- scripts/i18n/common.py
- scripts/i18n/create_messages.py
- scripts/i18n/dedup_json.py
- scripts/i18n/js_to_json.py
- scripts/i18n/tests.py
https://github.com/google/blockly/issues/5080
Updates commands to run python scripts using `python3` and updating shebang lines.
- python 2.7 is deprecated and the commands need to updated in order to explicitly run with python 3. 
- We do not plan to continue supporting running these scripts with python 2.7
Ran `npm run build:langfiles` and `npm run generate:langfiles`
These python scripts have already been updated to be python 3 compatible.
> Update script to use python3 command

- scripts/gulpfiles/typings.js
Cherry pick https://github.com/google/blockly/pull/5359 into goog_module.
> Quiet the typings script unless you tell it to be verbose.

- core/component_manager.js
- core/theme_manager.js
- core/utils.js
- core/variable_map.js
- core/workspace.js
Recently added code doesn't use existing utility function.
> Use Blockly.utils.arrayRemove

- tests/mocha/index.html
Changes mocha tests to use node modules instead of unpkg.
Tests use latest version on unpkg.
Tests use version that is installed in node modules.
It is confusing to install a version of mocha and then use a different version from unpkg.
> test: Changes mocha tests to use node_modules instead of unpkg

- .github/workflows/build.yml
Remove support for node 10 as it is [no longer being maintained](https://nodejs.org/en/about/releases/).
> chore: remove support for node 10

- package.json
Disables the cache when we run `npm run start`.
When testing with the playground we have to do a hard refresh whenever the code changes.
When testing with the playground we only have to refresh the page.
> chore: disables caching when running the playground

- core/serialization/variables.js
- core/utils/useragent.js
Fixes jsdoc syntax errors on `goog_module` branch
Syntax errors need to be resolved in order to generate jsdoc documentation.
Ran jsdoc generation script.
> Fix goog module jsdoc

- core/common.js
- core/interfaces/i_selectable.js
- core/serialization/exceptions.js
- core/toolbox/category.js
- core/zoom_controls.js
- scripts/gulpfiles/build_tasks.js
Fixes #4457 
- Enables the `missingRequire` flag in `build_tasks`
- Adds the last few missing `requireTypes` needed to make this work
`build:debug` failed with error if `missingRequire` was enabled.
`build:debug` completes with no errors.
Better compiler checks -> more correct code.
> fix: enable missingRequire in build_tasks

- scripts/gulpfiles/release_tasks.js
`npm run publish` was throwing an error because we were not building the msg typings. 
In the publish script create the update the typings for messages.
> fix: Updates the release task to build typings for msgs

- core/widgetdiv.js
Fixes typo in alias annotation.
> Fix typo in alias

- core/blockly.js
Part of #5508
Adds alias annotations to additional properties 
Corrects issue where jsdoc for properties and methods were not generating on the correct page.
Tested by running jsdoc generation script on branch.
> Add missing @alias annotations

- core/theme/classic.js
- core/theme/zelos.js
Part of #5508
Adds jsdoc annotations to `Blockly.Theme` classes.
Adds class summary and property types to generated jsdoc page.
Tested by running jsdoc generation script on branch.
> Add JSDoc to theme classes.

- core/interfaces/i_registrable_field.js
- core/positionable_helpers.js
Part of #5508
Adds alias annotations to additional properties 
Corrects issue where jsdoc for properties and methods were not generating on the correct page.
Tested by running jsdoc generation script on branch.
> Add missing alias annotations

- tests/playground.html
JS Spaghetti button doesn't work in playground.
The API changed but the playground was not updated.
> fix: Fix JS Spaghetti button.

- blocks/lists.js
- blocks/logic.js
- blocks/loops.js
- blocks/math.js
- blocks/procedures.js
- blocks/text.js
- blocks/variables.js
- blocks/variables_dynamic.js
Part of https://github.com/google/blockly/issues/5160
Replace uses of `var` with `const` and `let` as appropriate.
No change in behaviour.
Get closer to google style guide.
Standard tests + opened all categories in the playground + played around with mutators on list blocks to test updateShape logic.
> chore: replace var with const and let in blocks directory

- .github/actions/assign_reviewers.js
- .github/workflows/assign_reviewers.yml
- .github/workflows/check_clang_format.yml
- .github/workflows/scripts/assign_reviewers.js
#5643
Adds a github action to assign a PR to the requested reviewer.
Detailed in #5643
> chore: adds initial action to assign reviewers

- core/renderers/zelos/info.js
> fix(zelos): typo

- generators/javascript/math.js
- tests/generators/golden/generated.js
> fix: isPrime block should cast str as num

- .github/workflows/check_clang_format.yml
- core/touch.js
- package-lock.json
- package.json
- scripts/gulpfiles/build_tasks.js
The clang format github action we had was failing after developers ran `npm run format` due to an out of date clang format version used in the npm clang-format package.
- Update to use clang-format version 1.6.0
- Update our gulp script to use the imported clang format version. This did not help this issue, but just seems like good practice.
Running `npm run format` would give us:
```
return e.pointerId !== undefined ?
e.pointerId :
(e.changedTouches && e.changedTouches[0] &&
e.changedTouches[0].identifier !== undefined &&
e.changedTouches[0].identifier !== null) ?
e.changedTouches[0].identifier :
'mouse';
```
This is different than what the github action expects and therefore fails CI.
Running `npm run format` gives us:
```
return e.pointerId !== undefined ? e.pointerId : …
```
> chore: applies fixes to clang format

- .eslintrc.json
- core/common.js
- package-lock.json
- package.json
- scripts/migration/renamings.js
Closes #5160 
- Add `eslint-config-google` as a dev dependency.
- Extend `"google"` in our `.eslintrc.json`
- Fix a few remaining comma dangles.
No change in behaviour.
No change in behaviour.
New lint!
a) conforming to Google style
b) using the same style in both blockly and blockly-samples.
> chore: enable eslint-config-google

- core/interfaces/i_positionable.js
- core/trashcan.js
- core/zoom_controls.js
> fix: Prevent error when maxTrashcanContents is 0

- generators/javascript/procedures.js
- tests/deps.js
Part of #5598 
Converts to goog.module with named requires, and fixes missingRequires.
> refactor: convert generators/javascript/procedures.js to goog.module

- generators/javascript/loops.js
- tests/deps.js
Part of #5598 
Converts to goog.module with named requires, and fixes missingRequires.
> refactor: convert generators/javascript/loops.js to goog.module

- core/blockly.js
- scripts/gulpfiles/build_tasks.js
https://github.com/google/blockly-samples/issues/902
Sets the compiled flag to true when we compile.
Samples tests were failing. See https://github.com/google/blockly-samples/issues/902 for more information.
Samples tests work! 🎊
> chore: sets the compiled flag to true

- core/block_svg.js
Makes block.checkAndDelete a public API that can be used in keyboard navigation.
checkAndDelete was package.
checkAndDelete is public.
This was necessary to not have to copy and paste this function into keyboard navigation. PR #942 uses this.
> feat: make checkAndDelete a public API

- core/utils.js
- core/utils/parsing.js
The deprecation notices for Blockly.parsing were incorrect.
Change `Blockly.parsing.X` --> `Blockly.utils.parsing.X`.
Prints out incorrect name for functions under the parsing namespace. 
Prints out correct name for functions under the parsing namespace.
Found this while trying to fix a warning in samples.
> chore: updates the names for parsing

- README.md
#5817
Updates the release date and version numbering scheme in the README.
> docs: Update the README to reflect the next release date.

- package-lock.json
- package.json
Fixes #5697 
Fixes the advanced playground by updating the version of dev-tools we use in core. 
Advanced playground was broken.
Advanced playground works 🎉 
We need to cherry pick this into master for the upcoming patch release.
> chore: update the dev-tools version

- package-lock.json
This is a follow up to #5826 where I forgot to add the package-lock after updating the version number.
Update the package-lock
> chore: update the package-lock

- core/touch.js
With current testing devices I was not able to pinpoint a specific bug that this resolves (I don't have access to a phone running v12 of Safari.), however according to code.org tests this solves a bug on safari v12 on mobile. 
Adds a check for `e.changedTouches` in `setClientFromTouch`.
According to [code.org comments](https://github.com/code-dot-org/code-dot-org/blob/a93d3c2a15910e6dfc1aafda62747bae9b4ce5ae/apps/src/blockly/addons/cdoTouch.js#L7) as well as [caniuse](https://caniuse.com/?search=Event.changedTouches) changedTouches is not available in older versions of Safari. 
- We are working on getting code.org on the version 7 of Blockly. They were monkey patching `setClientFromTouch` in a way that is no longer supported in v7.
- We do this same check in other places in the file, …
> fix: Adds check for changedTouches

- scripts/gulpfiles/build_tasks.js
A certain amount of developer pain.
Because of our mis-use of `@package`, and the removal of the hack that made it work reasonably (in PR #5918), compilation has been generating a large number of `JSC_BAD_PACKAGE_PROPERTY_ACCESS` warnings, making it hard to see any other warnings/errors that might be generated.
To make compiler diagnostics more useful, disable the `visibility` diagnostic group entirely for the time being.
Also improve the documentation for `JSCOMP_ERROR` and the newly-introduced `JSCOMP_WARNING` and `JSCOMP_OFF`.
`npm run build-debug` generates over 1000 `JSC_BAD_PACKAGE_PROPERTY_ACCESS` warnings.
`npm run build-debug` generates no errors or warnings.
Make it easier to see any other warnings/errors generated.
* `npm run test` completes successfully.
* This does risk us …
> chore(build): Disable `visibility` warnings

- core/renderers/common/block_rendering.js
- core/renderers/common/debug.js
Deprecate the debug renderer because it is being moved to @blockly/dev-tools. See the [dev-tools README](https://www.npmjs.com/package/@blockly/dev-tools) for more information.
> deprecate: the debug renderer

- core/renderers/common/renderer.js
Work on #5860 
Convert to a class.
Should be no change in behavior 🤞 
The yellow brick road to TypeScript
All unit tests pass.
N/A
N/A
> fix: convert the common renderer to an ES6 class

- tests/playground.html
- tests/playgrounds/blockly.mjs
N/A
Returns the global Blockly from `blockly.mjs` instead of the `goog.module.get('Blockly'` so that the window `Blockly` object and the playground's module `Blockly` object are the same object.
Not sure if this will need to change later, but it's necessary right now so that the playground module can have access to the language generators.
Also changes the on click handlers to be defined within the module instead of via html tags b/c scoping.
There were 2 `Blockly` objects, one in the module and one that was global.
None of the test buttons worked.
There is only 1 `Blockly` object. The module is given access to the global.
All of the test buttons work.
Need to be able to test for the release!
N/A
N/A
> fix: playground access to Blockly for testing

- .github/PULL_REQUEST_TEMPLATE.md
Part of #5604 was to find a way to tell developers what they should run when clang-format has failed. I am sure there is a way to run a GitHub action do it, but I am not sure we have the time to spend on it currently. I think having information on how to format the code in the PR will serve a similar purpose as commenting on the code. 
Even if we get the comment working, I still think we want to tell developers before their build fails that they need to run `npm run format`. 
Adds run `npm run format` to our check list of tasks to finish before creating a PR. 
The other option is to have a single command that includes lint, formatting and running the closure compiler to see any type problems.
> chore: update PR template to include formatting info

- core/block.js
- core/events/events_block_create.js
- core/events/events_block_delete.js
- tests/mocha/event_test.js
- tests/playgrounds/screenshot.js
This reverts commit bce4c5e2c61b3d3e8bbb99694af18f99dbfc4d50.
Closes #6001 
Reopens #5438
> fix: revert "Delete events should animate when played (#5919)"

- tests/playgrounds/screenshot.js
Silences lint warning in screenshot.js. This is "unused" because it's imported into the playground directly via script tag and used, so it's not exported anywhere.
> chore: fix screenshot lint

- scripts/migration/renamings.json5
N/A
Updates the renamings file so that renames are correctly associated with 8.0.0
I'll add a step to our internal release docs for doing this.
I think this will need to be cherry picked into master.
> chore: update renamings file for new release

- .github/release-please.yml
Add 'handleGHRelease' so that it will create a github release and tag it.
> chore: update release please to handle github releases

- core/utils/svg_math.js
> chore: Reduce number of calls to getAttribute

- .github/PULL_REQUEST_TEMPLATE.md
Note code! Needs to go into master.
N/A
Makes the pull request template explicit about what testing information we want.
Makes it easier for us to manually test things before release to prevent bugs. And makes it easier for contributors to provide information about what to test.
> chore: update PR template for test requirements

- scripts/gulpfiles/build_tasks.js
Delete `flattenCorePaths` and `unflattenCorePaths`.
Unchanged.
We are no longer using either function, so delete them.
Passes `npm test`.  No changes to manual testing required.
> chore(build): Delete flattenCorePaths

- msg/json/fr.json
- msg/json/ia.json
Not a security issue, just gets printed literally.
> fix: HTML is not allowed in messages

- core/blockly_options.ts
Work on #5857 
Add type information to the BlocklyOptions interface
No type information (ie no checking and no intellisense)
Yes type information!
Type checking and intellisense are helpful.
N/A, this is types
https://developers.google.com/blockly/guides/configure/web/configuration_struct is out of date. It should have info about `rendererOverrides` and possibly `parentWorkspace`
N/A
> fix: add type information to blockly options

- tests/bootstrap.js
- tests/playground.html
]
N/A
Reverts accidental changes to the files the playground uses for including blockly.
This should be handled by #6218
> chore: revert changes to playground used for testing

- core/block_animations.ts
N/A
Remove AnyDuringMigration from block animations.
N/A
N/A
N/A
> chore: remove AnyDuringMigration from block animations

- core/bump_objects.ts
N/A
Remove AnyDuringMigration from bump objects.
N/A
N/A
N/A
> chore: remove AnyDuringMigration from bump objects

- core/browser_events.ts
- core/bubble.ts
- core/flyout_base.ts
- core/gesture.ts
- core/icon.ts
- core/mutator.ts
- core/scrollbar.ts
- core/toolbox/toolbox.ts
- core/touch_gesture.ts
- core/utils.ts
- core/workspace_comment_svg.ts
- core/workspace_svg.ts
N/A
Remove AnyDuringMigration from block drag surface.
N/A
N/A
N/A
> refactor: remove AnyDuringMigration from browser events

- core/comment.ts
N/A
Remove AnyDuringMigration from the comment icon.
N/A
N/A
N/A
> refactor: remove AnyDuringMigration from the comment icon

- core/connection.ts
N/A
Remove AnyDuringMigration from connection.
N/A
N/A
N/A
> refactor: remove AnyDuringMigration from connection

- core/bubble_dragger.ts
- core/gesture.ts
N/A
Remove AnyDuringMigration from bubble dragger.
N/A
N/A
N/A
> refactor: remove AnyDuringMigration from bubble dragger

- core/blockly.ts
- core/common.ts
- core/main.js
Work on #5857 
* Adds an accessor for `getSelected` to `Blockly`
* Updates the setters and getters in `main.js` to point you to the accessors on `Blockly`.
* Updates some of the docs.
No accessor
Accessor!
We don't really want external developers to have to use `common`, since it was just used to break some circular dependencies.
N/A
We probably have documentation that still points to `mainWorkspace` and `selected` that should be updated.
Removal date is September 2022 so that we can remove `main.js` as soon as possible.
> feat: updates accessors for getMainWorkspace and getSelected

- core/input.ts
N/A
Remove AnyDuringMigration from input.
N/A
N/A
N/A
> refactor: remove AnyDuringMigration from input

- tests/playgrounds/advanced_playground.html
N/A
Makes the advanced playground actually work.
The advanced playground would not work due to the import path being incorrect (404 error)
The advanced playground loads!
We need the advanced playground to work in develop so that we can onboard our new tester.
N/A
N/A
> chore: fix the advanced playground

- tests/bootstrap.js
Part of #6325
Remove specific support for IE11 and additionally refactor `bootstrap.js` to use ES6 constructs where applicable.
Remove technical debt.
> chore(tests): Remove IE11 / ES5-only support from `bootstrap.js`

- core/renderers/common/constants.ts
- core/renderers/geras/constants.ts
- core/renderers/zelos/constants.ts
N/A
Just fixing some formatting.
> chore: format css

- core/block_animations.ts
- core/common.ts
- core/dropdowndiv.ts
- core/extensions.ts
- core/flyout_base.ts
- core/flyout_metrics_manager.ts
- core/generator.ts
- core/keyboard_nav/basic_cursor.ts
- core/menu.ts
- core/menuitem.ts
- core/mutator.ts
- core/procedures.ts
- core/utils.ts
- core/utils/aria.ts
- core/utils/array.ts
- core/utils/idgenerator.ts
- core/utils/parsing.ts
- core/variables.ts
- core/variables_dynamic.ts
Part of #5857.
Replaces some more uses of AnyDuringMigration with actual types.
> refactor: Remove more uses of AnyDuringMigration.

- .github/CONTRIBUTING.md
Part of #6325 
Remove mention of IE from `CONTRIBUTING.md`.
> chore: remove IE support from CONTRIBUTING.md

- scripts/gulpfiles/release_tasks.js
N/A
Fixes the release script so it doesn't yell at us when directories don't exist (cuz they're not supposed to anymore).
SHould be no change in user-facing behavior.
SHould be no change in user-facing behavior.
Being able to release the package is important.
Did the beta release with these changes and it worked.
N/A
N/A
> chore: fix release tasks checking for bad directories

- core/block_svg.ts
- core/renderers/common/drawer.ts
- core/renderers/common/i_path_object.ts
- core/renderers/common/info.ts
- core/renderers/geras/constants.ts
- core/renderers/geras/drawer.ts
- core/renderers/geras/highlighter.ts
- core/renderers/geras/path_object.ts
- core/renderers/geras/renderer.ts
- core/renderers/measurables/row.ts
- core/renderers/measurables/top_row.ts
- core/renderers/minimalist/info.ts
- core/renderers/thrasos/info.ts
- core/renderers/zelos/constants.ts
- core/renderers/zelos/drawer.ts
- core/renderers/zelos/info.ts
- core/renderers/zelos/marker_svg.ts
- core/renderers/zelos/measurables/inputs.ts
- core/renderers/zelos/measurables/row_elements.ts
- core/renderers/zelos/path_object.ts
Work on #5857 
Removes `AnyDuringMigration` from the non-common renderers.
Should be no change in user-facing behavior.
Should be no change in user-facing behavior.
Tyyypes
N/A
N/A
Dependent on #6402
> chore: remove AnyDuringMigration from the other renderers

- core/block.ts
- core/block_svg.ts
Part of the outstanding AnyDuringMigration issues.
Fix some leftover AnyDuringMigrations where no code change was needed.
No change
No change
Cleanup
Mocha
> fix: some AnyDuringMigration

- typings/dart.d.ts
- typings/javascript.d.ts
- typings/lua.d.ts
- typings/php.d.ts
- typings/python.d.ts
Work on #6358 
Fixes the type declarations for the generators. They're still typed as `any` until we actually convert the generators to typescript, but at least the declarations match the way you're supposed to import the generators.
Import5ing the generators the correct way would result in type errors.
No type errors!
Type errors make  me sad =(
Linked to the dev tools plugin with https://github.com/google/blockly-samples/pull/1236 implemented.
We need to update the documentation on importing the generators before the release. But that's my job!
N/A
> fix: generator type declarations

- core/flyout_metrics_manager.ts
- core/grid.ts
- core/rendered_connection.ts
- core/renderers/common/debugger.ts
- core/renderers/common/marker_svg.ts
- core/scrollbar.ts
- core/toolbox/category.ts
- core/toolbox/separator.ts
- core/utils/dom.ts
- core/workspace_comment.ts
Part of #5857
Removes and replaces uses of AnyDuringMigration with proper type information.
> refactor: Remove more uses of AnyDuringMigration

- core/renderers/geras/path_object.ts
Somehow some type problem snuck into develop. This fixes them.
Makes sure that the geras path object checks for theme properties before it accesses them.
No change in user-facing behavior.
No change in user-facing behavior.
We like the build to build.
N/A
N/A
N/A
> fix: path object not checking theme props

- core/field.ts
Changes in core needed to fix https://github.com/google/blockly-samples/issues/1268
We are no longer setting `DEFAULT_VALUE` directly on the prototype of `Field` so our old logic for this wasn't working correctly. (External developers are still expected to put `DEFAULT_VALUE` directly on the prototype)
So now we are checking whether the property exists on the prototype, and using that if it does. If it doesn't exist, we're assigning `null`, which is equivalent to how the system worked before, when we were setting `DEFAULT_VALUE` directly on the prototype of `Field`.
Breaking everyone who relied on the `DEFAULT_VALUE` behavior.
No more breaking!
Backwards compatibility.
Linked to the field-bitmap plugin and confirmed that this fixed the test failures.
N/A
N/A
> fix: field defaults not being defined correctly

- scripts/migration/renamings.json5
N/A
Updates the renamings file so that renames are correctly associated with 9.0.0
Prep for the release.
> chore: update renamings to be v9

- scripts/package/README.md
This is just a docs update. Updates the package readme (which is what appears on npm) to show how to properly import the library blocks and generators.
> chore: update readme

- tests/scripts/check_metadata.sh
Update metadata tests with file sizes for 2022 Q3 release.
> chore(tests): Update metadata for 2022 Q3 release

- tests/mocha/index.html
- tests/mocha/procedure_map_test.js
N/A
Adds some unit tests (currently skipped b/c they fail) for the procedure map (which will be added).
Tests are good for verifying behavior :D
N/A
N/A
> test: add skipped tests for the procedure map

- scripts/migration/renamings.json5
N/A
Fixes a typo in the renamings database.
The `@blockly/migration` script would incorrectly migrate php.
The migration (or in this case, lack of one) is correct.
We want people to trust using the migration script.
N/A - should be covered by previous testing.
N/A
This actually does need to go against master, because the migration script [looks at master](https://github.com/google/blockly-samples/blob/5f95f6802878f9cadd4c9203a72916c1f82fe05d/plugins/migration/bin/rename.js#L20).
> chore: fix typo in renamings database

- package-lock.json
- package.json
Bumps all of our `@blockly` packages to the latest major.
Had to do a force install to get it to figure out the peer dependencies, but I think it should be fine going forward.
> chore(deps): force update @blockly deps

- core/blockly.ts
- core/procedures.ts
- core/procedures/observable_parameter_model.ts
- core/procedures/observable_procedure_map.ts
- core/procedures/observable_procedure_model.ts
- tests/mocha/procedure_map_test.js
Fixes #6561 
🎵 Updates the tests 🎵
Tests should test.
N/A
Dependent on #6560
> chore: update procedure map tests to match the refactored API

- core/procedures/observable_parameter_model.ts
- core/procedures/observable_procedure_map.ts
#6514
Resolves PR feedback on #6489 
Requested in a PR review that didn't get sent due to trains 🚂
N/A - gonna handle in a follow up when I update the tests to match the new API.
N/A
N/A
> fix: feedback on procedure model implementations

- core/serialization.ts
- core/serialization/priorities.ts
- core/serialization/procedures.ts
- tests/mocha/jso_deserialization_test.js
- tests/mocha/jso_serialization_test.js
Fixes #6522 
Adds a serializer for procedure models.
No procedure data model serialization.
Procedure data model serialization!
Saving data is important.
Unskipped tests written in #6574 
N/A
N/A
> feat: add serialization of procedure models

- tests/mocha/procedure_map_test.js
#6517 
Adds unit tests for firing procedure events.
Unit tests are good!
Tests for when all of the different types of tests should be fired.
N/A
N/A
> test: firing procedure events

- core/serialization/procedures.ts
- tests/mocha/jso_serialization_test.js
N/A
Temporarily disables serialization for point release.
Want to make sure we don't accidentally mess up people's save data when they use the point release (since this needs more testing for me to be 100% confident in it).
Skips relevant tests.
N/A
N/A
> chore: disable serialization of procedure data for point release

- tests/mocha/event_procedure_change_return_test.js
- tests/mocha/event_procedure_create_test.js
- tests/mocha/event_procedure_delete_test.js
- tests/mocha/event_procedure_enable_test.js
- tests/mocha/event_procedure_parameter_create_test.js
- tests/mocha/event_procedure_parameter_delete_test.js
- tests/mocha/event_procedure_parameter_rename_test.js
- tests/mocha/event_procedure_rename_test.js
Fixes #6600 
Adds tests for round-tripping procedure events through serialization.
Tests make me happy :D
N/A
N/A
> chore: procedure event serialization

- core/blocks.ts
- core/icon.ts
- scripts/gulpfiles/build_tasks.js
- tests/generators/webdriver.js
- tests/mocha/webdriver.js
* Better description for `Icon.prototype.setVisible` (and tweaked description for getBlock to use @returns).
* Fix type in description of `type BlockDefinition` ("lose" -> "loose").
* Factor out common `goog:chromeOptions` in mocha and generators `webdriver.js`s.
* Minor style fixes in `build_tasks.js`.
Cleaning out my saved stashes.
* Passes `npm test`.
* No changes to manual test procedures required.
Improved.
> chore: miscellaneous fixes to docs, style, and tests

- typings/README.md
N/A
Updates the readme related to typings.
Updated docs are nice!
> chore: update typings docs

- tests/scripts/check_metadata.sh
Update metadata tests with file sizes for 2022 Q4 release.
> chore(tests): Update metadata for 2022 Q4 release

- core/mutator.ts
- tests/mocha/blocks/procedures_test.js
- tests/mocha/test_helpers/procedures.js
Fixes #3781
Adds tests for the user-facing behavior of procedure blocks, as well as the internal (new!) behavior of updating the data models, and responding to data model updates.
Hopefully prevent breakages during procedure block refactoring 🤞 
N/A
Dependent on #6669
> chore(tests): procedure blocks

- blocks/procedures.js
Work on #6526 
Refactors the procedure blocks to use JSON definitions with extensions.
Easier to parse the logic + reuse code in plugins.
Tests from before are still running to ensurer behavior is consistent.
N/A
Dependent on #6670
> feat: refactor procedure blocks

- blocks/procedures.js
Fixes https://github.com/google/blockly/pull/6718#pullrequestreview-1246335158
Fixes type annotations so that closure no longer complains.
> chore: fix closure type errors

- core/generator.ts
Adds a helpful docs link to an error.
> chore: add docs link to generator error

- blocks/procedures.js
- core/interfaces/i_procedure_block.ts
- core/procedures.ts
Fixes N/A
Reexport procedure related symbols so people can actually uh use them.
> chore: reexport procedure related symbols

- blocks/procedures.js
- tests/mocha/blocks/procedures_test.js
Work on moving the procedures stuff out of core and into a plugin.
Reversions.
We don't want these changes in core anymore.
Deleted tests =(
N/A
N/A
> chore: revert changes to procedure blocks

- core/variable_map.ts
- scripts/gulpfiles/release_tasks.js
https://groups.google.com/g/blockly/c/l_vUnrGSJ0M
> fix: Fire deletion events when clearing variables.

- core/events/events_abstract.ts
Resolves #6830.
https://groups.google.com/g/blockly/c/uy_8e7Q8XEw/m/8XveAYi3AQAJ
> fix: move deprecation warning to correct fromJson

- core/main.js
Fixes N/A, reported by https://groups.google.com/g/blockly/c/v_UKly84WUI
Adds info about what to use instead of the deprecated properties.
Also changes the deprecation dates to use versions instead (since that's our new format).
Makes it easier for developers to find the new methods they're supposed to use.
N/A
This is documentation silly!
N/A
> chore: fixup dialog deprecation warnings

- core/events/events_var_create.ts
- core/events/events_var_delete.ts
- tests/mocha/event_var_create_test.js
- tests/mocha/event_var_delete_test.js
Fixes #6823 
Checks for undefined-ness, rather than falseyness in types, so that untyped variables (i.e. those with a type of `''`) do not fail.
Fixing bugs!
Added tests for round-tripping untyped variables.
N/A
N/A
> fix: variable events not deserializing properly

- core/insertion_marker_manager.ts
- core/render_management.ts
- core/rendered_connection.ts
Changes requested on #6851 after merge.
> chore: cleanup render management

- blocks/colour.ts
Part of https://github.com/google/blockly/issues/6828.
> refactor(blocks): Migrate `blocks/colour.js` to TypeScript

- scripts/migration/renamings.json5
N/A
Updates the renamings file to be correct for this release.
Note that the [gesture change happened in 9.2.0](https://github.com/google/blockly/commit/90cb965e7c53650d630d65f96d201b4ffaeec88d) but it looks like the renamings file wasn't updated, so I've fixed that.
> chore: update renamings file for 2023 Q1 release

- tests/scripts/check_metadata.sh
Updates metadata sizes for the new release.
> chore: Update metadata for 2023 Q1 release

- core/insertion_marker_manager.ts
> fix: Fix offset location of connection ripple

- core/field_label.ts
https://groups.google.com/g/blockly/c/S5b3iKB2Sos
> fix: Don't truncate text label fields.

- package-lock.json
- package.json
Merge master back into develop.
1) Branched `release/master-to-develop-v9.3.3` from develop.
2) Merged `master` into `release/master-to-develop-v9.3.3.` via the command line, resolving conflicts in `ab3a796f`.
3) Put up this PR to merge `release/master-to-develop-v9.3.3` into `develop`.
Therefore we should have all of the changes currently on master in develop (importantly the updates to the version number).
> chore: Merge master back into develop following v9.3.3 release

- tests/mocha/icon_test.js
- tests/mocha/index.html
- tests/mocha/test_helpers/block_definitions.js
Fixes #7035 
Adds tests for checking that the API hooks on icons are called at the proper times by its block.
Tests make me happy :D
N/A
N/A
> test: icon block hooks

- tests/mocha/block_test.js
Fixes #7034 
Adds unit tests for adding, removing, and accessing icons.
Tests are good :D
N/A
N/A
> chore: test icon management

- core/bubbles/text_bubble.ts
Fixes #7044 
Creates a TextBubble that visualizes text.
We want bubbles to be pure views with a object oriented structure. This works toward that =)
Manually tested by hacking into the warning icon. Looks the same as bubbles did previously.
N/A
Dependent on #7071
> feat: text bubble

- core/block_dragger.ts
- core/block_svg.ts
- core/interfaces/i_has_bubble.ts
- core/renderers/common/drawer.ts
- core/renderers/measurables/icon.ts
- core/serialization/blocks.ts
Fixes N/A
Makes it so that icon locations are properly updated.
Important for dragging blocks with open bubbles,
Manually tested with new warning icons (will open PR in a bit).
N/A
Dependent on #7101
> fix: updating icon locations

- generators/javascript.js
PR comments on #7153
Fix a comment.
> chore(generators): Comment tweak for PR #7153

- core/theme.ts
Fixes N/A
Makes it so that themes allow overrides during registration, so that if you import a theme twice (e.g. once directly and once via dev-tools) you don't get errors.
Double imports would cause errors.
Double imports do not cause errors.
We can't get rid of the side effects (unless we want to make that breaking change), but we can make it so the side effects don't cause errors.
N/A
N/A
N/A
> chore: allow themes to override eachother

- core/bubbles/bubble.ts
- core/bubbles/mini_workspace_bubble.ts
- core/bubbles/text_bubble.ts
- core/bubbles/textinput_bubble.ts
- core/icons/comment_icon.ts
- core/icons/exceptions.ts
- core/icons/icon.ts
- core/icons/icon_types.ts
- core/icons/mutator_icon.ts
- core/icons/warning_icon.ts
- core/inputs/input.ts
Fixes N/A
Adds some top-level inline docs so that our doc previews are more helpful =)
N/A - no behavioral changes!
This is documentation :D
N/A
> chore: add top-level inline docs to bubbles icons and inputs

- core/icons/icon.ts
Fixes N/A
Adds a wrapper method `setVisible` which calls `setBubbleVisible` to match the old `setVisible` method, so that we don't break people's code.
Not breaking people's code.
N/A
N/A
Reported by clement: https://groups.google.com/g/blockly/c/l1wnlLNoAlk/m/loM1UJ56AQAJ
> chore: add setVisible

- tests/browser/test/procedure_test.js
- tests/browser/test/test_setup.js
Fixes N/A
Flyout test helpers should actually work now :P Since the browser context is getting properly piped through the helpers.
> chore: fixup flyout test helpers

- tests/browser/test/extensive_test.js
- tests/browser/test/test_setup.js
Added testing for loading blocks and large interconnected block deletion.
> chore: Added test for loading json and interblock deletion

- tests/browser/test/basic_playground_test.js
Resolves [#7276](https://github.com/google/blockly/issues/7276)
- Switch to clearing the workspace after tests in this suite, instead of reloading the window before tests.
- Add tests for adding and removing comments through the right-click menu
> chore(tests): Add tests for adding and removing comments

- scripts/migration/renamings.json5
Fixes N/A
"Blocky" -> "Block*ly*" in the renamings script.
Typos breaking people :/
N/A
N/A
N/A
> fix: renamings for v10

- scripts/migration/renamings.json5
> chore: fix renamings for v10

- package-lock.json
- package.json
Fixes N/A
Updates the dependency on test blocks so that the basic mutator block in the playground works properly
> chore: update block test dependency

- .github/PULL_REQUEST_TEMPLATE.md
Fixes N/A
Removes sections of the PR template that are rarely used.
They are rarely used, so no sense making new people waste time on them :P
N/A
N/A
N/A
> chore: remove unused sections from PR template

- core/insertion_marker_manager.ts
Fixes N/A
Makes it so that insertion markers do full serialization.
Insertion markers should not share state with their actual blocks.
N/A
N/A
N/A
> fix: doFullSerialization for insertion markers

- core/flyout_base.ts
Fixes https://github.com/google/blockly/issues/7461
> feat: Add a getTargetWorkspace method to flyout_base.ts

- core/icons/comment_icon.ts
- core/icons/mutator_icon.ts
- core/icons/warning_icon.ts
Fixes #7623 
Modified the initView method to call dom.addClass for each file specified in the issue.
> feat: add css classes to icons

- core/events/events_block_field_intermediate_change.ts
- tests/mocha/event_block_field_intermediate_change_test.js
Fixes  https://github.com/google/blockly/issues/7601
> feat: added intermediate event change

- core/interfaces/i_parameter_model.ts
- core/interfaces/i_procedure_model.ts
- core/serialization/procedures.ts
- tests/mocha/jso_deserialization_test.js
- tests/mocha/jso_serialization_test.js
- tests/mocha/test_helpers/procedures.js
Fixes #7397 
Adds `saveState` and `loadState` hooks to procedure models and parameter models...
...so they can be easily overriden in downstream applications.
Refactored automated tests.
Needs updates to documentation - filed a separate task for that.
Also needs updates in the procedures plugin - filed a separate task for that.
If you are using [custom procedure models](https://developers.google.com/blockly/guides/create-custom-blocks/procedures/creating-custom-procedure-data-models), you need to add `saveState` and `loadState` hooks to them.
> feat!: add serialization hooks to procedure models

- core/block_svg.ts
- core/icons/comment_icon.ts
- core/icons/mutator_icon.ts
- core/icons/warning_icon.ts
- core/interfaces/i_has_bubble.ts
- tests/mocha/blocks/procedures_test.js
- tests/mocha/comment_test.js
- tests/mocha/mutator_test.js
Fixes #7068 
Makes it so the icons' `setBubbleVisible` methods wait for the current render to complete before showing their bubbles. 
This way we know the location information is updated so the bubbles will show up in the right spot, but we're also not triggering an immediate render, which is bad for performance.
Updated tests to use promises.
Need to check docs on custom icons. Also needs changes in the release notes.
N/A
If you are calling `setBubbleVisible` and then accessing the contents of the open bubble, you now need to wait for the promise returned by `setBubbleVisible` to resolve before accessing the contents.
```js
function openBubbleAndDoStuff(block) {
const icon = block.getIcon(Blockly.icons.IconType.MUTATOR);
icon.setBubbleVisible(true);
icon.getWorkspace().doStuff();
}
``` …
> feat!: modify icons to use the rendering queue

- core/rendered_connection.ts
- core/renderers/common/drawer.ts
- core/renderers/common/path_object.ts
- core/renderers/common/renderer.ts
- core/renderers/geras/drawer.ts
- core/renderers/measurables/connection.ts
- core/renderers/zelos/drawer.ts
- core/renderers/zelos/renderer.ts
Work on #7204 
Makes it so that zelos highlights connections in the same cases where the base renderer does (no more special casing).
To get this working, I also had to get updating connection highlight locations working. Because in zelos connecting an insertion marker changes the location of a connection. Now if a connection changes location while it is highlighted, the highlight changes location to match.
Now highlighting happens as part of the normal draw loop, so I removed the top-level APIs on the render class. This is not a breaking change because this code hasn't been released yet. I removed it to keep the API smaller.
1) Open the playground.
1) Drag a "logic_compare" block into the workspace.
2) Run the following code in the console.
```js
block = …
```
> fix: highlighting connections in zelos, also highlight connections moving

- core/render_management.ts
- scripts/gulpfiles/build_tasks.js
- tests/mocha/render_management_test.js
- tests/typescript/src/generators.ts
Fixes N/A
Makes it so that the v11 branch passes lint.
> chore: fix v11 branch build

- package-lock.json
- package.json
Fixes N/A
CI was failing, see https://github.com/webdriverio/webdriverio/issues/12251 and https://github.com/puppeteer/puppeteer/pull/11923 
This fixes that by updating to the latest version of webdriverio.
Hopefully CI passes!
N/A
N/A
> chore: update webdriverio to fix chrome endpoint issue

- core/common.ts
> chore: fix spelling in common.ts

- core/connection_previewers/insertion_marker_previewer.ts
- package-lock.json
- package.json
Releases the fix to connections in zelos previewing and unpreviewing repeatedly.
> release: v10.4.3

- core/comments.ts
- core/comments/rendered_workspace_comment.ts
- core/comments/workspace_comment.ts
Work on #7907 
Adds an extremely basic rendered workspace comment class.
Manually tested that everything is connected correctly.
We can't automatically test that the view gets updated correctly since we don't have screenshot testing.
Ensuring that the model gets updated will be covered by future serialization tests.
N/A
N/A
> feat: rendered workspace comment

- core/connection.ts
- core/render_management.ts
- core/xml.ts
- demos/blockfactory/block_definition_extractor.js
- scripts/migration/renamings.json5
- tests/scripts/load.mjs
> chore: remove repetitive words in comments

- core/comments/workspace_comment.ts
- core/events/events.ts
- core/events/events_comment_collapse.ts
- core/events/utils.ts
- tests/mocha/event_comment_collapse_test.js
- tests/mocha/index.html
- tests/mocha/workspace_comment_test.js
Fixes #7909 
Adds the final event to workspace comments. It signals when the comment has been collapsed or uncollapsed.
Manually tested that undo and redo work properly. Also added a round-trip test.
N/A
N/A
> feat: comment collapse event

- core/block_svg.ts
Fixes N/A
Renames `toFlyoutData` to `toFlyoutInfo`.
Matches naming of the type returned.
N/A
N/A
N/A
> fix: backpack compatibility (rename `toFlyoutData` to `toFlyoutInfo`)

- core/blockly.ts
- core/dragging.ts
Fixes N/A
More drag-related things that should be exported but weren't.
N/A
N/A
N/A
> fix: more drag exports

- core/bubbles/textinput_bubble.ts
Fixes N/A
The CSS for text input bubbles wasn't being properly applied.
Old:
New:
See above screenshots.
N/A
N/A
> fix: text input bubble css

- core/bump_objects.ts
- core/dragging/comment_drag_strategy.ts
Fixes N/A
Fixes bumping comments into bounds so it actually works.
Manually tested that bumping into bounds works properly.
N/A
Dependent on https://github.com/google/blockly/pull/8036
> fix: bumping comments into bounds

- core/insertion_marker_previewer.ts
Fixes https://github.com/google/blockly/issues/8110
Fixes https://github.com/google/blockly/issues/8111
Reimplements changes from https://github.com/google/blockly/pull/7899 which seem to have gotten messed up in a merge resolution at some point.
Fixing buggies.
Manually tested that neither issue reproduces.
N/A
N/A
> fix: extra insertion markers being created

- tests/playground.html
I would just personally prefer this had a different name. Happy to close if it bugs people.
> chore: rename airstrike -> scatter

- core/comments/rendered_workspace_comment.ts
- core/dragging/comment_drag_strategy.ts
Fixes https://github.com/google/blockly/issues/8112
Fixes https://github.com/google/blockly/issues/8124 (the other half)
Snaps the comment from the correct locations so that events are fired in the right order and grouped correctly.
N/A
N/A
N/A
> fix: comment move events and snapping

- core/bump_objects.ts
- core/comments/comment_view.ts
- core/comments/workspace_comment.ts
- core/dragging/comment_drag_strategy.ts
- core/events/events.ts
- core/events/events_comment_drag.ts
- core/events/events_comment_resize.ts
- core/events/utils.ts
- core/utils/size.ts
- tests/mocha/event_comment_drag_test.js
- tests/mocha/event_comment_resize_test.js
- tests/mocha/event_test.js
- tests/mocha/index.html
- tests/mocha/workspace_comment_test.js
Just bringing over the updated comment events.
> chore: Merge develop into v12

- package-lock.json
- package.json
Reverts #8209, due to this gotten our `package-lock.json` out of sync with `package.json` and thus breaking `npm ci`.
> fix(deps): Revert "chore(deps): bump the npm_and_yarn group across 1 directory with 7 updates"

- core/field_variable.ts
> feat: Add a `blocklyVariableField` CSS class to variable fields

- core/block_svg.ts
Fixes: #8264 
**feat: Add a blocklyCollapsed CSS class to collapsed blocks' root SVG (#8264)**
> feat: Add a blocklyCollapsed CSS class to collapsed blocks' root SVG (#8264)

- core/renderers/common/path_object.ts
Feature Request https://github.com/google/blockly/issues/8261
Add a blocklyBlock CSS class to the block's root SVG
> feat: Add a blocklyBlock CSS class to the block's root SVG

- blocks/procedures.ts
- blocks/text.ts
- core/block.ts
- core/block_svg.ts
* Improve JSDoc and other comment content + formatting.
* Remove one unneeded `const` declaration.
Cleanup in preparation for work on #8225.
Hopefully passes `npm test`.
Slightly improved.
> docs(blocks): `block.ts` and `blocks/*` JSDoc / formatting / etc. cleanup

- core/blockly.ts
- core/clipboard.ts
- core/dropdowndiv.ts
Fixes #8621
This PR exports a variety of types which developers using Blockly may need in order to extend and customize its behavior. These are a combination of types that were needed when converting scratch-blocks to Typescript (https://github.com/gonfunko/scratch-blocks/pull/224) and those reported in #8621.
> fix: improve typings and export additional types

- .github/workflows/assign_reviewers.yml
- .github/workflows/conventional-label.yml
This PR hopefully resolves the "Resource not accessible by integration" GitHub action failures.
> chore: Update permissions on GitHub actions.

- core/keyboard_nav/ast_node.ts
Fixes https://github.com/google/blockly-keyboard-experimentation/issues/269
This PR updates ASTNode to not return invisible inputs for visitation by the cursor.
> fix: Don't visit invisible inputs with the cursor.

- package-lock.json
- package.json
Version bump for beta release.
> release: update version number to 12.0.0-beta.7
