gulpfile.js
package.json
scripts/gulpfiles/build_tasks.js
scripts/gulpfiles/config.js
tsconfig.json

Part of https://github.com/google/blockly/issues/5892
- Adds a `tsconfig.json` telling the typescript compiler a few critical things: where the input code is, where the output code goes, and that it should read existing js files. 
- Adds a gulp task that runs the typescript compiler
- Adds a flag, `compileTs`, that controls where the build tasks look for source files. By default build uses the files in `core`. When `compileTs` is set, it uses the files in `build/ts/core`.
- Adds a script in `package.json` that runs the ts compiler and then runs build with the appropriate flag set.
Note that the `compileTs` flag is a hack designed to let me set up compilation without properly passing parameters through the build tasks. 
The default behaviour is currently to just run the closure compiler on …

chore(build): add a script to run the ts compiler and send the new files to closure compiler

---

core/block.js
core/events/events_block_create.js
core/events/events_block_delete.js
tests/mocha/event_test.js

Same as PR #5640, except for the addition of a parameter in the JSON to turn this on or off.  While one would normally want animations/sounds on (e.g. undo/redo stack) sometimes they'd be annoying (e.g. events from realtime collaborators).

feat: Delete events should animate when played.

---

core/contextmenu_registry.js
core/registry.js
core/shortcut_registry.js
tests/mocha/contextmenu_items_test.js
tests/mocha/shortcut_registry_test.js

Part of https://github.com/google/blockly/issues/5860
- Change the shortcut registry and context menu registry to have internal `registry` variables that are exported under appropriate names.
- Add `reset` functions to the shortcut registry and context menu registry.
- Update tests as needed.
- Change the `Type` object in `registry.js` to an es6 class.
Clearing the shortcut registry or context menu registry in tests was done by calling the constructor. 
Now clearing those registries is done by calling `reset`.
Movement toward Typescript.
Typescript warns that `keyMap_` and `registry_` and so on can be undefined, because I'm setting them in the `reset` function instead of directly in the constructor. Typescript has the [definite assignment assertion …

refactor: convert registry files to es6 classes

---

closure/goog/base.js
closure/goog/goog.js
tests/deps.js
tests/playground.html
tests/playgrounds/blockly.mjs
tests/playgrounds/prepare.js

Part of #5904.
Change how `tests/playground.html` loads Blockly.
* `playground.html` would use a `<script>` tag to load `tests/playgrounds/load_all.js`
* which in turn would (in uncompiled mode) use a `<script>` tag to load `blockly_uncompressed.js` from the project root
* which in turn used further `<script>` tags to load `base.js` and `deps.js` and then finally do a `goog.require('Blockly')` call to get the debug module loader to load `core/*`.
* After this, `load_all.js` would use further `<script>` tags to load `msg/messages.js`, `tests/themes/test_themes.js` and `@blockly/block-test`.
* Finally, a `<body onload="...">` would call the `start` function in `playground.html`.
* `playground.html` will use a `<script>` tag to load `tests/playgrounds/prepare.js`
* which in turn will (in …

refactor(tests): Use `goog.bootstrap` to allow loading ES modules in playground

---

.eslintignore
blockly_uncompressed.js
core/utils/global.js
gulpfile.js

Rather than ignoring `blockly_uncompressed.js`, `gulpfile.js` and `core/utils/global.js` entirely, add suitable `eslint-disable` directives to those files so that they lint cleanly (and migrate `gulpfile.js` to use `const` instead of `var`).
Lints cleanly.
Lints more stuff cleanly.
Catch other (future) lint in these files.
`npm run lint` completes successfully.

refactor: Be more selective in eslint ignorance

---

package.json
tests/compile/main.js

* Pass the `--debug` flag when running the `buildAdvancedCompilationTest` gulp task.
* Migrate `test/compile/main.js` to `goog.module`.
* Use more selective `goog.requires`.
* `@suppress` "extra" requires needed for side effects.
The compiled output (`tests/compile/main_compressed.js`) was 402441 bytes.
The compiled output (`tests/compile/main_compressed.js`) is 373888 bytes (a 7% reduction).
* Make advanced compilation test actually test partial compilation.
* Make sure that it picks up any errors that might only be generated when doing `ADVANCED_OPTIMIZATIONS`.
* `npm test` completes successfully.

fix(tests): Enable `--debug` for `test:compile:advanced`; fix some errors

---

package.json
tests/compile/main.js

Reverts google/blockly#5959
The above PR caused the advanced compilation CI to break. For some reason the CI on #5959 didn't actually test with the `--debug` flag enabled.

revert: "fix(tests): Enable `--debug` for `test:compile:advanced`; fix some errors"

---

blocks/procedures.js

https://github.com/google/blockly/issues/5972
The field _callType__ was defined as 'procedures_callnoreturn' in PROCEDURE_DEF_COMMON.
Now it is defined separately in procedures_defnoreturn and in procedures_defreturn so each one defines it's own value for it.
As shown in https://github.com/google/blockly/issues/5972, when selecting the option to create a caller of a returning procedure, the result was a procedures_callnoreturn block.
Now a procedures_callreturn is created.
To fix the problem.
Tested on:
Desktop Chrome v98.0.4758.102 (Windows 11)

fix(blocks): correct the `callType_` of `procedures_defreturn`

---

tests/mocha/index.html
tests/mocha/run_mocha_tests_in_browser.js

#5622 
Reports mocha failures in console output when running `npm run test` and `node tests/mocha/run_mocha_tests_in_browser.js` (but not when running `npm run test:mocha:interactive`)
Also removed the extra number that was printed before the line saying `x tests failed`
Only logged the number of tests that failed.
0 failures shows:
```
============Blockly Mocha Test Summary=================
0 tests failed
============Blockly Mocha Test Summary=================
```
1+ failures shows:
```
============Blockly Mocha Test Failures================
"Abstract Fields Serialization Save JSO No implementations" failed: expected 'test value' to not equal 'test value'
"Tooltip Custom Tooltip Custom function is called" failed: Expected custom tooltip function to have been called: expected true to be …
```

feat: add mocha failure messages to console output

---

core/dropdowndiv.js
core/inject.js
core/menu.js
core/menuitem.js
core/toolbox/category.js
core/toolbox/collapsible_category.js
core/toolbox/separator.js
core/toolbox/toolbox.js
core/tooltip.js
core/utils/dom.js
core/widgetdiv.js

Part of #5857
- Add casts when calling `document.createElement('div')`.
- Update types for properties, return types, and parameters that can be more specific as a result.
These were annotated as `Element`. The typescript compiler threw errors, saying that `style` and similar properties do not exist on `Element`.
Code works the same but tsc has fewer errors.
Improve typing/fix errors.
`tsc` doesn't actually care about the casts when the divs are created and used immediately, because it's [clever](https://www.typescriptlang.org/docs/handbook/dom-manipulation.html#documentcreateelement). But `tsc` cares about having the correct types when the divs are saved or passed around, and the closure compiler needs the casts to agree that it's safe.

chore: makes types of divs more specific

---

tests/migration/renamings-schema.json

Use [the official semantic versioning regexp from semver.org](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) rather than [the shorter but sloppier one
we had previously found](https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39).
Avoid any possible problems that could be caused by invalid version numbers in `renamings.json5` when comparing version numbers in the process of running the renamings script.
* Passes `npm test`.

feat(tests): Use official semver.org RegExp

---

core/workspace_svg.js

fixes #5930 and possibly #5404
Change the truthy tests of width and height in WorkspaceSvg.setCachedParentSvgSize to actual comparisons with null/undefined so that zero value can be saved into the cache
If the div containing the Blockly workspace is hidden and Blockly.svgResize is called you end up in a state where the svg is forced to zero size and it will never some back.
The cause is that during the hidden svgResize WorkspaceSvg.setCachedParentSvgSize fails to record the zero size as noted here https://github.com/google/blockly/issues/5404#issuecomment-907989018, but the SVG is still made 0x0. Later when the div is un-hidden svgResize doesn't see that the size is growing since the cached value is bad, so the SVG is not set back to a visible size.
The same as what seemed to be noticed …

fix: Change the truthy tests of width and height in WorkspaceSvg.setCachedParentSvgSize

---

core/blockly.js
core/events/utils.js
core/field.js
core/gesture.js
core/inject.js
core/mutator.js
core/procedures.js
core/serialization/workspaces.js
core/theme_manager.js
core/toolbox/toolbox.js
core/variables.js
core/variables_dynamic.js
core/workspace.js
core/workspace_svg.js
core/xml.js
tests/deps.js

More work on #5860 
Converts the workspace "class" to an ES6 class.
Should be no behavior changes 🤞 
The long winding road to typescript
All unit tests pass
N/A
N/A

fix: convert the Workspace class to an ES6 class

---

scripts/migration/renamings.json5

Data [exists on browserEvents](https://github.com/google/blockly/blob/c9be8d984d6cc459917f2a777e03ba858f2e623d/core/browser_events.js#L31), not eventHandling.

fix: incorrect module for event data in renamings database

---

scripts/gulpfiles/build_tasks.js

Part of #5904.
Makes various changes to the way UMD chunk wrappers are generated.  Specifically:
* Corrects erroneous assumption that `closure-calculate-chunks` outputs chunks in the same order as the `--entrypoint`s were specified on the command line.
* Introduces the configuration constant `NAMESPACE_PROPERTY` to control where the namespace object is saved on the exports object.
* Save the namespace object on every chunk exports object.
* Corrects erroneous assumption that chunks could have multiple dependencies; instead, they have a single parent chunk.
* Miscellaneous other updates to chunk wrapper generation.
The namespace object is saved only on the `.internal_` property of the first (`blockly`) chunk's exports object.
The namespace object is saved on the `.__namespace__` property …

refactor(build): Prepare UMD wrapper generation for transition to ES modules

---

tests/playground.html

N/A
Makes it so that:
1) Test blocks are accessible.
2) The text area properly triggers updates.
3) The show and hide buttons work.
None of those things worked.
Now they work!
Need to be able to use the playground for testing.
Tested on:
N/A
Abby figured out how to get the test blocks to import! They need to be added as a plain script instead of a module script (I think b/c we're using the dist version). I didn't think that would work b/c Blockly wouldn't be defined. But it turns out prepare.js defines Blockly in the global scope. So as long as we load the test blocks after we load prepare.js everything is happy :D

fix: playground test blocks, text area listeners, and show/hide buttons

---

blocks/procedures.js
tests/mocha/procedures_test.js
tests/mocha/test_helpers/procedures.js

#5971 
Makes it so that when call blocks are created, if their name matches an existing procedure def, but they do not have the args to match that procedure def, a new def is created with a new name, and the callers name is changed to match.
A new procedure would be created, but the caller would not be renamed to match it, so the program would end up in a broken state.
The caller is renamed to match the generated definition, so the program is legal.
Letting users accidentally make their programs invalid is bad.
Tested on:
N/A
Love it when my past self writes tests for my future self :D

fix: always rename caller to legal name

---

tests/playgrounds/advanced_playground.html
tests/playgrounds/prepare.js
tests/themes/test_themes.js

#6019 and the fact that the playground was not working when hosted.
- Changes the prepare.js script to use absolute path instead of relative path. This means that it will work with both the playground and the advanced playground. This makes it possible to fix #6019.
- Moving to the absolute path also fixed a bug that made it impossible to load the scripts from hosted sites. (We were using ../.. instead of just ../)
- Small fix for the test_theme that was not working.
- Playground and advanced playground did not work when hosted.
- Advanced playground and playground now both work when hosted on appspot.
- Regular playground works when hosted on google.github.io. We would still need to upload the dev-tools/index.js file to the gh-pages branch for this to work on `google.github.io`.
- If we …

fix: advanced playground and playground 

---

tests/playground.html
tests/playgrounds/advanced_playground.html
tests/playgrounds/screenshot.js

#6023 
This PR fixes the Download Screenshot command in the workspace contextual menu in the playgrounds.
The contextual menu item had no visible effect and logged an error to the console.
A screenshot of the workspace is downloaded.

fix: Fix downloading screenshots on the playground.

---

core/contextmenu.js

Fixes a bug that prevented workspace comments from being added via the contextual menu by destructuring WorkspaceCommentSvg when loading its module.

fix: Fix bug where workspace comments could not be created.

---

blocks/loops.js

Fixes an error in the instructions about how to access `loopTypes` in the usual case (`import ... from 'blockly/blocks';`).
Instructions were incorrect and misleading.
N/A.  But passes `npm test`.

doc: Fix comment for loopTypes

---

core/serialization/blocks.js
core/utils/toolbox.js

In the JSON serializer there are two [typedefs](https://github.com/google/blockly/blame/master/core/serialization/blocks.js#L61) with a property called `extra-state`. This breaks the hell out of the typescript definitions because the compiler can't parse the jsdoc. e.g. the early commits here https://github.com/google/blockly/pull/6051 (and also last quarter had to be hand-fixed)
Adds quotations around the property. Properties with dashes can only be accessed with bracket notation and quotes, so adding the quotes helps the TypeScript parser.
I think this property probably should have been called extraState from the beginning. Is it worth changing now? It's probably somewhat annoying for an external developer because they have to use bracket notation. If we were to change it then asap …

fix: update extraState property in serializer typedefs

---

blocks/lists.js
blocks/logic.js
blocks/text.js
core/mutator.js

Closes #6033 
Makes it so that saveConnections skips insertion markers.
Child blocks would sometimes get disconnected when they should not.
No more badly disconnected child blocks.
Bugs be bad.
1. Created a 6 input block as in #6033 
2. Moved the bottom input to the top.
3. Moved the bottom input to the top again.
4. Disconnected the bottom input.
5. Attached the disconnected child to the open input. -> Tests that saved connections are updated when the main workspace is modified.
6. Reattached the disconnected bottom input at the top.
7. Observed how the top input was now empty.
8. Observed how at no point where children erroneously disconnected.
I would include a screen recording, but I can't figure out how to do that with my current linux setup.
Tested on:
We should …

fix: mutators disconnecting from children instead of moving them

---

appengine/redirect.html

Part of https://github.com/google/blockly/issues/1586
Add redirects to the appengine folder so that some of the demos link to the blockly-samples github pages site instead of appengine.
Links went to appengine.
Links go to github pages.
These demos are duplicated on blockly-samples in the examples folder, and hosted on github pages. We don't need to have them in multiple locations. None of these demos save data, so they don't need to be on appengine.
Did not test yet, to avoid overriding the current site during testing. It's fine for this to land in Q2.
Need to check whether the icons for the demos still work on the index page.
None.
Future work:
- Delete demo folders for the affected demos.
- Decide what to do about the demos that I didn't redirect.
- Move the code demo to blockly games. …

chore(demos): redirect some demos to gh-pages

---

core/workspace_svg.js

feat: Add margin around zoomToFit

---

.github/workflows/build.yml
.github/workflows/check_clang_format.yml
.github/workflows/update_metadata.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

.github/dependabot.yml

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.
Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot
GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

chore: Included githubactions for dependabot

---

core/browser_events.js
core/bubble.js

Fixes a type error in bubble code.
Fixes a runtime error in `isTargetInput`
In bubble code, cast child nodes appropriately.
In `isTargetInput`, separate the check for a textarea from the check for other input types.
Clicking on comments didn't work; backspace when editing a new comment deleted the comment.
Input on textareas works again; two type errors resolved.
Fix type problems, and I found the textarea issue while testing.
Test case 1: textarea input
- Add a block to the workspace
- Right-click and add a comment
- Type some text, then hit backspace
**Comment should not disappear**
Test case 2: textarea input
- Add a block to the workspace
- Right-click and add a comment
- Click away
- Click on the comment
**Comment should be editable**
Test case 3: non-editable bubbles
- Load the …

fix: type error in uneditable bubbles

---

core/block_svg.js
core/field.js
core/flyout_base.js
core/tooltip.js

Part of #6097
When modifying a tooltip attribute, the object it is being attached to is cast to ? to silence Closure's complaints.
Closure would produce an error in strict mode.
Closure is silent.
We need to get the codebase compiling cleanly under Closure to migrate to Typescript.
Verified that the test suite passes.

fix: Silence Closure errors when modifying tooltips.

---

core/gesture.js
core/touch.js
core/touch_gesture.js

Add specificity to types in touch code.
I added more specific types where possible (e.g. with `instanceof`) but left fallbacks to the old code with casts to `?`, to avoid accidentally changing behaviour in the edge cases.
Fix or mask type errors.
Tested on desktop chrome and through device emulation in chrome dev tools, acting as a pixel 5.
https://github.com/google/blockly/issues/6097 tracks future cleanup.
caniuse.com says pointer events are supported in all browsers we support, so we can refactor and simplify this code--but we'll need to do a lot of testing to verify it.

fix: improve types in touch code

---

core/block.js
core/events/utils.js

Part of migration to typescript.
Add annotations for compose and decompose functions on block.
Change a cast from `*` to `?`.
Fixes several type errors blocking typescript conversion.

fix: add compose and decompose to block

---

core/delete_area.js
core/drag_target.js
core/interfaces/i_block_dragger.js
core/interfaces/i_component.js

Part of https://github.com/google/blockly/issues/5857
Changes the `id` property on `i_component` to be on the prototype, and then updates things that implement `IComponent` accordingly.
The IDs were already there--created in the constructors for things that implement `IComponent`. `id` was not supposed to be at the top level, since it's not shared between instances of a class.
Also added `dispose` to `IBlockDragger`.
Fix type errors to convert to typescript

fix: component id should be on the prototype

---

core/block_animations.js
core/block_drag_surface.js
core/dropdowndiv.js
core/workspace_drag_surface_svg.js

Work on #6124
* Removes the forced style calculation and layout by removing the call to `getBBox`
* Uses `Math.round` instead of `.toFixed(0)`
Average time to run onKeyDown decreased from ~27ms to ~15ms. Doesn't quite meet the goal of 10ms, but does almost double speeds.
[deleting-2.txt](https://github.com/google/blockly/files/8586810/deleting-2.txt)
Performance is good!
Deletion:
1) Drag a block onto the workspace.
2) Delete it.
3) Observe how the animation  plays correctly.
4) Repeat with:
* Workspace zoomed in
* Workspace zoomed out
* Page zoomed in
* Page zoomed out
* Combinations of the above four.
Block dragging:
1) Drag a block onto the workspace.
2) Drag the block around the workspace.
3) Observe how the block is not fuzzy.
Workspace dragging:
1) Drag a block onto the workspace. …

fix: Increases the  speed of deleting blocks

---

core/inject.js

The changes include a small improvement that reuses the imported module `bumpObjects` instead of loading it again with `goog.module.get`.
`bumpObjects` is imported here:
https://github.com/google/blockly/blob/63ca83b545d9f00ed8a7e0be6ff8c54dc909e1a7/core/inject.js#L24
then used here:
https://github.com/google/blockly/blob/63ca83b545d9f00ed8a7e0be6ff8c54dc909e1a7/core/inject.js#L190-L191
and loaded again here:
https://github.com/google/blockly/blob/63ca83b545d9f00ed8a7e0be6ff8c54dc909e1a7/core/inject.js#L222-L223
`goog.module.get` is unnecessary.
No tests have been modified.
The API has not changed.

fix: reuse the 'bumpObjects' module in inject.js

---

core/mutator.js

Work on #6131 
Delays expensive operations using setTimeout so that:
1) We aren't calling `compose()` multiple times for things that won't be rendered.
2) We can render the mutated block without waiting for the mutator bubble to resize (which is expensive). This makes the UI feel more responsive.
~188ms for `updateWorkspace` to run, which was required to complete before the first frame could be drawn.
~35ms for `updateWorkspace` to run, after which the mutated block is drawn
Then ~20ms for `resizeBubble_` to run, after which the newly positioned/sized bubble is drawn
[mutating-2.txt](https://github.com/google/blockly/files/8642273/mutating-2.txt)
Make the UI feel more responsive.
I button mashed mutating the block + undo and redo. This didn't seem to cause any problems because the events …

fix: add timeouts to delay expensive mutation operations

---

generators/javascript/math.js
generators/javascript/text.js
generators/python/colour.js

Warning message from closure-compiler (and/or closure-make-deps): `Unnecessary escape: "\'" is equivalent to just "'"`.
Remove unnecessary escapes.
Prevent warning message from our tooling by fixing the problem.

chore(generators): Remove unnecessary escapes

---

core/xml.js

Type error in `appendDomToWorkspace` when attempting to call `.getBlocksBoundingBox` on a `Workspace` object.
Have `appendDomToWorkspace` take a `WorkspaceSvg` instead of a `Workspace`.
Turns out if one runs `tsc` on `.js` files in `core/`, the output will be basically identical to the input except for whitespace changes, yet this is sufficient to cause Closure Compiler to detect type errors that were not detected previously.
BREAKING CHANGE: have appendDomToWorkspace take a WorkspaceSvg instead
of a Workspace as its second parameter.
This function rearranges blocks on the workspace and is only relevant to rendered workspaces.  If you use this function in headless mode, switch to using `domToWorkspace` instead.

fix!(xml): Make appendDomToWorkspace take only WorkspaceSvg

---

blocks/lists.js
tests/mocha/blocks/lists_test.js

https://github.com/google/blockly/issues/6176
Don't serialize xml mutations to extra state in json serialization for
- lists_setIndex
- lists_getSubList
- lists_split
xml mutations were serialized in json extra state and deserialized
xml mutations no longer serialized and are ignored on deserialization
- not needed in JSON serialization
- better (de-)serialization performance
Added basic roundtrip (de)serialization tests, including with previous extra state

fix: json hooks for lists blocks not needing extra state

---

scripts/gulpfiles/package_tasks.js
scripts/i18n/create_messages.py
scripts/package/templates/umd-msg.template

Fixes https://github.com/google/blockly/issues/6123, fixes https://github.com/google/blockly-samples/issues/1066 and fixes https://github.com/google/blockly-samples/issues/1065
Same as #6060, but hopefully this also works for requiring multiple CJS modules.
See https://github.com/google/blockly/issues/6123#issuecomment-1144197138
Also changed the generated, but unwrapped, msg.js files to write to a new `messages` object, rather than `Blockly.Msg` to be clearer about what we're doing, and hopefully prevent errors in the future.
Message loading from script tags does not work.
Message loading from script tags works.
See https://github.com/google/blockly/issues/6123#issuecomment-1144197138
* Playground
* Playground after changing `prepare.js` to pull the `dist/msg/es.js` file instead of …

fix: loading messages from script tags.

---

tests/generators/run_generators_in_browser.js

Turns out `process.exit()` was sometimes getting called before the (async) `fs.writeFile` had finished writing the last of the generator output files.  This was causing occasional failures where the last (or last several) generator tests would fail because they ended up writing 0 byte files.
Use `fs.writeFileSync` instead of `fs.writeFile`
Generator tests could fail due to a race condition.
Generator tests no longer fail because of this particular race condition.
Changes made in one of my TS-related branches were causing this failure to happen almost every time.

fix(tests): Fix race condition causing flakiness in PHP generator test

---

scripts/gulpfiles/package_tasks.js

Hopefully fixes problems with message dependencies we ran into in samples.
Removes the vestigially Blockly dependency from the message wrappers.
The Blockly module could not be resolved.
No need to resolve any modules hopefully.
Getting the messages to actually work.
I tested manually removing the dependencies in the node_modules of some plugins in samples, and that seemed to fix things.
I also tried linking to `field-bitmap` and running `npm run predeploy` before and after this change, and the changes in this PR seemed to fix the problem.

fix: remove vestigial dependency

---

core/theme.js
tests/mocha/theme_test.js

#6186
Add a line in defineTheme to convert its name to lower case.
`Theme.name` did not match registered name, when it included upper case letters.
Now it does :tada:

fix: Theme.name does not match registered name (#6186)

---

gulpfile.js
package.json
scripts/gulpfiles/build_tasks.js

Have `npm run prepare` (which is done automatically by `npm install`) do nothing when running in CI.
We don't need to do any building, because `npm test` will build everything needed in the workflows in which it is run, and we don't want to build anything in other workflows because a `tsc` error would prevent those workflows from completing.
`npm run prepare` (and `npm install`) fail if there are `tsc` errors, causing the clang-formatter and lint workflows to abort unnecessarily.
Only the workflows that run `npm test` should fail if there are `tsc` errors.
More useful CI feedback.
Have a look at the CI runs for this PR!

fix(build): Have `npm run prepare` do nothing when running in CI

---

scripts/gulpfiles/build_tasks.js

Suppresses spurious error messages from `closure-make-deps`.
A little bit of an ugly hack, but it works: pipe `stderr` through `grep -v` to suppress error output starting with "WARNING in".
`npm run build:deps` generates ~7.7k lines of useless and irrelevant warnings.
`npm run build:deps` does not generate any warnings.
The code generated by `tsc` doesn't have Closure type annotations and does have unused variables and other issues that cause the parser in `closure-make-deps` to generate warnings.  Unfortunately that command does not have any (documented) way to suppress these warnings.

chore(build): Suppress spurious warnings from closure-make-deps

---

core/block.ts
core/component_manager.ts
core/interfaces/i_copyable.ts
core/keyboard_nav/ast_node.ts
core/metrics_manager.ts
core/options.ts
core/renderers/common/constants.ts
core/renderers/zelos/constants.ts
core/shortcut_registry.ts
core/theme.ts
core/theme_manager.ts
core/toolbox/category.ts
core/toolbox/collapsible_category.ts
core/toolbox/separator.ts

N/A
Follows the same strategy as #6246 
Typedefs that were on classes were transformed into interfaces, but they were not properly appended to the classes they used to exist on. This fixes that, and also exports the type to match the other places where the auto-migration script changed things.
Should be no change in behavior (besides whether these types exist or not).
Should be no change in behavior (besides whether these types exist or not).
Backwards compatibility.
No manual testing necessary.
N/A
I didn't include the `export const E = C.E;` line, because I don't believe we actually want these to be declared (at the module level) in the exported JavaScript.

fix: properly export interfaces that were typedefs

---

core/block_dragger.ts
core/connection.ts
core/flyout_metrics_manager.ts
core/gesture.ts
core/metrics_manager.ts
core/renderers/common/info.ts
core/renderers/common/marker_svg.ts
core/renderers/geras/info.ts
core/renderers/geras/measurables/inline_input.ts
core/renderers/geras/measurables/statement_input.ts
core/renderers/measurables/base.ts
core/renderers/measurables/connection.ts
core/renderers/measurables/external_value_input.ts
core/renderers/measurables/hat.ts
core/renderers/measurables/in_row_spacer.ts
core/renderers/measurables/inline_input.ts
core/renderers/measurables/jagged_edge.ts
core/renderers/measurables/output_connection.ts
core/renderers/measurables/round_corner.ts
core/renderers/measurables/row.ts
core/renderers/measurables/square_corner.ts
core/renderers/measurables/statement_input.ts
core/renderers/zelos/info.ts
core/toolbox/category.ts
core/toolbox/collapsible_category.ts
core/toolbox/toolbox_item.ts

N/A
The automatic migration script renamed some properties when transforming them into parameter properties. This is fine for private properties, but protected properties are part of our public API, and constitute a breaking change when they are renamed.
Properties were renamed, creating a breaking change.
Property renames are reverted.
Lessen the number of accidental breaking changes we're committing.
No manual testing needed.
N/A
Also going to do a sweep for public properties that might have gotten renamed.

fix: renamed protected parameter properties

---

scripts/gulpfiles/build_tasks.js

For some reason on Github CI servers `execSync` uses `/bin/sh`, which is (on Ubuntu) `dash`, which does not understand the `pipefail` option, rather than `bash`.
So remove the `grep` pipe on `stderr` and just discard all error output.
This is not ideal as errors in test deps will go unreported AND not even cause test failure, but it's not clear that it's worth investing more time to fix this at the moment.

fix(build): Don't depend on execSync running bash

---

core/options.js

#6263 
Add a trailing slash to `media` option, if not present.
Add deprecated warning to `path` option
I was unsure about the deletion date on the deprecation warning, so I just set it to 1 year from now.

fix: options parser should add trailing slash to 'media' if not present. (#6263)

---

core/block.ts
core/block_svg.ts
core/registry.ts
core/toolbox/toolbox.ts

N/A
* Fixes extensions
* Removes a breaking change affecting toolbox subclasses
* Extensions would throw an error for all mutators because it detected that `compose`/`decompose` had a value besides `undefined` (ie `null`)
* Toolbox subclasses would not build because `workspace_` had been renamed to `workspace`
* Extensions work
* Toolbox subclasses work
Fixing regressions.
N/A
N/A
N/A

fix: bugs revealed by getting the built output working

---

core/variables.ts

- You didn't ask if they passed!
Generator test failures
It appears that a function call got modified incorrectly (possibly in an effort to fix a typing issue).  This fix trivially reverts
the line in question to match the original JS version from `develop`.

fix(variables): Revert inadvertent change to `allDeveloperVariables`

---

core/block.ts
core/block_animations.ts
core/block_dragger.ts
core/block_svg.ts
core/comment.ts
core/connection.ts
core/contextmenu_items.ts
core/dropdowndiv.ts
core/events/events_block_base.ts
core/events/events_block_drag.ts
core/events/events_bubble_open.ts
core/events/events_click.ts
core/events/events_marker_move.ts
core/events/events_ui.ts
core/field.ts
core/field_variable.ts
core/gesture.ts
core/icon.ts
core/input.ts
core/insertion_marker_manager.ts
core/keyboard_nav/ast_node.ts
core/mutator.ts
core/procedures.ts
core/rendered_connection.ts
core/serialization/blocks.ts
core/shortcut_items.ts
core/xml.ts

Part of #5857
The workspace property of Block/BlockSvg is non-nullable.
The workspace property was nullable, even though it was de facto never null.
The workspace is no longer nullable and doesn't need a bunch of ! and ? when referring to it.
Ensured tests still pass and manually tested.

fix: Made workspace non-nullable.

---

core/block_drag_surface.ts

N/A
Remove AnyDuringMigration from block drag surface.
N/A
N/A
N/A
Calls to `BlockDragSurface().createDom()` should be removed because the dom is now automatically created by the constructor, and `createDom()` is no-op.

refactor: remove AnyDuringMigration from the block drag surface

---

core/flyout_base.ts
core/mutator.ts
core/workspace.ts
tests/mocha/workspace_svg_test.js

N/A
Make isMutator public.
There was no way for external developers to tell if a workspace was a mutator workspace.
There is a way for external developers to tell if a workspace is a mutator workspace.
Fixing https://github.com/google/blockly-samples/issues/1169, and also just general usefulness
N/A
N/A
N/A

feat: make isMutator public

---

scripts/gulpfiles/package_tasks.js
typings/core.d.ts
typings/index.d.ts

Messed up on one of the final commits to https://github.com/google/blockly/pull/6257 where I changed it to use the `config.js` values instead of the `tsconfig.json` values, so the type definitions weren't actually getting included. This fixes that.
Tested against the `blockly-typescript-libcheck` repo and it works.

fix: packaging .d.ts files

---

package.json
tests/run_all_tests.sh

Removes unused code
Removes a commented-out run of typings.
No change
No change
We disabled this during the high-error portion of the rewrite, and now it's redundant because tsc checks types during the normal build.
Normal build.
Typescript is cool!

chore(tests): remove unused run of typings

---

scripts/gulpfiles/build_tasks.js

Fixes #6328 
Set the closure compiler to compile to ES2015 instead of ES5.
`blockly_compressed.js` could be used directly in ES5 environments such as Internet Explorer and Firefox < 43.
`blockly_compressed.js` does not work directly in ES5 environments. It can still be transpiled further if needed.
Part of #6325 
Rebuild and started the server, and confirmed that I can open and use the playground.
Any remaining documentation that says that we support ES5 will need to change by the next release.
The results of `check_metadata.sh` are:
```
Size of build/blockly_compressed.js at 862067 compared to previous 1040413.
Size of build/blocks_compressed.js at 102485 compared to previous 102176.
Size of build/blockly_compressed.js.gz at 172738 compared to previous 185766.
Size of …
```

chore(build)!: compile to ES2015 instead of ES5

---

core/block_svg.ts
core/component_manager.ts
core/contextmenu_registry.ts
core/marker_manager.ts
core/names.ts
core/renderers/zelos/path_object.ts
core/shortcut_registry.ts
core/theme_manager.ts
core/touch_gesture.ts
core/variable_map.ts
core/variables.ts
core/workspace.ts
core/workspace_audio.ts
tests/mocha/shortcut_registry_test.js
tests/mocha/test_helpers/workspace.js
tests/mocha/variable_map_test.js
tests/mocha/workspace_comment_test.js

Part of #5857
This PR uses JS `Map` and `Set` objects in places where plain objects were being used due to the absence of those data structures in older versions of Javascript. Only variables that were private have been converted.
General codehealth and improved typing accuracy.
Verified tests pass and manually tried the playground.

refactor: Use maps and sets instead of plain objects.

---

scripts/gulpfiles/build_tasks.js
tsconfig.json

Part of #5857.
* Enable `sourceMap` in `tsconfig.json`.  This alone is suffiicient to get functional,  per-`.ts`-file sourcemaps in `build/src/**` that work in uncompiled mode (i.e. in the playground / tests).  Moreover, no further changes are required for these to be ingested by gulp + Closure Compiler; the resulting sourcemaps—`build/*_compressed.js.map`—now correctly point at files in core/, blocks/, etc.  This works when packaged and also when doing local testing in compiled mode of the checked-in build products (i.e., after they are copied to the repository root by `checkinBuilt`).
* In order to get sourcemaps to work for local testing in compiled mode of the build products directly from `build/`, modify `buildCompiled` so that it creates symlinks in `build/` to `core/`, `blocks/` …

fix(build): Fix sourcemaps

---

core/comment.ts
core/contextmenu.ts
core/contextmenu_items.ts
core/field.ts
core/grid.ts
core/renderers/common/constants.ts
core/touch.ts
core/utils/dom.ts
core/utils/svg_math.ts
core/utils/toolbox.ts
core/utils/useragent.ts
tests/mocha/contextmenu_items_test.js

Part of https://github.com/google/blockly/issues/6325
- Remove uses of `userAgent.IE`
- Remove export of `userAgent.IE`
Breaking change because of the removed export.
Assorted checks for IE in our code.
No special behaviour for IE--but note that there are still special cases for Edge.
No more IE support.
Built and ran tests.
`isGecko` still uses whether IE has been found inside `useragent.js`
`isGecko = has('Gecko') && !isWebKit && !isIe && !isEdge;`
We should consider removing all exports from `useragent.js` that we aren't already using. User agent sniffing is highly not-recommended, and we can get rid of excess exports. It's technically a breaking change, but I think we want to do it in this release.

fix!: remove checks for IE and EdgeHTML in core

---

core/utils/useragent.ts

Followup from https://github.com/google/blockly/pull/6336
Remove exported useragent booleans for chrome, webkit, ipod, and tablet.
No change.
No change.
We weren't using these checks, and it's fragile for us to be maintaining and exporting them if we're not using them.
Standard tests. We'll want to test on iOS for the release, but it should only impact sound loading anyway.
Developers who were using these values should read the MDN page on [browser detection using the user agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent). If there is no way to detect what you're looking for without checking the user agent, follow the instructions on that page to find the most targeted possible solution.

fix!: remove unused or obsolete useragent checks

---

scripts/gulpfiles/build_tasks.js

Modify `buildDeps` gulp target (in `build_tasks.js`) to only suppress expected warnings from `closure-make-deps`.
All `stderr` output from `closure-make-deps` redirected to `/dev/null`
`stderr` output from `closure-make-deps` read by the gulp task and logged to console after filtering known-
While preparing PR #6337, @BeksOmega discovered that our block tests (in `tests/mocha/blocks/`) were not being run.  This was due to invalid `import`s, where several of those files attempted to import from `../../build/…` instead of `../../../build/…`.  I was surprised that this did not provoke more complaints from various parts of our build/test infrastructure, and it occurred to me that `closure-make-deps` may have discovered the problem and reported it but we threw the error in the bit-bucket along …

chore(build): Only suppress expected warnings from closure-make-deps

---

.eslintrc.json
core/block.ts
core/block_svg.ts
core/blockly.ts
core/connection.ts
core/flyout_base.ts
core/rendered_connection.ts
core/scrollbar.ts
core/toolbox/category.ts
core/variable_map.ts
core/workspace_comment_svg.ts

Part of #5857
Fixes or individually disables violations of the no-this-alias lint rule. Where the violation was in the spirit of the rule (shenanigans with `this`) I fixed it by generally converting to arrow functions; in cases where the assignment was intentional (generally recursive traversals starting with `this`), I disabled the warning.
Lint warnings for assigning `this` to a variable were always suppressed.
Lint warnings for assigning `this` to a variable are selectively suppressed but generally enabled.

chore: Fix or individually disable no-this-alias lint rule violations.

---

scripts/gulpfiles/build_tasks.js

"Did you forget to signal async completion?" error from gulp when running the `prepare` task (as invoked by `npm run prepare` or `npm install`).
Add a `done` parameter and pass the provided callback to `buildJavaScriptAndDeps`.  This also allows a simplification of the the don't-run case by simply calling `done()` and then `return`ing.
When not run by a GitHub action, `npm run prepare` and `npm install` generate the aforementioned error.
`prepare` script successfully signals async completion, avoiding error.
PR #6244 made a change to have the `npm run prepare` script (automatically invoked by `npm install` after package installation) not bother running the `buildJavaScriptAndDeps` gulp task when run from a GitHub action (since our build action will do npm test straight afterwards, which …

fix(build): Have prepare task signal async completion

---

.eslintrc.json
core/field_multilineinput.ts
core/field_number.ts
core/flyout_base.ts
core/renderers/common/constants.ts
core/renderers/measurables/base.ts
core/renderers/measurables/input_connection.ts
core/utils/svg_math.ts

Part of #5857
Removes type annotations that can be inferred from the literal value being assigned.

chore: Fix no-inferrable-types lint rule violations.

---

scripts/gulpfiles/build_tasks.js
scripts/gulpfiles/package_tasks.js

`tsc` compile failures for developers whose build pipeline is misconfigured in a way that causes it to ingest `.ts` source files from `node_modules/blockly/core/`—somehow without also ingesting `core/any_aliases.ts`—resulting in compile errors due to `AnyDuringMigration`.  (See e.g. item #2 of #6358.)
Don't package the source `.ts` files; instead, include sources inline in the `.js.map` sourcemaps.
`.ts` files are copied from `core/`, `blocks/` and `generators/` to `dist/`.
Sourcemap (`.js.map`) files contain a two-byte `sourceRoot` property.
`.ts` files are not packaged.
Sourcemap files contain a large `sourcesContent` property (~2MB for `blockly_compressed.js.map), containing all of the original source.
@btw17 points out that it is [generally not advised to package `.ts` sources along …

chore(build): use inline sources in sourcemaps; don't package sources separately

---

core/renderers/common/constants.ts

N/A
Removes a commented out definition for a type.
I think the one I chose to leave is the more correct type definition.

chore: remove alt dynamic shape definition

---

core/comment.ts
core/icon.ts
core/mutator.ts
core/warning.ts

Work on #5857 
Removes instances of AnyDuringMigration and replaces them with better types where applicable.
Also makes some private things actually `private`.
No change in behavior.
No change in bheavior.
Types are fun!
N/A
N/A
I didn't fix the `Pid_` type in mutator because I still don't know how to properly type `setTimeout` return values.

chore: remove instances of AnyDuringMigration in icons code

---

core/dropdowndiv.ts
core/widgetdiv.ts

Work on #5857 
Removes instances of `AnyDuringMigration` from the `DropDownDiv` and the `WidgetDiv`
No change in behavior.
No change in behavior.
Types are fun :D
N/A
N/A
N/A

chore: remove AnyDuringMigration from dropdown and widget divs

---

core/events/events_bubble_open.ts
core/flyout_metrics_manager.ts
core/registry.ts
core/renderers/common/renderer.ts
core/renderers/geras/renderer.ts

Part of #5857
Makes optional arguments to some methods actually optional; before they had an opt_ prefix and were treated as optional, but were actually required arguments from TS' perspective.

refactor: Mark optional parameters as optional.

---

core/grid.ts

General cleanup.
Remove underscores on private variables and methods in `grid.ts` to match google TS style guide.
Remove unused property.
No change.
No change.
Match style guide; delete unused code.
Tested in the playground to make sure the grid still worked.
None

chore: remove underscores from private properties in grid.ts

---

core/variables.ts
tests/generators/unittest.js

Removes checks for getDeveloperVars(), which was deprecated and replaced by getDeveloperVariables() 4 years ago.
getDeveloperVars() method would be called if present.
Only getDeveloperVariables() will be invoked.

refactor!: Removed backwards compatibility for getDeveloperVars().

---

core/utils/style.ts

API cleanup
Deletes two unused functions from `core/utils/style.ts`
`isRightToLeft` and `setElementShown` were exported.
No longer exported.
Unused and not Blockly-specific code.
Automated tests.
None
Suggested workaround: implement as helper functions in your own codebase if you need this functionality.

fix!: remove unused functions in style.ts

---

core/utils/dom.ts
core/utils/style.ts

Part of #6325 
- Remove some IE-specific code related to setting and reading styles.
- Remove use of `getCascadedStyle` and mark it as deprecated.
- Simplify code in `getComputedStyle` by using `window` instead of `document.defaultView`
- MDN documentation on [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#defaultview) says "In many code samples, getComputedStyle is used from the document.defaultView object. In nearly all cases, this is needless, as getComputedStyle exists on the window object as well. It's likely the defaultView pattern was a combination of folks not wanting to write a testing spec for window and making an API that was also usable in Java."
- Use `?.` to tighten up some style checks. There's future work here to sort out the …

fix: remove some IE-specific code in dom and style

---

core/shortcut_registry.ts
core/utils/deprecation.ts
core/utils/object.ts

Part of #6325.
- Removes special casing for IE in `object.values`.
- Marks `object.values` and `object.inherits` as deprecated, with removal dates.
- Switches to using `Object.values` directly in `shortcut_registry.js`.
- Fixes exposed type errors.
- Changes the deprecation warning function to say things will be deleted after a date or a version.
No change.
No change
Remove workaround and deprecate unused code in preparation for removal.
Improve types!
Tested by opening up the playground and trying to register shortcuts with modifiers that do and don't exist:
Functional cases:
```
// Create a serialized key from the primary key and any modifiers.
var ctrlW = Blockly.ShortcutRegistry.registry.createSerializedKey(
Blockly.utils.KeyCodes.W, [Blockly.ShortcutRegistry.modifierKeys.Control]); …
```

fix: deprecate functions in object.ts

---

core/menu.ts

N/A
Fixes the context menu, which was not working if you clicked on the text.
Clicking on the text of a context menu option would not trigger the action.
Clicking on the text does trigger the action.
Fixing bugs is fun :D
Manually tested that clicking context menu options works.
N/A
N/A

fix: context menu not working

---

core/insertion_marker_manager.ts

Work on #5857 
Removes `AnyDuringMigration` from the insertion marker manager.
Should be no change in behavior
Should be no change in behavior.
Types are fun :D
Did a basic manual test of insertion markers, and they seem to work.
N/A
N/A

chore: remove AnyDuringMigration from the insertion marker manager

---

core/block_svg.ts
core/bubble_dragger.ts
core/utils/svg_math.ts
core/workspace_comment_svg.ts
core/workspace_svg.ts

Part of #6325
Stop checking whether `translate3d` is supported--it's fine on all browsers in 2022.
Deprecate `is3dSupported` in preparation for deleting it.
Checked for support using a variety of browser prefixes, because there was not a standard way to check.
Always assume it's supported and act accordingly.
Remove workarounds for old browser behaviour.
Checked in Chrome and Firefox.
I made the change in several pieces so that I could check functionality at an intermediate point.
None
We might be able to make block and workspace drag surfaces always get built, or else decide they don't improve performance and delete them entirely. Either case would be nice since it would let us reduce the number of available code paths. But that's tricky because it requires performance analysis and …

fix: stop using `is3dSupported`

---

core/block.ts
core/field_registry.ts
core/utils/toolbox.ts

resolves #6360
Fairly minor refactoring to bypass some typescript errors appearing on dependent projects with certain tsconfig settings.
N/A. No behavioral changes. 
N/A. No behavioral changes. 
Existing tests should cover my changes:
- run_node_test.js covers `Generator#workspaceToCode`
- toolbox_test.js has "parseToolbox" suite covers `parseToolboxTree`
- block_test.js has "toString" suite to test `Block#tostring`
Ran `npm run test` and all existing tests passed.

fix: TS errors on dependent projects with certain tsconfig settings (#6360)

---

core/gesture.ts
core/rendered_connection.ts
core/touch_gesture.ts

Work on #5857 
Removes `AnyDuringMigration` from the gesture code (mostly, I left it in where I think type guards are the correct solution, or where it deals with touch/mouse events being derpy).
Removes the different booleans tracking if a dragger exists, and instead just checks if the dagger exists.
Should be no change in behavior.
Should be no change in behavior.
Types === good?
Tested dragging things around and clicking things etc. Gestures appear to work, but who really knows.
N/A
N/A

chore: work on refactoring gesture code

---

core/block_svg.ts
core/contextmenu.ts
core/dropdowndiv.ts
core/field.ts
core/field_checkbox.ts
core/field_colour.ts
core/field_dropdown.ts
core/field_label.ts
core/field_multilineinput.ts
core/field_textinput.ts
core/icon.ts
core/inject.ts
core/menu.ts
core/menuitem.ts
core/mutator.ts
core/renderers/common/path_object.ts
core/theme_manager.ts
core/toolbox/category.ts
core/toolbox/collapsible_category.ts
core/toolbox/separator.ts
core/toolbox/toolbox.ts
core/utils/dom.ts
core/widgetdiv.ts
core/workspace_comment_svg.ts
core/workspace_drag_surface_svg.ts
core/workspace_svg.ts

Part of https://github.com/google/blockly/issues/6325
Followup on https://github.com/google/blockly/pull/6411
- Replace calls to `Blockly.utils.dom.removeClass` with `elem.classList.remove`
- Replace calls to `Blockly.utils.dom.hasClass` with `elem.classList.contains`.
No change.
No change.
These functions only existed because Internet Explorer couldn't handle access/modification of the classList for SVG elements.
Built and opened the playground and clicked around a bit.
None
Later work includes deprecating these functions and then deleting them.

fix: remove calls to removeClass and hasClass

---

core/contextmenu.ts
core/field_dropdown.ts
core/menu.ts

Removes a need for `?.`
Return the div from `menu.render` so that it can be used immediately and guaranteed to be non-null in calling code.
No return value, so you had to call `getElement`, which could return null.
Noticed while working on `addClass`.

feat: return element from menu.render

---

core/field_dropdown.ts
tests/mocha/json_test.js

Previously the options data structure passed to the dropdown constructor was sometimes copied (in the case of prefix/suffix trimming), but other times it was merely referenced. This meant if options data was used to create one dropdown, then the options data was modified and a second dropdown was created, the first dropdown's options would mysteriously change as well.
This uncovered a broken test that was only passing because of a side effect of the dropdown option data getting modified.

fix: Deep copy options used by dropdown fields

---

core/rendered_connection.ts
tests/mocha/serializer_test.js
tests/mocha/test_helpers/workspace.js

I noticed some tests were not running while testing another change.
Enable two test suites.
Re-enables tests for serializers and `getById`
None

chore(tests): re-enable some skipped tests

---

blocks/lists.js

It was the only JSON-defined block to still use Msg.

chore(blocks): Convert sort block to use BKY messages.

---

core/events/events_abstract.ts
core/events/events_comment_base.ts
core/events/events_selected.ts
core/events/events_var_base.ts
core/field.ts
core/field_angle.ts
core/field_checkbox.ts
core/field_dropdown.ts
core/field_multilineinput.ts
core/flyout_base.ts
core/interfaces/i_component.ts
core/procedures.ts
core/toolbox/collapsible_category.ts
core/toolbox/toolbox.ts
core/toolbox/toolbox_item.ts
core/utils/dom.ts
core/utils/idgenerator.ts
core/utils/svg_math.ts
core/workspace_comment.ts
core/workspace_svg.ts
core/xml.ts
core/zoom_controls.ts
tests/mocha/utils_test.js
typings/msg/id.d.ts

parseInt guesses the radix if one was not provided.  While this is normally 10, a prefix of '0x' will switch it to hexadecimal -- this is fine.  But more problematic was that a prefix of '0' would switch it to octal.  Thus `parseint('018')` would return `1` since there's a leaning zero, and parsing would stop at the first invalid character (eight).  This caused a lot of subtle errors and as a result adding a radix used to be required.
However, years ago implicit octal detection was removed from parseInt.  Thus we no longer need to worry about it.

chore: Remove radix from parseInt, simplify Blockly.utils.dom methods, use Unicode characters.

---

core/block.ts
core/block_svg.ts
core/connection.ts
core/contextmenu_items.ts
core/field.ts
core/field_variable.ts
core/keyboard_nav/ast_node.ts
tests/mocha/event_test.js
tests/mocha/test_helpers/block_definitions.js

Part of #6358 
Change where we set `block.disposed` to `true`. I audited all of the places where `disposed` is referenced, and I don't *think* this will break anything. But let's be honest, it probably will break something.
If you disposed of a workspace that had an overwritten shadow block in it, the workspace would throw an error. See https://github.com/google/blockly/issues/6358#issuecomment-1244375899
No end-user-facing change in behavior.
No Error!
No end-user-facing change in behavior.
Errors are sad =(
Manually tested that disposing of a workspace with the following blocks in it did not cause an error to be thrown:
```
{
"blocks": {
"languageVersion": 0,
"blocks": [
{
"type": "math_single",
"id": "f#E]:l@J;BJ;N(?;KQ5T",
"x": 138,
"y": 138,
"fields": {
"OP": "ROOT"
},
"inputs": { …
```

fix: disposing of a workspace that has overwritten shadows

---

core/block_svg.ts
core/field_angle.ts
core/field_dropdown.ts
core/field_textinput.ts
core/renderers/common/constants.ts
core/renderers/common/path_object.ts
core/renderers/zelos/path_object.ts
core/theme.ts

Work on #6358 
Makes properties of the theme interfaces optional (since they are mostly optional).
This was tricky, because after the theme gets passed to the renderer, all of the properties should be "filled in". But trying to record this side-effect based change with types was going to be... difficult. So it's easier just to check that the renderer properly initialized the properties.
External developers had to provide properties to themes they didn't want to override.
Should be no end-user-facing change in behavior.
Now you only need to provide the properties you want to override.
Should be no end-user-facing change in behavior.
Better dev experience.
N/A
N/A
N/A

fix: theme types

---

blocks/lists.js
blocks/procedures.js
blocks/text.js
core/comment.ts
core/extensions.ts
core/icon.ts
core/mutator.ts
core/warning.ts

#6420
Passes the block to the Mutator constructor.
Mutators would fail to initialize properly.
Mutators initialize and work as expected.
As part of the migration to TS, the Mutator constructor was changed to require the block it's attached to. Most existing block definitions had not been updated to pass this in. This PR updates those definitions to invoke the new constructor correctly.
Alternatively, I could try to revert the previous change to the Mutator constructor and pass null as the block value to the Icon superclass constructor as it did in v8, which probably requires some other changes to types.

fix: Fix blocks with mutators.

---

core/block_svg.ts
core/contextmenu.ts
core/dropdowndiv.ts
core/field.ts
core/field_checkbox.ts
core/field_colour.ts
core/field_dropdown.ts
core/field_label.ts
core/field_multilineinput.ts
core/field_textinput.ts
core/icon.ts
core/inject.ts
core/menu.ts
core/menuitem.ts
core/mutator.ts
core/renderers/common/path_object.ts
core/theme_manager.ts
core/toolbox/category.ts
core/toolbox/collapsible_category.ts
core/toolbox/separator.ts
core/toolbox/toolbox.ts
core/utils/dom.ts
core/widgetdiv.ts
core/workspace_comment_svg.ts
core/workspace_svg.ts
tests/mocha/toolbox_test.js

Fixes #6454 
Adds proper splitting to addClass and removeClass. Changes everything back to using addClass and removeClass
We had things in core that implicitly supported applying multiple classes separated by spaces, which recently broke.
Now it is working once again.
Regressions are sad.
Added a test specifically for applying multiple classes to an icon, cuz it was easy. But generally I'm just trusting that my fixes are correct.
N/A
N/A

fix: adding and removing css classes that contained spaces

---

core/renderers/common/marker_svg.ts

Resolves one of the issues blocking https://github.com/google/blockly-samples/pull/1297#issuecomment-1261527686
Use a cast and checking for a property, rather than an `instanceof` check, to make it safe to call `beginElement()` on a marker. This avoids breaking tests when run in jsdom.
Tests broke becuase `SVGAnimationElement` was not defined when running with jsdom.
These tests pass (although a different set of tests fails >.<)
The tests are running in Mocha, and using jsdom to pretend that they are in a rendered page. The marker SVG and similar elements are created but certain classes don't exist. `SVGAnimationElement` is one of them, which triggered a failure.
Note that the tests running rendered in jsdom is a bit weird, but they cannot run in headless mode because keyboard navigation …

fix(tests): revert change in marker_svg to keep keyboard nav tests working

---

core/field.ts
core/field_angle.ts
core/field_checkbox.ts
core/field_colour.ts
core/field_dropdown.ts
core/field_image.ts
core/field_label.ts
core/field_multilineinput.ts
core/field_textinput.ts
core/field_variable.ts
core/renderers/common/drawer.ts
core/tooltip.ts

This resolves several `AnyDuringMigration` type cases in `core/field.ts`.
- Updates nullable types, when set, to be `<OriginalType>|null` to properly reflect its possible state
- Updates usage of those nullable types to assert they're available in `core/field.ts` and impacted descendants 
- **Note:** Used the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator), `someValue!.nowExists`
- Added type information for `callingClass` which uses Field's prototype
- Updates numbers which are expected to be strings to be cast to strings in `core/field.ts`
- Less precise type information.
- `SVGTextElement.setAttribute` passed in numbers as attribute values instead of strings in `core/field.ts`
- More precise type …

chore: cleaned up several type cases in core/field.ts and impacted files

---

api-extractor.json
core/extensions.ts
core/renderers/common/block_rendering.ts
core/utils.ts

This resolves missing deprecation messages.
- Added `@deprecated` messages and updated `./api-extractor.json` to no longer ignore logs for `"tsdoc-missing-deprecation-message"`
- Updated the blockly alias to be bolded for some deprecation messages in `./core/utils.ts`.
- Removed `@internal` from **runAfterPageLoad** in `./core/extensions.ts`
- Some `@deprecated` notices did not have messages to display.
- All `@deprecated` notices have messages to display.
- Deprecation messages display in **bold**.
This is a cleanup task to provide more information to function descriptions and, by extension, the documentation.
N/A for automated tests, though I manually tested this change by running `npx @microsoft/api-extractor run --local` from the root. I used that command to identify the missing …

chore: fixed tsdoc missing deprecation messages

---

core/block_drag_surface.ts
core/blockly.ts
core/css.ts
core/generator.ts
core/main.js
core/renderers/common/block_rendering.ts
core/renderers/common/debug.ts
core/utils.ts
core/utils/object.ts
core/utils/string.ts
core/utils/style.ts
core/utils/svg_math.ts
core/workspace_svg.ts

N/A
- Removes deprecated things we said we would remove.
- Updates some deprecation warnings to be removed in the next major.
- Adds `@deprecated` tags to some functions that did not have them.
Some functions existed.
Now those functions do not exist.
Code health.
N/A
N/A
For any breakages due to the removal of deprecated methods, please refer to the deprecation tag, and/or deprecation warning in the code below.

fix!: Update deprecations for the new release.

---

core/field_multilineinput.ts

- #6165 
- #6071 
Changing size calculation in `updateSize_`  from `getTextWidth` to `getFastTextWidth`.
Multiline field not correctly size in parent block when copy/paste or load.
Multiline field correctly size in parent block when copy/paste or load.

fix: Multiline field not correctly size in parent block when copy/paste or load.

---

core/css.ts

Noticed this when Firefox whined about it in the developer tools.  I ran the CSS through W3's CSS validator and there were no other errors.

Fix: `//` isn't a legal comment in CSS

---

core/rendered_connection.ts

fixes https://github.com/google/blockly/issues/6501
In connection highlight, if highlightPath already exists, then silently return early because it's already highlighted.
Calling highlight twice will leave the connection highlight. 
The highlight is not applied twice, so can be removed. 
Manually tested, see pictures. 
No documentation update is needed, now it works as expected and documented.

fix: Connections can be highlighted multiple times

---

core/field_angle.ts
core/field_dropdown.ts
core/field_textinput.ts
core/renderers/common/constants.ts
core/renderers/common/path_object.ts
core/renderers/zelos/path_object.ts
core/theme.ts

Fixes #4774 
Moves the `BlockStyle` type to have required properties, and use `Partial` where necessary.
Code health
N/A
N/A
N/A

fix: move Theme to use a Partial type for BlockStyle

---

core/block_drag_surface.ts
core/blockly.ts
core/bubble.ts

General code cleanup.
Stop using underscores for private fields and methods in `block_drag_surface.ts` and `bubble.ts`. Where possible, remove casts and `!` markers.
No change.
No change.
General code cleanup: standardize on non-underscored private variable names, and avoid casts so the compiler can better tell us when we make a breaking change.
Mocha tests, and manual testing:
- Open up the playground and get a block with a mutator.
- Drag the mutator around by various parts of the bubble (check for no change in bubble behaviour)
- Add multiple blocks and drag them around the workspace, singly and connected (check for no changes in block drag surface).
None.
This change was made possible by knowing which properties are private and which are public!
I did not touch anything that's …

chore: clean up some underscores

---

core/workspace.ts
tests/mocha/gesture_test.js
tests/mocha/test_helpers/workspace.js

General cleanup.
Renames private properties in `workspace.ts` to remove underscores.
In the process, I found many tests that accessed private properties directly instead of using getters, and fixed them. This means those tests are now using external APIs.
No change
No change
General cleanup, and conformance with the google style guide.
Standard Mocha tests
None

chore: remove underscores from private properties in workspace.ts

---

core/workspace_svg.ts
core/zoom_controls.ts
tests/mocha/gesture_test.js

General cleanup/matching style guide
Remove underscores from some private properties and methods. Update tests where needed to use public APIs instead of private properties.
No change.
No change.
Match style guide (no underscores in private properties) and stop using private properties in tests.
Mocha tests.
I didn't get every case in workspace svg, because some are used in unexpected ways. These are just the trivial ones.

chore: remove underscores from some private properties and methods

---

blocks/procedures.js
core/block_svg.ts
core/shortcut_registry.ts
demos/blockfactory/factory.js
demos/blockfactory/standard_categories.js
demos/blockfactory/workspacefactory/wfactory_controller.js
demos/blockfactory/workspacefactory/wfactory_view.js
tests/mocha/blocks/variables_test.js
tests/mocha/shortcut_registry_test.js

utils.dom.add/removeClass is going away, now that the IE work-around it provided is no longer required.
Fixes #6325

chore: Remove blockly factory use of utils.dom.add/removeClass

---

core/block_svg.ts
core/rendered_connection.ts

#6017 
makes it so that whenever a block in a block stack has `bumpNeighbours` called on it, all of the connections in the block stack bump.
We have to bump every single connection, because with custom renderers, we can't predict how blocks will be shaped based on other blocks. E.g. in geras higher sibling connections don't move, but in other renderers they might. So we have to trigger bumping on everything.
Parent blocks would not bump neighbours when a child block was rerendered.
Parent blocks do bump neighbours when a child block is rerendered.
Having blocks appear tto be connected (visually) without actually being connected (in terms of code generation) can cause confusing results and frustration for end-users. This helps eliminate that.
N/A
N/A
Also did some code cleanup of …

fix: parent blocks not bumping neighbours

---

core/procedures/observable_parameter_model.ts
core/procedures/observable_procedure_map.ts
core/procedures/observable_procedure_model.ts

Fixes #6514 
Dependent on #6488 
Adds some basic implementations of the procedure interfaces. They don't do any of the important stuff yet (i.e. triggering `doProcedureUpdate` or firing events).
Interfaces need to be implemented.
N/A
N/A
N/A

feat: add basic observable implementations of procedure interfaces

---

tests/playgrounds/shared_procedures.html

Blocked by #6475 cuz I need to change the `additionalScripts` to point to the built msgs.
Adds a test page (which doesn't do anything yet) for eventually testing the shared procedures code.
Having a test page is going to be helpful for things that are more difficult to unit test.
This is testing silly!
Noup
N/A

test: add shared procedures playground

---

core/events/events_block_drag.ts
core/events/events_bubble_open.ts
core/field_registry.ts
core/shortcut_items.ts

This is the only place in our codebase where it's quoted.  The result is a failure to compile correctly using advanced optimizations.

fix: Don't quote fromJson property.

---

core/field_angle.ts

Removes some `AnyDuringMigrations`.
Remove some uses of `AnyDuringMigration` and set default values in the class declaration instead of the constructor. Also move property comments to the class declaration, which I think will make them show up in our generated documentation, and make some SVG element types more accurate.
I tried to also rename properties to not have underscores, but we're checking those properties a lot in the tests, so more work is needed there.
No change.
No change.
Incremental cleanup.
Mocha tests.
Should slightly improve generated documentation.
Angle field tests check private properties, specifically while checking that the constructor runs correctly.

chore: clean up code in field_angle.ts

---

core/field.ts
core/field_angle.ts
core/field_dropdown.ts
core/field_multilineinput.ts
core/field_textinput.ts
core/field_variable.ts
core/interfaces/i_ast_node_location_with_block.ts
core/keyboard_nav/ast_node.ts
core/procedures.ts

https://groups.google.com/g/blockly/c/IxL-Px8GMXA/m/EK5g2VQ8BwAJ?utm_medium=email&utm_source=footer
Makes getSourceBlock nullable again.
No user-facing change in behavior.
No user-facing change in behavior.
We were breaking people who were using getSourceBlock in callbacks that were called before the field was attached to a block. 
N/A
N/A
N/A

fix: make getSourceBlock nullable again

---

core/field.ts
core/utils/parsing.ts

One part of issue #6557.
Part two is updates to the json translation files (but those go into the translatewiki branch).

fix: Don't warn if field is acually 0 width

---

core/block_animations.ts

Fixes #6541 
Reverts changes made in #6301 that caused jumping.
Bugs are bad.
Manually tested the repro steps from #6541 
N/A
Thank you to Maribeth for the bisect + cherrypick idea!
Also for now I've just reverted the bug-causing changes. But I'm also going to file a bug for actually refactoring this system to be more testable + less stateful + not use private properties on svg elements.

chore: fix mutator blocks jumping

---

core/blockly.ts
core/procedures.ts
core/procedures/observable_parameter_model.ts
core/procedures/observable_procedure_model.ts
tests/mocha/procedure_map_test.js

Dupe of #6562 (but this time actually waiting for dependent things)
Fixes #6561

chore: update procedure map tests to match the refactored API

---

core/interfaces/i_procedure_block.ts
core/procedures/observable_parameter_model.ts
core/procedures/observable_procedure_map.ts
core/procedures/observable_procedure_model.ts
core/procedures/update_procedures.ts
tests/mocha/procedure_map_test.js

#6515 
Makes it so updates to the procedure data models actually trigger updates to blocks.
Note that the built-in blocks haven't be refactored to /respond/ to these updates. But now they could be.
Enabled skipped tests!
N/A
Dependent on #6569

feat: trigger updates to IProcedureBlock blocks

---

package-lock.json
package.json
scripts/migration/renamings.json5

Merge changes made in the master branch since the v9.0.0 release.  This merges a substantial number of commits, but most are either rolled back by other later commits or are cherry-picks of changes already in `develop`, leaving just two actual changes:
* Updating the version number to 9.0.1, and
* Correcting an error in `renamings.json5`.
Keep `develop` up-to-date with respect to changes in `master`, and thereby reduce the likelihood of merge conflicts when we next release (i.e. merge from `develop` to `master`).
* There were conflicts in
* `core/field_angle.ts`
* `core/field_dropdown.ts`
* `core/field_variable.ts`
that were due to having cherry-picked changes from `develop` into `master` for the 9.0.1 release; these were "resolved" by resetting those files to the `develop` version, since …

chore: Merge branch 'master' back into develop after v9.0.1 release

---

core/interfaces/i_parameter_model.ts
core/interfaces/i_procedure_map.ts
core/procedures/observable_parameter_model.ts
core/procedures/observable_procedure_map.ts
core/procedures/observable_procedure_model.ts
core/workspace.ts
tests/mocha/procedure_map_test.js

- [] I branched from develop
No tracking issue for this, just what we discussed in internal chat / vc.
Three separate things:
* Expanding the IParameterModel interface
* Removing support for return types from the ObervableProcedureModel
* Adding an interface of the ProcedureMap (which includes our non-`Map` methods)
Relevant tests already existed.
N/A
Dependent on #6570

fix: refactors concrete implementations of the procedure data models

---

core/scrollbar.ts

In three commits:
- Restructure the constructor so that properties are set in the constructor, not in a helper function. This let me remove nullability from several SVGElements that the scrollbar tracks.
- Stop tracking an SVG Element that was only used during construction.
- Change `dispose` to remove the scrollbar's root node but not set anything else to `null`. This also helped with nullability. The garbage collector is in charge of the rest of cleanup.
- Add comments to property definitions to make them more meaningful for the next reader.
- Rename all private properties and methods that end in underscores to remove the underscores.
No change.
No change.
Cleanup, and reading code to understand dependencies.
Mocha tests, but I also …

chore: remove underscores and clean up scrollbar.ts

---

scripts/gulpfiles/test_tasks.js

Fixes an issue where the generator tests fail on Linux with 
```
fenichel@fenichel-glaptop2:~/Documents/gblockly-rr$ npm run test:generators
> blockly@9.0.1 test:generators
> gulp --silent testGenerators
=======================================
== generators
Cannot read properties of null (reading 'code')
FAILED: generators
fenichel@fenichel-glaptop2:~/Documents/gblockly-rr$
```
Remove trailing slashes from calls to `rimraf`.
Crashes on linux
Tests run and don't crash.
Rimraf didn't like the trailing slash, which is surprising to me.
Caused by #6431 so we'll need to verify it still works on windows after this fix.

fix(tests): generator tests on linux

---

core/comment.ts
core/icon.ts
core/mutator.ts
core/warning.ts
tests/mocha/mutator_test.js

Remove underscores from private property names and method names, where they weren't being used by tests.
Also cleans up some nullability indicators.
No change.
No change.
General cleanup, as a way of reading through code and understanding icon architecture.
Mocha tests, and also opened up the playground and played around with comments and mutators.
None.
`comment.textarea_` and `comment.paragraphElement_` are being accessed directly in tests, so I left them alone.

chore: remove some underscores in icon-related classes

---

tests/mocha/index.html
tests/mocha/insertion_marker_manager_test.js
tests/mocha/test_helpers/block_definitions.js

Just improving test coverage.
Add tests.
There are four test suites.
The first one checks that the constructor works when given various blocks and block stacks, and that the appropriate number of markers is created (i.e. one marker for the first block, and sometimes another for the last block in the stack).
The second suite checks logic controlling whether a block is deleted when the drag ends. I stubbed the capability manager and drag target to force it down various paths. `wouldDeleteBlock` is one of the few public methods available to get information out of the insertion marker manager.
The third and fourth suites check that the insertion marker manager can find an appropriate connection in the middle of a drag. I faked dragging the block above, below, left, and right from the …

test: add tests for the insertion marker manager

---

core/block_dragger.ts
core/insertion_marker_manager.ts
tests/mocha/insertion_marker_manager_test.js

Part of #6548 
There are several rounds of changes in here. I did my best to have separate commits for basic naming changes, whitespace changes, and actual changes. I suggest reviewing one commit at a time.
The first bunch are fairly mechanical.
- Move documentation comments out of the constructor and onto property declarations. This should also improve tsdoc.
- Remove underscores from private property names
- Remove underscores from private properties and methods
- Format/lint
After that things get more complicated. The code previously had many checks for null that happened because a property could be null _at some point_, even though the relevant method was only called once and the relevant properties would never be null. Also, the information about the potential connection to make (the …

chore: clean up insertion marker code

---

core/input.ts

Part of #6548 
Renames some private properties to remove underscores, and move comments around.
No change.
No change.
Cleanup
Input tests in mocha.
None

chore: removes underscores in input

---

core/field.ts
core/field_angle.ts
core/field_checkbox.ts
core/field_colour.ts
core/field_image.ts
core/field_label.ts
core/field_number.ts
core/field_textinput.ts

This update provides handling for `AnyDuringMigration` for `DEFAULT_VALUE` in `core/field.ts` and its descendants.
- Adds `DEFAULT_VALUE` to base `core/field.ts` of type `T|null`
- `DEFAULT_VALUE` was hidden in the corresponding classes before
- Had to use `AnyDuringMigration` to set `DEFAULT_VALUE`
- No longer need `AnyDuringMigration` for `DEFAULT_VALUE`
Code health! :)
N/A
N/A
Nothing!

chore: clean up field default values

---

.github/PULL_REQUEST_TEMPLATE.md

N/A
Adds the "fixes" keyword to the PR template.
Makes it harder to forget to link an issue.
This won't actually effect anything until this gets merged into master. But I didn't know if we wanted to do that right now, so I'm putting it up against develop.

chore: add 'fixes' to PR template

---

scripts/migration/renamings.json5

A small error in the entry for `Blockly.utils.global`, that failed to account for the fact that this (former) module had a named export.
Adjust the entry to make it clear that `globalThis` was a named export, not the default export.
Also remove some unnecessary quoting of keywords.
It would have worked anyway.
It will work correctly, and now for the right reason.
I am pedantic.
This change doesn't make any difference in practice to the behaviour of the renamings script, so there is no reason to push it to `master` immediately for the benefit of the renamings script.

fix(renamings): Small correction to renaming of `Blockly.utils.global`

---

gulpfile.js
package-lock.json
package.json
scripts/gulpfiles/test_tasks.js

* **feat**: Modify `runTestBlock` so that it can run any async task, not just ones that return a `Promise`, by using the `async-done` package (part of Gulp, and already an indirect dependency) to detect task completion.  Celebrate by renaming it to runTestTask.
* Create a `Tester` class to encapsulate the `runTestTask`, `reportTestResult` and `runAll` functions.
* Remove the `--silent` flag from npm scripts so as not to suppress syntax error in gulpfiles.
* Have the `test` task invoke the `buildAdvancedCompilationTest` task (via `onlyBuildAdvancedCompilationTest`, to skip already-run prerequisites) directly, rather than by running `npm`.
* Generally cleaner code.
* Remove npm scripts that aren't intended to be used by humans.

feat(test): Miscellaneous improvements to `test_tasks.js`

---

msg/json/README.md

Add a README.md file to msg/json/ explaining the purpose of the files therein, mentioning that PRs are not accepted but that translation updates should be made via TranslateWiki, and with a short description of how to build the langfiles that are generated from them.
Well-meaning external contributors send us PRs with translation corrections.
With luck: well-meaning external contributors instead use TranslateWiki to submit translation updates.
Avoid wasting their (and our) time with PRs that we cannot accept.
Yes.

docs(messages): Add a msg/json/README.md

---

core/mutator.ts

Fixes https://github.com/google/blockly/issues/6630
Revert the renaming of the mutator workspace: `workspace` -> `workspace_` and make it public.
Workspace was not officially public but was being used by procedure mutators, and it broke when I renamed it.
Existing procedure mutators work now.
Revert a rename that actually broke something.
1. Open the playground
2. Pull out a procedure definition block
3. Open the mutator
4. Add two parameters
5. Rename one of the parameters
Beka reported that this triggered the issue, and it now works.
Beka is also adding tests for procedures as part of the rest of her work, which should help avoid this in future.
None
The built-in blocks blur the line between internal and public. My position: any property the blocks access (e.g. in mutators) is public …

fix: make mutator workspace public

---

.github/workflows/check_clang_format.yml

Fixes 
clang-format 1.8.0 uses format 15
format 13 used
format 15 used
ci version should be as close as possible to the version that the npm package supports

ci: clang format version bump

---

core/block.ts
tests/mocha/event_block_delete_test.js
tests/mocha/test_helpers/setup_teardown.js

Fixes #6319 
but actually this time.
Makes it so that block change listeners unregister themselves when they receive the delete event for the block they are associated with. This ensures they actually receive that event (i.e. they're not getting removed too early).
Blocks were not receiving their own delete events.
Blocks are receiving their own delete events.
Sometimes you want to trigger cleanup / other operations when a block is deleted.
Fixed test to actually wait for the delay built-in to the events system. Before the tests were passing incorrectly because we'd stubbed the fire method to fire immediately.
N/A
N/A

fix: blocks not receiving their own delete events

---

core/flyout_base.ts
core/workspace_svg.ts

Amusingly Flyout.isVisible and .setVisible are public, but there's no way to access a flyout given that getFlyout was not public.

feat: make `getWorkspace`, `getFlyout`, and `getToolbox` public

---

blocks/procedures.js
core/block.ts
tests/mocha/blocks/procedures_test.js
tests/mocha/event_block_delete_test.js
tests/mocha/index.html

Reverts google/blockly#6337
We are reverting these changes and creating a different solution for #6319

Revert "feat!: allow blocks to receive their own delete events"

---

core/variable_map.ts
core/variable_model.ts
tests/mocha/variable_map_test.js

Fixes #6524 
1) Makes it so that the variable map returns early in cases where renames are noops (other modificiations already did this correctly).
2) Moves firing create events from the `VariableModel` to the `VariableMap`.
1) This prevents us from getting into infinite event loops when sharing events between multiple workspaces. See [here](https://github.com/google/blockly/pull/6650#discussion_r1036554356) for an example/explanation.
2)  This allows us to use variable models as backing data models without actually having them (e.g.) show up in the flyout.
Added unit tests for creating, deleting, and renaming, and when they should fire events vs not fire events.
N/A
This is not dependent on any parent branches, so it's ready for review!

feat: make the variable map return early for noops

---

core/variables.ts

No functional change, just jumping through hoops due to tooling.
"JSDoc @returns declaration present but return expression not available in function"

chore: stop linter from whining about no return

---

appengine/blockly_compressed.js

Logs show about a dozen orgs actively using Blockly instances that are hot-linked to blockly-demo.appspot.com
These files disappeared on 25 November 2022, breaking a bunch of people.  This alert should point developers in the right direction.

docs: Add notice to use unpkg instead of demos.

---

core/block.ts
tests/mocha/block_test.js
tests/mocha/test_helpers/events.js
tests/mocha/test_helpers/setup_teardown.js

Fixes #6319 maybe actually finally
Adds a new `destroy` lifecycle hook that is called at the end of `dispose` which can be used for cleanup (e.g. of any backing data models for the block).
Sometimes you need to clean data up!
Adds tests to make sure dispose gets called at the proper time, and events fired from it are actually fired.
N/A
Putting this up as a draft until we're sure we're definitely happy with the design.

feat: add destroy lifecycle hook to blocks

---

scripts/gulpfiles/appengine_tasks.js

Temporary fix for #6609, fixing 404 errors on devsite that break the homepage demo (for languages other than English, which has already been successfully fixed by making changes to devsite).
Modify the `prepareDemos` script to copy the messages and compressed files to their previous locations in the deploy directory
Build products are copied to `_deploy/static/build/msg/` and `_deploy/static/dist/`, matching their usual locations in the Blockly repo.
Build products are additionally copied to `_deploy/static/msg/js/` and `_deploy/static/`, matching their locations in the Blockly repo prior to PR #6475.
The demo on [the Blockly Developers website homepage](https://developers.google.com/blockly/) was broken by #6475 and we have only been able to fix by updating devsite for English so far; it …

fix(appengine): Restore build products to previous location

---

core/events/events_procedure_base.ts
core/events/events_procedure_change_return.ts
core/events/events_procedure_create.ts
core/events/events_procedure_delete.ts
core/events/events_procedure_enable.ts
core/events/events_procedure_parameter_base.ts
core/events/events_procedure_parameter_create.ts
core/events/events_procedure_parameter_delete.ts
core/events/events_procedure_parameter_rename.ts
core/events/events_procedure_rename.ts
core/serialization/procedures.ts
tests/mocha/event_procedure_change_return_test.js
tests/mocha/event_procedure_create_test.js
tests/mocha/event_procedure_delete_test.js
tests/mocha/event_procedure_enable_test.js
tests/mocha/event_procedure_parameter_create_test.js
tests/mocha/event_procedure_parameter_delete_test.js
tests/mocha/event_procedure_parameter_rename_test.js
tests/mocha/event_procedure_rename_test.js

Fixes #6601
Adds round-tripping procedure events through serialization.
To be able to share events between workspaces we need to be able to serialize and deserialize them.
Tests are now enabled.
N/A
Dependent on #6668

feat: procedure event serialization

---

core/field.ts

Although the default Field type `T` should eventually be `unknown`, set it to `any` so it does not break users with subclasses extending from `Field` in the meantime.
- Update `core/field.ts` - `FieldValidator` to provide the correct return type.
- Update `core/field.ts` - `T = unknown` to `T = any`
TypeScript users with classes extending from `Field` would have to fill in a type for `Field` or their code will break.
TypeScript users can now extend from `Field` without providing the value type.
This is for introducing the Field type information in multiple stages.
N/A
N/A
Nope!

fix: set default field to any and fix validator function return type

---

core/field_number.ts

For the most part spellcheckers ignore numbers so this isn't an issue.  But (for example) 'Infinity' is an English word that's hardcoded into Blockly, and other languages may spellcheck it as wrong.

fix: Don't spellcheck number fields.

---

core/trashcan.ts

No visible change for regular case.  But if there's thousands of blocks in the trash, the visual feedback that something's happening is needed.  Otherwise the user will click in confusion, and that click will cause some random block to be spawned out of the trash.

feat: Display a 'wait' cursor when opening trashcan

---

core/field_input.ts
tests/mocha/blocks/procedures_test.js

Fixes #6701 
Makes it so that you can set a text field to empty.
Sometimes the empty string is useful!
Mostly manual testing. Also updated some change-detector tests to not fail. (gah past self)
N/A
I think the issue started here: https://github.com/google/blockly/pull/6073
Basically, we used to be checking the text value against `null` and then we were checking it against `''` (to see if it had changed), which was failing.
So now, instead of trying to do this weird thing to check if the value had changed, just let `setValue` handle it like a normal field, and set `isDirty_` in the `doValueUpdate_` and `doValueInvalid_` functions instead of forcing a layout "manually".

fix: not being able to set field values to empty

---

blocks/procedures.js
tests/mocha/blocks/procedures_test.js

Work on #6526 
Updates procedure blocks to respond to changes in data models.
Work on getting procedures to actually use the source of truth data models!
Tests for responding to updates are now enabled.
N/A
Dependent on #6672

feat: procedure def blocks respond to models

---

blocks/procedures.js
core/procedures/observable_parameter_model.ts
tests/mocha/blocks/procedures_test.js

Work on #6526 
Makes it so that procedure defs properly deserialize procedure models when they are instantiated. 
Makes it so the procedures can appear to be implicitly defined (maintaining the previous user-facing behavior).
Added unit tests for deserialization.
N/A
Dependent on #6673

feat: procedure defs deserialize models

---

blocks/procedures.js
core/procedures/update_procedures.ts
tests/mocha/blocks/procedures_test.js
tests/mocha/test_helpers/procedures.js
tests/mocha/test_helpers/serialization.js

Work on #6526 
Refactors the procedure caller blocks to rely on the backing data models.
Using the data models makes it so that procedures are explicitly defined!
Enabled some tests, added some tests, reorganized some tests etc.
N/A
Almost certainly best to review this commit-wise haha.
Dependent on #6706

feat: procedure callers respond to models

---

blocks/procedures.js
core/procedures/observable_parameter_model.ts
core/serialization/procedures.ts
tests/mocha/blocks/procedures_test.js
tests/mocha/jso_serialization_test.js
tests/mocha/webdriver.js

Fixes #6040 
Work on #6526 
Fixes two bugs found with undo and redo and parameters:
* Undoing and redoing creating a parameter would create duplicate parameters
* Undoing and renaming parameters would fail with errors
Fixing bugs is fun!
Added tests for undoing and redoing:
* Adding parameters
* Renaming parameters
* Deleting parameters
Also changes a bunch of tests to properly tick the clock instead of calling `compose` or doing other things.
N/A
Had to skip some tests for dealing with unnamed procedures, because once I fixed them to properly tick the clock, I found out they were broken. They are fixed in a follow-up PR.
Dependent on #6718

fix: undoing and redoing parameter events

---

blocks/procedures.js
core/procedures.ts
tests/mocha/blocks/procedures_test.js

Work on #6526 
Discovered that when a procedure was deleted, and then the action was undone, procedure callers that were deleted with the definition were not properly reassociated with the procedure definition when they were deserialized. So e.g. when the definition was renamed, callers would not be renamed with it.
Fixing bugs is rad!
Added tests for undoing and redoing deleting procedures.
N/A
Dependent on #6721

fix: undoing and redoing deleting procedures

---

tests/mocha/field_angle_test.js
tests/mocha/field_number_test.js
tests/mocha/test_helpers/fields.js

Fixes #6180 
- Updated `tests/mocha/test_helpers/fields.js`

fix: change assertFieldValue in test helpers to use deepEqual

---

core/events/events.ts

Fixes Blockly.Events.Abstract not being documented: https://developers.google.com/blockly/reference/js/blockly.events_namespace.abstract_variable.md
exports the class directly instead of importing it under a different name and then exporting it under the original name
Tested by packaging, linking to blockly-typescript-libcheck, and making sure Blockly.Events.Abstract is still valid
Also checked the generated documentation is fixed

fix: export Abstract event class directly

---

blocks/procedures.js
core/interfaces/i_procedure_block.ts
core/procedures.ts
tests/mocha/procedure_map_test.js

Fixes #6525 
Refactors the procedures namespace to use the new procedure block interface methods instead of the old ones.
Should be no change in behavior.
Realized I actually did need to refactor this so that external devs don't have to implement the old `getProcedureDef` and `getProcedureCall` methods.
Passes all existing tests.
N/A
Dependent on #6736

chore: refactor procedures namespace

---

blocks/procedures.js
tests/mocha/blocks/procedures_test.js
tests/mocha/test_helpers/serialization.js

N/A
Procedure parameters were not being rendered correctly when loading from JSON. This fixes that.
Properly rendering parameters is important!
Added JSON serialization tests equivalent to the existing XML serialization tests.
N/A
Dependent on #6745

fix: proc json serialization

---

blocks/procedures.js
core/interfaces/i_procedure_block.ts
tests/mocha/blocks/procedures_test.js

Fixes #6749 
Before when you would load two procedure definition blocks that point to the same procedure ID (e.g. when copy pasting) they would both be associated with the same procedure model, which is not what you want. This makes sure that each individual procedure definition block (excluding insertion markers) is associated with its own procedure model.
Added a test for deserializing two procedure definition blocks that are both associated with the same procedure model.
N/A
Dependent on #6746

fix: copying and pasting procedure definitions

---

core/utils/xml.ts
scripts/package/node/core.js

Fixes #6725.
1. Introduce a mechanism for injecting arbitrary dependencies into modules, specifically in this case
to inject required bits of [jsdom](https://github.com/jsdom/jsdom)'s `Window` and `Document` implementations into `core/utils/xml.js` when running in node.js or other environments lacking a DOM.
0. Rename the `xmlDocument` local variable back to `document` (was renamed in #5461) so that the name used in this module corresponds to the [usual global variable](https://developer.mozilla.org/en-US/docs/Web/API/Window/document) it replaces.
0. Change the injection in `scripts/package/node/core.js` to use `injectDependencies` instead of `setDocument` + global variables for `DOMParser` and `XMLSerializer`; also eliminate apparently-unnecessary creation of a special
`Document` …

fix(deps): Don't use global variables for jsdom injection in `scripts/package/node/core.js` and `core/utils/xml.ts`

---

package.json

Doing `npm start` in a clean checkout loads a broken playground, because the `deps` script does not run `buildLangfiles`.
To fix this have the `start` script run the `build` script rather than just `deps`.  This also ensures that compressed playground loading would work too (though uncompressed is the default).

fix(tests): Have `npm start` run a full build

---

scripts/gulpfiles/test_tasks.js
tests/scripts/check_metadata.sh
tests/scripts/update_metadata.sh

#6768
This PR updates the metadata test to verify that the previous size of the files is not undefined, in order to trigger an explicit test failure in the situation reported in #6768. It also updates the check_metadata.sh file to remove errant whitespace before the file sizes that was causing the regex in test_tasks.js to fail to identify the old file sizes when running the test. Finally, it updates update_metadata.sh to strip whitespace when updating the file sizes in check_metadata.sh to avoid this issue recurring.
Metadata test scripts didn't actually check the change in filesize and passed regardless.
Metadata test scripts work properly.

fix: Make metadata tests more resilient.

---

core/block_animations.ts
core/block_svg.ts
core/workspace_comment_svg.ts

Fixes #6595
This change stops setting skew_ and translation_ attributes on SVGs for blocks. It introduces an internal getter for the translation, and stores it in a proper field on BlockSvg.
skew_ was only being set to a non-'' value in one place, and then immediately read back to set the transform. Instead, the transform is simply setting using the directly-calculated skew value, so there's no need to carry it around and clear it at other points.
WorkspaceCommentSvg also maintained the skew_ and translate_ attributes, but they appear to be vestigial from a long-ago copy-paste and not actually used, so they were removed.

refactor: Don't use skew_ and translate_ attributes on SVGs to animate blocks.

---

scripts/gulpfiles/build_tasks.js
tests/mocha/event_marker_move_test.js
tests/mocha/event_selected_test.js

`npm test` output had become increasingly cluttered with miscellaneous WARNINGs from `closure-make-deps`.  Investigating this, it turned out that two recently-added test files were not being run at all.
- Fix actual syntax errors in `import`s in `event_marker_move_test.js` and `event_selected.test.js`, which were preventing those tests from being run.
- Remove `suite.only` directives in those tests that would prevent all the other tests from running.
- Run `closure-make-deps` only once, instead of separately for `core/` and `tests/`.
- Specify a larger `exec` `maxBuffer` size, to ensure output and diagnostics are not truncated.
- Change `stderr` filtering in `buildDeps` to filter out bounded generics messages and blank lines.
- Attempt to suppress warnings in `stderr` output when …

fix(build): Fix event tests, improve `buildDeps`

---

core/workspace_svg.ts
tests/mocha/workspace_svg_test.js

#5432 
Adds an optional argument to centerOnBlock() that, if set to true, will center the workspace on the block itself, rather than the default behavior of centering on that block's stack.

feat: Add support for centering on a block itself vs its stack.

---

core/events/events_comment_move.ts
core/field_colour.ts
core/field_image.ts
core/interfaces/i_copyable.ts
core/interfaces/i_selectable_toolbox_item.ts
core/toolbox/collapsible_category.ts
core/toolbox/toolbox.ts
core/utils/toolbox.ts
core/workspace.ts
core/workspace_comment.ts
core/workspace_comment_svg.ts
tests/mocha/workspace_comment_test.js

Part of #5857 
Removes uses of AnyDuringMigration from workspace_comment_svg.ts, toolbox.ts, field_colour.ts, field_image.ts, and workspace.ts.

chore: Remove some more uses of AnyDuringMigration

---

tests/bootstrap_helper.js
tests/playgrounds/shared_procedures.html

Fixes #6824.
Use `en.js` instead of `messages.js` in tests.
`messages.js` is not intended to be used this way.  Also: we want to test build output.
This change had already been made (by PR #6475 amongst other) to most of the tests, but there were a couple of stragglers that still mentioned `messages.js`.

fix(tests): Use `build/msg/en.js` instead of `msg/messages.js`

---

blocks/lists.js
blocks/procedures.js
blocks/text.js

#6611
Updates the standard block definitions to use the field registry to instantiate fields, rather than instantiating the field classes directly.

refactor: Use the field registry to instantiate fields in block definitions.

---

core/field_dropdown.ts

Specifically in Blockly Samples the field-grid-dropdown wants to call this inherited function.

chore: Make dropdownDispose available for plugins.

---

tests/bootstrap_helper.js
tsconfig.json

Prior to PR #6818, circular imports resulted in the debug module loader (in `closure/goog/base.js`) failing to record the
`goog.module` ID of most modules that were involved in any cycle, and in particular of the `Blockly.Xml` module.  This had secondary fallout that resulted in library blocks modules being loaded in the wrong order.
A kludge was introduced in PR #6703 that worked around this problem by making sure that `window.Blockly` was set, allowing the modules loaded out-of-order to still work.
Now that we have removed all remaining circular dependencies there is no need for the kludge, since all module IDs are properly recorded and modules are loaded in the correct order.
There was a transitional period where we had both `core/blockly.ts` and `core/blockly.js`, and wished to …

chore(build,tests): Remove obsolete kludges / config options

---

core/procedures.ts
tests/mocha/blocks/procedures_test.js

N/A
isNameUsed was not fully respecting the procedure map, so it was possible when sharing procedures between workspaces for two procedure definition blocks (in different workspaces) to have the same name. This makes it so that that is no longer possible.
Add tests that `isNameUsed` respects the procedure map.
N/A
N/A

chore: fix isNameUsed not fully respecting the procedure map

---

scripts/migration/js2ts

Add a script, `js2ts`, to automate some of the more trivial but annoying work to be done converting blocks and generators from JavaScript to TypeScript.  In particular, it
- Converts `goog.module()` to `goog.declareModuleId()`, and adds the requisite import of `goog.js`.
- Converts `goog.require()` to `import`
- Converts `exports.foo = foo` into `export foo` (preferably by `export` to the declaration of `foo` if possible), rather than as a separate statement).
I'm lazy and don't want to do all this fiddly work by hand.
I ran it on `math/blocks.js` and the result was vaguely reasonalble-looking.
It could use some.

chore: Create script to help with `.js` -> `.ts` migration

---

core/flyout_button.ts

In response to https://groups.google.com/g/blockly/c/sMG41uE-WG0, this enables setting the border radius via overwriting the newly added static variable.
Add static variable for the button's border radius.
No static variable for Flyout Button's border radius.
Added static variable for Flyout Button's border radius.

feat: updated flyout button to set border radius via static variable

---

core/css.ts
core/field_number.ts

Fixes #1595
Sets the `type` of the input field for field_number.ts to `number`.
field_number.ts didn't specify a type for its input field.
Verified that tests pass and field behaves normally on Chrome, Firefox, Safari and Mobile Safari.

refactor: Use input type=number for field_number.ts

---

scripts/gulpfiles/build_tasks.js
tsconfig.json

Part of #6828
Modify `build_tasks.js` so that `blocks/` and `generators/` are passed through `tsc` before being fed to `closure-make-deps`, Closure Compiler, etc.
Closure Compiler and debug module loader read from `blocks/` and `generators/` directly.
`blocks/` and `generators/` are included in `tsc`'s input, and Closure Compiler and debug module loader read from `build/src/blocks/` and `build/src/generators/`.
Allow conversion of blocks and generators to TypeScript.
Changes untested so far; leaving this PR as a draft until I've verified that everything actually works as expected.

feat(build): Run `tsc` on `blocks/` and `generators/`

---

core/block.ts
core/serialization/blocks.ts
tests/mocha/serializer_test.js

Work on #6807
Serializes disabled interactions in the built-in JSON serializer.
This fixes undo and redo for deleting immovable and ineditable blocks.
Added tests for round-tripping the disabled properties from XML -> Workspace -> JSON -> Workspace -> XML
N/A
Next step is to work on deprecating the plugin.

fix: serializing disabled interactions

---

core/block.ts
core/block_svg.ts
core/connection.ts
core/events/events_block_move.ts
core/field_angle.ts
core/inject.ts
core/keyboard_nav/ast_node.ts
core/names.ts
core/theme_manager.ts
core/xml.ts
tests/mocha/workspace_svg_test.js

Part of #5857
Replaces various uses of AnyDuringMigration with accurate type information.

refactor: Remove more uses of AnyDuringMigration

---

core/block_dragger.ts
core/block_svg.ts
core/insertion_marker_manager.ts
core/render_management.ts
core/rendered_connection.ts

Fixes #6130 
Work on #6786 
Adds a render queue that is used to delay / batch block rerendering.
5x performance improvement!
Only manual testing.
N/A
There are some things in core that need blocks to be rendered immediately. E.g. flyouts need blocks to render immediately so that they can then be positioned. So I only converted dragging / connecting / disconnecting to use the queue, and we can convert other things over time.
This did run into some problems with the connection database, because rendering blocks after a delay means their connections have moved a bit before the normal call to `tighten` happens. Which is why we need to `updateConnectionLocations` on all blocks, even the ones that haven't been rendered. So we might need to pull this change out if it causes other unfound …

feat: add basic render queueing

---

core/block_svg.ts
core/render_management.ts
core/rendered_connection.ts

Works on #6786 as a follow up to #6851 
Separates out updating connection locations into a separate pass, specifically when using the render queue (normal immediate rendering is unaffected).
This means that we are no longer recursively moving all of the child blocks every time we tighten a parent block (which was causing us to do a lot of duplicate work adding and removing things from the connection db). It also eliminates a heck-ton of calls to `getRelativeToSurfaceXY`, which is a pretty expensive function.
This makes rerendering ~ 2.5x faster when you're moving a bunch of connections. E.g. when you're wrapping a new if-block around the spaghetti stress test blocks.
Just manual testing =(
N/A
Dependent on #6851

fix: updating connections in the db multiple times

---

core/insertion_marker_manager.ts

Fixes  #6839
#5722 introduced logic to update the available connections (and marker block) for a block being dragged as it was being dragged in order to make the marker block reflect changes to the connections of the block being dragged that happened during the drag. The insertion marker corresponding the first block in the stack being dragged was only regenerated when (a) it was shown and (b) its connections were inconsistent with those on the corresponding insertion marker block. However, the insertion marker corresponding to the last block in the stack was recreated every time the drag moved. This PR updates the insertion marker manager to only create the insertion marker block corresponding to the last block in the stack being dragged (a) at the beginning of the drag and (b) in the …

fix: Don't repeatedly recreate the last marker block during a drag.

---

core/blockly.ts
core/field.ts
core/field_angle.ts
core/field_checkbox.ts
core/field_colour.ts
core/field_dropdown.ts
core/field_input.ts
core/field_multilineinput.ts
core/field_number.ts
core/field_textinput.ts
core/field_variable.ts

Re-export Field types from Blockly
fixes #6870
- Adds `FieldDropdownConfig` export
- Imports then re-exports `Field{Name}Config` and `Field{Name}FromJsonConfig` types from `./core/blockly.ts`
- Config exports were not re-exported in `./core/blockly.ts`
- Config exports are re-exported in `./core/blockly.ts`
- To make the included types available in the root export for Blockly
N/A
N/A
- `FieldDropdownConfig` is just a re-export of `FieldConfig`. Should we include this?
- We currently have `FieldTextInputConfig` as a re-export of `FieldInputConfig` already, though the base `FieldInputConfig` isn't actually exported since `FieldInput` is only used internally
- **Note:** As mentioned above, the base `FieldInput` types aren't exported. It is not a registered field since it was created for …

fix: export Field-related types from Blockly

---

core/block_svg.ts
core/field.ts
core/input.ts
tests/mocha/block_test.js
tests/mocha/blocks/procedures_test.js
tests/mocha/field_checkbox_test.js
tests/mocha/input_test.js

Fixes N/A
Related to #6786 
Updates methods related to collapsing to use the `queueRender` method instead of `render`.
Changes `bumpNeighbours` to always queue a bump, instead of bumping immediately.
Performance and performance.
Only manual testing :/
Dependent on #6859

fix: improve collapse / uncollapse performance

---

core/block_svg.ts
core/input.ts
tests/mocha/block_test.js

Fixes #6786
Changes remaining calls to `render` that can be changed to `renderQueue` to `renderQueue`. (in conjunction with #6860 )
Performance!
N/A
N/A
N/A

fix: improve performance of modifying block shape

---

core/serialization/procedures.ts

Fixes N/A
Makes it so that ifthere are no procedure models in the workspace the procedure serializer returns null.
Workspaces without procedure models would be serialized as:
```
{
'procedures': [],
}
```
Workspaces without procedure models are serialized as:
```
{ }
```
The tiniest amount of space saving.
N/A
N/A
N/A

fix: empty procedure arrays in serialization

---

core/block.ts

Fixes #4229 
Increases peformance of `toString` 50x. Used to take ~50ms, now takes <1ms.
Speeeeed.
Just manual testing.
N/A
N/A

fix: toString performance

---

core/any_aliases.ts

Add missing copyright notice to `core/any_aliases.ts`.
Missing licence tag causes presubmit failure when updating Blockly in third_party.

chore: Add required @license tag to any_aliases.ts

---

core/block_svg.ts
core/connection.ts
core/contextmenu.ts
core/insertion_marker_manager.ts
core/rendered_connection.ts
tests/mocha/block_test.js

Related to #6130 
Optimizes the performance of connecting blocks by:
* Removing unnessary calls to `updateDisabled`
* Only setting the parent once (when connecting) instead of twice (when connecting and disconnecting)
Cuts off ~100ms from wrapping an if block around the spaghetti code test blocks.
Only manual testing :/
N/A
Dependent on #6860

fix: improve performance of connecting blocks

---

core/block.ts
core/block_animations.ts
core/block_svg.ts
core/connection.ts
core/field.ts
core/icon.ts
core/tooltip.ts
tests/mocha/connection_checker_test.js
tests/mocha/event_block_delete_test.js
tests/mocha/serializer_test.js

Fixes #6890 
Improves performance of deleting blocks.
See #6890 for previous performance. The new performance is ~300ms total, and ~100ms for `checkAndDelete`.
Speeeed
Manual testing + fixing failing tests.
Added one test to check that blocks do not receive their own delete events.
N/A
We save an extra 20ms after #6876 is merged.
Best to review this commit-wise since there is some code reorganization.

fix: dispose performance

---

blocks/math.ts

Part of #6828.
The types are not completely finalised, in particular because `BlockDefinition` is defined as `AnyDuringMigration`, and so it has been necessary in a few places to use `.!` and/or `as AnyDuringMigration`.  Hopefully it will be possible to address these in a future PR.

refactor(blocks): Migrate `blocks/math.js` to TypeScript

---

core/menu.ts

Fixes #6759
The menu item selection handler is triggered on pointerup vs down.
Attempting to scroll a menu on mobile would select the item that was tapped to initiate the scroll.
Menus can be scrolled as expected, and tapping an item selects it.

fix: Fix scrolling of menus on mobile.

---

core/field_dropdown.ts

Fixes #4465 
Makes it so that dropdowns actually scroll to the selected element.
Setting the highlight would normally scroll the menu. However, when a menu is in the dropdown div, it isn't actually scrollable. The dropdown div /content/ is scrollable. So we need to trigger a scroll of that separately.
Just manual testing.
N/A
N/A

fix: scrolling dropdown items into view

---

core/events/utils.ts

Discovered that flyouts were not being resized when blocks changed size (e.g. changing field values) during investigation of #4086 This was caused by #6860 
Makes it so that events are always fired after the current frame finishes drawing. This ensures that all blocks have been rendered and their dimensions, positions, connection positions, etc are all updated before event listeners are triggered.
Event listeners would be working with info that wasn't up to date because they were triggered too early.
Just manual testing.
N/A
This fixes a regression and should go in before the release.

fix: flyouts resizing for blocks

---

core/flyout_base.ts
tests/playground.html

Fixes #4443
Stops mutating the toolbox definition when parsing dynamic categories.
See explanation in #4443 
Can add unit testing after we confirm this is the behavior we actually want.
N/A
Do we actually want flyout toolboxes to parse the dynamic categories? I kind of understand it in that you might want to embed variables / procedures in your flyout toolbox. But it also just seems.... weird?
Just want to confirm this before adding unit tests / merging.

fix: overwriting flyout def with dynamic categories

---

core/rendered_connection.ts

Aaron discovered an issue with the ternary block during testing, where blocks couldn't be connected to it. Turns out that some connection locations weren't being added to the db due to the `moved` check. I'm not sure why this is occuring, so I'm just removing it for now. This does give us a performance hit of ~20ms when moving spaghetti blocks around. But it's still ~5x faster than on master so nbd.
Fixes regression where connections weren't being added to the db.
Regressions are sad.
N/A
Going to create an issue for reverting this now that I've created this PR.
This is release blocking.

fix: connection locations not updating

---

core/field_input.ts

Pressing Escape while editing a text field does nothing.
Pressing Escape cancels the edit and reverts the field to its previous value.

fix: Make Escape cancel changes in text fields.

---

core/mutator.ts

Fixes #4086 
Adds a listener to the flyout so that changes to the flyout resize the workspace as well.
Fixin buggies.
Manual testing with https://github.com/google/blockly-samples/pull/1638
N/A
N/A

fix: mutator not resizing for flyout

---

scripts/gulpfiles/package_tasks.js

Temporarily exclude the generated `.d.ts` files for `blocks/*` and `generators/*` from the package.
Generated `.d.ts` files were copied from `build/declarations/blocks/` and `…/generators/` into `dist/`, and thus included in the published package.
They are not copied or included.
These files will in due course replace the (very simplistic) hand-written versions in `typings/`, but for now they are not referenced anywhere a developer's tooling should be looking, and contain in some cases actually incorrect typings (e.g., in unmigrated blocks files, the `blocks` export is typed as `ObjectConstructor`, which is wrong).
Untested.

chore(build): Temporarily exclude blocks and generators .d.ts files

---

core/mutator.ts

Fixes #3511 
Fixes #6953 
Work on #4288 
Removes the batch rendering from the mutator logic - since we now have actual batch rendering that doesn't rely on mangling the `rendered` property!
Code simplification.
Manually tested that #4175 and #3458 do not reproduce.
Tested that mutating continues to work.
N/A
While I do trust this code, I don't trust it enough to put it into the imminently approaching release. So I'm going to put this up as a draft.

fix: remove forced rerender from mutator

---

core/block_dragger.ts

Fixes #6945
Makes it so that block move events are not fired if a block was disposed during a drag.
Because of how disposing was rearranged during https://github.com/google/blockly/pull/6894 the block got removed from the workspace's list of blocks before the gesture was canceled. This meant that when the move event tried to find the block, it couldn't.
N/A
1) I don't /think/ there are any other cases where this should be a problem. But if something like this comes up again we should look at rearranging the dispose order again.
2) Did not look into why this was *not* causing problems for drag targets (e.g. the trashcan) ¯\\\_(ツ)_/¯
3) This should probably go into tomorrow's patch as well.

fix: disposing during dragging

---

core/trashcan.ts
tests/mocha/comment_deserialization_test.js
tests/mocha/trashcan_test.js

Part of #6548
Remove underscores from private property and method names. Fix uses in tests. Note that the tests are still accessing private properties. I decided not to add getters that would only exist for tests.
Stop setting properties to `null` in `dispose` when not needed.
No change
Match current google style guide.

chore: remove underscores from properties and methods in trashcan

---

core/flyout_base.ts
core/flyout_button.ts
core/flyout_horizontal.ts
core/flyout_vertical.ts
tests/mocha/flyout_test.js

Remove underscores from private property and method names. Fix uses in tests. Note that the tests are still accessing private properties. I decided not to add getters that would only exist for tests.
Hopefully this makes later extraction of flyouts easier.

chore: remove underscores from private properties and methods for flyout

---

core/blockly.ts
core/inject.ts
core/theme/classic.ts

Part of #5857
Removes uses of AnyDuringMigration and replaces them with correct type information.

refactor: Remove some more uses of AnyDuringMigration.

---

core/connection.ts
core/connection_db.ts
core/rendered_connection.ts
tests/mocha/block_test.js
tests/mocha/blocks/logic_ternary_test.js
tests/mocha/connection_db_test.js

Part of #6548
Remove underscores from private property and method names. Fix uses in tests. Note that the tests are still accessing private properties. I decided not to add getters that would only exist for tests.
Stop setting properties to `null` in `dispose` when not needed.
No change
Match current google style guide.

chore: remove underscores from private properties and methods in connections

---

core/keyboard_nav/ast_node.ts
core/keyboard_nav/basic_cursor.ts
core/keyboard_nav/marker.ts
core/renderers/common/constants.ts
core/renderers/common/marker_svg.ts
core/renderers/geras/highlighter.ts
core/renderers/geras/renderer.ts
core/renderers/zelos/constants.ts
core/renderers/zelos/info.ts
core/renderers/zelos/marker_svg.ts
core/renderers/zelos/path_object.ts
tests/mocha/astnode_test.js
tests/mocha/cursor_test.js

Remove underscores from private property and method names. Fix uses in tests. Note that the tests are still accessing private properties. I decided not to add getters that would only exist for tests.

chore: remove underscores from private properties and methods in keyboard nav and rendering

---

core/field_checkbox.ts
core/field_dropdown.ts
core/field_image.ts
core/field_label.ts
core/field_number.ts
tests/mocha/field_image_test.js

Remove underscores from private property and method names. Fix uses in tests. In some cases, update tests to use existing getters.

chore: remove underscores from private properties and methods in some fields

---

core/inject.ts
core/utils/dom.ts
core/workspace_svg.ts

The 'compareDocumentPosition' call was inherited from Closure Library, in order to work with IE 8 and earlier.  Use the more modern 'contains' call instead.
This change was originally added here:
https://github.com/google/blockly/pull/1991
Remove the DOCUMENT_POSITION_CONTAINED_BY constant which is not a NodeType and should never have been part of that enum.
This change was originally added here:
https://github.com/google/blockly/pull/2736

chore: 'compareDocumentPosition' to 'contains'

---

core/utils/xml.ts
tests/mocha/serializer_test.js
tests/mocha/xml_test.js

Fixes #4590 
Makes it so that non-printable characters are properly escaped when serializing to XML, and that we do best-effort parsing when deserializing unescaped characters.
App Inventor needs this to be pulled into core for them to be able to update.
Unit tests for serializing and deserializing.
N/A
N/A

fix: non-printable characters in XML

---

blocks/lists.ts

refactor(blocks): Migrate `blocks/lists.js` to TypeScript

---

blocks/loops.ts

Part of #6828 
Migrates loop blocks, following the examples in #6900 and #6901

refactor(blocks): Migrate `blocks/loops.js` to TypeScript

---

.eslintrc.js
.github/workflows/build.yml
package-lock.json
package.json

* Update the test matrix to include node.js v20.
* Update some dependencies for (nominal) compatibility with the new version of node.
Test run on node.js v14, 16, and 18.
Test run on node.js v14, 16, 18 and 20.
Ensure that we are compatible with the most recent LTS version of node.js.
Yes, that's the idea.
I'm going to leave v14 in our test matrix for the moment; I'll remove it in a separate PR along with some other related updates.

chore(tests): Update configuration to test on node.js v20

---

core/insertion_marker_manager.ts

Fixes #7002 
Reverts reordering hiding and connecting. It is more efficient to connect "on top" of another connection, because then we can avoid setting the block's parent element twice. But this only saves ~12ms from wrapping an `if` around the spaghetti blocks. So I think correctness is better in this case.
Just manual testing.
N/A
Broken by https://github.com/google/blockly/pull/6876

fix: insertion markers firing move events

---

core/block.ts
core/input.ts
core/input_types.ts
core/registry.ts
tests/mocha/block_json_test.js

Work on #2062 
Adds an `appendInput` function, and support for constructing inputs from the registry.
Support for custon inputs!
Added a test for constructing custom inputs from JSON.
N/A
I reorganized some tests. Relevant changes are in commit 3e6db57 =)
I'd like to consider this the minimum viable API for handling custom inputs. It has several limitations:
* No `fromJson` method for constructing inputs, meaning custom inputs cannot be further parameterized when constructing from a JSON block definition.
* We force external developers to construct their own connections if they want them, which may be what we want, but signalling that by passing `null` to the connection constructor parameter is not ideal.
* Our built-in inputs are still differentiated using a `type` property, which …

feat: add support for appending custom inputs

---

core/renderers/zelos/drawer.ts

General cleanup: pull out some values in drawer code to avoid stacking ternaries too deeply.

chore: clean up some drawer code lint

---

blocks/loops.ts
blocks/variables.ts
blocks/variables_dynamic.ts
core/contextmenu.ts

Part of https://github.com/google/blockly/issues/6828

refactor(blocks): Migrate `blocks/variables.js` and  `blocks/variables_dynamic.js` to TypeScript

---

core/render_management.ts

Fixes #6999
Adds a step to the queued render process that updates the location of icons.
Elements of a block don't get to decide where they are positioned, but some of them (icons and connections) need to know where they're positioned. Before the code for updating icons was hidden inside `moveConnections` which was triggered via `renderedConnection.tighten`. Now it has been separated out so that it is clear what's happening.
Just manual testing =(
N/A
N/A

fix: icons not having their locations updated

---

core/field_variable.ts
tests/mocha/field_variable_test.js

Remove underscores from private property and method names. Fix uses in tests.

chore: remove private underscores in field_variable.ts

---

blocks/text.ts

refactor(blocks): Migrate `blocks/text.js` to TypeScript

---

core/gesture.ts
tests/mocha/gesture_test.js

Remove underscores from private property and method names. Fix uses in tests.

chore: remove private underscores in `gesture.ts`

---

core/toolbox/category.ts

The Aria level system starts with 1, but the variable 'this.level_' is zero-indexed and starts with 0, so be aware of this discrepancy when working with the code.
Fixes https://github.com/google/blockly/issues/7027
Increase aria-level to start with 1 instead of 0.
The aria-level starts with 0.
The aria-level starts with 1.
There are no aria-level with 0.
-
-
-
Refs: #7027

fix: Update category.ts to produce valid "aria-level" attributes

---

.github/workflows/build.yml

This formally ends our support for node.js v14.
Remove `14.x` from our node-version test matrix.
We run `npm test` on node.js v14 in CI.
We no longer test on v14, only v16, v18 and v20.
Node.js v14's LTS period has ended, and some of our dev dependencies no longer support it.  By dropping it as a test target we can update our dev dependencies to current versions.
Reduced.

chore(tests): Stop testing on node.js v14

---

core/field.ts
core/interfaces/i_has_bubble.ts
core/interfaces/i_icon.ts
core/interfaces/i_serializable.ts

Work on #7036 
Adds interfaces we need for defining icons.
Interfaces are how we keep the relationships between internal blockly code and external code clear =)
N/A These are just interfaces, no functionality.
N/A
N/A

feat: add IIcon interface, and related interfaces

---

blocks/procedures.js
core/block_svg.ts
core/flyout_horizontal.ts
core/flyout_vertical.ts
core/mutator.ts
core/rendered_connection.ts
core/workspace_svg.ts

Was looking at https://github.com/google/blockly/issues/6980 and realized it would be easier to document if we just have one rendering path rather than two :P So I'm looking at trying to get rid of the old one.
Looked through all of the remaining uses of `render` and switched any over to `queueRender` that could use `queueRender`.
Remaining uses of `render` after this PR include icons (because they need to know their locations immediately) and deserialization (because it's causing forced layouts that I need to investigate).
Unification of rendering paths.
Manual poking at things.
N/A - but soon! hopefully 🤞 
The plan for the icons is to add a function to the render management system that forces an immediate render of all queued renders.

fix: switch most remaining render calls to queueRender

---

core/events/utils.ts

Fixes #7026 
This PR filters events in a group prior to undoing them.
Events being undone were not filtered before being put onto the redo stack. If there were multiple events that needed to be merged, this can result in inconsistent changes on the undo and redo stacks.
During undo, events within a group are passed through the Event.utils.filter function so that any sequence of events that result in a no-op will be removed from the undo/redo stack.
The issue was appropriately described in #7026.
I ran `npm test` and all tests passed. However, we may want to add more tests to evaluate the specific sequence of events that lead to #7026.

fix: filter undone event groups before moving them to the redo stack

---

core/blockly.ts
core/icons.ts
core/icons/registry.ts
core/registry.ts
core/serialization/blocks.ts
core/serialization/exceptions.ts
core/serialization/registry.ts
tests/mocha/icon_test.js

Fixes #7062 
Adds the ability to register icons. Also adds the ability to serialize and deserialize them.
Sometimes you want icons to be serializable, so we should support that!
Added tests for serialization and deserialization.
N/A
Dependent on #7059

feat: add registering and serializing icons

---

core/serialization/blocks.ts

Makes props in ConnectionState optional, so that the [code in documentation](https://developers.google.com/blockly/guides/configure/web/toolbox#preset_blocks) works.
Previously, one had to specify both `block` and `shadow` and write `undefined` into one of them:
```typescript
{
"kind": "flyoutToolbox",
"contents": [
{
"kind": "block",
"type": "controls_for",
"inputs": {
"FROM": {
"block": {
"type": "math_number",
"fields": {
"NUM": 1
},
"shadow": undefined, // error if omitted
}
},
// ...
}
},
]
}
```
Now we can use the code written in the documentation:
```typescript
{
"kind": "flyoutToolbox",
"contents": [
{
"kind": "block",
"type": "controls_for",
"inputs": {
"FROM": {
"block": {
"type": "math_number",
"fields": {
"NUM": 1
}
}
},
// ...
}
},
]
}
```
This way it is both more convenient …

fix: Make props of ConnectionState optional

---

core/bubbles/bubble.ts

N/A
Fix typo.
Make blocks draggable.
Manually tested dragging by hacking the bubble into the warning icon.
N/A
N/A

fix: bubbles not being dragged

---

core/blockly.ts
core/bubbles/bubble.ts
core/bubbles/mini_workspace_bubble.ts
core/flyout_base.ts
core/mutator.ts
core/workspace.ts

Fixes #7045 
Adds a new kind of bubble which is a mini workspace bubble.
We want bubbles to be pure views with a object oriented structure. This works toward that =)
Manually tested by hacking into the warning icon. Looks the same as bubbles did previously.
This is the one I'm most nervous about since it has so much functionality that I can't test it all. But the simple case looks good! And I added validation to hopefully restrict peeps to those use cases.
If we want we can also mark the constructor `@internal` until we're more confident in it.
N/A

feat: mini workspace bubble

---

core/block_svg.ts
core/icons/icon.ts
core/interfaces/i_icon.ts
core/render_management.ts
core/renderers/common/drawer.ts
core/renderers/measurables/icon.ts
tests/mocha/block_test.js
tests/mocha/icon_test.js

Fixes #7098
Adds correctly calling the new icon hooks in a bunch of places.
Actually get the code to work for testing refactoring icons.
Enabling tests yay!
N/A
Two of the `initView` tests are still skipped because I need to fix #7099 first.

fix: work on calling icon hooks

---

core/block_svg.ts
core/gesture.ts
tests/mocha/icon_test.js

Fixes #7099 
Changes the gesture system to handle icon clicks.
Code consistency.
Enabled last block -> icon hook tests.
N/A
Dependent on #7100

fix: gestures handling icons

---

core/interfaces/i_has_bubble.ts
core/rendered_connection.ts
core/renderers/measurables/icon.ts
tests/mocha/block_test.js
tests/mocha/icon_test.js
tests/mocha/test_helpers/icon_mocks.js

Fixes N/A
Makes it so that you can collapse blocks whose children have icons.
Removing errors is good.
Manually tested. Might add unit tests for this before merging, since we can pretty easily check `bubbleIsVisible`.
N/A

fix: collapsing blocks with children with icons

---

core/block.ts
core/block_svg.ts
core/inputs/dummy_input.ts
core/inputs/input.ts
core/inputs/statement_input.ts
core/inputs/value_input.ts

Fixes #2062 
Makes it so that inputs must + can easily construct their own connections (for inputs that have connections).
Inputs were passed their connections, except for custom inputs which weren't. It was difficult for custom inputs to construct their own connections, because they had to deal with rendered vs headless.
All inputs must construct their own connections. They can easily do this using the `protected makeConnection` method.
This makes built-in inputs and custom inputs more consistent. It also makes custom inputs with connections easier to implement.
N/A
N/A
N/A

fix: have inputs construct connections

---

scripts/gulpfiles/build_tasks.js

Fixes #6864.
Look for `path.sep` instead of hard-coded `'/'` when parsing output of `closure-make-deps`.
`npm run minify` (and therefore `build`, `package`, etc.) fails on Windows.
Hopefully less failing.

fix(build): Fix path issue on Windows

---

core/inject.ts

Fixes an issue where a Blockly workspace cannot be injected into a yet-to-be-attached element.
Check whether the ownerDocument of the injection div is the current document if the initial check for containment fails (e.g., due to the element not having been append elsewhere to the DOM).
If a `div` is created and `inject` is called to create a workspace before that div has been attached, an error is thrown.
The check for membership in the document is made more permissive, so if the `div` is owned by the `document` it will still be used to create a workspace (to be attached at a later time).
In App Inventor, screens are separated into design and blocks, with the design being shown first. We must create a workspace and have it contain the blocks to participate in code generation, but the …

fix: Allow for unattached elements during inject call

---

core/icons/icon.ts

Fixes N/A
Has icons hide their bubble when the block is collapsed
Fixin buggies.
Manually tested collapsing with open bubbles.
N/A
N/A

chore: fix hiding bubbles on collapse

---

generators/javascript.js
generators/javascript/colour.js
generators/javascript/lists.js
generators/javascript/logic.js
generators/javascript/loops.js
generators/javascript/math.js
generators/javascript/procedures.js
generators/javascript/text.js
generators/javascript/variables.js
generators/javascript/variables_dynamic.js

First part of #7085.
* Introduce a `JavascriptGenerator` class to be the class of which `javascriptGenerator` is an instance (without any additional properties making it a singleton).
* Introduce an `Order` enum (for now Closure-style) for the operator precedence table.
* Don't rename `javascriptGenerator` to `JavaScript` in `generators/javascript/*.js`.
There should be no changes in behaviour.
See #7085.
Passes `npm test`; no changes to manual testing anticipated.
Documentation for the `JavascriptGenerator` class and `Order` enum should be automatically generated by our JSDoc configs (though if this is not currently the case then we should fix that).

refactor(generators): Introduce `JavascriptGenerator` class, `Order` enum

---

core/block.ts
core/block_svg.ts
core/events/events_block_change.ts
core/icons.ts
core/icons/comment_icon.ts
core/icons/icon.ts
core/icons/icon_types.ts
core/icons/mutator_icon.ts
core/icons/registry.ts
core/icons/warning_icon.ts
core/interfaces/i_icon.ts
core/serialization/blocks.ts
core/xml.ts
tests/mocha/block_test.js
tests/mocha/test_helpers/icon_mocks.js

Fixes #7126 
Has `getIcons` and other relevant methods use an generic `IconType<T>` class to reference/retrieve icons so that we return icons of the correct type.
Make typescript happy :D
Fixed tests.
N/A
N/A

feat: add types for accessing icons.

---

generators/dart.js
generators/dart/colour.js
generators/dart/lists.js
generators/dart/logic.js
generators/dart/loops.js
generators/dart/math.js
generators/dart/procedures.js
generators/dart/text.js
generators/dart/variables.js
generators/dart/variables_dynamic.js

Part of https://github.com/google/blockly/issues/7085.
Introduce a `DartGenerator` class to be the class of which `dartGenerator` is an instance (without any additional properties making it a singleton).
Introduce an `Order` enum (for now Closure-style) for the operator precedence table.
Don't rename `dartGenerator` to `Dart` in generators/javascript/*.js.
There should be no changes in behaviour.
See #7085.
Passes `npm test`; no changes to manual testing anticipated.
Documentation for the `DartGenerator` class and `Order` enum should be automatically generated by our JSDoc configs.

refactor(generators): Introduce `DartGenerator` class, `Order` enum

---

generators/python.js
generators/python/colour.js
generators/python/lists.js
generators/python/logic.js
generators/python/loops.js
generators/python/math.js
generators/python/procedures.js
generators/python/text.js
generators/python/variables.js
generators/python/variables_dynamic.js

Part of https://github.com/google/blockly/issues/7085.
Introduce a `PythonGenerator` class to be the class of which `pythonGenerator` is an instance (without any additional properties making it a singleton).
Introduce an `Order` enum (for now Closure-style) for the operator precedence table.
Don't rename `pythonGenerator` to `Python` in generators/python/*.js.
There should be no changes in behaviour.
See #7085.
Passes `npm test`; no changes to manual testing anticipated.
Documentation for the `PythonGenerator` class and `Order` enum should be automatically generated by our JSDoc configs.

refactor(generators): Introduce `PythonGenerator` class, `Order` enum

---

generators/lua.js
generators/lua/colour.js
generators/lua/lists.js
generators/lua/logic.js
generators/lua/loops.js
generators/lua/math.js
generators/lua/procedures.js
generators/lua/text.js
generators/lua/variables.js
generators/lua/variables_dynamic.js

Part of https://github.com/google/blockly/issues/7085.
Introduce a `LuaGenerator` class to be the class of which `luaGenerator` is an instance (without any additional properties making it a singleton).
Introduce an `Order` enum (for now Closure-style) for the operator precedence table.
Don't rename `luaGenerator` to `Lua` in generators/lua/*.js.
There should be no changes in behaviour.
See #7085.
Passes `npm test`; no changes to manual testing anticipated.
Documentation for the `LuaGenerator` class and `Order` enum should be automatically generated by our JSDoc configs.

refactor(generators): Introduce `LuaGenerator` class, `Order` enum

---

core/generator.ts
generators/dart.js
generators/javascript.js
generators/python.js

Addresses various nits that escaped previous PRs:
* Add TSDoc for `BlockGenerator` in `core/generator.ts` for PR #7150.
* Fix bad formating in `generators/javascript.js` from PR #7153.
* Add missing `@enum` tag that should have been included in PR #7160.
* Delete obsolete comment from `generators/python.js` for PR #7163.
Fixes #7085.

chore(generators): Fix nits

---

scripts/gulpfiles/build_tasks.js

Implements proposal 3 (option 3B) of #7086.
Previously, when loading a generator chunk (e.g., `javascript_compressed.js`) as a script (e.g., in a browser using a `<SCRIPT>` tag), only a single named export from that chunk would be made available (e.g, `javascriptGenerator` would be made available as `Blockly.JavaScript`).
Until recently, that was fine because each generator chunk had only a single named export, but now each one additionally has a `<Lang>Generator` class and `Order` enum export.  At present developers loading generator chunks as scripts have no way to access these additional named exports.
To allow these new exports to be accessed by script users, the chunk wrappers are modified to provide the whole export object at a correspondingly-named global variable—e.g., when loaded …

refactor(build)!: Provide all generator exports when loaded as script

---

blocks/logic.ts
blocks/text.ts

Where certain block mixin methods had been marked `@private`, and these annotations had been deleted while migrating the containing files to TypeScript, mark those methods as `@internal`.
These methods might have appeared in our `.d.ts` files and external documentation.
These methods should not appear in our `d.ts` files or external documentation.
The migration PRs were not intended to change any API.
Passes `npm test`.  No changes to manual testing required.
…may be sparser than before, intentionally.
I'm not actually sure if these methods appear in our external documentation at the moment—I'd guess not.   But better to keep it that way.

fix(blocks): Mark previously-`@private` methods `@internal`

---

blocks/procedures.ts

refactor(blocks): Migrate `blocks/procedures.js` to TypeScript

---

core/icons/mutator_icon.ts

Fixes N/A
Makes it possible for external developers to access the workspace of the mutator icon.
Found that this was access in samples, so there are use cases for accessing it.
N/A
N/A
N/A

chore: make MutatorIcon.prototype.getWorkspace public

---

tests/mocha/field_multilineinput_test.js
tests/mocha/generator_test.js

Part of #6858.
Migrate the two remaining uses of goog.require in the mocha tests from goog.require to import.
Trying to make it possible to get rid of `base.js`.

refactor(tests): Migrate mocha tests from `goog.require` to `import`

---

scripts/gulpfiles/build_tasks.js

Three separate mistakes left only the Python and PHP chunks with the correct code for the legacy script exports.
Fix typos
Only `python_compressed.js` and `php_compressed.js` had correct code for legacy exports (`Blockly.<Lang>`) in their UMD wrappers.
All five `<lang>_compressed.js` chunks get correct wrappers.
Don't want to break developer's code.
Output manually checked.

fix(build): Correct typos in PR #7169

---

demos/blockfactory/blocks.js

Fixes N/A
Properly passes the block to the mutator icon constructor in the block factory demos.
The block factory field blocks would cause console errors.
No Errors
The block factory should be usable!
N/A
Going to update the description of the mutator refactor PR to include info about needing to pass the block to the constructor. Previously passing the block was optional (even though it was not marked as optional).
N/A

fix: properly pass the block to the icon constructor in blockfactory blocks

---

core/block_svg.ts
tests/mocha/comment_deserialization_test.js
tests/mocha/contextmenu_items_test.js
tests/mocha/xml_test.js

Fixes #7164 
utilize `getIcon()` in preparation for v11
> The mocha tests are currently outputting deprecation warnings to the console because of calls to getCommentIcon. (https://github.com/google/blockly/issues/7164#issue-1757210807)
`npm run test:mocha:interactive` -> check console
Removed deprecation function, docstring, and dependencies from `block_svg.ts`
N/A

fix: Utilize getIcon instead of getCommentIcon in tests

---

demos/blockfactory/factory_utils.js

Update the BlockFactory block generator function stub generator to apply recent changes in generator function best practices:
- Use `<language>Genarator` instead of `Blockly.<Language>`.
- Put generator functions in the `.forBlock` dictionary.
- Accept (and use) a second `generator` argument that is the calling CodeGenerator object.
- User `Order.ATOMIC` enum instead of `.ORDER_ATOMIC`.
Also:
- Prefix (e.g.) `javascriptGenerator` and `Order` with `javascript.`.
- Use template literals where useful.
- DRY up all the non-special field stub code generation.
Ensure developer generator functions are as modern as possible.
I added `language.` prefix to places where the stub code references `langaugeGenerator` and `Order`, as is necessary when loading the generators as a script (e.g. via a …

fix(demos): Update BlockFactory generator stub generator

---

demos/code/code.js

Fixes errors in `Code.checkAllGeneratorFunctionsDefined` caused by the breaking change in PR #7150, implementing the `.forBlock` dictionary.
* Update the `demos/code/` demo to use the new import names (e.g. `BlocklyJavaScript` -> `javascript.javascriptGenerator`.
* Fix `Code.checkAllGeneratorFunctionsDefined` by having it use `.forBlocks` dictionary.
Code generation fails with dialog warning about missing generator functions.
Code generation works.
Keep code functional and up-to-date.
Manually tested.

fix(demos): Update code demo to use new script import names for generators

---

core/block.ts
core/block_svg.ts

See https://github.com/google/blockly/issues/3096 
This probably existed for implementing scratch-style dragging rules but is completely unused in core.
Delete unused function.
Not a breaking change because this function is `internal`.

chore: delete unused function getFirstStatementConnection

---

core/block_svg.ts

Delete an unused function on `blockSvg` that was probably used for drag surface transformations in the past. Not breaking because it's private.

chore: delete unused fuction clearTransformAttributes_

---

core/toolbox/collapsible_category.ts

Fixes #7174 
call `setVisible(isExpanded)` on the `parentToolbox_`'s flyout to update visibility
flyout is not closed when `setExpanded(false)` is called on `collapsible_category`, contrary to expected behavior
https://github.com/google/blockly/assets/70596906/cca9a332-7d9e-463f-9d78-aaf5569ead69
flyout is hidden along with collapsed category
https://github.com/google/blockly/assets/70596906/ccd9b5dd-9b33-46db-aea5-ab09296bd121
fulfilling expected behavior in every case
tested full functionality of expand/collapse by opening, switching, and unfocus clicking the flyout/collapsible regions before and after changes 
updated setExpanded` docstring

fix: set flyout visbility on calling setExpanded

---

core/main.js

Developer errors/confusion caused by the removal of `HSV_SATURATION` and `HSV_VALUE` by PR #7077 despite them not having previously been formally deprecated.
Restore these accessors but mark them as deprecated.
Reduce developer pain.
This was an undocumented and not-previously-promulgated change in Blockly v10.0.0.  If we do not revert (via this PR or similar) we should at least issue an errata to the release notes.
**DEPRECATION:** `Blockly.HSV_SATURATION` and `Blockly.HSV_VALUE` are deprecated and will be removed in a future version of Blockly.  Use `Blockly.colour.getHsvSaturation` / `Blockly.colour.setHsvSaturation` and `Blockly.colour.getHsvValue` / `Blockly.colour.setHsvValue` instead.

fix: Restore `HSV_SATURATION` and `HSV_VALUE` accessors and deprecate

---

tests/browser/test/procedure_test.js
tests/browser/test/test_setup.js

Fixes N/A
Adds helper methods for getting blocks from the flyout.

chore: add test helpers for getting blocks from the toolbox

---

core/rendered_connection.ts
core/utils/svg_math.ts
tests/browser/test/procedure_test.js
tests/browser/test/test_setup.js

Fixes https://github.com/google/blockly/issues/7227
Adds a test helper for connecting blocks together.
Also makes `getOffsetInBlock` public because I needed it.
Tested that the logic still worked with a scaled (aka zoomed) workspace!

chore: add test helpers for connecting blocks

---

tests/mocha/comment_deserialization_test.js
tests/mocha/contextmenu_items_test.js
tests/mocha/field_multilineinput_test.js
tests/mocha/generator_test.js
tests/mocha/xml_test.js

Addresses the cause of #7224 being filed, though without making more than a token effort to address the issue as written.
* Fix invalid `import` paths in mocha tests.  This resolves the warnings generated during `buildDeps` by
`closure-make-deps`.
* Fix failing context menu item test:
* The test appears to have been wrong: `Block.prototype.getIcon` is typed as
getIcon<T extends IIcon>(/* ... */): T | undefined
and documented as "@returns The icon with the given type if it exists on the block, undefined otherwise."
* Clean up inconsistent usage of `CommentIcon` in the test files touched by PR #7200 to be consistent with existing usage of `Blockly.icons.CommentIcon` instead of importing it separately.
* Scary (but apparently not sufficiently scary) warnings generated by `closure-make-deps` …

fix(tests): Make test `import`s correct and more consistent

---

core/zoom_controls.ts

Fixes N/A
Adds specific css classes to individual zoom controls. This allows external developers to style the zoom controls individually. It also allows us to easily reference individual zoom controls in automated UI tests.

chore: add css classes to individual zoom controls

---

core/workspace_comment_svg.ts
tests/mocha/workspace_comment_test.js

Fixes https://github.com/google/blockly/issues/7177
Makes it the sole responsibility of the WorkspaceComment superclass to mark the comment as disposed, instead of letting the subclass mark it as disposed before the superclass has a chance to handle disposing it.
The superclass's dispose method did not actually run, and the comment would not be completely disposed.
Deleting a comment now fully disposes it.
Previously there was test coverage for disposing WorkspaceComment, but not for disposing WorkspaceCommentSvg. I added a method testing the latter.

fix: disposing workspace comments.

---

tests/browser/test/basic_playground_test.js
tests/browser/test/procedure_test.js
tests/browser/test/test_setup.js

Adds tests for collapsing/expanding and disabling/enabling blocks through the right-click menu.
Adds a helper function to right-click on the given block and click on the menu item with the given text.
For now I'm just refreshing the browser at the beginning of each test to keep them hermetic, but that should happen in a `setup` function instead.

feat(tests): add right click tests and helpers

---

tests/browser/.eslintrc.json
tests/browser/test/test_setup.js

Fixes lack of jsdoc.
Change jsdoc rules for browser tests to not require types, because we don't have strong typing here (and do not intend to compile this code before running it).
Add jsdoc for functions in `test_helpers.js`.
No change in test behaviour.
Documentation!
These are tests.
This is documentation!
I think I got the promises right but would appreciate a double-check.

chore(tests): Add documentation to browser test helper functions

---

core/icons/mutator_icon.ts

Fixes https://github.com/google/blockly/issues/7288
Adds clearer error throwing to the mutator. Throws if necessary methods do not exist.
N/A Can add unit tests if desired.
N/A
N/A

fix: add compose and decompose errors to mutator icon

---

tests/browser/test/basic_block_factory_test.js
tests/browser/test/basic_block_test.js
tests/browser/test/basic_playground_test.js
tests/browser/test/block_undo_test.js
tests/browser/test/extensive_test.js
tests/browser/test/field_edits_test.js
tests/browser/test/procedure_test.js
tests/browser/test/test_setup.js

First part of #7274.
Implement the "Drag three blocks into the workspace and verify they are present" test.
Also:
* Refactor the `testSetup` helper to take a URL.
* Turn the `testFileLocations` enum into a URL dictionary.
* Add a `getAllBlocks` helper.
Slightly improved.

test: Basic Blocks: verify drag blocks works properly

---

core/generator.ts
generators/python/python_generator.js
typings/dart.d.ts
typings/javascript.d.ts
typings/lua.d.ts
typings/php.d.ts
typings/python.d.ts

Fixes #7283.
Also partially fixes google/blockly-samples#1785.
* Add missing declarations for `Order` enums to `typings/<language>.d.ts`. 
This is a temporary measure until the generators are converted to TypeScript and the `.d.ts` files can be autogenerated.)
* Remove the `protected` declaration on the `provideFunction_` method and `FUNCTION_NAME_PLACEHOLDER_` property on `CodeGenerator` so they can be used from generator functions written in TypeScript.
Previously generator functions were (ES5-style) methods on (Code)`Generator` instances, and Closure Compiler was apparently happy with this, but now these functions live in a separate dictionary and `tsc` is pickier.
It was not possible to write code generators in TypeScript that made use of `Order`, `provideFunction_` or …

fix(generators): Changes to exports and access controls for TypeScript compatibility

---

tests/browser/test/basic_playground_test.js
tests/browser/test/test_setup.js

Fixes #7277 
Adds tests for disabling blocks via the right click context menu.
Testing is great!
This is tests :P
N/A

chore: add tests for disabling blocks

---

core/generator.ts
core/main.js
generators/python/python_generator.js
package-lock.json
package.json
scripts/migration/renamings.json5
typings/dart.d.ts
typings/javascript.d.ts
typings/lua.d.ts
typings/php.d.ts
typings/python.d.ts

* fix(generators): Changes to exports and access controls for TypeScript compatibility (#7295)
* fix(generators): Add missing declarations for Order enums
* chore(generators): Remove spurious whitespace
* fix(generators): Make provideFunction_ etc. public
Remove the protected declaration on provideFunction_ and
FUNCTION_NAME_PLACEHOLDER_ so they can be used from generator
functions written in TypeScript.
Not strictly part of #7283, but closely related and required to
fixing the related issue google/blockly-samples#1785.
* chore(generators): format
(cherry picked from commit d503fbb409e58d80a3a4db89ec603532505e8663)
* fix: Correct errors in `HSV_SATURATION`, `HSV_VALUE` accessors (#7297)
* fix: Correct errors in HSV_SATURATION, HSV_VALUE accessors
Fix the comment / message errors noted in …

release: merge master back into develop for v10.0.2 release

---

tests/browser/test/test_setup.js

fix: Add delay after block connection.  Otherwise it can randomly and silently fail.

feat: Allow dragging from simple toolbox

---

core/block_svg.ts
core/render_management.ts
tests/mocha/block_test.js

Work on #7068 
1) Adds a new method to the render management system to immediately trigger any queued renders. This should only be used in cases where it's necessary for backwards compatibility (like this one).
2) Switches icon methods over to use the render management system (with the immediate trigger).
3) Adds dummy promises to the return value of all `setBubbleVisible` methods.
1) We need adding icons to trigger a render immediately so that if the bubbles are set to be visible immediately, they are positioned correctly. Eventually we want to move this to be promises-based (so setting the visibility will wait for any queued renders to finish first). But that is a breaking change.
2) This gets us one step closer to tearing out the old render management system.
3) This makes it easier …

fix: have icons use the new render management system

---

tests/browser/test/.mocharc.js
tests/browser/test/basic_block_test.js
tests/browser/test/basic_playground_test.js
tests/browser/test/test_setup.js

- Change offset math to offset by a fixed amount from top-left, rather than a percent
- Use correct input for one of the tests (`DO0` instead of `IF0`)
- Use a different category for one of the drag tests, because one of the blocks in the category was broken. That broken block is also fixed in a different PR/set of PRs.
- Switched from the 'landing' reporter, which the mocha documentation calls a 'gimmick', to one that prints the names of tests to the console as it runs.
Tests worked for Beka but not for me
Hopefully tests work for everyone

fix(tests): fix broken browser tests

---

core/connection.ts
core/contextmenu.ts
core/flyout_base.ts
core/serialization/blocks.ts
core/workspace_svg.ts
core/xml.ts
tests/mocha/flyout_test.js

Fixes #7290 
Changed both the JSON and XML deserialization systems to use the render queue, but trigger an immediate render.
Moving both sytems to use the render queue allows us to get rid of the old render management system. But I chose to make them trigger an immediate render (instead of waiting until the end of the frame) to ensure 100% backwards compatibility.
We could have people use the `finishQueuedRenders` method if they want to calculate things based on the size/position of the blocks after deserialization. However, as we discovered last time I was reorganizing stuff, that's technically a breaking change :/ And I think deserialization is a much more high-risk area for this kind of thing! (as opposed to like, adding an input to a block).
* Verified that there is no performance …

fix: make deserialization use the new render management system

---

core/insertion_marker_manager.ts
core/workspace_svg.ts

Fixes N/A
Makes is so that insertion markers use the new render management system.
Necessary for tearing out the ~new~ old render management system.
Manually tested that insertion markers appear and look correct.
N/A
Dependent on https://github.com/google/blockly/pull/7296

fix: make insertion markers use new render management system

---

core/block_svg.ts
core/flyout_base.ts
core/workspace_svg.ts
core/xml.ts

Fixes N/A
Removes the last vestiges of the old render management system.
Less variants! 
All tests pass. Smoke tested the playground and it looks good!
Also tested that hiding and showing the workspace works properly.
N/A
Dependent on https://github.com/google/blockly/pull/7306 and https://github.com/google/blockly/pull/7307

fix: remove old `render` method

---

core/scrollbar.ts
core/scrollbar_pair.ts

Fixes https://github.com/google/blockly/issues/6971
Adds a method to toggle the visibility of a scrollbar pair.
App inventor needs this to reduce clutter when opening flyouts.
Manually tested that setting the scrollbar visibility hides the scrollbars.
N/A
I thought about solving this in a bunch of different ways, but the only one that ended up working was adding the internal `setVisible` method.
Removing the `this.pair` check alone doesn't work because external devs can access the individual scrollbars and try to mess with them, so we will run into the corner-error that the comment references. And we can't fix that by by telling the scrollbar pair to update itself when an individual scrollbar gets hidden, because having a reference to the scrollbar pair would cause circular dependencies.

feat: add the ability to toggle scrollbar visibility

---

tests/generators/unittest_dart.js
tests/generators/unittest_javascript.js
tests/generators/unittest_lua.js
tests/generators/unittest_php.js
tests/generators/unittest_python.js

Fixes https://github.com/google/blockly/issues/7303
- Update how per-block generators are defined to use `forBlock`, as described in https://github.com/google/blockly/pull/7150
- Move the `defineAssert` functions off the `unittest_main` generator objects, and make sure their names don't collide when loaded in the same page.
Lots of deprecation warnings, but everything works.
No deprecation warnings, and everything still works.
Respond to deprecation.

chore(tests): update generator test blocks to use forBlock

---

package.json
tests/browser/.mocharc.js

Fixes difficulties with running individual tests via `npx mocha path/to/test_file.js`
Move `tests/browser/test/.mocharc.js` to `tests/browser` and use `__dirname` to make the `require` directive work regardless of where `mocha` is invoked from.
Simplify the `browser:test` script accordingly, taking advantage also of the mocha default of running all tests in the `test/` subdirectory.
It was necessary to be in the repository root, and specify `--config tests/browser/test/.mocharc.js` in order to successfully invoke `mocha` on any/all of the files in `tests/browser/test`.
The previous way works, but it's also possible to `npx mocha path/to/test_file.js` from anywhere in `browser/tests/`
Convenience when developing tests.
Unchanged.

fix(tests): Make `.mocharc.js` independent of current working directory

---

core/clipboard/block_paster.ts
core/clipboard/workspace_comment_paster.ts
core/interfaces/i_paster.ts

Fixes #7336 
Add an IPaster interface and pasters for blocks and workspace comments.
Work toward having separate pasters for separate objects so that we can easily add new pastable objects.
N/A - This is just using the serialization system so no need to test it separately. I'll add tests for the integration between the clipboard and the pasters when I get to that point! (I.e. to make sure the correct APIs are getting called).
N/A
Currently these are not actually used anywhere :P I'm going to wire them in in a future PR.

feat: add basic pasters

---

blocks/variables_dynamic.ts
core/rendered_connection.ts

Fixes https://github.com/google/blockly/issues/7334
I think it's a bug 🤔️
Is there a better way than rerender?

fix(blocks): boolean variable block wrong shape for zelos

---

core/block_svg.ts
core/clipboard.ts
core/clipboard/block_paster.ts
core/clipboard/registry.ts
core/clipboard/workspace_comment_paster.ts
core/interfaces/i_copyable.ts
core/interfaces/i_paster.ts
core/registry.ts
core/workspace_comment_svg.ts

Work on #7337 
Changes the `CopyData` interface to `ICopyData` and changes it to only require the `paster: string;` property.
Updates everything using this type/downstream APIs to conform to the new interface.
Working toward more flexible copy pasting.
Should be covered by existing tests!
N/A
Best to review commit-wise due to renames =)

fix: refactor CopyData interface to have the correct structure

---

package.json
scripts/gulpfiles/build_tasks.js

#6864 and #7097 
Fixes 
Make building process compatible with machines run on windows. 
When running `npm run start` errors occur as described in the bug reports above.
Running `npm run start` is working with no errors on Windows.
Help developers who work on Windows machines to run blocky locally and potentially contribute to the codebase.
I did not create any tests. I tested the code on my Windows machine. 
I don't think any further documentation required for this change. Current documentation already asks users to run `npm run start`. The user does not need to do anything specific on Windows machines.
No

fix(build): support running Blocky locally on Windows machines

---

tests/browser/test/basic_playground_test.js
tests/browser/test/block_undo_test.js
tests/browser/test/extensive_test.js
tests/browser/test/field_edits_test.js
tests/browser/test/test_setup.js
tests/browser/test/toolbox_drag_test.js

Closes #7327 
Closes #7347 
Closes #7346
In order of commits:
- Test cleanup: use helpers
- Test cleanup: miscellaneous
- Format
- Add test to drag out every block from the toolbox, with associated helpers
- Make toolbox drag tests work in RTL
- Lint
The toolbox drag tests open every category in the basic toolbox and test blocks toolbox, and drag out every (non-disabled) block.
**These tests take a long time (>100 seconds for the test blocks ones) so I have set them to be skipped right now.**
The verification step simply checks whether there is a single top block on the workspace after the drag. As written, these tests will tell us about some catastrophic failures but won't guarantee that everything about block initialization works. Having a human watch the tests, with `PAUSE_TIME` set to …

chore(tests): cleanup and toolbox drag tests

---

core/block_svg.ts
core/blockly.ts
core/clipboard.ts
core/clipboard/registry.ts
core/common.ts
core/interfaces/i_copyable.ts
core/interfaces/i_paster.ts
core/registry.ts
core/shortcut_items.ts
core/workspace_comment_svg.ts
core/workspace_svg.ts
tests/mocha/clipboard_test.js
tests/mocha/index.html

Fixes #7337
* Updates the `ICopyable` interface to be generic.
* Updates the `clipboard` APIs to take in data instead of being stateful.
* Makes `paste` public. Everything else remains internal.
* More informative typing.
* State is the worst.
* Necessary if we want people to paste things by passing in data.
Now that the methods aren't stateful anymore, I could test the API boundary between the clipboard and pasters :D
N/A
N/A
`Blockly.clipboard.copy` and `Blockly.clipboard.duplicate` have both been deprecated. These were marked `@internal` so if you are conforming to Blockly's API, you should not be accessing them anyway.
`Blockly.clipboard.copy` can be replaced with calling `toCopyData` on the element you want to copy.
`Blockly.clipboard.duplicate` can be replaced by calling …

feat: make ICopyable generic and update clipboard APIs

---

core/flyout_horizontal.ts
core/flyout_vertical.ts
core/utils/toolbox.ts

- Fixes #6280 
The [BlockInfo type](https://github.com/google/blockly/blob/fa58cbaaf7456ab227c2214af5dd0e7025dc731c/core/utils/toolbox.ts#L19) should be updated to not include X and Y.
Blockly has two kinds of flyouts built-in, horizontal and vertical. You should update the layout logic in both of them.
The flyouts should be changed to use [moveTo](https://github.com/google/blockly/blob/fa58cbaaf7456ab227c2214af5dd0e7025dc731c/core/block_svg.ts#L414) [instead of moveBy](https://github.com/google/blockly/blob/61322294da70c770b32abb28b9d695af75f61a16/core/flyout_vertical.js#L250)
The `BlockInfo type` was picking up the values of `x` and `y` henceforth the position of the Toolbox Element was getting changed.
After removing the `X` and `Y` from the `BlockInfo type` the Toolbox Element is now …

fix: removed X & Y from toolbox.ts and replaced movBy to moveTo

---

core/trashcan.ts

Fixes N/A
Related to https://github.com/google/blockly-samples/issues/1841
Temporarily hide the scrollbars in the main workspace while the trashcan flyout is open.
Having multiple sets of overlapping scrollbars is confusing to users.
Manually tested that scrollbars are hidden.
N/A
N/A

feat: have the trashcan hide scrollbars when the flyout opens

---

appengine/storage.py

Glockenspiel broke due to 'query' now being required within a client context.  This change fixed Glockenspiel.  Blockly samples doesn't appear to be broken yet, but Glockenspiel broke at midnight yesterday.
Similar change being made to Blockly Games.
google.cloud.ndb.exceptions.ContextError
No current context. NDB calls must be made in context established by google.cloud.ndb.Client.context.
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 271, in handle keepalive = self.handle_request(req, conn) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request respiter = self.wsgi(environ, resp.start_response) File "/srv/main.py", line 42, in app …

fix: Preemptively fix API change in NDB.

---

core/block_svg.ts
core/workspace_svg.ts

Fixes N/A
Dedeprecates `render` on the block and workspace.
See here: https://github.com/google/blockly/pull/7355#issuecomment-1666203356
N/A
N/A
N/A

fix: dedeprecate render functions

---

core/insertion_marker_manager.ts

- Fixes #7316 
Change the insertion marker `createMarkerBlock` code over to use **JSON serialization and deserialization**.
In Blockly's XML serialization, child blocks are represented using nested XML elements. This means that if a block has child blocks connected to it, those child blocks will be represented as nested XML elements within the XML element representing the parent block. The structure of the XML serialization mirrors the structure of the blocks in the workspace.
The JSON serialization system in Blockly does something similar, but with a JSON structure instead of XML. The structure of the serialized data, whether XML or JSON, is designed to capture the hierarchical relationships between blocks and their connections.
Insertion markers duplicate the block being dragged, and …

feat: Insertion marker json deserialization 7316

---

core/clipboard/block_paster.ts
core/clipboard/workspace_comment_paster.ts
core/serialization/blocks.ts
core/workspace_svg.ts
tests/mocha/clipboard_test.js
tests/mocha/test_helpers/events.js

Fixes N/A
Adds logic to bump pasted blocks out of the way of other blocks.
Adds logic to bump pasted comments out of the way of their original comment.
Pasting blocks directly on top of other blocks or within the snap radius of other connections is confusing to the end user.
Added a test to make sure block create events are being fired.
Added tests to make sure the bumping is working correctly.
N/A
Dependent on #7348

fix: bumping copied objects

---

core/contextmenu.ts
core/contextmenu_items.ts
core/shortcut_items.ts
core/shortcut_registry.ts
tests/mocha/contextmenu_items_test.js
tests/mocha/keydown_test.js

Fixes #7338 
Upgrades keyboard shortcuts and context menu items to use `toCopyData` instead of `copy` and `duplicate`
Deprecation warnings are sad :/
Manually tested that copying, pasting, cutting, and duplicating works for blocks and workspace comments.
Workspace comments only support duplicating.
N/A
Dependent on #7349

chore: upgrade keyboard shortcuts and context menus to use non-deprecated APIs

---

core/renderers/common/block_rendering.ts

- Fixes #7286 
Export the shape interfaces defined in the ConstantProvider file from blockRendering, or the relevant namespace (geras, zelos) for the given renderer.
External developers have to look at the source code to see what values they should return from custom rendering methods.
After this change the External developers do not have to look at the source code for returning the custom rendering methods.
As the types related to shapes (e.g. `BasicShape`, `StartHat`, `Notch`, `PuzzleTab`) are not exported from `Blockly.blockRendering` which was making the bad developing experience for the external developers.

feat: Export shape interfaces from ConstantProvider

---

core/insertion_marker_manager.ts

Fixes #7383 (Ignore the reasoning there, as I had no idea what caused this at the time when I opened that issue)
Address issues in PR #7364
Don't add next block to the insertion marker when we do an insertion marker json serialization.
Also, to keep consistent with the old behavior, we don't need to add input blocks for the insertion marker.
And we don't need to do a full serialization here as it will just become an insertion marker.
The insertion marker's next blocks are real blocks and can get connected to the statements stack.
[Screencast from 2023-08-13 02-42-30.webm](https://github.com/google/blockly/assets/43995067/071fa480-bebd-4b63-9f99-719961b03b53)
Everything returned to normal, just like the old behavior.
To fix the problem.
N/A
N/A
N/A

fix: insertion marker's next blocks are real blocks

---

core/workspace_svg.ts

Fixes N/A
Deprecates the `paste` function on the workspace.
This function is not maintainable. It is hard coded to deserialize block data and workspace comment data. It cannot be backwards compatibily updated to use the new paster system, because it doesn't takes in the save state instead of the `CopyData` directly.
I see no reason to maintain this when we have better functionality in `clipboard.paste`.
For now it will continue to work as it did before (no breaking changes). But it will be deleted in v12.
N/A This is just a deprecation :P
N/A
N/A

deprecate: workspace paste

---

scripts/gulpfiles/build_tasks.js

Fixes error when loading playgrounds.
Have dependent chunks import `blockly.loader.mjs` instead of `blockly.mjs`.
Trying to load playgrounds gives console error:
```
GET http://127.0.0.1:8080/build/blockly.mjs net::ERR_ABORTED 404 (Not Found)               javascript.loader.mjs:2
```
Loading playgrounds works correctly.
In PR #7380 [it was suggested](https://github.com/google/blockly/pull/7380#discussion_r1291667037) that the shims be renamed from (e.g.) `blockly.mjs` to `blockly.loader.mjs`, and in commit 6f930f5 this was duly done, but alas one place was overlooked.
The problem was not spotted in local testing because the `blockly.mjs` module that the blocks and generators chunks were attempting to import did still exist on disk, left over from before the change was made.
Running `npm …

fix(build): Fix import of parent chunk's shim

---

core/block.ts
core/events/events_block_change.ts
core/field.ts
core/serialization/blocks.ts

Fixes #7339 
Passes a `doFullSerialization` parameter to blocks' `saveExtraState` methods.
This parameter signals that they should serialize all of their state (instead of just serializing a reference to it) for use during copy-paste.
N/A
N/A
Dependent on https://github.com/google/blockly/pull/7356

feat: add doFullSerialization support to blocks

---

tests/browser/test/test_setup.js

Fixes some tests that were flaky because the workspace wasn't always fully loaded.
In the `testSetup` function that loads a URL, wait for the workspace's block canvas to exist before returning.
The workspace must exist before the test actions start running. Checking for the block canvas is an easy test that uses standard webdriver APIs (`waitForExist` and selectors).

fix(tests): wait for the workspace to render before starting test actions

---

core/events/events_block_change.ts

Fixes N/A
Switches change events (i.e. for mutations) to use full serialization.
I am reasonably sure this is the behavior it should have. But I needed to do a lot of playing with the shared procedure blocks to be confident.
Events are built for two use cases:
1) Notifying the developer when things happen.
2) Mirroring workspaces.
If we don't do full serialization then (1) breaks. E.g. in the shared procedure blocks change events will not be fired when the blocks mutate because their extra state isn't changing (their just serializing the same procedure ID). (2) is still fine because mirroring the procedure model updates updates the blocks.
With full serialization, (2) is a bit tricky because you need to mirror the changes to blocks and makes sure /not/ to mirror the changes to data …

fix: block change serialization

---

core/field.ts

Fixes https://github.com/google/blockly/issues/7315 by switching to single-backtick for a code snippet that is inside of a markdown table.
Use single backticks instead of triple backticks.
Fixes bad rendering in our documentation pages.
Tested by running `npm run package && npm run docs` and making sure that the change is propagated correctly.

chore: fix docs in FieldImage

---

core/workspace_svg.ts

Work on #7157 
Adds public accessor for `svgGroup_`.
This is necessary for the scroll options plugin to add a wheel listener, and for the multiselect plugin to add a mouse enter listener.
N/A
N/A
I didn't make `getBlockCanvas` public because I realized the scroll options plugin is only using it to get the transform. I think we should either be able to use the metrics, or just `scrollX` and `scrollY` to do that instead.
App Inventor asked that I fix the `svgGroup_` issue this quarter so they don't need to worry about the multiselect plugin breaking (in this way) in the future.

feat: add accessor for the workspace svg group

---

core/icons/mutator_icon.ts

Fixes N/A
Dispose of `saveConnections` change listeners when the mutator bubble is hidden.
We weren't properly cleaning up `saveConnections` listeners, so blocks with mutators were just getting more of them every time their mutators were opened. Not great for performance.
`saveConnections` behavior is covered by existing tests.
N/A
N/A

fix: saveConnections listener not being disposed

---

core/bubbles/mini_workspace_bubble.ts

Part of https://github.com/google/blockly/issues/7104
Stop adding extra margin to mini workspace bubbles (mutator bubbles). Make the margin the same in RTL and LTR.
RTL:
LTR:
RTL:
LTR:
Could not find a reason for the previous inconsistency.
Opened mutators in LTR and RTL modes and dragged blocks around inside the mutator bubbles to make them change size.
None

chore: clean up measurement code in mini workspace bubble

---

core/contextmenu_registry.ts

Fixes https://github.com/google/blockly/issues/6406
Fixes the types on context menu items so that you can pass your own HTML elements. The context menu already supports this, we were just restricting it with our documented types.
Peoples want to be able to add their own icons and whatnot to the context menu! This enables them to do so.
Manually tested by changing the `displayText()` method on the duplicate option to the following:
```
displayText() {
const elem = document.createElement('span');
elem.appendChild(document.createTextNode('test'));
elem.style.fontWeight = 'bold';
return elem;
},
```
https://developers.google.com/blockly/guides/configure/web/context-menus should be updated.
I looked into whether we need to do anything to support people using our CSS classes, but they're all …

feat: add custom context menu rendering

---

tests/browser/test/basic_playground_test.js
tests/browser/test/delete_blocks_test.js
tests/browser/test/extensive_test.js
tests/browser/test/field_edits_test.js
tests/browser/test/mutator_test.js
tests/browser/test/procedure_test.js
tests/browser/test/test_setup.js
tests/browser/test/toolbox_drag_test.js

- Makes it easier to slow down tests to watch them run.
- Enables a set of tests that are slow but might have caught some issues during the past release.
- Add a `PAUSE_TIME` constant in the test helper file, and use it everywhere.
- Enable toolbox drag tests (previously skipped)
- Switch to using `continue` in toolbox drag tests (per Beka's feedback from when I initially added them)
Try to make tests more useful.
This isn't wired through to the command line yet--anyone who wants to change the value has to change it manually. But I also expect that we'll only change this value when running tests locally + manually.
The drag tests take for-freaking-ever.

chore(tests): set browser pause time in one place and enable toolbox tests

---

core/block_dragger.ts
core/block_svg.ts

Fixes #6852
When blocks are dragged, bring them to the front, and update `setParent` to insert blocks before the block being dragged, if any, when removing it from its parent.
Blocks would occassionally appear behind other blocks when being dragged.
Blocks being dragged appear atop all other blocks.
Fixes a regression introduced in #6758.

fix: Always draw dragged blocks atop others in the workspace.

---

core/workspace.ts

If you're using typescript then you know how frustrating it is to always add ordered param when calling workspace.getAllBlocks()/workspace.getTopBlocks()/workspace.getTopComments()/workspace.getBlocksByType(). That's why I think it's a good idea to make it optional. If a value is not passed, it will use false as default.

feat: make ordered argument optional for workspace functions

---

core/workspace_svg.ts

Fast follow to https://github.com/google/blockly/pull/7424 that also makes it optional for workspace_svg functions.

chore: make ordered argument optional for workspace_svg functions

---

core/bubbles/mini_workspace_bubble.ts

Fixes #7421 
Sets `internalIsMutator` on the mini workspace bubble workspace.
Makes it so that dragging behaves correctly.
Manually tested dragging with a zoomed workspace.
N/A
N/A

fix: dragging blocks within a zoomed mutator

---

core/insertion_marker_manager.ts

Reverts google/blockly#7384
See https://github.com/google/blockly-samples/issues/1856#issuecomment-1690637093 for context on why we are rolling back the change to make insertion markers use JSON serialization.
Full steps:
- (**Current step**) Roll back google/blockly#7384 
- Roll back https://github.com/google/blockly/pull/7364
- Patch release
- Decide whether this was a breaking change
- Roll forward this change and https://github.com/google/blockly/pull/7364 together for the next major release

Revert "fix: insertion marker's next blocks are real blocks"

---

core/insertion_marker_manager.ts

Reverts google/blockly#7364
See https://github.com/google/blockly-samples/issues/1856#issuecomment-1690637093 for context on why we are rolling back the change to make insertion markers use JSON serialization.
Full steps:
- Roll back https://github.com/google/blockly/pull/7384
- (**Current step**) Roll back https://github.com/google/blockly/pull/7364
- Patch release
- Decide whether this was a breaking change
- Roll forward this change and https://github.com/google/blockly/pull/7429 together for the next major release

Revert "feat: Insertion marker json deserialization 7316"

---

core/flyout_base.ts
tests/browser/test/mutator_test.js
tests/browser/test/test_setup.js

Fixes N/A
Follow on to #7423 that fixes up the mutator tests.
* Reformats the mutator tests to conform to the style guide.
* Changes the `connect` method to not need to take in the element selector.
* Adds some helpers to remove more concrete selectors from the test.
All of these things are to aid in readability.
Changes to the `connect` method also involved partially fixing https://github.com/google/blockly/issues/7432, so we may want to delay those changes for now since they're not complete.
This is tests!
N/A
N/A
](https://github.com/google/blockly/pull/7393/files)

chore: clean up mutator tests

---

core/rendered_connection.ts

Fixes N/A
Disposes of the connection highlight if it still exists when the connection is disposed
Was running into some problems with connection highlights sticking around in the dynamic connection plugin.
N/A
N/A
N/A

fix: connection highlight not disposed when block deleted

---

appengine/storage.py

The cgi modue disappears in the next version of Python.  This PR adds an import of urllib.parse, but that's not a new dependency since cgi already imported it.

chore: Remove 'cgi' import from Python

---

core/block_svg.ts
core/insertion_marker_manager.ts

Fixes https://github.com/google/blockly/issues/7426
When positioning the insertion marker, take into account that its connection may have been resized.
With these changes, when positioning the insertion marker, we ensure that the target connection will not move.
I tested in the playground with Zelos and Geras that insertion markers don't move target connections anymore, even if their connection have been resized.
N/A

fix: insertion marker position when connection is resized (#7426)

---

tests/browser/test/basic_playground_test.js
tests/browser/test/delete_blocks_test.js
tests/browser/test/test_setup.js

Fixes https://github.com/google/blockly/issues/7484
- Add a helper function that tags the first label field on a block, then uses that to get that element as a Webdriverio Element.
- Change context menu helper function to take in a block ID instead of a block element.
- Use the helper function in all context menu tests and in block deletion tests.
Fix issues with clicking when the block's path is occluded or has a hole in it.
Ran browser tests and watched for unexpected behaviour.
I added JSDoc
- You could run into issues if you used this function twice, on different blocks, within the same test context. In that case the solution is to add a helper that removes the ID from the SVG element. This seems not worth adding unless/until it becomes an issue.
- There are other tests that click on …

fix(tests): contextMenuSelect sometimes clicks the wrong block

---

core/block.ts
core/field.ts
core/field_colour.ts
core/field_input.ts
tests/playground.html

Fixes #7442 
Makes it so that input fields (and subclasses) and colour fields properly switch back and forth between full block fields and normal fields when their blocks are modified.
Before they didn't have the ability to switch, so mutated blocks would break.
Manually tested the following behaviors using the browser console for number inputs and colour fields:
1) Instantiate a full block field.
2) Add a label field to it via the console.
3) Observe how the original field is rerendered to not be a full block field.
4) Remove the added label field via the console.
5) Observe how the original field is rerendered to be a full block field again.
I think this would be a good candidate for screen shot testing. The code is so jank and I don't think unit testing is worthwhile.
N/A
I disagree …

fix: zelos full block fields rendering badly

---

core/render_management.ts

Fixes https://github.com/google/blockly/issues/7444
Makes it so that JavaFX always immediately rerenders blocks.
JavaFX doesn't handle `requestAnimationFrame` properly. It draws the frame before callbacks have completed, so we get glitchy jumpy looking blockly.
This change makes it so that JavaFX doesn't use `requestAnimationFrame` getting rid of the glitchiness. With this, we also sacrifice the performance improvements provided by the render management system.
Manually tested that this works with the reproduction sample provided in https://github.com/google/blockly/issues/7444.
Also manually tested that normal in-browser code still uses queueing. (userAgent is working properly)
N/A
N/A

fix: immediately render for JavaFX

---

core/serialization/blocks.ts
tests/mocha/jso_deserialization_test.js

Fixes https://github.com/google/blockly/issues/7486
Adds a `try... finally` block to make sure events are reenabled even if you load bad JSON.
Fix https://github.com/google/blockly/issues/7486
Manual test steps do not reproduce.
Added a test that events are enabled even after bad JSON is loaded and deserialization throws.
N/A
N/A

fix: bad JSON state leaving events disabled

---

core/field_input.ts
msg/messages.js

On the desktop, widgetDispose_ will call onFinishEditing_ on close.
This was missing in the mobile counterpart, so any cleanups in onFinishEditing_ would not be called.
Also update the message string comment while we are touching this code.
On mobile, any cleanups in `onFinishEditing_` would not be called.
It is called in `widgetDispose_` but not in `showPromptEditor_`.
Call `onFinishEditing_`  in `showPromptEditor_`.
Make sure `onFinishEditing_` works consistently on mobile and desktop.
Tested on a playground hosted on desktop, viewed on Android mobile device on local network and verified that `onFinishEditing_` was not called before but is now.
Updated the docstring for the prompt translation.
For consideration (though possibly not needed): Should  `showPromptEditor_` share more things …

fix: Call onFinishEditing_ for fields on mobile.

---

core/block.ts

- [ x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)
Fixes : https://github.com/google/blockly/issues/7448
Removes the unwanted BlockChange event during jsonInit.
```
if (json['inputsInline'] !== undefined) {
eventUtils.disable();
this.setInputsInline(json['inputsInline']);
eventUtils.enable();
}
```
disabling the event while creating will fix it.

fix: incorrect blockchange firing

---

core/field_input.ts

Fixes #7253 
Update the `field_input.ts` file with the following changes:
- Update the return type info from `HTMLElement` to `HTMLInputElement` for [widgetCreate_](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/field_input.ts#L351)
- Remove the `as HTMLInputElement` cast in [showInlineEditor](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/field_input.ts#L334C10-L334C20).
Returning proper type info for input-specific manipulations of the element.

minor: update 'field_input.ts' file

---

core/shortcut_items.ts

- Fixes #6274: Move delete keyboard shortcut in-progress gesture check to precondition
- Add a check to the precondition function  to make sure a gesture is not in progress.
- Remove the gesture check
-The delete keyboard shortcut was  checking if there is a gesture in progress from within its callback function, and returns early if so which should not have been the case
- issue https://github.com/google/blockly/issues/6274

fix: move delete keyboard shortcut in-progress gesture check to precondition #6274

---

core/block.ts
core/interfaces/i_movable.ts
core/shortcut_items.ts

Fixes https://github.com/google/blockly/issues/6848
When copying a block, blocky pastes the block near the original block. With this change, it will paste the new block either in the middle of the view or near where the cursor is.
The method getRelativeToSurfaceXY(): Coordinate is added to the IMovable interface

feat: Paste block in viewport / near cursor

---

core/flyout_button.ts

Fixes https://github.com/google/blockly/issues/7526
This pr renames the incorrectly labeled variable and removes underscore from it precisely
I did npm run and tested all the buttons before and after and checked the entire functionality once
I have attached a screenshot of the working functionality after making the changes
I don't believe any additional documentation is required

fix: removed underscore from isLabel_ in flyout_button.ts

---

.gitattributes

Description:
Issue: [#7191](https://github.com/google/blockly/issues/7191)
Overview:
This pull request addresses the issue reported in [#7191](https://github.com/google/blockly/issues/7191) by adding a .gitattributes file to standardize line endings within the Blockly project.
Changes:
Added a .gitattributes file with the following configuration to ensure consistent line endings:
* text=auto
Motivation:
Standardizing line endings to LF (Unix-style) is essential for maintaining code consistency across different platforms and prevents issues related to mixed line endings when collaborating on projects.
Testing:
I have tested these changes locally by cloning the repository and verifying that the .gitattributes file is properly applied to the project. Line endings are consistent with LF, as …

fix: Addition of the .gitattributes file to standardize line endings #7191

---

core/workspace_svg.ts

Fixes 
https://github.com/google/blockly/issues/7176
Added an API to programmatically scroll the workspace
Removed the @internal
All changes were in workspace_svg.ts file
Make it easier for users to use the ToolBox and WorkSpace

Feat: Added an API to programmatically scroll the workspace

---

core/flyout_horizontal.ts

Fixes #7522 https://github.com/google/blockly/issues/7522
Fixes flyout_horizontal.ts In [layout_] where we access the block with const block = item.block. The result was nullable, so all later uses of block have to have a [non-null assertion].
To avoid writing the non-null assertion, to present the horizontal bar with the categories(blocks) in an appropriate manner. 
We changed the variable horizontalLayout to true in playground.html to test the changes.
We recommend updating the test coverage documentation in playground.html.

fix: non-nullable check for block variable and removed ! in layout_ #7522

---

package-lock.json

Fixes broken build due to missing `goog-closure-compiler` dependencies.
Install `google-closure-compiler-osx` or …`-windows` as appropriate.
Not having a broken build is good.
I ran `npm run build` and it succeeded.  What more do you want?!?

fix(build): Fix broken npm install of Closure Compiler

---

scripts/gulpfiles/git_tasks.js

Fixes an issue where playgrounds did not work on github pages because the `*.loader.mjs` files were not committed. They have to be committed explicitly with `-f` because they are gitignored in all non-gh-pages cases.
Add `'build/*.loader.mjs'` to the list of `EXTRAS` IN `git_tasks.js`
Tested by manually doing the gh-pages steps with these additional files, then pushing to my gh-pages branch.

fix: include loaders in gh-pages commits

---

scripts/gulpfiles/appengine_tasks.js

This is the equivalent of #7559 for the demos on appengine. I tested it by making the change locally and running `npm run deployDemos`. Playgrounds now load correctly.
Note that we don't actually link to the playgrounds. We still serve them, so they should still work.

fix: missing loaders for appengine deployment

---

core/shortcut_items.ts

Fixes https://github.com/google/blockly/issues/6848
Removes references to `getSelected` so you can paste while nothing is selected. Also reorganizes code to use Rect.contains
Bug fixing.
Tested pasting when the original coords are inside and outside the viewport. Works correctly in both cases.
N/A
N/A

fix: pasting with nothing selected

---

package-lock.json
package.json

Fixes https://github.com/google/blockly/issues/7543

chore: remove bump script from package.json

---

core/generator.ts

Fixes https://github.com/google/blockly/issues/7367
Adding " " between two strings
Correcting typo
N/A
N/A
N/A

correcting typo from 'codefor' to 'code for'

---

core/field_colour.ts

Fixes https://github.com/google/blockly/issues/7582
Makes it so picking a colour actually updates the colour field.
Bugs be bad.
Manually tested selecting colors in geras and zelos. Manually tested adding and removing fields in zelos switches between full block and normal colour fields.
N/A
N/A

fix: colour from colour picker not being updated

---

core/dropdowndiv.ts
core/tooltip.ts
core/widgetdiv.ts

Fixes #7571 
Check if the element(.blocklyDropDownDiv) exists.
Closing blockly does not reset the 'div' variable.
Therefore, the createDom method of dropDownDiv is not re-executed.
I have verified that the drop-down elements are displayed on the second view.

fix: recreate dropdown div

---

core/gesture.ts

Closes #7588
Fixes #7588
Added a call to bringBlockToFront() in doIconClick().
N/A
N/A
N/A
N/A

fix: bring block to front when icon clicked

---

core/block.ts

See #7589
Fixes #7589 
Adding a check for `json["message0"] === undefined` at the start of `jsonInit` function.
To fix current behavior which allows creation of blocks when messages is undefined.
I wasn't actually able to reproduce the bug mentionned in #7589, so I added a check which should fix the issue if I understand correctly. How can I attempt to reproduce the issue, please ?
Also, I'd be happy to make any necessary changes. I know my current solution may not be what you had in mind.

Throw an error for undefined messages in block definitions

---

core/renderers/common/info.ts
core/renderers/zelos/info.ts

Fixes N/A
Fixes the docs for `shouldStartNewRow` since they were incorrect, and renames the params to be less confusing.
I have had trouble with this several times. When helping John, when writing the renderer guides (which are misleading because I didn't understand what the code was doing), and when helping App Inventor.
N/A
Luckily params are one of the few things we can rename without breaking people :P
Please check my understanding of `createRows_` for yourself to make sure these doc changes are actually correct.

chore: fix shouldStartNewRow docs and param names

---

core/generator.ts

Part of #6828; solves a problem with the typing of the second (`generator`) argument to block generator functions.
Make two changes to the `forBlock` dictionary on CodeGenerator objects:
- Change the type of the second argument to the special [polymorphic `this` type](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-types) (was CodeGenerator)
- Change the way `forBlock` is declared from using an index signature to using the `Record<>` template type.  The two should be equivalent but [the former provokes type errors when used with the 'this' type](https://stackoverflow.com/q/77197616/4969945).
Additionally, mark the now-unused (but exported) `BlockGenerator` type alias as `@deprecated` pending removal in the next major version.
Having the `forBlock` dictionary typed …

fix(generators): Modify type signature of `forBlock`

---

blocks/text.ts

When combined with https://github.com/google/blockly-samples/pull/2025 this resolves https://github.com/google/blockly-samples/issues/1134.
Register the quote_image_mixin.
This allows the block-plus-minus plugin to access the mixin which stops the following warning (when combined with https://github.com/google/blockly-samples/pull/2025) from appearing when using the text_join block with the plugin:
`field named "TEXT" not found in "text_join" block`
The passing of this should be followed by the passing of https://github.com/google/blockly-samples/pull/2025.

fix: text join block warning when using block-plus-minus plugin

---

core/block_dragger.ts
core/block_svg.ts
core/field.ts
core/field_input.ts
core/render_management.ts
core/rendered_connection.ts
tests/mocha/render_management_test.js

Fixes #7491
Reorganizes a bunch of code, and makes it so that fields get `onLocationChange` call backs.
Makes it so that fields can reposition their widgets properly.
* Tested that https://github.com/google/blockly/issues/6976 does not reproduce
* Tested that changing the window size properly repositions the div, re: https://github.com/google/blockly/issues/6915
* Tested that #7491  does not reproduce
* Tested that we did not get a significant performance drop by dragging spaghetti blocks, and also typing into the spaghetti blocks. We might have gotten a slight performance dip from splitting up the connection update operations so they're not happening contiguously (the engine can't optimize as much). But all of this code is internal so I can circle back once I've had more time to …

fix: widget positioning

---

core/icons/icon.ts

Fixes #7047
Makes it so that built-in icons can have tooltips.
People want icons to have tooltips.
Manually tested that by default icons show the tooltip of the parent.
Manually tested that setting the tooltip displays the new tooltip.
Manually tested that setting the new tooltip to `null` displays the tooltip of the parent.
This should be added to the custom icons docs maybe? Need to check.
This adds tooltip support for any icons inheriting from `Blockly.icons.Icon`. Any icons made by external developers which are not inheriting can do what I've done here to support their own tooltips.

feat: add tooltip support for icons

---

core/icons/mutator_icon.ts

Fixes #7557  
When the source block is not editable, the bubble won't be visible hence it won't allow mutation of the block.
It was a bug causing the user to mutate a block in read-only workspace.

fix: Can mutate blocks in readOnly workspace

---

.github/workflows/browser_test.yml
.github/workflows/build.yml

Dropping node 16 support to unblock https://github.com/google/blockly/pull/7615
Technically I don't think we /need/ to drop support from the browser tests, but I think it's better to run the tests on consistent node versions than to have them get out of sync.

chore: drop node16

---

core/flyout_base.ts
core/serialization/blocks.ts
tests/mocha/jso_serialization_test.js

- [ x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)
Fixes  #7432 
Adds a parameter,  `saveIds: boolean`, to the [`save`](https://github.com/google/blockly/blob/4ab8d000995a93eafbc29444abb76e535aedf134/core/serialization/blocks.ts#L82) function. I also made sure that the parameter is passed through the recursive calls.
This ensures that when a block is dragged out, the ID of the newly placed block is different than the one in the flyout. 
1. Open up the flyout, inspect the if block and note the data-id attribute 
2. Drag the block out, note the data-id attribute
3. The data-ids are not the same

fix: flyout id is different than first placed block

---

core/block_svg.ts

Fixes  #7587 
The change is to check if the block is dead or is in dying state before accessing it in the ```bringToFront``` function.

fix: prevent crash when clicking on a field to delete a block

---

core/field_dropdown.ts

Fixes #7416 
The block doesn't check its parent colour even if it's a shadow block for the dropdown field, It simply takes the colour style from the block itself.

fix: Shadow block dropdown gets color of parent category

---

core/insertion_marker_manager.ts
tests/mocha/insertion_marker_manager_test.js

Fixes https://github.com/google/blockly/issues/7466
Makes it so that children of insertion markers are also set as insertion markers
You can set shadow blocks programmatically, but they weren't previously being set as insertion markers.
Tested with the following two block definitions. The first sets the shadow in the `init` method, the second sets the shadow in the `loadExtraState` method.
```js
Blockly.Blocks['test'] = {
init: function () {
this.appendValueInput('test').connection.setShadowState({
'type': 'math_number',
});
this.setPreviousStatement(true);
},
};
Blockly.Blocks['test2'] = {
init: function () {
this.appendValueInput('test');
this.setPreviousStatement(true);
},
loadExtraState: function () {
this.getInput('test').connection.setShadowState({
'type': 'math_number',
});
}, …
```

fix: shadows in insertion markers being displayed as shadows

---

core/flyout_base.ts
core/flyout_horizontal.ts
core/flyout_vertical.ts
core/metrics_manager.ts
core/workspace_svg.ts
tests/mocha/metrics_test.js
tests/mocha/trashcan_test.js

Fixes #7506 
~Also https://github.com/google/blockly-samples/issues/1922 ? Need to check.~
Makes it so that autoclose on flyouts is toggleable.
People want to make the continuous toolbox autoclose. Also app inventor wants to control the flyout from an external component, so they use an autoclosing simple flyout.
Manually tested steps [here](https://github.com/google/blockly/issues/7506#issuecomment-1729531204).
Fixed up some change detector unit tests.
N/A
N/A
Makes https://github.com/google/blockly-samples/issues/1922 possible to do further work on. Still needs fixes to `refreshSelection`

fix: make autoclose toggleable for flyouts

---

core/block_dragger.ts
core/block_svg.ts
core/bubble_dragger.ts
core/css.ts
core/inject.ts
core/interfaces/i_rendered_element.ts
core/layer_manager.ts
core/layers.ts
core/workspace_comment_svg.ts
core/workspace_svg.ts
tests/mocha/index.html
tests/mocha/layering_test.js
tests/mocha/theme_test.js
tests/mocha/workspace_comment_test.js

Fixes #7354 
Adds a layer manager to keep track of what layers we have (dragging layer, block layer, and bubble layer) and what order they should be in.
The new system should be entirely internal.
Needed to add a dragging layer so that blocks could exist in front of the toolbox while dragging, so I just decided to implement a better layer management system at the same time. This prepares us to easily add new layers in the future if we need to.
There are still parts of blockly that are directly accessing the block and bubble layers, these can be moved to use the layer manager.
Added tests to make sure the layer manager properly handles adding new layers, and appending elements to the drag layer.
Manually tested that dragging elements and the worskpace seems to work properly, with the …

fix: blocks being dragged behind toolbox

---

core/block.ts
core/block_svg.ts

Fixes https://github.com/google/blockly/issues/7636
Updates TSDocs for `setShadow` according to issue.

fix: update setShadow TSDoc for Block and BlockSvg

---

generators/lua.ts
generators/lua/colour.ts
generators/lua/lists.ts
generators/lua/logic.ts
generators/lua/loops.ts
generators/lua/lua_generator.ts
generators/lua/math.ts
generators/lua/procedures.ts
generators/lua/text.ts
generators/lua/variables.ts
generators/lua/variables_dynamic.ts

Part of https://github.com/google/blockly/issues/6828.
Migrate `generators/lua/*.js` and `generators/lua.js` to TypeScript.
Finish TS migration.
`npm test` passes. No changes to manual test procedures required.
No changes to documentation yet, as there should be minimal changes to the generated code and no changes to the published typings (because during build we overwrite the generated `.d.ts` files with the ones from `typings/`).
It may be easier to review this commit-by-commit, as the final format commit make a lot of noisy changes.

refactor(generators): Migrate Lua generators to TypeScript

---

.github/workflows/browser_test.yml
.github/workflows/build.yml

Fixes #2114 
Re-enables build for macosx
build seems to work fine after several triggers: https://github.com/alicialics/blockly/actions/runs/6830695852
Re-enables browsers-test for ubuntu
browsers-test seem to fail but this is a manually triggered job that doesn't get run very often:
https://github.com/alicialics/blockly/actions/runs/6830698569
#2114 
ran in CI
N/A
cc @BeksOmega

chore: Renable macos-latest build

---

scripts/package/README.md

Fixes #7624 
Modifies the README to hopefully be correct about how we want people to import things.
Getting our code is important.
No functional changes!
This is documentation silly!
N/A

chore: modify readme about how we want people to acquire Blockly

---

core/trashcan.ts

Fixes https://github.com/google/blockly/issues/7681
Has the trashcan check if there is a drag in progress before opening.
Unbork borkedness.
Tested repro steps from https://github.com/google/blockly/issues/7681 and could not reproduce.
N/A
N/A

fix: trashcan flyout opening on drag

---

core/workspace_svg.ts

Fixes #7674
- Introduced a new class member dummyWheelListener in WorkspaceSvg to store the dummy wheel event listener.
- Modified the dispose method in WorkspaceSvg to remove the dummyWheelListener from the document body when the workspace is disposed.
Previously, the dummy wheel event listener added to the document as a workaround for a Safari bug was not being properly disposed of. This could potentially lead to memory leaks and unintended behavior. By storing the listener in a class member, we can ensure it is correctly removed when the workspace is disposed, thus improving the robustness and cleanliness of the code.
- Manually tested to confirm that the dummyWheelListener is added and removed correctly.
- Ensured that the addition and removal of this listener have no side effects on …

Release dummy wheel listener on workspace dispose

---

core/flyout_horizontal.ts
core/flyout_vertical.ts

Fixes https://github.com/google/blockly/issues/7677
Re-adds logic for setting absolute metrics in the flyout code removed in https://github.com/google/blockly/pull/7634/files#r1385439054
Unbork borkedness.
* Manually tested mutators.
* Tested that setting the autoclose-ness of flyouts on workspaces with scrollbars still properly updates the absolute metrics.
N/A
Filed https://github.com/google/blockly/issues/7689 to track actually fixing this.

fix: mutator coordinates not respecting flyout

---

core/flyout_base.ts

Fixes N/A
Makes it show that we can show empty flyouts again.
Backpack has an option where you can open the empty flyout. For... reasons.
Manually tested that this doesn't break app inventor and works with the backpack plugin.
N/A
N/A

fix: reenable showing empty flyouts

---

tests/mocha/webdriver.js

Fixes https://github.com/google/blockly/issues/7649
Instead of using `getText()`, which requires a visible element, I use `getHTML()` and strip out the `p` tag.
- See https://webdriver.io/docs/api/element/getText and **note:** only visible elements will return display.
- The root element with id `failureCount` has `display: none`, so the text content here never displays.
Previous output:
```
Loading URL: file:///usr/local/google/home/blaketw/git/blockly/blockly/tests/mocha/index.html
============Blockly Mocha Test Failures================
============Blockly Mocha Test Summary=================
1 tests failed
============Blockly Mocha Test Summary=================
Mocha tests failed
```
Updated  output:
```
Loading URL: file:///usr/local/google/home/blaketw/git/blockly/blockly/tests/mocha/i …
```

fix: updated mocha tests to display error messages

---

core/flyout_base.ts

Fixes #1801
Fixes issue where flyout blocks were incorrectly highlighted during workspace drag,
by adding a check for the workspace's drag state before triggering block highlighting events.
Flyout blocks should not highlight if the workspace is being dragged.
N/A
N/A
N/A

fix: prevent flyout block highlighting during workspace drag

---

scripts/gulpfiles/package_tasks.js
typings/dart.d.ts
typings/javascript.d.ts
typings/lua.d.ts
typings/php.d.ts
typings/python.d.ts

Fixes #7652.
* Modify `package_tasks.js` to include `tsc`-generated `.d.ts` files for the generators in `dist` when building the `blockly` NPM package.
* Replace the hand-written `.d.ts` files for the generator chunks with ones that reexport the types from the corresponding `tsc`-generated `.d.ts` file.
Publish accurate typings for the generators.
BREAKING CHANGE: Previously the `dartGenerator`, `luaGenerator`, `javascriptGenerator`, `phpGenerator`, and `pythonGenerator` exports (from the `blockly/dart`, `blockly/lua`, `blockly/javascript`, `blockly/php` and `blockly/python` entrypoints respectively) were being typed `any`.  Now their types are correct.  There is no change to their runtime behaviour, but developers who have written code in TypeScript that manipulates generators (adding …

fix(generators): Fix generator typings

---

core/block_svg.ts

Work on #5146  #4288 
Makes it so that snapping to the grid happens immediately instead of after a delay.
I am working on refactoring how block initialization works. As part of it, I need to have `bumpNeighbors` be triggered by the render management system, instead of being triggered by each individual change that might change the shape of the block.
But before `bumpNeighbors` gets called, I need to make sure the snap has happened. So I'm getting rid of the delay.
Manually tested that snapping works properly, and looks correct when dropping after dragging.
N/A
Dependent on #7743

fix: snap immediately

---

core/insertion_marker_manager.ts

Fixes #7316
Reverts https://github.com/google/blockly/pull/7430 https://github.com/google/blockly/pull/7429
Makes it so that insertion markers are created using JSON deserialization.
From https://github.com/google/blockly/pull/7364
> Insertion markers duplicate the block being dragged, and then tell the duplicate to be an insertion marker.
> Currently the duplication duplicates (ha) a lot of code from the serialization system. We think this is because in the past the XML system didn't have a good way to just serialize and deserialize a single block (without children). But the JSON system does have this!
> Sparked by this discussion: https://groups.google.com/g/blockly/c/gcvynl88QLY/m/shFyX4x0BwAJ
All tests pass.
N/A
Insertion-marker-ness is now set after any mutation is deserialized.
If …

fix!: have insertion markers use json deserialization

---

core/block.ts
core/block_svg.ts
core/inputs/input.ts
core/insertion_marker_manager.ts
core/rendered_connection.ts
tests/mocha/icon_test.js
tests/mocha/test_helpers/workspace.js
tests/mocha/workspace_svg_test.js

Fixes https://github.com/google/blockly/issues/4288
Makes it so that `rendered` is constant, and is only used to check whether the block is a `Block` or a `BlockSvg`.
Makes the system easier to reason about and understand.
Fixed change detectors.
This will need docs. I have separate tasks filed for that.
This PR creates a pretty significant performance degredation related to `bumpNeighbours` I have a separate fix in the works for that. But in an effort to keep my PRs small I'm putting that up separately.
There's also more work to be removing references to `initSvg` and `rendered` and cleaning up `initSvg`.
Dependent on #7745 
If you are using `rendered` to check whether the block is initialized or currently visible, do not do that. `rendered` should only be used to tell if the block is a …

fix!: `rendered` meaning

---

core/renderers/zelos/constants.ts
core/renderers/zelos/drawer.ts

Work on #7204 
Makes it so that zelos has the ability to highlight connections, so the eventual connection previewer system can call the renderer to highlight connections consistently (instead of sometimes calling the renderer, and sometimes doing other things).
Manually tested highlighting all three shapes of dynamic connections in zelos (hexagon, rounded, and square). Manually tested highlighting non-dynamic connections (puzzle tabs).
N/A
N/A
The drawer architecture is... a bit frustrating. All of the methods are stateful, so I had to pull out some logic for creating internal input paths into pure methods. This way the code could be reused.
Some of the "constants" for path shapes were also broken. Previously `pathDown()` was never being called, so no one noticed that it was busted. I …

feat: connection highlight zelos

---

core/flyout_base.ts
core/render_management.ts
tests/mocha/render_management_test.js

Fixes https://github.com/google/blockly/issues/7783
Makes it so that rerenders can be triggered in specific workspaces. This way flyouts only trigger renders in their workspace (which is necessary for calculating their size correctly) but don't rerender blocks in other workspaces (which is causing #7783 )
Manually tested using the repro steps in #7783 
Will add unit tests. [Edit: Done]
N/A
N/A

fix: triggering flyout show from field render causing infinite loop

---

core/render_management.ts

Fixes N/A
Follow up to https://github.com/google/blockly/pull/7784 We were canceling all queued renders when triggering a render in one workspace.  We shouldn't do that because there may still be queued renders in other workspaces
All tests pass.
1) Defined the following block in the playground in develop.
```js
Blockly.Blocks['test'] = {
init: function() {
this.setColour('#ccc');
this.appendDummyInput().appendField(
new Blockly.FieldImage('media/arrow.png', 50, 50, '', this.onClick.bind(this)));
},
onClick: function() {
this.setNextStatement(true);
this.workspace.getFlyout().show([{'kind': 'block', 'type': 'controls_if'}])
}
}
```
2) Observed that when clicked, the flyout was shown but the next statement was not rendered.
3) Did the same thing on this branch.
4) Observed that the flyout …

fix: cancelling all renders on triggering queued renders

---

core/block.ts
core/block_dragger.ts
core/block_svg.ts
core/field.ts
core/gesture.ts
core/inputs/input.ts
core/render_management.ts
core/rendered_connection.ts
tests/mocha/input_test.js
tests/mocha/render_management_test.js

N/A
Makes it so that `bumpNeighbours` is called as part of the rendering cycle.
1) You no longer have to remember to call `bumpNeighbours` because it just happens whenever the block changes shape.
2) Alleviates a performance regression caused by https://github.com/google/blockly/pull/7747 . The regression was that `bumpNeighbours` was being called on every single block initialization action during deserialization, which meant a ton of `setTimeout` calls, which were slowing everything down. Making `bumpNeighbours` part of serialization gets rid of these `setTimeout` calls.
Manually tested.
Manually profiled performance.
Also covered by some existing unit tests (caught the issue with event grouping!)
N/A
Dependent on https://github.com/google/blockly/pull/7747

fix: bump neighbours performance regression

---

blocks/procedures.ts
core/block.ts
core/block_svg.ts
core/field.ts
core/inputs/input.ts
core/render_management.ts
core/renderers/common/drawer.ts
tests/mocha/render_management_test.js

Fixes https://github.com/google/blockly/issues/7749
Makes initiailzation for inputs and fields more consistent.
1) Separates initialization for inputs into `init` and `initModel` to match separate initialization paths for blocks and fields.
2) Makes it so that when fields are appended, they are always initialized (regardless of whether the block is rendered or not).
Make initialization work consistently and more understandably.
Tests continue to pass.
I'm going to write dev docs at some point about the intialization / deserialization life cycle.
Dependent on #7748 
I had to add the early return in the render management system for uninitialized blocks because we have ~200 tests that do not properly initialize the blocks. **TODO**: File an issue for this once this is merged.

fix: block initialization

---

appengine/app.yaml

3.7 is not supported from 31 January.  Failure to upgrade appears to result in the inability to push new versions.  3.12 is the latest available Python version for App Engine, and should last the longest.
Tested on DOM-Tutorials and Glockenspiel.  No issues there.

chore: Bump Python from 3.7 to 3.12

---

core/field_input.ts

Fixed the block change event firing. #7780 
Passed false boolean  as a second argument to set_value() function located in the fields_input.ts file
Because the old_value field contains an incorrect value.
I tested it out by doing the reproduction steps outlined in the issue #7780, and this time the old value was correct.

fix: prevent block change event firing if editing is cancelled by using keypress

---

core/rendered_connection.ts

Work on #7204 
Deletes the highlight path from the rendered connection since it's unused.
All tests pass.
All tests pass.
N/A
N/A

fix: delete highlight path from rendered connection

---

core/connection_previewers/insertion_marker_previewer.ts

Work on #7204 
Adds the insertion marker previewer so we can stop relying on the insertion marker manager (in a future PR).
Manually tested with the next PR that insertion markers and highlights properly appear:
- When inserting in stacks.
- When inserting around stacks.
- When inserting in rows.
- When inserting around rows.
- When replacing stacks.
- When replacing rows.
N/A
N/A
Recommend reveiewing comit-wise.
A lot of this code was adapted from the insertion marker manager, so it may be useful to look at that.
Please let me know if anything needs more docs.

feat: insertion marker previewer

---

core/xml.ts

Enabling the ability for shadow blocks to be de-serialized from XML.
Fixes #7779 
The PR deletes 
```
// Ensure this block doesn't have any variable inputs.
if (block.getVarModels().length) {
throw TypeError('Shadow blocks cannot have variable references.');
}
```
in the core/xml.ts file.
There is no reason to disallow serialization and also the JSON serialization system does not have this constraint.
I tested the results by trying to reproduce the error.
The error was fixed as it did not appear in the console.

fix: shadow blocks with variable fields are allowed to be deserialized from XML

---

core/block_dragger.ts
core/config.ts

Work on #7204 
Switches the block dragger to use the connection previewer so we can actually swap the logic in and out.
See https://github.com/google/blockly/pull/7792
N/A
Dependent on https://github.com/google/blockly/pull/7792
Should be reviewed commit-wise. I did mess up one thing with deleting (blocks weren't actually getting deleted when dropped over delete areas), which is fixed in a further commit.
A lot of this code was adapted from the insertion marker manager, so it may be useful to look at that.
Let me know if anything needs more docs.

feat: update block dragger to use connection previewer

---

core/serialization/procedures.ts

Fixes N/A
We need to export the save and load functions because the save and load functions deal with parameters, while the functions on the procedure classes do not.
The events in samples need to be able to serialize and deserialize procedures properly.
N/A
N/A
N/A

fix: export save and load procedure

---

core/insertion_marker_manager.ts
core/renderers/common/renderer.ts
core/renderers/zelos/renderer.ts

Work on #7204 
Deprecates the insertion marker manager.
We aint using it no more.
All tests pass
N/A
Dependent on https://github.com/google/blockly/pull/7793
I'll go through and update this when I write the buttload of docs I need to write this quarter -.-

fix: deprecate insertion marker and related methods

---

core/renderers/common/renderer.ts

Fixes N/A
Updates docs to reflect that `shouldHighlightConnection` might not be respected by all connection previewers.
N/A
N/A
N/A

chore: fix docs for shouldHighlightConnection to say it might not be respected

---

core/rendered_connection.ts

Fixes N/A
Destroys the connection highlight when the connection is disposed so that we don't get hanging highlights.
Manually tested with the dynamic connections plugin in samples.
N/A
N/A

fix: destroy connection highlight when the connection is disposed

---

core/connection_previewers/insertion_marker_previewer.ts

Fixes N/A
If the insertion marker block had more connections that the original block (e.g. for [chameleon blocks](https://github.com/google/blockly-samples/pull/2193)) The insertion marker previewer could find the wrong connection and try to connect that.
How chameleon blocks work: If they were connected in a stack, when they start dragging, they add an output connection. Before this change, previews for the previous connection (previously the first connection) would grab the output connection of the insertion marker block (current first connection). This would cause the insertion marker to be positioned incorrectly, because the output couldn't connect where the previous connection is supposed to.
This makes is so that we fail early if the blocks don't match. And that makes the chameleon …

fix: insertion marker previewer finding wrong connection for different conn counts

---

generators/lua/lists.ts

Fixes #6720 
Makes it so that lua generators use 'nil' instead of 'None'. Reasoning is explained in the linked issue.
N/A
N/A
N/A
This may break some user's downstream block programs if they are assigning to a variable called 'None' and then initializing lists with empty inputs expecting them to contain the value assigned to `None`.
It is unlikely that this behavior was ever actually discovered, and as such the correction shouldn't affect end-users.

fix!: have Lua generators use 'nil' instead of 'None'

---

core/grid.ts
core/workspace_svg.ts

Fixes #7827 
Makes it so that grid options are toggleable so App Inventor can toggle them from their context menu items.
Manually tested that setting all of the options works as expected.
Covered by reference documentation.
N/A

feat: make grid options togglable

---

core/block_dragger.ts

Fixes N/A
We were never actually calling dispose on the connection previewer. This worked fine because the default previewer's `dispose` method just calls `hidePreview`. But other previewers may need to do other work.
Manually spot-tested, everything seems good.
Discovered this when writing docs :P
N/A

fix: disposing of connection previewer

---

core/block_dragger.ts

Fixes N/A
Makes it so the conneciton previewer is disposed after the blocks are connected, because the dynamic connections plugin tears down and rebuilds the block when `disposed` is called. If we dispose before they're connected, the block dragger's connection references are invalid, so the blocks can't actually connect.
Manually tested.
N/A
N/A

fix: connection previewer disposing too early

---

core/events/events_click.ts

This is a simple typo fix in Click event class docs (for my OCD sake 😸).
It ain't much, but it's honest work.

fix: typo in Click event class docs

---

core/blockly.ts
core/insertion_marker_previewer.ts

Fixes N/A
Moves the `InsertionMarkerPreviewer` out of the subdirectory since we're exporting it from the root level.
N/A
N/A
N/A

chore: move connection previewer out of subfolder

---

core/block_dragger.ts

Fixes #7871 
Properly take into account workspace scaling to avoid buggies.
manually testing that scale does not affect insertion marker connection previewing range any longer.
N/A
N/A

fix: insertion marker drag scaling

---

core/block_dragger.ts

Fixes #7872 
Restores respecting the connecting snap radius. I didn't realize that the `config` was actually something we allowed folks to overwrite. I thought it was just some place we dumped values.
Manually tested that having a larger connecting snap radius means we stay previewing the current connection for a greater distance.
N/A
Originally broken in https://github.com/google/blockly/pull/7793/files#diff-788430e802e06b0327df87b7fec2bd6ef4685901b8e9daf14ad9bb48da9698c9

fix: restore respecting snap radius

---

blocks/blocks.ts

Fixes N/A
`Blockly.libraryBlocks` and `Blockly.libraryBlocks.blocks` were missing `logic` blocks and `texts` blocks respectively. They should be exported to ensure completeness and consistency. This PR addresses this issue.
`npm test` succeeds.
N/A
N/A

fix: libraryBlocks exports

---

core/block_dragger.ts

Fixes N/A
https://github.com/google/blockly/pull/4886 never actually worked.
Makes it so that `shouldPreventMove` is actually respected.
Manually tested by linking to the backpack plugin.
* Dragging an orphaned block moves it back to the old location on the workspace.
* Dragging a child block reattaches it to parent.
* Dragging a parent block (holding ctrl to heal stack) reattaches to child.
* Dragging a middle block (holding ctrl to heal stack) reattaches to parent and child.
* Dragging from the simple flyout toolbox bumps blocks into bounds.
N/A
I'm going to release a beta of 10.5 for this for app inventor so they can test with it.

fix: shouldPreventMove not being respected

---

core/insertion_marker_previewer.ts

"Fixes" https://github.com/google/blockly/issues/7898 by not having zelos use insertion blocks for inputs and outputs (instead we just highlight). Going to leave a comment on that issue with a more proper fix we should do in the future.
Manually tested that zelos shows insertion markers for stack blocks.
Manually tested that zelos does not show insertion markers for row blocks.
Manually tested that geras shows insertion markers in all cases.
N/A
We should release a patch for this.

fix: connection dancing

---

core/grid.ts

Fixes N/A
Makes getters for the grid attributes public and updates the inline docs. I don't know why this would need to be queried, but Mark (App Inventor) requested that the `shouldSnap` method be public, so I just added getters for everything.
N/A
N/A
N/A

chore: make getters for grid attributes public and update inline docs

---

core/comments/comment_view.ts
core/utils/size.ts

Fixes N/A 
Makes it so we calculate the minimum size of the comment based on the size of the preview text. This way we'll never get preview text hanging off the edge of the comment.
Alternatively, I could have tried to truncate the preview text to fit within the available area, but this is super inefficient because it requires continual trial and error and layout recalculation. So instead of fitting the text to the area, I fit the area to the text.
Ideally the browser would just truncate the preview and add ellipses for us (then we could fit the text to the area), but SVG doesn't support that! So instead we have to do this complicated madness :P
Tested that the minimum size is properly set with different text width, and with or without the delete icon.
N/A
This doesn't work exactly like …

fix: comment min size

---

blocks/blocks.ts
core/block_dragger.ts
core/common.ts
core/grid.ts
core/insertion_marker_previewer.ts
package-lock.json

Re-merges develop into v11, but this time we're actually going to use a merge commit so we can track where v11 is relative to develop. (as opposed to https://github.com/google/blockly/pull/7893 which squashed)

chore: merge develop into v11.0.0

---

core/block.ts
core/block_svg.ts
core/connection.ts
core/xml.ts
tests/mocha/block_test.js

Fixes https://github.com/google/blockly/issues/7864
Makes it so `disposing` is set at the beginning of the `dispose` and `disposeInternal` methods.
This way we can check `isDeadOrDying` in the dynamic connection plugin to get around issues with the dynamic connection plugin (see the linked issue for more detail).
Updated incorrect tests.
N/A
N/A

fix!: have disposing be true from start of dispose

---

core/bubbles/bubble.ts
core/bubbles/textinput_bubble.ts

Fixes N/A
Makes the text input bubble css consistent with the workspace comment css. Yay for styling.
Manually checked that everything still looks correct in LTR and RTL.
Will need to start documenting CSS classes somewhere.
If/when we move the workspace comments into  a plugin, we'll need to do something with the CSS for the resize handle because right now the text input bubble is relying on it. One option is to just move that CSS into the text input bubble class.

fix!: classes on text input bubble to match comment view

---

core/block.ts
core/icons/icon_types.ts
core/interfaces/i_comment_icon.ts
tests/mocha/block_test.js

Fixes #7910
Fixes #7911 
Allows comment icons to be overriden, and constructed from `Block.prototype.setCommentText`.
This will allow external partners to create their own comment icons (e.g. that use the new `CommentView`, while still using the built-in functionality like `setCommentText`, context menu options, etc.
Added tests that `setCommentText` properly constructs classes from the registry.
Yesh, we'll need to document the fact that you can do this somewhere.
N/A

feat: allow overriding comment icons

---

core/comments.ts
core/comments/workspace_comment.ts

Fixes #7906 
Adds a headless workspace comment class (just holds data, doesn't refer to any view elements) to support headless mode. 
No testing, because this is just a bunch of data storage methods. These methods will be covered by later serialization tests.
N/A
N/A

feat: add headless workspace comment class

---

core/field_dropdown.ts
package-lock.json
package.json

Fixes https://github.com/google/blockly/issues/7715
Update `FieldDropdown`'s type information for `doClassValidation` to match the template in `Field` so it properly infers `FieldDropdown` as `Field<string>` instead of `Field<string|undefined>`.
To enable Blockly to update to TypeScript 5.3.3 and beyond.
N/A
N/A
None

fix: updated field_dropdown to properly infer its Field type with TS 5.3.3

---

core/generator.ts
generators/javascript/javascript_generator.ts
generators/python/python_generator.ts

Fixes #2156
Make remove `protected` access modifier from `CodeGenerator.prototype.scrub_`, making it public.
In PRs #7602, #7616, #7646, #7647 and #7654 the `@protected` access modifier on `scrub_` overrides subclasse of `CodeGenerator` not transcribed to the new typescript signature.  I was going to re-add it, but this breaks some of the procedure block generator functions which rely on it, and then @BeksOmega pointed out that this might be one of the CodeGenerator API functions which we had already decided should be public—and lo and behold I found #2156.
Per discussion amongst team, I am not renaming it to scrub at this time.
Documentation will need updating in the usual way.

fix(generators): Make `scrub_` `public`

---

core/block_animations.ts

This PR addresses several issues with the block deletion animation:
* When the workspace is at a scale other than 1.0, the animation is offset (or invisible) from the location of the block being deleted when deleting a block by dragging it to the toolbox
* The deletion animation is obscured by the toolbox, so that only that portion of the block within the workspace bounds when the block is dropped in the toolbox has its animation visible, even though the whole block was visible atop the toolbox when the drag was ongoing
These changes make the deletion animation when disposing of a block into the toolbox smoother and more natural.
Note that there is still some offsetting when the workspace is zoomed out, a block is dragged in, the workspace is zoomed in, and the block is disposed of into …

fix: Fix block disposal animations

---

core/comments/rendered_workspace_comment.ts

Work on #7907 
Adds support for these interfaces so that rendered workspace comments can be used in places where those interfaces are required (e.g. bumping elements into bounds).
N/A
N/A
N/A

feat: have RenderedWorkspaceComment implement IBoundedElement and IRenderedElement

---

core/comments/workspace_comment.ts
core/serialization.ts
core/serialization/priorities.ts
core/serialization/workspace_comments.ts
tests/mocha/jso_serialization_test.js

Fixes #7908 
Implements a JSON serializer for workspace comments so they can be saved.
Adds tests for serialization. Deserializing will be covered by round-tripping tests once I fix up the XML system.
N/A
N/A

feat: add JSON serialization for workspace comments

---

core/comments/comment_view.ts
core/xml.ts
tests/mocha/clipboard_test.js
tests/mocha/serializer_test.js

Fixes N/A
Updates the XML system to save and load new workspace comment classes for a ✨ seamless transition ✨ 
Added round-trip tests for comments. This also covers the logic for all the headless setters and getters (as promised in a previous PR)
N/A
Sorry about the derpy format for the serialization tests. But rewriting them to be mocha style isn't worth it.
When writing this I realized that JSON isn't handling RTL correctly. I used the same (bad) implementation here, then I'm going to fix it in my next PR.

fix: comment have XML save and load new workspace comments classes

---

core/comments/comment_view.ts
core/comments/workspace_comment.ts
core/serialization/workspace_comments.ts
core/xml.ts

Fixes comments being positioning incorrectly when loading from XML in RTL mode
Makes it so that comments are positioned relative to the toolbox when loading in RTL mode, to match blocks.
To get this to work the same as blocks I had to change how I was handling RTL in the comment view. We can't apply the scale at the top level because that messes up the transform (we still want +x to go right and +y to go down in RTL mode to match blocks). So I need to apply it to the sub elements of the icon. And to get rotating the foldout icon to work, that meant I needed an element to encompass the elements of the top bar.
Manually tested loading and saving in RLT and LTR in JSON and XML
N/A
N/A

fix: comment position in RTL

---

core/dragging/dragger.ts

Fixes #7839.
Introduce a concrete `Dragger` class, implementing `IDragger`.
Having decided to delegate dealing with drag targets (and in particular delete areas) to the drag strategy, this class does not have much left in it.
Support custom dragging.

feat(dragging): Introduce `Dragger`, implementing `IDragger`

---

core/dragging/dragger.ts
core/interfaces/i_deletable.ts
core/interfaces/i_draggable.ts

Fixes N/A
This refactors the implementation to match the agreed upon design with two changes:
1) Draggables won't take in `IDragTarget` objects. I don't know why I did that, since the dragger handles all interaction with drag targets.
2) We have a new `moveToStart` method that is (essentially) used to cancel a drag in the case that the `IDragTarget` returns `true` for `shouldPreventMove`. Before we were just moving the block back to the original coordinates, but that doesn't allow blocks to reattach to parents or children.
The agreed upon design has a good separation of concerns between the draggable and the dragger. Giving the draggable responsibility over handling drag targets confuses that, and breaks the single responsibility principle. It also makes it more likely for an external …

fix: draggable interface and concrete dragger

---

core/block_dragger.ts
core/bubble_dragger.ts
core/config.ts
core/delete_area.ts
core/dragging/dragger.ts
core/insertion_marker_manager.ts
core/interfaces/i_delete_area.ts
core/toolbox/toolbox.ts

Fixes N/A
Removes the `couldConnect` parameter from `wouldDelete` since that doesn't really make sense in the context of generic `IDraggable` implementations.
In practice, the only thing this changes is that if you're dragging over the trashcan and the block could connect to something, the block will now be deleted instead of connecting.
N/A
N/A
This is a dupe of https://github.com/google/blockly/pull/7848
Dependent on https://github.com/google/blockly/pull/7967

fix!: remove couldConnect parameter from wouldDelete

---

demos/code/index.html

The colour-picker is leaving core.
Removing the colour blocks means that any stored programs that use colour blocks will no longer load.  However, since the code demo has no visual output, the colour blocks serve no use.  An examination of the database shows no usable programs which use the colour blocks.
Resolves #7826
Resolves #7938

chore: Remove colour blocks from code demo.

---

core/generator.ts
generators/dart/procedures.ts
generators/dart/text.ts
generators/javascript/procedures.ts
generators/lua/procedures.ts
generators/lua/text.ts
generators/php/procedures.ts
generators/python/procedures.ts

Previously generators could generate code from inputs that didn't exist and get back the empty string.  This silent failure was causing problems for diagnosing issues.  This PR changes the behaviour so that an error is thrown.
This will break generators which rely on the previous behaviour.  Several of our demo blocks needed editing to accommodate this change.
Resolves #7665

feat!: Throw errors on missing inputs

---

core/dragging/block_drag_strategy.ts

Fixes #7840
Adds a block drag strategy to confirm to the new dragging API. Most of this is just taken from the existing block dragger.
Tested with following PRs that change the gesture system. Once those are in I can do some more thorough testing.
N/A
Dependent on https://github.com/google/blockly/pull/7968

feat: add block drag strategy

---

core/block_svg.ts
core/dragging/block_drag_strategy.ts

Fixes #7841 
Has the `BlockSvg` delegate to a `IDragStrategy` (which external devs can supply). This makes the blocks use the new drag system, and allows external devs to customize how blocks handle drags.
Tested manually with a following PR that updates the gesture system to use the dragger and raggables.
N/A
N/A

feat: have blocks use drag strategy

---

core/comments/rendered_workspace_comment.ts
core/comments/workspace_comment.ts
core/dragging/comment_drag_strategy.ts

Fixes #7842 
Moves workspace comments to use the new dragging API. This does not actually enable dragging because this also needs fixes in the gesture (next PR)
Tested with the next PR that dragging does work - although I messed something up with the CSS :P
N/A
N/A

feat: make comment a draggable

---

core/comments/workspace_comment.ts
core/events/events_comment_base.ts
core/events/events_comment_change.ts
core/events/events_comment_create.ts
core/events/events_comment_delete.ts
core/events/events_comment_move.ts
core/xml.ts
tests/mocha/comment_view_test.js
tests/mocha/event_comment_change_test.js
tests/mocha/event_comment_create_test.js
tests/mocha/event_comment_delete_test.js
tests/mocha/event_comment_move_test.js
tests/mocha/event_test.js
tests/mocha/index.html
tests/mocha/old_workspace_comment_test.js
tests/mocha/workspace_comment_test.js

Work on #7909  
Changes all of the comment events to use new workspace comments classes instead of the old ones.
Updates the create and delete events to use JSON.
Updates the workspace comments classes to fire create and delete events.
Updates tests. Adds tests for firing the events. Manually tested undo and redo for create and delete events.
N/A - docs for events are just reference docs, which are automatically generated.
N/A

fix: comment create and delete events

---

core/icons/comment_icon.ts
core/interfaces/i_comment_icon.ts
tests/mocha/block_test.js

Fixes N/A
When writing up docs for how to override comment icons I realized that the interface didn't really deal with serialization, when it should. These edits remedy that.
N/A
This is for docs!
N/A

fix: comment icon interface re serialization

---

core/widgetdiv.ts

Work on #7819
If the div `blockyWidgetDiv` already exists, store it inside `containerDiv` doing the same `document.querySelector`, creating the constant `container` and appeding the already existing `containerDiv` as a child.
Covered in #7819
Same tests passed before and after the PR.
N/A
N/A

fix: Assign to containerDiv blockyWidgetDiv if it already exists

---

core/shortcut_items.ts

Fixes https://github.com/google/blockly/issues/1915
Prevents default actions for events where we trigger undo or redo.
Tested with my next PR, which relies on this behavior. (Undoing and redoing comment change events, which edit a text area)
N/A
N/A

fix: prevent default undo

---

core/comments/rendered_workspace_comment.ts
core/gesture.ts

Fixes N/A
Makes it so the gesture handles starting drags on comments. The code for starting drags is going to get refactored an unified in a bit, but I wanted to be able to test the comment dragging before then.
Manually tested, and drags to occur!
N/A
N/A

feat: support dragging comments in the gesture

---

core/flyout_base.ts
core/flyout_button.ts
core/keyboard_nav/ast_node.ts
core/renderers/common/marker_svg.ts

Makes it possible to support keyboard navigation of flyout buttons, which is listed as a limitation in the documentation:
https://developers.google.com/blockly/guides/configure/web/keyboard-nav
- Create new AST Node type for flyout buttons. A marker for a flyout button resembles one used for a stack.
- Implement `IASTNodeLocationSvg` into the `FlyoutButton` class. This is necessary in order to be able to create a navigation cursor around a flyout button.
- Add methods `setContents()` and `getContents()` for flyouts. These are used to be able to return an ordered array of blocks and buttons, necessary for navigating the contents of a flyout.
- Add new `navigateFlyoutContents()` function which supports traversing next/previous flyout items.
These changes will make it possible for users to …

feat: support keyboard navigation of flyout buttons

---

core/comments/comment_view.ts

Fixes N/A
I set the scope for the comment colour variables to be a bit too restrictive :P The drag surface is not part of the workspace because then we wouldn't be able to drag over the trashcan! So when we moved the comment to the drag surface it lost its colours.
Also at some point the delete icon was made visible by default which we don't want.
Tested that comments are still properly colourful 🌈 when dragging.
N/A
N/A

fix: comment colours when dragging

---

core/comments/rendered_workspace_comment.ts
core/comments/workspace_comment.ts
core/events/events_comment_change.ts
core/events/events_comment_move.ts
tests/mocha/workspace_comment_test.js

Work on #7909  
Fixes the comment move and comment change events to be fired at the correct times and whatnot.
All tests pass.
Manually tested undo and redo work correctly.
N/A
N/A

fix: comment move and change events

---

blocks/procedures.ts
core/block_svg.ts
core/bubbles/bubble.ts
core/bubbles/mini_workspace_bubble.ts
core/bubbles/text_bubble.ts
core/bubbles/textinput_bubble.ts
core/clipboard/block_paster.ts
core/comments/rendered_workspace_comment.ts
core/common.ts
core/contextmenu.ts
core/dragging/block_drag_strategy.ts
core/gesture.ts
core/interfaces/i_selectable.ts
tests/mocha/comment_deserialization_test.js

Fixes N/A
Makes it so the gesture class looks at whatever is selected when it starts a drag. This will allow the multi select plugin to provide its own draggable for when multiple things are selected.
Manually tested and everything seems to be working! But this could definitely use some hammering.
* Dragging blocks
* Dragging child blocks
* Dragging the workspace
* Dragging flyouts
* Dragging blocks from the flyout
* Dragging on child blocks in the flyout
* Dragging blocks in mutators
N/A
N/A

feat!: change gestures to look at selected when dragging

---

core/block_svg.ts
core/dragging/block_drag_strategy.ts

Fixes N/A
https://github.com/google/blockly/pull/7991 Broke dragging shadow blocks, but this PR fixes it again.
Tested that dragging shadows, including shadows who are children of shadows, drags the nearest parent real block
N/A
N/A

fix: dragging shadow blocks

---

core/blockly.ts
core/gesture.ts
core/internal_constants.ts

Fixes N/A
Deletes the useless `DRAG_STACK` value which was not being respected, and is now not even being referenced.
N/A
N/A
N/A

chore!: delete drag stack

---

tests/browser/test/workspace_comment_test.js

Fixes N/A
Adds some visual tests to theoretically catch bugs in the future.
This is tests!
N/A
N/A

chore: add webdriver tests for workspace comments

---

core/block_svg.ts

Work on https://github.com/google/blockly-samples/issues/2311
Adds a `toFlyoutData` method to the `BlockSvg` so that we can add it to the backpack without knowing its exact type.
Manually tested that the output looks correct (it's the same logic that currently exists in the backpack plugin). I can add unit tests, but kinda wanted this to go in the beta today.
N/A
N/A

feat: add toFlyoutData method for compatibility with backpack

---

core/comments/comment_view.ts
core/comments/rendered_workspace_comment.ts
core/gesture.ts

Fixes https://github.com/google/blockly/issues/8007
Adds visually highlighting workspace comments when they are selected
N/A
N/A

feat: visual comment selection

---

core/dragging/bubble_drag_strategy.ts

Fixes N/A
Bubbles were being returned to the `BLOCK` layer when they should have been returned to the `BUBBLE` layer.
Tested that bubbles are now properly always on top of blocks.
N/A
N/A

fix: bubbles not being returned to the correct layer after drag

---

core/insertion_marker_previewer.ts

Fixes N/A
Insertion markers were firing move events when they became the top blocks in a stack. Insertion markers shouldn't fire events, so I disabled this.
Tested that these erroneous events are no longer fired.
N/A
N/A

fix: insertion marker firing move event

---

core/css.ts

Fixes https://github.com/google/blockly/issues/7680
Makes it so the grabbing cursor actually shows up when you're dragging a block.
Tested that the grab cursor properly shows up when dragging.
N/A
N/A

fix: drag cursor

---

core/dragging/block_drag_strategy.ts
core/trashcan.ts

Fixes N/A
See PR title.
Tested that blocks that didn't have parents when their drag started are properly returned to the `BLOCK` layer.
N/A
N/A

fix: blocks not being returned to the correct layer if their drag is reverted with no parent

---

core/field_dropdown.ts

Fixes https://github.com/google/blockly/issues/7890
Ensure that the dominant baseline for the arrow symbol on dropdown fields is 'center'. The exception is when a field's text element's dominant baseline should not be centered. Previously this was true for certain browsers (IE and Edge), but now it's only true for the Geras renderer. (https://github.com/google/blockly/blob/9e05d69d2accba5dca97b39281b322a2ec0961d3/core/renderers/geras/constants.ts#L15)
Screenshots are of the Advanced Playground, renderer set to Thrasos on Safari. No regressions found for other renderers or other browsers.
**Before:**
**After:**
When using the Thrasos renderer on Safari, all arrows in dropdown fields appear too high. This is evidently because Safari does not inherit the property dominant-baseline: "central" …

fix: correct dropdown arrow placement for Thrasos on Safari

---

core/dragging/dragger.ts
core/gesture.ts
core/registry.ts

Fixes N/A
Discussed over standup, and everyone had very small opinions about how this should be named. I ended up reverting draggers back to have the inaccurate "BLOCK_DRAGGER" name because I think there are more people using the scroll options plugin than there are people implementing their own blocks draggers. And this decreases the burder on the scroll-options folks.
For folks that are implementing their own block draggers it will be a bit annoying because the registry's types are so lax  they won't get a compiler warning, so they'll have to find out their stuff is broken at run time.
Build passes.
Updated pending docs change.

fix: revert dragger name

---

core/comments/rendered_workspace_comment.ts
core/shortcut_items.ts

N/A
Related to #8006
Makes it so the rendered workspace comment implements the `IDeletable` interface. The comment will now be deleted if you drag it over the toolbox or trashcan, or if you use the delete key while it is selected.
Manually tested that deleting works in the three outlined cases:
* Deleting over the toolbox.
* Deleting over the trashcan.
* Deleting using the keyboard shortcut.
N/A
Going to fix the context menu option separately, since that needs more work.

feat: add ability to delete workspace comments

---

core/blockly.ts
core/clipboard/workspace_comment_paster.ts
core/comments/rendered_workspace_comment.ts
core/serialization/workspace_comments.ts
core/workspace.ts
core/workspace_svg.ts

Fixes #8008 
Integrates the new `RenderedWorkspaceComment` with the copy paste system.
Manually tested that copying and pasting works properly. Including with text, collapsed comments, resized comments, etc.
N/A
N/A

feat!: add ability to copy and paste workspace comments

---

core/block_svg.ts
core/blockly.ts
core/comments/rendered_workspace_comment.ts
core/contextmenu.ts
core/contextmenu_items.ts
core/contextmenu_registry.ts
core/gesture.ts
core/workspace_svg.ts
tests/playground.html

Fixes #8005 
Makes it so that context menu options can be registered to apply to workspace comments. To support one option that creates a workspace comments at the click position, I also had to pass the original right click event to all of the callbacks.
Also upgrades the old workspace comments context menu options to work with the "new" (several years old at this point :P ) context menu system.
Manually tested that context menu options work.
N/A
N/A

feat!: Add context menu options for workspace comments

---

core/shortcut_items.ts

Fixes #8006 
Fixes the cut keyboard shortcuts to work with workspace comments.
Other shortcuts were fixed by other incremental fixes (e.g. fixing copy paste).
Manually tested that delete, copy, cut, and paste all work with workspace comments.
N/A
Dependent on https://github.com/google/blockly/pull/8035

fix: comment keyboard shortcuts

---

core/comments/comment_view.ts

Fixes N/A
In samples the comment text areas weren't the correct height.
In core they were because the playground sets:
```css
html, body {
height: 100%;
}
```
Disguising the issue.
I didn't want to change the CSS for a core class (like `blocklyMinimalBody`) to also declare height 100% because that could break other random implementations. Instead I set the height and width on the text area explicitly, which is also what the `TextInputBubble` does to handle this same problem.
Tested by linking with samples.
N/A
N/A

fix: comment text area size in samples

---

core/comments/comment_view.ts
tests/playground.html

Fixes N/A
Makes it so that comments can not be resized unless the comment is editable.
Manually tested that the comment cannot be resized. Tested that the cursor looks correct (default) in LTR and RTL.
The playground was actually broken in read-only mode because it was trying to access a flyout that didn't exist :P So I'm just fixing that as part of this.

chore: fix comments being resizable when readonly

---

core/comments/comment_view.ts

Fixes N/A
The comment highlight was being positioned incorrectly in RTL mode (it was to the right of where it should be. Now it is properly positioned.
Manually tested that the highlight is positioned correctly in RTL.

fix: comment highlight being positioned incorrectly in RTL

---

scripts/gulpfiles/package_tasks.js
scripts/package/templates/node.template

Reintroduce  shims (`dist/core.js`, `dist/blocks.js`, `dist/javascript.js`, etc.) for submodule entrypoints in top level of package.  Have them created by `package_tasks.js` directly, rather than being copied from `scripts/package/`.
Assumptions:
- Such bundlers will _completely_ ignore the exports declaration.
- The bundles are intended to be used in a browser—or at least not in node.js—so the core entrypoint never needs to route to `core-node.js`.  This is reasonable since there's little reason to bundle code for node.js, and node.js has supported the exports clause since at least v12, considerably older than any version of node.js we officially support.
- It suffices to provide only a CJS entrypoint (because we can only provide CJS or ESM, not both.  (We could in future switch to …

fix(build): Reintroduce shims for subpackage entrypoints

---

blocks/loops.ts
blocks/procedures.ts

There's no need to record and replay these events since the change will happen automatically anyway.
Resolves #7951

fix: Don't record undo events for enable/disable

---

core/icons/comment_icon.ts

Discussed this fix offline with @BeksOmega.
Fixes two related issues: 
* Comment bubbles were being duplicated when a workspace is loaded with a comment that is already expanded
* Comment bubbles were being created and orphaned whenever insertion markers were being created by the InsertionMarkerPreviewer

fix: prevent duplication of comment icon bubbles

---

core/field.ts
core/field_angle.ts
core/field_input.ts
tests/mocha/field_angle_test.js
tests/mocha/field_number_test.js
tests/mocha/field_textinput_test.js

Fixes https://github.com/google/blockly/issues/7966
This propagates the `fireChangeEvent` parameter to the `doValueInvalid_` method, and uses it to conditionally inhibit the default behavior of firing a block change event when a field is assigned an invalid value.
I also made a significant change to the way `doValueInvalid_` reverts the field value. Previously, it copied the value from `this.htmlInput_!.getAttribute('data-untyped-default-value')`, which is always a string value. However, this doesn't really make sense for number fields, which usually contain a numerical value even when editing the associated text input widget. I replaced it with `this.valueWhenEditorWasOpened_` which is the exact value the field used to have.
Finally, I conditionally skip firing the block change event if …

fix!: Only fire intermediate events when editing input with invalid text.

---

core/flyout_base.ts

This PR adds a method for serializing a block to the flyout, which is used during the block dragging/creation process. This will allow subclasses to override it to customize the block that gets created on the target workspace.
This is needed by scratch-blocks to ensure that newly created blocks have different IDs from their source blocks in the flyout, to allow uniquely identifying blocks.

refactor: split out block serialization for creating new blocks from the flyout

---

blocks/loops.ts
blocks/procedures.ts

This reverts commit 1a8e4d9e691fd7ed8fb00295918f67c4c61937e6.
While we want this change, we'd rather keep the develop branch clean and obtain the change via back-ports from the v11 branch.

Revert "fix: Don't record undo events for enable/disable"

---

core/dialog.ts
tests/mocha/contextmenu_items_test.js
tests/mocha/dialog_test.js
tests/mocha/index.html
tests/mocha/test_helpers/workspace.js

Fixes https://github.com/google/blockly/issues/7882
Makes it so the `setX` dialog methods assign directly to the property on the exported namespace tree instead of to an internal variable.
Fixes a problem for Scratch where they didn't have a good place for their dialog code to live.
Added tests that assigned dialogmethods can take in extra parameters.
This is pretty niche so I don't think it needs explicit documentation.
This doesn't have to go into v11, I just put it up against that in case it can be reviewed in time.

feat: allow the dialog methods to take in extra parameters

---

package.json
scripts/gulpfiles/build_tasks.js
typings/msg/yue.d.ts

Work towards #7449
Introduce an `import` conditional export for each of the entrypoints (`blockly`, `blockly/core`, `blockly/blocks`, `blockly/javascript`, etc., `blockly/msg/en`, `blockly/msg/fr`, etc.), and point these at wrappers created by `build_tasks.js`
that import the corresponding `index.js` / `<chunk>_compressed.js` / `msg/<lang>.js` CJS module and `export` its named exports.
Providing ESM entrypoints, even ones that are just wrappers of the existing CJS entrypoints, is the first step towards publishing Blockly as a pure-ESM package.
* Verified that `npm test` runs successfully.
* Verified that `import * as … from 'blockly/…'` works correctly and as expected when run in node.js.
* Verified that `npm test` runs successfully in blockly-samples `rc/v11.0.0` branch, when linked …

feat(build)!: Introduce ESM entrypoints

---

core/block_svg.ts
core/comments/rendered_workspace_comment.ts
core/grid.ts

Now that there are two things that snap (blocks and WS comments), the alignment code in being moved to a common place.
Resolves #8060

feat: Add snapping to workspace comments.

---

scripts/gulpfiles/package_tasks.js

Set `"type": "commonjs"` in the generated `dist/package.json` file, since the `.js` files in the package root are CJS.  This should be a no-op since that's the default, but by setting it explicitly we ensure that any change to the repository top-level package.json to set "type": "module" won't break the published package accidentally.
As described this should be a no-op, but by publishing it now in v11 it will help discover any compatibility issues with 3rd party build tools that might change how the process the package when it is present.
* Passes `npm test`
* Passes `npm test` in blockly-samples when linked against a `dist/` build with this change.
* Passes manual test of importing and requiring blockly in node.js.
No changes to manual test procedures needed.

chore(build): Set `"type": "commonjs"` in `dist/package.json`

---

core/serialization/blocks.ts
core/xml.ts

We must continue to support existing XML and JSON serialization formats since they are in external databases.
The decision was taken not to make the save formats compatible with older versions of Blockly.  We could not think of a convincing use-case for a newer Blockly's output to be read by an older Blockly.  If such a case appears, then our decision should change.
Resolves #8095.

fix: Remove deprecation warnings for 'disabled'.

---

core/block_svg.ts

Fixes #8102 
Makes it so that blocks in the flyout have the `blocklyDraggable` CSS class, even though they aren't actually draggable. The flyout detects a drag, duplicates the block, and then starts a drag on the new block.
Buggy fixing.
Manually tested and all tests pass.
N/A
I'm not 100% sure that we actually want blocks in the flyout to have the `blocklyDraggable` class since they are draggable but also kind of aren't. But we can deal with that in V12 with the CSS refactor.

fix:  drag cursor being incorrect for flyout blocks

---

core/insertion_marker_previewer.ts

Fixes https://github.com/google/blockly/issues/8096
Returns early before positioning the insertion marker if the insertion marker is ded.
Deals with race condition where sometimes the insertion marker can be hidden before a queued positioning of it occurs, which causes an error.
Neil said he'd test this for me since it's easier for him to reproduce the race condition!
N/A
I don't think this is a race condition we can fix by being clever. I think this is just the cost of waiting for the browser to queue an animation frame before rendering.

fix: connection db error for insertion markers

---

core/serialization/blocks.ts

Fixes https://github.com/google/blockly/issues/7599
Add code to fire VAR_CREATE event when a JSON is serialized and new variables are created while creating a block.
Fixes the bug of variable create event not being fired, even though a variable is created when a block is created through JSON serialization.
Manually tested that the VAR_CREATE event fires when a variable is created during JSON serialization.
N/A
N/A

fix: JSON deserialization not firing variable create events for blocks

---

core/comments/rendered_workspace_comment.ts

Fixes #8117
Return the appropriate bounding box if the workspace is in RTL or not
Fixing bug
Tested in playground

fix: workspace comment bounding box affecting RTL zoom

---

core/dragging/dragger.ts

Work on https://github.com/google/blockly/issues/8124
Makes it so that any possible delete events fired by `disposed` are grouped with any possible move events fired by draggables.
Makes it so when you undo a deleted that happened over a drag targets the draggable gets returned to its original location at the start of the drag.
Fixes blocks but workspace comments are still broken. I think that's because of https://github.com/google/blockly/issues/8112

fix: undoing block delete over trashcan creates block in wrong place

---

core/bubbles/textinput_bubble.ts

Fixes https://github.com/google/blockly/issues/8144
Rearranges some transforms to make it compatible with how the resize handle is styled now. (scale is applied via css transform so we need to apply the position via X and Y attributes)
Manually tested, comment and block resize handles are correctly positioned in RTL and LTR.
N/A
N/A

fix: comment handle position in RTL

---

core/block.ts
core/block_svg.ts
core/dragging/block_drag_strategy.ts
core/gesture.ts

Fixes https://github.com/google/blockly/issues/8137
Reverts the old code for dragging shadows, which delegated to parents, and instead just select the parent from the beginning.
Click events still get fired on the shadow though because that's based on the start blocks not the selection.
Manually tested dragging and deleting by shadows.
N/A
N/A

fix: dragging blocks by shadows to delete

---

core/comments/comment_view.ts
core/comments/rendered_workspace_comment.ts
tests/mocha/workspace_comment_test.js

Fixes https://github.com/google/blockly/issues/8115
Makes it so the bounding rect of the comment is properly reported when it is collapsed.
N/A
N/A

fix: comment size not respecting collapsed-ness

---

core/comments/comment_view.ts

Fixes https://github.com/google/blockly/issues/8116
For some reason we were setting the size of the text area even though it's already set to `100%` of parent. The explicit setting of the size wasn't accounting for the height of the top bar, which is why the bottom border was hidden.
Manually tested, and bottom border appears correctly.

fix: comment text area bottom border hidden

---

core/bubbles/textinput_bubble.ts
core/comments/comment_view.ts
core/comments/rendered_workspace_comment.ts

Fixes multiple rendering and sizing issues across different browsers.
Tip: `text-overflow: hidden;` is not legal CSS and did nothing.
Resolves #8142

fix: Properly size comments.

---

core/comments/rendered_workspace_comment.ts

Fixes https://github.com/google/blockly/issues/8159#issue-2306127588
Broken by https://github.com/google/blockly/pull/8136
Makes it so we don't error if the view is undefined.
So what happens is we have this stack trace:
```
rendered_workspace_comment.ts:136 console.trace
getBoundingRectangle	@	rendered_workspace_comment.ts:136
getBlocksBoundingBox	@	workspace_svg.ts:1619
getContentMetrics	@	metrics_manager.ts:195
getMetrics	@	metrics_manager.ts:393
getWidth	@	workspace_svg.ts:1216
saveWorkspaceComment	@	xml.ts:68
CommentCreate	@	events_comment_create.ts:46
fireCreateEvent	@	workspace_comment.ts:65
WorkspaceComment	@	workspace_comment.ts:60
RenderedWorkspaceComment	@	rendered_workspace_comment.ts:52
callback	@	contextmenu_items.ts:619
(anonymous)	@	contextmenu.ts:124
setTimeout (async) …
```

fix: creating comments in RTL

---

core/block_animations.ts
core/css.ts
core/dragging/dragger.ts
core/layer_manager.ts

Fixes #8098 
Hacks some things around to get delete animations to work. Everything should be internal. Please check!
Once we add an animation API we'll need to add those side effect requirements to the dragger docs.

fix: delete area animation

---

core/bubbles/textinput_bubble.ts
core/comments/comment_view.ts

Merge the CSS so that both comment types (block and workspace) are the same -- other than a border.
This also resolves some alignment issues that show up exclusively in Safari.

fix: Normalize CSS between comment types

---

tests/browser/test/field_edits_test.js
tests/browser/test/test_setup.js

Fixes https://github.com/google/blockly/issues/7332
1. Add helper to get the svg root of the main blockly workspace to be clicked on
2. Add helper to get the svg root of the mutator workspace to be clicked on
To make a helper that can be used to click the main workspace or the mutator workspace
Manually tested that the clickWorkspace and clickMutatorWorkspace functions click on the main workspace svg root and the mutator workspace svg root respectively
N/A
N/A

feat(tests): Browser test helper to get workspace svg root

---

scripts/gulpfiles/build_tasks.js

Fixes https://github.com/google/blockly/issues/8174
Makes it so that lang files with dashses can be imported properly by changing the name of the import we use to use underscores instead.
https://github.com/google/blockly/issues/8174 no longer reproduces.
N/A
This needs to go in the patch this week.

fix: lang file imports

---

core/block.ts
core/dragging/block_drag_strategy.ts
core/dragging/dragger.ts
core/gesture.ts

Fixes https://github.com/google/blockly/issues/8171
This handles shadow block dragging behavior in a very non-generalized but backwards compatible way. As far as I can think, there's no way for it to be both generalized and backwards compatible, so I chose backwards compatibility.
Our requirements are:
1) We need shadows to be the thing being dragged, so that custom draggables can duplicate instead of dragging shadows.
2) We need non-customized shadow blocks to drag their parent blocks.
3) We need non-customized shadow blocks to dispose of their root blocks when they're dragged over a delete area.
Our constraints are:
1) We can't change the signature of `dispose` in `IDeletable` because it would with the block `dispose` parameters.
5) We can't change anything else about `IDeletable` …

fix: dragging and disposing of shadows

---

core/inject.ts
tests/mocha/keydown_test.js

Fixes #8187
Bind the keydown event to the workspace's injection div rather than the HTML document
See #8187 for details.
I modified the unit tests which deal with keydown events.  I also tested it manually in Chrome, Firefox and Safari on a Mac.
The docstring for `bindDocumentEvents` was changed to reflect the change in the code.  I don't believe that that docstring is exposed in the reference documentation.
In theory, this might be considered a breaking change, in that a developer might be depending on the current behavior, even though it is undocumented and possibly confusing to their users.  It is also possible that a developer might have some code which, for some reason, is expecting the event to be bound to the document.

fix: change which element keydown is bound to from document to injection div

---

core/dragging/block_drag_strategy.ts

Fixes https://github.com/google/blockly/issues/8189
The issue was we weren't properly clearing the state of the current candidate connection, so the preview was incorrect causing blocks to disconnect and disappear, because the place they were trying to be inserted was invalid.
To explain that slightly more linearly:
1) You start with a nested stack of 3 statement blocks, built from the inside out.
2) The middle block's current candidate connection is its child, because the state from when it connected to its child was never cleared.
3) You disconnect the middle block, and it finds the parent as the valid candidate, but the current candidate (its child) is better (I.e. closer) because its state was never cleared. So we use the current candidate instead.
4) The child blocks gets …

fix: statement input blocks disappearing

---

core/bubbles/textinput_bubble.ts
core/icons/comment_icon.ts
core/interfaces/i_comment_icon.ts
core/xml.ts
tests/mocha/block_test.js
tests/mocha/comment_test.js

Fixes  #8230
This PR preserves the positions of block comments when (de)serializing a workspace.
We allow users to position block comments arbitrarily, but while we preserve the location of workspace comments when (de)serializing the workspace, block comments have their positions lost. This is also needed to support the Scratch modernization effort, since Scratch persists block comment locations as well.
This PR modifies the ICommentIcon interface to have two additional methods: `setBubbleLocation(location: Coordinate): void` and `getBubbleLocation(): Coordinate | undefined`. If you have a class that implements ICommentIcon, you'll need to implement these methods as well. They should set and retrieve the location of the comment bubble/box, in workspace coordinates.

feat!: Add support for preserving block comment locations.

---

core/comments/comment_view.ts

…ize change listeners
This PR stores the workspace comment size at the start of a drag on the resize handle, and reports that value to size change listeners. Previously, because the comment was continuously resized during the drag, but size change events were only fired at the end, the "old" comment size calculated in the method that fires the size change event was identical to the new size, so size change listeners were misinformed.

fix: correctly report the pre-resize-drag size to workspace comment size change listeners

---

core/events/events_abstract.ts

This makes the `getEventWorkspace_()` method in the abstract event class public. This is widely used and a general purpose convenience function, so probably should have had the internal annotation removed some time ago.

chore: make getEventWorkspace_() public

---

.github/workflows/build.yml

Add node.js v22.x to list of versions to test Blockly on.
Keep up to date; find any v22 incompatiblities.
Improved.

test(CI): Add node.js v22.x to build matrix

---

.github/workflows/appengine_deploy.yml
.github/workflows/build.yml
core/comments/comment_view.ts
core/events/events_abstract.ts
demos/blockfactory/app_controller.js
demos/blockfactory/factory.css
demos/blockfactory/index.html
package-lock.json
package.json

Bring over some recent changes in develop into the v12 branch.

chore: merge develop into v12

---

.github/workflows/build.yml

Have the GitHub `build` workflow, which runs our tests, use `npm ci` instead of `npm install` when installing dependencies.
This should help ensure that CI catches PRs that update `package.json` without updating `package-lock.json` to match.
Proposed in response to breakage caused by PR #8209.

test(CI): Have GitHub use `npm ci` instead of `npm install`

---

core/block_svg.ts
core/renderers/common/drawer.ts

Fixes #7212
This PR adds a `getBoundingRectangleWithoutChildren()` method to BlockSvg that returns the bounding box for the block alone, not including its children (for C blocks) or subsequent blocks in the stack.
There was no public API to retrieve this information, and it's useful.

feat: allow fetching block bounds not including children.

---

core/block_svg.ts

Fixes a bug in the just-introduced getBoundingRectangleWithoutChildren() where it used the childful instead of childless width field.

fix: use the correct with in getBoundingRectangleWithoutChildren().

---

core/icons/comment_icon.ts
core/icons/mutator_icon.ts
core/icons/warning_icon.ts

Fixes Rename the blockly icon CSS classes to use camelCase [#8329](https://github.com/google/blockly/issues/8329)
Rename the following CSS classes and references to them:
.blockly-icon-comment -> blocklyCommentIcon
.blockly-icon-warning -> blocklyWarningIcon
.blockly-icon-mutator -> blocklyMutatorIcon

fix!: rename the blockly icon CSS classes to use camelCase (#8329)

---

core/field.ts

Added  `.blocklyField` to `fieldGroup_` using `dom.addClass()`
https://github.com/google/blockly/issues/8289

feat: Add blocklyField to field's SVG Group

---

core/block_svg.ts
core/renderers/common/i_path_object.ts

This PR updates the `IPathObject` Interface to make following methods optional:
- `applyColour`
- `setStyle`
Fixes #8279

fix!: Make `IPathObject` styling methods optional

---

core/block_svg.ts

This PR add `addClass` and `removeClass` methods, which accept the class name as a parameter and can be used to perform the `dom.addClass` call rather than calling it directly.
Fixes #8270

refactor: Add `addClass` and `removeClass` methods to blockSvg

---

core/blockly.ts
core/interfaces/i_variable_map.ts
core/interfaces/i_variable_model.ts

Fixes #8072.
This PR adds formal interfaces for variable maps and models.
This is needed to enable Scratch to upgrade to modern Blockly, and adds useful extension APIs for all developers.

feat: add the IVariableMap and IVariableModel interfaces.

---

core/toolbox/category.ts
tests/mocha/comment_deserialization_test.js
tests/mocha/toolbox_test.js

- This commit renames the blocklyTreeRow CSS class to blocklyToolboxCategory.
- The commit was made against v12.0.0 branch
- It is a breaking change

fix!: Rename `blocklyTreeRow` and `blocklyToolboxCategory` CSS classes

---

core/bubbles/text_bubble.ts

Fixes #8331 Add a blocklyTextBubble CSS class to the text bubble
Added a call to dom.addClass that adds a blocklyTextBubble CSS class to the this.svgRoot
`dom.addClass(this.svgRoot, 'blocklyTextBubble');`

feat: Add a blocklyTextBubble CSS class to the text bubble #8331

---

core/variable_model.ts

Fixes #8073
This PR updates the VariableModel class to conform to the newly-added IVariableModel interface.

refactor: make VariableModel implement IVariableModel.

---

.npmrc
package-lock.json
package.json

Fixes CI failures in (and obsoletes) #8248.
* Set `legacy-peer-deps=true` in `.npmrc`.
* Add one peer dependency that had not been explicitly (dev)depended upon.
* Upgrade `@blockly/` plugin dev deps to `@latest`.
Enabling `legacy-peer-deps`:
* Doesn't install a second, probably out-of-date copy of Blockly in `node_modules/blockly/`.
* Prevents version conflicts when trying to update `@blockly/*` dev dependencies, beacuse npm doesn't seem to be clever enough to resolve peer dependency version conflicts for the `blockly` package when updating plugins (which have blockly as a peer), even if all plugins are updated at the same time.
* Brings the configuration of the blockly repo in line with blockly-samples, for whatever that is worth.  (Might avoid problems during monorepo migration.) …

chore(deps): Enable `legacy-peer-deps`, update `@blockly/` plugins

---

core/renderers/common/path_object.ts

Fixes #8262,
Added a blocklyShadow CSS class to shadow blocks' root SVG
Please let me know, if any changes are needed. 
Also, I am not sure why is it showing 4 commits, I only added in the `path_object.ts`

feat: Add a blocklyShadow class

---

core/toolbox/category.ts

Fixes #8347 
This pull request is for renaming blocklyTreeIcon with blocklyToolboxCategoryIcon. 
This is marked as a breaking change.
Pull request is created against rc/v12.0.0 branch.

fix!: renamed blocklyTreeIcon Css class to blocklyToolboxCategoryIcon #8347

---

core/menu.ts
core/menuitem.ts

Fixes Replace Closure UI CSS classes with Blockly CSS classes #8286 
replaces all instances of the deprecated goog-menuitem, goog-menuitem-disabled, and goog-menu CSS classes
with the corresponding blocklyMenuItem, blocklyMenuItemDisabled, and blocklyMenu classes
This change ensures that the code
follows the updated styling guidelines and removes dependency on the old Closure UI library.
Please let me know, if any changes are needed.

fix!: Replace Closure UI CSS classes with Blockly CSS classes

---

core/block_svg.ts

This PR overrides the `jsonInit` method in the `BlockSvg` class to get the css class names from the `classes` field and apply the same using the `addClass` method. 
Fixes #8271

feat: Add css classes from json block definitions

---

core/toolbox/category.ts
core/toolbox/collapsible_category.ts
core/toolbox/toolbox.ts

Fixes [#8344](https://github.com/google/blockly/issues/8344)
This Pull Request renames the `blocklyToolboxContents` CSS class to `blocklyToolboxCategoryGroup`. All references to the old class name have been updated accordingly.

fix!: rename `blocklyToolboxContents` to `blocklyToolboxCategoryGroup`

---

core/toolbox/toolbox.ts

Added  `blocklyToolboxFlyout` CSS class to the `flyout_`  before adding it to DOM
Fixes https://github.com/google/blockly/issues/8341

feat: Add blocklyToolboxFlyout CSS class to the flyout

---

.github/workflows/build.yml

Works around https://github.com/nodejs/node/issues/53902 / https://github.com/npm/cli/issues/7657 et al.
CI is currently broken due to upstream issues in node.js and/or npm.
We'd like some.
Issue #8392 created to remind us to unpin.

chore: Pin node.js v22 to v22.4.1 in CI

---

core/interfaces/i_variable_map.ts
core/interfaces/i_variable_model.ts
core/registry.ts
core/serialization/variables.ts
core/variable_model.ts

This PR revamps the new variable interfaces in response to issues encountered during implementation. Specifically:
* `save` and `load` are moved from IVariableMap to IVariableModel. In the case where somebody wants to add additional properties to their variables, this means they need only subclass/implement IVariableModel, and not also have to replace the variable map solely to handle serialization. 
* `getWorkspace()` is added to IVariableModel; the existing VariableModel had this property, and it's often necessary to determine which workspace a variable is associated with.
* `addVariable()` is added to IVariableMap. Again, this allows for simple variables-with-extra-fields without having to subclass the VariableMap in order to change the method signature of `createVariable`  to …

refactor: update the variable interfaces.

---

core/variable_map.ts
core/variables.ts
core/workspace.ts
tests/mocha/variable_map_test.js

Fixes #8074 
This PR makes the existing VariableMap class implement the new IVariableMap interface. I also changed the backing store from a map of arrays to a map of maps, since this made implementing the new methods easier and allowed for efficiency improvements in some of the existing ones.

refactor: make VariableMap implement IVariableMap.

---

blocks/loops.ts
blocks/procedures.ts
blocks/variables_dynamic.ts
core/block.ts
core/events/events_var_base.ts
core/events/events_var_create.ts
core/events/events_var_delete.ts
core/events/events_var_rename.ts
core/field_variable.ts
core/interfaces/i_variable_backed_parameter_model.ts
core/names.ts
core/serialization/blocks.ts
core/variable_map.ts
core/variable_model.ts
core/variables.ts
core/variables_dynamic.ts
core/workspace.ts
core/workspace_svg.ts
core/xml.ts
generators/php/procedures.ts
generators/python/procedures.ts
tests/mocha/xml_test.js

Fixes #8370 
This PR updates core to use IVariableModel rather than hard-coding VariableModel. It also updates code that was directly accessing properties on VariableModel to use the getter/setter methods defined in the IVariableModel interface.

refactor: Use IVariableModel instead of VariableModel.

---

core/names.ts
core/variable_map.ts
core/variables.ts
core/workspace.ts
tests/mocha/variable_map_test.js

-[x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change)
Fixes #8371, #8079, #8075
This PR uses IVariableMap in place of hardcoding VariableMap. It also refactors variable deletion handling; the VariableMap methods `getVariableUsesById` and `deleteVariableById` are deprecated and moved to the `Variables` namespace.
The `VariableMap.deleteVariable` method now unconditionally deletes uses of the variable in question as well.

refactor!: Use IVariableMap instead of VariableMap

---

core/block.ts
tests/mocha/blocks/procedures_test.js

Fixes https://github.com/google/blockly/issues/8310
When any disabled reason is removed, and the workspace is configured to not allow manually disabling/enabling, and a block is currently disabled for the manual reason, remove the manual reason in addition to whatever reason initiated the change.
A legacy serialized workspace does not specify the reason why blocks are disabled. When loaded with blocks that had been disabled due to being orphaned but without a recorded reason, Blockly defaults to using the manually disabled reason. However, some workspaces are configured to disallow disabling/enabling blocks, in which case the user can't remove the manually disabled reason.
For the specific case where a workspace does not allow manually disabling or enabling blocks, and a block currently …

fix: Enable blocks if user can't manually enable them.

---

core/variable_model.ts
tests/mocha/variable_model_test.js

This PR refactors the `VariableModel.load()` method to use the new variable-related APIs, adds docs to methods that were missing them, makes the VariableModel workspace `readonly`, and cleans up the names of private fields and tests that were accessing them.

refactor: clean up VariableModel.

---

core/field.ts
core/field_dropdown.ts

Fixes: #8277
**feat: Remove references to getFastTextWidth (#8277)**

fix: Remove references to getFastTextWidth (#8277)

---

core/field_input.ts
core/renderers/common/constants.ts
core/renderers/zelos/constants.ts

Fixes: #8287
**chore!: Rename editing CSS class to blocklyEditing (#8287)**

fix!: Rename editing CSS class to blocklyEditing (#8287)

---

core/bubbles/mini_workspace_bubble.ts

This PR add `blocklyMiniWorkspaceBubble` css class to the `MiniWorkspaceBubble` constructor.
Fixes #8340

feat: add `blocklyMiniWorkspaceBubble` css class

---

core/field_variable.ts
core/variable_map.ts
core/variable_model.ts
core/workspace.ts
tests/mocha/field_variable_test.js
tests/mocha/variable_map_test.js

Fixes #8083
This PR deprecates the variable-related methods in `Workspace` that simply pass through calls to the `VariableMap`. Callers should retrieve the VariableMap from the workspace and call the corresponding methods on it.
Several internal methods that are not in the variable interfaces, have been moved to the Variables namespace, or are unnecessary have been deleted.

refactor: deprecate and clean up variable-related methods.

---

core/block_svg.ts

Code Changes:
- Added a condition in the setEditable method to check the editability of the block.
- Utilized dom.addClass to add the blocklyNotEditable class when this.editable_ is false.
- Utilized dom.removeClass to remove the blocklyNotEditable class when this.editable_ is true.
Fixes #8266

feat: Add a blocklyNotEditable CSS class to the block's root SVG

---

core/field.ts

Part of #6895
This PR removes the `@internal` annotation from various Field methods that should be accessible by subclasses.

chore: Removed @internal annotation from public Field methods.

---

core/dragging/block_drag_strategy.ts
core/dragging/bubble_drag_strategy.ts
core/dragging/comment_drag_strategy.ts

Fixes https://github.com/mit-cml/workspace-multiselect/pull/62#issuecomment-2225465398
We should add a condition check so that we don't unset the group ID that is not set by us, otherwise, the multi-select plugin undo/redo will be broken (apply individually instead of all together)
If not, then a monkey patch will be needed on the multi-selection plugin side.

fix: drag strategy only clear group id set by us

---

core/css.ts
core/dropdowndiv.ts
core/menu.ts

… style to :focus
Fixes #8326
Remove the blocklyFocused class from being assigned in menu.ts and dropdowndiv.ts
Change the styles in css.ts to use the :focus css pseudo class
Removed the blocklyFocused class from being assigned in menu.ts and dropdowndiv.ts
Changed the styles in css.ts to use the :focus css pseudo class
Not necessary 
No it won't affect anything. just some minor css changes

fix: use `:focus` pseudo class instead of `blocklyFocused`

---

core/component_manager.ts
core/flyout_base.ts
core/toolbox/toolbox.ts
core/trashcan.ts
core/zoom_controls.ts

Fixes https://github.com/google/blockly/issues/8417
I created an enum codifying the weights for the flyout, toolbox, trashcan, and zoom buttons, and provided weight values that give the toolbox higher precedence than the flyout.
When the pointer is dragging a block from the workspace to a toolbox or flyout, the drag target areas may overlap, in which case we should decide which should take precedence and handle the event. The flyout's drag area intentionally extends beyond its own bounds, but if the toolbox is also present, then the flyout's bounds include the toolbox. Currently, the flyout and the toolbox have the same weight but the flyout happens to be found first and effectively takes precedence. However, it would be more intuitive for the toolbox to take precedence when the pointer …

fix: Codify component weights with toolbox in front of flyouts.

---

core/events/events.ts
core/events/events_var_type_change.ts
core/events/utils.ts
tests/mocha/event_var_type_change_test.js
tests/mocha/index.html

Fixes #8080
This PR adds a new event type to be fired when a variable's type is changed. Actual firing of the event will be included in a future PR.

feat: Add a VarTypeChange event.

---

core/field_image.ts

fixes #8314 
This pull request introduces a change to the `FieldImage` class in Blockly to enhance the styling capabilities of image fields. By adding the `blocklyImageField` CSS class to the `fieldGroup_` element, developers can now apply custom styles more easily to image fields within Blockly.
- Modified the `initView` method in `core/field_image.ts` to call `dom.addClass` with `this.fieldGroup_` and `'blocklyImageField'`.
The `initView` method has been updated to ensure that the `blocklyImageField` CSS class is applied to the `fieldGroup_` element whenever an image field is initialized. This addition enhances the flexibility for developers to customize the appearance of image fields using CSS.
- This change has been made against the `rc/v12.0.0` branch.
By adding the …

Added blocklyImageField CSS class to image fields 

---

core/block_svg.ts

Added `blocklyNotDeletable` CSS class to `block_svg`.
#8265

feat: added `blocklyNotDetetable` class to block_svg

---

core/block_svg.ts

Fixes #8268 
This PR adds the `prototypeName` as a CSS class to the SVG group element of each block in the `BlockSvg` constructor. This enhancement allows for easier styling and identification of blocks based on their prototype.
- Modified the `BlockSvg` constructor to add the `prototypeName` as a CSS class to `this.svgGroup_` using `dom.addClass()`.
- Improved block identification in the DOM
- Enhanced styling capabilities for specific block types
This change is backwards-compatible and provides a hook for future enhancements or debugging.

feat: add the block's type as a CSS class to the block's root SVG

---

core/field_label.ts

Fixes [Issue #8315](https://github.com/google/blockly/issues/8315)
This pull request adds a `blocklyLabelField` CSS class to label fields in the `FieldLabel` class by modifying the `initView` method to call `dom.addClass` with `this.fieldGroup_` and `blocklyLabelField`.
This change helps in applying specific styles to label fields, allowing better customization and theming of Blockly components.
I tested these changes manually by creating and manipulating label fields in the Blockly playground. Additionally, I verified that the `blocklyLabelField` class is applied correctly in different scenarios.
No additional documentation is needed for this PR.
No additional information.

feat: add `blocklyLabelField` css class to label field

---

core/toolbox/category.ts

The pull request renames all references to blocklyTreeIconOpen to blocklyToolboxCategoryIconOpen
Fixes #8348

fix!: Rename blocklyTreeIconOpen to `blocklyToolboxCategoryIconOpen`

---

core/field_number.ts

Fixes #8313
This PR adds a 'blocklyNumberField' CSS class to the FieldNumber element. Specifically:
- Implements the `initView` method in the FieldNumber class
- Applies the 'blocklyNumberField' class to the fieldGroup_ element
- Adds a null check for fieldGroup_ to prevent TypeScript errors
This change allows for more specific styling of number fields in Blockly, as requested in issue #8313. It provides a way to target number fields specifically in CSS, enhancing the ability to customize the appearance of these fields.
I manually tested these changes by:
1. Creating a block with a number field
2. Inspecting the DOM to verify that the 'blocklyNumberField' class was applied
3. Applying CSS to the new class and verifying that it affected only number fields
Additional unit tests could be …

feat: Add a blocklyNumberField CSS class to number fields 

---

core/field_variable.ts

This PR adds a protected `getDefaultType()` method to FieldVariable. Scratch needs this to add menu items to the dropdown dependent on the type (list, regular variable, broadcast message) and it's conceivable that other subclasses may need this information as well, which is currently inaccessible to them.

feat: add a method for subclasses of FieldVariable to get the default type.

---

core/bubbles/bubble.ts
core/comments/rendered_workspace_comment.ts

Fixes 
#7675 (https://github.com/google/blockly/issues/7675)
1. Workspace comments now move to the block layers when selected.
2. All bubbles (including block comments) move to the top layer when selected.
The comments/bubbles raise when dragged a pixel, so it make sense for them to be raised when they are selected.
I don't see how automated tests could be used here.
I tested the changes with comments, block comments, and bubbles opened by mutators. 
No changes needed
No additional information

fix:  comments and bubbles on click

---

package-lock.json
package.json
tests/browser/test/toolbox_drag_test.mjs

Addresses the issues described in: https://github.com/google/blockly/issues/8132
Updates the dev-tools dependency, and removes references to obsolete toolbox categories `'Colour'` and `'Angles'`.
dev-tools no longer references obsolete categories, and https://github.com/google/blockly-samples/pull/2346 removed test block categories.
Previously passing tests still pass. The `toolbox_drag_test.mjs` file in `npm run test:browser` was failing previously and is still failing, but less badly. In particular, the `'Drag'` test toolbox category is still failing even after my changes, because https://github.com/google/blockly-samples/pull/2377 added a test block to this category called `'drag_to_dupe'` that duplicates itself after dragging, which results in the workspace containing two top-level …

fix: Update dev-tools, remove toolbox category tests Colour and Angles

---

core/toolbox/category.ts

fixes https://github.com/google/blockly/issues/8351
This pull request updates the CSS class names associated with the selection state of toolbox categories in Blockly. The changes improve clarity and consistency by aligning the CSS class naming with the context in which they are used.
- **Renamed CSS Classes:** Updated the CSS class name from `blocklyTreeSelected` to `blocklyToolboxSelected` across the relevant files. This change reflects the role of the class in styling the selected state of toolbox categories rather than tree elements.
- **CSS Style Updates:** Adjusted the CSS selectors to use the new class name, ensuring that all styling for selected toolbox categories remains functional.
The renaming of CSS classes enhances code readability and maintainability by making it clear which …

fix!: Renamed the blocklyTreeSelected CSS class to blocklyToolboxSelected

---

core/block_svg.ts

Added the `blockStyleName` as a CSS class on the block. Also called `dom.removeClass` with `this.styleName_` to remove any previous style.
#8269

feat: added block's style as a CSS class to block's root SVG

---

core/css.ts

2. blocklyResizeLine
3. blocklyResizeSW
4. blocklyResizeSE
5. blocklyDropDownButton
Fixes issue #8285 
Link: https://github.com/google/blockly/issues/8285
I have deleted the styles blocklyHidden,  blocklyResizeLine, blocklyResizeSW, blocklyResizeSE and blocklyDropDownButton
from css.ts
These styles are deleted as they are not used by any other classes
executed commands 
npm run build
npm run format and npm test commands.
All 10 tests passed
No documentation required

fix!: deleted styles without associated classes from css.ts, issue #8285

---

core/block_svg.ts

Fixes #8233 
Removes the `@internal` from the JSDoc, adds some info about the cost of the function, and also removes an extra colon in the JSDoc.
Described in the original issue #8233 
Tested manually with browser console in the playground (although I believe the function was working before this, as this change only relates to JSDoc).
Yes, documentation for [`BlockSvg`](https://developers.google.com/blockly/reference/js/blockly.blocksvg_class) should include the `bringToFront()` method.

feat: expose `bringToFront()` method

---

core/workspace_svg.ts

Fixes #8281 
Implements `addClass` and `removeClass` methods to the `WorkspaceSvg` class.
As requested in #8281 
Ran the usual build/test scripts and also made sure it worked okay in the playground.
Yes, add docs for the new methods

feat: implement `WorkspaceSvg` class manipulation

---

tests/browser/test/toolbox_drag_test.mjs

Fixes #8466 
Removed the ‘Drag’ category from the blocks tested by toolbox_drag_test.mjs.
This change ensures that the test only includes blocks that add exactly one block to the workspace upon being dragged, aligning with the test’s original intent.

chore: removed the whole Drag category from the browser test

---

core/comments/comment_view.ts

Fixes https://github.com/google/blockly/issues/8413
This removes an obsolete CSS property on the workspace comment top bar that overrides the mouse cursor style to be the grab cursor. Other CSS rules affecting the workspace comment have the same cursor, and additionally switch to a different cursor when dragging over the trash can, so removing this property allows those switches to take effect.
The CSS property was added in https://github.com/google/blockly/commit/e4b734c0db537032a36ae907ba7af20bb5bb41f7 a couple months ago and was necessary at the time because there wasn't any other style at the time that provided the drag cursor for workspace comments. However,  https://github.com/google/blockly/commit/4cdca28fe5c92ce883cc597d517d01531bf8770e was added more recently and provides the …

fix: Let workspace comment have delete cursor over trash.

---

blocks/variables.ts
blocks/variables_dynamic.ts
core/field_variable.ts
core/flyout_button.ts
core/variables.ts

This PR resolves several issues when deleting variables:
* Fixes a regression introduced in v12 where deleting a variable from the menu in the flyout would prompt to confirm that you wanted to delete the other blocks referencing that variable in the flyout
* Fixes #8528, where deleting a variable from the menu in the flyout would not warn if only one block referencing that variable existed in the main workspace
`Blockly.Variables.deleteVariable()` now takes an optional third argument, `triggeringBlock`, corresponding to the block that triggered the deletion, which is used to filter it out of the list of block references correctly when determining whether to prompt the user. Before, it simply assumed that if there was one reference that was the block that triggered the deletion, but …

fix: improve prompting when deleting variables

---

core/events/utils.ts
core/workspace.ts

Cleanup work adjacent to fixes for #2037 and #8225.
* Don't call `filter` function from `Workspace.prototype.undo`.
* Delete post-fire undo/redo queue filtering from `fireNow`.
Use of the `filter` function in `Workspace.prototype.undo` was intended to reduce the number of events that would need to be run when undoing or redoing, but because it mutates and sometimes deletes stacked events this has caused problems with repeated undo/redo (see issue #7026).  The originally-chosen fix for which was the addition (in PR #7069) of code to `fireNow` to post-filter the `.undoStack_` and `.redoStack_` of any workspace that had just been involved in dispatching events; this apparently resolved the issue but added considerable additional complexity and made it difficult to reason about how events are …

refactor(events): Don't filter events before undo

---

core/bump_objects.ts
core/events/predicates.ts
core/events/type.ts
core/events/utils.ts
core/icons/mutator_icon.ts
core/procedures.ts
core/trashcan.ts

* Introduce predicates for testing `Abstract` event subclasses based on their `.type` properties.  These are useful because there are places where it is not possible to use `instanceof <ClassConstructor>` tests for type narrowing due to load ordering issues that would be caused by the need to `import` (rather than just `import type`) the class
constructors in question.
* Simplify several sections of code by using these type predicates for type narrowing, and thereby avoiding the need for explicit casts.
Cleanup and preparation for fixing #8225 et al.
* Passes `npm test`.
* Trashcan behaviour has been tested manually to ensure refactor has not broken anything.
The type predicates are not currently reexported from `core/blockly.ts`.  This could be done by adding suitable `export … from …` …

refactor(events): Introduce and use event type predicates

---

core/css.ts
core/menu.ts
core/menuitem.ts

Fixes Remove blocklyMenuItemHighlight CSS class and use :hover CSS selector #8327 
Remove the blocklyMenuItemHighlight CSS class from the [menu item](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/menuitem.ts#L73).
Use the [:hover CSS pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) in [css.ts](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L481).

fix!: Remove the blocklyMenuItemHighlight CSS class and use the hover

---

core/variables.ts

When deleting a variable with one or more references in the workspace from the dropdown/contextual menu of the variable blocks in a non-autoclosing flyout, the number of references in the  prompt confirming the deletion was off by one. This PR fixes this by not including the block triggering the deletion (in the flyout) in the reference count.

fix: display the correct variable reference count when deleting a variable.

---

core/block.ts
core/block_svg.ts
tests/mocha/block_test.js

Partially addresses: https://github.com/google/blockly-samples/issues/2426
Detects whether deleting a block would delete the currently selected block, and if so, deselects it *before* severing connections.
When a shadow block is selected, an ancestor of that block receives a visual highlight. If the shadow block is then deleted (e.g. because it was replaced with a real block via the shadow block converter plugin), then the highlighted block no longer has any relationship to any selected block. That highlight should go away, but currently it persists and may continue to persist while making further changes to the selection.
Note that `Block.dispose()` severs a connection, and `Block.disposeInternal()` also severs connections, so we need to determine whether any parent block needs to be …

fix: Detect if deleting shadow block affects selection highlight

---

core/events/utils.ts
tests/mocha/event_test.js

Fixes #2037, #8225
* Remove the broken `BlockChange` event reordering code from `filter`.  Instead, do necessary event reordering in a new (and hopefully more robust and less buggy) `enqueueEvent` function called from `fireInternal` as events are fired.
* Since (as of #8537) we don't filter in undo any more, and filtering in reverse order is confusing and can cause problems, prepare to remove this opportunity for error by deprecating calling `filter` with `forward=false`.
* Simplify `filter` by having it consider only adjacent events in the queue for merging.  Previously any events in the queue could potentially be merged if they were of suitable (typically identical) `.type`, even if other events had occurred between them (with the sole exception of `BlockMove` events, which would only …

fix(events): Simplify `filter` function, add new `enqueueEvent` function

---

core/renderers/common/marker_svg.ts

Necessary for continued keyboard experimentation.
Make private properties protected so that they can be overridden in a subclass.
This will need a beta to be usable in keyboard experimentation.

feat: mark some marker_svg properties protected instead of private

---

core/flyout_horizontal.ts
core/flyout_vertical.ts

This PR updates the flyout classes to use the pre-existing `getWidth()` and `getHeight()` methods instead of directly accessing the corresponding instance variables. This broadly improves code health, and concretely allows subclasses to e.g. enforce a fixed/maximum width or height by overriding the appropriate getter. This is needed by Scratch: https://github.com/gonfunko/scratch-blocks/issues/153

refactor: use getters for flyout width and height.

---

core/flyout_base.ts

This PR improves performance of flyouts. Previously, flyouts were reflowing/repositioning their contents in response to every event fired by the flyout workspace; this was particularly problematic during populating the flyout, when blocks being added/removed could cause this to happen hundreds of times. Scrolling the flyout also triggered continuous relayouts due to viewport change events. Reflowing is now only triggered in response to block change events, which can legitimately require it when e.g. the user types into a field in a block in the flyout and the flyout needs to resize to accomodate the block's new dimensions.
Additionally, the flyout was also listening to all events from the main/target workspace, and running a handler to check for and disable blocks over the maximum allowed …

fix: improve flyout performance

---

core/utils/dom.ts

Re-fixes #8277
Recently, code that was calling `getFastTextWidth()` was updated to call `getTextWidth()` instead, because `getFastTextWidth()` required knowledge of some styling attributes. Historically, these were derived from the theme/renderer, but with recent changes to move towards using CSS for this purpose, it was thought that we needed to use `getTextWidth()` instead, which relied on the `getComputedTextLength()` method of SVG text elements.
Unfortunately, `getComputedTextLength()` has a significant limitation: it doesn't work when the SVG text element (or any of its parents) has `display: none` or similar set. This could result in blocks being incorrectly sized when manipulated while not visible, e.g. https://github.com/gonfunko/scratch-blocks/issues/163.
This PR modifies the …

fix: size text with computed styles even when hidden

---

core/bubbles/textinput_bubble.ts
core/comments/comment_view.ts
core/utils/drag.ts
core/workspace_svg.ts

Fixes https://github.com/google/blockly/issues/7926
This PR transfers the logic from `WorkspaceSvg` methods `startDrag` and `moveDrag` into a new utils file. It further factors out some shared coordinate math into a private function. It removes the private property `dragDeltaXY` from `WorkspaceSvg` (is this a breaking change?) and replaces it with an internal map from workspace to delta.
This feature is used by block comments and workspace comments, but is not generally used by workspace objects and thus is not really appropriate for `WorkspaceSvg`.
Manually dragging and resizing comments seems to work as expected. I don't believe any existing tests directly call these methods on a workspace, maybe some do indirectly, but FWIW all existing tests pass.
N/A
Is removing a private property …

fix: Factor out workspace drag methods into utils.

---

core/field_variable.ts

Blockly has two sets of variables: those in the main workspace, and those that exist solely in the flyout. The latter were not included in the dropdown list of variables shown by FieldVariable however; this PR resolves that. This fixes https://github.com/gonfunko/scratch-blocks/issues/149.

fix: include potential variables in variable dropdowns in the flyout

---

core/workspace_svg.ts

This PR removes a redundant call to `Flyout.position()` in `WorkspaceSvg`. The code calls `Toolbox.position()` on the previous line, which [in turn calls `Flyout.position()`](https://github.com/google/blockly/blob/develop/core/toolbox/toolbox.ts#L723), so the flyout was needlessly being positioned twice.

refactor: remove redundant flyout positioning.

---

blocks/lists.ts
blocks/text.ts

Fixes https://github.com/google/blockly/issues/8556
I modified the following block type definitions:
- `lists_getIndex`
- `lists_setIndex`
- `lists_getSublist`
- `text_getSubstring`
Each of these had an input called `AT` with an attached field called `WHERE`. The input and its attached field were sometimes removed and recreated in response to the field's validator. This PR instead attaches the field to a separate dummy input, such that the field does not need to be recreated every time the input is recreated.
Edits to the field did not always fire a BlockChange event. In particular, if the user is trying to change the field's value to its default value, but the field gets recreated, then the recreated field will already have the default value and thus no change is detected.
All existing …

fix: Simplify list and text WHERE validation

---

core/field.ts
tests/mocha/jso_serialization_test.js

Fixes https://github.com/google/blockly/issues/8588
Also fixes https://github.com/google/blockly/issues/6456
Creates a change group before performing any field validation, and uses this group for the field value change event.
There are field validators in the core blockly library that make workspace changes in response to field value changes. For example, the block `list_getIndex` creates or destroys an input connection depending on the value of a dropdown. However, these changes do not get grouped with the field value changes, which causes problems when undoing.
This PR also allows change listeners to retroactively create changes that are grouped with the changes that they are responding to, which is a technique that is already used by some plugins but is incompatible with fields that …

fix: Group field validator changes with field value changes.

---

core/interfaces/i_flyout_inflater.ts
core/registry.ts

Fixes #8540
This PR adds a new IFlyoutInflater interface that will be used to create and dispose of arbitrary elements that may live on a flyout's workspace. Future PRs will add concrete implementations and refactor the flyout to use them.
This will allow for developers to add additional, arbitrary types of elements to flyouts.

feat: Add the IFlyoutInflater interface.

---

core/button_flyout_inflater.ts
core/flyout_button.ts
core/label_flyout_inflater.ts

Fixes #8544 and fixes #8545.
This PR adds `IFlyoutInflater` implementations for buttons and labels. Both buttons and labels are represented by instances of `FlyoutButton`, which has been slightly refactored to implement `IBoundedElement` and `IRenderedElement` to comply with the expected API.

feat: Add inflaters for flyout labels and buttons.

---

core/flyout_separator.ts
core/separator_flyout_inflater.ts

This PR adds a new `FlyoutSeparator` class to represent a gap between items in a flyout, and a corresponding flyout inflater for items of this type. This will allow flyouts to no longer have to track gaps and content in separate lists, and instead just use one list of content items, some of which are rendered blocks/buttons/labels/etc and some of which are invisible spacers that simply occupy space between other items.

feat: Add support for inflating flyout separators.

---

core/block_flyout_inflater.ts

Fixes #8541 and fixes #8542.
This PR adds a concrete implementation of IFlyoutInflater responsible for creating blocks in the flyout. It also includes the existing capacity filtering logic. Because recycling is not used in core, recycling support is not included; it will be added in a subclass in the continuous toolbox plugin.

feat: Add a BlockFlyoutInflater class.

---

demos/blockfactory/block_library_controller.js
demos/blockfactory/block_library_view.js
demos/blockfactory/blocks.js
demos/blockfactory/factory.js

Fixes https://github.com/google/blockly/issues/6820
Makes a record of all of the reserved block type names that are required by the old block factory workspace on startup, and uses that to determine whether a user-defined block type has a conflicting name, instead of assuming the current definitions in `Blockly.Blocks` is an authoritative proxy for the reserved types.
The desired behavior is to prevent replacing critical blocks that are used by the block factory, like core Blockly blocks or even block-factory-specific blocks like `factory_base`. The existing strategy is to refuse to overwrite any block type that is currently recognized by the definitions in `Blockly.Blocks`, and to support this strategy, whenever the factory defines a user-defined block in this mapping, it always [removes …

fix: Let old block factory overwrite user defined blocks.

---

core/widgetdiv.ts

Fixes #8599
This PR updates `WidgetDiv.hideIfOwnerIsInWorkspace()` to hide the widget div if its owner is an indirect child of the given workspace, e.g. the given workspace is the root workspace but the widget div is owned by a child of a mutator workspace. AFAIK workspaces are only ever nested one level deep in practice, but I'm not aware of anything that enforces that, so it attempts to walk up an arbitrarily deep workspace hierarchy.

fix: Fix bug that prevented dismissing the widgetdiv in a mutator workspace.

---

core/field_input.ts
core/workspace_svg.ts
tests/mocha/field_textinput_test.js

Fixes #8596
This PR introduces a new `WorkspaceSvg.getAbsoluteScale()` method that returns the absolute scale of a workspace, taking into account whether it is in a flyout, nested in one or more parent workspaces, mutator editors, etc. Workspace scaling is somewhat counterintuitive in that workspaces that are children of one another have multiplicative scaling, because scaling is achieved through transforms and those apply to child elements and compound. 
The PR also updates field editors, which are visually associated with a particular workspace but live at the top of the DOM, to use the absolute scale of their visually-associated workspace.

fix: Fix bug that caused fields in the flyout to use the main workspace's scale.

---

core/blockly.ts
core/flyout_base.ts
core/flyout_horizontal.ts
core/flyout_vertical.ts
core/keyboard_nav/ast_node.ts
tests/mocha/flyout_test.js

Fixes #8546
This PR updates the base, horizontal and vertical flyout classes to use the newly introduced inflaters rather than hardcoding support for buttons/labels/blocks. As a result, it's now possible to add arbitrary elements of different types to flyouts.
This is a fairly extensive refactor, and makes several changes to the behavior of flyouts. At a high level, support for recycling blocks has been removed. This always required a subclass to enable, and is still achievable through subclassing, but the mostly-inaccessible code that partially supported it has been removed. The continuous toolbox plugin in blockly-samples, which did use recycling, will be updated to implement it using the new API.
Additionally, the backing mats/rects placed behind blocks in the flyout have been removed. …

refactor!: Update flyouts to use inflaters.

---

core/generator.ts

This PR removes a comment suggesting that the code falls back to a backwards compatibility path that is no longer present. The code in question was removed in https://github.com/google/blockly/commit/75007a064c1849ddc0ffadc05f7475dc63f3dd8b#diff-1f7f2233af4c61fb9680419c9a4203252eee09ff2f85a9cd6c6c86e585da9c75, but the comment wasn't updated.

chore: Remove obsolete comment.

---

core/comments/comment_view.ts
core/comments/rendered_workspace_comment.ts
core/contextmenu_items.ts

This PR adds a `setPlaceholderText()` method to `CommentView` and `RenderedWorkspaceComment` that allows specifying the placeholder text for a comment. It also updates the workspace comment creation contextual menu item to set the default text as a placeholder instead of literal text so that users don't have to manually delete/type over it to write their comment.

feat: Allow specifying the placeholder text of workspace comments.

---

core/renderers/common/constants.ts
core/renderers/common/info.ts
core/renderers/zelos/constants.ts

Fixes https://github.com/gonfunko/scratch-blocks/issues/201
This PR updates the calculation of the height of hats on blocks. Previously, the height of a hat was the value that was used for the Y position of points on an SVG curve. However, this is not the actual Y position of e.g. the apex of the curve, but rather the Y position of the control points used to define the Bézier curve, which is different from the actual max Y value of the curve itself; note the position of the lower control points relative to the bottom of the curve in the graphic here: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#b%C3%A9zier_curves.
Per https://stackoverflow.com/a/5327329, the height of the curve is 3/4 the Y position of the control points, at least in the simple situation we use for …

fix: Correctly calculate the bounds of hat blocks.

---

core/toolbox/toolbox.ts

Fixes https://github.com/gonfunko/scratch-blocks/issues/199 and https://github.com/gonfunko/scratch-blocks/issues/187
This PR updates the code that handles repositioning the workspace in response to a toolbox item size change. It seems to have been written taking into account the normal auto-closing flyouts, but in Scratch, where the flyout is visible by default, the workspace was positioned as if the flyout wasn't present. This caused the first block dropped on the workspace to shift by the width of the flyout, and also caused blocks to be mispositioned when restoring the state of the workspace.

fix: Take the flyout into account when positioning the workspace after a toolbox change.

---

core/comments/comment_view.ts
core/comments/workspace_comment.ts

This PR unblocks https://github.com/gonfunko/scratch-blocks/issues/190 by adding an API for specifying the default size of comments.
Users can now set `Blockly.comments.CommentView.defaultCommentSize` (a static property) to the size that newly created workspace comments should default to.
Enables users to customize comment sizes for their application.

feat: Allow specifying the default size of comments.

---

core/workspace.ts

Fixes https://github.com/gonfunko/scratch-blocks/issues/210
This PR fixes a tricky bug related to workspace disposal. When a WorkspaceSvg instance A is disposed:
1. It sets `this.rendered = false`
2. It disposes of its flyout
3. The flyout disposes of its flyout workspace B
4. The flyout workspace B, as part of disposing itself, clears its variable map, which is the same as the variable map of workspace A, because when a flyout is created the parent workspace shares its variable map with the flyout
5. When the variable map clears itself, it calls VariableMap.deleteVariable for each variable it contains
6. `VariableMap.deleteVariable` calls `VariableMap.getVariableUsesById` to identify references to the variable
7. `VariableMap.getVariableUsesById` calls `Variables.getVariableUsesById`, …

fix: Fix exception when disposing of a workspace with a variable block obscuring a shadow block.

---

core/comments/comment_view.ts

Fixes https://github.com/google/blockly/issues/8626
Calls `clearTouchIdentifier()` inside the two pointerdown events for the workspace comment icons inside the CommentView class.
The two icon pointerdown event handlers inside the workspace CommentView don't ever clear the touch identifier. Click events should always call that function when bound with conditionalBind or else they leave behind an orphaned touchIdentifier that prevents all further events from firing.
N/A
N/A
Tested on the iPad simulator using ios 18.0

fix: clear touch identifier on comment icon down

---

tsdoc.json

Fixes #6338
This PR removes API Extractor rules for handling `@alias` and `@suppress`, which no longer exist in the codebase.

chore: Remove unneeded handling for @suppress and @alias.

---

core/bubbles/textinput_bubble.ts
core/icons/comment_icon.ts
tests/mocha/comment_test.js

Fixes #2917
This PR uses the regular block comment bubble, but with the textarea's `readonly` attribute set, for displaying block comments in readonly workspaces. This allows the comments to be scrolled (and their text selected/copied) and otherwise interacted with normally, while prohibiting edits.

fix: Use a readonly textarea for non-editable comments.

---

core/css.ts
core/dropdowndiv.ts
core/field_textinput.ts
core/toolbox/category.ts
core/toolbox/separator.ts
core/toolbox/toolbox.ts
tests/mocha/toolbox_test.js

* Fixes #8349
* Fixes #8350
* Fixes #8343
* Fixes #8285
* Fixes #8323
* Fixes #8312

refactor!: Improve ability to use CSS to style Blockly.

---

core/field_dropdown.ts

Fixes #6349 
This PR moves several functions that were in field_dropdown.ts, not exported, and used only by FieldDropdown, to simply be members of the FieldDropdown class in order to allow subclasses to override them.

refactor: Move functions into FieldDropdown.

---

core/css.ts
core/field.ts
core/field_checkbox.ts
core/field_dropdown.ts
core/field_input.ts

* Fixes #8319
* Fixes #2885
* Fixes #2884
* Fixes #995
This PR removes the `CURSOR` field from fields, and instead uses CSS to specify which cursor should be used for which fields. This directly fixes #8319. #2885 and #2884 are old bugs proposing adding options to inject classes into fields and refactoring the `CURSOR` field, which I believe are obsolete in light of the move to CSS. All core fields now add a class specifying the type of field, and custom field subclasses can also easily do this. As a result, users should be able to use CSS to customize the appearance of fields in general and their cursors in particular.
#995 was incidentally fixed here, since now that we're using CSS to specify cursors, it's trivial to specify the grabby cursor for fields when their parent block is being …

feat!: Use CSS to specify field cursors.

---

core/field_input.ts

Fixes #7809
This PR fixes a crash that could occur when the window was resized while a field has focus/is being edited. Calling `moveBy` on a child block is invalid, but because FieldInput was bumping its parent block (potentially nested) during resizes, that invalid code path could be triggered. Instead, the root block of the FieldInput will be bumped into bounds if needed, which is safe. `resizeEditor_()` was also updated to wait for the active render to complete, since it needs to know the bounds of its parent block, which was causing rendering glitches.

fix: Fix crash when resizing page while editing a field.

---

core/toolbox/toolbox.ts
tests/mocha/test_helpers/toolbox_definitions.js
tests/mocha/toolbox_test.js

This PR updates the toolbox to use a single `Map` for keeping track of its contents, in place of an array and an object keyed by ID. Previously, these two sources of truth needed to be kept in sync, which was error prone, and also minorly memory inefficient. Now, there is a single source of truth. This is a breaking changed because the `protected` fields `contents_` and `contentMap_` have been removed and replaced by the single `protected` field `contents`.

refactor!: Use one map for toolbox contents.

---

core/interfaces/i_toolbox.ts

Fixes #7273
This PR updates the IToolbox interface by adding `setSelectedItem()`, to pair with the existing `getSelectedItem()`. This is a breaking change; implementers of this interface will need to add this method. Blockly's core Toolbox class already does implement this method, so subclasses of that will get it for free. The linked issue requested a method to select an item by ID, but since this (a) adds a setter to an existing getter (b) is already implemented in the core Toolbox class and (c) you'd need to have an item to get its ID anyway, I think this addresses the root need and is a bit cleaner.

refactor!: Add setSelectedItem() to IToolbox.

---

core/icons/comment_icon.ts

Fixes #7855
This PR fixes a bug that caused block comments to be incorrectly positioned/overlapping their parent block when loaded into a hidden workspace that was subsequently shown.

fix: Fix bug that caused comments to be incorrectly positioned.

---

core/bubbles/bubble.ts
core/css.ts
core/grid.ts
core/inject.ts
core/renderers/common/constants.ts
core/renderers/common/path_object.ts
core/renderers/common/renderer.ts
core/renderers/geras/renderer.ts
core/renderers/zelos/constants.ts
core/renderers/zelos/path_object.ts
core/workspace_svg.ts

Fixes https://github.com/google/blockly/issues/8272
We'll need a related PR in blockly-samples that adapts the screenshot plugin to be aware of CSS vars.
Adds CSS variables scoped to the injection div referencing the SVG pattern ids so that CSS can use these consistent variable names instead of the random ids that were previously assigned to SVG attributes.
So that renderer CSS can customize and override how SVG patterns are used.
I did not create any new tests, but all existing tests pass and I manually tested that the filters appear to be rendering correctly.
N/A
N/A

fix: Create CSS vars for SVG patterns.

---

blocks/procedures.ts

Fixes #8661
This PR fixes a bug that allow enabled function caller blocks to be created on the workspace after their corresponding definition block was disabled.

fix: Disable newly created function call blocks when the corresponding definition is disabled.

---

core/css.ts
core/toolbox/toolbox.ts
tests/mocha/toolbox_test.js

* Fixes #4954
* Fixes #2188
This PR sets `user-select: none;` on the entire injection div, which prevents users from selecting text. We had already had this in place on block text, menus, and toolbox categories, but since e.g. the workspace and blocks themselves did not, long-pressing those items on mobile would also select text (often outside of Blockly) in addition to presenting the context menu. I repro'd this and confirmed the fix on an iPad, but I strongly suspect the two linked issues are the same thing; if folks with an Android and/or ChromeOS touchscreen device could confirm this also resolves the issue there, that would be great, but I'm nearly certain this resolves the problem there as well.
Note that this does not prevent selecting text in text fields, either in blocks or …

fix: Fix bug that caused text to be selected when long-pressing in the workspace on a touch device.

---

core/css.ts

Fixes https://github.com/google/blockly-samples/issues/2418
This PR removes CSS targeting the multiline input field, which has now been moved out of core into a plugin. The only rule attempted to apply monospace styling to it; I didn't migrate this to samples, because, while that field has historically been used for code, it's perfectly reasonable to use it for regular multiline text as well, and we shouldn't make an assumption either way. Developers that wish to can easily apply that style themselves.

chore: Remove CSS targeting multiline input field.

---

core/inject.ts

Fixes #397
This PR removes a dedicated `orientationchange` listener for iPads, which was apparently added due to iPads not triggering `resize` events in response to rotating the device. This special handler failed to account for multiple workspaces, but I confirmed on an iPad that rotating the device triggers regular `resize` events as expected, so I've removed the workaround entirely.

chore: Remove obsolete workaround for resize events on iPads.

---

scripts/gulpfiles/package_tasks.js

Fixes #8705
Adds `encoding: false` option to `gulp.src()` in `packageMedia()` to treat files as binary.
Without this the files are interpreted as UTF-8, which corrupts binaries like MP3s etc. This was a breaking change in gulp 5.0.0.
Manually tested with:
```
npm run package
diff -r media dist/media
```

fix: treat media files as binary while packaging them

---

core/inputs/input.ts

Fixes #8694
This PR checks if the connection in Input.setVisible() is actually a rendered connection before assuming it is. If `setVisible()` was called while initing a block, connections may not have been fully set up and this would throw.

fix: Fix unsafe cast in Input.setVisible().

---

api-extractor.json
core/block.ts
core/connection.ts
core/events/events_var_delete.ts
core/events/events_var_rename.ts
core/interfaces/i_metrics_manager.ts
core/interfaces/i_rendered_element.ts
core/menu.ts
core/metrics_manager.ts
core/renderers/common/renderer.ts
core/workspace_svg.ts

Fixes #6936
This PR resolves various warnings when generating documentation. It fixes the @link syntax in various docstrings to either be valid or disambiguate the symbol being referenced, removes @class on docstrings attached to a class, unifies docs for setters/getters to be on the getter, and updates the API Extractor config to not require leading underscores on internal symbols.
`WorkspaceSvg.getLayerManager()` is now marked `@internal`; API Extractor was complaining that the class itself was internal but had a public getter. The PR that introduced the layer manager and this method (#7619) stated that "The new system should be entirely internal.", so I believe this being public was an oversight.
The `IRenderedElement` interface is made public by this change.

chore!: Fix warnings when generating docs.

---

blocks/lists.ts
tests/mocha/blocks/lists_test.js

Fixes #8692
This PR updates the `lists_split` block's implementation to serialize the state of the mode (join vs split) field. While as the old comment notes the field validator does update this, during block serialization blocks are connected to their parents before having their field values set, so at the time of connection the field validator has not yet run to set the appropriate connection check, so the block and its parent become separated due to the connection check failing. Now, the extra state will be deserialized early, update the connection checks, and allow the block to be connected to its parent during deserialization. Note that this will not resolve already-saved projects with this issue, but it will fix it going forward.

fix: Fix serialization of the lists_split block.

---

core/variables.ts
core/variables_dynamic.ts

Fixes #1098
This PR logs a warning to the console if the regular or dynamic variables category is loaded in the flyout without its corresponding block definitions being available.

feat: Warn if a variable category is loaded without variable blocks.

---

tests/generators/index.html
tests/generators/webdriver.js

Fixes #1800
This PR updates the generator tests to not use synchronous XMLHttpRequests, which have been deprecated for some time and triggering a corresponding console warning. It also removes access to several private fields in favor of using public getters.

chore: Improve code health of generator tests.

---

core/flyout_base.ts

Fixes #785
This PR moves the call to `setResizesEnabled(true)` to after the call to `reflow()` in flyouts. The multiplayground environment with both simple and category toolboxes showed no behavioral differences with this change. I'm making this change against v12 since there are significant flyout refactors there already.

refactor: Reenable workspace resizing after reflowing flyouts.

---

core/clipboard.ts
core/shortcut_items.ts
tests/mocha/clipboard_test.js

* Fixes #8711
* Fixes #8659
This PR makes it so that, when blocks copied from a mutator workspace are pasted, they are pasted into the mutator workspace rather than the root workspace.
Previously, mutator blocks would wind up in the main workspace, where they are invalid, and it wasn't possible to copy and paste blocks within a mutator workspace.

fix: Paste blocks copied from a mutator into the mutator.

---

core/contextmenu_items.ts

This PR suppresses the Add Comment contextual menu item in mutator workspaces. Comments added there are not serialized/persisted, and broadly don't make much sense.

fix: Disallow adding comments to mutator workspaces.

---

core/trashcan.ts

Fixes #5799
This PR repositions the trashcan's flyout when the trashcan itself is repositioned, e.g. in response to workspace resize events. This fixes a bug that could cause the flyout to be detached when changing the browser zoom level or rotating a mobile device.

fix: Reposition the trashcan's flyout in response to workspace changes.

---

core/renderers/common/constants.ts
core/renderers/common/drawer.ts
core/renderers/common/info.ts
core/renderers/geras/drawer.ts
core/renderers/geras/info.ts
core/renderers/measurables/in_row_spacer.ts
core/renderers/measurables/input_row.ts
core/renderers/measurables/jagged_edge.ts
core/renderers/measurables/next_connection.ts
core/renderers/measurables/previous_connection.ts
core/renderers/measurables/round_corner.ts
core/renderers/measurables/row.ts
core/renderers/measurables/square_corner.ts
core/renderers/measurables/statement_input.ts
core/renderers/measurables/top_row.ts
core/renderers/measurables/types.ts
core/renderers/thrasos/info.ts
core/renderers/zelos/drawer.ts
core/renderers/zelos/info.ts

Fixes #6997 
This PR converts the various methods for checking the types of measurables in renderers/measurables/types.ts to be typeguards, and updates the code that calls them to remove now-unnecessary casts and instanceof checks.

refactor: Convert renderer typecheck methods to typeguards.

---

core/block_svg.ts
core/field_dropdown.ts
core/field_input.ts
core/icons/comment_icon.ts
core/icons/mutator_icon.ts
core/icons/warning_icon.ts
core/renderers/zelos/path_object.ts

Fixes #8565
This PR adds a `getStyle()` method to `BlockSvg`, and updates the rest of core to not directly access the `.style` property.

feat: Add a BlockSvg.getStyle() method.

---

blocks/procedures.ts

Fixes #8693 
This PR updates the procedure argument renaming logic to rename the variable being edited, rather than creating a new one for every keystroke and cleaning up the intermediate states when the field editor is dismissed. This prevents intermediate variables from appearing in the flyout when it is open while a procedure argument's name is being edited in the mutator.

fix: Don't create intermediate variables when renaming a procedure argument.

---

core/procedures.ts
core/variables.ts
core/variables_dynamic.ts
core/workspace_svg.ts
tests/mocha/contextmenu_test.js
tests/mocha/xml_test.js

Fixes #5580
This PR updates the variable, dynamic variable, and procedure toolbox category definitions to use the newer JSON schema in place of the older XML-based format.
Support for XML will eventually be removed, and this serves as both eating our own dogfood and a practical example of implementing a dynamic category definition with JSON which third party developers may benefit from as a reference.
* The `Element[]` return type of the `flyoutCategory()` method for each category is now deprecated. Users can opt-in to the new `FlyoutItemInfo[]` (JSON) return type by passing a second argument of `false` to the method. We expect to switch the default return type in v13.

refactor!: Use JSON instead of XML for defining dynamic toolbox categories.

---

core/block_flyout_inflater.ts
core/blockly.ts
core/button_flyout_inflater.ts
core/flyout_base.ts
core/flyout_horizontal.ts
core/flyout_item.ts
core/flyout_vertical.ts
core/interfaces/i_flyout.ts
core/interfaces/i_flyout_inflater.ts
core/keyboard_nav/ast_node.ts
core/label_flyout_inflater.ts
core/separator_flyout_inflater.ts

This PR fixes an issue that caused `findNextLocationInFlyout()` to return invalid items. With the flyout changes in v12, spacers (and potentially custom user-defined items) are included in the list of flyout contents, but are not valid keyboard navigation locations. As such, simply taking the next/previous item relative to the current one is insufficient; that item may be inspected, but if it is of a non-navigable type, the subsequent item needs to be checked until a valid navigation location is found.

fix: Fix bug that prevented keyboard navigation in flyouts.

---

core/inject.ts

Fixes #8725
This PR adds keydown listeners for the widget and dropdown divs and runs those events through the shortcut infrastructure. This allows keyboard shortcuts (e.g. esc, delete, copy/paste) to operate when a menu/dropdown is focused.

fix: Listen for keyboard shortcuts when the widget or dropdown divs have focus.

---

core/bubbles/text_bubble.ts

Fixes #8696
This PR works around a [Webkit rendering issue](https://stackoverflow.com/questions/75595621/safari-rending-svg-text-tspans-in-wrong-positions-when-using-a-rtl-language) that caused RTL text in `tspan`s to be misplaced. It changes the structure of markup in text bubbles to consist of multiple SVG `<text>` tags rather than one `<text>` tag with a series of nested `<tspan>`s. This makes rendering consistent across Chrome/Safari/Firefox. I also updated it to specify the direction, which appears to fix the comma placement issue mentioned in the bug as well.

fix: Fix display of multiline RTL strings in bubbles on Webkit.

---

core/menu.ts
tests/browser/test/basic_playground_test.mjs
tests/browser/test/delete_blocks_test.mjs
tests/browser/test/procedure_test.mjs
tests/browser/test/test_setup.mjs
tests/browser/test/workspace_comment_test.mjs

This PR fixes various failures in the WebDriver interactive browser tests, which have been neglected for some time. This PR also includes a fix for an actual bug caught by the tests where scrolling menu items into view could scroll the page itself in addition to just the menu.

fix: Fix the browser tests.

---

tests/browser/test/test_setup.mjs

This PR toggles a config option to make WebDriver not suppress dialogs/alerts, which is needed in addition to the listener added in #8735 to fix the browser tests.

fix: Actually fix the browser tests.

---

tests/mocha/workspace_svg_test.js

Fixes #8676
This largely reduces the dependence on direct value testing and instead updates clean-up tests to verify logic based on relative positioning. This guards against potential system-specific flakes that can occur when there are subtle calculation differences on different systems.
Note that the approach for improving robustness of the specific tests that were failing also provided an opportunity to clean up all of the other workspace SVG tests to make use of the same or similar helpers. I'm hoping that the latest versions are much more readable than they were previously.
For unknown reasons, different systems (such as OSX and specific versions of Ubuntu) would lead to differences in calculations for workspace tests. The tests really only needed to verify relative positioning …

fix: Improve the robustness of workspace SVG tests.

---

core/field.ts
core/renderers/common/info.ts
core/renderers/geras/info.ts
core/renderers/thrasos/info.ts
core/renderers/zelos/info.ts

Fixes #8699
This PR makes several changes around zero-width fields:
* Fields no longer prevent themselves from having zero-width by swapping their (empty) display text with a non-breaking space character
* [BREAKING] The long-deprecated support for re-rendering a field by setting its width to 0 has been removed
* [BREAKING] The `Field.NBSP` static constant has been removed
* The built-in renderers have been updated to not insert padding after zero-width fields to avoid doubled-up padding around invisible fields

fix!: Don't add padding around zero-width fields.

---

core/renderers/zelos/constants.ts

Fixes https://github.com/google/blockly/issues/8740
Update CSS class
CSS classes have changed to remove goog-x, but it was not updated here.
Tested in advanced playground.

Fix: Fix dropdown text color in Zelos

---

core/block.ts
core/block_svg.ts
core/comments/workspace_comment.ts
core/dragging/block_drag_strategy.ts
core/dragging/comment_drag_strategy.ts
core/flyout_base.ts
core/gesture.ts
core/shortcut_items.ts
core/workspace.ts
core/workspace_svg.ts
tests/mocha/keydown_test.js

Fixes #8732
This PR adds a `setIsReadOnly()` method to `Workspace` that allows dynamically toggling readonly status at runtime. Previously, the readonly option could only be set at injection time, and thus required reinjecting the workspace to modify.
For backwards compatibility, the `readOnly` field in the `options` dictionary is updated when the state is changed, since this was previously the only way to observe the readonly status. A getter, `isReadOnly()`, has also been introduced, and core has been refactored to use it.
This unblocks #8732, but also has potential instructional usecases.

feat: Add support for toggling readonly mode.

---

tests/mocha/connection_checker_test.js

Fixes #8688
This PR resolves a flaky test that was triggered by identifying blocks based on their position rather than their identifiers.

fix: Fix flaky connection checker test.

---

core/block_flyout_inflater.ts
core/button_flyout_inflater.ts
core/flyout_base.ts
core/interfaces/i_flyout_inflater.ts
core/label_flyout_inflater.ts
core/separator_flyout_inflater.ts

This PR fixes a bug in v12 that caused blocks dragged from non-primary flyouts (e.g. the trash) to be misaligned relative to the mouse. The block inflater was setting up click handlers with the flyout of the flyout workspace's target workspace (confusing, I know), on the assumption that that was the flyout in which the block was being inflated. This is not true though; the trash's flyout workspace's target workspace is the main workspace, and that workspace's flyout is the main toolbox flyout, not the trash flyout. This indirection was necessary because IFlyout passed in the flyout workspace to inflaters, so the flyout itself had to be derived when needed. This PR changes the interface to instead pass in the flyout itself (which has a getter for its workspace). This would be breaking, but …

fix: Fix bug that caused blocks dragged from non-primary flyouts to be misplaced.

---

core/menu.ts

* Fixes #8745
* Fixes #8746
This PR updates the menu to check if the pointer has actually moved before selecting the hovered menu item in response to an alleged pointer move event. Previously, it was listening for `pointerover` events, and selecting the hovered menu item. In the case where the user has their pointer over the menu, and is scrolling through the list of menu items via the up/down arrows, the menu items will scroll into view when the selection reaches the beginning/end of the visible set of menu items. This movement of elements under the pointer causes a `pointerover` event to fire, even though the pointer has been stationary, which had the effect of jumping the selection backwards to whatever menu item was under the pointer.
Although `pointerover` events have …

fix: Improve menu mouse/keyboard selection interaction.

---

core/field_dropdown.ts
core/menu.ts
core/utils/style.ts

Fixes #8762
This PR reverts #8726, which attempted to fix menu scrolling by using `scrollIntoView()`. Instead, the original scrolling utility function is reintroduced and used; the original issue was apparently that an intermediate div got introduced, so the parent element that was passed to the scrolling utility function wasn't actually the scrollable element.

fix: Fix menu scrolling.

---

core/css.ts

Fixes #842
This PR sets `pointer-events: none` on the scrollbar background, which is a small square element in the corner where a pair of scrollbars join. Previously, if a block was located in this 15x15px square, clicking and dragging on it would pan the workspace, since the click event never reached the block to focus it because it was intercepted by the scrollbar background. Now, the click will pass through to the block, which will become selected, and the subsequent drag will move the block rather than the workspace.

fix: Allow dragging blocks from the far lower right corner.

---

core/blockly.ts
core/interfaces/i_focusable_node.ts
core/interfaces/i_focusable_tree.ts

Fixes #8772
Fixes #8773
Fixes part of #8770
Introduces the necessary base interfaces for representing different focusable contexts within Blockly. The actual logic for utilizing and implementing these interfaces will come in later PRs.
These interfaces provide the foundation for introducing a central system for managing focus (see #8770 for more context).
N/A -- This is an interface-only change.
Probably not--the class documentation should be sufficient.
See also https://github.com/google/blockly-keyboard-experimentation/issues/142#issuecomment-2657938253 for broader technical design context on the introduction of these new interfaces.

feat: Add interfaces for focus management

---

core/dragging/block_drag_strategy.ts
core/dragging/bubble_drag_strategy.ts
core/dragging/comment_drag_strategy.ts
core/dragging/dragger.ts

Fixes #8764 
Moves the event group management up to dragger.ts instead of being handled in the various *_drag_strategy.ts files. Conceptually, this makes it the responsibility of the top level dragger to manage event groups and ensures that the group wraps all side effects of the drag.
In vanilla Blockly this shouldn't have any effect, but is necessary for the multi-select plugin used by AppInventor.
Also fixes a bug where snapping to the grid adds a move event that isn't part of the group.
AppInventor has a multi-select plugin that creates multiple BlockDragStrategy instances. This requires that endDrag be called on each one, which was causing the event group to be reset after the first one. Moving it up a level ensures all of the block drags finish before the event group is reset. …

fix: Fixes #8764 by moving the event grouping calls up to dragger.ts

---

core/comments/comment_view.ts
core/comments/rendered_workspace_comment.ts

Fixes #8768
This PR fixes a bug that prevented editing the text of workspace comments on Firefox.

fix: Fix bug that prevented editing workspace comments on Firefox.

---

generators/dart/logic.ts
generators/javascript/logic.ts
generators/lua/logic.ts
generators/php/logic.ts
generators/python/logic.ts

Fixes https://github.com/google/blockly/issues/8778 .
Check if 'ELSE' input exists before trying to generate code, since `generator.statementToCode` now throws instead of returning empty string.
When `STATEMENT_SUFFIX` is defined and no 'ELSE' is present, the IF block generator adds an empty 'ELSE' branch anyway - this way e.g. highlighting works correctly. So there is a code path that wants to generate code for the else branch even when the input doesn't exist.
I tested manually in playground by adding suffixes for all languages and generating code for various IF block configurations.

fix: Fix bug in IF block generators.

---

core/comments/comment_view.ts

This PR makes `CommentView` more compatible with subclassing. Scratch has a subclass, which it uses to provide a bubble-based comment view attached by a line to its parent block. This PR allows that subclass to implement `ISelectable`, which requires `this.workspace` to be public, and allows for it to correctly update its disposal state around additional disposal logic.

refactor: make CommentView more amenable to subclassing.

---

core/block_flyout_inflater.ts
core/utils/toolbox.ts

Fixes #6280
This PR removes `x` and `y` from `BlockInfo`, and removes them if set before loading and laying out blocks in a flyout. Previously, these would cause blocks to be positioned incorrectly in the flyout, since the flyout repositions its contents relative to one another but assumes their initial origin is (0, 0). The XML codepath was not subject to this issue.

fix: Disallow and ignore x and y attributes for blocks in toolbox definitions.

---

core/rendered_connection.ts

Fixes #8787
This PR un- and re-selects selected blocks when they are connected to another block. This fixes the z-ordering of the selection highlight path relative to other blocks, which prevents it from becoming partially obscured.

fix: Fix a bug where selection outlines could be cut off when connecting blocks.

---

core/contextmenu.ts
core/contextmenu_registry.ts
core/css.ts
core/extensions.ts
core/field_dropdown.ts
core/menu.ts
core/menu_separator.ts
core/utils/aria.ts

Fixes #8752
This PR adds support for separators in all Blockly menus, including contextual menus on the workspace, blocks and comments, and in dropdown menus spawned from `FieldDropdown`.
For contextual menus, separators can be added via the context menu registry in a similar manner to normal menu items:
```typescript
const separator: RegistryItem = {
separator: true,
scopeType: ContextMenuRegistry.ScopeType.WORKSPACE,
id: 'whatever-id-goes-here',
weight: 2,
};
ContextMenuRegistry.registry.register(separator);
```
For `FieldDropdown`, separators can be added via JSON (or a generator function) by using the string literal `separator`:
```typescript
{
'type': 'field_dropdown',
'name': 'SOME_DROPDOWN_FIELD',
'options': [
['Normal menu item', 'normal'],
['Other menu item', 'other'], …
```

feat!: Added support for separators in menus.

---

.github/workflows/assign_reviewers.yml
.github/workflows/conventional-label.yml

This PR attempts to fix the CI breakage by adding `contents: read` permissions. The docs indicate this is granted by default, but also suggest that if you manually specify any permission then all others are set to none.

chore: Try adding additional permissions.

---

core/keyboard_nav/marker.ts
core/marker_manager.ts
core/renderers/common/marker_svg.ts

Fixes #8794
This PR fixes the typing on `Marker.curNode` to allow for it to be null, and updates types in related methods accordingly.

fix: Allow the marker's current node to be null.

---

core/toolbox/toolbox.ts
core/trashcan.ts
core/workspace_svg.ts

Fixes #8816
Pass the modalInputs option when creating the toolbox.
The modalInputs is missing when creating toolbox, therefore, the specified modalInputs option has never been fully effective.

fix: fix bug that modalInputs option is not working in toolbox area

---

core/keyboard_nav/ast_node.ts
core/renderers/common/marker_svg.ts

Fixes #8827
This PR updates most of the static `ASTNode.create*Node()` methods to not check for null arguments (which their method signature prohibits) and not (claim to) return null when that only happened in the case of an invalid null argument. I also cleaned up several unsafe casts and non-null assertions and corrected some other typings.
* The type signature of `ASTNode.getWsCoordinate()` now allows for null return types, which were always possible but not part of the return type before
* `createWorkspaceNode()` no longer allows null workspace or coordinate arguments; it would have just returned null had either of those been provided, so callers check for that and do whatever they would have done had the return value been null.

fix!: Tighten and correct typings on ASTNode

---

core/keyboard_nav/line_cursor.ts

Fixes https://github.com/google/blockly/issues/8851
Make two methods public for use by keyboard dragging code.
See https://github.com/google/blockly/issues/8851

feat: make getNextNode and getPreviousNode public

---

core/blockly.ts
core/css.ts
core/focus_manager.ts
core/interfaces/i_focusable_node.ts
core/interfaces/i_focusable_tree.ts
core/utils/focusable_tree_traverser.ts
tests/mocha/focus_manager_test.js
tests/mocha/focusable_tree_traverser_test.js
tests/mocha/index.html

Fixes #8782
This is the bulk of the work for introducing the central logical unit for managing and sychronizing focus as a first-class Blockly concept with that of DOM focus.
While this introduces the core support needed for focus synchronization and management (along with its tests), there are some likely functional gaps that will need to be fixed in a subsequent change:
- Ensuring clicks within Blockly's scope correctly sync back to focus changes.
- Ensuring that `FocusManager` behaves in real world scenarios (i.e. those exposed by the experimental keyboard plugin). Early testing suggests that the manager handles focusing correctly, but that more work is likely needed around active/passive tracking and styling specifics, the former requiring much deeper changes in the plugin in order to …

feat: Introduce FocusManager implementation

---

core/dragging/block_drag_strategy.ts

Fixes #8869 
Create a protected helper function that can be overridden.
Keyboard drags sometimes search for the nearest compatible block on a workspace, which means an effective radius of Infinity.
No current change to functionality.
I'd like to put this into the next v12 beta release.

feat: add getSearchRadius to BlockDragStrategy

---

core/keyboard_nav/line_cursor.ts
scripts/gulpfiles/test_tasks.js
tests/mocha/cursor_test.js

Progress on https://github.com/google/blockly-keyboard-experimentation/pull/409
Add helpers that navigation and movement code can use to do loopback.
The tests were the hardest part of this. I ran into an issue with our test tooling when handling equality comparisons and diffs of objects with circular dependencies. @BenHenning and I debugged it and I will write up an issue.
But the tests check that the last node on various blocks and stacks is correct, and that it works with multiple stacks.
I moved the existing cursor tests into a subsuite named "movement", which caused indentation changes for a large block of code.

feat: add getFirstNode and getLastNode to cursor with tests

---

core/keyboard_nav/line_cursor.ts
tests/mocha/cursor_test.js

Progress on https://github.com/google/blockly-keyboard-experimentation/pull/409
- Add a `loop` parameter to `getPreviousNode` and `getNextNode` in cursor.
- Add tests for loopback and non loopback cases.
Both navigation and keyboard drags will use this to smoothly roll from the end of the workspace to the beginning and vice versa, matching standard approaches to searching.
Added tests in `cursor_test.ts`.
I got some unexpected (to me) behaviour in `getPreviousNode` but they turned out to be unexpected stack nodes. Getting rid of stack nodes is being considered already, and will require updates to these tests.
The fourth commit inlines some logic in functions in `line_cursor.ts`, but I can revert it if necessary.

feat: add loopback in cursor navigation, and add tests

---

core/css.ts
core/field_dropdown.ts
core/menu.ts

Fixes #8880
This PR fixes scrolling of contextual menus using the arrow keys. It scrolls the menu item relative to the menu, whereas previously it was scrolling the menu item relative to the menu's parent element. This worked for dropdowns (which have an intermediate div between the menu and the container), but not for contextual menus, where the menu element lived directly in the WidgetDiv. This change broke keyboard scrolling of dropdown menus, but I adjusted their styling to work similarly to context menus. This in turn allowed for the removal of a manual scroll to move the selected dropdown menu item into view, which is now handled automatically by the menu.

fix: Fix keyboard-driven menu scrolling.

---

core/dropdowndiv.ts

Fixes #8897
This PR updates the DropDownDiv to clear itself more reliably by recreating its div from scratch, rather than trying to reset/clear every conceivable property.

fix: Recreate the dropdowndiv when clearing it.

---

msg/json/en.json
msg/json/qqq.json
msg/messages.js

This PR adds several messages from the keyboard experimentation repo that I missed in #8904

fix: Add some missing message strings.

---

core/block_svg.ts
tests/mocha/block_test.js

Fixes #6020 
- Clears the collapsed block warning message when a block is expanded.
- When collapsing, checks if any children have a warning and if so adds the collapsed warnings warning.
The collapsed block warning message was set if any block in a collapsed stack added a warning, but wasn't added if there already was a warning and was never removed making it sticky on the parent even after expanding and deleting the block with the warning.

Fix: Remove the collapsed block warning when expanding a block

---

.github/workflows/assign_reviewers.yml

This PR adds the `pull-requests: write` permission to assign_reviewers.yml. The docs say it needs this or `issues: write`, but I'm suspicious it may need both.

chore: Try another workflow permission.

---

core/block_svg.ts
core/inject.ts
core/renderers/common/path_object.ts
core/workspace_svg.ts
tests/mocha/workspace_svg_test.js

Fixes #8913
Fixes #8914
Fixes part of #8771
This updates `WorkspaceSvg` and `BlockSvg` to be focusable, that is, it makes the workspace a `IFocusableTree` and blocks `IFocusableNode`s.
Some important details:
- While this introduces focusable tree support for `Workspace` it doesn't include two other components that are obviously needed by the keyboard navigation plugin's playground: fields and connections. These will be introduced in subsequent PRs.
- Blocks are set up to automatically synchronize their selection state with their focus state. This will eventually help to replace `LineCursor`'s responsibility for managing selection state itself.
- The tabindex property for the workspace and its ARIA label have been moved down to the `.blocklyWorkspace` element itself rather than its …

feat: Make WorkspaceSvg and BlockSvg focusable

---

core/keyboard_nav/line_cursor.ts
tests/mocha/cursor_test.js

Fixes https://github.com/google/blockly/issues/8901 
- Use `getPreviousNode` in `prev` and `out` methods so that the `loop` parameter can be used and set as `true`.
- Add tests for loopback in `prev` and `out` methods.
To fix https://github.com/google/blockly/issues/8901 so that cursor loops when keyboard navigating blocks backwards (up arrow keys, or left arrow keys) as it can forwards.
Added loop tests for `prev` and `out` in `cursor_test.ts`.

fix: LineCursor can loop forward, but not back

---

.github/workflows/assign_reviewers.yml

_This is a cherry-pick of #8811 into the v12 release branch._
(ish--largely relying on the original testing for this PR since it's actions-related)
This fixes the same issue as #8811 but on the v12 branch.
See #8811.
The failing assignee workflow will continue on v12 so the cherry-pick makes the next couple of PRs for this branch a bit nicer, but it's not a strong must-have since we'll eventually merge `develop` into `v12` which would then include #8811.
N/A -- There's no strong benefit from automated tests for this workflow, and it was manually tested as part of #8811 (see https://github.com/google/blockly/pull/8811#issuecomment-2822741434).
N/A -- No documentation changes are needed for this.
None.

chore: update assignment workflow permissions for v12

---

core/block_svg.ts
core/css.ts
core/inject.ts
core/renderers/common/path_object.ts
core/workspace_svg.ts

_Note: This is a roll forward of #8916 that was reverted in #8933. See Additional Information below._
Fixes #8913
Fixes #8914
Fixes part of #8771
This updates `WorkspaceSvg` and `BlockSvg` to be focusable, that is, it makes the workspace a `IFocusableTree` and blocks `IFocusableNode`s.
Some important details:
- While this introduces focusable tree support for `Workspace` it doesn't include two other components that are obviously needed by the keyboard navigation plugin's playground: fields and connections. These will be introduced in subsequent PRs.
- Blocks are set up to automatically synchronize their selection state with their focus state. This will eventually help to replace `LineCursor`'s responsibility for managing selection state itself.
- The tabindex property for the workspace …

feat: Make WorkspaceSvg and BlockSvg focusable (roll forward)

---

core/css.ts

Fixes an issue found while working on #8950 
The black outline around the selected block should not be visible when the keyboard nav plugin is not involved. Also true for the workspace, flyout, and toolbox.
Add CSS that sets outline width to zero on the focus items.
Fix visual regression.
Tested by clicking around in the playground to change focus, including
- field (during edit)
- field (after edit)
- block
- toolbox
- workspace background
- flyout
- blocks in flyout
CSS provided by @BenHenning

fix: remove black outline on focused items

---

.github/workflows/conventional-label.yml

This fixes the ongoing CI failure for the conventional auto-labeling.
This fixes the permissions in a way that should work. It may be the case that 'issues' only needs to be 'read' but I'm basically just copying what's done in https://github.com/GoogleCloudPlatform/developer-journey-app/blob/main/.github/workflows/auto-label.yml since it's working for them.
We want this workflow working--it's preferable to avoid getting used to a failing CI workflow (ideally every PR has zero CI failures).
As for the specific changes, note that the check will still fail in this PR. Similar to #8811, it's not expected that the CI workflow will pass in this PR until the change is checked in since the workflow uses 'pull_request_target'. While I haven't verified this change directly, I'm fairly confident it …

fix: Fix conventional auto labeling

---

core/workspace_svg.ts

Fixes #8874.
* Add a private property `.keyboardMoveInProgress` with associated `@internal` set method to `WorkspaceSvg` to allow `Mover` to inform the workspace when a keyboard-initiated move is in progress.
* Modify `Workspace.prototype.isDragging` to return true if `.keyboardMoveInProgress` is true as well as when a drag gesture is in progress.
Make dragging behaviour more consistent regardless of whether initiated by pointer or keyboard.
Tested manually by console calls to `.setKeyboardMoveInProgress`.
JSDocs for `.isDragging` updated to describe current behaviour.
Filed #8960 to implement a less kludgy approach once `Mover` is part of core (or can at least be more easily accessed from core than at present).

feat(WorkspaceSvg): Add support for tracking keyboard moves

---

core/block_svg.ts
core/events/events_var_create.ts
core/events/events_var_delete.ts
core/events/events_var_rename.ts
core/field_variable.ts
core/variable_map.ts
core/variables.ts
core/variables_dynamic.ts
core/workspace.ts
core/workspace_svg.ts
core/xml.ts

Fixes closure compiler warnings for calls to deprecated methods.
Part of #8945.
Delete the following methods from `WorkspaceSvg`:
- `renameVariableById`
- `deleteVariableById`
- `createVariable`
Modify the following methods on `VariableMap` to call `this.workspace.refreshToolboxSelection()` if this.workspace is a `WorkspaceSvg`, replicating the behaviour of the aforementioned deleted methods and additionally ensuring that that method is called following any change to the variable map:
- `renameVariable`
- `changeVariableType`
- `renameVariableAndUses`
- `createVariable`
- `addVariable`
- `deleteVariable`
Additionally, refactor remaining calls to deprecated `Workspace` variable methods in `core/`, and improve consistency of use of `@deprecated` JSDoc tag.
PR #8401 deprecated certain …

refactor!: Finish refactor of `WorkspaceSvg` `VariableMap` methods

---

core/keyboard_nav/ast_node.ts

Fixes https://github.com/google/blockly-keyboard-experimentation/issues/269
This PR updates ASTNode to operate only on visible inputs that are filtered by a new private method when searching for an input or field to navigate to. Previous work didn't fully address the problem as noted on https://github.com/google/blockly-keyboard-experimentation/issues/269
As above.
There are no existing unit tests to my knowledge. We have run this version of Blockly and the latest keyboard experimentation plugin in MakeCode and manually verified that the invisible navigation positions have been removed.
N/A
N/A

fix: Address remaining invisible input positions

---

core/workspace_svg.ts

Fixes #8874.
Modify `WorkspaceSvg.prototype.getGesture` to return `null` when there is a keyboard-initiated move in progress.
Allows us to remove monkey patches in `Mover`.

feat(WorkspaceSvg): Ignore gestures when keyboard move in progress

---

core/workspace_svg.ts

Fixes #8976
Only auto-close the flyout if focus is being lost to a known tree.
I noticed from testing that the system does attempt to restore focus back to the flyout after creating a variable but the auto-closing logic was kicking in due to focus being lost with the variable creation prompt open. Even though an attempt was made to restore focus, this doesn't automatically reopen the flyout (since it is primarily governed by the toolbox selection state).
One alternative might be to try and save the previously selected toolbox category and restore it, but that's tricky. This seems simpler, and also seems to largely maintain parity with pre-focus manager Blockly. Clicking outside of the toolbox with the flyout open only closes it if the click is within the toolbox itself or within the …

fix: Ensure flyout remains open after creating a variable with mouse

---

core/block_svg.ts
core/clipboard/block_paster.ts
core/dragging/dragger.ts
core/dropdowndiv.ts
core/field_dropdown.ts
core/focus_manager.ts
core/gesture.ts
core/widgetdiv.ts

Fixes #8952
Fixes #8950
Fixes #8971
Fixes a bunch of other keyboard + mouse synchronization issues found during the testing discussed in https://github.com/google/blockly-keyboard-experimentation/pull/482#issuecomment-2846341307.
This introduces a number of changes to:
- Ensure that gestures which change selection state also change focus.
- Ensure that ephemeral focus is more robust against certain classes of failures.
There are some ephemeral focus issues that can come up with certain actions (like clicking or dragging) don't properly change focus. Beyond that, some users will likely mix clicking and keyboard navigation, so it's essential that focus and selection state stay in sync when switching between these two types of navigation modalities.
Other changes:
- Drop-down div was …

fix: Synchronize gestures and focus

---

blocks/variables.ts
blocks/variables_dynamic.ts
core/field_variable.ts
core/variable_map.ts
core/workspace_svg.ts

Fixes #8975 
Wraps the refreshToolbox calls in a setTimeout so they happen after the changes to variables finish.
We were ending up in an infinite recursion as the toolbox refreshed before the variables were fully created which then tried to create the variables again.
Will need a follow-up PR to add tests for this.

fix: Replace explicit calls to refreshToolboxSelection with a workspace listener

---

core/focus_manager.ts
core/interfaces/i_focusable_tree.ts
tests/mocha/focus_manager_test.js

Fixes #8994
This removes an error that was previously thrown by `FocusManager` when attempting to focus an invalid node (such as one that's been removed from its parent).
https://github.com/google/blockly/issues/8994#issuecomment-2855447539 goes into more detail. While this error did cover legitimately wrong cases to try and focus things (and helped to catch some real problems), fixing this 'properly' may become a leaky boat problem where we have to track down every possible asynchronous scenario that could produce such a case. One class of this is ephemeral focus which had robustness improvements itself in #8981 that, by effect, caused this issue in the first place. Holistically fixing this with enforced API contracts alone isn't simple due to the nature of how these components interact. …

fix: Improve missing node resiliency

---

package.json

Version bump to cut a beta release.

chore: bump version to 12.0.0-beta.5

---

core/block_svg.ts
core/field.ts
core/flyout_button.ts
core/flyout_separator.ts
core/interfaces/i_navigable.ts
core/interfaces/i_navigation_policy.ts
core/keyboard_nav/block_navigation_policy.ts
core/keyboard_nav/connection_navigation_policy.ts
core/keyboard_nav/field_navigation_policy.ts
core/keyboard_nav/flyout_button_navigation_policy.ts
core/keyboard_nav/flyout_navigation_policy.ts
core/keyboard_nav/flyout_separator_navigation_policy.ts
core/keyboard_nav/workspace_navigation_policy.ts
core/navigator.ts
core/rendered_connection.ts
core/workspace_svg.ts

Fixes https://github.com/google/blockly/issues/8943
This PR makes `INavigable` extend `IFocusableNode`, which is useful for converting between focused items and elements in the cursor traversal. It also moves `isNavigable()` onto `INavigationPolicy` instead of `INavigable` to allow it to be overridden/configured for classes (like `BlockSvg`, `WorkspaceSvg` and `RenderedConnection`) that are effectively not subclassable.
It may be possible to remove `INavigable` entirely pending the outcome of the discussion in https://github.com/google/blockly/pull/8992#discussion_r2079376896, but this change will be desirable in any case.

refactor: Make INavigable extend IFocusableNode.

---

core/utils/focusable_tree_traverser.ts
core/workspace_svg.ts

Fixes https://github.com/google/blockly-keyboard-experimentation/issues/515
This adds `canBeFocused()` checks to all the places that could currently cause problems if a node were to return `false`.
This can't introduce a problem in current Core and, in fact, most of these classes can never return `false` even through subclasses. However, this adds better robustness and fixes the underlying issue by ensuring that `getFocusableElement()` isn't called for a node that has indicated it cannot be focused.
I've manually tested this through the keyboard navigation plugin. However, there are clearly additional tests that would be nice to add both for the traverser and for `WorkspaceSvg`, both likely as part of resolving #8915.
No new documentation changes should be needed here.
This is fixing …

fix: Improve robustness of `IFocusableNode` uses

---

core/keyboard_nav/block_navigation_policy.ts
core/keyboard_nav/field_navigation_policy.ts
core/keyboard_nav/line_cursor.ts
core/keyboard_nav/workspace_navigation_policy.ts
tests/mocha/cursor_test.js
tests/mocha/navigation_test.js

Fixes https://github.com/google/blockly-keyboard-experimentation/issues/464
This PR updates the navigation policies to not visit connections, but instead proceed directly to the connected block/field. The connection navigation policy has been left in place for now, but is mostly unreachable (outside of a connection being selected in some cases when a block is deleted). This also makes siblings/parents/children semantically accurate for blocks, fields and the workspace, and allows simplifying the `LineCursor`.

fix: don't visit connections with the cursor.

---

core/field.ts
core/field_image.ts
core/field_input.ts
core/field_variable.ts

Fixes #9005
This PR fixes several regressions in `Field` introduced by an earlier change:
* It restores the `Field.NBSP` constant, which was in fact in use
* It makes empty input fields have a reasonable minimum width
* It prevents sequential spaces from collapsing when rendering a field

fix: Fix regressions in `Field`.

---

core/block_svg.ts
core/interfaces/i_focusable_node.ts
core/workspace_svg.ts

Fixes #9043
Fixes https://github.com/google/blockly-samples/issues/2512
This replaces using BlockSvg's own ID for focus management since that's not guaranteed to be unique across all workspaces on the page.
Both https://github.com/google/blockly-samples/issues/2512 covers the user-facing issue in more detail, but from a technical perspective it's possible for blocks to share IDs across workspaces. One easy demonstration of this is the flyout: the first block created from the flyout to the main workspace will share an ID. The workspace minimap plugin just makes the underlying problem more obvious.
The reason this introduces a breakage is due to the inherent ordering that `FocusManager` uses when trying to find a matching tree for a given DOM element that has received focus. These trees are …

fix: Ensure BlockSvg is uniquely focusable on the page

---

core/field_input.ts

Fixes  https://github.com/google/blockly/issues/8821
This PR re-adds support for tabbing between editable fields to correct a regression. This is a bit complicated because, in Zelos, navigation is to blocks rather than fields for simple reporters, but it appears to work correctly in both Zelos and non-Zelos renderers.

fix: Reenable support for tabbing between fields.

---

core/field_dropdown.ts

This PR fixes an error when calling `validateOptions` in node/non-browser environments. This is the same fix as used in https://github.com/google/blockly/pull/9048, just targeting another place where the root issue occurred in the same file.

fix: Fix bug when referencing HTMLElement in non-browser environments.

---

core/utils/dom.ts

This PR removes a cast that could cause errors at runtime on environments without Canvas support, such as JSDom.

fix: Remove un-typesafe cast.

---

core/keyboard_nav/field_navigation_policy.ts

This PR fixes an issue that prevented fields that were clickable/interactable but not editable from being visited via keyboard navigation.

fix: Make clickable but non-editable fields navigable.
